### ISSUE TITLE
OpenSSL version error not correct.

### ISSUE THREAD

**Issue by gnif** [openresty/lua-nginx-module#1000]
Nginx reports this at runtime if the OpenSSL version is too old:

`2017/02/28 20:39:54 [emerg] 25466#25466: at least OpenSSL 1.0.2e required but found OpenSSL 1.0.1t  3 May 2016`

Upgrading the package on the system has no effect as Ngnix is checking the version it was compiled against, not the version that is installed. This error should state this instead, perhaps:

`Nginx was compiled with OpenSSL x, but requires at least 1.0.2e`

**Comment by agentzh** [comment]
@gnif Yes. It's checking the compiled version of OpenSSL, obviously.

I agree it's better to say "at least OpenSSL 1.0.2e required but OpenSSL 1.0.1t is compiled in". Mind to propose a pull request for this change? Thanks!

**Comment by agentzh** [comment]
@gnif The current message is ambiguous but not incorrect. It's really talking about finding openssl in the current process space.

**Comment by gnif** [comment]
@agentzh You are correct, it is talking about finding OpenSSL on the system, but the test is invalid as it is checking against the version it was compiled against. After upgrading libssl and verifying it was loaded by Nginx by use of `ldd` and `strace` Nginx was still showing the same error.

**Comment by BenMorganIO** [comment]
Hey guys,

I currently have `OpenSSL 1.0.1t  3 May 2016` which is, as apt is telling me, the latest version. Should I downgrade my OpenSSL to get rid of this error message?

**Comment by agentzh** [comment]
@gnif @BenMorganIO I suggest you guys just use the official OpenResty pre-built packages and package repositories:

https://openresty.org/en/linux-packages.html

It's highly recommended.

**Comment by BenMorganIO** [comment]
@agentzh I tried, however I wasn't able to provide any further since I'm on Raspbian.

```
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

**Comment by agentzh** [comment]
@BenMorganIO Hmm, maybe you can just use our prebuilt deb packages for Debian jessie. Maybe you can even reuse the same APT repository too.

Just try this command instead on your Raspbian jessie:

```
sudo add-apt-repository -y "deb http://openresty.org/package/debian jessie openresty"
```

**Comment by agentzh** [comment]
@BenMorganIO Let me know if it works. If it works, I'll add the instructions for Raspbian jessie to the official documentation.

**Comment by BenMorganIO** [comment]
@agentzh Sorry, it didn't seem to work :(

```
$ sudo add-apt-repository -y "deb http://openresty.org/package/debian jessie openresty"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

**Comment by BenMorganIO** [comment]
It looks like it's just searching for a `Raspbian/jessie`. Do you know of a way I could trick it to grab the Ubuntu one?

**Comment by agentzh** [comment]
@BenMorganIO OK, I was an idiot. Raspberry Pi uses an ARM CPU. Our existing prebuilt packages are for Intel's CPU. It'll never work. So the best way for now is just to build the deb packages using our packaging source for Debian yourself on Raspbian:

https://github.com/openresty/openresty-packaging

We may offer an official APT repository for Raspbian in the future.

**Comment by agentzh** [comment]
@BenMorganIO Or you can just follow the instructions in the official documentation for building from OpenResty's source package:

https://openresty.org/en/installation.html
