### ISSUE TITLE
how use the ssl_session_fetch_by_lua_file and ssl_session_store_by_lua_file to do (distributed) caching of SSL sessions

### ISSUE THREAD

**Issue by xusong** [openresty/lua-nginx-module#1003]
i want to speed up for https with 4 openresty as group, there is a problem ,ssl_session need to be shared in openresty group , i find 2 directives , ssl_session_fetch_by_lua_file and ssl_session_store_by_lua_file , but do not know how it is for use , someone know this ?
wait for your help, thank you!

---------------------
This hook, together with the ssl_session_store_by_lua* hook, can be used to implement distributed caching mechanisms in pure Lua (based on the cosocket API, for example). If a cached SSL session is found and loaded into the current SSL connection context, SSL session resumption can then get immediately initiated and bypass the full SSL handshake process which is very expensive in terms of CPU time.
---------------------

**Comment by fankeke** [comment]
I have a quick question ,where is your redis_cluster from? There is not a official redis cluster client for OR  now .

**Comment by xusong** [comment]
@fankeke  there is , but not a official redis cluster client

**Comment by fankeke** [comment]
@xusong  
From the information you post, problem maybe occur in your rediscluster client. 
Give your rediscluster  client infomation.

**Comment by xusong** [comment]
@fankeke  find it , missing patch for openssl 
see https://openresty.org/en/installation.html
-------------------------------------------------------
If you prefer building the OpenSSL and PCRE dependencies from their source tarballs, then you could follow the commands below (you may want to change the version number accordingly):

wget https://www.openssl.org/source/openssl-1.0.2j.tar.gz
tar -zvxf openssl-1.0.2j.tar.gz
cd openssl-1.0.2j/
patch -p1 < /path/to/openresty/patches/openssl-1.0.2h-sess_set_get_cb_yield.patch
cd ..
