### ISSUE TITLE
ngx.req.set_header headers not being proxied to origin server

### ISSUE THREAD

**Issue by ledzepp4eva** [openresty/lua-nginx-module#1004]
* nginx version: nginx/1.10.3
* CentOS Linux release 7.3.1611 (Core)
* /root/rpmbuild/BUILD/lua-nginx-module-0.10.7

Running the following lua 
<pre>
header_filter_by_lua_block {
    if ngx.req.http_version() == 1 then
      ngx.req.set_header("Via", "1.0 name")
    elseif ngx.req.http_version() == 2 then
      ngx.req.set_header("Via", "2.0 name")
   elseif ngx.req.http_version() == 1.1 then
      ngx.req.set_header("Via", "1.1 name")
   else
      ngx.exit(ngx.HTTP_FORBIDDEN)
    end
   }
    proxy_pass          http://x.x.x.x;
    proxy_redirect      off;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    Connection "";
    proxy_set_header    Host $http_host;
    proxy_http_version  1.1;
    proxy_pass_header Server;

</pre>

I can see this is working, as logging the $http_via variable is giving me the following in the logs:
<pre>
y.y.y.y - - [06/Mar/2017:15:22:28 +0000] "GET / HTTP/1.1" 301 185 "-" "curl/7.29.0" "-" MISS 0.038 80 - - y.y.y.y example.org "x.x.x.x:80" "301" "0.038" "185""1.1 name"
</pre>

But on the backend server I can't see that header and I am also unable to see it in tcpdump. So it looks like the header isn't being processed in the proxy_pass. please tell me I have done something silly?

Liam

**Comment by spacewander** [comment]
`header_filter_by_lua*` will run after Nginx's content phase. In this case it is after backend server process the request.

If you want to pass the header in `proxy_pass`, you can use `access_by_lua*`, which will run before content phase.

**Comment by ledzepp4eva** [comment]
@spacewander as I thought I was being stupid. Thank you.
