### ISSUE TITLE
Failed to parse the output of "nginx -V"

### ISSUE THREAD

**Issue by linyang02** [openresty/lua-nginx-module#1007]
I am using Test::Nginx to test my nginx modules, but when I run the .t files. I get the output "mixed.t .. Bailout called.  Further testing stopped:  Failed to parse the output of "nginx -V": Project : Pr-nginx
FAILED--Further testing stopped: Failed to parse the output of "nginx -V": Project : Pr-nginx". Who can help me?

**Comment by agentzh** [comment]
@linyang02 Seems like you are creating the issue in the wrong repository. Test::Nginx has its own test-nginx code repository.

Regarding your issue, well, apparently `Test::Nginx` does not know about `Pr-nginx`. It only knows about `nginx` and `openresty` BTW.
