### ISSUE TITLE
cannot convert from 'ngx_chain_t' to 'ngx_buf_t *

### ISSUE THREAD

**Issue by ddatsh** [openresty/lua-nginx-module#1008]
nginx commit  
Converted hc->busy/hc->free to use chain links.
https://github.com/nginx/nginx/commit/fca26c2e53d46549320a3b23ce0398c5921348dd

lua-nginx-module/src/ngx_http_lua_headers.c(151): error C2440: '=': cannot convert from 'ngx_chain_t' to 'ngx_buf_t *'
lua-nginx-module/src/ngx_http_lua_headers.c(227): error C2440: '=': cannot convert from 'ngx_chain_t' to 'ngx_buf_t *'

**Comment by agentzh** [comment]
@ddatsh This is a backward incompatible change in the latest nginx core. I'd rather wait for it to get included in a mainline nginx release before we take any actions.

**Comment by centminmod** [comment]
looks to be included now :)
