### ISSUE TITLE
about exit_by_lua

### ISSUE THREAD

**Issue by RocFang** [openresty/lua-nginx-module#1010]
hello, @agentzh  @doujiang24  etc.

How do you like the idea of adding the feature of "exit_by_lua/exit_process_by_lua" just like "init_by_lua/init_worker_by_lua"?

In some scenarios, we need to do some work when the processes(worker, master) exits. At present, this can only be done when QUIT signal has been received. But in reality, restart or kill operations are quite common too.

**Comment by thibaultcha** [comment]
Hi,

Have you seen #927? It is currently under review.

**Comment by RocFang** [comment]
@thibaultcha 
wow,  thanks for that, I have only checked the issues just now.

**Comment by RocFang** [comment]
Close the issue. Thank @thibaultcha  again.
