### ISSUE TITLE
the problem of ngx.req.set_uri used in content_by_lua*

### ISSUE THREAD

**Issue by dth801** [openresty/lua-nginx-module#1014]
nginx.conf:

> location /hello {
        default_type 'text/html';
        content_by_lua '
            ngx.req.set_uri("/php", true)
        ';  
    }   
    location /php {
        default_type 'text/html';
        echo I am PHP;
    }

get http://xxx.com/hello/aaccc
http_code 500
errlog:
> [error] 7650#0: *7075766 lua entry thread aborted: runtime error: content_by_lua(lua.conf:43):2: API disabled in the context of content_by_lua*
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        content_by_lua(lua.conf:43):2: in function <content_by_lua(lua.conf:43):1>, client: 10.235.54.40, server: xxx, request: "GET /hello/aaccc HTTP/1.1", host: "xxx.com"

**Comment by detailyang** [comment]
Hello.

@dth801 

Try this as the following:
```bash
        location /hello {
                default_type 'text/html';
                rewrite_by_lua_block {
                        ngx.req.set_uri("/php", true)
                }
        }
        location /php {
                default_type 'text/html';
                echo I am PHP;
        }
```

And It looks like document at [ngxreqset_uri](https://github.com/openresty/lua-nginx-module#ngxreqset_uri) is wrong for context. I will fix it after creating new PR.

**Comment by dth801** [comment]
@detailyang  I saw it now, thank you.
