### ISSUE TITLE
Add support for LuaJIT's GC64 mode

### ISSUE THREAD

**Issue by agentzh** [openresty/lua-nginx-module#1019]
LuaJIT has recently added support for the new GC64 mode which allows the full low 47-bit address space to be used by LuaJIT's GC-managed memory.

It seems that this module requires some changes regarding light userdata to actually support this GC64 mode:

http://www.freelists.org/post/luajit/fix-lightud-type-for-48bit-virtual-address

https://github.com/LuaJIT/LuaJIT/pull/230#issuecomment-260205661

**Comment by xch91** [comment]
Appreciate the effort! Would love to know roughly which version is going to include the fix. Thank you.

**Comment by agentzh** [comment]
@spacewander Patches welcome.

**Comment by spacewander** [comment]
Let me repost the discussion in elsewhere:
1. With LuaJIT in GC64 mode, all test cases pass in x64 platform.
2. However, there is a problem with lightuserdata in ARM64 and simillary platform. See the detail in https://github.com/openresty/lua-nginx-module/issues/1152.
3. GC64 mode slightly drops performance for CPU-bound task.

**Comment by agentzh** [comment]
We already have #1152 for ARM64 + GC64. We can close this.

**Comment by agentzh** [comment]
Noted one segmentation fault when running lua-resty-core's test suite with LuaJIT GC64:

https://github.com/openresty/lua-resty-core/issues/144

**Comment by pavelnemirovsky** [comment]
Hi,
We are trying to test openresty-1.11.2.5-2.el6.x86_64 with -DLUAJIT_ENABLE_GC64 to have bigger GC size and seeing very confusing behavior of the code that worked fine before this change like:

2017/09/26 07:55:08 [error] 31426#31426: *10548 lua entry thread aborted: runtime error: /path/adutils.lua:193: bad argument #1 to 'string_char' (invalid value)
stack traceback:
coroutine 0:
	[C]: in function 'string_char'
	/path/adutils.lua:193: in function 'createRandString'
	/path/adutils.lua:204: in function 'getEnc'
	/path/demands/info.lua:254: in function 'encode_cpm'
	/path/get_player_app_core.lua:1328: in function 'getPlayerApp'
	/path/get_player_app.lua:5: in function </path/get_player_App.lua:1>, client: 170.51.33.76, server: *.algovid.com, request: "GET /player/app?p=123321312&d=com.cleanmaster.mguard&sid=com.cleanmaster.mguard&pv=111.13&w=300&h=250&f=0&dd=ads.mopub.com&vs=1&sa=hha&&loclong=-57.989958100000003&loclat=-34.944766600000001  325 HTTP/1.1", host: "s1.algovid.com", referrer: "http://ads.mopub.com/"

**Comment by agentzh** [comment]
@pavelnemirovsky Please do not cross post. It's annoying. Thanks for your cooperation.
