### ISSUE TITLE
Are double quotes here [--with-ld-opt="-Wl,-rpath,/path/to/luajit-or-lua/lib" \] a must?

### ISSUE THREAD

**Issue by Sauraus** [openresty/lua-nginx-module#1022]
Wanted to clarify the documentation in the README.MD here on GitHub, it has double quotes around this.

`--with-ld-opt="-Wl,-rpath,/path/to/luajit-or-lua/lib" \`

However building without those double quotes also works fine, so are they really needed or is this just a little dirt in the docs?

**Comment by detailyang** [comment]
Hello
@Sauraus agree with you. It just pass the option to linker and I think it is no need to use double quotes.

**Comment by agentzh** [comment]
@Sauraus Double quotes there are handy when the user wants to add more linker options. Not a must, but good to have.

**Comment by detailyang** [comment]
BTW, the gcc doc said using comma split syntax can pass multiple options as the following:

>Pass option as an option to the linker. If option contains commas, it is split into multiple options at the commas. You can use this syntax to pass an argument to the option. For example, -Wl,-Map,output.map passes -Map output.map to the linker. When using the GNU linker, you can also get the same effect with -Wl,-Map=output.map.

**Comment by agentzh** [comment]
@detailyang I mean something like this:

```
--with-ld-opt="-Wl,-rpath,/foo -L/foo/bar/ -L/baz -lxxx"
```

**Comment by detailyang** [comment]
@agentzh  Got you :smile:

**Comment by Sauraus** [comment]
@agentzh agreed about the use case of " but is this the right place to educate or otherwise inform people about how to go about linker options?

I am fine with either way it just seems out of place that's all.

**Comment by thibaultcha** [comment]
It's always good to show best and/or un-opinionated practices in your documentation, regardless of its scope, or so I would think.

**Comment by Sauraus** [comment]
Just to follow up on this, having the `"` in the ld options causes the lua library to be rebuilt every time as reported here https://github.com/chef-cookbooks/chef_nginx/issues/86, removing the `"` ensures the lua library is not rebuilt if the source doesn't change.

**Comment by agentzh** [comment]
@Sauraus Double quotes must be special in your chef configuration syntax, otherwise it won't make any difference in a normal shell.

**Comment by agentzh** [comment]
@Sauraus If you want to avoid rebuilding everything from scratch, then you shouldn't invoke `./configure` everytime. Instead, after the first-time `./configure` invocation, you should only run `make` every time you change something. It is `make` handling incremental build while `./configure` always initiates a complete rebuild.

**Comment by Sauraus** [comment]
AFAIK `./configure` is idempotent just like `make` is if nothing changes and thus becomes a `NOP`. However the fact remains that with the `"` in the `ld` options the library will be rebuilt every single time, whereas if the `"` is left away this does not happen, no matter how many times `./configure` is called.

Is this perhaps some undocumented side-effect of `"` on `ld` that causes the rebuild?

**Comment by agentzh** [comment]
@Sauraus Your shell should interpret `"`, which should never passed down to `ld` at any rate. `./configure` always starts rebuilding from scratch otherwise your toolchain tries to do anything clever (and thus non-standard). I won't follow this conversation any more.
