### ISSUE TITLE
Logging does not work properly

### ISSUE THREAD

**Issue by yharish991** [openresty/lua-nginx-module#1023]
`ngx.NOTICE, ngx.INFO`logging levels don't work.. but the other loggings levels like `ngx.STDERR, ngx.EMERG, ngx.ALERT, ngx.CRIT, ngx.ERR` work.

is it a bug/know issue?

**Comment by agentzh** [comment]
@yharish991 Check your `error_log` configuration directive. You may just be filtering lower log level messages yourself in your `nginx.conf`.

**Comment by yharish991** [comment]
Thanks for the quick reply? That is true there was a filter in the `error_log` directive. Thanks for the help really appreciate it.
