### ISSUE TITLE
Build error with nginx-1.10.3

### ISSUE THREAD

**Issue by azuryyu** [openresty/lua-nginx-module#1026]
Lua:    lua-5.1.5
Nginx:nginx-1.10.3
lua-nginx-module-0.10.7

Build error:
lua-nginx-module-0.10.7/src/ngx_http_lua_module.c: In function ‘ngx_http_lua_merge_srv_conf’:
/root/software/nginx/lua-nginx-module-0.10.7/src/ngx_http_lua_module.c:1017:37: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type [-Werror]
                                     ngx_http_lua_ssl_sess_fetch_handler);
                                     ^
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:83,
                 from /root/software/nginx/lua-nginx-module-0.10.7/src/ddebug.h:13,
                 from /root/software/nginx/lua-nginx-module-0.10.7/src/ngx_http_lua_module.c:11:
/root/software/nginx//openssl-1.1.0e/.openssl/include/openssl/ssl.h:621:6: note: expected ‘struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)’ but argument is of type ‘struct SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^
cc1: all warnings being treated as errors

**Comment by detailyang** [comment]
Hello
@azuryyu Now It isn't compatible with OpenSSL 1.1.0+ and Can you try OpenResty on [openresty.org/en/download.html](https://openresty.org/en/download.html) ?

**Comment by azuryyu** [comment]
Thanks for the quick response. I'll try.

**Comment by agentzh** [comment]
This is definitely a duplicate ticket for #922.
