### ISSUE TITLE
Build broken after LuaJIT commit dc320ca

### ISSUE THREAD

**Issue by nzt4567** [openresty/lua-nginx-module#1029]
LuaJIT commit dc320ca removes some old Lua 5.0 compatibility defines, including `luaL_getn` which is required for lua-nginx-module. Hotfixed by returning the define but that's not probably the right way to do it ;)

**Comment by agentzh** [comment]
@nzt4567 Yeah, this ngx_lua module should use `lua_objlen` instead. Mind to propose a pull request for this change? Thanks for the report!

**Comment by centminmod** [comment]
yup seems ran into this as well

```
       -o objs/addon/src/ngx_http_lua_headers.o \
       ../lua-nginx-module-0.10.7/src/ngx_http_lua_headers.c
../lua-nginx-module-0.10.7/src/ngx_http_lua_headers.c: In function ‘ngx_http_lua_ngx_header_set’:
../lua-nginx-module-0.10.7/src/ngx_http_lua_headers.c:721:13: error: implicit declaration of function ‘luaL_getn’ [-Werror=implicit-function-declaration]
        n = luaL_getn(L, 3);
            ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
make[1]: Leaving directory `/svr-setup/nginx-1.11.10'
make: *** [build] Error 2
```

**Comment by agentzh** [comment]
@dndx Will you take care of this? Thanks!

**Comment by dndx** [comment]
@agentzh On it

**Comment by dndx** [comment]
Thanks for reporting @nzt4567 @centminmod 

Also fixed the build failure of `lua-cjson` due to similar change.

https://github.com/openresty/lua-cjson/issues/21
https://github.com/openresty/lua-cjson/pull/22

**Comment by nzt4567** [comment]
Sorry guys, ongoing vacation is keeping me away from the keyboard most of the time ;) Thanks @dndx @agentzh
