### ISSUE TITLE
openresty compile error with Libressl 

### ISSUE THREAD

**Issue by AnoopAlias** [openresty/lua-nginx-module#1035]
Getting the following error on compiling with LibreSSL

```
        -o objs/addon/src/ngx_http_lua_ssl_ocsp.o \
        ../ngx_lua-0.10.7/src/ngx_http_lua_ssl_ocsp.c
../ngx_lua-0.10.7/src/ngx_http_lua_ssl_ocsp.c: In function ‘ngx_http_lua_ffi_ssl_set_ocsp_status_resp’:
../ngx_lua-0.10.7/src/ngx_http_lua_ssl_ocsp.c:493:13: error: ‘SSL’ has no member named ‘tlsext_status_expected’
     ssl_conn->tlsext_status_expected = 1;
             ^
../ngx_lua-0.10.7/src/ngx_http_lua_ssl_ocsp.c: At top level:

```

LIBRESSL_VERSION="2.5.2"
OPENRESTY_VERSION="1.11.2.2"

**Comment by agentzh** [comment]
@AnoopAlias Maybe you should try the latest master instead?

BTW, some important `ngx_lua` SSL features are not available when building with libressl and libressl is not an officially supported target of this module. You are at your own risk. The libressl library is not officially meant to be used by 3rd-party applications as a standalone SSL library anyway.

**Comment by nonchip** [comment]
@AnoopAlias in case you still need this, i'm currently using a workaround like this: https://github.com/cuddlyrobot/dysnomia/blob/5cdacf0644bb06369c4bfb6c288da9d18f4b5f93/setup.zsh#L63
