### ISSUE TITLE
Nginx 1.12.0 (lua module v.0.10.8) Compilation Error 

### ISSUE THREAD

**Issue by Senset** [openresty/lua-nginx-module#1040]
Hello!
I got that problem when compiling:

> lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c: In function ‘ngx_http_lua_ngx_req_raw_header’:
> lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c:151:15: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’ (b = hc->busy[i];)
> lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c:227:15: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’ (b = hc->busy[i];)

What I doing wrong or it wait for fix?

**Comment by hilyjiang** [comment]
+1

**Comment by spacewander** [comment]
Duplicate https://github.com/openresty/lua-nginx-module/issues/1016

**Comment by Senset** [comment]
Ok, closed as duplicate
