### ISSUE TITLE
Fail to make with nginx-1.12.0

### ISSUE THREAD

**Issue by artnurr** [openresty/lua-nginx-module#1043]
Can't add module to nginx-1.12.0.
incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
Error with v0.10.7 and v0.10.8 versions

**Comment by agentzh** [comment]
@artnurr Why don't you try the latest git master branch?

**Comment by artnurr** [comment]
I try latest release from https://github.com/openresty/lua-nginx-module/releases

**Comment by GreenSuslik** [comment]
I'm to

**Comment by agentzh** [comment]
@artnurr You have to use the latest master for now.

**Comment by artnurr** [comment]
When you planned next release?

**Comment by agentzh** [comment]
@artnurr At least one month away. Since a new release is just out.
