### ISSUE TITLE
Build Instructions documentation out of date.

### ISSUE THREAD

**Issue by impetodira** [openresty/lua-nginx-module#1045]
Current version of README says to run ./configure there is no 'configure' file.  There is a 'config' file but it has no #!/bin/sh or #!/bin/bash type line for the correct interperter.   The documentation also references Lua 5.1, seems like 5.2 ought to be supported by now.

**Comment by agentzh** [comment]
@impetodira You are not looking carefully enough. It's talking about the `./configure` script of the nginx source distribution.
