### ISSUE TITLE
lua entry thread aborted: runtime error

### ISSUE THREAD

**Issue by cjhust** [openresty/lua-nginx-module#1046]
version old： lua-nginx-module-0.10.5, not support session_fetch and session_store
version new:  lua-nginx-module-0.10.7, support session_fetch and session_store

step 1:  just replace lua file,  there is following errors:  (version old)

2017/04/19 18:23:18 [error] 3191336#0: lua entry thread aborted: runtime error: /usr/local/marco/nginx//app/lib/ngx/session.lua:73: /usr/local/marco/luajit/lib/libluajit-5.1.so.2: undefined symbol: ngx_http_lua_ffi_ssl_get_session_id_size

step2:  kill -USR2 

undefined symbol: ngx_http_lua_ffi_ssl_get_session_id_size  disappear

**Comment by agentzh** [comment]
@cjhust The `ngx_http_lua_ffi_ssl_get_session_id_size` function is defined in the ngx_http_lua module. It's obviously your own setup problem. Have I told you to use the OpenResty release to save troubles in the official documentation of this module?

**Comment by cjhust** [comment]
I don't understand，no kill -HUP, just replace lua file, how happen？

**Comment by cjhust** [comment]
@cjhust The ngx_http_lua_ffi_ssl_get_session_id_size function is defined in the ngx_http_lua module. It's obviously your own setup problem. Have I told you to use the OpenResty release to save troubles in the official documentation of this module?

send me the document link? thanks

**Comment by agentzh** [comment]
@cjhust https://github.com/openresty/lua-nginx-module/#installation

To quote:

"It is highly recommended to use the OpenResty bundle that bundles Nginx, ngx_lua, LuaJIT 2.0/2.1 (or the optional standard Lua 5.1 interpreter), as well as a package of powerful companion Nginx modules. The basic installation step is a simple command: ./configure --with-luajit && make && make install."

**Comment by agentzh** [comment]
@cjhust Okay, I just updated that documentation section to reflect the current status:

```
It is highly recommended to use OpenResty releases which integrate Nginx, ngx_lua, LuaJIT 2.1, as well as other powerful companion Nginx modules and Lua libraries. It is discouraged to build this module with nginx yourself since it is tricky to set up exactly right. Also, the stock nginx cores have various limitations and long standing bugs that can make some of this modules' features disabled, not work properly, or slower.
```

**Comment by cjhust** [comment]
we all upgrade, thanks very much.
the reason of the issue is that before replaycing the lua files there is no traffic to set out the ssl_session_fetch_*
