### ISSUE TITLE
in nginx proxy_cache with slice, using ngx.location.capture will get error

### ISSUE THREAD

**Issue by gwy8868** [openresty/lua-nginx-module#1047]
in nginx proxy_cache with slice, if response is cached and response size is more than slice size, use ngx.location.capture in rewrite_by_lua or access_by_lua, it will get error "[error] 55987#0: *4 unexpected range in slice response".

**Comment by agentzh** [comment]
@gwy8868 I think this is a limitation officially documented:

https://github.com/openresty/lua-nginx-module/#locations-configured-by-subrequest-directives-of-other-modules

This limitation applies here since the standard `slice` nginx modules does use subrequests itself.

**Comment by gwy8868** [comment]
@agentzh I think it is maybe not about that. The ngx.location.capture directive can get right result (with ngx.HTTP_GET method). This error occurs in the process of slice nginx module after ngx.location.capture.

It is maybe the bug of the standard slice nginx module. From the official change log of nginx 1.11.13, we can see that it modified the bug about slice nginx module. After I modified the bug to the nginx of OpenResty, the error not happen again.

**Comment by agentzh** [comment]
@gwy8868 OK, glad you resolved it.

**Comment by gwy8868** [comment]
reference: https://github.com/nginx/nginx/commit/8c9a66298c627ed4eae2557b322c3f33da97eca4
