### ISSUE TITLE
How do I know that the current request is PHP

### ISSUE THREAD

**Issue by p0nley** [openresty/lua-nginx-module#1058]
How do I know that the current request is php

忽略掉静态资源请求

**Comment by detailyang** [comment]
Hello @p0nley 

The HTTP Request and Response is the stream of binary. And you question actually is that which request is requesting the css、js、image and so on resource.  In fact there is no type on HTTP Request and Response.  However, you can define the "type" according the request URL、Method、Header. 

To your question,  it's a good way (tricks) to identify "静态资源" by distinguishing the URL prefix like "/statc/xxx" or suffix like "\.(jpg|css|js)$" or the "Content-Header: Accept" setting by browser.

Also we suggest you learn something about  [HTTP/1.1 Protocol](https://www.w3.org/Protocols/rfc2616/rfc2616.html)

BTW, Consider closed.

**Comment by p0nley** [comment]
i see, thanks @detailyang
