### ISSUE TITLE
File descriptor increases continuously when lua_code_cache is off

### ISSUE THREAD

**Issue by jonas0616** [openresty/lua-nginx-module#1064]
When `lua_code_cache` is `off`, fd which points to error.log increases continuously for workers.

```
$ ll /proc/{worker_pid}/fd/
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 14 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 2 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 28 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 30 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 33 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 35 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 37 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 39 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 42 -> /var/log/nginx/error.log
l-wx------ 1 ubuntu ubuntu 64 May  8 06:43 44 -> /var/log/nginx/error.log
...
```
Under observation, fd is increased by two after serving each request.
Eventually, the limit of open files is reached, and the worker will be no longer able to accept requests.
However, it printed nothing to error.log during serving requests.

The openresty version is:
```
./nginx -v
nginx version: openresty/1.11.2.1
```

**Comment by agentzh** [comment]
@jonas0616 You know that you should never ever use `lua_code_cache off` in production, right?

Regarding the file descriptor issue, it looks strange, will you provide a minimal and standalone example that can easily reproduce the problem on our side?

**Comment by jonas0616** [comment]
@agentzh I do understand `lua_code_cache off` should not be used is production. This setting exists in development environment only.

After some experiments and observation, I can reproduce by the following simplified scripts:
Entry script:
```
#!/usr/bin/env lua
local Geo = require "MyGeo"
```

MyGeo.lua:
```
#!/usr/bin/env lua
local geoip_country = require "geoip.country"

local GeoIp = {
    db_country = geoip_country.open("/usr/share/GeoIP/GeoIP.dat")
}

return GeoIp
```

The geoip module is 
```
# luarocks show lua-geoip

lua-geoip 0.1.2-1 - Bindings for MaxMind's GeoIP library

License:        MIT/X11
Homepage:       http://github.com/agladysh/lua-geoip
Installed in:   /usr/local

Modules:
        geoip.country
        geoip
        geoip.city
```

I don't know who takes the blame of this issue, nginx-lua-module or lua-geoip.

**Comment by agentzh** [comment]
Seems like it's lua-geoip library that leaks the file descriptors. We do not support this library on our side.

If you still believe it's a problem of our module, please provide a minimal and standalone example *without* any 3rd-party Lua libraries that are not maintained by us.

**Comment by jonas0616** [comment]
Thanks for your explanation. I will report this issue to lua-geoip.
