### ISSUE TITLE
How to log POST body but limit length?

### ISSUE THREAD

**Issue by FrancisHe** [openresty/lua-nginx-module#1065]
My project support both POST and GET method for most API, parameters in body for POST request and in URL for GET request. I want to log parameters both POST and GET request, $request_body can solve this problem. But some API has long data in body, so I want limit the $request_body length in access_log, is there a good solution?

**Comment by spacewander** [comment]
@FrancisHe 
First of all, you should ask your question in OpenResty's mail list:
https://github.com/openresty/lua-nginx-module#community

You can customize the access log format. Like this:
```
    log_format custom $request_body_head;

    server {
        location /test {
            set $request_body_head '';
            access_log logs/access.log custom;
            content_by_lua_block {
                ngx.req.read_body()
                -- Just a example
                local body = ngx.req.get_body_data()
                ngx.var.request_body_head = body:sub(1, 16)
            }
        }
```

**Comment by FrancisHe** [comment]
@spacewander Thanks a lot, it‘s a good solution and it's exactly what I want.

**Comment by tangjn** [comment]
Becarefull don't log username and password.

**Comment by spacewander** [comment]
@agentzh 
Consider it resolved?
