### ISSUE TITLE
error loading module 'lpeg' from file ... undefined symbol: lua_tointegerx

### ISSUE THREAD

**Issue by camstuart** [openresty/lua-nginx-module#1067]
Hi,

My environment is:
`Ubuntu 16.04`
`nginx version: openresty/1.11.2.3`
`Lua 5.2.4`
`luarocks 2.4.2`

My installation of `openresty/nginx` is local to my user account, and I have installed the `lua` module `http` with: `luarocks install http --local`

So when launching, I populate the `LUA_PATH` and `LUA_CPATH` environment variables according to the output provided by: `luarocks path --bin` 

My `lua` script at this stage is very simple:

```lua
content_by_lua_block {
    local redis = require "resty.redis"
    local http_request = require "http.request"
    local red = redis:new()

    red:set_timeout(5000)

    local ok, err = red:connect("127.0.0.1", 6379)
    if not ok then
        ngx.say("failed to connect: ", err)
        return
    end
}
```

And the error I get is:

```log
2017/05/12 14:54:44 [error] 96391#0: *4 lua entry thread aborted: runtime error: content_by_lua(authenticate.lua:17):3: loop or previous error loading module 'http.request'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(authenticate.lua:17):3: in function <content_by_lua(authenticate.lua:17):1>, client: 127.0.0.1, server: , request: "GET /auth HTTP/1.1", host: "localhost:8080"
```

It seems a problem with the `http` module, and indeed commenting out the `require` stops the error.

Any idea what's going wrong here?

My end goal here is to be able to unpack http headers

**Comment by agentzh** [comment]
@camstuart You know that the `http.request` Lua module from luarocks will block the nginx event loop unless it utilizes openresty's cosocket API for network I/O?

**Comment by agentzh** [comment]
@camstuart The error log message you quoted is not the first error message, but just a consequence of the previous error. So it is not really helpful for debugging the problem.

**Comment by agentzh** [comment]
@camstuart You should really use one of those lua-resty-http libraries out there for OpenResty. See

http://opm.openresty.org/

And this is also why we created opm in the first place. 90%+ of the Lua modules on luarocks will block OpenResty's event loop and ruin the performance.

**Comment by agentzh** [comment]
@camstuart Your Lua 5.2.4 item listed is also strange. OpenResty comes with its own LuaJIT and only works with the Lua 5.1 *language* and ABI.

**Comment by camstuart** [comment]
Ok, thanks @agentzh that's a lot to take in. I just tried to use:

```lua
local http = require "resty.http"
```
But it looks like I will need to use `opm` to install it.... trying now

**Comment by camstuart** [comment]
Ok, I managed to install with `opm --cwd get agentzh/lua-resty-http`

And that has created for me: `/home/cameron/sde/openresty-auth/resty_modules`

Containing:

```
.
├── lualib
│   └── resty
│       ├── http_headers.lua
│       └── http.lua
├── manifest
│   ├── lua-resty-http.list
│   └── lua-resty-http.meta
├── pod
│   └── lua-resty-http-0.09
│       └── lua-resty-http-0.09.pod
└── resty.index
```

To load, should I be using:

`lua_package_path "/home/cameron/sde/openresty-auth/resty_modules/lualib/resty/?.lua;;";` ?

**Comment by agentzh** [comment]
@camstuart See https://github.com/openresty/opm#global-installation

**Comment by camstuart** [comment]
Fantastic, thanks @agentzh all working now.

**Comment by agentzh** [comment]
@camstuart I made more edits to that doc section now. Ensure you have not hard-coded the absolute paths in the nginx configuration file.

**Comment by agentzh** [comment]
@camstuart `$prefix` variable is meaningful to OpenResty and you are not supposed to edit it.
