### ISSUE TITLE
Variable not change value after access_by_lua

### ISSUE THREAD

**Issue by lebanggit** [openresty/lua-nginx-module#1068]
I have this config:

server
{
       listen 8080;
      location /
      {
            default_type 'text/plain';
            set $myvar "Hello";
            access_by_lua '
            ngx.var.myvar = "Hello, This is Lua value"
            ngx.say(ngx.var.myvar)
            ';
            add_header Server-logs $myvar;
      }
}

In the results: Server-logs in the header still "Hello"

Please tell me why?

**Comment by agentzh** [comment]
@lebanggit I tried your example on my side with the latest OpenResty and it works as expected when testing with curl:

```
$ curl -i localhost:8080
HTTP/1.1 200 OK
Server: openresty/1.11.2.4rc0.1
Date: Sun, 14 May 2017 21:22:18 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server-logs: Hello, This is Lua value

Hello, This is Lua value
```

**Comment by agentzh** [comment]
@lebanggit I guess it is because of the comma character (`,`) used in your header value. Commas are special in header values. They are used to separate multiple header values. Better avoid it.

**Comment by agentzh** [comment]
@lebanggit BTW, you may want to use `access_by_lua_block` instead of `access_by_lua` nowadays.
