### ISSUE TITLE
ngx.req.set_uri and uri escaping

### ISSUE THREAD

**Issue by bungle** [openresty/lua-nginx-module#1069]
Right now `ngx.req.set_uri` wants to have the `uri` in `unescaped` form. That's perfectly fine, but it seems that Nginx does escaping differently compared to `lua-nginx-module` (see: `ngx.escape_uri`).

One concrete example of this is represented here:
https://github.com/Mashape/kong/pull/2519/files

(scroll to the bottom to see the actual failing test that shows that the escaping is different in Nginx and `lua-nginx-module`).

Couple of workarounds:

* try to deal this on your own (maybe implementing a more transparent **un**escaping that works similarly to Nginx)
* ask here for help / possible enhancements (e.g. an argument to `set_uri` e.g. `ngx.set_uri(uri, jump?, already_escaped?)`)

**Comment by agentzh** [comment]
@bungle Well, we should just follow the RFC instead of doing something strange here. Just my 2 cents.

**Comment by thibaultcha** [comment]
I don't think we are doing anything particularly strange or out of the ordinary. Here is a simple use case:

```nginx
    server {
        listen 8080;

        location / {
            content_by_lua_block {
                ngx.say(ngx.var.request_uri)
            }
        }
    }

    server {
        listen 8888;

        location / {
            access_by_lua_block {
                ngx.req.set_uri("/auth%7C123")
                --ngx.req.set_uri(ngx.unescape_uri("/auth%7C123"))
            }

            proxy_pass http://127.0.0.1:8080;
        }
    }
```

Now if we hit it:
```bash
http :8888
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 14
Content-Type: text/plain
Date: Mon, 15 May 2017 22:16:43 GMT
Server: openresty/1.11.2.2

/auth%257C123
```

This shows that the upstream server (8080) received a double percent-encoded URI.

As reported in that PR that @bungle linked to, `ngx.req.set_uri()` sets the `internal` field of the `ngx_http_request_t` struct, as we can see [here](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_uri.c#L93). This causes ngx_http_proxy_module to escape (hence, double-escape) the URI when proxying.

If we uncomment the second line which unescapes the `$request_uri` before proxying (which seems like a waste of CPU cycles), we receive:
```bash
http :8888
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 10
Content-Type: text/plain
Date: Mon, 15 May 2017 22:18:38 GMT
Server: openresty/1.11.2.2

/auth|123
```

Which seems to indicate that Nginx and ngx_lua's escaping/unescaping do not encode the same sets of characters.

**Comment by agentzh** [comment]
@thibaultcha The `ngx.req.set_uri()` accepts the raw URI data, not encoded ones. So `%` will surely get escaped. This is by design. It would be a bug if it did not escape `%` in the value.

**Comment by thibaultcha** [comment]
Yes, that makes sense. What we're wondering is if this behavior should be made configurable, or, if we perform the (wasteful) `ngx.unescape_uri()`, it could encode the URI in such a way that `|` is percent-encoded as well.

**Comment by agentzh** [comment]
@thibaultcha I'm not sure what exactly you are suggesting. Are you suggesting a `ngx.req.set_unparsed_uri()` API function here? We definitely cannot make `ngx.req.set_uri()` accept already encoded URIs, since it just makes no sense. But for `ngx.req.set_unparsed_uri()`, we also need to decide whether we should update `r->uri` and `r->args` at the same time as changing `r->unparsed_uri`. And the proxy module may still favor `r->uri` when `r->uri` is diverged from `r->unparsed_uri`, resulting in zero gain.

**Comment by thibaultcha** [comment]
We're not sure how to handle this either tbh. I think the expectation is that when OpenResty/Nginx is used as a transparent reverse proxy, the upstream URI is identical as the one received from the client:
```
/auth%7C123 -> OpenResty -> /auth%7C123 -> upstream
```

However, the current options make proxying less transparent:
```
/auth%7C123 -> OpenResty -> /auth%257C123 -> upstream
```

Even if we do:
```lua
ngx.req.set_uri(ngx.var.uri)) -- use the decoded URI
```

We still have a divergence:
```
/auth%7C123 -> OpenResty -> /auth|123 -> upstream
```

Granted, `|` is not in the reserved sets of characters. Maybe our users ought not to expect it to be sent upstream percent-encoded... It is still a pain point/un-intuitive for them that URIs are not transparently proxied. 

I think @bungle opened this issue rather seeking for council/possibly raising awareness about the behavior, and possibly discussing if a new API would make sense at all.

**Comment by thibaultcha** [comment]
Maybe I'll spend some time investigating ngx_http_proxy_module to see if `ngx.req.set_unparsed_uri()` would make any sense at all, if we are not sure.

**Comment by agentzh** [comment]
@thibaultcha I think what you really need here is just to detect whether the URI is already URI-encoded or not. You can simply use `string.find()` to search `%` in the string for that. This is VERY efficient, especially when the `string.find()` call is JIT compiled.

**Comment by bungle** [comment]
@agentzh in this case we perfectly know that `$request_uri` Is the raw uri from the client and it might contain percent encodings. What we want is that the upstream server would have the equal `$request_uri`. But because all this unescaping and escaping it seems some (non rfc and questionable) encodings are lost in process making the upstream to receive a slightly different `$request_uri` than what the reverse proxy received.

I do think this is related to this:
http://stackoverflow.com/questions/28684300/nginx-pass-proxy-subdirectory-without-url-decoding/37584637#37584637

**Comment by bungle** [comment]
One note though, we might strip the prefix from the `$request_uri` and that is basically why we do call `set_uri`.

**Comment by agentzh** [comment]
@bungle This looks like a hack :)

**Comment by tokers** [comment]
@agentzh  Maybe we can invoke the `ngx_http_parse_unsafe_uri` in `ngx_http_lua_ngx_req_set_uri` ？

**Comment by agentzh** [comment]
@tokers No, it looks wrong to me. As I said, the input has to be the original form, not an encoded form. This is by design for `ngx.req.set_uri()`. No exceptions.

**Comment by bungle** [comment]
What would be the `non-hack` version of it (a solution)? Just guidance that this is not possible (e.g. if you have escaped non-rfc chars, those might get changed to non-escaped)?

**Comment by agentzh** [comment]
@bungle The thing is that we should only support RFC-compliant behaviors in the core, not working around non-RFC-compliant code on this level. The latter should be kept on the higher level.

**Comment by agentzh** [comment]
@bungle The real thing here is how `ngx_proxy` module handles your particular requirements. We should not hack `ngx.req.set_uri()` just to please `ngx_proxy`. Those are two different things.

**Comment by bungle** [comment]
Yes, I agree 100%. I will study other solutions, e.g. we could possibly change the `proxy_pass` to contain the `location` (or the possibly modified value of `$request_uri`) but I have not yet tested it yet.

**Comment by tokers** [comment]
@agentzh OK, i see, we can just do the encode(if need) on the higher land.

**Comment by bungle** [comment]
@agentzh ok, on our side we decided to append the url and the args to the `proxy_pass` as described in my comment above (a slightly modified version of that idea to fit our use case). I will close this now, because at least we have a workaround.

**Comment by czjxy881** [comment]
It seems can use ndk.set_var.set_unescape_uri now ? [Document](https://github.com/openresty/lua-nginx-module#ndkset_vardirective)
