### ISSUE TITLE
socket.http load localhost failed

### ISSUE THREAD

**Issue by lebanggit** [openresty/lua-nginx-module#1070]
I have nginx config bellow:

```Lua
server
{
	listen 80;
	server_name backend;
	root            /home/nginx/public_html/backend/;
}
server
{
	listen 80;
	server_name frontend;
	location /
	{
		default_type  'text/html';
		access_by_lua_block
		{
			ngx.say('Hello, this is Lua')
			local http = require("socket.http")
			url = 'http://backend'
			--url = 'http://www.google.com'
			response = http.request(url)
			ngx.say(response)
		}
	}
}
```
http.request work fine with url is google.com or other sites hosted on diffrent server. But with the http://backend, it not working.

On nginx error.log no info of this problem.

On browser status, Its loading on the long time and nginx server seems crash.

On three days testing. I don't known what is happening.

Please help me.

**Comment by agentzh** [comment]
@lebanggit Do not use the LuaSocket library in OpenResty. It will BLOCK the nginx event loop on network I/O and ruin your OpenResty's performance.

**Comment by agentzh** [comment]
@lebanggit Use http libraries based on OpenResty's cosocket API instead, like `lua-resty-http`.

**Comment by agentzh** [comment]
@lebanggit Regarding your question, you should make sure `resolver` directive is properly pointed to a DNS server that can resolve names like `backend` used in your examples.

**Comment by agentzh** [comment]
The `/etc/hosts` file is usually not supported since it relies on the system resolver which is always blocking.
