### ISSUE TITLE
Status on 1.11.11+ support

### ISSUE THREAD

**Issue by StephanDollberg** [openresty/lua-nginx-module#1071]
What's the status on 1.11.11+ support?

While https://github.com/openresty/lua-nginx-module/commit/0459a285ca0159d45e73da8bd1164edb5c57cde3 makes it build the commit mentions that 1.11.11+ is not yet supported.

Where can I track progress on that?

**Comment by agentzh** [comment]
@StephanDollberg You can track the progress here:

https://qa.openresty.org/

Once it starts to officially support nginx 1.13.x, you'll see the test results for nginx 1.13.x there.

**Comment by spacewander** [comment]
@agentzh 
We could close this issue now, since Nginx 1.13.x is already supported.

**Comment by agentzh** [comment]
@spacewander Right. Closing.
