### ISSUE TITLE
[discussions] Tests about iscribblet.org and g.sregex.org

### ISSUE THREAD

**Issue by detailyang** [openresty/lua-nginx-module#1072]
Now the OR's tests is based on [https://iscribblet.org](https://iscribblet.org) and [https://g.sregex.org](https://g.sregex.org). Unfortunately their SSL certificate now is expired. So we should rewrite these tests about [https://iscribblet.org](https://iscribblet.org) and [https://g.sregex.org](https://g.sregex.org) or report the certificate issue to  [https://iscribblet.org](https://iscribblet.org) and [https://g.sregex.org](https://g.sregex.org) ?

**Comment by agentzh** [comment]
@detailyang Yeah, I was aware of this. Thanks for the report. I'll renew the SSL certificates for these 2 sites ASAP. Sorry for the inconvenience.

**Comment by detailyang** [comment]
glad to know :)
