### ISSUE TITLE
[PR proposal] customize stack level of ngx.log API

### ISSUE THREAD

**Issue by thibaultcha** [openresty/lua-nginx-module#1074]
It's quite common to develop an OpenResty application/framework/library, and create logging facilities. Some more or less complex, but here is a very basic example:

```lua
local function log(lvl, ...)
    ngx.log(lvl, "[my namespace] ", ...)
end
```

Now one can call this function like so:

```lua
local ok, err = thing()
if not ok then
    log(ngx.ERR, "could not do X: ", err)
end
```

This is very convenient for various reasons. However, it's harder to debug since the `ngx.log()` API uses the current stack level, and hence, the developer/sysadmin sees this:

error.log:
```
[error] 5226#0: *25 [lua] my_file.lua:3: log(): [my namespace] could not do X: reason
```

I propose that instead, we allow for a lvl argument to the `ngx.log()` API, while still maintaining backwards-compatibility. Something like:

```lua
local s_lvl = ngx.log_lvl(2) -- just like error("thing", 2)

local function log(lvl, ...)
    ngx.log(lvl, s_lvl, "[my namespace] ", ...) -- 2nd arg can be some userdata with the stack level in it
end
```

And this will print the stacktrace info from the caller (correct line number and caller function name):

```
[error] 5226#0: *25 [lua] my_file.lua:20: [my namespace] could not do X: reason
```

It'd be my pleasure to propose a PR for this. Do we have thoughts, concerns, or other plans about it?

**Comment by agentzh** [comment]
@thibaultcha I think you can just use the standard Lua debug API to fetch the upper level frame's Lua source location yourself?

I don't like the `lvl` thing in your proposal I'm afraid. It looks weird.

**Comment by thibaultcha** [comment]
> I think you can just use the standard Lua debug API to fetch the upper level frame's Lua source location yourself?

Sure, but then the logging facility of ngx_lua will still print undesired information about the current level, so it looks more like a hack than a real solution.

> I don't like the lvl thing in your proposal I'm afraid. It looks weird.

Would happily implement another solution to this, but since backwards compatibility is, I am certain, quite the concern here (and this is a variadic function, unlike Lua's `error()`), I'm not sure how else to do that.

**Comment by agentzh** [comment]
@thibaultcha I think we can just add a raw error logger API to the new `ngx.errlog` Lua module in lua-resty-core. This raw error logger adds no Lua source location prefixes and can be even JIT compiled by LuaJIT itself. Then it is easier for users to add custom wrappers with whatever extra debugging info to the log message. Does it sound good?

**Comment by thibaultcha** [comment]
@agentzh Oh, I had a strong hunch you were going to suggest such a lua-resty-core implementation ;) Yeah, that sounds good.

**Comment by agentzh** [comment]
@thibaultcha LOL. Pull requests welcome! Thanks!

**Comment by spacewander** [comment]
@agentzh 
Consider it resolved?

**Comment by thibaultcha** [comment]
@spacewander thanks! Closing it since the `rawlog` API now exists for this use-case!
