### ISSUE TITLE
ngx_http_slice_filter_module would lead to Resuming broken transfer mistakes

### ISSUE THREAD

**Issue by toints** [openresty/lua-nginx-module#1075]
In nginx version 1.10.3, when I opened slice module, I use "Range" and "If-Range" for Resuming broken transfer, it should response with ` 206 Partial Content` in a normal way, but it indeed returns with `200 OK`. And if closed this module , everything is OK.

**Comment by agentzh** [comment]
@toints I don't understand how you combine the slice module and the lua module. Your description is very vague.

**Comment by toints** [comment]
@agentzh  I use nginx as a Reverse Proxy Server, and use lua module in access phase and header filter phase. Slice module mainly for splitting big size file. I think there is probably a bug in slice module .

**Comment by agentzh** [comment]
@toints The slice module initiates subrequests which can have problems with the ngx_lua module. See

https://github.com/openresty/lua-nginx-module/#locations-configured-by-subrequest-directives-of-other-modules
