### ISSUE TITLE
lua_shared_dict is atomic?

### ISSUE THREAD

**Issue by monolithh** [openresty/lua-nginx-module#1076]
i have 40 nginx worker which using 1 lua_shared_dict. i need know which lockings used in lua_shared_dict if they are used. if locking are used when nginx worker do set method - which it is lock? key? or table? whats happened when 2 workers at the same time try to set key? 

I need to know if there is CPU overload when all 40 workers using 1 shared dict and call set method and get method very often

**Comment by monolithh** [comment]
i tried to google it, tried to find answer on github, but no luck.

**Comment by agentzh** [comment]
@monolithh Every method directly exposed by the shdict object is atomic.

**Comment by monolithh** [comment]
@agentzh thanks for quick answer. how you think is this possible to overload CPU when 40 workers using shared_dict and they often using set/get method?

**Comment by agentzh** [comment]
@monolithh When spinlocks expire, it falls back to semaphore. And for the latter, there is no CPU usage.

**Comment by agentzh** [comment]
@monolithh Whether lock contention will be a problem highly depends on your data set and use cases. Usually it's not a problem since the locks only protect *pure memory* accesses. No syscalls, no I/O.

**Comment by agentzh** [comment]
@monolithh You have to do benchmark for your dataset and use cases yourself. Otherwise it just does not make much sense.
