### ISSUE TITLE
how to read frames from websocket not create by lua-resty-websocket

### ISSUE THREAD

**Issue by liguanquan** [openresty/lua-nginx-module#1082]
Hi is websocket not create by lua-resty-websocket can read like 
content_by_lua '
               ngx.req.read_body()

**Comment by agentzh** [comment]
@liguanquan You should use the `resty.websocket.server` module in the `lua-resty-websocket` library instead.

BTW, you are filing tickets in the wrong repository. It really belongs to

https://github.com/openresty/lua-resty-websocket

**Comment by liguanquan** [comment]
thx a lot
