### ISSUE TITLE
separator in ngx.log

### ISSUE THREAD

**Issue by tokers** [openresty/lua-nginx-module#1083]
When using `ngx.log` like this

```lua
ngx.log(ngx.ERR, "host", "127.0.0.1", "port", 80)
```

We will get `"host127.0.0.1port80"`, it is unreadable, most of the time we need to add a separator manually like 

```lua
ngx.log(ngx.ERR, "host", " ", "127.0.0.1", " ", "port", " ", 80)
```
So my problem is, why not just add a separator in `ngx.log` through a directive or a optional argument? this is more convenient.

**Comment by spacewander** [comment]
Maybe you could implement your log formatter just with Lua code.
It would be more flexible.

**Comment by rainingmaster** [comment]
`ngx.log` just prove a tool to log, mayby you can add a function like this:
```
local function format_log(...)
	local info = { ... }
	ngx.log(ngx.ERR, table.concat(info, " "))
end
```

**Comment by tokers** [comment]
@spacewander @rainingmaster 
All right, it's a good idea format my logs on the Lua hand.
