### ISSUE TITLE
Global shared.DICT

### ISSUE THREAD

**Issue by sdmrnv** [openresty/lua-nginx-module#1086]
Hello!

I used ngx.shared.DICT for sharing (cache) data inside 1 nginx server. But is there method/technique in this module to share data between 2 remote NGINX servers? Something like shared.dict for 2 remotely computers: 1 comp put data into  DICT and another can read this data value from this global DICT...

Regards,
Sergey

**Comment by agentzh** [comment]
@sdmrnv No. Shared memory zones cannot span across multiple machines. It will require socket communications anyway. You should implement that yourself atop cosockets.
