### ISSUE TITLE
Build failed with libssl-dev 

### ISSUE THREAD

**Issue by midorinet** [openresty/lua-nginx-module#1088]
Tried using libssl-dev 1.1.0e-2 on Debian Stretch, but failed with the following

`        /usr/local/src/lua-nginx-module/src/ngx_http_lua_regex.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_UPSTREAM_LIST  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/ngx_devel_kit-0.3.0rc1/objs -I objs/addon/ndk -I /usr/local/src/lua-nginx-module/src/api -I /usr/local/src/nginx-push-stream-module/src -I /usr/local/src/nginx-push-stream-module/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I /usr/local/src/ngx_devel_kit-0.3.0rc1/src -I /usr/local/src/ngx_devel_kit-0.3.0rc1/src -I /usr/local/src/ngx_devel_kit-0.3.0rc1/objs -I objs/addon/ndk -I /usr/include/luajit-2.0 -I src/stream \
        -o objs/addon/src/ngx_http_lua_module.o \
        /usr/local/src/lua-nginx-module/src/ngx_http_lua_module.c
/usr/local/src/lua-nginx-module/src/ngx_http_lua_module.c: In function 'ngx_http_lua_merge_srv_conf':
/usr/local/src/lua-nginx-module/src/ngx_http_lua_module.c:1022:37: error: passing argument 2 of 'SSL_CTX_sess_set_get_cb' from incompatible pointer type [-Werror=incompatible-pointer-types]
                                     ngx_http_lua_ssl_sess_fetch_handler);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:82,
                 from /usr/local/src/lua-nginx-module/src/ddebug.h:13,
                 from /usr/local/src/lua-nginx-module/src/ngx_http_lua_module.c:11:
/usr/include/openssl/ssl.h:621:6: note: expected 'SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, const unsigned char *, int,  int *)}' but argument is of type 'SSL_SESSION * (*)(SSL *, u_char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, unsigned char *, int,  int *)}'
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
objs/Makefile:1750: recipe for target 'objs/addon/src/ngx_http_lua_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx-1.12.0'
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 2`

Any fix?

**Comment by spacewander** [comment]
@midorinet
The support of OpenSSL 1.1.0 is still working in progress.
See #761 and #922.

**Comment by agentzh** [comment]
@midorinet Please consider using the official OpenResty deb packages for Debian stretch to avoid such incompatibilities and quirks:

http://openresty.org/en/linux-packages.html
