### ISSUE TITLE
nginx variables and init_by_lua*

### ISSUE THREAD

**Issue by silverwind** [openresty/lua-nginx-module#1089]
I'd like to set a variable during `init_by_lua*`, so I can assign the `resolver` option to the value of the variable. For this to work, one has to define the variable  through `set` as outlined in the docs:

````nginx
http {
  set $ips '';
  init_by_lua_block {
    ngx.var.ips = '1.2.3.4'
  }
  resolver $ips;
}
````
This results in the error
````
"set" directive is not allowed here
````
because nginx does not allow `set` in the `http` scope. Would it be possible to allow creation of variables during `init_by_lua*` so this issue can be avoided?

(I realize that there are workarounds available by moving the `resolver` directive into a `location`)

**Comment by spacewander** [comment]
IMHO, Nginx variable is associated with `ngx_http_request_t`. So it is nearly impossible to use variable without any request.

**Comment by silverwind** [comment]
Yes, it seems that nginx variables are too limited for my purpose.

As an alternative: Is it somehow possible to set configuration directives like `resolver` from Lua? I scanned the docs for the `ngx` API, but couldn't see anything suitable.

**Comment by spacewander** [comment]
@silverwind 
Dynamic resolver could be implemented via [lua-resty-dns](https://github.com/openresty/lua-resty-dns#synopsis).

**Comment by agentzh** [comment]
Right. NGINX variables do not even exist in the `init_by_lua*` phase. So this just does not make any sense. I'm closing this.

**Comment by silverwind** [comment]
> NGINX variables do not even exist in the init_by_lua* phase

Yes, but that's a stupid limitation of nginx. What I'm asking is to access `http` and possibly `main ` level directives from within Lua. Or is that out of question?
