### ISSUE TITLE
body_filter_by_lua block's ngx.arg[1] could not return all response body value

### ISSUE THREAD

**Issue by yanmingbi** [openresty/lua-nginx-module#1092]
**Here is my exact version of the related software**
```
nginx1.10.2
lua-nginx-module 0.10.7
```

**Here is my code snippet**
```
	server {
		listen 8103;
		error_log /home/nginx1.10.2/logs/error.log debug;
		location / {
			body_filter_by_lua_block { 
				ngx.log(ngx.INFO,"ngx.arg[1]===========", ngx.arg[1])
				ngx.log(ngx.INFO,"ngx.arg[2]===========", ngx.arg[2])
			}
			proxy_pass http://test8103;
		}
	}
	upstream test8103 {
		server 172.16.49.39;
	}
```
**If I direct access http://172.16.49.39, Browser will receive follow response:**

> {"errCode":"000000","msg":"success","data":{"stockCode":"002054","name":" 德美化工 股票","announceItems":[{"type":"业绩大幅下降","summary":"净利润2000万元至4500万元,下降幅度为79.91%至54.79%","range":"-79.91","netProfit":"9953.11万","announceDate":"2017-04-25"},{"type":"预计扭亏","summary":"净利润0万元至500万元","range":"184.56","netProfit":"-591.29万","announceDate":"2017-03-31"},{"type":"业绩大幅下降","summary":"净利润13292万元至15092万元,下降幅度为55.79%至49.8%","range":"-55.79","netProfit":"2.85亿","announceDate":"2016-10-28"},{"type":"业绩大幅下降","summary":"净利润11000万元至14500万元,下降幅度为65.75%至54.86%","range":"-65.75","netProfit":"3.06亿","announceDate":"2016-08-27"},{"type":"业绩大幅下降","summary":"净利润7500万元至11000万元,下降幅度为70.2%至56.3%","range":"-70.20","netProfit":"2.52亿","announceDate":"2016-07-02"},{"type":"业绩大幅下降","summary":"净利润1000万元至4000万元,下降幅度为96.03%至84.11%","range":"-96.03","netProfit":"2.52亿","announceDate":"2016-04-27"},{"type":"业绩预亏","summary":"净利润-1000万元至-500万元","range":"-179.00","netProfit":"1265.79万","announceDate":"2016-04-01"},{"type":"业绩大幅上升","summary":"净利润27868.34万元至30741.37万元,增长幅度为191%至221%","range":"221.00","netProfit":"9576.76万","announceDate":"2016-01-30"},{"type":"业绩大幅上升","summary":"净利润32014.59万元至34887.61万元,增长幅度为234.00%至264.00%","range":"264.00","netProfit":"9576.76万","announceDate":"2015-10-31"},{"type":"业绩大幅上升","summary":"净利润30072.18万元至32194.92万元,增长幅度为325.00%至355.00%","range":"355.00","netProfit":"7075.81万","announceDate":"2015-08-29"},{"type":"业绩大幅上升","summary":"净利润24773.84万元至26176.14万元,增长幅度为430%至460%","range":"460.00","netProfit":"4674.31万","announceDate":"2015-07-08"},{"type":"业绩预降","summary":"净利润3272.02万元至4674.31万元,下降幅度为30%至0%","range":"-30.00","netProfit":"4674.31万","announceDate":"2015-04-29"},{"type":"业绩预降","summary":"净利润8061.01万元至11515.73万元,下降幅度为30%至0%","range":"-30.00","netProfit":"1.15亿","announceDate":"2014-10-30"},{"type":"业绩预降","summary":"净利润6298.91万元至8998.44万元,下降幅度为30%至0%","range":"-30.00","netProfit":"8998.44万","announceDate":"2014-08-27"},{"type":"业绩预降","summary":"净利润4175.89万元至5965.56万元,下降幅度为30%至0%","range":"-30.00","netProfit":"5965.56万","announceDate":"2014-04-29"},{"type":"业绩预增","summary":"净利润10865.52万元至14125.18万元,增长幅度为0%至30%","range":"30.00","netProfit":"1.09亿","announceDate":"2013-10-26"},{"type":"业绩大幅上升","summary":"净利润8092.90万元至9960.49万元,增长幅度为30%至60%","range":"60.00","netProfit":"6225.31万","announceDate":"2013-08-26"},{"type":"业绩大幅上升","summary":"净利润4602.28万元至5706.82万元,增长幅度为25%至55%","range":"55.00","netProfit":"3631.82万","announceDate":"2013-04-27"},{"type":"业绩大幅上升","summary":"净利润1563.03万元至1875.64万元,增长幅度为50%至80%","range":"80.00","netProfit":"1042.02万","announceDate":"2013-03-29"},{"type":"业绩预降","summary":"净利润8590.05万元至11453.4万元,下降幅度为40%至20%","range":"-40.00","netProfit":"1.43亿","announceDate":"2012-10-26"},{"type":"业绩大幅下降","summary":"净利润4987.79万元至7481.68万元,下降幅度为60%至40%","range":"-60.00","netProfit":"1.25亿","announceDate":"2012-08-29"},{"type":"业绩预降","summary":"净利润3289.4054万元至4111.7567万元,下降幅度为20%至0%","range":"-20.00","netProfit":"4111.76万","announceDate":"2012-07-13"}]}}

**but when I access http://127.0.0.1:8103 , check /home/nginx1.10.2/logs/error.log , I find body_filter_by_lua_block was called 4 times, and the first and second call are valid. Here is the logs from 
error.log :**

**The first call :**

```
2017/04/11 18:50:29 [info] 12510#0: *23 [lua] body_filter_by_lua:3: ngx.arg[1]==========={"errCode":"000000","msg":"success","data":{"stockCode":"002054","name":" 德美化工 股票","announceItems":[{"type":"业绩大幅下降","summary":"净利润2000万元至4500万元,下降幅度为79.91%至54.79%","range":"-79.91","netProfit":"9953.11万","announceDate":"2017-04-25"},{"type":"预计扭亏","summary":"净利润0万元至500万元","range":"184.56","netProfit":"-591.29万","announceDate":"2017-03-31"},{"type":"业绩大幅下降","summary":"净利润13292万元至15092万元,下降幅度为55.79%至49.8%","range":"-55.79","netProfit":"2.85亿","announceDate":"2016-10-28"},{"type":"业绩大幅下降","summary":"净利润11000万元至14500万元,下降幅度为65.75%至54.86%","range":"-65.75","netProfit":"3.06亿","announceDate":"2016-08-27"},{"type":"业绩大幅下降","summary":"净利润7500万元至11000万元,下降幅度为70.2%至56.3%","range":"-70.20","netProfit":"2.52亿","announceDate":"2016-07-02"},{"type":"业绩大幅下降","summary":"净利润1000万元至4000万元,下降幅度为96.03%至84.11%","range":"-96.03","netProfit":"2.52亿","announceDate":"2016-04-27"},{"type":"业绩预亏","summary":"净利润-1000万元至-500万元","range":"-179.00","netProfit":"1265.79万","announceDate":"2016-04-01"},{"type":"业绩大幅上升","summary":"净利润27868.34万元至30741.37万元,增长幅度为191%至221%","range":"221.00","netProfit":"9576.76万","announceDate":"2016-01-30"},{"type":"业绩大幅上升","summary":"净利润32014.59万元至34887.61万元,增长幅度为234.00%至264.00%","range":"264.00","netProfit":"9576.76万","announceDate":"2015-10-31"},{"type":"业绩大幅上升","summary":"净利润30072.18万元至32194.92万元,增长幅度为325.00%至355.00%","range":"355.00","netProfit":"7075.81万","announceDate":"2015-08-29"},{"type":"业绩大幅上升","summary":"净利润24773.84万元至26176.14万元,增长幅度为430%至460%","range":"460.00","netProfit":"4674.31
2017/04/11 18:50:29 [info] 12510#0: *23 [lua] body_filter_by_lua:4: ngx.arg[2]===========false while sending to client, client: 192.168.153.1, server: , request: "GET /industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054 HTTP/1.1", upstream: "http://172.16.49.39:80/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054", host: "192.168.153.136:8103"

```
**The second call :**
```
2017/04/11 18:50:29 [info] 12510#0: *23 [lua] body_filter_by_lua:3: ngx.arg[1]=========== while sending to client, client: 192.168.153.1, server: , request: "GET /industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054 HTTP/1.1", upstream: "http://172.16.49.39:80/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054", host: "192.168.153.136:8103"
2017/04/11 18:50:29 [info] 12510#0: *23 [lua] body_filter_by_lua:4: ngx.arg[2]===========true while sending to client, client: 192.168.153.1, server: , request: "GET /industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054 HTTP/1.1", upstream: "http://172.16.49.39:80/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054", host: "192.168.153.136:8103"
```
**We can see , in the first call ,the ngx.arg[1] are not complete response body, so the ngx.arg[1] of the 
second call should return the rest , but it returns nothing.**

**Maybe I forget to insert some directives into nginx.conf cause this problem.**

**Could you help me solve this problem ? Think you!**

**Comment by spacewander** [comment]
> I find body_filter_by_lua_block was called 4 times, and the first and second call are valid.
What about the third and fourth calls? Why are they invalid?

**Comment by spacewander** [comment]
BTW, the log of the first call is truncated, because the limit of Nginx log length. It doesn't have the correct HTTP tail.
So data have not been seen in the log doesn't mean data have not be transmited.
Could you paste the HTTP response from http://127.0.0.1:8103?

**Comment by hongliang5316** [comment]
@yanmingbi How do you know the `body_filter_by_lua_block` is called fourth times? According to your imformation, i think the `body_filter_by_lua_block` is called twice. Maybe the full response body is logged on the first call, but because of a hard coded 2048 byte limitation on error message lengths in the Nginx core, it didn't write to `error.log` completely. Maybe you can simplily log this to a file by `lua io` for verifing.

**Comment by agentzh** [comment]
@yanmingbi It's expected for the nginx response body filter to be called for multiple times for each data chunk of the response body for a single response. This is what is called streaming processing or non-buffered processing. Otherwise nginx response body filters cannot efficiently work with huge response body streams like giga bytes in length. BTW, this behavior is explicitly documented.

And yeah, as @spacewander, there is a length limit in nginx's error log messages, which is 2KB in the standard nginx core, and 4KB in OpenResty's nginx core.

**Comment by yanmingbi** [comment]
**@spacewander the third calls :**
```
2017/04/11 18:50:30 [info] 12510#0: *23 [lua] body_filter_by_lua:3: ngx.arg[1]===========<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /favicon.ico was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at test8103 Port 80</address>
</body></html>
 while sending to client, client: 192.168.153.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.49.39:80/favicon.ico", host: "192.168.153.136:8103", referrer: "http://192.168.153.136:8103/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054"
2017/04/11 18:50:30 [info] 12510#0: *23 [lua] body_filter_by_lua:4: ngx.arg[2]===========false while sending to client, client: 192.168.153.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.49.39:80/favicon.ico", host: "192.168.153.136:8103", referrer: "http://192.168.153.136:8103/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054"
```
**The fourth call:** 
```
2017/04/11 18:50:30 [info] 12510#0: *23 [lua] body_filter_by_lua:3: ngx.arg[1]=========== while sending to client, client: 192.168.153.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.49.39:80/favicon.ico", host: "192.168.153.136:8103", referrer: "http://192.168.153.136:8103/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054"
2017/04/11 18:50:30 [info] 12510#0: *23 [lua] body_filter_by_lua:4: ngx.arg[2]===========true while sending to client, client: 192.168.153.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.49.39:80/favicon.ico", host: "192.168.153.136:8103", referrer: "http://192.168.153.136:8103/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054"
```
**Because when I access http://127.0.0.1:8103/industry2/?iw-apikey=123&iw-cmd=10jqka_preannounceInfo&stockCode=002054&stockCode=002054 from browser, it will request a valid section of jsonString and request /favicon.ico. The second request invoke the third call and the fourth call as above. I think the second request has nothing to do with my question.**

-----------------------------------------------------------------------------
**I check the response from chrome browser, the HTTP response from http://127.0.0.1:8103?  and the HTTP response from http://172.16.49.39 is consistent and I already pasted in my first ask.**

**Comment by spacewander** [comment]
> I check the response from chrome browser, the HTTP response from http://127.0.0.1:8103? and the HTTP response from http://172.16.49.39 is consistent and I already pasted in my first ask.
It seems everything has passed through the body_filter.

As @hongliang5316 suggested, could you write `ngx.arg[1]` to a file? Then we could know whether the response data is actually lost.

**Comment by yanmingbi** [comment]
I follow @hongliang5316 suggestion to write ngx.arg[1] value into a file and the file exactly log all response body. So , I know as a length limit in nginx's error log messages cause my puzzle.
Think you very much. @spacewander @hongliang5316 @agentzh

**Comment by nemoyin** [comment]
local resp_body = string.sub(ngx.arg[1], 1, 1000)
   ngx.ctx.buffered = (ngx.ctx.buffered or "") .. resp_body
   if ngx.arg[2] then
       ngx.var.resp_body = ngx.ctx.buffered
   end
how can I get all response content if contains multiply trunks

**Comment by agentzh** [comment]
@nemoyin You shouldn't do that. All the point of an output filter in nginx is to do the data processing in a non-buffered fashion, which is crucial for processing HUGE response body data streams. If you do full buffering yourself in `body_filter_by_lua*`, then you may blow up the LuaJIT's GC-managed memory upon HUGE responses, and defeat all the purposes of nginx's output filter design.

This is officially documented already. I'm closing this.

**Comment by jitcoder** [comment]
@agentzh whats your alternative to capturing response body from proxy_pass?

**Comment by huweiqing915** [comment]
I met the same question too. I'm confused with why it called  body_filter_by_lua_block twice. 

nginx.conf:
server {
    ...
    body_filter_by_lua_block {
        ngx.log(ngx.INFO, "test")
    }
}

log:
2017/10/26 17:03:01 [info] 11009#0: *1 [lua] body_filter_by_lua:3: test while sending to client, client: xxx.xxx.xxx.xxx, server: , request: "GET /test/ HTTP/1.1", upstream: "http://xxx.xxx.xxx.xxx:80/test/", host: "xxx.xxx.xxx.xxx:8080"
2017/10/26 17:03:01 [info] 11009#0: *1 [lua] body_filter_by_lua:3: test while sending to client, client: xxx.xxx.xxx.xxx, server: , request: "GET /test/ HTTP/1.1", upstream: "http://xxx.xxx.xxx.xxx:80/test/", host: "xxx.xxx.xx.xxx:8080"

**Comment by agentzh** [comment]
@huweiqing915 You were not reading this thread. It's already answered above:

https://github.com/openresty/lua-nginx-module/issues/1092#issuecomment-309081761
