### ISSUE TITLE
nginx unknown directive “ssl_certificate_by_lua_block” error

### ISSUE THREAD

**Issue by lyenliang** [openresty/lua-nginx-module#1094]
Sorry in advance for asking this question, but I've been trapped in this problem for hours.

Does anyone know how to install `ssl_certificate_by_lua_block` directive?

The [install guide](https://barfi.gitbooks.io/lua-nginx-module/content/#installation) says that you just need to install [OpenResty](http://openresty.org/en/) and configure it with `./configure --with-luajit && make && make install`.

I just created a new ubuntu 14.04 virtual machine and installed OpenResty with

    sudo su -    
    export OPENRESTY_VERSION=1.9.15.1
    apt-get -y update && \
    apt-get -y install nginx-extras build-essential libpcre3-dev libssl-dev libgeoip-dev libpq-dev libxslt1-dev libgd2-xpm-dev && \
    apt-get -y install wget && \
    wget -c https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz && \ 
    tar zxvf openresty-${OPENRESTY_VERSION}.tar.gz && \ 
    cd openresty-${OPENRESTY_VERSION} && \
    ./configure --with-luajit && make && make install

Then I add 

    server {
        listen 443 ssl;
        server_name   test.com;

        ssl_certificate_by_lua_block {
            print("About to initiate a new SSL handshake!")
        }

        location / {
            root html;
        }
    }

in /etc/nginx/nginx.conf.

`nginx -t` then gives me a `nginx unknown directive “ssl_certificate_by_lua_block”` error.

Do I misunderstand the installation guide? Is there anything else I need to install?

My full configuration is listed on another [stackoverflow question](https://stackoverflow.com/questions/44612847/nginx-unknown-directive-ssl-certificate-by-lua-block-error). That configuration doesn't work, either.

**Comment by agentzh** [comment]
@lyenliang Will you just try the official OpenResty APT repo for Ubuntu 14.04? See

http://openresty.org/en/linux-packages.html

It's not easy to get it right yourself.

BTW, better use `ssl_certificate_by_lua*` in the `http {}` scope instead of in the `server {}` scope. We'll soon prohibit the use of this directive in the latter.

**Comment by lyenliang** [comment]
Thank you for your instant reply, I'll try.  :-)

**Comment by agentzh** [comment]
@lyenliang BTW, please make sure you are invoking `openresty` instead of `nginx` since you may have multiple different nginx binaries in your system. And apparently not every `nignx` is `openresty` :)

**Comment by agentzh** [comment]
@lyenliang BTW 2: 1.9.15.1 is ancient. We are at 1.11.2.3 right now and will soon get on to 1.11.2.4 :)

**Comment by thibaultcha** [comment]
Considering this answered (you were either mistakenly starting the wrong Nginx binary, or not compiling OpenResty right/not using an official release package). Closing this thread, thanks!
