### ISSUE TITLE
mute the init_by_lua logic when test config

### ISSUE THREAD

**Issue by RocFang** [openresty/lua-nginx-module#1096]
As a practical standard，every time we start nginx,  configuration should be tested using nginx -t.
However, in this mode ,the init_by_lua logic will execute. This behavior is not appropriate when init_by_lua involves some key preparation for a normal booting.

**Comment by agentzh** [comment]
@RocFang Well, we have actually been taking advantage of the current behavior to test any problems when (pre)loading the application Lua library modules. For example,

```
init_by_lua_block {
     require "myapp.foo"
     require "myapp.bar"
     require "myapp.baz"
}
```

So if any of these application modules fail to load, the test config can catch these errors.

**Comment by RocFang** [comment]
@agentzh  Thanks for the explanation，but in the scenarios i have mentioned, mybe it is not desirable,for example, blocking operations, shared dict operations and so on. And these operations can not be put into int_worker_by_lua context for their time-consuming feature.

Or, would you like to give some sugestions?

**Comment by agentzh** [comment]
@RocFang Blocking I/O operations are harmless in the `init_by_lua*` contexts since it's running in the master process. Regarding shdict initialization, I think you can simply set a flag in the shdict yourself to signal that the shdict has already been initialized by the previous `init_by_lua*` run.

**Comment by RocFang** [comment]
@agentzh  Thans for the  suggestions and i'll gladly take the second at once.
As for the blocking operations, mybe it's not blocking but just time-cosuming. when we put these kind of logic int init_by_worker context, there will be a  short period that nginx can not serve rightly when we relod nginx.

**Comment by agentzh** [comment]
@RocFang I don't understand why you want to reload nginx before your config test completes.

**Comment by agentzh** [comment]
@RocFang If you really want to bypass your init Lua code in config test, you can set an environment variable to your `nginx -t` or `openresty -t` command and check that environment in your init Lua handler.
