### ISSUE TITLE
How can ngx.shard.DICT fetch the key's ttl time

### ISSUE THREAD

**Issue by tokers** [openresty/lua-nginx-module#1101]
Hi!
Is there any way that i can get one key's ttl time in the NGINX shm when i using the ngx.shared.DICT?

**Comment by agentzh** [comment]
No, you can't at least for now.

**Comment by tokers** [comment]
@agentzh  Thanks your reply! is there any plan for it?

**Comment by thibaultcha** [comment]
This is now possible since #140 and we can close this issue.
