### ISSUE TITLE
Why not escape "|" on URI

### ISSUE THREAD

**Issue by toruneko** [openresty/lua-nginx-module#1103]
%7C can be unescape to "|"
but can not be escape to %7C

tomcat server (ver. 7.0.73) will be return 400 when url contains "|"

Why not escape "|" on URI?

**Comment by bungle** [comment]
Because it doesn't need to be escaped per RFC, see also:
https://en.wikipedia.org/wiki/Percent-encoding

Tomcat must be doing something wrong, and you may report that to Tomcat?

**Comment by toruneko** [comment]
But [RFC1728](http://www.ietf.org/rfc/rfc1738.txt) said that "|" is a unsafe character.
All unsafe characters must always be encoded within a URL.
@。@

**Comment by agentzh** [comment]
@toruneko I think there is a pending PR that fixes this and some other bytes. Will you dig up the pull request list?

**Comment by toruneko** [comment]
I got it [PR-542](https://github.com/openresty/lua-nginx-module/pull/542).
thanks @agentzh .

**Comment by agentzh** [comment]
@toruneko PR 542 is just merged with some minor tweaks.

**Comment by bungle** [comment]
@toruneko, thanks for corrections.

**Comment by bungle** [comment]
@toruneko, but you are referring to obsolete standard by the way. There is a more recent one.
