### ISSUE TITLE
rewrite_by_lua_block not executing the right url in proxy_pass

### ISSUE THREAD

**Issue by fjosimovski** [openresty/lua-nginx-module#1104]
I have an app that should redirect some of the apis to other backend app based on a parameter that is passed into the body.

I've setup the rewrite_by_lua_block and here is the code example below.

```
location /mylocation {
	resolver 8.8.8.8;
	set $backend_host "";
	lua_need_request_body on;
		rewrite_by_lua_block {
		-- Try POST first
		ngx.req.read_body();
		local args, err = ngx.req.get_post_args();
		local data = ngx.req.get_body_data();
		execute_proxy = false;
		appkey=args["appkey"];
		if (nil ~= appkey and appkey == "xxxxxx")
		then
			ngx.var.backend_host = "myfirsturl.com";
			execute_proxy = true;
		else
			ngx.var.backend_host = "mysecondurl.com"
		end
		if (true == execute_proxy)
		then
		local subreq_path = ngx.var.uri
		ngx.req.set_uri(subreq_path)
	end}
	proxy_pass https://$backend_host;
}
```

The issue i have is that it always doing proxy_pass to "mysecondurl.com". When i check the backend_host value it's always the one that it should be depending of the conditions.

If i do something like this, it's working too and it will redirect me to the changed backend_host.

```
location /mylocation {
	resolver 8.8.8.8;
	set $backend_host "mysecondurl.com";
	lua_need_request_body on;
		rewrite_by_lua_block {
		ngx.var.backend_host = "myfirsturl.com";
			
	end}
	proxy_pass https://$backend_host;
}
```
Can you please help me what could be the issue regarding this.
Thanks

**Comment by agentzh** [comment]
@fjosimovski I think you should just debug your own Lua code for it. It might just be taking the other Lua code path. You should check why your condition `nil ~= appkey and appkey == "xxxxxx"` is not evaluated to true.

BTW, if you believe there is an issue in this module, you should *minimize* your code example and also make your example *complete*. We do not have the resources to help debug your own Lua coding issues for free. Thanks for your understanding.

**Comment by agentzh** [comment]
Consider it resolved.
