### ISSUE TITLE
build of resty1.11.2.3 fails with libressl 2.5.4

### ISSUE THREAD

**Issue by nonchip** [openresty/lua-nginx-module#1105]
trying to build ngx_lua-0.10.8 (packaged in https://openresty.org/download/openresty-1.11.2.3.tar.gz) on void linux (64bit; glibc; gcc) using libressl 2.5.4 fails at:

    ../ngx_lua-0.10.8/src/ngx_http_lua_ssl_ocsp.c: In function 'ngx_http_lua_ffi_ssl_set_ocsp_status_resp':
    ../ngx_lua-0.10.8/src/ngx_http_lua_ssl_ocsp.c:493:13: error: 'SSL {aka struct ssl_st}' has no member named 'tlsext_status_expected'; did you mean 'tlsext_status_type'?
         ssl_conn->tlsext_status_expected = 1;
                 ^~
    make[2]: *** [objs/Makefile:2105: objs/addon/src/ngx_http_lua_ssl_ocsp.o] Error 1

checking (`less`ing) the `ssl.h` confirms there's no `tlsext_status_expected` in libressl (yet?).

note that it worked perfectly in the version shipped with at least 1.9.3.2 (the only version number i can confirm right now because i have a known working setup using it), but as far as i remember even late into 1.10.x versions.

**Comment by agentzh** [comment]
LibreSSL is never an officially supported target of OpenResty. Also libressl is not meant to be used by general 3rd part applications after all.

**Comment by nonchip** [comment]
and yes, i am aware of #1035, but, to quote your readme:

> It is highly recommended to use OpenResty releases which integrate Nginx, ngx_lua, LuaJIT 2.1, as well as other powerful companion Nginx modules and Lua libraries. It is discouraged to build this module with nginx yourself since it is tricky to set up exactly right. 

and since it did work...

**Comment by nonchip** [comment]
also, according to the changelogs on openresty.org, libressl was a target of API bugfixes.

see e.g https://openresty.org/en/changelog-1009007.html where another libressl incompatibility was fixed.

**Comment by nonchip** [comment]
also note that simply commenting out the offending line has no negative effects (since the value is only used by openssl, not your own code), so the fix should be as easy as wrapping that line in some `#ifdef` or similar

**Comment by nonchip** [comment]
current workaround on my end: https://github.com/cuddlyrobot/dysnomia/blob/5cdacf0644bb06369c4bfb6c288da9d18f4b5f93/setup.zsh#L63, but that just feels wrong.

**Comment by nonchip** [comment]
see latest workaround commit, you would simply need a `#ifdef LIBRESSL_VERSION_TEXT` to fix this

**Comment by agentzh** [comment]
@nonchip Well, I'm afraid you mix up two different things:

1. LibreSSL is not an officially supported target. This means that we do not officially test and guarantee it works in every new release of this module and OpenResty.
2. We *do* accept community patches to get the current version of the module to work with LibreSSL but we do not maintain the state ourselves in the future.

The same applies to our BoringSSL support.

Other projects use a similar policy as well, for example, the LuaJIT project does accept patches for the Cygwin toolchain but Cygwin is never an officially supported target of LuaJIT.

I hope I've got this clear enough for you.

At any rate, pull requests are very welcome to make this module compile with LibreSSL at any time.

**Comment by nonchip** [comment]
@agentzh yeah, that's why I wrote this ticket. I'm not complaining libressl doesn't work, I'm simply informing you while giving a solution. I'm not shouting at a support hotline, I'm pointing out a regress + possible fix in an open source project. anyway, yes, please expect a pull request for 2 lines of preprocessor code soon :P

**Comment by nonchip** [comment]
see #1107

**Comment by agentzh** [comment]
Already merged a different version of your change now.
