### ISSUE TITLE
Building fails on Arch

### ISSUE THREAD

**Issue by vercruyce** [openresty/lua-nginx-module#1110]
Hey,

I'm trying to build the module with the package provided on the [AUR](https://aur.archlinux.org/packages/nginx-mainline-mod-lua). However, I'm getting the following compilation error:

```
../lua-nginx-module-0.10.8/src/ngx_http_lua_ssl_ocsp.c: In function ‘ngx_http_lua_ffi_ssl_set_ocsp_status_resp’:
../lua-nginx-module-0.10.8/src/ngx_http_lua_ssl_ocsp.c:471:17: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
     if (ssl_conn->tlsext_status_type == -1) {
                 ^~
make[1]: *** [objs/Makefile:2254: objs/addon/src/ngx_http_lua_ssl_ocsp.o] Error 1
```
The error seems to suggest a problem with SSL, so:
```bash
$ openssl version
OpenSSL 1.1.0f  25 May 2017
```

Please do not hesitate to ask for further information.
Kind regards

**Comment by agentzh** [comment]
@vercruyce It's currently not compatible with OpenSSL 1.1.x. You need the OpenSSL 1.0.2 series for now.

**Comment by vercruyce** [comment]
You do not happen to have any experience with building it on arch?

**Comment by agentzh** [comment]
@vercruyce Well, it's still Linux. You should follow the installation instructions on the official web site:

http://openresty.org/en/installation.html

**Comment by alez007** [comment]
for some reason I'm having identical problem with the following configuration:
nginx 1.11.10
OpenSSL 1.0.1f 6 Jan 2014
lua-nginx-module v0.10.2

might not be related to 1.1.x openssl

**Comment by agentzh** [comment]
@alez007 Read the document: http://openresty.org/en/installation.html

**Comment by bjoe2k4** [comment]
I have compiled it on Arch some time ago (but after the openssl 1.1 switch). I have ended up using a dedicated openssl source tree:
```
cd /usr/local/src
git clone https://github.com/openssl/openssl.git
cd openssl
git checkout b3a3bab05ce32964ee32cbfe97cbe3edee5cf4a9

./configure  \
...
        --with-openssl=/usr/local/src/openssl \
...
```

Note that Tag https://github.com/openssl/openssl/commit/b3a3bab05ce32964ee32cbfe97cbe3edee5cf4a9 is the lastest 1.0.2 release tag.
