### ISSUE TITLE
luaL_newstate ??

### ISSUE THREAD

**Issue by ai930** [openresty/lua-nginx-module#1111]
----------------------------------------
checking for LuaJIT library in /usr/local/lib and /usr/local/include/luajit-2.1 (win32)

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
cl: 命令行 warning D9002 :忽略未知选项“-LG:/jlynetProject/jly-Tools/msys2-x86_64/usr/local/lib”
cl: 命令行 warning D9002 :忽略未知选项“-LG:/jlynetProject/jly-Tools/msys2-x86_64/usr/local/lib”
cl: 命令行 warning D9002 :忽略未知选项“-llua51”
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 _luaL_newstate，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

#include <lauxlib.h>

int main(void) {
    #if LUA_VERSION_NUM != 501
#   error unsupported Lua language version
#endif
(void) luaL_newstate();;
    return 0;
}

----------
cl -I/usr/local/include/luajit-2.1 -DFD_SETSIZE=1024 -I /usr/local/include/luajit-2.1 -o objs/autotest objs/autotest.c -L/usr/local/lib -L/usr/local/lib -llua51
----------

**Comment by agentzh** [comment]
@ai930 Maybe you just want to use the official Win32 binary for OpenResty? See

https://openresty.org/en/download.html#win32

Also, make sure you have read this documentation on how to use this and also how to rebuild it from source on Win32:

https://github.com/openresty/openresty/blob/master/doc/README-win32.md

Microsoft Visual C/C++ compilers are not officially supported yet though some users succeeded in doing it by hacking their own way through the code base and build system.
