### ISSUE TITLE
win 下用mingw32编译报少头文件

### ISSUE THREAD

**Issue by ai930** [openresty/lua-nginx-module#1112]
----------------------------------------
checking for C compiler

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 

----------------------------------------
checking for -Wl,-E switch

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
cl: 命令行 error D8021 :无效的数值参数“/Wl,-E”
----------

#include <sys/types.h>

int main() {
    ;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c -Wl,-E
----------

----------------------------------------
checking for gcc builtin atomic operations

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 ___sync_bool_compare_and_swap，该符号在函数 _main 中被引用
autotest.obj : error LNK2019: 无法解析的外部符号 ___sync_fetch_and_add，该符号在函数 _main 中被引用
autotest.obj : error LNK2019: 无法解析的外部符号 ___sync_synchronize，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 3 个无法解析的外部命令
----------

#include <sys/types.h>

int main() {
    long  n = 0;
                      if (!__sync_bool_compare_and_swap(&n, 0, 1))
                          return 1;
                      if (__sync_fetch_and_add(&n, 1) != 1)
                          return 1;
                      if (n != 2)
                          return 1;
                      __sync_synchronize();;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for C99 variadic macros

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 

----------------------------------------
checking for gcc variadic macros

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(5): error C2010: “.”: 宏形参表中的意外
----------

#include <sys/types.h>

#include <stdio.h>
#define var(dummy, args...)  sprintf(args)

int main() {
    char  buf[30]; buf[0] = '0';
                      var(0, buf, "%d", 1);
                      if (buf[0] != '1') return 1;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for gcc builtin 64 bit byteswap

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 ___builtin_bswap64，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

int main() {
    __builtin_bswap64(0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for unistd.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory
----------

#include <unistd.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for inttypes.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 

----------------------------------------
checking for limits.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 

----------------------------------------
checking for sys/filio.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “sys/filio.h”: No such file or directory
----------

#include <sys/filio.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sys/param.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “sys/param.h”: No such file or directory
----------

#include <sys/param.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sys/mount.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “sys/mount.h”: No such file or directory
----------

#include <sys/mount.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sys/statvfs.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “sys/statvfs.h”: No such file or directory
----------

#include <sys/statvfs.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt.h

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “crypt.h”: No such file or directory
----------

#include <crypt.h>

int main() {
    return 0;
}

----------
cl -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for poll()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “poll.h”: No such file or directory
----------

#include <sys/types.h>

#include <poll.h>

int main() {
    int  n; struct pollfd  pl;
                  pl.fd = 0;
                  pl.events = 0;
                  pl.revents = 0;
                  n = poll(&pl, 1, 0);
                  if (n == -1) return 1;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for /dev/poll

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/devpoll.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/devpoll.h>

int main() {
    int  n, dp; struct dvpoll  dvp;
                  dp = 0;
                  dvp.dp_fds = NULL;
                  dvp.dp_nfds = 0;
                  dvp.dp_timeout = 0;
                  n = ioctl(dp, DP_POLL, &dvp);
                  if (n == -1) return 1;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for kqueue

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/event.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/event.h>

int main() {
    int kq; kq = kqueue();
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 _crypt，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

int main() {
    crypt("test", "salt");;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt() in libcrypt

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
cl: 命令行 warning D9002 :忽略未知选项“-lcrypt”
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 _crypt，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

int main() {
    crypt("test", "salt");;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c -lcrypt
----------

----------------------------------------
checking for F_READAHEAD

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(7): error C2065: “F_READAHEAD”: 未声明的标识符
----------

#include <sys/types.h>

#include <fcntl.h>

int main() {
    fcntl(0, F_READAHEAD, 1);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for posix_fadvise()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(7): error C2065: “POSIX_FADV_SEQUENTIAL”: 未声明的标识符
----------

#include <sys/types.h>

#include <fcntl.h>

int main() {
    posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for O_DIRECT

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(7): error C2065: “F_SETFL”: 未声明的标识符
objs/autotest.c(7): error C2065: “O_DIRECT”: 未声明的标识符
----------

#include <sys/types.h>

#include <fcntl.h>

int main() {
    fcntl(0, F_SETFL, O_DIRECT);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for F_NOCACHE

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(7): error C2065: “F_NOCACHE”: 未声明的标识符
----------

#include <sys/types.h>

#include <fcntl.h>

int main() {
    fcntl(0, F_NOCACHE, 1);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for directio()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(5): fatal error C1083: 无法打开包括文件: “sys/fcntl.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/types.h>
                  #include <sys/fcntl.h>

int main() {
    directio(0, DIRECTIO_ON);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for statfs()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(9): error C2079: “fs”使用未定义的 struct“statfs”
----------

#include <sys/types.h>

                  
                  

int main() {
    struct statfs  fs;
                  statfs(".", &fs);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for statvfs()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(5): fatal error C1083: 无法打开包括文件: “sys/statvfs.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/types.h>
                  #include <sys/statvfs.h>

int main() {
    struct statvfs  fs;
                  statvfs(".", &fs);;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for dlopen()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “dlfcn.h”: No such file or directory
----------

#include <sys/types.h>

#include <dlfcn.h>

int main() {
    dlopen(NULL, RTLD_NOW | RTLD_GLOBAL); dlsym(NULL, NULL);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for dlopen() in libdl

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
cl: 命令行 warning D9002 :忽略未知选项“-ldl”
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “dlfcn.h”: No such file or directory
----------

#include <sys/types.h>

#include <dlfcn.h>

int main() {
    dlopen(NULL, RTLD_NOW | RTLD_GLOBAL); dlsym(NULL, NULL);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c -ldl
----------

----------------------------------------
checking for sched_yield()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 __imp__sched_yield，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

#include <sched.h>

int main() {
    sched_yield();
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sched_yield() in librt

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
cl: 命令行 warning D9002 :忽略未知选项“-lrt”
autotest.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:autotest.exe 
/out:objs/autotest.exe 
autotest.obj 
autotest.obj : error LNK2019: 无法解析的外部符号 __imp__sched_yield，该符号在函数 _main 中被引用
objs/autotest.exe : fatal error LNK1120: 1 个无法解析的外部命令
----------

#include <sys/types.h>

#include <sched.h>

int main() {
    sched_yield();
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c -lrt
----------

----------------------------------------
checking for SO_SETFIB

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for SO_REUSEPORT

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_REUSEPORT, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for SO_ACCEPTFILTER

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_RECVDSTADDR

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>

int main() {
    setsockopt(0, IPPROTO_IP, IP_RECVDSTADDR, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_PKTINFO

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>

int main() {
    setsockopt(0, IPPROTO_IP, IP_PKTINFO, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IPV6_RECVPKTINFO

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>

int main() {
    setsockopt(0, IPPROTO_IPV6, IPV6_RECVPKTINFO, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for TCP_DEFER_ACCEPT

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_DEFER_ACCEPT, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for TCP_KEEPIDLE

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_KEEPIDLE, NULL, 0);
                  setsockopt(0, IPPROTO_TCP, TCP_KEEPINTVL, NULL, 0);
                  setsockopt(0, IPPROTO_TCP, TCP_KEEPCNT, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for TCP_FASTOPEN

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_FASTOPEN, NULL, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for TCP_INFO

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    socklen_t optlen = sizeof(struct tcp_info);
                  struct tcp_info ti;
                  ti.tcpi_rtt = 0;
                  ti.tcpi_rttvar = 0;
                  ti.tcpi_snd_cwnd = 0;
                  ti.tcpi_rcv_space = 0;
                  getsockopt(0, IPPROTO_TCP, TCP_INFO, &ti, &optlen);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for accept4()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/socket.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/socket.h>

int main() {
    accept4(0, NULL, NULL, SOCK_NONBLOCK);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for eventfd()

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/eventfd.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/eventfd.h>

int main() {
    (void) eventfd(0, 0);
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for eventfd() (SYS_eventfd)

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(4): fatal error C1083: 无法打开包括文件: “sys/syscall.h”: No such file or directory
----------

#include <sys/types.h>

#include <sys/syscall.h>

int main() {
    int n = SYS_eventfd;
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for int size

用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24210 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
autotest.c
objs/autotest.c(3): fatal error C1083: 无法打开包括文件: “sys/time.h”: No such file or directory
----------

#include <sys/types.h>
#include <sys/time.h>

#include <signal.h>
#include <stdio.h>
#include <sys/resource.h>
#include <inttypes.h>

int main() {
    printf("%d", (int) sizeof(int));
    return 0;
}

----------
cl -DFD_SETSIZE=1024 -o objs/autotest objs/autotest.c
----------

**Comment by agentzh** [comment]
@ai930 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your issue, the Microsoft C/C++ compiler is not an officially supported toolchain for OpenResty yet though some developers fought their way through and got it compiled with nontrivial changes in the code base and the build system.

I'm closing this.
