### ISSUE TITLE
nginx.1.13.3 :/src/ngx_http_lua_headers.c:151: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'

### ISSUE THREAD

**Issue by 358235737** [openresty/lua-nginx-module#1117]
HI : again
                /wls/appsystems/nginx/nginxmodule/luamodule/lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c
/wls/appsystems/nginx/nginxmodule/luamodule/lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c: In function 'ngx_http_lua_ngx_req_raw_header':
/wls/appsystems/nginx/nginxmodule/luamodule/lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c:151: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
/wls/appsystems/nginx/nginxmodule/luamodule/lua-nginx-module-0.10.8/src/ngx_http_lua_headers.c:227: error: incompatible types when assigning to type 'struct ngx_buf_t *' from type 'ngx_chain_t'
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
make[1]: Leaving directory `/wls/appsystems/nginx/sourcefile/nginx-1.13.3'
make: *** [build] Error 2

**Comment by spacewander** [comment]
@358235737 
You should search before submitting a new issue.
Duplicate with https://github.com/openresty/lua-nginx-module/issues/1051

**Comment by 358235737** [comment]
Use the master branch of this module. sorry~！
