### ISSUE TITLE
access_by_lua_block and nginx return

### ISSUE THREAD

**Issue by erankor** [openresty/lua-nginx-module#1119]
Hi @agentzh,

Bumped into something a bit un-intuitive and wanted to check if that's the expected behavior or some kind of bug - issue is reproduced with the following test config:
```
                location = /lua1 {
                        access_by_lua_block {
                                ngx.log(ngx.ERR, "return")
                        }
                        return 200 "return";
                }

                location = /lua2 {
                        access_by_lua_block {
                                ngx.say("ngx.say")
                                ngx.log(ngx.ERR, "ngx.say")
                        }
                }
```
Both locations return the expected response body (`return` / `ngx.say` respectively) but when using nginx's return statement, the Lua code does not run (=I don't see the log message)
I'm using nginx 1.12.0, and lua-nginx-module master branch.

Thanks!

Eran

**Comment by tokers** [comment]
@erankor I think this because the `return` directive works in the rewrite phase, and it triggers the response start to be sent, so the access phase hook `access_by_lua_block` no chance to work.

**Comment by erankor** [comment]
Thanks @tokers, looks like you are right, wrote this test config:
```
                location /test {
                        deny all;
                        return 200 "hello";
                }
```
It returns 200, and not 403 like I'd expect.
Anyway, this proves it's not related to lua-nginx-module...

**Comment by thomasleplus** [comment]
@erankor did you find a way around this issue by any chance? I am trying to do something very similar to your example /lua1 and my access_by_lua_block is not run. Thanks.

**Comment by erankor** [comment]
In my case, I just used ngx.say instead of return (/lua2 above)

**Comment by thomasleplus** [comment]
Thank you, it worked. Alternatively doing `echo "return"` instead of `return 200 "return"` also works for me.
