### ISSUE TITLE
helper to check if ngx.api_enabled(func)?

### ISSUE THREAD

**Issue by bungle** [openresty/lua-nginx-module#1121]
Sometime the code will fail if it runs on non-supported phase. Sometimes we can move ahead even with the failure. From code perspective it would make it easier to have a function `ngx.api_enabled()` (suggestions for better name?) to check if you can use API on current phase?

e.g.

```lua
if ngx.api_enabled(ngx.req.get_method) then
  ...
end
```

Does having this make sense?

**Comment by agentzh** [comment]
@bungle No, such Lua API is very difficult to implement and maintain. I think you should just use `ngx.get_phase()` in the condition instead? Another way is to use `pcall` to catch any exceptions.
