### ISSUE TITLE
ngx lua 如何将存在mysql的二进制图片输出到浏览器端

### ISSUE THREAD

**Issue by Steven201314** [openresty/lua-nginx-module#1122]
如题,
一直应用都是用的是web应用,敢问各位大牛，突然想着怎么样把缓存在内存中或者数据库的图片二进制通过lua输出输出到浏览器客户端，原理都晓得，愣是不知道怎么下手了。。。

**Comment by spacewander** [comment]
@Steven201314 
The issues is only used for bug report.
Please redirect your question to the [OpenResty Chinese mailling list](https://groups.google.com/group/openresty).

Anyway, why not set the Content-Type response header(just like what Nginx does for static file)?

**Comment by Steven201314** [comment]
Setted the Content-Type had no Effects. May I made a mistake, I'll try again,Thanks a lot.

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

BTW, without seeing a *self-contained* and *minimal* example that can easily reproduce the problem on our side, we cannot really help you out.
