### ISSUE TITLE
LUA scripting is not working if server in proxy_protocol

### ISSUE THREAD

**Issue by SniperCZE** [openresty/lua-nginx-module#1123]
Lua module is not working when server is configured for proxy_protocol (ie. for usage behind ELB or HAProxy). Everything works well when proxy protocol disabled.

OS: Debian 8 Jessie
Nginx package: nginx-extras 1.6.2-5+deb8u5
Nginx version: nginx/1.6.2

Nginx configuration:

    upstream gogrid {
      server vps-chat-ws-01.qa.eu-west-1.aws.be.loc:3000 fail_timeout=10;
    }
    
    upstream aws {
      server vps-chat-ws-02.qa.eu-west-1.aws.be.loc:3000 fail_timeout=10;
    }
    
    upstream ams01 {
      server vps-chat-ws-02.qa.eu-west-1.aws.be.loc:3000 fail_timeout=10;
    }
    
    server {
        listen 80 proxy_protocol;
        server_tokens: off;
        set_real_ip_from: 10.150.68.0/22;
    
      access_log /var/log/nginx/livechat_ws-access.log combined_proxy;
      error_log /var/log/nginx/livechat_ws-error.log;
    
      charset utf-8;
    
      location / {

        access_by_lua '
          ngx.log(ngx.ERR, "Test if LUA scripting in Nginx works")
        ';

        if ($target_upstream = gogrid) {
          proxy_pass http://gogrid;
        }
        if ($target_upstream = aws) {
          proxy_pass http://aws;
        }
        if ($target_upstream = ams01) {
          proxy_pass http://ams01;
        }
    
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP       $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
      }
    }

when Listen is configured with proxy_protocol, no messages is logged from nginx (but no error too). When removing proxy_protocol, nginx logs "Test if LUA scripting in Nginx works".

**Comment by agentzh** [comment]
@SniperCZE "If is evil": https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

We do not want to support the buggy "if" usage in `nginx.conf`.

**Comment by agentzh** [comment]
@SniperCZE My hunch is that in the "proxy protocol" mode, the normal nginx request processing phase handlers are simply skipped altogether.

**Comment by rayward** [comment]
@agentzh can this be reopened, it seems to be an issue still. Neither `ssl_certificate_by_lua` nor `access_by_lua` handlers seem to be functioning for `proxy_protocol` servers.

Is this something that openresty can patch?

**Comment by rayward** [comment]
Never mind, I think we just have a server configuration issue!
