### ISSUE TITLE
ngx.location.capture acess link get 502 status code

### ISSUE THREAD

**Issue by JLLNANA** [openresty/lua-nginx-module#1126]
nginx configuration is:
 location ~ ^/p_link/(.+)$ {
            internal;
            proxy_pass http://i.test.proxy/2/stories/$1?$args;
            proxy_set_header Host 'i.api.weibo.com';
            proxy_http_version 1.1;
            proxy_set_header Accept-Encoding '';
            proxy_set_header Connection "";
            proxy_connect_timeout 10ms;
            proxy_send_timeout 10ms;
            proxy_read_timeout 100ms;
        }
    location ~ ^/test_link/(.+)$ {
            internal;
            proxy_pass http://test.proxy/article/2017-07/$1?$args;
            proxy_set_header Host 'china.huanqiu.com';
            proxy_http_version 1.1;
            proxy_set_header Accept-Encoding '';
            proxy_set_header Connection "";
            proxy_connect_timeout 10ms;
            proxy_send_timeout 10ms;
            proxy_read_timeout 100ms;
       }

    }
        upstream i.test.proxy {
            server i.test.com;
            keepalive 64;
        }
        upstream test.proxy{
           server china.huanqiu.com;
           keepalive 35;
        }

i.test.com need appkey do some authorization operation which need a parameter named appkey and submit it to the interface is ok

These two configuration of test_link can access. But p_link can not access
I have use php code to access the   sever of i.test.com , php can work correctly;

**Comment by rhettli** [comment]
here you shou use  three nginx program ,the first is used to be upstream man ,

the second and  the third can be used  for run lua script ,then access the first nginx.

**Comment by JLLNANA** [comment]
sorry for disturb, miss setting of port number
