### ISSUE TITLE
why openressy not support  get ip address in lua.

### ISSUE THREAD

**Issue by rhettli** [openresty/lua-nginx-module#1127]
why openresty not support   get ip adderss in lua script or any doc to introduce it?

why openresty have no  plugs to access sphinx?

**Comment by agentzh** [comment]
@rhettli We usually just use `ngx.var.remote_addr` to access the nginx builtin variable `$remote_addr`. See http://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_addr

Regarding sphinx, we rely on community libraries for such 3rd-party backend's drivers. Apparently the official OpenResty distribution won't try to support every single 3rd-party backend service.
