### ISSUE TITLE
ngx.location.capture + proxy_pass = 404

### ISSUE THREAD

**Issue by abagshaw** [openresty/lua-nginx-module#1129]
I am using openresty 1.11.2.4 (from the docker image `openresty/openresty:1.11.2.4-trusty`)

For some reason, `ngx.location.capture()` doesn't appear to be playing nice with my location that has a `proxy_pass` for my upstream API engine docker container (`apicontainer` is my docker container hostname). I've defined the following (I can include more details if necessary):

```
upstream api_main {
    server apicontainer:8080;
}
```
```
location /api_upstream {
    internal;
    proxy_pass http://api_main/;
    proxy_redirect off;
}
```

In another `location` controlled by a `content_by_lua_block` I have the following Lua script:

```
local api_response = ngx.location.capture("/api_upstream", {share_all_vars = true})
    if api_response.status ~= ngx.HTTP_OK then
        ngx.exit(api_response.status)
    return
end
```

Unfortunately for some reason, `ngx.location.capture("/api_upstream")` always returns a 404 when calling `/api_upstream`. I've tried a ton of things: I tried removing `internal;` on the `/api_upstream` location to externally verify by directly accessing it that it indeed works - and it does and the proxying works as expected. I also tried just putting `return 200 "Yes this works";` in place of the `proxy_pass` in `/api_upstream` and when I do this, `ngx.location.capture("/api_upstream")` magically works again so it appears that it's the `proxy_pass` that's causing issues.  Any ideas?

Thanks!

**Comment by agentzh** [comment]
@abagshaw I suggest you install the openresty-debug package instead and then use the `debug` filtering level in all your `error_log` directive in your `nginx.conf`. Basically, you just need to look at the debugging logs to see what went wrong. BTW, `share_all_vars` is a very bad idea and it may lead to problems that are extremely difficult to debug.

**Comment by abagshaw** [comment]
Turns out it was an issue with how my upstream API service was handling the request. Problem solved, thanks!
