### ISSUE TITLE
The latest version of this module is compatible with the following versions of Nginx:1.13.3?

### ISSUE THREAD

**Issue by stspqxl** [openresty/lua-nginx-module#1130]
The latest version of this module is compatible with the following versions of Nginx:1.13.3?

**Comment by stspqxl** [comment]
how to get The latest version of this module is compatible with the following versions of Nginx:1.13.3?

**Comment by agentzh** [comment]
@stspqxl It's not yet officially tested. To check the compatibility list, see the documentation:

https://github.com/openresty/lua-nginx-module/#nginx-compatibility

The last officially tested nginx core is still 1.11.2 (though our tests still need OpenResty's patches in the nginx core to pass completely, so it's recommended to use OpenResty instead to avoid hitting known nginx bugs).

We'll try testing the latest nginx 1.13.x version after OpenResty 1.11.2.5 is out.
