### ISSUE TITLE
ngx_http_lua_ctx_t ctx is null point

### ISSUE THREAD

**Issue by jiansongjay** [openresty/lua-nginx-module#1134]
The following old nginx code, when the ctx is null point leads to the coredump. Writing the lua what steps lead to ctx null pointer.
`void ngx_http_lua_request_cleanup(ngx_http_lua_ctx_t *ctx, int forcible)
{
    lua_State                   *L;
    ngx_http_request_t          *r;
    ngx_http_lua_main_conf_t    *lmcf;
    ngx_http_lua_loc_conf_t     *llcf;
    ngx_http_lua_ctx_t          *cur_ctx;

    r = ctx->request;

    ngx_log_debug1(NGX_LOG_DEBUG_HTTP, r->connection->log, 0,
                   "lua request cleanup: forcible=%d", forcible);

    /*  force coroutine handling the request quit */
    if (ctx == NULL) {
        dd("ctx is NULL");
        return;
    }
}`

**Comment by agentzh** [comment]
@jiansongjay I don't quite follow you. What versions of NGINX and ngx_lua (or OpenResty) are you using? Will you try the latest version of ngx_lua or OpenResty? I'm not sure how `ctx` would be end up with NULL in that place. Will you provide a minimal example?

**Comment by jiansongjay** [comment]
Mine version is lua-nginx-module-0.9.5rc2. I found it be fixed by this version (https://github.com/openresty/lua-nginx-module/commit/99866b50df8ad864d1f9f990045e7db48c3aa36c#diff-4c237c57e5462e077417a5177672ce82)
It occurs by chance not always.

**Comment by agentzh** [comment]
Then this issue should be closed now.
