### ISSUE TITLE
v0.10.9

### ISSUE THREAD

**Issue by parkr** [openresty/lua-nginx-module#1135]
Hey @agentzh! I was wondering when you plan to release v0.10.9. I see an rc8 in the tree here as well as some recent commits. We would love to upgrade as only v0.10.9 supports nginx 1.12 in our tests. Do you have any plans for a final v0.10.9 release?

I can post this to the mailing list if you'd prefer, but it fell under "development discussion" for me, which is an allowed topic in the issues here. I'm sorry if I misinterpreted! Thank you!

**Comment by agentzh** [comment]
@parkr I only tag a new formal release of `ngx_lua` (and other components) upon the next OpenResty release, be it an RC release or a formal release. The next OpenResty 1.11.2.5 RC1 is expected to be out in the next couple of weeks if nothing special comes up.

**Comment by parkr** [comment]
@agentzh Ok, so v0.10.9 is not coming in the next couple weeks, but another rc? That's ok, thank you!
