### ISSUE TITLE
Bulid error with nginx 1.12.1

### ISSUE THREAD

**Issue by artnurr** [openresty/lua-nginx-module#1136]
Hello!
Try to build version lua-nginx-module v0.10.10 with nginx-1.12.1 and openssl-1.1.0f, get this error

cc1: warnings being treated as errors
/etc/nginx/mods/lua-nginx-module-0.10.10/src/ngx_http_lua_module.c: In function ‘ngx_http_lua_merge_srv_conf’:
/etc/nginx/mods/lua-nginx-module-0.10.10/src/ngx_http_lua_module.c:1022: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type
/etc/nginx/mods/openssl-1.1.0f/.openssl/include/openssl/ssl.h:637: note: expected ‘struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)’ but argument is of type ‘struct SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.12.1'
make: *** [build] Error 2

**Comment by agentzh** [comment]
@artnurr OpenSSL 1.1 is not a supported target yet. This is duplicate with #922. I'm closing this.

**Comment by agentzh** [comment]
@artnurr BTW, you may want to just use the official OpenResty Linux packages here to save troubles:

https://openresty.org/en/linux-packages.html

**Comment by yaung** [comment]
the  branch  openssl-1.1 of  lua-nginx-module have resolve this bug , hope @agentzh merge it to the master branch.
