### ISSUE TITLE
suggestion: const value of error message

### ISSUE THREAD

**Issue by dista** [openresty/lua-nginx-module#1137]
Currently,  resty return error as string and it may change,  if our app depends on this error message, any change of the error message in resty will break our app.

So can the error msg become a part of the API, app can refer it as something like ngx.ERR_XXX.

**Comment by agentzh** [comment]
@dista No, we do not want to introduce error codes, which is too much a burden. We do not change error strings and they serve as *symbols*.

**Comment by dista** [comment]
@agentzh thanks, if it does not *change*, it's fine.
