### ISSUE TITLE
X-Accel-Redirect to lua location does not work

### ISSUE THREAD

**Issue by passerbya** [openresty/lua-nginx-module#1140]
Here is my conf files

**test.yyets.conf:**
`upstream redisServer {
	server 127.0.0.1:6379;
	keepalive 500;
}
upstream iosyyetsapi443 {
        server 43.255.191.40:80;
        keepalive 5000;
}
server {
	listen 808;
	server_name test.ousns.net;

	location /lua {
	  content_by_lua_file conf/vhosts/test.lua;
	}
	
	location ~ .+\.php {
		proxy_redirect off;
		proxy_pass http://iosyyetsapi443;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   Accept-Encoding  "";
		proxy_set_header   Connection "";
		proxy_http_version 1.1;
		client_max_body_size 10m;
		client_body_buffer_size 128k;
		proxy_connect_timeout 30;
		proxy_send_timeout 30;
		proxy_read_timeout 30;
		proxy_buffer_size 4k;
		proxy_buffers 4 32k;
		proxy_busy_buffers_size 64k;
		proxy_temp_file_write_size 64k;
	}
	
	location = /get_redis {  
		internal;

		set_unescape_uri $redis_key $arg_key;  
		redis_pass redisServer;  
	}
	
	location = /set_redis {  
		internal;

		set_unescape_uri $exptime $arg_exptime;  
		set_unescape_uri $key $arg_key;
		set_unescape_uri $c $arg_c;

		redis2_query set $key $c;  
		redis2_query expire $key $exptime;  
		redis2_pass redisServer;  
	}
  access_log   logs/access.log;
}`

**test.lua:**
`function string:split(sep)  
    local sep, fields = sep or ":", {}  
    local pattern = string.format("([^%s]+)", sep)  
    self:gsub(pattern, function (c) fields[#fields + 1] = c end)  
    return fields  
end

local key = ngx.var.arg_url
local res = ngx.location.capture("/get_redis", {args={key=key}})

if res.status == 200 then
	local c = res.body
	local start,_ = string.find(c, "\n\n")
	local headers = string.sub(c, 1, start-1)
	local body = string.sub(c, start+2, -1)
	local result = headers:split("\n")
	
	ngx.status = res.status
	for i=1, #result do
		local idx,_ = string.find(result[i], ":")
		local name = string.sub(result[i], 1, idx-1)
		local val = string.sub(result[i], idx+1, -1)
		if name == "Content-Type" then
			ngx.header.content_type = val
		else
			ngx.header[name] = val
		end
	end

	ngx.header["X-Cached-From"] ="HIT"
	ngx.header["X-Cached-Store"] = "BYPASS"
	ngx.header["X-Key"] = key
	ngx.header["Content-Length"] = #body
	ngx.send_headers()
	ngx.say(body)
	ngx.eof()
else
	res = ngx.location.capture(key)
	local body = res.body
	local xCachedStore = nil
	
	if res.status == 200 or res.status == 201 then
		local headers = ""
		if res.header["Content-Type"] ~= nil then
			headers = headers.."Content-Type:"..res.header["Content-Type"].."\n"
		end
		if res.header["Cache-Control"] ~= nil then
			headers = headers.."Cache-Control:"..res.header["Cache-Control"].."\n"
		end
		if res.header["Date"] ~= nil then
			headers = headers.."Date:"..res.header["Date"].."\n"
		end
		local c = headers.."\n"..body
		local setRes = ngx.location.capture("/set_redis", {method=ngx.HTTP_POST, args={key=key, exptime=3600, c=c}})
		if setRes.status == 200 then
			xCachedStore = "STORE"
		else
			xCachedStore = "BYPASS"
		end
	end
	
	ngx.status = res.status
	ngx.header.content_type = res.header["Content-Type"]
	ngx.header["X-Cached-From"] = "MISS"
	ngx.header["X-Cached-Store"] = xCachedStore
	ngx.header["X-Key"] = key
	ngx.header["Date"] = res.header["Date"]
	ngx.header["Content-Length"] = #body
	ngx.send_headers()
	ngx.say(body)
	ngx.eof()
end`

**test1.php:**
`<?php
	header("X-Accel-Redirect: /lua?url=/test2.php");
?>`

**test2.php:**
`<?php
	header("Content-Type: text/plain");
	header("Cache-Control: max-age=600");
	echo "111";
?>`

When I visit the page “http://test.ousns.net:808/lua?url=%2Ftest2.php” that displays fine, when I  I visit the page “http://test.ousns.net:808/test1.php” that displays "404 Not Found".

**Comment by spacewander** [comment]
@passerbya 
Could you paste the debug log here?
You could enable debug log via http://nginx.org/en/docs/debugging_log.html.

**Comment by passerbya** [comment]
[lua.zip](https://github.com/openresty/lua-nginx-module/files/1227184/lua.zip)

**Comment by passerbya** [comment]
I change test.lua to
`ngx.header["Content-Type"] = "Content-Type: text/plain"
ngx.send_headers()
ngx.say("lua")
ngx.exit(200)`
it also displays "404 Not Found".
[lua.zip](https://github.com/openresty/lua-nginx-module/files/1227209/lua.zip)

**Comment by spacewander** [comment]
@passerbya 

The 404 is returned from `/get_redis`. It is not related with `X-Accel-Redirect`.
```
2017/08/16 13:53:43 [debug] 23352#0: *1 http upstream request: "/get_redis?key=%2Ftest2.php"
2017/08/16 13:53:43 [debug] 23352#0: *1 http upstream process header
2017/08/16 13:53:43 [debug] 23352#0: *1 malloc: 000000000104CB40:4096
2017/08/16 13:53:43 [debug] 23352#0: *1 recv: eof:0, avail:1
2017/08/16 13:53:43 [debug] 23352#0: *1 recv: fd:17 10 of 4096
2017/08/16 13:53:43 [debug] 23352#0: *1 redis: "+OK
$-1"
2017/08/16 13:53:43 [info] 23352#0: *1 key: "/test2.php" was not found by redis while reading response header from upstream, client: 59.175.154.49, server: test.ousns.net, request: "GET /lua?url=/test2.php HTTP/1.1", subrequest: "/get_r
edis", upstream: "redis://127.0.0.1:6379", host: "test.ousns.net:808"
2017/08/16 13:53:43 [debug] 23352#0: *1 finalize http upstream request: 404
```

**Comment by passerbya** [comment]
"/get_redis?key=%2Ftest2.php" returns 404, then test.lua request /test2.php, this log is created by "http://test.ousns.net:808/lua?url=%2Ftest2.php". See the next request "http://test.ousns.net:808/test1.php".

**Comment by passerbya** [comment]
See line 1383 "2017/08/16 13:53:44 [debug] 23352#0: *4 http request line: "GET /test1.php HTTP/1.1", or see this attachment that I delete the useless code.
https://github.com/openresty/lua-nginx-module/files/1227209/lua.zip

**Comment by spacewander** [comment]
@passerbya 
Sorry, I made my decision too early.
I found the `/test1.php` now.
It seems that the `/test1.php` was not found, which caused the 404 response code.
```
2017/08/16 13:53:44 [debug] 23352#0: *4 http upstream request: "/test1.php?"
...
2017/08/16 13:53:44 [debug] 23352#0: *4 http proxy status 404 "404 Not Found"
2017/08/16 13:53:44 [debug] 23352#0: *4 http proxy header: "Server: nginx/1.10.3"
```

**Comment by spacewander** [comment]
BTW, `X-Accel-Redirect` header is handled right after the upstream server responses its header. If everything is well, Nginx will change the location to the new one. This process doesn't involve lua-nginx-module.

In my experience, the strange result might be due to misconfiguration or some environement effects. It would be helpful if we are able to dig the Nginx debug log.

**Comment by passerbya** [comment]
I modify test1.php to
`<?php
	header("X-Accel-Redirect: /test2.php");
?>`
then "http://test.ousns.net:808/test1.php" was found.

**Comment by spacewander** [comment]
@passerbya 
My guess is that your php is listening behind another Nginx proxy.
The second Nginx proxy handles the `X-Accel-Redirect` header, and returns 404 or other response code to the first Nginx/OpenResty proxy.

**Comment by passerbya** [comment]
@spacewander 
Yes, that's the problem, thx.

**Comment by spacewander** [comment]
@agentzh  @passerbya
Consider it as solved and close the issue?

**Comment by agentzh** [comment]
Consider it resolved. @spacewander Thanks!
