### ISSUE TITLE
tcpsocket settimeouts doesn't work when the timeout number is too large

### ISSUE THREAD

**Issue by spacewander** [openresty/lua-nginx-module#1141]
The version of OpenResty:
`nginx version: openresty/1.11.2.2`

A minimal reproduction:

With a `conf/nginx.conf` like this:
```nginx
events {
    worker_connections 4096;
}
error_log logs/error.log debug;
http {
    server {
        listen 8888;
        location /foo {
            content_by_lua_block {
                local tcp=ngx.socket.tcp()
                ngx.say(ngx.now())
                ngx.flush()
                local err = tcp:settimeouts(2^31,2^31,2^31)
                tcp:connect("127.0.0.1", 8000)
                local data, err = tcp:receive(1)
                ngx.say(err)
                ngx.update_time()
                ngx.say(ngx.now())
            }
        }
    }
}
```

And then set up `nc -l 8000 -k` in one terminal session.

Finally, run `curl localhost:8888/foo` in another terminal session, we would see the output:
```
1503062229.088
timeout
1503062289.091
```

60s default read timeout is used instead of 2^31.

This issue is first reported in https://github.com/openresty/lua-resty-redis/issues/129.

---

It seems that the problem is caused by incorrect numeric conversions.

Between `settimeouts` and `connect`, the type of `timeout` has been changed from `lua_Number` to `lua_Integer` to `ngx_int_t` to `int` to `ngx_msec_t`.
When conversed from `ngx_int_t` to `int`, the value of `timeout` overflow to a negative number. After that, the default timeout is used as fallback.

**Comment by agentzh** [comment]
@spacewander Thanks for the analysis! Will you contribute a patch for it? Seems like we should just return an error when overflow is doomed.

**Comment by spacewander** [comment]
IMHO, I'd like to be strict with  `lua_tointeger` and `ngx_msec_t` everywhere, so that we could avoid the overflow at root.

**Comment by agentzh** [comment]
@spacewander Lua numbers are double-precision floating point numbers per se. It would overflow one way or another.

**Comment by spacewander** [comment]
Sorry, I made a mistake. `ngx_msec_t` is an `uintptr_t` integer, so it still could be overflow in 32 bits platform. We should check it with `(ngx_msec_t) -1` when setting timeout.

But in 64 bits platform, `ngx_msec_t` is 64 bits. Converting a double number to 64 bits integer would not be overflow in most platforms. And convert a double(Lua number) to int32(int) then to uint64(ngx_msec_t, in 64 bits platform) looks bad. IMHO, why not convert a double to uint64 directly?

**Comment by spacewander** [comment]
@agentzh 
Maybe I understand your meaning now.
Since large timeout number is not meaningful, we could just support timeout <= 2^31-1. For the greater timeout number, we returns an error instead. This approach is easier to implement and is consistent in both 32 bits platform and 64 bits platform.
Please correct me if my thought is wrong.

**Comment by agentzh** [comment]
@spacewander Right, supporting too large timeout values does not make sense at all.

**Comment by agentzh** [comment]
@spacewander Great, thanks!
