### ISSUE TITLE
ngx.say/ngx.print ignores __tostring metamethod

### ISSUE THREAD

**Issue by isage** [openresty/lua-nginx-module#1144]
ngx.say/ngx.print ignores __tostring metamethod and doesn't work on userdata at all,
as opposed to lua's print.

**Comment by agentzh** [comment]
@isage Right, this is a notable difference. They are different APIs anyway. We have no intention to make `ngx.say` and `ngx.print` 100% compatible with Lua's `print()` builtin. And it's hard to add support for it without slowing down the existing API. Maybe we can do this when `ngx.say` and `ngx.print` are re-implemented via FFI, then in that case we can just call the Lua builtin `tostring()` directly on the arguments.

**Comment by isage** [comment]
Can't we just reimplement luaL_tolstring (https://github.com/keplerproject/lua-compat-5.2/blob/master/c-api/compat-5.2.c#L574) and call it instead of lua_tolstring?

**Comment by agentzh** [comment]
@isage It adds overhead and slows down all the existing OpenResty applications, especially for those with many function arguments.

**Comment by isage** [comment]
Yeah, but using tostring in FFI is essentially the same (in 5.2/5.3 it just calls luaL_tolstring and in 5.1 it implements luaL_tolstring analog). So the only way without overhead of calling __tostring is just leave it as it is and user should call tostring when needed.
It would be nice, however, to document this.

**Comment by agentzh** [comment]
@isage The thing is that LuaJIT is very good at optimizing metamethod calls away in its JIT compiler :) But it's a big no for interpreted C API calls like this. That's why I suggested we only do this in FFI-based implementations.

**Comment by agentzh** [comment]
@isage We didn't claim behavior compatibility with standard Lua's `print()` in our documentation at all. So I don't see why we should document this especially when this detail may change in the future. I'd say it's undocumented by intention.

**Comment by thibaultcha** [comment]
Considering this answered, closing the thread.

Thanks
