### ISSUE TITLE
Building with luajit-rocks from Torch - LuaJIT not found

### ISSUE THREAD

**Issue by elefthei** [openresty/lua-nginx-module#1148]
Hello Openresty folks,

I've built Torch from https://github.com/torch/distro.git it comes bundled with luajit-rocks, now I'm trying to build *lua-nginx-module* so that it uses the same LuaJIT.
My Torch LuaJIT is version LuaJIT-2.1-beta1, it works and lives in `/usr/src/torch/install/bin/luajit`

FYI the same issue described below I've encountered building *openresty* with the `--with-luajit=/usr/src/torch/install`

## Environment

`LUAJIT_LIB=/usr/src/torch/install/lib`
`LUAJIT_INC=/usr/src/torch/install/include`

## Files
```
root@99d449ef1c35:/usr/src/nginx-1.11.2# ls /usr/src/torch/install/include/
TH  THNN  lauxlib.h  lua.h  lua.hpp  luaT.h  luaconf.h	luajit.h  lualib.h  qtlua
root@99d449ef1c35:/usr/src/nginx-1.11.2# ls /usr/src/torch/install/lib/    
libTH.so  libTH.so.0  libluaT.so  libluaT.so.0	libluajit.so  libqlua.so  libqtlua.so  libthreadsmain.so  lua  luarocks
```

## Configure
The build step that is failing (when trying to build *NGINX* with modules)
```
 ./configure --prefix=/opt/nginx \
         --with-ld-opt="-Wl,-rpath,$LUAJIT_LIB" \
         --add-module=/usr/src/ngx-dev-kit \
         --add-module=/usr/src/lua-nginx-module
```

## Errors
And this is the error:
```
checking for LuaJIT library in /usr/src/torch/install/lib and  (specified by the LUAJIT_LIB and LUAJIT_INC env, with -ldl) ... not found
checking for LuaJIT library in /usr/src/torch/install/lib and  (specified by the LUAJIT_LIB and LUAJIT_INC env) ... not found
        ./configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUAJIT_LIB is defined as /usr/src/torch/install/lib and LUAJIT_INC (path for lua.h) , but we cannot find LuaJIT there.
```

Basically what is requred to find LuaJIT? Is it possible to use the one that comes with luajit-rocks?

**Comment by agentzh** [comment]
@elefthei this module looks for `libluajit-5.1.so*` files. That is the official LuaJIT DSO name. BTW, it's highly recommended to use OpenResty's LuaJIT and nginx core with this module, otherwise you'll likely run into known bugs and security vulnerabilities. You are warned.

BTW, you can always find the details of the failed feature tests in the file `objs/autoconf.err` when debugging such things.

**Comment by elefthei** [comment]
Thanks, `objs/autoconf.err` helped a lot. FYI for whoever wants to do the same, need to run configure like this:

```
$ export LUAJIT_LIB=/usr/src/torch/install/lib
$ export LUAJIT_INC=/usr/src/torch/install/include
$    ./configure --prefix=/opt/nginx \
         --with-ld-opt="-Wl,-rpath,$LUAJIT_LIB" \
         --with-cc-opt="-I$LUAJIT_INC" \
         --with-pcre=/usr/src/pcre-${PCRE_VERSION} \
         --with-pcre-jit \
         --add-module=/usr/src/ngx-dev-kit \
         --add-module=/usr/src/lua-nginx-module && \
```

For NGINX to use luajit-rocks include libraries.

**Comment by agentzh** [comment]
@elefthei Be careful that Lua modules on luajit-rocks may not be aware of OpenResty and its network I/O may simply block the nginx event loop and ruin the performance. It's highly recommended to use opm instead to install OpenResty oriented Lua libraries.
