### ISSUE TITLE
SSL_R_NO_CIPHERS_PASSED

### ISSUE THREAD

**Issue by coder-sreeraj** [openresty/lua-nginx-module#1153]
I am getting error while installing openresty
make[2]: Entering directory '/home/sreeraju/Downloads/openresty-1.11.2.2/build/nginx-1.11.2'
cc -c -I/home/sreeraju/Downloads/openresty-1.11.2.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DLUA_DEFAULT_PATH='"/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/site/lualib/?/init.lua;/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/?/init.lua"' -DLUA_DEFAULT_CPATH='"/usr/local/openresty/site/lualib/?.so;/usr/local/openresty/lualib/?.so"' -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../ngx_lua-0.10.7/src/api -I objs \
	-o objs/src/event/ngx_event_openssl.o \
	src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
src/event/ngx_event_openssl.c:2048:21: error: ‘SSL_R_NO_CIPHERS_PASSED’ undeclared (first use in this function)
             || n == SSL_R_NO_CIPHERS_PASSED                          /*  182 */
                     ^
src/event/ngx_event_openssl.c:2048:21: note: each undeclared identifier is reported only once for each function it appears in
objs/Makefile:1090: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[2]: *** [objs/src/event/ngx_event_openssl.o] Error 1
make[2]: Leaving directory '/home/sreeraju/Downloads/openresty-1.11.2.2/build/nginx-1.11.2'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/sreeraju/Downloads/openresty-1.11.2.2/build/nginx-1.11.2'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by agentzh** [comment]
@coder-sreeraj Seems like your OpenSSL is too new. Try the 1.0.2 series instead.
