### ISSUE TITLE
ssl_session_store_by_lua_block phase right-after-SSL-handshake?

### ISSUE THREAD

**Issue by dongbeiouba** [openresty/lua-nginx-module#1158]
The phase of ssl_session_store_by_lua_block is right-after-SSL-handshake but ssl_session_store_by_lua_file is right-before-SSL-handshake, are you kidding me? which one is right?

```
ssl_session_store_by_lua_block

syntax: ssl_session_store_by_lua_block { lua-script }

context: http

phase: **right-after-SSL-handshake**

```

```
ssl_session_store_by_lua_file

syntax: ssl_session_store_by_lua_file <path-to-lua-script-file>

context: http

phase: **right-before-SSL-handshake**

**Equivalent to ssl_session_store_by_lua_block,** except that the file specified by <path-to-lua-script-file> contains the Lua code, or rather, the Lua/LuaJIT bytecode to be executed.

```

**Comment by spacewander** [comment]
It looks like a typo under `ssl_session_store_by_lua_file`, because you can not create a session before making handshake. 
Maybe you could submit a pr to update the [HttpLuaModule.wiki](https://github.com/openresty/lua-nginx-module/blob/master/doc/HttpLuaModule.wiki) and the readme.

**Comment by agentzh** [comment]
It's indeed a typo. Thanks for the report. Already fixed in master.
