### ISSUE TITLE
Dose balancer_by_lua_block support "stream module" zone?

### ISSUE THREAD

**Issue by zacard-orc** [openresty/lua-nginx-module#1159]
I set "balancer_by_lua_block" in http zone can work,But I set it into the "stream/upstream" zone can't work.Now I have some udp application to use，How can this parameters can support"
---- error.log ------
2017/09/21 17:21:59 [emerg] 3909#0: "balancer_by_lua_block" directive is not allowed here in /opt/app/nginx/nginx/conf/nginx.conf:22

**Comment by agentzh** [comment]
@zacard-orc This lua-nginx-module is really `ngx_http_lua_module`. You'll need the following sister module for the stream subsystem instead:

https://github.com/openresty/stream-lua-nginx-module

Mind you, this stream lua module is still a work in progress.
