### ISSUE TITLE
ngx arg[1] get unknown encoding string

### ISSUE THREAD

**Issue by nemoyin** [openresty/lua-nginx-module#1161]
I want to capture http response body , using ngx.arg[1] in body_filter_by_lua_block

the original response body contains json result like this:

{"appList":[],"resultCode":0,"totalCount":0,"retCount":null}

however, 
I got return like this:

«VJ,(񇪮Q²ԑ*J-.˩q͏IU²2ϑ*ǯI˱̯˃J¹E©@)0'¯4'§򪖼

When I grep the log contains the unknown encoding string,  terminal comes this tips, 

Binary file (standard input) matches

I doubt ngx.arg[1] string type, as document mentioned, as a Lua string value.

**Comment by spacewander** [comment]
@nemoyin
Could you provide a minimal case to reproduce the issue?

**Comment by agentzh** [comment]
@nemoyin Maybe your origin server just sends you a gzip compressed response?

**Comment by ICrazyMouse** [comment]
@agentzh 
Thanks very much！
`proxy_set_header Accept-Encoding "";`
resolved it.
