### ISSUE TITLE
Issue with set_header in lua if value for set_header is retrieved from post/get request.

### ISSUE THREAD

**Issue by labhane** [openresty/lua-nginx-module#1164]
Issue with set_header in lua if value for set_header is captured from post/get request.

Hi Team,

I am trying set custom headers which are required for a backend system to login.
Objective is to set the principal name and value as request header for successful login.

set_header(myheader,headervalue)

Below code does not work.

location /
{

rewrite_by_lua
'
ngx.req.read_body()
local data = ngx.req.get_body_data()
local fetchedName= string.gsub(ngx.req.get_body_data(),"myheader=","")
ngx.set_header("myheader",fetchedName)

'
proxy_pass http://backend.system.to.login:8080;

}

If I print fetchedName , I can see the value correctly.

ngx.print(fetchedName)

Also if I try to retrieve the value as key value pair it prints the value correctly but does not set the value as header.

 Thanks in advance.

Regards,
Vaibs

**Comment by agentzh** [comment]
@labhane I'm afraid `ngx.set_header()` is not an API function provided by this module. Do you have a typo here? If you mean the `ngx.header[NAME] = VALUE` API, then you should really do the response header changes *after* `proxy_pass` is run, i.e., in the `header_filter_by_lua*` handler. The reason is that `proxy_pass` generates a new response header from scratch, thus wiping out any previously set response headers in an earlier phase (like the rewrite phase).

**Comment by labhane** [comment]
@agentzh Thanks for the quick response. Yes that is the typo. 
I have tried 3 different ways to fetch the params and set it as a header in rewrite_by_lua section.


1.  Catching the query string param

hit below url in browser :
http://nginxserver/backendsystem?name="TestUser007"

Code :
	local name = ngx.var.arg_name
	ngx.req.set_header("myheader",name)

2. Reading it from posted parameters in key,val pair

I have created a plain html form with action as http://nginxserver/backendsystem providing single input text field with name as myheader and value as TestUser007. 

Code:
         ngx.req.read_body()
         local args, err = ngx.req.get_post_args()
         if not args then
             ngx.say("failed to get post args: ", err)
             return
         end
         for key, val in pairs(args) do                                
             ngx.req.set_header("myheader",val)
             
         end


3. Reading the body data in full and trimming it to get the required parameter

Code :

	ngx.req.read_body()
	local data = ngx.req.get_body_data()

	local fetchedName= string.gsub(ngx.req.get_body_data(),"myheader=","")

	ngx.set_header("myheader",fetchedName)

 
What is noticable is 

a. if I hard-code the header value it works soomthly and I am able to login into Backend system.
b. if I try to print the incoming value from query string or posted request by ngx.say or ngx.print I am able to see the correct value printed on screen.
c. Below is the little modified version of Scenario 2, in this I am just updating the tempVariable which will be set as a header value.

Code :

         ngx.req.read_body()
         local tempVariable="TestUser008"
         local args, err = ngx.req.get_post_args()
         if not args then
             ngx.say("failed to get post args: ", err)
             return
         end
         for key, val in pairs(args) do                                
             tempVariable=val             
         end
         ngx.req.set_header("myheader",tempVariable)

It lets me login smoothly but the header appears on my backend system as TestUser008 and not TestUser007.

**Comment by agentzh** [comment]
@labhane Your examples are not self-contained since it has external dependencies to run on others' machines. I complete your last example myself by faking the backend using the current nginx server, like below:

```nginx
    location = /t {
        rewrite_by_lua_block {
            ngx.req.read_body()
            local tempVariable="TestUser008"
            local args, err = ngx.req.get_post_args()
            if not args then
                ngx.say("failed to get post args: ", err)
                return
            end
            for key, val in pairs(args) do
                tempVariable=val
            end
            ngx.req.set_header("myheader",tempVariable)
        }

        proxy_pass http://127.0.0.1:$server_port/fake-backend;
    }

    location = /fake-backend {
        return 200 "myheader: $http_myheader";
    }
```

And then I use curl to send a POST request with the request body `foo=TestUser007` like below:

```
curl -d 'foo=TestUser007' localhost:8080/t
```

And get the following output from this curl command:

```
myheader: TestUser007
```

So we're getting the expected value, not `TestUser008`. You can try this standalone example on your side yourself and apply the same test approach to the other examples of yours above.

**Comment by labhane** [comment]
Thanks for the complete example.
Yes the header can be printed correctly but this mechanism does not set header in the same way as being set by the hard-coded value. In a nutshell I am still not able to login using this mechanism.
My question is what is the difference when header value is set as hard coded vs from a variable.

I  have tried one more way which was successful it is through ldap authentication, here I am doing ldap lookup and if the user is valid the user name is being read from $remote_user and same is being set as myheader in the configuration.

Code 

worker_processes 1;

events {
worker_connections 1024;
}

http {
include mime.types;
default_type application/octet-stream;
sendfile on;
keepalive_timeout 65;

ldap_server myldap {
url ldap://xx.xx.x.xxx:389/cn=users,dc=test,dc=com?uid?sub?(objectClass=foo);
binddn "cn=somebinduser,cn=users,cn=testusers,DC=TEST,DC=COM";
binddn_passwd "somepassword";
group_attribute member;
group_attribute_is_dn on;
require group "cn=Myproduct,cn=groups,DC=TEST,DC=COM";
require valid_user;
satisfy any;
}
server {
listen 8080;
server_name localhost;
auth_ldap "Please enter your LDAP username and password.";
# name should match the ldap_server specified above
auth_ldap_servers myldap;

location / {
#// replace localhost:8000 with host and port of the app
proxy_pass_header on;
proxy_pass http://backend.system.to.login:8080;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header myheader $remote_user;
}
}

**Comment by agentzh** [comment]
@labhane What is this `ldap_server` directive? Please make sure you do not use any 3rd-party modules that are not maintained by the nginx team or the openresty team. We're not responsible for investigating problems in those 3rd-party modules. To properly report a problem, you need to provide *minimal* and *standalone* examples as I've demonstrated above. Thanks for your cooperation.

**Comment by labhane** [comment]
What I mentioned in my previous post is the correct working dummy example of setting header using ldap authentication and it works for me. I am able to set "myheader" correctly using this mechanism in nginx.
However my original question has still remained unanswered :
What is the difference between setting the header value hard-coded vs reading from get/post request?
A back-end system which requires a specific header to allow login works correctly with nginx if the header is hard-coded. Reading it from a variable and then setting it up as a header does not allow access to the back-end system.

**Comment by agentzh** [comment]
@labhane As I've repeatedly suggested, we really need a minimal and standalone example that we can easily reproduce the problem you were seeing on our side. Please do that. Otherwise it is too difficult for us to do anything about it given so little information. We're not gods anyway.
