### ISSUE TITLE
Can't set or read request Body on rewrite_by_lua

### ISSUE THREAD

**Issue by davidwr** [openresty/lua-nginx-module#1166]
I'm trying to read the request body to do some logic, but my var $req_body is empty always, even when I force a value...

I think that because in my access.log the $request_body is empty.

This is my nginx.conf:
`http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    #include /etc/nginx/conf.d/*.conf;

    log_format log_req_resp '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" $request_time req_body:"$request_body" resp_body:"$resp_body"';

    server {
        listen 8082;
        access_log /var/log/nginx/access.log log_req_resp;

        lua_need_request_body on;

        set $resp_body "";
        body_filter_by_lua '
            local resp_body = string.sub(ngx.arg[1], 1, 1000)
            ngx.ctx.buffered = (ngx.ctx.buffered or "") .. resp_body
            if ngx.arg[2] then
                ngx.var.resp_body = ngx.ctx.buffered # This works
            end
        ';

        set $request_body "";

        rewrite_by_lua '
               ngx.req.read_body()
               local args = ngx.req.get_post_args()
               for key, val in pairs(args) do
                  ngx.var.request_body = key
               end
               ngx.var.request_body = "blablabla" # This not works
        ';

        location / {
                lua_need_request_body on;
                rewrite_by_lua '
                    ngx.req.read_body()
                    ngx.var.request_body = ngx.req.get_body_data() # This not works
                    ngx.var.request_body = "FORCED VALUE" # This not works
                ';

                return 200 'gangnam style!';
        }
    }
}`

Thank you for attention!

**Comment by agentzh** [comment]
@davidwr To quote the official documentation from https://github.com/openresty/lua-nginx-module/#ngxreqget_body_data : 

> If the request body has been read into disk files, try calling the ngx.req.get_body_file function instead.
> 
> To force in-memory request bodies, try setting client_body_buffer_size to the same size value in client_max_body_size.
