### ISSUE TITLE
Redirect by adding $request_uri equivalent

### ISSUE THREAD

**Issue by kaziqta** [openresty/lua-nginx-module#1168]
I've been trying to do it, that is what I managed to do so far, but I cannot pass the $request_uri argument to ngx.exec, site is multilingual I am setting cookies, checking a cookie, then if it is there, I rewrite:

```
rewrite_by_lua '
    bglink = ngx.var.request_uri
        if string.find(ngx.var.request_uri,"bg") then
        return
    elseif ngx.var.cookie_lang == "bg" then
            ngx.exec("/bg/",bglink)
    return
    elseif ngx.var.cookie_lang == "en" then
        return
    end
    ';
```
what I am trying to do is redirect users with cookie bg to /bg$request_uri

**Comment by spacewander** [comment]
Since the second argument of `ngx.exec` is `args` and you want to set the url, why not use `ngx.exec("/bg" .. bglink)` instead?

**Comment by kaziqta** [comment]
yeah...
`rewrite or internal redirection cycle while internally redirecting to "/bg/"`

this is what I got

**Comment by agentzh** [comment]
@kaziqta That error message is self-explanatory, I think? You're redirecting to your own location recursively, which is definitely prohibited.

**Comment by kaziqta** [comment]
I managed to get to a solution:
`rewrite_by_lua '
        uri = ngx.var.request_uri
        if string.find(uri,"wp-admin") or string.find(uri,"bg") then
                return
        elseif ngx.var.cookie_lang == "bg" then
                ngx.redirect("/bg" .. uri)
        return
        elseif ngx.var.cookie_lang == "en" then
                return
        end
        ';`

But had to add this to the php block:

`if (!-e $request_filename){
	    rewrite ^(.*)$ /index.php?q=$1 last;
            break;
            }`

new with lua, going to get the ching of it :)
