### ISSUE TITLE
"Set-Cookie" make connection closed

### ISSUE THREAD

**Issue by gosp** [openresty/lua-nginx-module#1175]
(openresty/1.11.2.5)    
my example: https://github.com/gosp/lua-resty-ntlm    
It works if client connect to openresty server directly. (`brower<--> server`)    
It doesn't work when client connect to openresty server via squid proxy server(`brower <--> proxy <--> server`)    
I find the line: `ngx.header["Set-Cookie"] = "gsuid=" .. username .. "; path=/"` is the reason.     
When run the line, proxy (or openresty itself) will send request again using a new `ngx.var.connection`. 
       
(In the debug trace: `2017/10/24 10:42:48 [info] 11563#11563: *1 client 10.157.10.66 closed keepalive connection` --- the connection between proxy and server is closed.)      
 
If I comment the line, the proxy environment becomes ok.

In addition, the issue only occurs when I use real browser.  If I use `curl` to imitate real browser, the issue can't reproduce. :(

**Comment by agentzh** [comment]
@gosp I suggest you temporarily enable the nginx debugging logs to see why a retry is attempted. The "client 10.157.10.66 closed keepalive connection" log message is an info level message, which is harmless. It's also not the debugging logs (you need to see the `[debug]` level messages).

**Comment by gosp** [comment]
Should I re-build openresty? 
Now I use `official pre-built packages`. and I have enable `debug` in conf file, but there isn't [debug] messages:
```
server {
    error_log  logs/error.log debug;
}
```

**Comment by gosp** [comment]
from the following trace. it seems nginx receive `close` message from remote?
```
2017/10/24 17:59:18 [debug] 10467#0: timer delta: 116
2017/10/24 17:59:18 [debug] 10467#0: worker cycle
2017/10/24 17:59:18 [debug] 10467#0: epoll timer: 4397
2017/10/24 17:59:19 [debug] 10467#0: epoll: fd:3 ev:2001 d:00007F96120F71E0
2017/10/24 17:59:19 [debug] 10467#0: *1 http keepalive handler
2017/10/24 17:59:19 [debug] 10467#0: *1 malloc: 0000000000D43030:1024
2017/10/24 17:59:19 [debug] 10467#0: *1 recv: eof:1, avail:1
2017/10/24 17:59:19 [debug] 10467#0: *1 recv: fd:3 0 of 1024
2017/10/24 17:59:19 [info] 10467#0: *1 client 10.157.10.66 closed keepalive connection
2017/10/24 17:59:19 [debug] 10467#0: *1 close http connection: 3
2017/10/24 17:59:19 [debug] 10467#0: *1 event timer del: 3: 1508828423764
```

**Comment by gosp** [comment]
replace `cookie` with `http header` to record the result of authentication
