### ISSUE TITLE
When you configure multiple servername, you get servername errors through ngx.var.servername

### ISSUE THREAD

**Issue by firebroo** [openresty/lua-nginx-module#1181]
When you configure multiple servername, you get servername errors through ngx.var.servername，when i set nginx servername, e.g.(servername www.a.com www.b.com), I visit www.a.com and www.b.com, and ngx.var.servename always www.a.com

**Comment by qlees** [comment]
In nginx, this variable is defined as the first member of the server_names in a server.
so the ngx.var.servername is always www.a.com

**Comment by kaspergrubbe** [comment]
I think the variable might be `ngx.var.server_name` instead of `ngx.var.servername`.

Is there a list of these variables somewhere?

**Comment by agentzh** [comment]
@kaspergrubbe Each nginx module can define its own builtin nginx variables. The only way to find out is to refer to their documentation or to scan its C source code. For example:

http://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_name

**Comment by hulining** [comment]
@firebroo  You can use `ngx.var.host` instead of `ngx.var.server_name`
