### ISSUE TITLE
use content_by_lua require my test lib "mylib.so" undefined symbol: luaL_checkversion

### ISSUE THREAD

**Issue by lbsxymltzb** [openresty/lua-nginx-module#1182]
mytest.c:
#include <stdio.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

int l_map(lua_State *L)
{
	int num = luaL_checknumber(L,1);
	int res = 300 * num;
	lua_pushnumber(L,res);
    	return 1;    
}

static const struct luaL_Reg lbslib[] = {
    {"mymap", l_map},
    {NULL, NULL}
};

int luaopen_mylib(lua_State* L)
{
    luaL_checkversion(L);
    luaL_newlib(L, lbslib);
    return 1;
}

nginx.conf：
 lua_package_path "/home/lbs/?.lua;;";
 lua_package_cpath "/home/lbs/luaclib/test/?.so;;";

dir /home/lbs/luaclib/test
mylib.so    lbs.lua

lbs.lua
require "mylib"

error
/home/lbs/luaclib/test/mylib.so: undefined symbol: luaL_checkversion_

please help me，i am  learning and using openresty

**Comment by qlees** [comment]
Maybe you use lua-5.2 or later when build the shared library?
Using lua-5.1 or luajit would works.

**Comment by agentzh** [comment]
Yes, this is definitely an ABI incompatibility issue. Lua C modules for OpenResty MUST be compiled against the Lua 5.1 ABI.

**Comment by lbsxymltzb** [comment]
thank you very much , i think i should learn how to build C extension modules for Lua on Lua 5.1
