### ISSUE TITLE
Cannot iterate a cjson decoded value

### ISSUE THREAD

**Issue by bytesploit** [openresty/lua-nginx-module#1185]
I am reading a valid json file into a variable then passing it to cjson.encode then subsequently to cjson.decode. I assuming the returned variable can be treated as a lua table because according to the docs is says,"cjson.decode will deserialise any UTF-8 JSON string into a Lua value or table."  However, when I try to iterate through the returned table it crashes ? 

Here is the code:

     access_by_lua_block {
                       local cjson = require "cjson"

                        --- Read Serialized Table

                        file = io.open("/etc/nginx/user_table.json", "r");
                        local user_table = file:read("*a");
                        file:close();

                        local encoded_json = cjson.encode(user_table);
                        local users = cjson.decode(encoded_json);

                        ngx.req.read_body();

                        local post_params = ngx.req.get_post_args();
                        local username;
                        local password;

                        if (post_params) then

                                -- Iterate through post params

                                for key,value in pairs(post_params) do
                                        if (key == "username") then
                                                username = value;
                                        elseif (key == "password") then
                                                password = value;
                                        end
                                 end
                        end

                        if (username and password) then
                               --- the following line is crashing
                                **for key,value in pairs(users) do print(key,value) end**
                        end

Here is the contents of /etc/nginx/user_table.json

    [{
		    "user": "user_1",
		    "password": "something",
		    "id": "35",
		    "message": "message 1"
	    },
	   {
		    "user": "user_2",
		    "password": "something",
		    "id": "5c",
		    "message": "message 2"
	   },
	   {
		    "user": "user_3",
		    "password": "something",
		    "id": "7e",
		    "message": "message 3"
	    },
	   {
		    "user": "user_3",
		    "password": "something",
		    "id": "6f",
		    "message": "message 4"
	   }
    ]

**Comment by bytesploit** [comment]
I also tried this valid lua code and it does not work either. (meaning when I take away these lines I know longer get an error 500)

local users = {};

users[1] = {"user_!","password","12345","message here"};
print(users[1][2]);

I am doing this is the  access_by_lua_block  should it be in the init_by_lua_block instead ?

**Comment by agentzh** [comment]
@bytesploit You should really check out your nginx error log file to see the error message. Do this every time you see 500.

**Comment by bytesploit** [comment]
I have checked it but this is all it says: access_by_lua(nginx.conf:100): in function <access_by_lua(nginx.conf:100):1> Which is how I know what line is making it crash but no idea why.

**Comment by agentzh** [comment]
@bytesploit The real error messages are right under your nose. You should check out the subsequent lines right after the line you quoted.

**Comment by thibaultcha** [comment]
Considering this answered.

Thank you.
