### ISSUE TITLE
http v2 not supported yet

### ISSUE THREAD

**Issue by ouwsh** [openresty/lua-nginx-module#1186]
[C]: in function 'raw_header'
        /opt/openresty/openstar/access_all.lua:32: in function </opt/openresty/openstar/access_all.lua:1>, client: 110.81.7.88, server: _, request: "GET /favicon.ico HTTP/2.0", host: "179.226.234.102", referrer: "https://179.226.234.102/index.html"
2017/11/11 12:31:16 [error] 20108#0: *9095 lua entry thread aborted: runtime error: /opt/openresty/openstar/access_all.lua:32: http v2 not supported yet
stack traceback:
coroutine 0:

----------------------
[root@serve logs]# vi /opt/openresty/openstar/access_all.lua

-----  access_all by zj  -----
local optl = require("optl")
local ngx_var = ngx.var
local ngx_ctx = ngx.ctx
local ngx_unescape_uri = ngx.unescape_uri
local config = optl.config
local config_base = config.base or {}

local limit_ip_dict = ngx.shared.limit_ip_dict
local ip_dict = ngx.shared.ip_dict
local host_dict = ngx.shared.host_dict

-- 经测试可直接用request_id,无重复产生 openresty >= 1.11.0.0
local next_ctx = {request_guid = ngx_var.request_id}
ngx_ctx.next_ctx = next_ctx

-- 获取所有参数的内容
        local remoteIp = ngx_var.remote_addr
        local host = ngx_unescape_uri(ngx_var.http_host)
        local ip = remoteIp
        local method = ngx_var.request_method
        local request_uri = ngx_unescape_uri(ngx_var.request_uri)
        local uri = ngx_unescape_uri(ngx_var.uri)
        local useragent = ngx_unescape_uri(ngx_var.http_user_agent)
        local referer = ngx_unescape_uri(ngx_var.http_referer)
        local cookie = ngx_unescape_uri(ngx_var.http_cookie)
        local query_string = ngx_unescape_uri(ngx_var.query_string)

        local headers = ngx.req.get_headers()

what shoud I do to fix this ?

**Comment by ouwsh** [comment]
cd /opt/openresty-1.11.2.5/
./configure  --prefix=/opt/openresty  --with-luajit --with-pcre-jit  --with-http_v2_module --with-http_stub_status_module --with-http_ssl_module  --with-stream --with-http_realip_module --with-http_sub_module  --with-pcre --with-openssl=/opt/openssl-1.0.2m  --with-pcre=/opt/pcre-8.41
make && make install

**Comment by agentzh** [comment]
@ouwsh I think the error message is self-explanatory. This Lua API is just not yet supported in HTTP/2 connections.

This is duplicate with #979.

**Comment by agentzh** [comment]
@ouwsh Just use the `ngx.req.get_headers()` API function for HTTP/2 requests:

https://github.com/openresty/lua-nginx-module/#ngxreqget_headers
