### ISSUE TITLE
Error when building nginx from scratch with LNM

### ISSUE THREAD

**Issue by matthewsuan** [openresty/lua-nginx-module#1190]
When compiling/buiding, I got this error:

`objs/addon/src/ngx_http_lua_socket_tcp.o: In function ngx_http_lua_socket_connected_handler':`
`/usr/src/packages/BUILD/debian/modules/nginx-lua/src/ngx_http_lua_socket_tcp.c:3318: undefined reference to 'ngx_inet_get_port'`

It seems this was added on the latest commit 2 hours ago.

Nginx 1.10.3
OpenSuse Build

Thanks.

**Comment by agentzh** [comment]
@matthewsuan I suggest you try the latest OpenResty release instead:

https://openresty.org/en/download.html

**Comment by agentzh** [comment]
@matthewsuan Your error is definitely compatibility issue between the version of nginx and the version of ngx_lua you are using (or even maybe your ngx_lua has debian's own patches that I don't know).

**Comment by matthewsuan** [comment]
I used the stable release. it worked!

ty

**Comment by agentzh** [comment]
@matthewsuan NGINX's stable releases only mean stability in its API, not really code. The mainline versions of NGINX usually have more bug fixes and are also production ready. It's highly recommended to use OpenResty instead to make sure compatibility and the best result (OpenResty's nginx core also has bug fixes that have not yet been merged in the official nginx cores).
