### ISSUE TITLE
ngx.status returns 000

### ISSUE THREAD

**Issue by JoyChou93** [openresty/lua-nginx-module#1192]
ngx.status does not return the correct status, but 000.

**Comment by agentzh** [comment]
@JoyChou93 Your report is not helpful since you fail to provide any details or examples. It's apparently working fine according to our test suite. We already have tests covering this API.

**Comment by JoyChou93** [comment]
env
- lua-nginx-module-master.v0.10.8
- content_by_lua_file

code
```lua
ngx.header.content_type = "text/html"
--ngx.status = ngx.HTTP_CREATED
ngx.say('status: ', ngx.status)
```

**Comment by spacewander** [comment]
@JoyChou93 
Have you ever set the `ngx.status`? If you don't set the response's status code, obviously it should be zero at the time you haven't made the response.

**Comment by agentzh** [comment]
Right, status code does not have a default value before a response header is produced.
