### ISSUE TITLE
loading lua module in lua file

### ISSUE THREAD

**Issue by NithishReddy** [openresty/lua-nginx-module#1193]
Hi,
While including lua module in lua file, it is giving error as
"attempt to call global 'lua_package_path' (a nil value)"

Code:
in test.lua file : (path location: /usr/local/nginx/lua )
lua_package_path ";;/usr/local/ngx_openresty-1.5.8.1/build/lua-resty-http/lib/?.lua;"

in nginx.conf:
server{
location /test{
       access_by_lua_file lua/test.lua
}
}

??

**Comment by spacewander** [comment]
@NithishReddy 
You are calling `lua_package_path` as a function. Not sure what you want to do...

**Comment by NithishReddy** [comment]
Actually i want to call one service among multiple services based on  incoming request and after based on resposne , for this purpose am using acces_by_lua_file directive with lua-resty-http module.

**Comment by agentzh** [comment]
`lua_package_path` is an nginx configuration directive and should only be put inside `nginx.conf` (and outside any Lua code chunks).
