### ISSUE TITLE
How to handle gziped capture?

### ISSUE THREAD

**Issue by robert-martens** [openresty/lua-nginx-module#12]
This may be more of a question than an issue.  I want to feed the body of one capture into another ex: 
    local res2 = ngx.location.capture("/cap2?"..res1.body)
However res1.body was gziped by the origin server.  Any idea how I can prevent the gzip of the body (a special Accept-Encoding header maybe) or unzip it using something like the gzio library on luaforge (http://luaforge.net/projects/gzio/)?

**Comment by shann09** [comment]
[zzlib ](https://github.com/zerkman/zzlib) may help
