### ISSUE TITLE
lua code in log_by_lua_file not executed when the upstream server is down.

### ISSUE THREAD

**Issue by sstong123** [openresty/lua-nginx-module#1201]
the nginx.conf as below:

upstream my_server {
    server localhost:8095;
    keepalive 2000;
}

location /private/rush2purchase/ {
    limit_conn addr 20;
    proxy_pass http://my_server/private/rush2purchase/;
    proxy_set_header Host $host:$server_port;
    rewrite_by_lua_file D:/tmp/lua/draw_r.lua;
    **log_by_lua_file** D:/tmp/lua/draw_decr.lua;
}

when I send request to http://localhost/private/rush2purchase/  ,it works fine the the stream server is up,
but when I shutdown the upstream server(port:8095),I find the code not executed in **log_by_lua_file** (draw_decr.lua).

info in nginx access.log:
127.0.0.1 - - [01/Dec/2017:21:03:20 +0800] "GET /private/rush2purchase/ HTTP/1.1" **504** 558 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3236.0 Safari/537.36"

error message in nginx  error.log:
2017/12/01 21:02:20 [error] 35292#42868: *3298 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /private/rush2purchase/ HTTP/1.1", upstream: "http://[::1]:8095/private/rush2purchase/", host: "localhost"
2017/12/01 21:03:20 [error] 35292#42868: *3298 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /private/rush2purchase/ HTTP/1.1", upstream: "http://127.0.0.1:8095/private/rush2purchase/", host: "localhost"

How to fix it?

**Comment by spacewander** [comment]
@sstong123 
I could not reproduce your issue. Have you configured `error_page` directive for 504 status code? The `error_page` will trigger an internal redirection, which will change the location of your request.

Anyway, you should [enable debug log](http://nginx.org/en/docs/debugging_log.html) and see what happended indeed.

**Comment by sstong123** [comment]
[config.zip](https://github.com/openresty/lua-nginx-module/files/1523716/config.zip)

I have modify the config as:
```
            error_page   500 502 503 504  /50x.html;
             location /private/rush2purchase/ {		
		         proxy_pass http://my_server/private/rush2purchase/;
			  proxy_set_header Host $host:$server_port;	
			log_by_lua_file D:/tmp/lua/draw_decr.lua;
		}
```

I have uploaded the code files.please check whether you can reproduce it.
 /private/rush2purchase/ shoud be your beckend system uri,you can cheange it.
if you start the upstream server,you should get the "Just for test" in error.log that defined in draw_decr.lua file.
but when you shutdown the upstream server,you shoud not get the "Just for test"  log.
