### ISSUE TITLE
Directive in location overwrites same in server?

### ISSUE THREAD

**Issue by arcivanov** [openresty/lua-nginx-module#1205]
This is more of a question than a bug report, but documentation is unclear on whether directives in location overwrite (as opposed to execute after) the same directives in server.

1) What is the expected behavior?
2) Did anything change with that respect between 1.11 and 1.13?

Originally I could swear that a server directive was executed prior to a location one. But currently I'm observing that the directive in location is overwriting the one in server, basically causing a server directive to not be executed. 

I could be just hallucinating the "original" behavior, but I could swear it worked before.

**Comment by agentzh** [comment]
@arcivanov You didn't mention what exact config directives you are talking about. Different directives have different inheritance (or "merge" in nginx's own term) rules.

**Comment by arcivanov** [comment]
access_by_lua_block

**Comment by agentzh** [comment]
@arcivanov `access_by_lua_block` directives never accumulate. Only one directive can take effect so the inner scope always override those in an outer scope.

**Comment by agentzh** [comment]
@arcivanov You should use Lua module files and Lua's `require()` builtin to do Lua-land code composition.
