### ISSUE TITLE
nginx-1.13.4 lua-nginx-module/src/ngx_http_lua_module.c:11:

### ISSUE THREAD

**Issue by qist** [openresty/lua-nginx-module#1206]
../lua-nginx-module/src/ngx_http_lua_headers.c
../lua-nginx-module/src/ngx_http_lua_headers.c: 在函数‘ngx_http_lua_ngx_req_raw_header’中:
../lua-nginx-module/src/ngx_http_lua_headers.c:151:15: 错误：将‘ngx_chain_t’赋值给‘struct ngx_buf_t *’时类型不兼容
             b = hc->busy[i];
               ^
../lua-nginx-module/src/ngx_http_lua_headers.c:227:15: 错误：将‘ngx_chain_t’赋值给‘struct ngx_buf_t *’时类型不兼容
             b = hc->busy[i];
               ^
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] 错误 1
make[1]: 离开目录“/usr/local/src/nginx-1.13.6”
make: *** [build] 错误 2
openssl-1.1.0f

**Comment by spacewander** [comment]
@qist 
Duplicated with #1051.

**Comment by spacewander** [comment]
BTW, OpenSSL 1.1.0 is not supported yet.
You should use OpenSSL 1.0.2 instead.
See #922.

**Comment by agentzh** [comment]
Closing due to duplication.
