### ISSUE TITLE
 how to guarantee the timer run only once

### ISSUE THREAD

**Issue by playaround88** [openresty/lua-nginx-module#1210]
hi master
I am also programmer from china. I am a new openresty user, and is your fans!
Get to the point, I just write a dynamic web gate, which use "init_worker_by_lua" start a timer,fetch servers from consul  Periodically. But  I found that if worker_processes set to mult, timer also will be mult run, ngx.timer.appending_count/running_count as if not effective, and I also tried the lua-resty-lock module. Now I am confused for how can i guarantee the timer run only once?

thank u very much!

**Comment by playaround88** [comment]
Sorry, just after I post the issue, an idea occurred to me.
use lua-resty-lock and a shared DICT before start a timer maybe works!
Dose the idea true?
I will try later.
Sorry again!

**Comment by playaround88** [comment]
it's works!
thanks anyway!

**Comment by playaround88** [comment]
Maybe I found a bug
I have test again again
I just invoke ngx.time() and set the value to shared DICT will occur this exception
`
2017/12/16 20:07:25 [error] 15635#15635: init_worker_by_lua_file error: /usr/local/openresty/lualib/resty/lock.lua:151: API disabled in the context of init_worker_by_lua*
stack traceback:        [C]: in function 'sleep'
        /usr/local/openresty/lualib/resty/lock.lua:151: in function 'lock'
`
my code show below(for timer worker process died, and new worker start)
`
local now = ngx.time()
local lock,err = resty_lock:new("route")
if not lock then
    ngx.log(ngx.ERR,"failed to create lock: ", err)
end

local elapsed, err = lock:lock("add_timer")
ngx.log(ngx.ERR,"locked elapsed: ", elapsed, ", ", err)

local added = ngx.shared.route:get("timer")
if not added or now-added > 10 then
    ngx.log(ngx.ERR,"no timer flag in dict, add a timer")
    local ok, err = ngx.timer.at(0,sync_consul)
    if not ok then
        ngx.log(ngx.ERR, "failed to create timer: ", err)
        return
    end
    ngx.shared.route:set("timer",now)
end

ngx.log(ngx.ERR,"before release the add_timer lock")
local ok, err = lock:unlock()
if not ok then
    ngx.log(ngx.ERR,"failed to unlock: ", err)
end
`

**Comment by spacewander** [comment]
@playaround88 
You better to use `ngx.worker.id` to run your timer in one worker only.

lua-resty-lock uses `ngx.sleep` internally, and `ngx.sleep` could not be used in `init_by_worker*` phase.
See https://github.com/openresty/lua-resty-lock#description.

**Comment by playaround88** [comment]
I try some way to guarantee only one timer run( it fetch servers info from consul Periodically). but sadly, because Nginx process model, it's maybe impossible! when an worker died Nginx will start a new one 
immediately, but the timer is append to the worker. At that time, cannot to detect the timer in other worker is or not running.

**Comment by spacewander** [comment]
@playaround88 
I have already mentioned to use `ngx.worker.id` instead.
The `ngx.worker.id` will keep the same even when the worker is respawned.

**Comment by playaround88** [comment]
Wow, it's good news!
Thank u very much!
