### ISSUE TITLE
header_filter_by_lua_file not working with self-defined header

### ISSUE THREAD

**Issue by jgao-aa** [openresty/lua-nginx-module#1211]
We have some self-defined header that needs to be set by proxied server behind Nginx and we want to strip them by header_filter_by_lua_file in Nginx configuration.
After including a lua script in server level config as below, it turns out that "content-length" can be stripped. But for "strict-transport-security", "X-Frame-Options" and self-defined "X-Blocked-By", the filter doesn't stripped them.

> local internal_ip = ngx.var.internal_ip
> if internal_ip == "true" then
>    ngx.header['content-length'] = nil
>    ngx.header['strict-transport-security'] = nil
>    ngx.header['X-Frame-Options'] = nil
>    ngx.header['X-Blocked-By'] = nil
> end

**Comment by spacewander** [comment]
@jgao-aa 
I could not reproduce it in my machine with configure below:
```nginx
server {
        listen 9999;
        header_filter_by_lua_block {
            ngx.header['content-length'] = nil
            ngx.header['strict-transport-security'] = nil
            ngx.header['X-Frame-Options'] = nil
            ngx.header['X-Blocked-By'] = nil
        }

        location = /backend {
            content_by_lua_block {
                ngx.header['strict-transport-security'] = "a"
                ngx.header['X-Frame-Options'] = "b"
                ngx.header['X-Blocked-By'] = "c"
                ngx.say("OK")
            }
        }

       location = /proxy {
            proxy_pass http://127.0.0.1:9999/backend;
       }
}
```
```bash
￥ curl localhost:9999/proxy -i
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 19 Dec 2017 10:09:49 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

OK
```

Could you provide a minimal case to reproduce the issue?

**Comment by jgao-aa** [comment]
@spacewander , thanks for the quick reply. I double-checked and found that we have some conflicting config in Nginx http module. Please consider this closed:)
