### ISSUE TITLE
ngx.exec @location  到upstream +(加号) 不会转义

### ISSUE THREAD

**Issue by axingblog** [openresty/lua-nginx-module#1214]
nginx version: nginx/1.12.1
ssl version: libressl-2.5.5
ngx_devel_kit: v0.3.0
lua-nginx-module: v0.10.11

使用nginx + lua 做 阿里云OSS 代理自动签名.
使用lua 代码 和nginx 配置 采用 https://yq.aliyun.com/articles/8532 这里
发现  ngx.exec @location  到upstream + 不会转义 

原始请求如下:
http://192.168.1.251/v1/oss/ec-4gvoice-test/amr/2017/12/20/2160357_%2B8618600866585_1513756119880_101.amr

到upstrem 请求变成了 GET  /ec-4gvoice-test/amr/2017/12/20/2160357_+8618600866585_1513756119880_101.amr

'+' 号没转义

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, it's standard nginx proxying semantics, not our problem.
