### ISSUE TITLE
ngx.re split bug

### ISSUE THREAD

**Issue by ms2008** [openresty/lua-nginx-module#1217]
### snippet

```lua
./resty -e '
     local ngx_re = require "ngx.re"
     
     local raw_list = {
         "1\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15",
         "1\x1fT\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15",
         "1\x1fT\x1fT\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15"
     }
     
     for _,v in ipairs(raw_list) do
         local col_list = ngx_re.split(v, "\\x1F")
         print(#col_list, "\t", table.concat(col_list, "|"))
     end
'
```

### openresty/1.13.6.1

```
9	1|T|||||||15
9	1|T|T||||||15
10	1|T|T|T||||||15
```

### openresty/1.11.2.4

```
15	1|T|||||||||||||15
15	1|T|T||||||||||||15
15	1|T|T|T|||||||||||15
```

**Comment by changjiasheng** [comment]
确实有

**Comment by spacewander** [comment]
@ms2008 
I think it was a bug in openresty/1.11 and got fixed in openresty/1.13.
The result under `openresty/1.11` doesn't exclude the delimiter when it try to split multiple `\x1f`.

**Comment by ms2008** [comment]
@spacewander 
Have this been confirmed? I'd want to see convincing, quantitative proof.

**Comment by spacewander** [comment]
@ms2008 
This is only my personal thought. Let cc @agentzh to confirm if this behavior is a bug or not.

**Comment by ms2008** [comment]
Thanks for pointing your comment out. I started this discussion on OpenResty-en mailing list:

https://groups.google.com/forum/#!topic/openresty-en/9ygmZ6fBhOA

**Comment by agentzh** [comment]
The code example above is very painful to read, at least for me.

Generally we are following perl’s split() function’s behavior here.

**Comment by ms2008** [comment]
@agentzh 
Well. I think I didn't make this clear.

The example above I used the Control Character: `\x1f` as delimiter to split strings. However, the result under `openresty/1.13.6.1` looks strange, it should been return 15 substrings of list. Is there a bug?

Awaiting reply from all regex experts..

**Comment by agentzh** [comment]
@ms2008 I just tried your example using perl:

```perl
use v5.10.1;
use strict;
use warnings;

my @raw_list = (
    "1\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15",
    "1\x1fT\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15",
    "1\x1fT\x1fT\x1fT\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f15",
);

for my $v (@raw_list) {
    my @col_list = split /\x1F/, $v;
    say scalar @col_list, "\t", join "|", @col_list;
}
```

And the result is

```
$ perl a.pl
15      1|T|||||||||||||15
15      1|T|T||||||||||||15
15      1|T|T|T|||||||||||15
```

Seems like in this case, openresty 1.11.2.4's behavior is correct. @thibaultcha Will you look into this regression in the latest OpenResty 1.13.6.1? Thanks!

**Comment by thibaultcha** [comment]
Thanks for the report. I just proposed a fix at openresty/lua-resty-core#159 - awaiting for feedback!

**Comment by thibaultcha** [comment]
https://github.com/openresty/lua-resty-core/pull/159 has just been merged. We could close this once it is released.

**Comment by agentzh** [comment]
We can close this now :)
