### ISSUE TITLE
lua_shared_dict :Can I dynamic create lua_shared_dict and dynamic get dict by ngx.shared.DICT(the DICT can be a variable)?

### ISSUE THREAD

**Issue by mengjuan** [openresty/lua-nginx-module#1220]
Our company wants to use openResty do spy right control. So there are many spy datas need to cache in OpenResty.
    I used the lua_shared_dict to store the spy datas at the present. It worked fine~
    At now, we want to upgrade it to supports multi domains. It only support us domain now, if I want to it supports Canada domain, I need to modify the code and new some lua_shared_dict, I want to it can dynamic support this.
    Do I have any method to dynamic create the lua_shared_dict and dynamic get dict by ngx.shared.DICT(the DICT can be a variable)?
   Thank you so much~~

**Comment by spacewander** [comment]
> Can I dynamic create lua_shared_dict?

No. The memory used by `lua_shared_dict` is  allocated before spawning Nginx worker, so that they could be shared across multiple worker processes.

BTW, why not add prefix to your key? For example, `"us:" .. key` means key for us data, `"ca:" .. key` means key for ca data.

**Comment by mengjuan** [comment]
Thank you spacewander, thank you for your reply.
Actually we don't want to mix the us and ca data together.  I will allocate two  lua_shared_dict for us and ca .
Do I have any method to dynamic to invoke the lua_share_dict by its name? 
Like below:
I defined two dict in http block:
lua_shared_dict us 10m;
lua_shared_dict ca 10m;
Can I invoke them in ***by_lua_block like below:
local dictname = "us"
ngx.shared.dictname:get()

It seems don't support this invoke way. Do you have any suggestion on this?
Thank you again~~

**Comment by spacewander** [comment]
@mengjuan 
You need to use `ngx.shared[dictname]:get()` instead.
Note that `ngx.shared.dictname` means accessing the value of attribute `dictname`, not attribute `us` or `ca`.

**Comment by mengjuan** [comment]
Got it , I have try and it works ~~
Thank you so much ,@spacewander .
