### ISSUE TITLE
log bug: log a wrong phase

### ISSUE THREAD

**Issue by yandongxiao** [openresty/lua-nginx-module#1232]
this is my test code
```
daemon off;
error_log logs/error.log info;
worker_processes 1;

events{}

http {
    server {
        location / {
            rewrite_by_lua_block {
                ngx.ctx.name = "hello"
            }

            content_by_lua_block {
                ngx.log(ngx.INFO, ngx.ctx.name)
            }

            body_filter_by_lua_block {
                ngx.log(ngx.INFO, ngx.ctx.name)
            }
        }
    }
}
```

and this is my log
```
2018/01/11 17:41:36 [notice] 69083#2161562: start worker process 69084
2018/01/11 17:41:37 [info] 69084#2161563: *1 [lua] content_by_lua(test.conf:16):2: hello, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
2018/01/11 17:41:37 [info] 69084#2161563: *1 [lua] content_by_lua(test.conf:16):2: hello, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
2018/01/11 17:41:37 [info] 69084#2161563: *1 kevent() reported that client 127.0.0.1 closed keepalive connection
```
>
- the phase is logged wrong
- the log problem is triggered  when lua code is the same but at different phase
- both mac and linux system have this problem

**Comment by spacewander** [comment]
@yandongxiao
Just provide a quick fix for the bug you found.

**Comment by qlees** [comment]
Logging it in contet_by_lua, isn't it?

**Comment by agentzh** [comment]
It's just that the Lua code chunk name is wrong. Not sure if we can swap the loaded Lua code chunks' names on-the-fly. The easiest way is to stop sharing identical inlined Lua code chunks across different `*_by_lua` and `*_by_lua_block` handlers. For nginx.conf having many identical Lua code snippets (especially when using nginx's `include` directive), @spacewander's fix will lead to more Lua GC objects at runtime and also more GC CPU overhead. Well, maybe it's not a big deal.

**Comment by agentzh** [comment]
Adding support for swapping Lua code check names for already loaded Lua code chunks would require patching the LuaJIT core and expose such an API, which is nontrivial and may not worth the troubles.

**Comment by spacewander** [comment]
@agentzh 
The GC overhead is acceptable, since it could not be too complex `include` rules with many identical Lua code snippets for nginx configuration files written by human.

BTW, if someone has written many identical Lua code snippets, it is too bad for the sake of maintainability. The GC penalization is not the biggest problem. They should put the code into a file and load the same file in all places.

**Comment by agentzh** [comment]
The fix has already been merged in master. Thanks!
