### ISSUE TITLE
Nested `rewrite` inside block with `rewrite_by_lua` causes "http reading blocked"

### ISSUE THREAD

**Issue by twistedfall** [openresty/lua-nginx-module#1235]
Hello everyone,

I'm having problem with the following reduced nginx configuration file:
```nginx
server {
	listen              80;

	server_name         testdomain.com;

	error_log           /tmp/debug.log debug;

	rewrite_by_lua_block {
	}

	location /url1 {
		rewrite ^ /url2;
	}
}
```
When you do a request to `http://testdomain.com/url1` the http client just hangs and later terminates by timeout. This is the debug log of nginx for that request: https://gist.github.com/twistedfall/f1058fd6cab4b7d588f28f4c5e61767a.

This problem only happens when `rewrite_by_lua_no_postpone` is `on`. The code inside `rewrite_by_lua_block` doesn't seem to matter. I'm using `nginx` v1.13.8 with `lua-nginx` v0.10.11.

The workaround as far as I can see is to replace `rewrite` directive with `rewrite_by_lua_block` with the corresponding logic inside.

I have tried searching for this, but I haven't been able to find anything explaining such behaviour. Can you please tell me what's happening here? Is it a bug?

**Comment by agentzh** [comment]
@twistedfall Seems like you forgot to define a default `location / {}`?

**Comment by twistedfall** [comment]
@agentzh Well, this configuration file, though minimal, is still valid and it works (replies with 404, not hangs) if I set `rewrite_by_lua_no_postpone` to `off`. But I tried adding `location /` anyway, it doesn't change the behavior:
Option 1:
```nginx
server {
	listen              80;
	server_name         testdomain.com;
	error_log           /tmp/debug.log debug;
	rewrite_by_lua_block {
	}

	location / {
	}
	
	location /url1 {
		rewrite ^ /url2;
	}
}
```
Option 2:
```nginx
server {
	listen              80;
	server_name         testdomain.com;
	error_log           /tmp/debug.log debug;

	rewrite_by_lua_block {
	}

	location / {
		location /url1 {
			rewrite ^ /url2;
		}
	}
}
```
Option 3:
```nginx
server {
	listen              80;
	server_name         testdomain.com;
	error_log           /tmp/debug.log debug;

	location / {
		rewrite_by_lua_block {
		}

		location /url1 {
			rewrite ^ /url2;
		}
	}
}
```

**Comment by agentzh** [comment]
@twistedfall I just tried your `Option 1` example provided above with ngx_lua v0.10.11 + nginx 1.13.8 and the request `GET /url1` finishes very quickly and returns 404 as expected:

```
$ time curl -i -sS -X GET --connect-timeout 60 http://127.0.0.1:1984/url1
HTTP/1.1 404 Not Found
Server: nginx/1.13.8
Date: Wed, 17 Jan 2018 19:12:00 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>

real	0m0.014s
user	0m0.004s
sys	0m0.006s
```

And the error.log file shows the following message:

```
2018/01/17 11:12:00 [error] 88748#0: *2 open() "/home/agentzh/git/lua-nginx-module/t/servroot/html/url2" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /url1 HTTP/1.1", host: "127.0.0.1:1984"
```

So it tries to open the url2 file on the file system, as expected.

I've put the full debugging logs produced on my side here, for your reference:

https://gist.github.com/agentzh/a81602a97dbd6cf466110f664e6cd033

The full `nginx.conf` file that I used is here:

https://gist.github.com/agentzh/75d8b838e4c330b153bd4c46861bd553

(this nginx.conf contains some unrelated "noises", which were boilerplate generated by the Test::Nginx::Socket test scaffold developed by ourselves. They should not be relevant though).

And indeed, removing the `location / {}` part does not affect the result in this example.

**Comment by agentzh** [comment]
@twistedfall After having another look at your nginx debugging logs given above, I noted the following lines:

```
2018/01/16 15:28:53 [debug] 22621#0: *114 video_proxy subrequest handler
2018/01/16 15:28:53 [debug] 22621#0: *114 video_proxy declined, module not enabled at this location
```

This apparently some unknown 3rd-party modules engaged in. Please remove all such 3rd-party nginx C modules not maintained by us (the openresty team) nor the official nginx team and try again.

We do not want to waste our time debugging other 3rd-party module developers' mistakes or issues.

**Comment by twistedfall** [comment]
Thank you for checking! As far as I can see this is definitely not the external module, I've tried building with only debug and lua-nginx and it's still reproducible. But it looks like the environment has something to do with it, with the same binary I'm seeing problem on one machine, but not the other. I'll continue investigating, but I'm closing this report for now, if I have anything, I'll follow up. Thanks!

**Comment by twistedfall** [comment]
I was to quick to close the issue. I have a reliable way to reproduce it with vanilla nginx and only lua-nginx-module:

```bash
wget http://nginx.org/download/nginx-1.13.8.tar.gz
git clone https://github.com/openresty/lua-nginx-module -b v0.10.11

tar xzf nginx-1.13.8.tar.gz
cd nginx-1.13.8/

./configure --with-debug --add-module=../lua-nginx-module --prefix=/tmp --error-log-path=error.log --conf-path=nginx.conf --pid-path=nginx.pid --lock-path=nginx.lock --http-log-path=access.log
make
```

Create /tmp/nginx.conf with the following contents:
```nginx
events {}

http {
	rewrite_by_lua_no_postpone on;
	server {
		listen              80;
		server_name         testdomain.com;
		error_log           /tmp/debug.log debug;

		rewrite_by_lua_block {
		}

		location /url1 {
			rewrite ^ /url2;
		}
	}
}
```

Run it:
```bash
sudo ./nginx-1.13.8/objs/nginx
```

And do a curl request:
```bash
curl -v http://127.0.0.1/url1
```

It will hang. I've tested this on Ubuntu 14.04 and Gentoo systems. I have also tried doing the same with `nginx v1.13.6`, the behaviour is the same.

**Comment by agentzh** [comment]
@twistedfall The `rewrite_by_lua_no_postpone on` is the hint that I need. Sorry I missed it in your original issue description. Already fixed in the git repository as commit 9e5cc6e.

Thanks for the report!

**Comment by twistedfall** [comment]
@agentzh Thanks a lot! I've applied the patch to `v0.10.11` and it solves the issue in my case.

**Comment by kpunit** [comment]
I am trying same thing using rewrite in server block and using resty_template to server a html but template_root variable is not working. Full path in template_render() works properly. 
Any idea whats wrong?
