### ISSUE TITLE
How to detect current context?

### ISSUE THREAD

**Issue by yangxikun** [openresty/lua-nginx-module#1236]
I encounter a problem: `API disabled in the current context, context: init_worker_by_lua*`
I need to detect current context, so my code can use ngx.var correctly.
Thanks.

**Comment by dndx** [comment]
You should not really attempt to use `ngx.var` in phases it doesn't support. If that is not an option, take a look at [`ngx.get_phase`](https://github.com/openresty/lua-nginx-module#ngxget_phase) for getting the current phase.

**Comment by yangxikun** [comment]
`ngx.get_phase` is what I need. Thanks.
