### ISSUE TITLE
Write nginx variable (access_by_lua) cannot be checked with "if"  

### ISSUE THREAD

**Issue by HanXHX** [openresty/lua-nginx-module#1240]
## Issue
`access_by_lua` doesn't write properly variable... Nginx `echo` works well, but i can't check variable with a Nginx `if`. I know `set_by_lua` should be perfect, but it doesn't work with redis module.

## System Infos

- OS : Debian Stretch
- nginx version + ngx_lua: 1.10.3 (shipped with Debian Stretch)

## Example

```nginx
server {
	listen 80;
	server_name experimental.vagrant;

	location / {

		set $mymode '';

		access_by_lua '
			local redis = require "redis"

			-- connect redis
			local red = redis:new()
			red:set_timeout(1000)
			red:connect("127.0.0.1", 6379)

			local res = red:get("test")

			if res == "0" then
				ngx.log(ngx.ERR, "set S")
				ngx.var.mymode = "S"
			else
				ngx.log(ngx.ERR, "set P")
				ngx.var.mymode = "P"
			end
		';

		#set $mymode S;

		if ($mymode = S) {
			#proxy_pass http://$myproxy/request_uri;
			echo "$mymode = S";
			break;
		}

		default_type text/plain;
		echo ">>> $mymode";
	}
}
```

## Actual

```
$ redis-cli set test 0
OK
$ curl 'http://experimental.vagrant'
>>> S
$ redis-cli set test 1
OK
$ curl 'http://experimental.vagrant'
>>> P
```

## Expected

```
$ redis-cli set test 0
OK
$ curl 'http://experimental.vagrant'
S = S
$ redis-cli set test 1
OK
$ curl 'http://experimental.vagrant'
>>> P
```

```

**Comment by agentzh** [comment]
@HanXHX You misunderstand nginx directive running order. Access_by_lua* always run after `if`, no matter how you arrange them in `nginx.conf`. Better read my nginx tutorials on nginx directive running order before you write nontrivial nginx.conf to save your time (and ours):

https://openresty.org/download/agentzh-nginx-tutorials-en.html

**Comment by michel-leonard** [comment]
Firefox don't find the term `if(` or `if (` in the `https://openresty.org/download/agentzh-nginx-tutorials-en.html` tutorial.
