### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by erikcw** [openresty/lua-nginx-module#1249]
I believe OpenResty may have a memory leak.  I've repeatedly noticed my nginx server running out of memory over the last several months before crashing and needing a restart.  I've tried running it on boxes with more memory, but the same thing happens eventually.

```
2018/02/01 22:36:51 [crit] 28035#28035: *230136 [lua] web.lua:460: handle_error(): ERROR cfa9581b-42da-4ccd-ccfd-1ac8af16e89f_1517524611.346 - err: null trace: null, client: 172.30.6.51, server: _
2018/02/01 22:36:51 [error] 28035#28035: *230136 failed to run log_by_lua*: not enough memory while logging request, client: 172.30.6.51, server: _
2018/02/01 22:36:53 [crit] 28035#28035: *230322 [lua] web.lua:460: handle_error(): ERROR c6480863-74c6-4617-87f4-4a32f83493c2_1517524613.655 - err: null trace: null, client: 172.30.6.51, server: _
2018/02/01 22:36:53 [alert] 28033#28033: worker process 28035 exited on signal 6 (core dumped)
```
I've also seen:
```
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
```

I've tried locating it with stapp -- so far here is what I've found:
```
root@ip-172-30-5-125:/opt/openresty/nginx/conf/stapxx# ./samples/lj-gc-objs.sxx -x 28035 -D MAXACTION=90000000
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
Start tracing 28035 (/usr/local/openresty/nginx/sbin/nginx)

ERROR: Skipped too many probes, check MAXSKIPPED or try again with stap -t for more details.
main machine code area size: 196608 bytes
C callback machine code size: 4096 bytes
GC total size: 1206839764 bytes
GC state: propagate

6576378 upvalue objects: max=24, avg=24, min=24, sum=157833072 (in bytes)
4532037 function objects: max=144, avg=28, min=20, sum=128112048 (in bytes)
2085692 table objects: max=1572896, avg=108, min=32, sum=226262032 (in bytes)
1085306 userdata objects: max=5712, avg=622, min=27, sum=675990140 (in bytes)
95149 string objects: max=7030, avg=129, min=18, sum=12310451 (in bytes)
9136 thread objects: max=1648, avg=588, min=424, sum=5379352 (in bytes)
885 proto objects: max=2982, avg=254, min=74, sum=225149 (in bytes)
279 trace objects: max=2668, avg=659, min=160, sum=184008 (in bytes)
2 cdata objects: max=12, avg=12, min=12, sum=24 (in bytes)
JIT state size: 7296 bytes
global state tmpbuf size: 4096 bytes
C type state size: 2520 bytes

My GC walker detected for total 1206839764 bytes.
4161265 microseconds elapsed in the probe handler.
ERROR: probe overhead exceeded threshold
WARNING: Number of errors: 1, skipped probes: 101
WARNING: /usr/bin/staprun exited with status: 1
Pass 5: run failed.  [man error::pass5]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```
I'm running on Ubuntu 16:04 with `openresty/1.13.6.1` intstalled from the OpenResty repo.

Is there anything else I can provide that might help locate the source of the problem?

**Comment by agentzh** [comment]
@erikcw Looks like you have a memory leak in your own Lua code. You keep loading and registering new Lua function objects but without unloading them. The extremely high large number of those upvalue objects and function objects explain that.

For example, if you keep require() more and more new Lua modules in your Lua code, then that's a memory leak in your application, not in OpenResty.

Similarly, if you have a Lua table growing forever, that's your application's bug, not OpenResty. From the lj-gc-objs output above, it seems like you indeed have a huge table taking 1572896 bytes on its own (excluding the memory taken by its keys or values). You should investigate that huge table by the gdb tool lj-gc-path, for example:

https://github.com/openresty/openresty-gdb-utils#lgcpath

**Comment by erikcw** [comment]
Thanks @agentzh!

So I tried `lgcpath`, but it didn't seem to catch much:

```
(gdb) source luajit21.py
(gdb) lgcpath 100000 tab
path 000:[registry] ->Tab["tcp{client}"] ->Tab["__index"] ->Tab["send"] ->cfunc ->env ->Tab["loaded"] ->Tab["lapis"] ->Tab["app_cache"] ->Tab sz:786464 (GCobj*)0x41415e18 ->END
(gdb) lgc
The current memory size (allocated by GC): 677781795 bytes
```
I'd be grateful for any other suggestions on how I can find this leak in my lua code.

I'm only using a handful of globals in `init_by_lua`

```lua
init_by_lua_block {                                                                   
    -- init lua uuid module                                                           
    uuid = require 'resty.jit-uuid'                                                   
    uuid.seed() -- very important!                                                    
                                                                                      
    -- prometheus                                                                     
    prometheus = require("nginx.prometheus").init("prometheus_metrics")               
    metric_requests = prometheus:counter(                                             
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "uri", "status"})
    metric_latency = prometheus:histogram(                                            
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host", "uri"})   
    metric_connections = prometheus:gauge(                                            
    "nginx_http_connections", "Number of HTTP connections", {"state"})                
    metric_garbage_collection = prometheus:gauge(                                     
    "nginx_memory_gc", "Garbage collection size", {"worker"})                         
 
}                                                                                     
```

The bulk of my application code is in `content_by_lua_file "web.lua";` -- which comprises of a `lapis` application.  `web.lua` does `require()` several modules (and those in term may have their own `require` statements).

```lua
local lapis = require("lapis")
local lapis_util = require("lapis.util")
local date = require("date")
local cjson = require("cjson")
local console = require("lapis.console")
local utils = require("utils")
local config = require("lapis.config").get()
local matchtable = require("matchtable")
local fetch_url_from_upstream
fetch_url_from_upstream = function()...end
```

Should I move all of my `require()`s out of my `content_by_lua_file` and into `init_by_lua`?

Thanks again so much!

**Comment by erikcw** [comment]
I found it!  https://github.com/leafo/lapis/issues/203

Turns out that changing:
```
content_by_lua_file web.lua;
```
to:
```
            content_by_lua_block {
                require("lapis").serve("web")
            }
```
resolved the memory leak.

Thanks for all of your help!

**Comment by agentzh** [comment]
@erikcw OK, so it's indeed a leak in your application code (though in this case, the 3rd party library, Lapis).

**Comment by thibaultcha** [comment]
Sorry for replying to a close issue, but I want to point out something @erikcw is doing which might be dangerous for his application.

@erikcw I see you are using resty-jit-uuid (cool), but you are seeding the LuaJIT PRNG in the init phase, instead of init_worker (as instructed by resty-jit-uuid's manual). This is _highly_ dangerous since your NGINX workers will generate identical sequences of UUIDs, which defeats the purpose. Please move `uuid.seed()` to `init_worker_by_lua` instead, to ensure that each worker's Lua VM gets a different, unique seed.

**Comment by erikcw** [comment]
@thibaultcha great catch!  Thank you. I’m deploying a patch right now....
