### ISSUE TITLE
A problem with SHARED_DICT.incr

### ISSUE THREAD

**Issue by Justinmad** [openresty/lua-nginx-module#1251]
I am using the lua-resty-worker-events library provided by KONG, which uses the incr api in dict during the init_worker_by_lua phase. Then the worker process crashes, the program will continue to re-create the worker process, I do not have the basis of the C language can not provide a more detailed error message, the following is my program error message, hoping to help locate the problem:

2018/02/02 21:49:41 [notice] 32720#0: using the "epoll" event method
2018/02/02 21:49:41 [notice] 32720#0: nginx/1.13.8
2018/02/02 21:49:41 [notice] 32720#0: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
2018/02/02 21:49:41 [notice] 32720#0: OS: Linux 4.13.0-32-generic
2018/02/02 21:49:41 [notice] 32720#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2018/02/02 21:49:41 [notice] 32720#0: start worker processes
2018/02/02 21:49:41 [notice] 32720#0: start worker process 32721
2018/02/02 21:49:41 [notice] 32720#0: start worker process 32722
2018/02/02 21:49:42 [notice] 32720#0: signal 17 (SIGCHLD) received from 32722
2018/02/02 21:49:42 [alert] 32720#0: worker process 32722 exited on signal 11 (core dumped)
2018/02/02 21:49:42 [notice] 32720#0: start worker process 32725
2018/02/02 21:49:42 [notice] 32720#0: signal 29 (SIGIO) received
2018/02/02 21:49:42 [notice] 32720#0: signal 17 (SIGCHLD) received from 32721
2018/02/02 21:49:42 [alert] 32720#0: worker process 32721 exited on signal 11 (core dumped)
2018/02/02 21:49:42 [notice] 32720#0: start worker process 32727
2018/02/02 21:49:42 [notice] 32720#0: signal 17 (SIGCHLD) received from 32727
2018/02/02 21:49:42 [alert] 32720#0: worker process 32727 exited on signal 11 (core dumped)
2018/02/02 21:49:42 [notice] 32720#0: start worker process 32729
2018/02/02 21:49:42 [notice] 32720#0: signal 29 (SIGIO) received
2018/02/02 21:49:42 [notice] 32720#0: signal 17 (SIGCHLD) received from 32725
2018/02/02 21:49:42 [alert] 32720#0: worker process 32725 exited on signal 11 (core dumped)

This problem occurs when v0.10.12rc2 version is used, after the version is changed to v0.10.11 to solve this problem.

**Comment by agentzh** [comment]
@Justinmad We know nothing about Kong's internals so please try providing a minimal and standalone example that we can easily reproduce the issue without Kong on our side. We are not interested in investigating potential bugs in Kong (this one could be Kong's bug).

As a general rule of thumb, you should try fetching detailed information from the resulting core dump files otherwise your logs are not really helpful. See

https://www.nginx.com/resources/admin-guide/debug/#backtrace

BTW, nginx 1.13.8 is not yet an officially supported target of this lua-nginx-module. See

https://github.com/openresty/lua-nginx-module/#nginx-compatibility

So you are on your own before we officially test that new version of the nginx core.

**Comment by agentzh** [comment]
@Justinmad I suggest you contract the Kong team first instead of us. Also, I recommend you try formal OpenResty releases first since you may run into known nginx core bugs which do not exist in the OpenResty releases.

**Comment by thibaultcha** [comment]
@Justinmad Please follow agentzh's suggestion and go ahead and open an issue in the lua-resty-worker-events repository :) Also, cc'ing @Tieske for visibility in this issue never gets reported over there.

@agentzh Sorry for the noise here.

**Comment by Tieske** [comment]
@Justinmad I didn't see a corresponding issue at https://github.com/Kong/lua-resty-worker-events . Did you resolve your issue?
