### ISSUE TITLE
How can I do this using LUA?

### ISSUE THREAD

**Issue by c0debreaker** [openresty/lua-nginx-module#1255]
I'm new to LUA. Here is the rule I have right now.

```
location ~ /app/(?<hashcode>...)/?$ {
  proxy_pass http://internal-server:8080/app/${hashcode}/;
}
```

This is an existing rule. Right now, hashcode is a plain readable text string like `1.2.0.139`. Yesterday, I built and Nginx with lua support. What I want to do is convert hash code into a readable string using lua. I'm not sure if there is a lua function that can help with decoding/encoding a passed string or an approach that is similar using lua.

An example http call for that rule would be something like http://www.example.com/app/05dabf7f0a61ce1066d17a97ddb3a1f6

The string `05dabf7f0a61ce1066d17a97ddb3a1f6` will be converted by lua into a readable string like 1.2.0.139. This value will be inserted to a variable that will be used in proxy_pass.

So
```
location ~ /app/(?<hashcode>...)/?$ {
  # lua_script_something to inject calculated value into decoded_hashcode 
  proxy_pass http://internal-server:8080/app/${decoded_hashcode}/;
}
```

**Comment by yuz10** [comment]
```
set $decoded_hashcode "";
location ~ /app/(?<hashcode>...)/?$ {
	access_by_lua_block{
		ngx.var.decoded_hashcode = "decode"..ngx.var.hashcode
	}
	proxy_pass http://internal-server/app/${decoded_hashcode};
}
```

**Comment by c0debreaker** [comment]
Thank you but how is that being decoded?

**Comment by yuz10** [comment]
I just add 'decode' before the hash code, to represent the string is decoded. You can write a lua function instead.

**Comment by c0debreaker** [comment]
Got it. I'd like to learn how to write a lua function. Can you please direct me to a link that I can read about it?

**Comment by hanssywong** [comment]
You can write lua code within the {} block for your decoder code.

**Comment by c0debreaker** [comment]
Ok. I forgot that lua is a programming language. I'm going to study lua programming today. I guess we can write any valid lua code inside {}. Thanks a lot!

**Comment by c0debreaker** [comment]
Here is my latest code. I'm getting a nil output on the decryption.

The code `ngx.say(ngx.var.hashcode)` is working. I see the value I passed.
However, `ngx.say(aes_128_cbc_md5:decrypt(ngx.var.hashcode))` is outputing nil

What is wrong?

```
location ~ /app/(?<hashcode>.*)/?$ {
  access_by_lua_block {
    local aes = require "resty.aes"
    local str = require "resty.string"
    local aes_128_cbc_md5 = aes:new("AKeyForAES")
    ngx.say(ngx.var.hashcode)
    ngx.say(aes_128_cbc_md5:decrypt(ngx.var.hashcode))
    ngx.var.decoded_hashcode = aes_128_cbc_md5:decrypt(ngx.var.hashcode)
  }
  proxy_pass http://localhost:5555/app/${decoded_hashcode};
}
```

**Comment by c0debreaker** [comment]
I figured out why. The value I was passing was the result of str.to_hex() function. Is there a function to convert the hex value I was passing to the raw encrypted string?

**Comment by c0debreaker** [comment]
Here is my latest code and it's almost working. The only remaining issue is that it doesn't pass the value to my global $decoded_hashcode variable.

The value of `$decoded_hashcode` in return code and in the proxy_pass are blank.

```
set $decoded_hashcode "";

location ~ /app/(?<hashcode>.*)/?$ {
  content_by_lua_block {
    function fromhex(str)
      return (str:gsub("..", function (cc)
        return string.char(tonumber(cc, 16))
      end))
    end
    local aes = require "resty.aes"
    local str = require "resty.string"
    local aes_128_cbc_md5 = aes:new("AKeyForAES")
    local decodedhashcode = aes_128_cbc_md5:decrypt(fromhex(ngx.var.hashcode))
    ngx.say(decodedhashcode) <-- this looks great! It shows the correct value
    ngx.var.decoded_hashcode = decodedhashcode
  }
 #return 200 ${decoded_hashcode}; <-- it's empty
 #proxy_pass http://localhost:5555/app/${decoded_hashcode}; <-- this is also empty
}
```

**Comment by c0debreaker** [comment]
I found the bug! I change the code

```
set $decoded_hashcode "";
```

to

```
set $decoded_hashcode "superman";
```

Now I see the value on my browser as superman. It's not being overwritten. Is this a LUA bug?

**Comment by spacewander** [comment]
@c0debreaker 
You need to change `content_by_lua_block` to `access_by_lua_block`.
Beware of Nginx's phase order.

**Comment by c0debreaker** [comment]
Ok, trying that now.

**Comment by c0debreaker** [comment]
I created a new one, it doesn't work. It just showed `Hey!` on my screen

```
location /greetme {
  set $greetme '';
  access_by_lua '
    ngx.var.greetme = "Hi Google"
  ';
  return 200 "Hey! $greetme";
}
```

**Comment by c0debreaker** [comment]
I fixed the earlier code with decodedhash by moving `set $decoded_hashcode "";` inside location 
I am now able to proxy_pass to my backend netcat server

**Comment by agentzh** [comment]
@c0debreaker You know that the `return` directive runs in the rewrite phase, and thus always before your `access_by_lua*` handler (which runs in the access phase)?

**Comment by agentzh** [comment]
@c0debreaker Your code above indicates that you didn't ;)
