### ISSUE TITLE
how to replace existing 400 page

### ISSUE THREAD

**Issue by junhui** [openresty/lua-nginx-module#1256]
hi, for replace existing 400 page, i tried `error_page`, it doesn't work, can anyone help on this

For example:
**Request**
`curl "https://openresty.org/Windows/system.ini"%"00" -H "Host: openresty.org" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" -H "Cache-Control: max-age=0"
`

**Default Response**
```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

how to replace the `response` to my own html?

thanks and appreciate!

**Comment by hanssywong** [comment]
error_page 400 http://<your link>;

**Comment by hanssywong** [comment]
http://(your link);

**Comment by agentzh** [comment]
Intercepting and redirecting 400 can be dangerous since 400 may be initiated in a very early phase of the nginx request processing when the request header is not fully read and the request data structure is not really initialized, thus leading to potential segfaults and etc. Better avoid this.
