### ISSUE TITLE
add_header fail when call function (ngx.print(_M.subscriber()) )   in  Lua

### ISSUE THREAD

**Issue by VuDn5** [openresty/lua-nginx-module#1257]
**Hi everybody!  
I'm Vu and i come from Viet Nam.  i have a API like that http://"MyIP"/subscriber/check-forget-passwd.  Client cannot call API and error is : cross domain, i fix it by**
`add_header 'Access-Control-Allow-Origin' '*';`
 **That My configure** 
`        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                client_max_body_size 50k;
                client_body_buffer_size 50k;
                default_type 'text/plain;charset=utf-8';
                content_by_lua '
                        ngx.print(_M.subscriber())
                        ngx.print("adf")
                        ngx.req.set_header("Access-Control-Allow-Origin", "*")
                        ngx.req.set_header("ContentType", "application/json")
                        return
                ';` 
  **it's cannot response any" response header" but if i remove the line** 
`ngx.print(_M.subscriber())
_M is a nomarl function( or class or may be like class) that i write by Lua`
everything back is ok, there are my output: 
`server:
openresty/1.11.2.1
date:
Mon, 12 Feb 2018 03:25:33 GMT
content-type:
text/plain;charset=utf-8
transfer-encoding:
chunked
connection:
keep-alive
access-control-allow-origin:
*; *
access-control-allow-credentials:
true; true
access-control-allow-methods:
GET, POST, OPTIONS; GET, POST, OPTIONS
access-control-allow-headers:
DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type; DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type`

**This is Bug or my config errror and how can i  fix it? 
Thank for read!
Vu**

**Comment by spacewander** [comment]
@VuDn5 
Could you re-format your code snippets? Your example is squeezed and I read it serveral times, but still could not recognize all.

BTW, `content_by_lua` is deprecated, you should use `content_by_lua_block` or `content_by_lua_file` instead. And `ContentType` is not a standard header name, maybe you mean `Content-Type`?

**Comment by VuDn5** [comment]
Thanks @spacewander !  i have a solution for that!    i use 
`more_set_headers 'Access-Control-Allow-Origin: *' ;`     to fix that problem and successed, thanks for you help!~
