### ISSUE TITLE
append binary data to specific file

### ISSUE THREAD

**Issue by HadiAbbasi** [openresty/lua-nginx-module#1258]
Hi there
is there any standard and clean way to collect (append) binary data on a single cache file?
I want to separate and save some binary data (say some files) on a cache file inside my openresty project!
thanks a lot...

**Comment by agentzh** [comment]
@HadiAbbasi I don't know what "cache file" means. If you are talking about nginx's http cache's cache file on the disk, no, it's not possible without hacking the nginx core.
