### ISSUE TITLE
Balancer is not triggered 

### ISSUE THREAD

**Issue by sukidesuaoi** [openresty/lua-nginx-module#1263]
Hi,

I'm currently using lua-nginx included in Kong. However, I am encountering some error where in the balancer is not triggered. I'm not sure why it is skipped for this particular case. 

Example of a successful run:
```
2018/02/20 03:05:03 [info] 32#0: *362 client 127.0.0.1 closed keepalive connection
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:20: rewrite(): executing plugin "kong_middleman": rewrite
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:24: access(): executing plugin "kong_middleman": access
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] init.lua:331: balancer(): setting address (try 1): 172.18.80.231:8001
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:28: header_filter(): executing plugin "kong_middleman": header_filter
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:32: body_filter(): executing plugin "kong_middleman": body_filter
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:32: body_filter(): executing plugin "kong_middleman": body_filter
2018/02/20 03:05:04 [debug] 32#0: *367 [lua] base_plugin.lua:36: log(): executing plugin "kong_middleman": log
2018/02/20 03:05:04 [info] 32#0: *367 client 172.19.0.3 closed keepalive connection
```

Example of not successful:
```
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:24: access(): executing plugin "middleman": access
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:28: header_filter(): executing plugin "middleman": header_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:32: body_filter(): executing plugin "middleman": body_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:32: body_filter(): executing plugin "middleman": body_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:32: body_filter(): executing plugin "middleman": body_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:32: body_filter(): executing plugin "middleman": body_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:32: body_filter(): executing plugin "middleman": body_filter
2018/02/20 07:03:03 [debug] 32#0: *186 [lua] base_plugin.lua:36: log(): executing plugin "middleman": log
2018/02/20 07:03:25 [debug] 32#0: *194 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1519110180.415 to: 1519110205.06
```

I noticed that the balancer() is not triggered in the second example.
Is there any reason why the it is being skipped?

Thank you in advance

**Comment by spacewander** [comment]
@sukidesuaoi 
I think you should ask the question in the Kong's repo.
There are many ways to skip balancer phase. Only the developers of Kong could answer if the skip of balancer phase is by design or by mistake.

**Comment by sukidesuaoi** [comment]
Hi @spacewander, Thank you for your answer.
For my reference purposes, would you give me some examples in skipping the balancer? are there given functions?

**Comment by spacewander** [comment]
Assumed we have Nginx configuration like this:
```
    upstream foo {
        server 127.0.0.1;
        balancer_by_lua_block {
            ngx.log(ngx.ERR, "running balancer")
        }
    }

    server {
        listen 9999;
        location = /test {
            -- running access_by_lua* here before running the proxy_pass directive
            proxy_pass http://foo;
        }
    }
```
The key point of skipping balancer is to skip the `proxy_pass` directive, as the balancer is running while proxying.

One way to do it, is to generate some output in `access_by_lua*` phase, which will skip `proxy_pass` directive( this directive runs in `content` phase) and run into `header_filter` phase directly. For example,
```
            access_by_lua_block {
                ngx.say("You should not pass")
            }
            proxy_pass http://foo;
```

Another similar way is to terminate the request with status code, like this:
```
            access_by_lua_block {
                ngx.exit(ngx.HTTP_BAD_REQUEST)
            }
            proxy_pass http://foo;
```

Because you have already generated the output or terminated the request **before** proxying the request, there is not reason for Nginx to proxy it anymore. If the request is not proxied, it has not change to run the balancer logic.

**Comment by sukidesuaoi** [comment]
Thank you so much for this @spacewander! 

I was able to fix the problem in the code. It seems that my method on how to get the authorization header is faulty. Logic wise it works, but somehow it makes it skip the balancer.

**Comment by thibaultcha** [comment]
Considering this fixed. If not, please ask such questions in the Kong repository, thank you.
