### ISSUE TITLE
UDP and threads disabled in ssl_session_fetch_by_lua*

### ISSUE THREAD

**Issue by tmthrgd** [openresty/lua-nginx-module#1264]
The documentation for [`ngx.socket.udp`](https://github.com/openresty/lua-nginx-module#ngxsocketudp) states that it is supported in `ssl_session_fetch_by_lua*` directives, while failing the context checks [here](https://github.com/openresty/lua-nginx-module/blob/3cde1d8aa1887e8b76356013a24a7602440d283e/src/ngx_http_lua_socket_udp.c#L140) and [here](https://github.com/openresty/lua-nginx-module/blob/3cde1d8aa1887e8b76356013a24a7602440d283e/src/ngx_http_lua_socket_udp.c#L201).

`ngx.socket.tcp` works fine in these as `NGX_HTTP_LUA_CONTEXT_SSL_SESS_FETCH` *is* included in those context checks. It looks like this was simply forgotten about in 5bcc53cab6a178bd75a6da1113f1bcda1b70077b and no one ever noticed.

The documentation for [`ngx.thread.wait`](https://github.com/openresty/lua-nginx-module#ngxthreadwait) also states support in these directives, while failing the context check [here](https://github.com/openresty/lua-nginx-module/blob/3cde1d8aa1887e8b76356013a24a7602440d283e/src/ngx_http_lua_uthread.c#L126). Interestingly, the documentation for [`ngx.thread.kill`](https://github.com/openresty/lua-nginx-module#ngxthreadkill) is *lacking* support for `ssl_certificate_by_lua*`, and yet it passes [this](https://github.com/openresty/lua-nginx-module/blob/3cde1d8aa1887e8b76356013a24a7602440d283e/src/ngx_http_lua_uthread.c#L224) context check anyway.

It seems like 5bcc53cab6a178bd75a6da1113f1bcda1b70077b overlooked the context checks in [ngx_http_lua_socket_udp.c](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_socket_udp.c) and [ngx_http_lua_uthread.c](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_uthread.c), while both the documentation and implementation of `ngx.thread.kill` is currently wrong. I'll open a minimal PR to fix these issues.

**Comment by agentzh** [comment]
@tmthrgd Good catch! Yes, it just looks like a simple mistake in the context checks and/or the docs.

**Comment by thibaultcha** [comment]
Resolved since 97f0101e525b8f0c0f125ab50e381c936f0c2f10 is in master. Thanks for the report!
