### ISSUE TITLE
openssl-1.1.0g lua-nginx-module-0.10.11 error

### ISSUE THREAD

**Issue by gitboy123** [openresty/lua-nginx-module#1271]
0 -I src/stream \
	-o objs/addon/src/ngx_http_lua_consts.o \
	/data/server/nginx-waf/module/lua-nginx-module-0.10.11/src/ngx_http_lua_consts.c
/data/server/nginx-waf/module/lua-nginx-module-0.10.11/src/ngx_http_lua_module.c: In function ‘ngx_http_lua_merge_srv_conf’:
/data/server/nginx-waf/module/lua-nginx-module-0.10.11/src/ngx_http_lua_module.c:1022:37: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type [-Werror]
                                     ngx_http_lua_ssl_sess_fetch_handler);
                                     ^
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:82,
                 from /data/server/nginx-waf/module/lua-nginx-module-0.10.11/src/ddebug.h:13,
                 from /data/server/nginx-waf/module/lua-nginx-module-0.10.11/src/ngx_http_lua_module.c:11:
/data/server/nginx-waf/module/openssl-1.1.0g/.openssl/include/openssl/ssl.h:639:6: note: expected ‘struct SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *)’ but argument is of type ‘struct SSL_SESSION * (*)(struct SSL *, u_char *, int,  int *)’
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/data/server/nginx-waf/nginx-1.12.2'
make: *** [build] Error 2

**Comment by spacewander** [comment]
@gitboy123 
lua-nginx-module 0.10.11 doesn't support OpenSSL 1.1.0.
Could you try the latest lua-nginx-module 0.10.12rc2?

**Comment by andyone** [comment]
@spacewander I have checked. With `0.10.12rc2` nginx built without error.
