### ISSUE TITLE
having trouble in unlimited 302 redirect

### ISSUE THREAD

**Issue by nanqinlang** [openresty/lua-nginx-module#1275]
```nginx
location / {
    access_by_lua '
        random_initial = ngx.var.cookie_random
        if (random_initial == nil) then
            return ngx.redirect("/session_auth?url=" .. ngx.var.request_uri)
        end

        token_new = ngx.md5("sometimesnaive" .. ngx.var.remote_addr .. random_initial)
        if (ngx.var.cookie_token ~= token_new) then
            return ngx.redirect("/session_auth?url=" .. ngx.var.request_uri)
        end
    ';
}

location  ^~ /session_auth/ {
    access_by_lua '
        random_new = math.random(999999)
        token_standard = ngx.md5("sometimesnaive" .. ngx.var.remote_addr .. random_new)
        if (ngx.var.cookie_token ~= token_standard) then
            ngx.header["Set-Cookie"] = {"random=" .. random_new, "token=" .. token_standard}
            return ngx.redirect(ngx.var.arg_url)
        end
    ';
}
```

i use it in order to against CC attack, but `any session will be placed in unlimited 302 redirect`.

**Comment by spacewander** [comment]
@nanqinlang 
`/session_auth?url` doesn't match `location  ^~ /session_auth/`.
BTW, you should use `access_by_lua_block` instead of `access_by_lua`, the latter is deprecated.

**Comment by nanqinlang** [comment]
@spacewander  
thanks for reply.

though access_by_lua is `deprecated`, i think it is a simple way to view, and i prefer to use it, so will it takes me some problem...?

and about location, what location should i choose ?  
currently i find that whether i should use `location /session_auth { }`, but the target uri is like `/session_auth?url=article/2018/03/11/xxx.html`, i'm afraid that "location /session_auth" will only peer to uri like `/session_auth?url=xxx.html`

**Comment by spacewander** [comment]
> though access_by_lua is deprecated, i think it is a simple way to view, and i prefer to use it, so will it takes me some problem...?

Actually, `access_by_lua_block` is simpler, as using `access_by_lua` you may need to quote some special characters. Right now using `access_by_lua` is ok, but I can't guarantee that we will keep it in the future.

> i'm afraid that "location /session_auth" will only peer to uri like /session_auth?url=xxx.html

I don't quite understand what you means, but `/session_auth` should match `/session_auth?url=article/2018/03/11/xxx.html`.

**Comment by nanqinlang** [comment]
@spacewander  
thanks for reply, i'll try that `location /session_auth`.

BTW,  
>>Actually, access_by_lua_block is simpler, as using access_by_lua you may need to quote some special characters.

i don't know the reason why `access_by_lua_block is simpler`. Let us take a example:  
in `access_by_lua`, i should write `ngx.var.remote_addr` to use a variable. but if i use `access_by_lua_block`, how should i write ?...

**Comment by spacewander** [comment]
You should write `ngx.var.remote_addr` to use a variable, too.
For more information, please read the two links below:
https://github.com/openresty/lua-nginx-module#access_by_lua_block
https://github.com/openresty/lua-nginx-module#special-escaping-sequences

**Comment by nanqinlang** [comment]
@spacewander  
thanks for reply. case closed.
