### ISSUE TITLE
Cosocket :setkeepalive() in a a premature timer handler blocks nginx worker from exiting

### ISSUE THREAD

**Issue by kipras** [openresty/lua-nginx-module#1279]
If a TCP cosocket connection is opened in a timer handler which is called on Nginx exit (i.e. `premature = true`) and then kept alive with `:setkeepalive()` - then the worker that served that timer is prevented from exiting. You see `nginx: worker process is shutting down` in `ps -aux` output.

Also, if you restart Nginx, then you get alerts like this (and sometimes a core dump):
```
2018/03/16 18:46:25 [alert] 25633#0: *62 open socket #7 left in connection 4
2018/03/16 18:46:25 [alert] 25633#0: aborting
```

If the connection is either explicitly (via `:close()`) or implicitly closed though - this does not happen. This also doesn't happen if the timer runs normally (i.e. not prematurely).

* Versions:
nginx -V output:
```
nginx version: openresty/1.11.2.2
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_ssl_module
``` 
OpenResty: 1.11.2.2
Nginx: 1.11.2
ngx_lua: 0.10.7
OS: Ubuntu Linux 14.04 x64

* A minimal test case nginx.conf. Note that here the cosocket connects to this same Nginx server (on a different port), but that's only for the test case to be self-sustainable. The issue happens if the cosocket connects to a different server too. Also - we intentionally set the timer to a high value (100 seconds) to make sure that we will reload before it would normally run (to trigger a premature run). 
```
events {
  worker_connections 10000;
  multi_accept on;
  use epoll;
}

http {
  server {
    listen 80;

    server_name default_server;

    access_log logs/test.com_access.log;
    error_log logs/test.com_error.log;

    location / {
      content_by_lua_block {
        ngx.header["Content-Type"] = "text/plain"
        ngx.say("Hello planet!")

        -- This does not block Nginx worker from exiting
        local req_sock = ngx.socket.tcp()
        req_sock:connect("127.0.0.1", 8080)
        req_sock:setkeepalive()

        ngx.timer.at(100, function ()
          -- This blocks Nginx worker from exiting
          local timer_sock = ngx.socket.tcp()
          timer_sock:connect("127.0.0.1", 8080)
          timer_sock:setkeepalive()
        end)
      }
    }
  }

  server {
    listen 8080;

    server_name test_internal.com;

    access_log logs/test_internal.com_access.log;
    error_log logs/test_internal.com_error.log;

    location / {
      content_by_lua_block {
        ngx.header["Content-Type"] = "text/plain"
        ngx.say("Hello planet (internal) !")
      }
    }
  }
}
```

To reproduce:
1. Start Nginx with this `nginx.conf`
2. Make a request to nginx, e.g.:
`curl http://127.0.0.1/ -vv`
You should get a "Hello planet!" response.
3. Reload Nginx:
`./nginx -s reload`
4. Check the process list. E.g.:
```
$ ps -auxf | grep nginx
root     26159  0.0  0.1  38612  2716 ?        Ss   18:52   0:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody   26217  0.0  0.2  42760  6116 ?        S    18:52   0:00  \_ nginx: worker process is shutting down                                             
nobody   26245  0.0  0.2  42760  5640 ?        S    18:55   0:00  \_ nginx: worker process     
```

**Comment by tokers** [comment]
@kipras Does the "shutting down" nginx worker process exist continously? Or just disappear after some times?

It's normal for the "shutting down" status to appear a while, according to your configuration, i think it will hold for 60s (the default value of `lua_socket_keepalive_timeout`).  You can adjust this value to verify this.

The ngx_lua module will add a timer for the keepalive connection underlying the corresponding cosocket object, and the timer handler will close this idle connection. While nginx has to wait all the timers expire before it can exit (for the gracefully shutdown).

**Comment by tokers** [comment]
@kipras Does the "shutting down" status exist continuously? Or just disappears after a while.

It's normal that the "shutting down" status is maintained for a while. According to your configuration, i think it will hold for 60s, i.e. the default value of `lua_socket_keepalive_timeout`. You can just adjust this directive to verify it.

After you call `setkeepalive`, ngx_lua will add a timer (which is not cancelable) for the connection underlying the cosocket object. While the old nginx worker process has to wait for all the timers expire before it can quit.

**Comment by kipras** [comment]
@kipras Does the "shutting down" status exist continuously? Or just disappears after a while.
> Yes, it dissapears after a while

That makes sense. However why is it then that if the timer is called not prematurely or if `setkeepalive` is called directly from the request handler (not from the timer) - this does not happen ?

**Comment by spacewander** [comment]
@kipras 
Thank you for your detail report.

> Could those those keepalive timers maybe also be called prematurely

Note that @tokers  is talking about Nginx's timer(which is running in the C land). A Lua timer still could not be created inside premature call.

IMHO, Making a connection and keep it alive when Nginx is trying to shutdown gracefully, will block Nginx until the connection is dead ultimately, this consequence is expected. Because it is what the gracefully shutdown promises -- do not exit until all connection are finished. Nginx just does what it was told, though it probably is a programmer's mistake.

> Also, if you restart Nginx, then you get alerts like this (and sometimes a core dump):

I am really curious about the core dump part. Have you analysed the core dump? What causes the core dump directly? If the core dump is caused by calling `setkeepalive` when Nginx is shutdowning, it will be reasonable to disable it in this case.

**Comment by tokers** [comment]
@kipras 
> That makes sense. However why is it then that if the timer is called not prematurely or if setkeepalive is called directly from the request handler (not from the timer) - this does not happen ?

Well, i think it is because that the peer (`127.0.0.1:8080`) is also your nginx worker,  the listening sockets will be closed by the old worker when it is exiting. So the cosocket object connection's read handler will be triggered and the connection will be closed immediately.

> Could those those keepalive timers maybe also be called prematurely (to handle them during worker shutdown, instead of waiting the full 60s)? Whereas if you create a new timer from an already prematurely fired timer - this does not happen?

Just like @spacewander said, these keepalive timers run in the C land, timers created by ngx_lua are really can be expired prematurely. Whereas these timers created by nginx core cannot.

**Comment by kipras** [comment]
Thank you for replies.

> IMHO, Making a connection and keep it alive when Nginx is trying to shutdown gracefully, will block Nginx until the connection is dead ultimately, this consequence is expected. 

Yes, this is all true. The only confusing (and imho dangerous) part in this is the difference in behavior between premature and non-premature timers.

Because if you are running some complex logic in a timer and `setkeepalive` is called somewhere internally - you probably won't pass the `premature` flag all along the way. You might even use the same codebase that you use for your regular (not timer based) code, which would have no concept of such a flag. That's why i think this behavior difference should be mentioned in the docs, to keep people aware of this (so they could adjust `setkeepalive` usage accordingly).

> > That makes sense. However why is it then that if the timer is called not prematurely or if setkeepalive is called directly from the request handler (not from the timer) - this does not happen ?
>
> Well, i think it is because that the peer (127.0.0.1:8080) is also your nginx worker, the listening sockets will be closed by the old worker when it is exiting.

As mentioned in the issue description - the cosocket here connects to nginx itself only for the test-case to be self-sustainable. It happens if the cosocket connects to a separate server too (i first noticed this with redis connections).

> I am really curious about the core dump part. Have you analysed the core dump? What causes the core dump directly?

Sorry, my bad. Turns out i had `debug_points abort` in my nginx.conf, that's what generated the core dumps on restart.

**Comment by tokers** [comment]
@kipras 
> As mentioned in the issue description - the cosocket here connects to nginx itself only for the test-case to be self-sustainable. It happens if the cosocket connects to a separate server too (i first noticed this with redis connections).

You may observe the variation of this alive connection state, such as the abort by using tools like tcpdump.

**Comment by kipras** [comment]
@tokers this last comment was probably regarding the `debug_points abort` that i mentioned i had accidentally turned on in my nginx.conf ?

Either way, is it ok if i open a pull request to add the info about this phenomenon to `tcpsock:setkeepalive()` docs? Or you don't consider this important enough to be mentioned?

And we can close this ticket.

**Comment by spacewander** [comment]
@kipras 
1. `tcpsock:setkeepalive()` keeps connection alive.
2. An alive connection blocks Nginx from gracefully shutdown.
3. Call `tcpsock:setkeepalive()` when Nginx does gracefully shutdown blocks the process.

From `1,2`, it is expect to see `3`. So in my own opinion, the behavior is understandable.

**Comment by kipras** [comment]
@spacewander yes, this is all clear, i'm not saying that it is not understandable.

What i am saying is that such difference in behavior for the same code running in the same timer and the only change being the timer called prematurely is surprising at least, and in some cases can be dangerous (as workers that have not yet shut down are using up memory).

Because again, if you run `:setkeepalive()` in a non-premature timer - that kept alive connection doesn't block Nginx from gracefully shutting down. I don't see why a premature timer has to behave differently. And since it does (and maybe there are good reasons for it) i think it makes sense to at least inform the user of the API about this disparity in behavior, because at least for me it was unexpected.

That's all :) But do what you will, if you don't think it's important, that's fine.

**Comment by spacewander** [comment]
@kipras 
Aha, I guess the problem is about the `premature` flag.
When Nginx gracefully shutdowns, all pending timer will be trigged with `premature = true`(in other case, `premature` will be `false`). So when `premature == true`, it means the timer is running while Nginx is shutting down.

> Premature timer expiration happens when the Nginx worker process is trying to shut down, as in an Nginx configuration reload triggered by the HUP signal or in an Nginx server shutdown.

You can find above description there: https://github.com/openresty/lua-nginx-module#ngxtimerat
Note that it is also true for `ngx.timer.every` too.
