### ISSUE TITLE
ngx.location.capture http2 post bug

### ISSUE THREAD

**Issue by liyuan615** [openresty/lua-nginx-module#1285]
你好！

我使用openresty 搭建了 HTTP2的服务器 
在使用 ngx.location.capture 
GET没问题 但是使用 post 就是一直等待服务器的相应

谢谢解答

**Comment by vegaoqiang** [comment]
没有配置文件你让别人怎么解答?

**Comment by liyuan615** [comment]
nginx.conf：


	server {
	    lua_code_cache on;
	    access_log logs/d_xxx_cn_access.log main;
       #listen       443;
	    listen       443   ssl http2;
        server_name  127.0.0.1;
		# 打开ssl
		ssl  on;
		# 上一步生成的服务器证书
		ssl_certificate  /usr/xxxx/ssl/private/server.crt;
		# 服务器证书公钥
		ssl_certificate_key  /usr/xxxx/ssl/private/server.key;
		# 客户端证书签名 也就是第二步生成的CA签名证书
		ssl_client_certificate   /usr/xxxx/ssl/private/ca.crt;
		
		# 打开SSL客户端校验 (双向证书检测)
		ssl_verify_client on;

		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		#ssl_ciphers ECDHE-RSA-AES256-SHA384:AES256-SHA256:RC4:HIGH:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!AESGCM;
		
		ssl_ciphers 'CHACHA20:EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;';
        
		
		ssl_prefer_server_ciphers   on;
		#设置一10M大小的缓存池
		ssl_session_cache shared:SSL:10m;
		# ssl session 超时
		ssl_session_timeout  10m;
		
		client_max_body_size 10m;    #允许客户端请求的最大单文件字节数
          client_body_buffer_size 128k;  #缓冲区代理缓冲用户端请求的最大字节数，
          proxy_connect_timeout 90;  #nginx跟后端服务器连接超时时间(代理连接超时)
          proxy_send_timeout 90;        #后端服务器数据回传时间(代理发送超时)
          proxy_read_timeout 90;         #连接成功后，后端服务器响应时间(代理接收超时)
          proxy_buffer_size 4k;             #设置代理服务器（nginx）保存用户头信息的缓冲区大小
          proxy_buffers 4 32k;               #proxy_buffers缓冲区，网页平均在32k以下的话，这样设置
          proxy_busy_buffers_size 64k;    #高负荷下缓冲大小（proxy_buffers*2）
          proxy_temp_file_write_size 64k;  #设定缓存文件夹大小，大于这个值，将从upstream服务器传
	
	
	    location ~/upstream/(.*) {
		   internal;	
		   proxy_set_header      User-Agent "nginx/http";
		   proxy_set_header      Accept-Encoding "utf-8";
           client_max_body_size  100m;
           proxy_set_header      x-forward-for $remote_addr;
           proxy_set_header      Host $host;
           proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_pass_header     Set-Cookie;
		   proxy_set_header X-Real-IP $remote_addr;
           proxy_http_version 1.1;
           proxy_set_header Connection "";
		   proxy_intercept_errors on;
		   proxy_pass http://$1$is_args$args;
        }
		location ~ .*\.(do)$ {
           #proxy_pass              http://appupstream;
           client_max_body_size  10m;
           proxy_set_header      x-forward-for $remote_addr;
           proxy_set_header      Host $host;
           proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_pass_header     Set-Cookie;
			proxy_set_header X-Real-IP $remote_addr;
           proxy_http_version 1.1;
           proxy_set_header Connection "";
		   access_by_lua_file /usr/xxxx/website/openrestykjduobao/src/waf/waf.lua;
		   content_by_lua_file /usr/xxxx/website/openrestykjduobao/src/ydmvc/appmvc.lua;
        }
}


.lua


function _M.getresponse(request)
  if request.method==ngx.HTTP_POST then
    ngx.req.set_header("Content-Type", "application/x-www-form-urlencoded");
  end
  ngx.req.set_header("Accept", "application/json");
  ngx.req.clear_header("Cookie");

  local obj=ngx.location.capture(request.url, {
    method = request.method,
    body=request.body
  }); 
return obj
end

**Comment by spacewander** [comment]
@liyuan615 
`ngx.location.capture` doesn't support HTTP2.

**Comment by liyuan615** [comment]
@spacewander 
请问啥时候可以支持

**Comment by liyuan615** [comment]
在 lua 里 如何修改 http_version的版本号  
我想如果在LUA里把http_version的版本号修改为1.1
在去请求ngx.location.capture

**Comment by spacewander** [comment]
@liyuan615 
There is no API to change http version yet.
But you could use lua-resty-http to submit a HTTP 1.1 POST request.

**Comment by liyuan615** [comment]
希望大神 能早入实现 ngx.location.capture http2.0

**Comment by tokers** [comment]
@liyuan615 Have you tried to remove the `http2` listen option and what about the result?

@spacewander Are you talking about the problem described in https://github.com/openresty/lua-nginx-module/issues/415.
But seems that this problem isn't relevant with HTTP/2. I'm not sure whether there are some other reasons can cause the request to hang :).

**Comment by spacewander** [comment]
@tokers 
So you have some evidence to prove that the hang is not relevant with HTTP/2?

**Comment by tokers** [comment]
@spacewander 
> But seems that this problem isn't relevant with HTTP/2. I'm not sure whether there are some other reasons can cause the request to hang :).

I'm sorry to misunderstand you, what i mean is the problem in #415, not this issue.

I'm not sure the fundamental reason about the problem in this issue.

**Comment by liyuan615** [comment]
@spacewander  

listen       443   ssl http2;

我去掉了   http2   就一切正常

**Comment by vegaoqiang** [comment]
the official doc explains some features of ngx.location.capture, the original is as follows:
Also note that subrequests just mimic the HTTP interface but there is no extra HTTP/TCP traffic nor IPC involved. Everything works internally, efficiently, on the C level.
link —> https://github.com/openresty/lua-nginx-module#ngxlocationcapture
so,  i think this problem has nothing to do with http/2
------------------------------------------------------------------发件人：liyuan615 <notifications@github.com>发送时间：2018年3月26日(星期一) 13:52收件人：openresty/lua-nginx-module <lua-nginx-module@noreply.github.com>抄　送：vegaoqiang <vegaoqiang@aliyun.com>; Comment <comment@noreply.github.com>主　题：Re: [openresty/lua-nginx-module] ngx.location.capture http2 post bug (#1285)
@spacewander
listen       443   ssl http2;
我去掉了   http2   就一切正常

**Comment by agentzh** [comment]
@liyuan615 Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

We do not have the resources or interest to add HTTP/2 support to the subrequest capturing API. But we are open to pull requests from the community.
