### ISSUE TITLE
Content-Length and ngx.req.read_body() hang

### ISSUE THREAD

**Issue by SinSquare** [openresty/lua-nginx-module#1293]
If the client explicitly sets the Content-Length header, and the request body length is smaller than the Content-Length value then the ngx.req.read_body() hangs. Might be an NGINX issue, not sure.

To reproduce just send a POST request from a REST client, with a body and set Content-Length larger than the actual body size. The lua code:

```
location /test {
    access_by_lua_block {
        ngx.req.read_body()
        -- execution will not reach this
        local data = ngx.req.get_body_data()
    }
}
```

**Comment by agentzh** [comment]
@SinSquare This is the expected and desired behavior. If the client says in its Content-Length header that there's more data to come, the right thing for the server to do when seeing insufficient request body data is just to *wait*. I don't see there's any problems here.
