### ISSUE TITLE
 why is ngx.req.get_uri_args(0) strongly discouraged?

### ISSUE THREAD

**Issue by JoyChou93** [openresty/lua-nginx-module#1294]
https://github.com/openresty/lua-nginx-module#ngxreqget_uri_args

why is ngx.req.get_uri_args(0) strongly discouraged?

>Removing the max_args cap is strongly discouraged.

**Comment by agentzh** [comment]
@JoyChou93 Because it would be a great way for malicious clients to blow up your server memory usage since you have no limit on the number of request arguments.
