### ISSUE TITLE
Compile with nginx error "identifier "ndk_set_var_value_pt" is undefined"

### ISSUE THREAD

**Issue by tousuke** [openresty/lua-nginx-module#1307]
hello, excuse me for a question here.

When I compile nginx 1.14.0 with lua module and other modules,
I got a error about
```
...
-o objs/addon/src/ngx_http_lua_ndk.o \
        ../lua-nginx-module-0.10.13rc1/src/ngx_http_lua_ndk.c
../lua-nginx-module-0.10.13rc1/src/ngx_http_lua_ndk.c(20): error: identifier "ndk_set_var_value_pt" is undefined
  static ndk_set_var_value_pt ngx_http_lookup_ndk_set_var_directive(u_char *name,
         ^
...
```
here is my config option:

> ./configure \
> --prefix=/etc/nginx \
> --sbin-path=/usr/sbin/nginx \
> --modules-path=/usr/lib/nginx/modules \
> --conf-path=/etc/nginx/nginx.conf \
> --error-log-path=/var/log/nginx/error.log \
> --http-log-path=/var/log/nginx/access.log \
> --pid-path=/var/run/nginx.pid \
> --lock-path=/var/run/nginx.lock \
> --http-client-body-temp-path=/var/cache/nginx/client_temp \
> --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
> --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
> --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
> --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
> --user=nginx \
> --group=nginx \
> --with-compat \
> --with-file-aio \
> --with-threads \
> --with-http_addition_module \
> --with-http_auth_request_module \
> --with-http_dav_module \
> --with-http_flv_module \
> --with-http_gunzip_module \
> --with-http_gzip_static_module \
> --with-http_mp4_module \
> --with-http_random_index_module \
> --with-http_realip_module \
> --with-http_secure_link_module \
> --with-http_slice_module \
> --with-http_ssl_module \
> --with-http_stub_status_module \
> --with-http_sub_module \
> --with-http_v2_module \
> --with-mail \
> --with-mail_ssl_module \
> --with-stream \
> --with-stream_realip_module \
> --with-stream_ssl_module \
> --with-stream_ssl_preread_module \
> --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
> --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie,-rpath,/usr/local/lib/' \
> --add-module=../ngx_devel_kit-0.3.1rc1 \
> --add-module=../lua-nginx-module-0.10.13rc1 \
> --add-module=../ngx_brotli \
> --add-module=../nginx-ct \
> --with-openssl=../openssl-1.1.1-pre5 \
> --with-openssl-opt='enable-tls1_3 enable-weak-ssl-ciphers -fPIC'

gcc version 6.4.0
nginx version 1.14.0

is anything I make wrong or some software not support?
how could I fix it

Thank you!

**Comment by agentzh** [comment]
@tousuke I cannot reproduce it on my side with nginx 1.14.0 + git master branches of the relevant nginx C modules + gcc 7.3.1/clang 8.0.0 on Linux x86_64 and OS X. It always builds fine without errors.

Maybe you should try removing those 3rd-party nginx C modules that are not maintained by us.

**Comment by agentzh** [comment]
@tousuke BTW, nginx 1.14.0 is so now that it is not yet an officially supported target. You are at your own risk (even though it may compile okay).

**Comment by tousuke** [comment]
@agentzh Thank you for reply.

I'm sorry that was my fault,you said right,it's no problem,
seems I switched my compiler to intel compiler when that time,
switch to gcc let the compile successful.

and thanks,I will compile it with old version nginx,thank you for helping! 

by the way,could I ask about why intel compiler have the error like that,
it's possible to solve?
Thank you !

**Comment by agentzh** [comment]
@tousuke Intel C compiler is never an officially supported toolchain for OpenResty. And I don't have an Intel C compiler license, which makes debugging things not quite feasible at least for me.

**Comment by tousuke** [comment]
@agentzh Thanks for reply.

okay,thanks the answer,it's helpful.
Thank you again!
