### ISSUE TITLE
in https call ngx.req.read_body() will throw alert: Ignoring stale global SSL error

### ISSUE THREAD

**Issue by doox8086** [openresty/lua-nginx-module#1322]
When I use HTTPS post json data, if the json contains token="", ngx.req.read_body() will report the error:
Ignoring stale global SSL error (SSL: error: 0606506 d: digital envelope routines: EVP_DecryptFinal_ex: wrong final block length)

It only happens if the post data is json and token="".

For example: I use postman post data.
{"token": ""}

--
-- test. Lua
--
ngx.req.read_body ()
ngx.print('ok')

**Comment by doox8086** [comment]
@spacewander 

centos7
openrsety: 1.13.6.1

openssl
Arch        : x86_64
Version   : 1.0.2k
Release   : 8.el7

**Comment by spacewander** [comment]
@doox8086 
Could you provide a minimal runnable test case to reproduce the issue? Should include the Nginx configuration and a fake SSL certificate for the HTTPS requeset. The current information is not enough to reproduce the issue yet.

**Comment by doox8086** [comment]
Sorry, my fault!
I rewrote the minimum test and rechecked all the code for my project.
This SSL error was caused by a test code that I forgot to delete in my project.
