### ISSUE TITLE
Running out of worker_connections stops timers

### ISSUE THREAD

**Issue by gpaul** [openresty/lua-nginx-module#1338]
The `ngx.timer.at(delay, fn)` call schedules `fn` to run after a delay of `delay`.

The `fn` function takes a single parameter, usually called `premature`, which is `true` when the worker process is shutting down and allows one to stop a recursive timer sequence.

However, this value is also true when the maximum number of `worker_connections` is reached. This causes a recursive timer (the standard recipe for triggering an asynchronous action every N seconds) to terminate prematurely.

The code path appears to be:
`ngx_get_connection`
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1040

`c = ngx_cycle>free_connections;`
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1056

`if (c == NULL) {` 
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1058

`ngx_drain_connections((ngx_cycle_t *) ngx_cycle);`
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1059

`ngx_drain_connections(ngx_cycle_t *cycle)`
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1241

`c->read->handler(c->read);`
https://github.com/nginx/nginx/blob/0c4ccbea23813a50132df511d4445bc1686dbc2f/src/core/ngx_connection.c#L1261

The read handler for the fake timer connection is set here:
`lmcf->watcher->read->handler = ngx_http_lua_abort_pending_timers;`
https://github.com/openresty/lua-nginx-module/blob/576a10d246daf81c0ce1b959c50ee807769c01a8/src/ngx_http_lua_timer.c#L211

As such, calling the handler triggers:
`ngx_http_lua_abort_pending_timers(ngx_event_t *ev)`
https://github.com/openresty/lua-nginx-module/blob/576a10d246daf81c0ce1b959c50ee807769c01a8/src/ngx_http_lua_timer.c#L751

Steps to reproduce are:

Create the following file:
```
cat <<EOF > timer.conf
daemon off;
worker_processes  1;

events {
    worker_connections  10;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        location /t2 {
            content_by_lua_block {
                ngx.say("ok")
                ngx.log(ngx.ERR, "ok")
                local begin = ngx.now()
                local function timerhandler(premature)
                    ngx.log(ngx.ERR, "elapsed: ", ngx.now() - begin)
                    if premature then
                        ngx.log(ngx.ERR, "timer prematurely expired: ", premature)
                        return
                    end

                    local ok, err = ngx.timer.at(1.0, timerhandler)
                    if not ok then
                        ngx.log(ngx.ERR, "Failed to create timer: " .. err)
                    else
                        ngx.log(ngx.ERR, "Created recursive timer.")
                    end
                end

                local ok, err = ngx.timer.at(1.0, timerhandler)
                if not ok then
                    ngx.log(ngx.ERR, "failed to set timer: ", err)
                    return
                end
                ngx.say("ok2")
                ngx.say("registered timer")
            }
        }

	location /t3 {
            content_by_lua_block {
                ngx.log(ngx.ERR, "sleeping")
	        ngx.sleep(1)
                ngx.log(ngx.ERR, "responding")
            }
        }

        location / {
            root   /usr/local/openresty/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }
    }

}
EOF
```

Start an openresty docker container in one terminal:
```
docker run --net=host -it -v  `pwd`/timer.conf:/usr/local/openresty/nginx/conf/nginx.conf openresty/openresty:stretch-fat nginx
```

Start the timer:
```
curl http://localhost:80/t2
```

Observe the timer logs.

In a second terminal, launch ApacheBench:
```
ab -n1000 -c100 http://localhost:80/t3
```

Observe the timer stops logging.

```
2018/06/15 11:22:18 [alert] 7#7: 10 worker_connections are not enough
2018/06/15 11:22:18 [alert] 7#7: 10 worker_connections are not enough
2018/06/15 11:22:18 [alert] 7#7: 10 worker_connections are not enough
2018/06/15 11:22:18 [alert] 7#7: 10 worker_connections are not enough
2018/06/15 11:22:19 [error] 7#7: *176 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *177 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *178 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *179 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *180 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *181 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
2018/06/15 11:22:19 [error] 7#7: *182 [lua] content_by_lua(nginx.conf:54):4: responding, client: 127.0.0.1, server: localhost, request: "GET /t3 HTTP/1.0", host: "localhost"
127.0.0.1 - - [15/Jun/2018:11:22:19 +0000] "GET /t3 HTTP/1.0" 200 0 "-" "ApacheBench/2.3"
...
no more timer logs.
```

**Comment by gpaul** [comment]
I've tested a workaround that works, although I haven't considered all the potential issues with it.

The trick is to set `worker_rlimit_nofile << worker_connections`:

```
events {
    worker_connections  100;
}
worker_rlimit_nofile 80;
```

ApacheBench reports
```
Complete requests:      1000
Failed requests:        0
```

As expected, the nginx logs show "too many open files" errors under load, but the timer keeps running during and after the load test.

**Comment by spacewander** [comment]
@gpaul @agentzh 
Maybe we could check `ngx_exiting` in  `ngx_http_lua_abort_pending_timers`?

We could also do the same thing in the Lua code as a workaround.

**Comment by gpaul** [comment]
> We could also do the same thing in the Lua code as a workaround.

If you mean scheduling a new timer in the `if premature and ngx.worker.exiting(); ...; end` block then I am cautious about mutating the tree of timers at https://github.com/openresty/lua-nginx-module/blob/576a10d246daf81c0ce1b959c50ee807769c01a8/src/ngx_http_lua_timer.c#L897 while it is being iterated over. If it works, that would be a very cool workaround.

**Comment by spacewander** [comment]
@gpaul 
Sorry, I misundertand your meaning previously. It looks like there is not workaround in Lua land.

**Comment by spacewander** [comment]
@gpaul 
I read the `ngx_http_lua_abort_pending_timers` again just now.
It looks like the tree of timers in ` ngx_http_lua_abort_pending_timers` is not being iterated. It is `events` which is being iterated. I haven't tested it myself yet.

**Comment by gpaul** [comment]
Nice!

**Comment by spacewander** [comment]
@gpaul 
I run your test case and doubt whether the timer is triggered prematurely.
In the test case, if the timer is triggered prematurely, there should be a log "timer prematurely expired" but I can not find it.
And `ngx_drain_connections` only closed connections which is marked reuseable. But `lmcf->watcher` is not reuseable.

I suspect the timer lost because of the `worker_connections are not enough`. A timer also occupies a connection. We could not run the timer if there is no more connections. If I am correct, you need to replace `ngx.timer.at` with `ngx.timer.every` if possible.

**Comment by gpaul** [comment]
@spacewander that was exactly the issue. I switched to `ngx.timer.every` and it works as expected and the timer survives `worker_connections` being exhausted. Thanks!
