### ISSUE TITLE
How to read nested form urlencoded parameters?

### ISSUE THREAD

**Issue by ktalebian** [openresty/lua-nginx-module#1342]
Let's say I do a curl of `-d 'session[username]=name&session[password]=pwd'` 

Using `ngx.req.get_post_args()` gives me: `{"session[password]":"pwd","session[username]":"name"}`

But I want to get this parsed as `{"session":{"username":"name", "password":"pwd"}}`. 

What's the solution?

**Comment by p0pr0ck5** [comment]
@ktalebian,

You will need to manually parse the request body. Bracket-formed parameters are not part of any official spec. I suspect it wouldn't be too difficult to write a quick parser in Lua to read the raw body data (via `ngx.req.get_body_data`) and return a table containing the values you want.

**Comment by bungle** [comment]
I wrote this:
https://github.com/Kong/kong/blob/next/kong/api/arguments.lua

Some tests:
https://github.com/Kong/kong/blob/next/spec/01-unit/000-new-dao/03-arguments_spec.lua

It supports both `[]` and `.` notations. In your case you should use:
```
session.username=name&session.password=pwd
```

to get that:

```
{"session":{"username":"name", "password":"pwd"}
```

Brackets `[]` are used for arrays (and you can use index number in them, e.g. `[1]`. The `arguments` also supports things like `session.xxx[]=ccc`.

As @p0pr0ck5 mentioned, there is no standards on this. But this is what we currently use on Kong Admin API (some entities still use old).
