### ISSUE TITLE
"io.popen:read()" return nil  sometimes in "openresty + osx"

### ISSUE THREAD

**Issue by charpty** [openresty/lua-nginx-module#1346]
I found some lua code can not work on osx in openresty, but worked on linux.
Please note this problem only exists in "osx + openresty", this is version information
![image](https://user-images.githubusercontent.com/8869963/42020944-ebca1c1e-7aeb-11e8-83f0-19ffc19f95fb.png)

My conf and code:
```
        location /lua {
            default_type text/plain;
            content_by_lua_file /Users/charpty/test.lua;
            lua_code_cache off;
        }  
```
```
function getUnameInfo()                                                                                                                                       
    local handle = io.popen("uname -a", "r")
    ngx.say(handle == nil)
    local result = handle:read('*all')
    ngx.say(result)
    handle:close()
    ngx.say("no exception happened")
end
  
function errorCatch(e)
    ngx.say("error ->")
    ngx.say(e)
end 
 
ngx.say("begin")
xpcall(getUnameInfo, errorCatch)
ngx.say("end")
```
On my mac, it big probability return right value,  like：
![image](https://user-images.githubusercontent.com/8869963/42020756-5df9ce48-7aeb-11e8-9157-35fe7946202c.png)

But there's a chance "handle:read('*all')" return nil, like
![image](https://user-images.githubusercontent.com/8869963/42021456-32f65732-7aed-11e8-9bb4-82d03bb78015.png)

**Comment by charpty** [comment]
@agentzh 春哥帮忙看下，OpenResty2群有讨论过程，不然本地调试好麻烦哦～
Please take a look, there is some discussion in wechat.

**Comment by thibaultcha** [comment]
You are not properly catching the errors from `f:read()`. It returns `nil, err` on errors.

As for the underlying issue, you are most likely encountering the behaviour described in https://github.com/openresty/resty-cli/issues/35 in which the `SIGCHLD` signal from the shell's termination is interrupting the read syscall with `EINTR`.

If you write it as:
```
local result, err = handle:read('*all')
ngx.say(err)
```

You would probably see `Interrupted system call` as the error.

For the fixes, have a look at https://github.com/openresty/lua-nginx-module/pull/1296 + https://github.com/openresty/lua-resty-core/pull/183  (+ https://github.com/openresty/resty-cli/pull/41 for example usage).

**Comment by charpty** [comment]
@thibaultcha 
I understand, thank you! But err is 'Interrupted system call',  what does this mean, and what should I do to fix this?

**Comment by charpty** [comment]
@thibaultcha 
I understand, thank you! But the err is 'Interrupted system call', so what should I do to fix this?
Or I just wait for #1296 get into release？

**Comment by thibaultcha** [comment]
@charpty Can’t you load this value in the init_by_lua* phase and cache it in a module or other variable? It is bad practice to do such blocking I/O during the execution of the Nginx runloop anyway, so it should be a win-win to move the logic away.

**Comment by charpty** [comment]
This is just a demo. In fact, I want to execute k8s commands. Because of other restrictions I can not use kubectl to execute, so I want to use openresty to execute just like: 
```
function getK8sCommand(af, image)
    local log = "/tmp/apply_log_"..image.."_"..string.sub(af, af:match(".*/()"))
    local command = "sudo kubectl apply -f "..af.." > "..log
    return command,log
end 
  
function applyK8s()
    ngx.req.read_body()
    local args = ngx.req.get_post_args()
    -- apply file
    af = args.af
    image = args.image
    if(af == nil) then
        ngx.say("param af can not be nil")
        do return end 
    end 
    if(image == nil) then
        ngx.say("param image can not be nil")
        do return end 
    end 
    local command,log = getK8sCommand(af, image)
    ngx.say("execute: "..command)
    ngx.say("log file: "..log)
    os.execute(command)
    ngx.say("***logs***")
    for line in io.lines(log) do
	ngx.say(line)
    end
end 
 
function errorCatch(e)
    ngx.say("k8s apply error ->")
    ngx.say(e)
end 
 
ngx.say("******k8s apply begin**********")
xpcall(applyK8s, errorCatch)
ngx.say("******k8s apply end**********")
```
My first try openresty, thank you for your help, I have rewritten this with python so I close this issue.
