### ISSUE TITLE
readme document mistake

### ISSUE THREAD

**Issue by NietzscheX** [openresty/lua-nginx-module#1347]
https://github.com/openresty/lua-nginx-module#ngxlocationcapture

The args option can also take plain query strings:

 ngx.location.capture('/foo?a=1',
     { args = 'b=3&c=%3a' } }
 )
This is functionally identical to the previous examples.

here is a little mistake in document  on this  '}' , i think it  should be   { args = {'b=3&c=%3a' } } or { args = 'b=3&c=%3a' }

**Comment by thibaultcha** [comment]
Fixed in 81344434, thanks.
