### ISSUE TITLE
"ngx_http_headers_more_filter_module.so" is not binary compatible

### ISSUE THREAD

**Issue by LauraZhouYu** [openresty/lua-nginx-module#1351]
I am adding this module to nginx:1.13.6 docker image. I had ./configure  --prefix=/opt/nginx  --add-dynamic-module=headers-more-nginx-module-0.33 in docker file , and  load_module /opt/nginx/modules/ngx_http_headers_more_filter_module.so in nginx.conf. But it returns error: 
[emerg] 20#20: module "/opt/nginx/modules/ngx_http_headers_more_filter_module.so" is not binary compatible in /etc/nginx/nginx.conf:8

**Comment by agentzh** [comment]
@LauraZhouYu You know the current repo is lua-nginx-module? It's completely off topic. Also, please do not cross-post. It's very annoying.
