### ISSUE TITLE
HTTP request hangs while receiving chunked body (with more than 1 chunk) from another services that is running on the same host.

### ISSUE THREAD

**Issue by Unigoge** [openresty/lua-nginx-module#1373]
HTTP request's body_reader() hangs while receiving chunked body (with more than 1 chunk) from another services that is running on the same host (also a lua app inside the same Nginx). At the same time the same code works perfectly when fetching data from remote machines.

Using openresty-1.13.6.1 and pintsized/lua-resty-http.

Here is a code snippet - the `uri` is set outside of this code, `file` is opened outside, sha256 object is created at the outside:

```                                    
                                    local http = require "resty.http";
                                    local httpc = http.new();
                                    httpc:set_timeouts( 1000, 1000, 120000);
                                    
                                    local req_success = false;
                                    local received_res;
                                    local body_reader;
                                    
                                    while true do
                                        local req_params = {};

                                        local parsed_uri, err = httpc:parse_uri( uri, false );
                                        if not parsed_uri then
                                            break;
                                        end
                                    
                                        local scheme, host, port, path, query = unpack( parsed_uri );
                                        if not req_params.path then req_params.path = path end
                                        if not req_params.query then req_params.query = query end
                                    
                                        local c, err = httpc:connect( host, port );
                                        if not c then
                                            break;
                                        end
                                    
                                        if scheme == "https" then
                                            local ok, err = httpc:ssl_handshake(nil, host, false);
                                            if not ok then
                                                break;
                                            end
                                        end

                                        received_res, err = httpc:request(req_params);
                                  
                                        if not received_res then
                                          ngx.log( ngx.ERR, "Failed file download request: ", err);
                                          break;
                                        end
                                        
                                        body_reader = received_res.body_reader;
                                        req_success = true;
                                        break;
                                    end                          
                                
                                    while req_success do
                                        local body_part_size = (1024 * 1024) - 1024; -- almost 1Mb
                                        local curr_downloaded_size = 0;
                                        local body_part;
                                        repeat
                                            local err;
                                            body_part, err = body_reader( body_part_size );
                                            if err then
                                                ngx.log( ngx.ERR, "failed to read req body: ", err);
                                                req_success = false;
                                                break;
                                            end
                                            
                                            if body_part then
                                            
                                                ngx.log( ngx.INFO, "Received #", #body_part, " bytes of response" );
                                                
                                                file:write(body_part);
                                                download_sha256:update(body_part);
                                                curr_downloaded_size = curr_downloaded_size + #body_part;
                                                                     
                                            else
                                                ngx.log( ngx.INFO, "Finished receiving response" );
                                                break;
                                            end
                                            
                                        until not body_part;
                                        
                                        break;
                                    end

                                    ...some other processing...
```

...so, as I've said before - everything works perfectly when `uri` points to a remote server. However, when `uri` points to another service (also a lua app inside the same Nginx) and when the response body size is greater than 1 chunk (over 1 Meg in this case) - then the `body_reader( body_part_size );` hangs (up to set read timeout) at the last chunk of the response. I've also observed that in case of "localhost" the size of all received chunks is equal to `body_part_size` (almost 1 Meg), in case of remote machine it is vary and usually under 20-30 kilobytes.

I can tell for sure that all data gets sent from another service (since it is also a lua app inside the same Nginx I've put a lot of logging over there). Also traced it inside  `pintsized/lua-resty-http` code - it just never returns from this line - https://github.com/pintsized/lua-resty-http/blob/fe5c10a47cf40440845c140a5d29cd0e0cd0208f/lib/resty/http.lua#L405

It's weird... :) I would greatly appreciate any suggestions how to deal with this situation. Unfortunately, most of data I need to deal with sized in gigabytes - so, streaming request's data is a must!

Thanks,
Gene

**Comment by tokers** [comment]
@Unigoge 
Maybe you need to post this issue to the lua-resty-http repository.

> Also traced it inside pintsized/lua-resty-http code - it just never returns from this line - https://github.com/pintsized/lua-resty-http/blob/fe5c10a47cf40440845c140a5d29cd0e0cd0208f/lib/resty/http.lua#L405

The reason why this line "block" is because the server really doesn't send such more data (the rest part size is small than length). 

Have you ever  try to use other resty http client to do this? Like [lua-resty-httpipe](https://github.com/timebug/lua-resty-httpipe) or [lua-resty-requests](https://github.com/tokers/lua-resty-requests). Have they also can reproduce this problem?

**Comment by Unigoge** [comment]
Ok - I have found and fixed an issue - it's inside `pintsized/lua-resty-http` code:
- for some reason, in case of "the same host" responses the "Transfer-Encoding" header looks like this `Transfer-Encoding: chunked, chunked` ("chunked" value gets inserted twice, or - as another possibility, the whole  "Transfer-Encoding" header gets inserted twice);
- regardless of that - the response headers processing creates a table with two values for this header (instead of single string value);
- which breaks code over here - https://github.com/pintsized/lua-resty-http/blob/fe7341b755193cadf5daac339c2ab47a3c5ac2da/lib/resty/http.lua#L706 
- and then it tries to read chunked response with regular reader (essentially switching it into HTTP 1.0 mode - where it expects the connection to get closed at the end of response) - and gets blocked... 

The fix is simple - need to replace existing line of code (at line 706):
```
        local ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"])
```
with something like this:
```
        local ok, encoding;
        if res_headers["Transfer-Encoding"] and type(res_headers["Transfer-Encoding"]) == "string" then
            ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"])
        elseif res_headers["Transfer-Encoding"] and type(res_headers["Transfer-Encoding"]) == "table" then
            ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"][1])
        end
```
I will close this issue and will reference it at  `pintsized/lua-resty-http` issues.

Thanks,
Gene
