### ISSUE TITLE
balancer why not resolve hostname

### ISSUE THREAD

**Issue by toruneko** [openresty/lua-nginx-module#1376]
I found that `ngx_http_lua_ffi_balancer_set_current_peer` function marks peer no resolve.
`url.no_resolve = 1`
why? we need to resolve hostname when set a hostname for balancer.

**Comment by tokers** [comment]
@toruneko 
The field `no_resolve` in `ngx_url_t` indicates whether uses the **system DNS resolver** to resolve the hostname, this behavior will block Nginx's event loop and never be used in the runtime. Precisely, only the configuration parsing phase, it may be set to  `0 `.

For your case, you need to resolve the domain in advance, note the special phase `balancer_by_lua` cannot be yielded, you may want to resolve it in a common phase like `access_by_lua`.

**Comment by toruneko** [comment]
but `ngx.socket.tcp` support system resolver to resolve hostname..

**Comment by toruneko** [comment]
@tokers okey.. I got it. thanks you for explanation.

so, we can write some code to make `ngx_http_lua_ffi_balancer_set_current_peer ` support  runtime dynamic resolver to resolve hostname.?

**Comment by tokers** [comment]
@toruneko 

No, we can't. Since the phase `balancer_by_lua` cannot be yield.

**Comment by toruneko** [comment]
T.T

thank you.

**Comment by tokers** [comment]
@toruneko 

Just a reference from ngx.balancer:

>Domain names in host do not make sense. You need to use OpenResty libraries like lua-resty-dns to obtain IP address(es) from all the domain names before entering the balancer_by_lua* handler (for example, you can perform DNS lookups in an earlier phase like access_by_lua* and pass the results to the balancer_by_lua* handler via ngx.ctx.
