### ISSUE TITLE
proxy_protocol version 2 - NginX 1.13.11+

### ISSUE THREAD

**Issue by urifoox** [openresty/lua-nginx-module#1383]
Hello,

I am  using a Network Load Balancer on AWS which proxies connections from two target groups to our Openresty instance. Upon trying to get the user's real IP address, instead of the proxy, we stumbled upon the fact that we need to enable "Proxy Protocol V2" on the Network Load Balancer. Doing this has resulted in pages not loading and the error "broken header: "" while reading PROXY protocol" which indicates that we do not support Proxy Protocol V2. Here is a run down of what I did to test this.

listen *:80 proxy_protocol;
listen *:443 ssl proxy_protocol;

/usr/local/openresty/nginx/sbin/nginx -v
nginx version: openresty/1.13.6.2

but https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/ explains that Proxy Protocol V2 is only supported on NginX 1.13.11+

I installed a clean version of NginX 

/usr/sbin/nginx -v
nginx version: nginx/1.15.4

and everything works as expected with Proxy Protocol V2, revealing the user's IP address in the $proxy_protocol_addr server variable.

Are there any plans on updating NginX core in Openresty to support Proxy Protocol V2?

Should I try to compile Openresty on my own by downloading the source and replacing the bundle/nginx-1.13.6 with a newer version?

Any advice would be appreciated.

Thanks,
Uri

**Comment by urifoox** [comment]
Well for anyone who runs into this, here is how I solved it:

1. Download the source of Nginx 1.13.11
2. Download the latest Openresty source (1.13.6.2)
3. Copy src\core\ngx_proxy_protocol.cc from Nginx 1.13.11 to Openresty
4. Compile Openresty as needed - I used:

> ./configure -j2  --with-http_ssl_module  --with-http_realip_module  --with-http_addition_module  --with-http_v2_module --with-http_sub_module  --with-http_dav_module  --with-http_flv_module  --with-http_mp4_module  --with-http_gunzip_module  --with-http_gzip_static_module   --with-http_random_index_module   --with-http_secure_link_module   --with-http_stub_status_module   --with-http_auth_request_module   --with-mail   --with-mail_ssl_module   --with-file-aio   --with-cc-opt='-g -O2 -fstack-protector   --param=ssp-buffer-size=4 -Wformat -Werror=format-security'   --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro'   --with-ipv6
 
5. Make/Make install
6. Enable proxy_protocol in your nginx.conf or other appropriate file
7. Enable Proxy Protocol V2 on your devices

To get the real IP address you can use a variation of

set_real_ip_from x.x.x.x/xx; (change to whatever you need)
real_ip_header X-Forwarded-For;
real_ip_recursive on;
proxy_set_header X-Forwarded-For $proxy_protocol_addr;

Should be all set. Hope this helps someone else!

**Comment by thibaultcha** [comment]
Closing this now that OpenResty 1.15.8.1 is out, based on the NGINX 1.15.8 core.
