### ISSUE TITLE
how can i add the module with windows nginx

### ISSUE THREAD

**Issue by anychange** [openresty/lua-nginx-module#1391]
I want to add the module with windows nginx use mingw32,but when I compile it allways show 'lua library not found or luajit library not found',I have try to make install the luajit and it also show success ,but the problem still show,how can I do? please,thank you.

**Comment by agentzh** [comment]
@anychange You're recommended to just use the Win32 pre-built packages for OpenResty:

https://openresty.org/en/download.html

See also

https://github.com/openresty/openresty/blob/master/doc/README-windows.md
