### ISSUE TITLE
Why didn't we use ngx_murmur_hash2 instead of ngx_crc32_short?

### ISSUE THREAD

**Issue by chronolaw** [openresty/lua-nginx-module#1397]
In `shdict` ngx_lua use `ngx_crc32_short` to compute hash key, But As I know the `murmur_hash` is faster than `crc32` (about 10 times), Should we change it for performence?

If it is possible, may I contribte a patch for ngx_lua/meta_lua?

**Comment by spacewander** [comment]
Just my personal thought, this is not an official response from the OpenResty developers.

---

I just wrote a simple script to compare the murmurhash2 and crc32 version:

```lua
local s = "1234567890123456"
local r
r = ngx.shared.dogs:set(s, 1)
local total = 1e7
ngx.update_time()
local start = ngx.now()
for i = 1, total do
    r = ngx.shared.dogs:get(s)
    --r = ngx.shared.dogs:set(s, 1)
end

ngx.update_time()
ngx.say(ngx.now() - start)
ngx.say(r)
```

By switching to murmurhash2, the speed is double. The result is promising!

I must point out that this script shows the best case - no rbtree look up, no hash collision, using only one key
So real world benchmark is required.

Does murmurhash2 distribute well?
Does murmurhash2 outperforms crc32 with different length of strings?

BTW, I also test the script with a crc32c-hw version, the result is a bit faster.
Although the crc32c-hw implementation requires sse4.2, which is not a good news for a cross-platform software, could you do some research on it?

**Comment by agentzh** [comment]
Yeah, we can always switch to a faster hash function, even different hash function on different architectures at build time (like when hardware crc32 is available). The current choice was just copying nginx's own code at that time). Pull requests welcome :)

**Comment by chronolaw** [comment]
It is a complex task to switch different hash function, and murmurhash may be slower to deal with very short strings(<4 bytes). I am afraid that I am not suitble for this job. I hope in the future Openresty can has this feature, thanks.

**Comment by agentzh** [comment]
@spacewander Will you work on a crc32 hw version for the shdict key hashing when you have a chance? Thanks!

I think it should be well worth it for relatively long keys. We already use SSE 4.2's CRC instruction to do hashing for our LuaJIT branch's `lj_str_new()` calls.

**Comment by agentzh** [comment]
@spacewander We can add a feature test to the `config` file for the CRC instruction detection (if the nginx core does not do it already).

**Comment by spacewander** [comment]
@agentzh 
I will do it once I have enough free time.
