### ISSUE TITLE
ssl memory leak on reload

### ISSUE THREAD

**Issue by karlseguin** [openresty/lua-nginx-module#1398]
I believe the memory allocated by the call to `ngx_ssl_create` on init (https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_module.c#L1228) doesn't get freed on reload / sighup.

From what I can tell, Nginx's built-in ngx_http_proxy_module  calls `ngx_ssl_cleanup_ctx`, but this module doesn't.

**Comment by spacewander** [comment]
IMHO, `ngx_ssl_cleanup_ctx` is registered just a few lines below:
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_module.c#L1237

**Comment by karlseguin** [comment]
Oopps. Sorry :/
