### ISSUE TITLE
Issue a warning upon nginx startup when OpenResty's LuaJIT is not used

### ISSUE THREAD

**Issue by agentzh** [openresty/lua-nginx-module#1406]
Right now whether OpenResty's LuaJIT is used in this module makes a difference for many use cases (like the new `table.clone` API and the new closure-factorary-less and global-env-less request handlers). Let's issue a warning to the user when OpenResty's LuaJIT is not used during the nginx startup. Something like this:

```
[warn] ... http lua: openresty's luajit is not used and the openresty specific optimizations cannot be enabled; the performance will be compromised for many cases
```

To detect OpenResty's LuaJIT, we can just do the following:

```C
#ifndef OPENRESTY_LUAJIT
...
#endif
```

**Comment by thibaultcha** [comment]
Addressed with #1411 which was merged to master, closing this :)
