### ISSUE TITLE
LuaJIT.h not found during Nginx compilation

### ISSUE THREAD

**Issue by wenlez** [openresty/lua-nginx-module#1410]
I compile Nginx with Lua module. Since the last commit added `#include <luajit.h>` , I can no longer compile due to missing module. 

This is my configure command:
`
cd $NGINX_VER \
  &&  ./configure --with-ld-opt="-Wl,-rpath,/usr/lib64/" --add-module=../lua-nginx-module-master --add-module=../ngx_devel_kit-master --user=nginx --group=nginx --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-file-aio --with-http_v2_module --with-openssl=../$OPENSSL_VER --with-openssl-opt=no-weak-ssl-ciphers --with-openssl-opt=no-ssl3 --with-http_ssl_module --with-debug
`
NGINX_VER=nginx-1.15.5
OPENSSL_VER=openssl-1.1.1

This is the message I get from configure. 
`
In file included from ../lua-nginx-module-master/src/ngx_http_lua_script.h:11:0,
                 from ../lua-nginx-module-master/src/ngx_http_lua_script.c:13:
../lua-nginx-module-master/src/ngx_http_lua_common.h:20:20: fatal error: luajit.h: No such file or directory
 #include <luajit.h>
                    ^
`

**Comment by agentzh** [comment]
Duplicate with #1405. See my reply there.

**Comment by guotenv** [comment]
In file included from ./modules/lua-nginx-module//src/ngx_http_lua_script.h:11:0,
                 from ./modules/lua-nginx-module//src/ngx_http_lua_script.c:13:
./modules/lua-nginx-module//src/ngx_http_lua_common.h:20:20: fatal error: luajit.h: No such file or directory

**Comment by agentzh** [comment]
@guotenv This module now requires LuaJIT to build. To save the troubles, it's highly recommended to use the OpenResty releases:

https://openresty.org/en/download.html

**Comment by guotenv** [comment]
> @guotenv This module now requires LuaJIT to build. To save the troubles, it's highly recommended to use the OpenResty releases:
> 
> https://openresty.org/en/download.html

okay,I'll try
