### ISSUE TITLE
Error trying to send  a json to a bash script

### ISSUE THREAD

**Issue by luisRubiera** [openresty/lua-nginx-module#1416]
Hi guys, the usecase:
I want to use **Openresty** to add a REST API to a **C** application.The application should receive the **json in the body** of the request.The problem is that when i try to use the string generated by `cjson.encode` -> `cjson.decode` i get an invalid json.( im always missing the `"`).I think its releate to openresty/lua because if i print the resulting string in the lua script it shows the valid json, but if i do a print on bash (`$1`) i get the invalid json.

My configuration:
```
    location /json_params_test {
                    charset utf-8;
                    charset_types application/json;
                    default_type application/json;
                    content_by_lua_block {
                        ngx.req.read_body()
                        local args = ngx.var.request_body
                        local json = require('cjson')
                        if not args then
                            ngx.say("failed to get post body ")
                            return
                        end
                        local treatedJson=json.decode(args)
                        local treatedJsonString = json.encode(treatedJson)
                        ngx.log(ngx.STDERR,treatedJsonString)
                        local f = assert(io.popen("/home/ubuntu/testScript.sh " .. treatedJsonString , 'r'))
                        local s = assert(f:read('*a'))
                        f:close()
                        ngx.log(ngx.STDERR,s)
                        local decoded = json.decode(s)
                        ngx.say(json.encode(decoded))
                        return ngx.exit(ngx.HTTP_OK)
                }
        }

```
and my `testScript.sh`
```
echo $1 >/tmp/args
echo $1
```
/tmp/args:
```
{params3:val3,param4:4,param6:{param6a:25,param6b:val6b},param5:[val5a,val5b],param2:val2,param1:val13}
```
Note, if i change `$1` for a static valid json, i will get a valid response 
the logs
```
2018/11/07 13:21:28 [] 1780#1780: *1 [lua] content_by_lua(nginx.conf:117):13: {"params3":"val3","param4":4,"param6":{"param6a":25,"param6b":"val6b"},"param5":["val5a","val5b"],"param2":"val2","param1":"val13"}, client: xx.xx.xx.xx, server: , request: "POST /json_params_consistance HTTP/1.1", host: "xx.xx.xx.xx:8080"
2018/11/07 13:21:28 [error] 1780#1780: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:117):24: Expected object key string but found invalid token at character 2
stack traceback:
coroutine 0:
	[C]: in function 'decode'
	content_by_lua(nginx.conf:117):24: in function <content_by_lua(nginx.conf:117):1>, client: xx.xx.xx.xx, server: , request: "POST /json_params_consistance HTTP/1.1", host: "xx.xx.xx.xx:8080"
```
Note: i use json encode/decode to have a one line json ( if i use `args` i would get them in multiple lines and that will not work with a script )

**Comment by agentzh** [comment]
You need to escape or quote the JSON for the shell command line. Shell also has its own meta-characters and syntax like `"`.

**Comment by luisRubiera** [comment]
thanks for the information @agentzh , do you know the best way to achieve this ?

**Comment by luisRubiera** [comment]
if someone ever need a solution for this,  just add this :
```
local stringWithEscpadedChars = string.format("%q",treatedJsonString)
```
and change the param used to call the bash script:
```
local f = assert(io.popen("${MY_SCRIPT_PATH}/myScript.sh " .. stringWithEscpadedChars , 'r'))
```

**Comment by agentzh** [comment]
@luisRubiera Please note that Lua's `%q` formater quotes according to the Lua's rules, not your shell's rules. So there is risk of incompatibilities as well as security vulnerabilities (like shell injection attacks). You should really quote it according to your shell's syntax and quoting rules, exactly.
