### ISSUE TITLE
luajit.h: No such file or directory

### ISSUE THREAD

**Issue by spidersq** [openresty/lua-nginx-module#1419]
我的环境是 
nginx1.15.4 
lua-nginx-module 最新代码
luajit也安装好，环境变量也已经配置好，但是重新对nginx进行make 的时候出现以下错误

/usr/local/src/lua-nginx-module/src/ngx_http_lua_script.c
In file included from /usr/local/src/lua-nginx-module/src/ngx_http_lua_script.h:11:0,
                 from /usr/local/src/lua-nginx-module/src/ngx_http_lua_script.c:13:
/usr/local/src/lua-nginx-module/src/ngx_http_lua_common.h:20:20: fatal error: luajit.h: No such file or directory

然后换成lua-nginx-module 的0.10.13版本之后就成功了。

**Comment by agentzh** [comment]
We no longer support the standard Lua 5.1 interpreter. See #1405.

**Comment by agentzh** [comment]
@spidersq BTW, NO CHINESE HERE PLEASE!

This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.
