### ISSUE TITLE
Segfault with SPDY

### ISSUE THREAD

**Issue by baank** [openresty/lua-nginx-module#142]
Using Nginx 1.3.3 with SPDY patch I get the following segmentation fault:

Core was generated by `nginx: worker process                         '.
Program terminated with signal 11, Segmentation fault.
#0  ngx_epoll_add_event (ev=0xab31f0, event=4, flags=18446744071562067968) at src/event/modules/ngx_epoll_module.c:400
400	        e = c->read;

With the following rewrite:

       rewrite_by_lua '
	   		email = ngx.var.arg_email;
  			password = ngx.var.arg_password;
				
  			if email and password then
  				res = ngx.location.capture("/authenticate/" .. email .. "/" .. password);
				if res and res.status == 200 then
					if (res.body ~= "nouserid") then
						return ngx.exec("/newsession/" .. res.body);
					end
				end
			end
			
			return ngx.exit(401);
        ';

**Comment by agentzh** [comment]
SPDY is now dead. I'm closing this.
