### ISSUE TITLE
when using `lua_package_path` to set lua module search path, nginx has occurred unexpected errors.

### ISSUE THREAD

**Issue by NagamineLee** [openresty/lua-nginx-module#1420]
I have used nginx-1.12.2 with some of openresty components, like lua-nginx-modle, lua-resty-upstream-healthcheck. etc.

        But when using `lua_package_path` to set lua module search path, nginx has occurred unexpected errors.

        problems as shown below

nginx instance 1：
normal OS user: test
nginx install in /home/test/nginx
nginx configuration(include lua module) also in /home/test/instance

nginx instance 2:
super OS user: root
nginx install in /root/nginx
nginx configuration(include lua module) also in /root/instance

- case 1:  (OK)
 
 master process user: test
 worker processes user: nobody
 lua_package_path(absolute path): /home/test/instance/lua_lib/?.lua;;
 
 run in `test` user: `/home/test/nginx/sbin/nginx -c /home/test/instance/nginx.conf -p /home/test/instance`

 start successfully, and load lua module successfully.

- case 2: (OK)
 
 master process user: test
 worker processes user: nobody
 lua_package_path(relative path): ./lua_lib/?.lua;;
 
 run in `test` user: `/home/test/nginx/sbin/nginx -c /home/test/instance/nginx.conf -p /home/test/instance`
 
 start successfully, and load lua module successfully.

- case 3:( NOT OK)
 
 master process user: root
 worker processes user: nobody
 lua_package_path(absolute path): /root/instance/lua_lib/?.lua;;
 
 run in `root` user: `/root/nginx/sbin/nginx -c /root/instance/nginx.conf -p /root/instance`
 
 start successfully, and load lua module failed:
 
 ```
 init_worker_by_lua error: init_worker_by_lua:2: module 'resty.upstream.healthcheck' not found:
         no field package.preload['resty.upstream.healthcheck']
         no file '/root/instance/lua_lib/resty/upstream/healthcheck.lua'
 ```
 
 but lua module file `/root/instance/lua_lib/resty/upstream/healthcheck.lua` exists and is 755 mode.

- case 4:( OK)
 
 master process user: root
 worker processes user: nobody
 lua_package_path(relative path):  ./lua_lib/?.lua;;
 
 run in `root` user: `/root/nginx/sbin/nginx -c /root/instance/nginx.conf -p /root/instance`
 
 start successfully, and load lua module successfully.

- case 5: (NOT OK)
 
 master process user: root
 worker processes user: nobody
 lua_package_path(absolute path): /home/test/instance/lua_lib/?.lua;;
 
 run in `root` user: `/home/test/nginx/sbin/nginx -c /home/test/instance/nginx.conf -p /home/test/instance`
 
 start successfully, and load lua module failed:
 
 ```
 init_worker_by_lua error: init_worker_by_lua:2: module 'resty.upstream.healthcheck' not found:
         no field package.preload['resty.upstream.healthcheck']
         no file '/home/test/instance/lua_lib/resty/upstream/healthcheck.lua'
 ```
 
 but lua module file `/home/test/instance/lua_lib/resty/upstream/healthcheck.lua` exists and is 755 mode.

- case 6: (OK)
 
 master process user: root
 worker processes user: nobody
 lua_package_path(relative path):  ./lua_lib/?.lua;;
 
 run in `root` user: `/home/test/nginx/sbin/nginx -c /home/test/instance/nginx.conf -p /home/test/instance`
 
 start successfully, and load lua module successfully.

- case 7: (OK)

 for case3 and case4, if configured worker process use as `root`, both are OK.

- case 8: (OK)
 
 for case5 and case6, if configured worker process user as `test`, both are OK.

For all NOT OK case above, I thought these cases were related to worker process user permission.

But for the same worker process user, `lua_package_path` configured relative path is OK.
but `lua_package_path` configured absolute path is NOT OK.

So, these problems confused me?

**Comment by agentzh** [comment]
@NagamineLee It's not just the file should have enough read permission but also all the directory entries in the file path must have the executable permission for the system to resolve the path for the `nobody` user used by your nginx worker process. BTW, it's highly recommend to use OpenResty releases directly.

**Comment by NagamineLee** [comment]
@agentzh I also agree with you. But a startling contrast between case 3 and case 4( or  case 5 and case 6), the same file, the same user, except the path configured( absolute vs. relative).
directive of `lua_package_path` has also support relative path base on `prefix` or `-p PATH`, and test results also confirm this.

But why does absolute path not work(case 3 or case 6)?

Compared with other nginx directives(like `access_log`, `error_log`), these directives also support absolute path and relative path, and both can work well, no matter absolute path or relative path.

so I think `lua_package_path` directive might has some difference.

**Comment by agentzh** [comment]
> But a startling contrast between case 3 and case 4( or case 5 and case 6), the same file, the same user, except the path configured( absolute vs. relative).

Yes, this is expected. This is exactly how your operating system resolves the file/director path values. The operating system only requires executable permissions in the file or directory entries *actually mentioned* in the path value string. So for relative paths like `./lua_lib/`, it only requires executable permissions on both the `.` directory and the `./lua_lib` directory. You can try running the command `sudo chmod og-x` on any of those 2 directory entries, and you'll see the same error immediately. In contrast, for absolute paths like `/home/test/instance/lua_lib/`, it requires executable permissions on all those directories mentioned in the path, i.e., `/home`, `/home/test`, `/home/test/instance/`, and `/home/test/instance/lua_lib`.

This is really UNIX basics and is beyond the scope of this project.

> Compared with other nginx directives(like access_log, error_log), these directives also support absolute path and relative path, and both can work well, no matter absolute path or relative path.

The `access_log` and `error_log` directives resolve paths while loading (or reloading) the nginx configuration files, which is always in the master process, which is run by `root` in your experiments anyway.

The `lua_package_path` only provides a template per se and the actual file paths are resolved (by the operating system) in the first `require()` call for any particular Lua module. So if you run `require "module"` in the context of `init_by_lua*`, then you won't have any permission problems no matter what since `init_by_lua*` runs in the master process just like `access_log` and `error_log`. But if the first `require` call is in a request handler (like `content_by_lua*`), then it's subject to the system account used by the worker process (which is `nobody` in those problematic examples you gave above).

So this is the difference. And apparently it's not a bug on our side.

**Comment by NagamineLee** [comment]
```
 In contrast, for absolute paths like /home/test/instance/lua_lib/, it requires executable permissions on all those directories mentioned in the path, i.e., /home, /home/test, /home/test/instance/, and /home/test/instance/lua_lib.
```

this description is not true.

In my testing environment, path`/home/test` is only `rwx------`(700)，there is no executable permissions for `nobody` user, but using absolute path` /home/test/instance/lua_lib/` also can find lua module.

**Comment by agentzh** [comment]
@NagamineLee You can try the following experiment in a *NIX box yourself:

```shell
[root@glass ~]# mkdir /home/blah
[root@glass ~]# chmod 0700 /home/blah
[root@glass ~]# ls -ld /home/blah
drwx------. 2 root root 4096 Feb  3 23:41 /home/blah
[root@glass ~]# touch /home/blah/a.lua
[root@glass ~]# chmod 0777 /home/blah/a.lua
[root@glass ~]# ls -lh /home/blah/a.lua
-rwxrwxrwx. 1 root root 0 Feb  3 23:42 /home/blah/a.lua
[root@glass ~]# sudo -u nobody whoami
nobody
[root@glass ~]# sudo -u nobody cat /home/blah/a.lua
cat: /home/blah/a.lua: Permission denied
[root@glass ~]# cd /home/blah
[root@glass blah]# sudo -u nobody cat ./a.lua
cat: ./a.lua: Permission denied
[root@glass blah]# sudo -u nobody cat a.lua
cat: a.lua: Permission denied
[root@glass blah]# ls -lh a.lua
-rwxrwxrwx. 1 root root 0 Feb  3 23:42 a.lua
[root@glass blah]# chown nobody:nobody a.lua
[root@glass blah]# sudo -u nobody cat a.lua
cat: a.lua: Permission denied
[root@glass blah]# mkdir test
[root@glass blah]# chmod a+x test
[root@glass blah]# mv a.lua test/
[root@glass blah]# sudo -u nobody cat test/a.lua
cat: test/a.lua: Permission denied
[root@glass blah]# cd test/
[root@glass test]# sudo -u nobody cat ./a.lua
[root@glass test]#
```

**Comment by liyanyan-dev** [comment]
The version I used is openresty 1.15.8.3 .I had the same problem,  and after I execute the command: chmod -R 777 the absolute path ,the problem still exists;but the relative path is ok.
