### ISSUE TITLE
Setting body of subrequest not work?

### ISSUE THREAD

**Issue by linux2014linux** [openresty/lua-nginx-module#1431]
Current(parent) request method is GET, it have no any request data. Subrequest method is POST, I want set some body to request.But subrequest's body still empty.Code:

        local userCheckService = MY_TEST_URI;

        local subReqBody = {}

        subReqBody["user_name"] = login_username;

        local result = ngx.location.capture(userCheckService, {method = ngx.HTTP_POST, body = cjson.encode(subReqBody)});

        if result == nil then

            ngx.exit(403);

        end

The body of subrequest is empty in server. Could you help me?

**Comment by agentzh** [comment]
@linux2014linux You must read the (full) request body in the main request before you try to manipulate subrequests' request bodies. This is nginx core's requirement.

**Comment by agentzh** [comment]
@linux2014linux And yes, you still must call `ngx.req.read_body()` even for requests without a request body (like `GET` and `DELETE` requests).

**Comment by linux2014linux** [comment]
@agentzh I want to capture subrequest by wireshark. But I found can't capture subrequest info.

**Comment by tokers** [comment]
@linux2014linux 
What's your subrequest's Nginx location configuration?

**Comment by linux2014linux** [comment]
@tokers 
The current request is http://ip:port/api/user/list. The subrequest is /api/user/find-one.Nginx conf is:

	server {
		server_name  <ip>;
		listen <port>;

		location ~ /api {
			access_by_lua_file "/home/me/test.lua";
			# rest api
			proxy_pass http://<ip>:8889;
		}
	}


test.lua is:

	local cjson = require("cjson");

	local userCheckService = "/api/user/find-one";
	local login_username = "test";
	ngx.req.set_header("X-USERNAME-X", login_username);
	if userCheckService ~= nil and string.len(userCheckService) > 0 then
		local subReqBody = {}
		subReqBody["user_name"] = login_username;
		subReqBody["status"] = 0;
		ngx.req.read_body();
		local result = ngx.location.capture(userCheckService, {method = ngx.HTTP_POST, body = cjson.encode(subReqBody)});
		ngx.log(ngx.ERR, "userCheckService: ", userCheckService, "result: ", cjson.encode(result));
		if result == nil then
			ngx.exit(403);
		end
	end

I can capture /api/user/list. But subrequest is not captured. The rest server can receive subrequest, but body is empty.
