### ISSUE TITLE
ngx.req.get_uri_args(): GET var EMPTY arg values appears inconsistent could be BOOLEAN true or empty STRING

### ISSUE THREAD

**Issue by diegomontoya** [openresty/lua-nginx-module#1432]
Url: **/?a&b=**

using ngx.req.get_uri_args() to retrive the above url args table we get the following type/values 

1)  var a: vtype = BOOLEAN value = true
2) var b: vtype = STRING value = "" (empty string)

Why do they have different values? This appears to be a bug in my view.

`
for k, v in pairs(ngx.req.get_uri_args()) do 
       if type(v) == "table" then
            print("TABLE k:", k)
	elseif type(v) == "string" then
           print("STRING k:", k, " v:", v)
        elseif type(v) == "boolean" then
           print("BOOLEAN k:", k, " v:", v)
        end
    end
`

**Comment by agentzh** [comment]
@diegomontoya Read the official documentation for this API:

https://github.com/openresty/lua-nginx-module/#ngxreqget_uri_args

This is by design.
