### ISSUE TITLE
body_filter_by_lua cannot get the chunk properly

### ISSUE THREAD

**Issue by softputer** [openresty/lua-nginx-module#1437]
i have set an https backend and read the response body in body_filter_by_lua.

When the https backend response body is quite short, according to the log, ngx.arg[1] is the correct response body.

But when the https response body is a little bit longer, ngx.arg[1] is messy code not string.

but no matter how long the response body is , When the backend is http server. ngx.arg[1] is the right response.

**Comment by softputer** [comment]
i found out that it is because the response body is gzip format. i am looking for a way to handle that now.

**Comment by agentzh** [comment]
You can just add `proxy_set_header Accept-Encoding "";` to your proxy's location. Otherwise you'll have to do gzip decompression in a streaming fashion inside the Lua body filter handler.
