### ISSUE TITLE
When the POST request is in json format, the Key and value cannot be extracted correctly.

### ISSUE THREAD

**Issue by iuime** [openresty/lua-nginx-module#1441]
When the POST request is in json format, the Key and value cannot be extracted correctly.
```
  location /test {
       content_by_lua_block {
           local arg = ngx.req.get_uri_args()
           for k,v in pairs(arg) do
               ngx.say("[GET ] key:", k, " v:", v)
           end
           ngx.req.read_body()
           local arg = ngx.req.get_post_args()
           for k,v in pairs(arg) do
               ngx.say("[POST] key:", k, " v:", v)
           end
       }
   }
```
json

![image](https://user-images.githubusercontent.com/41294179/50089995-55acdd00-0242-11e9-93e4-26fe443cda6a.png)

XML

![image](https://user-images.githubusercontent.com/41294179/50090105-90167a00-0242-11e9-9541-03796c478b4a.png)

**Comment by tokers** [comment]
@iuime 
The `ngx.req.get_post_args` function is used for extracting the request body organized as the `application/x-www-form-urlencoded` format, neither JSON nor XML.

You can always decode your request body by yourself, depends on the different `Content-Type` request header.

**Comment by agentzh** [comment]
Consider it resolved.
