### ISSUE TITLE
Nginx reload failed when using 'lua-openssl' and 'init_work_by_lua_block’

### ISSUE THREAD

**Issue by xliuqq** [openresty/lua-nginx-module#1442]
openresty/1.13.6.2,  openSSL 1.0.2k, lua-openssl-scm-5

nginx.conf:
```
init_by_lua_block {
    require("luarocks.loader")
    local cms = require(“openssl”).cms
}

init_worker_by_lua_block {
    -- empty content
}
```
Nginx starts successfully and works fine. But when nginx reload, the error info is :

2018/12/18 21:33:53 [notice] 28600#0: using the “epoll” event method
2018/12/18 21:33:53 [notice] 28600#0: start worker processes
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28968
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28969
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28970
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28971
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28972
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28973
2018/12/18 21:33:53 [emerg] 28968#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28969#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28970#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28971#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28972#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28973#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))

However, if I remove the "init_worker_by_lua_block", nginx can reload successfully.

What's the difference about 'init_worker_by_lua' between nginx start and reload？

**Comment by agentzh** [comment]
@xliuqq You should contact the author of the lua-openssl library you're using for support. It's known that not every Lua library supports the OpenResty environment and vice verse.
