### ISSUE TITLE
ngx.location.capture + access_by_lua_file = 404  ngx.location.capture+content_by_lua_file = 200

### ISSUE THREAD

**Issue by mrsWangxing** [openresty/lua-nginx-module#1443]
openresty version : 1.9.7.4    OS: centos 7   openresty Installation Path： /opt/openresty
1.create  a file  request_header.lua (/opt/openresty/nginx/lua/request_header.lua)
Content：
`ngx.req.set_header('Foo','Bar')`
`local res = ngx.location.capture('/api/sub_request_header.json')`
`if res.status == ngx.HTTP_OK then`
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ngx.say(res.body)`
`else`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ngx.say(res.status)`
`end`
2.create  another  file sub_request_header.lua (/opt/openresty/nginx/lua/sub_request_header.lua)
Content:
`local function print_table(t)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`local function parse_array(key,tab)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` local str = ''`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`for _, v in pairs(tab) do`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` str = str .. key .. '  ' .. v ..'\r\n'`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`end`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return str`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`end`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`local str = ''`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`for k,v in pairs(t) do`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`if type(v) == "table" then`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`str = str .. parse_array(k,v)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`else`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`str = str .. k .. ' ' .. v .. '\r\n'`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`end`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`end`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return str`
`end`
`local headers = ngx.req.get_headers()`
`ngx.say(print_table(headers))`
3.modify nginx.conf
primary coverage：
`server {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` listen 80;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` server_name localhost;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`lua_code_cache off;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`location /api/request_header.json {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`access_by_lua_file lua/request_header.lua;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` location /api/sub_request_header.json {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**_access_by_lua_file_**  lua/sub_request_header.lua;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` }`
` }`

4.run `curl 127.0.0.1/api/request_header.json ` it will return 404
error.log show 
`2018/12/25 17:03:11 [error] 29323#0: *10937 open() "/opt/openresty/nginx/html/api/sub_request_header.json" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /api/request_header.json HTTP/1.1", subrequest: "/api/sub_request_header.json", host: "127.0.0.1"
`
5.modify nginx.conf
 location /api/sub_request_header.json {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **_content_by_lua_file_**  lua/sub_request_header.lua;
}
reload nginx, 
run `curl 127.0.0.1/api/request_header.json `
 It's OK.

**Comment by qlees** [comment]
subrequest would bypass the access phase, so access_by_lua was not executed

**Comment by snpcp** [comment]
So how do you call nginx internal location?
