### ISSUE TITLE
[question]An easy way to open DDEBUG

### ISSUE THREAD

**Issue by jinleileiking** [openresty/lua-nginx-module#1446]
使用openresty  1.13.6.1 如果使用configure带单数打开DDEBUG`./configure --with-debug  --with-cc-opt="-D DDEBUG"` 会导致编译不过。

我目前的方式是改  `ddebug.h` 加` #define DDEBUG 1`

是否考虑这块优化一下？

-- 后续补英文翻译

**Comment by thibaultcha** [comment]
@jinleileiking Hi, please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
