### ISSUE TITLE
Using coroutines inside __tostring breaks string.format (attempt to yield across C-call boundary)

### ISSUE THREAD

**Issue by yangm97** [openresty/lua-nginx-module#1447]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/4412002/50665841-5a3ef880-0f99-11e9-82c3-5f26e86ec43d.png">

Although the test above was run inside the init context, I discovered this issue while writing a method for an object that only gets created during requests. Forcing tostring before passing the argument works as expected. For instance:

```
function User:getLink()
	return ('<a href="%s">%s</a>'):format("tg://user?id="..self.id, (self):escape_html()) -- broken
	return ('<a href="%s">%s</a>'):format("tg://user?id="..self.id, tostring(self):escape_html()) -- works
end
```

```
attempt to yield across C-call boundary
stack traceback:
	[C]: in function 'receive'
	/usr/local/openresty/site/lualib/resty/http.lua:323: in function '_receive_status'
	/usr/local/openresty/site/lualib/resty/http.lua:671: in function 'request'
	/usr/local/openresty/site/lualib/resty/http.lua:864: in function 'request_uri'
	...openresty/nginx//lua/vendor/telegram-bot-api/methods.lua:82: in function 'getChat'
	/usr/local/openresty/nginx//lua/groupbutler/user.lua:81: in function </usr/local/openresty/nginx//lua/groupbutler/user.lua:80>
	[C]: in function 'format'
	/usr/local/openresty/nginx//lua/groupbutler/user.lua:109: in function 'getLink'
[...]
```

**Comment by agentzh** [comment]
@yangm97 You should make sure your request_uri() code runs in contexts that can be yielded, like the request handler context (like `content_by_lua*` and `rewrite_by_lua*`) or the timer handler context (callback function in `ngx.timer.*`).
