### ISSUE TITLE
The body content obtained by using the ngx.req.get_body_data method is truncated The size of the body is only 4KB.

### ISSUE THREAD

**Issue by wangdasheng** [openresty/lua-nginx-module#1454]
I have a requirement to set the proxy to the external network through resty.http, and then set the response value obtained by resty.http to openresty to respond to the original request. But I can't read the post's body value when I get the request. No matter whether I get it directly from the body or through a temporary file, the value is around 4k, which makes me unable to get the complete request information.

I have set the configuration parameters below, but they are not resolved。
client_max_body_size 10m;
client_body_buffer_size 128k;
proxy_buffer_size 32k;
proxy_buffers 4 32k;
lua_need_request_body on;
lua_socket_buffer_size 128k;
client_body_in_file_only on;

function get_body()
--local body_data = ngx.var.request_body;
    ngx.req.read_body()
    local request_body = ngx.req.get_body_data()         
    if request_body then
        return request_body  --Type is string
    end
    -- body may get buffered in a temp file:
    local body_file = ngx.req.get_body_file()
        if body_file then
             ngx.log(ngx.NOTICE,"body is in file " )
             local body_file_handle, err = io.open(body_file, "r")
             if body_file_handle then
                  body_file_handle:seek("set")
                  request_body = body_file_handle:read("*a")
                  body_file_handle:close()
             else
                  request_body = ""
                  ngx.log(ngx.NOTICE,"failed to open  file or failed for reading: " )
             end
         else
             request_body = ""
             ngx.log(ngx.DEBUG, "no body found")
         end
               return request_body
end

I can't paste the complete code for some reason. The above configuration was written by me manually.

**Comment by tokers** [comment]
@wangdasheng 
Have you investigated the request body file by yourself? You can check it out.

**Comment by wangdasheng** [comment]
@tokers
Thank you for your answer.
 I use postman or soapui to make a call, using the post method to request, is a simple text, similar to key1=1, key2={a:223333, pric:"ddsdfsf"...}. But the value of a single parameter is very long, Can reach 20M, is the string after the picture is encoded by base64. I am currently passing a value of about 3M, but I can only get 4k in length on the openresty side, and the remaining parameters cannot be obtained.

**Comment by tokers** [comment]
> @tokers
> Thank you for your answer.
> I use postman or soapui to make a call, using the post method to request, is a simple text, similar to key1=1, key2={a:223333, pric:"ddsdfsf"...}. But the value of a single parameter is very long, Can reach 20M, is the string after the picture is encoded by base64. I am currently passing a value of about 3M, but I can only get 4k in length on the openresty side, and the remaining parameters cannot be obtained.

@wangdasheng 
You can check the temporary request body file itself, 
by configuring `client_body_in_file_only on `, Nginx will not remove this temporary file after request processing.

**Comment by wangdasheng** [comment]
> > @tokers
> > Thank you for your answer.
> > I use postman or soapui to make a call, using the post method to request, is a simple text, similar to key1=1, key2={a:223333, pric:"ddsdfsf"...}. But the value of a single parameter is very long, Can reach 20M, is the string after the picture is encoded by base64. I am currently passing a value of about 3M, but I can only get 4k in length on the openresty side, and the remaining parameters cannot be obtained.
> 
> @wangdasheng
> You can check the temporary request body file itself,
> by configuring `client_body_in_file_only on `, Nginx will not remove this temporary file after request processing.

I have looked at the client_body_temp directory on both the window and linux platforms. No files are generated (including hidden) and may be deleted after being generated. Although the file name of 0000000001 is printed in the log.

**Comment by tokers** [comment]
@wangdasheng 

I can't reproduce your problem in my own machine, I am using the combination of Nginx/1.15.x  and lua-nginx-module's master branch.

What's your OpenResty and lua-nginx-module version?

**Comment by wangdasheng** [comment]
> @wangdasheng
> 
> I can't reproduce your problem in my own machine, I am using the combination of Nginx/1.15.x and lua-nginx-module's master branch.
> 
> What's your OpenResty and lua-nginx-module version?

I am using the latest version of window "1.13.6.2-win64" Linux "1.13.6.2"。
I just used the sleep method to pause the program. I can see the temporary file. In this case, the contents of the file generated by nginx are complete.

**Comment by tokers** [comment]
Well, the reason why your request body temporary file would be deleted is caused by `ngx.req.read_body` (or the directive `lua_need_request_body on`), it involves their internal implementations.

**Comment by tokers** [comment]
> Well, the reason why your request body temporary file would be deleted is caused by `ngx.req.read_body` (or the directive `lua_need_request_body on`), it involves their internal implementations.

The implementation of `ngx.req.read_body` sets `r->request_body_in_cleanup_file` to `1`, it disregards the value of directive`client_body_in_file_only` (when setting to `on`). Is it a deliberate behavior? @agentzh

**Comment by wangdasheng** [comment]
My problem seems to be that the log print is incomplete and the actual data is complete. Thank you again for your answer. However, this is also a limited single log output length, and there is a problem with the temporary file you said. @tokers
