### ISSUE TITLE
Cosocket SSL/TLS client certificates support

### ISSUE THREAD

**Issue by tokers** [openresty/lua-nginx-module#1455]
Hello!

Does the Cosocket SSL/TLS client certificates support plan is in progress or it's still lying on the TODO list?

**Comment by tokers** [comment]
@agentzh @thibaultcha

**Comment by agentzh** [comment]
IIRC, there is some pending pull requests for it? Cannot remember the details.

**Comment by tokers** [comment]
OK, I will check the PR list.

**Comment by thibaultcha** [comment]
It is #997

**Comment by tokers** [comment]
@thibaultcha 
Nice :)
