### ISSUE TITLE
logging memory address of a table

### ISSUE THREAD

**Issue by ms2008** [openresty/lua-nginx-module#1457]
Is there a way to log the table's address by `ngx.log`? Just same as PUC Lua `print({})` outputs `table: 0xcc1e00` . This feature may be useful for debugging the weak table related issues.

**Comment by agentzh** [comment]
@ms2008 Just use the `tostring()` Lua API function yourself to generate such strings.

**Comment by agentzh** [comment]
@ms2008 A quick example:

```shell
$ resty -e 'ngx.log(ngx.WARN, tostring{ dog = 3 })'
2019/01/19 12:58:32 [warn] 898#898: *2 [lua] (command line -e):1: table: 0x7f25a530f508, context: ngx.timer
```
