### ISSUE TITLE
Заголовки не преобразуются в push

### ISSUE THREAD

**Issue by Wladimir-N** [openresty/lua-nginx-module#1458]
Включил http2_push_preload on;, если делать заголовок с nginx или php-fpm всё проходит корректно. Но если я делаю заголовки с lua из header_filter_by_lua_block {} при помощи ngx.header.link то заголовки есть, а push-запросов нет.
# uname -a

Linux web 4.4.138-qs #2 SMP Mon Oct 15 13:09:10 MSK 2018 x86_64 GNU/Linux

# nginx -V

nginx version: nginx/1.14.1 built with OpenSSL 1.1.0f 25 May 2017 (running with OpenSSL 1.1.0j 20 Nov 2018) TLS SNI support enabled configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-jqo7Nx/nginx-1.14.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-jqo7Nx/nginx-1.14.1/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-jqo7Nx/nginx-1.14.1/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-jqo7Nx/nginx-1.14.1/debian/modules/http-echo --add-dynamic-module=/build/nginx-jqo7Nx/nginx-1.14.1/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-jqo7Nx/nginx-1.14.1/debian/modules/http-subs-filter

**Comment by tokers** [comment]
@Wladimir-N 
There is already an in-flight Pull Request for fixing this problem: https://github.com/openresty/lua-nginx-module/pull/1389

**Comment by tokers** [comment]
> @Wladimir-N
> There is already an in-flight Pull Request to fix this problem: #1389

This Pull Request was merged just now. Now you can try the master branch and I believe the problem was fixed.

**Comment by tokers** [comment]
cc @thibaultcha

**Comment by thibaultcha** [comment]
Considering this resolved. Thanks @tokers.
