### ISSUE TITLE
Nginx logging hexadecimal Value to JSON data

### ISSUE THREAD

**Issue by kalra-4** [openresty/lua-nginx-module#1461]
Issue what I am facing is while capturing the post body(JSON) and storing to nginx variable and logging them , Nginx is adding the hexadecimal value . How to solve this problem
Openresty Version: openresty-1.13.6

POST BODY JSON
-----------
 {"email":"example@test.com","timestamp":1548674893,"smtp-id":"\u003c14c5d75ce93.dfd.64b469@ismtpd-555\u003e","event":"group_resubscribe","category":"cat facts","sg_event_id":"NDDk2zGTmz7aToepWvWVLg==","sg_message_id":"14c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0","useragent":"Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)","ip":"255.255.255.255","url":"http://www.test.com/","asm_group_id":10}
-----------

Sample code
--------------------
local json = require "cjson"
ngx.req.read_body()  -- explicitly read the req body
local data = ngx.req.get_body_data() 
if data then
	ngx.var.request_body_head = json.encode(data)
	ngx.exit(200)
else
	ngx.exit(500)
end
--------------------

OUTPUT
---------
{\x5C\x22email\x5C\x22:\x5C\x22example@test.com\x5C\x22,\x5C\x22timestamp\x5C\x22:1548674893,\x5C\x22smtp-id\x5C\x22:\x5C\x22\x5C\x5Cu003c14c5d75ce93.dfd.64b469@ismtpd-555\x5C\x5Cu003e\x5C\x22,\x5C\x22event\x5C\x22:\x5C\x22group_resubscribe\x5C\x22,\x5C\x22category\x5C\x22:\x5C\x22cat facts\x5C\x22,\x5C\x22sg_event_id\x5C\x22:\x5C\x22NDDk2zGTmz7aToepWvWVLg==\x5C\x22,\x5C\x22sg_message_id\x5C\x22:\x5C\x2214c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0\x5C\x22,\x5C\x22useragent\x5C\x22:\x5C\x22Mozilla\x5C/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)\x5C\x22,\x5C\x22ip\x5C\x22:\x5C\x22255.255.255.255\x5C\x22,\x5C\x22url\x5C\x22:\x5C\x22http:\x5C/\x5C/www.test.com\x5C/\x5C\x22,\x5C\x22asm_group_id\x5C\x22:11}]\x22
---------

**Comment by agentzh** [comment]
@kalra-4 Just put the following line to your `nginx.conf`:

```nginx
log_escape_non_ascii off;
```

It's an OpenResty feature.

**Comment by gfuentesmorales** [comment]
@agentzh log_escape_non_ascii not work for me, my nginx.conf

```
 log_format bodylog '$remote_addr - $remote_user [$time_local] '  '"$request" $status 
$body_bytes_sent ' '"$http_referer" "$http_user_agent" $request_time '  
'request:["$request_body"],  response["$resp_body"]';

server {
        listen       9090;
        log_escape_non_ascii off;
       ....
       
}
```


```
request:["{\x0A\x09\x22hola\x22: \x22hello\x22\x0A}"], response["<p>hello, world</p>\x0A"]
```

**Comment by agentzh** [comment]
@gfuentesmorales You can try putting that in your `http {}` block directly, just in case you have other `server {}` blocks.

You're talking about access logs, right?

**Comment by agentzh** [comment]
@gfuentesmorales Also, make sure your nginx has successfully reloaded your new config.

**Comment by gfuentesmorales** [comment]
@agentzh 

> @gfuentesmorales You can try putting that in your `http {}` block directly, just in case you have other `server {}` blocks.
> 
> You're talking about access logs, right?

yes, on my acess logs,

Ok, i will try add on ``` http {} ```

**Comment by kalra-4** [comment]
Its not working for me . Still getting the this error while we write to new variable .

**Comment by agentzh** [comment]
@gfuentesmorales @kalra-4 Try adding the `escape=none` option to your `log_format` directive. See the documentation below for more details:

http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format

One example is like this:

```nginx
log_format bodylog escape=none '$remote_addr - $remote_user [$time_local] $request_body';
```

And a sample access log entry would be like this:

```
127.0.0.1 -  [17/Feb/2019:12:24:14 -0800] {
    "hello": 32,
}
```

**Comment by KeithTt** [comment]
> @gfuentesmorales @kalra-4 Try adding the `escape=none` option to your `log_format` directive. See the documentation below for more details:
> 
> http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format
> 
> One example is like this:
> 
> ```nginx
> log_format bodylog escape=none '$remote_addr - $remote_user [$time_local] $request_body';
> ```
> 
> And a sample access log entry would be like this:
> 
> ```
> 127.0.0.1 -  [17/Feb/2019:12:24:14 -0800] {
>     "hello": 32,
> }
> ```

It is strange that my openresty does not support `escape=none` this property...

**Comment by nirajmchauhan** [comment]
> @gfuentesmorales @kalra-4 Try adding the `escape=none` option to your `log_format` directive. See the documentation below for more details:
> 
> http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format
> 
> One example is like this:
> 
> ```nginx
> log_format bodylog escape=none '$remote_addr - $remote_user [$time_local] $request_body';
> ```
> 
> And a sample access log entry would be like this:
> 
> ```
> 127.0.0.1 -  [17/Feb/2019:12:24:14 -0800] {
>     "hello": 32,
> }
> ```

This works, thanks @agentzh
