### ISSUE TITLE
HTTP Status Codes (302, 501) names are incorrect

### ISSUE THREAD

**Issue by karai17** [openresty/lua-nginx-module#1466]
In reading the docs for this module, I noticed that the HTTP status codes have minor naming issues.

* ngx.HTTP_MOVED_TEMPORARILY (302) should be [ngx.HTTP_FOUND](https://en.wikipedia.org/wiki/HTTP_302)
* ngx.HTTP_METHOD_NOT_IMPLEMENTED (501) should be [ngx.HTTP_NOT_IMPLEMENTED](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors)

**Comment by karai17** [comment]
Sure thing. Would it be fine if I added a second 302 with the correct HTTP specification name as well?

**Comment by agentzh** [comment]
@karai17 for 302, I don't think so, should just be consistent with the nginx core :)

**Comment by karai17** [comment]
I already added both before you replied. You can cherry pick the PR if you'd rather not add the 302. I personally feel that having a constant that matches the HTTP spec is a good idea, but I also understand why an ngx module would prefer to follow ngx over the HTTP spec.

**Comment by agentzh** [comment]
@karai17 Please update the PR yourself since it'll be easier for us :) Thanks!

**Comment by karai17** [comment]
I sent a new PR as I didn't want to clutter up the commit log with my fumbling~
