### ISSUE TITLE
check lua_shared_dict array contains specific value

### ISSUE THREAD

**Issue by hexb0307** [openresty/lua-nginx-module#1474]
`
=== TEST 2: get operation on list type
--- http_config
    lua_shared_dict dogs 1m;
--- config
    location = /test {
        content_by_lua_block {
            local dogs = ngx.shared.dogs

            local len, err = dogs:lpush("foo", "bar")
            if len then
                ngx.say("push success")
            else
                ngx.say("push err: ", err)
            end

            local val, err = dogs:get("foo")
            ngx.say(val, " ", err)
        }
    }
--- request
GET /test
--- response_body
push success
nil value is a list
--- no_error_log
[error]
`

here, check if the "foo" list contains "bar"?

**Comment by hexb0307** [comment]
can i print the values of "foo" list?

**Comment by agentzh** [comment]
@hexb0307 Once we have the `lindex` method (from the same-name redis command), we could easily do this with it and the existing `llen()` method. Patches welcome :)

**Comment by hexb0307** [comment]
Thank you very much for your reply.
I have tried the `llen()` method.

**Comment by hexb0307** [comment]
非常感谢您百忙之中抽空回复，可能是我这蹩脚的英语没有表达清楚，这里我是想查看'foo'数组里面是否存在'bar'这个值。我尝试了'llen()'方法，但是得到的是'foo'数组的元素个数。是我使用'llen()'方法有问题吗？

**Comment by tokers** [comment]
@hexb0307 
Currently there is no elegant way to do this. You may try to check every element in the list with the `lpop` method and re-push them with the `rpush` method.

**Comment by hexb0307** [comment]
@tokers Thank you very much for your help.
