### ISSUE TITLE
ngx.var vs ngx.ctx

### ISSUE THREAD

**Issue by ktalebian** [openresty/lua-nginx-module#1482]
What is the different between `ngx.var` and `ngx.ctx`? I know `var` can only hold string values, while `ctx` can hold any variable, so it seems like it's easier to use `ngx.ctx` all the time. 

Does the `ctx` persist through internal proxies? Does it have any performance issues? When should one use `var` or `ctx`?

**Comment by agentzh** [comment]
@ktalebian Use `ngx.ctx` wherever you can. `ngx.var` is much more expensive and is also limited to string values. The latter should only be used to exchange data with other nginx C modules.

BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions. Thanks for
your cooperation! Please see https://openresty.org/en/community.html
