### ISSUE TITLE
lua tcp socket connections count return -1

### ISSUE THREAD

**Issue by AlexProfi** [openresty/lua-nginx-module#1490]
Hello I use nginx 1.15.8 and lua-nginx-module 0.10.14rc6 and lua-resty-redis
and get this error ander highload
I use redis in kubernetes cluster with nginx pods
lua tcp socket connections count  mismatched for connection pool "redis-svc.default.svc.cluster.     local:6379", connections: -1, size: 32768
my settings
          - name: REDIS_TIMEOUT
            value: "2000"
          - name: REDIS_PASSWORD
            value: _redis-server._tcp.redis-server.default.svc.cluster.local
          - name: REDIS_KEEPALIVE_TIMEOUT
            value: "20000"
          - name: REDIS_KEEPALIVE_POOLSIZE
            value: "32768"
and this is my code:

```
local redis_host = os.getenv("REDIS_HOST") .. "." .. os.getenv("NAMESPACE") .. ".svc." .. os.getenv("CLUSTER_NAME")
local red = redis:new()
--TODO If consumption of memory will be encrease try to enable timeout (in config now it is 25 ms)
red:set_timeout(os.getenv("REDIS_TIMEOUT"))
ngx.log(ngx.INFO, "Redis service host: ", redis_host)

--Connect to REDIS
local ok, err = red:connect(redis_host, os.getenv("REDIS_PORT"))
local res_fingerprint, err = red:exists("test")
local ok, err = red:set_keepalive(os.getenv("REDIS_KEEPALIVE_TIMEOUT"), os.getenv("REDIS_KEEPALIVE_POOLSIZE"))
if not ok then
    ngx.log(ngx.ERR, "Failed to set keepalive to redis connection: ", err)
    return
end
```
How to fix this

**Comment by agentzh** [comment]
@AlexProfi Will you provide a minimal and standalone example that we can relatively easily reproduce the issue on our side? It's not obvious how you fetch that "connections" count in the code snippet, for example.

**Comment by spacewander** [comment]
@AlexProfi 
Have you observed any network faults when `"socket connections count mismatched"` occurred?

**Comment by thibaultcha** [comment]
v0.10.14rc6 does not have the latest fix with connections counting in high concurrency scenarios: https://github.com/openresty/lua-nginx-module/compare/v0.10.14rc6...master

Please have a try with v0.10.14 instead.

**Comment by AlexProfi** [comment]
> @AlexProfi Will you please provide a minimal and standalone example that we can (relatively) easily reproduce the issue on our side? It's not obvious how you fetch that "connections" count in the code snippet, for example.

This is all of my code on lua. It's very simple But I use test with ab with -c 500 in parrallel -j8

**Comment by AlexProfi** [comment]
> v0.10.14rc6 does not have the latest fix with connections counting in high concurrency scenarios: [v0.10.14rc6...master](https://github.com/openresty/lua-nginx-module/compare/v0.10.14rc6...master)
> 
> Please have a try with v0.10.14 instead.

Thanks. I don't see this errors in nginx logs

**Comment by agentzh** [comment]
@AlexProfi BTW, it's recommended to use OpenResty 1.15.8.1 RC1 though:

https://openresty.org/en/ann-1015008001rc1.html

The standard nginx cores never fully pass our test suite anyway.

**Comment by thibaultcha** [comment]
Should we consider this resolved for now? If the issue reappears @AlexProfi, you can still reopen this issue, or open a new one in case something else occurs.

**Comment by AlexProfi** [comment]
Ok thanks

**Comment by AlexProfi** [comment]
> @AlexProfi BTW, it's recommended to use OpenResty 1.15.8.1 RC1 though:
> 
> https://openresty.org/en/ann-1015008001rc1.html
> 
> The standard nginx cores never fully pass our test suite anyway.

Ok I will wait when it have status stable
