### ISSUE TITLE
ngx_http_lua_socket_tcp.c - tcpsock:connect - random IP from list is wrong and retries to other IPs should be implemented

### ISSUE THREAD

**Issue by jarekchr** [openresty/lua-nginx-module#1494]
Issue:
For cases where connection has to be established with address given as FQDN and DNS will resolve it to more than 1 IP addresses code will take randomly one of them ("i = ngx_random() % ur->naddrs;"). This behaviour is wrong from few reasons:
- typically (by default) DNSes (like bind) returns addresses in round-robin mode so each query will get the same list of IP addresses but in different order - using random IP from the list will make that load sharing implemented in that way will not work
- if DNS has different weights for the list of IP addresses (this is typically for MX or SRV type of records) then first the list will be returned in order reflecting them and after applying round-robin in case weights are the same. Additionally for those cases operators can for example lower weight of the given server if there's some maintenance operations on it. Using random address will cause that we'll hit the server that is not working.
- note that some advanced DNS servers are able to monitor if given IP address is alive (typically this is not configured for all IPs that this server is handling)

Expected behaviour:
1) For cases when DNS returns more than 1 IP address for given FQDN try to connect with the first one from the list.
2) If connection fails then try connection with the 2nd and then next from the list till the end (it will require implementation of additional timeouts here).
3) Error should be returned when connection wasn't possible to any of the IPs on the list returned by DNS.

Version - at the moment of opening this issue master is ngx_lua v0.10.14 but issue exists in previous versions.

Test case - DNS (for example bind) returning multiple (2 or more) IP addresses for FQDN in round-robin mode, one or more of them are not responding

Thanks and regards,
Jarek

**Comment by agentzh** [comment]
@jarekchr Well, that's the behavior nginx core's builtin resolver. If you don't want that, you can always query the DNS via libraries like lua-resty-dns (which is also part of OpenResty), and feed whatever IP addresses you like specifically into this `connect()` method.

**Comment by jarekchr** [comment]
Hi,
I can write that I'm not happy with your response.
Knowing typical default DNS servers behaviour, using random address is not the best in my opinion.
This could be also configurable if somebody want's random or not.
Regards,
Jarek
