### ISSUE TITLE
ssl_certificate_by_lua_block "simple example" in readme is too simple

### ISSUE THREAD

**Issue by rulatir** [openresty/lua-nginx-module#1508]
The `ssl_certificate_by_lua_block` "trivial example" in readme is not even "trivial" - it's a functional no-op that only prints a message and doesn't do any actual ssl stuff:

```
 server {
     listen 443 ssl;
     server_name   test.com;

     ssl_certificate_by_lua_block {
         print("About to initiate a new SSL handshake!")
     }

     location / {
         root html;
     }
 }
```

The documentation links to some more complicated examples and that's OK, but I think that the example shown inline should document the "simplest usage that ActuallyDoesSomething™", as opposed to the "simplest usage that just places the directive in the nginx config file in a syntactically correct way".

**Comment by thibaultcha** [comment]
This example documents the Lua hook, where and how it is being executed. The hook in itself doesn't do anything else. And that is fine. More complete documentation on which functions may be used in this phase and to what purpose can be found in the lua-resty-core `ngx.ssl` module documentation, which, as you pointed out, is already mentioned in the `ssl_certificate_by_lua_block` documentation. Thank you for the feedback, but we judge the example appropriate.
