### ISSUE TITLE
failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: OPENSSL_sk_new_null)

### ISSUE THREAD

**Issue by asshaposhnikov** [openresty/lua-nginx-module#1509]
After install Lua as dynamic module, and enable in *.conf - error geted.

nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: OPENSSL_sk_new_null) in /etc/nginx/nginx.conf:19
nginx: configuration file /etc/nginx/nginx.conf test failed

Nginx v 1.15.10
3rd party modules installed:
pagespeed
memc
srcache
ndk_http_module
set_misc
headers_more
http_js
stream_js
replace_filter
brotli
lua

OpenSSL v 1.0.2g
Ubuntu 16.04

**Comment by asshaposhnikov** [comment]
Solved, by installing OpenSSL 1.1.1b in system and compile Nginx v 1.15.12 with modules Lua, and others.  But get new error. When run Lua code in conf file:

location / {
       content_by_lua_file /etc/...luafile.lua;
}

luafile.lua
res = ngx.location.capture("/abcdef", {copy_all_vars = true});
ngx.print(res.body)
ngx.say("headers:" res.header)

Error:
2019/04/22 18:10:33 [error] 19006#19006: *1 lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'), client: 11.22.11.22, server: example.com, request: "GET / HTTP/2.0", host: "example.com"
2019/04/22 18:10:33 [error] 19006#19006: *1 lua entry thread aborted: runtime error: ...ble/example.com/luafile.lua:1: http2 requests not supported yet
stack traceback:
coroutine 0:
	[C]: in function 'capture'
	...ble/example.com/luafile.lua:1: in main chunk, client: 11.22.11.22, server: example.com, request: "GET / HTTP/2.0", host: "example.com"

**Comment by chobits** [comment]
Same error message with nginx 1.15.12, think that it is triggered by [`default: lua_load_resty_core on`](https://github.com/openresty/lua-nginx-module#lua_load_resty_core).

**Comment by chobits** [comment]
@asshaposhnikov 

> Error:
2019/04/22 18:10:33 [error] 19006#19006: *1 lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:

Added `lua_load_resty_core off;` into http {} block of nginx.conf

> **Solved**, by installing OpenSSL 1.1.1b in system and compile Nginx v 1.15.12 with modules Lua, and others. But get new error. When run Lua code in conf file:
> 
> location / {
> content_by_lua_file /etc/...luafile.lua;
> }
> 
> luafile.lua
> res = ngx.location.capture("/abcdef", {copy_all_vars = true});
> ngx.print(res.body)
> ngx.say("headers:" res.header)
> 
> Error:
> 2019/04/22 18:10:33 [error] 19006#19006: *1 lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
> no field package.preload['resty.core']
> no file './resty/core.lua'
> no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core/init.lua'
> no file './resty/core.so'
> no file '/usr/local/lib/lua/5.1/resty/core.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> no file './resty.so'
> no file '/usr/local/lib/lua/5.1/resty.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'), client: 11.22.11.22, server: example.com, request: "GET / HTTP/2.0", host: "example.com"
> 2019/04/22 18:10:33 [error] 19006#19006: *1 lua entry thread aborted: runtime error: ...ble/example.com/luafile.lua:1: http2 requests not supported yet
> stack traceback:
> coroutine 0:
> [C]: in function 'capture'
> ...ble/example.com/luafile.lua:1: in main chunk, client: 11.22.11.22, server: example.com, request: "GET / HTTP/2.0", host: "example.com"

Try added `lua_load_resty_core off;` into http{} block of nginx conf.

**Comment by thibaultcha** [comment]
It seems like the initial issue was solved. As for lua-resty-core, you can still disable the `lua_load_resty_core` directive for the time being. In an upcoming release, lua-resty-core will become mandatory.

**Comment by mrPsycho** [comment]
@thibaultcha am i getting right, that in next versions it will be impossible to include lua-resty as module to standart nginx? 

also how affects `lua_load_resty_core off;` on lua support?

**Comment by agentzh** [comment]
@mrPsycho The lua-resty-core library will be a mandatory requirement for this module. That's all. The old CFunction-based API is buggy and slow and we're retiring it.

**Comment by aptalca** [comment]
@agentzh is there a dynamic module for resty-core? If not, does that mean that the only way to use the lua-nginx module in the future is to use openresty instead of nginx? (Currently we can build a dynamic module for lua-upstream with nginx)
