### ISSUE TITLE
`env` directive setting is nil value inside lua script (os.getenv('') ) 

### ISSUE THREAD

**Issue by lbthanh** [openresty/lua-nginx-module#1510]
Hi,

I would like to get environment variable from lua script via os.getenv("var_name") but the value is empty (nil). Is this a bug or I lacked of setting in the config file.

Here is my config files.

**nginx.conf**

```
env VAR1;  # The variable was set at /etc/environment

http {   

    lua_package_path "/var/lib/lua/lib/?.lua;";
    server {
        include /var/lib/lua/lua.conf;    
    }
}
```

**lua.conf**

```
location /test1 {
    content_by_lua_file /var/lib/lua/test1.lua;
}

location /test2 {
     content_by_lua_block {
         ngx.say(os.getenv("VAR1"));
     }
}
```

**test1.lua**
```
ngx.say(os.getenv("VAR1"));
```

Using version:
Lua 5.1.4
nginx/1.13.8
lua-nginx-module-0.10.14rc4
lua-jit 2-2.1-20190130

**Comment by spacewander** [comment]
@lbthanh 
I can't reproduce the issue with configuration below:

```nginx
env PATH;
events {
    worker_connections 64;
}

http {
    server {
        location /test2 {
            content_by_lua_block {
                ngx.say(os.getenv("PATH"));
            }
        }
    }
}
```

Could you confirm if the `VAR1` is really applied? You could use `gdb` or a Nginx C module to get the environment.

AFAIK, `/etc/environment` is part of the PAM (Pluggable Authentication Module). It works with login shell, but system services like `systemd` don't take it account. Maybe you are running the Nginx as a service?

**Comment by spacewander** [comment]
Consider it fixed.

**Comment by liangpinglk** [comment]
> @lbthanh
> I can't reproduce the issue with configuration below:
> 
> ```nginx
> env PATH;
> events {
>     worker_connections 64;
> }
> 
> http {
>     server {
>         location /test2 {
>             content_by_lua_block {
>                 ngx.say(os.getenv("PATH"));
>             }
>         }
>     }
> }
> ```
> 
> Could you confirm if the `VAR1` is really applied? You could use `gdb` or a Nginx C module to get the environment.
> 
> AFAIK, `/etc/environment` is part of the PAM (Pluggable Authentication Module). It works with login shell, but system services like `systemd` don't take it account. Maybe you are running the Nginx as a service?

@spacewander  I also had meet the prolem， i can get path value ,but ican't get myself env which i had set.
![image](https://user-images.githubusercontent.com/25102090/96864581-395fd400-149b-11eb-98c0-06749fcc8e55.png)
