### ISSUE TITLE
openresty ngx.var.uri or nginx.var.request_url lost "#arg"

### ISSUE THREAD

**Issue by jkzhao** [openresty/lua-nginx-module#1511]
when request url contains #, the string after # all lost.

**for example:**
**chrome input url:**     http://gemini.wisedu.com/gemini_dev/sys/skylobby/index.do?a=1#mod=aaa
**nginx error.log:**    /gemini_dev/sys/skylobby/index.do?a=1

"#mod=aaa" is lost

**Comment by tokers** [comment]
@jkzhao 
The fragment part is used for the client side resources indirect referencing and it not used in the scheme-specific processing of URI.

The following paragraph is an excerpt from [RFC3986-section3.5](https://tools.ietf.org/html/rfc3986#section-3.5):

> Fragment identifiers have a special role in information retrieval
   systems as the primary form of client-side indirect referencing,
   allowing an author to specifically identify aspects of an existing
   resource that are only indirectly provided by the resource owner.  As
   such, the fragment identifier is not used in the scheme-specific
   processing of a URI; instead, the fragment identifier is separated
   from the rest of the URI prior to a dereference, and thus the
   identifying information within the fragment itself is dereferenced
   solely by the user agent, regardless of the URI scheme.  Although
   this separate handling is often perceived to be a loss of
   information, particularly for accurate redirection of references as
   resources move over time, it also serves to prevent information
   providers from denying reference authors the right to refer to
   information within a resource selectively. Indirect referencing also
   provides additional flexibility and extensibility to systems that use
   URIs, as new media types are easier to define and deploy than new
   schemes of identification.

**Comment by spacewander** [comment]
Consider it fixed.
