### ISSUE TITLE
HTTP/2 capture headers and parsing html body on the fly

### ISSUE THREAD

**Issue by asshaposhnikov** [openresty/lua-nginx-module#1517]
Hello. Im try Lua, good tool. But i have two tasks to solve. 
1. Reading and modifying response headers in nginx reverse proxy
2. Read and analyze response html body, without modifying.

My server work with HTTP/2 protocol, and unfortunately Lua -> Capture - dont able to work with HTTP/2 protocol. Is there any way to solve this tasks by Lua ?

**Comment by spacewander** [comment]
Maybe you could use [`header_filter_by_lua*` ](https://github.com/openresty/lua-nginx-module#header_filter_by_lua) to modify the header, and [`body_filter_by_lua*`](https://github.com/openresty/lua-nginx-module#body_filter_by_lua) to read the body.

Note that `body_filter_by_lua*` filters the output as a stream, so it may be called multiple times during a response.

**Comment by spacewander** [comment]
Consider it fixed.
