### ISSUE TITLE
Global variables _G print alarms in the init and init_worker phases

### ISSUE THREAD

**Issue by kingljl** [openresty/lua-nginx-module#1521]
Hello, version 1.15.8.1, init and init_worker will print the alarm "2019/05/06 09:33:44 [warn] 58681#58681: *2 [lua] _G write guard:12: writing a global lua variable ( 'socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables", but see https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_util .c#L820 is judged here, but it actually prints a warning. See https://github.com/openresty/lua-nginx-module/blob/master/t/158-global-var.t here is not covered here. Can I fix this?

The following is a warning message for kong using third-party libraries。
2019/05/06 09:50:23 [warn] 59201#59201: *2 [lua] _G write guard:12: writing a global lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
2019/05/06 09:50:23 [warn] 59201#59201: *2 [lua] _G write guard:12: writing a global lua variable ('crypto') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
...

**Comment by spacewander** [comment]
It is weird. There is a test case cover this case: https://github.com/openresty/lua-nginx-module/blob/master/t/158-global-var.t#L431

Will you provide a minimal example to reproduce the issue?

**Comment by kingljl** [comment]
> It is weird. There is a test case cover this case: https://github.com/openresty/lua-nginx-module/blob/master/t/158-global-var.t#L431
> 
> Will you provide a minimal example to reproduce the issue?

Sorry, my question. After tracing, we enter the timer stage, so we can report the exception.
