### ISSUE TITLE
How to Install "pintsized/lua-resty-http"?

### ISSUE THREAD

**Issue by mpv945** [openresty/lua-nginx-module#1522]
I am compiling and installing nginx, LuaJIT, lua-nginx. 
Now download lua-resty-http to get the Lua file and introduce it into the module for use?

**Comment by linsir** [comment]
You should install [opm](https://github.com/openresty/opm), and `opm get  pintsized/lua-resty-http`. Or download `pintsized/lua-resty-http` sourcecode to `lualib` default is `/usr/local/openresty/lualib/`.

**Comment by thibaultcha** [comment]
Install it via opm, LuaRocks, or even manually. Make sure that `LUA_PATH` or `lua_package_path` include the directory where lua-resty-http's sources are installed.

Best,
