### ISSUE TITLE
[feature request] - json format messages coming from ngx.log()

### ISSUE THREAD

**Issue by dorongold** [openresty/lua-nginx-module#1526]
Nginx allows setting custom log format for access logs.
However, I realize that the Nginx core does not provide a way to customize error logs.

In our Lua code we use `ngx.log(...)` statements.
Because these are being written to the error log, we have no way to customize their format.
Since all our logs (both access log and error log) go to stdout and are then collected by logstash, we need a way to set **all** logs to have a json format.

Is there currently, or in plan, any way to achieve this?
As a workaround, is there a way to send messages coming from `ngx.log()` to access log instead of error log?

**Comment by thibaultcha** [comment]
Hello,

Alas, there is no way to fully override the error log formats in NGINX. The `ngx.errlog` module has a couple of compromise solutions though.

1. [raw_log()](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md#raw_log) was partly developed to solve this use-case. Not all of the log will be JSON-encoded, but it gives you a lot more freedom and flexibility than `ngx.log()`. Besides, it has a couple of other advantages, such as the ability to JIT.
2. [get_logs()](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md#get_logs) will allow you to retrieve the log line as a Lua table, which you can then JSON-encode if you wish so.

Either of those methods, or even a combination of both, would allow you to send your logs to logstash with a JSON format.

Best of luck,

**Comment by dorongold** [comment]
Thanks for the suggestions.
I eventually wrote a custom logger module which uses `raw_log()` to emit json.
There is still a non-json prefix added by nginx, but I was able extract just the json part at the logstash side.

**Comment by lowolf** [comment]
> Thanks for the suggestions.
> I eventually wrote a custom logger module which uses `raw_log()` to emit json.
> There is still a non-json prefix added by nginx, but I was able extract just the json part at the logstash side.

And where we can look your custom logger module which uses raw_log() to emit json?
