### ISSUE TITLE
ngx.re.match “no request object found“”

### ISSUE THREAD

**Issue by uttinie** [openresty/lua-nginx-module#1528]
`http {
    init_by_lua '
         dofile("/usr/local/NSP/etc/nginx/init_test.lua")
    ';
}`

> [root@localhost nginx]# cat init_test.lua
--15RC1  Uncomment
require "resty.core"
local validation_util={}
local log = ngx.log
local ERR = ngx.ERR
local ngx_phase = ngx.get_phase

local ip_is_valid =function (ip)
    log(ERR,"DPF1:", ip)
    if type(ip) ~= "string" then
        return false
    end
    log(ERR,"DPF1:", ip,",ngx.get_phase:", ngx_phase())
    local subip, err = ngx.re.match(ip, [[^(\d+)\.(\d+)\.(\d+)\.(\d+)$]], "jo")
    if not subip or #subip ~= 4 then
        return false
    end

    if tonumber(subip[1]) == 0 then
        return false
    end

    for i=1,4,1 do
        local n = tonumber(subip[i]);
        if n < 0 or n >255 then
            return false
        end
    end
    return true
end

ip_is_valid("127.0.0.1")

ngx.re.match can work in the version openresty-1.15.8.1RC1，but “no request object found” happened when i update the version to openresty-1.15.8.1.
Query api introduction, ngx.re.match does not support init_by_lua, why the 15RC1 version may work properly, is my use problem?

**Comment by thibaultcha** [comment]
Hi,
Thanks for reporting, I will have a look shortly.

**Comment by agentzh** [comment]
@uttinie Seems like you configured `lua_load_resty_core off;` in your `nginx.conf`? You'll get that error when you disable lua-resty-core. The old CFunction-based API never works in the context of `init_by_lua*`.

**Comment by agentzh** [comment]
@uttinie See the following test case in this project's test suite:

https://github.com/openresty/lua-nginx-module/blob/master/t/034-match.t#L1132

It passes with lua-resty-core loaded (which is the default behavior in OpenResty 1.15.8.1).

**Comment by thibaultcha** [comment]
Back to a laptop (was on mobile). This seemed the most likely culprit to me as well this morning, thanks for dropping in @agentzh!

**Comment by uttinie** [comment]
> @uttinie See the following test case in this project's test suite:
> 
> https://github.com/openresty/lua-nginx-module/blob/master/t/034-match.t#L1132
> 
> It passes with lua-resty-core loaded (which is the default behavior in OpenResty 1.15.8.1).

Sir, I noticed this lua_load_resty_core configuration, even if I actively set lua_load_resty_core on will report this error. In the RC1 version init_test.lua call "require resty.core" is normal operation

**Comment by agentzh** [comment]
@uttinie Try killing all nginx processes and then start again. Also make sure you don't have any stale version of lua-resty-core in your Lua library search paths.

**Comment by uttinie** [comment]
> @uttinie Try killing all nginx processes and then start again. Also make sure you don't have any stale version of lua-resty-core in your Lua library search paths.

@agentzh 

Did this error not happen in your environment? I have replaced all lua files in the /openresty/openresty-1.15.8.1/bundle/lua-resty-core-0.1.17/lib directory and /openresty/openresty-1.15.8.1/build/luajit-root/usr/ Local/NSP/luajit, still not, can I still have other omissions?

**Comment by agentzh** [comment]
@uttinie You should never replace any files in our OpenResty directory. That broke your "warranty". We won't support your own modified version.

**Comment by agentzh** [comment]
@uttinie As I already said above, we already have test case covering this usage and it passes without any issues.
