### ISSUE TITLE
nginx: [error] lua_load_resty_core failed to load the resty.core module 

### ISSUE THREAD

**Issue by wangkepermit** [openresty/lua-nginx-module#1533]
Thanks for your help！
### base info：
      nginx：1.10.1
      luagit：2.1
      ngx_devel_kit：0.2.19
      lua-nginx-module:0.10.15
### configure command for nginx：
./configure --prefix=/opt/nginx-1.10.1 --with-ld-opt='-ljemalloc' --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib" --add-module=/usr/local/src/freeapis-nginx/lua-nginx-module-0.10.2 --add-module=/usr/local/src/freeapis-nginx/ngx_devel_kit-0.2.19

### error messages in nginx startup：
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/luajit/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/local/luajit/share/lua/5.1/resty/core.lua'
	no file '/usr/local/luajit/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/luajit/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by wangkepermit** [comment]
my system is CentOS7：Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by spacewander** [comment]
See https://github.com/openresty/lua-nginx-module/pull/1501#issuecomment-486123650.
You need to put [lua-resty-core](https://github.com/openresty/lua-resty-core/releases/tag/v0.1.17) in your `package.path`.

**Comment by wangkepermit** [comment]
> See [#1501 (comment)](https://github.com/openresty/lua-nginx-module/pull/1501#issuecomment-486123650).
> You need to put [lua-resty-core](https://github.com/openresty/lua-resty-core/releases/tag/v0.1.17) in your `package.path`.

thank you ，i try

**Comment by Firegarden** [comment]
How do you actually do this? I am having same problem.

**Comment by aftabnaveed** [comment]
@wangkepermit 
> You need to put lua-resty-core in your package.path.
I am using the official docker container, isn't that supposed to be in the path already?

**Comment by Firegarden** [comment]
> 
> 
> @wangkepermit
> 
> > You need to put lua-resty-core in your package.path.
> 
> I am using the official docker container, isn't that supposed to be in the path already?

**Example:** sudo nano /etc/nginx/nginx.conf
`    # LUA Global Variables
    #lua_load_resty_core off; # If you don't have lua core this will disable warn
    lua_package_path "/usr/local/lib/lua/?.lua;;";`

**Comment by a575606** [comment]
> @wangkepermit
> 
> > You need to put lua-resty-core in your package.path.
> 
> I am using the official docker container, isn't that supposed to be in the path already?

my question exactly

**Comment by yjfvictor** [comment]
> > See [#1501 (comment)](https://github.com/openresty/lua-nginx-module/pull/1501#issuecomment-486123650).
> > You need to put [lua-resty-core](https://github.com/openresty/lua-resty-core/releases/tag/v0.1.17) in your `package.path`.
> 
> thank you ，i try

Where is `package.path`?

**Comment by yjfvictor** [comment]
> See [#1501 (comment)](https://github.com/openresty/lua-nginx-module/pull/1501#issuecomment-486123650).
> You need to put [lua-resty-core](https://github.com/openresty/lua-resty-core/releases/tag/v0.1.17) in your `package.path`.

Where is `package.path`?

**Comment by abhipsamishra0110** [comment]
Any fixes available for this please? I have a similar issue on MAC M1, while running on docker. nginx shows as starting up successfully but the logs show PANIC!

**Comment by Firegarden** [comment]
Did you add the path to your nginx config?
`lua_package_path "/usr/local/lib/lua/?.lua;;";`

**Comment by abhipsamishra0110** [comment]
Indeed I have, but I get this error consistently when nginx starts up.

PANIC: unprotected error in call to Lua API (bad light userdata pointer),

am using LuaJIT Version 2.1.0-beta3 and openresty-lua-nginx-module of version 0.10.15. Ngnix alpine version of 1.14.2.

Badly stuck on this, tried all kinds of workarounds, like adding lua package path and upgrading libraries, but nothing works :(

**Comment by Firegarden** [comment]
Perhaps you would like to try the latest openresty version of [LuaJIT v2.1-20210510](https://github.com/openresty/luajit2/releases)?

**Comment by Firegarden** [comment]
I am now having the same problem. I will try clone current project from lua-resty-core

**Comment by zhuizhuhaomeng** [comment]
you should add the detail info about how you build your openresty/nginx

**Comment by Firegarden** [comment]
Turns out I was using an older version of the code and by cloning the current project I was able to build fine on Ubuntu 20. Sorry for the confusion.

**Comment by nilyang** [comment]
> Did you add the path to your nginx config? `lua_package_path "/usr/local/lib/lua/?.lua;;";`

I'v solved it by add it to the path's last: 

`    lua_package_path "/etc/nginx/library/?.lua;;/usr/local/share/lua/5.1/?.lua;;/usr/local/lib/lua/?.lua;;";
`

**Comment by NoWait126** [comment]
Is there a way to custom the path, I have install openresty in `/home/mydir/usr/local/` not `/usr/local`, This directory`/home/mydir/usr/local/usr/local/openresty/lualib/resty/core`  exists correctly . And I add `lua_package_path "/home/mydir/usr/local/share/lua/5.1?.lua;;/home/mydir/usr/local/lib/lua/?.lua;;";` , but it still does not work, it is the same error.
