### ISSUE TITLE
Is nginx 1.15.x now officially supported?

### ISSUE THREAD

**Issue by Hsn723** [openresty/lua-nginx-module#1534]
I've noticed that OpenResty 1.15.8.1 has been formally released and based on the nginx 1.15.8, however the nginx compatibility matrix on the lua-nginx-module Readme (https://github.com/openresty/lua-nginx-module#nginx-compatibility) doesn't list 1.15.x support. Is it simply because the documentation hasn't yet been updated?

**Comment by agentzh** [comment]
@Hsn723 Yeah. Just updated the README doc. Thanks.
