### ISSUE TITLE
ssl_session_fetch|store issues with TLSv1.3

### ISSUE THREAD

**Issue by yongjianchn** [openresty/lua-nginx-module#1539]
@thibaultcha @spacewander  

with https://github.com/openresty/lua-nginx-module/pull/1503, I failed to reuse tls session with ssl_session_fetch\store_by_lua on TLSv1.3.

I reviewed the code, and I think SSL_client_hello_get0_session_id() which called in ngx_http_lua_ssl_client_hello_handler() will get the wrong session id on TLSv1.3, while the real session id is stored in PSK and ngx_http_lua_ssl_sess_fetch_handler() can get.

**Comment by yongjianchn** [comment]
-- ssl_session_fetch_by_lua_file

local ssl_sess = require "ngx.ssl.session"

local local_dict = ngx.shared.ssl_session

local function ssl_session_fetch()
    local sess_id, err = ssl_sess.get_session_id()
    if not sess_id then 
        ngx.log(ngx.ERR, "failed to get session ID: ", err) 
        return
    end  

    local sess,err = local_dict:get(sess_id)
    if sess then 
        ngx.log(ngx.ERR, sess_id, ", get sess from local dict")
    else 
        ngx.log(ngx.ERR, sess_id, ", can not get sess from local dict")
        return
    end  

    local ok, err = ssl_sess.set_serialized_session(sess)
    if not ok then 
        ngx.log(ngx.ERR, "failed to set SSL session: ", err) 
        return
    end  
end

ssl_session_fetch()
-- ssl_session_store_by_lua_file
local ssl_sess = require "ngx.ssl.session"

local local_dict = ngx.shared.ssl_session

local function ssl_session_store()
    local sess_id, err = ssl_sess.get_session_id()
    if not sess_id then 
        ngx.log(ngx.ERR, "failed to get session ID: ", err) 
        return
    end  

    local sess, err = ssl_sess.get_serialized_session()
    if not sess then         ngx.log(ngx.ERR, "failed to get SSL session: ", err) 
        return
    end  

    local ok, err = local_dict:set(sess_id, sess)
    if not ok then 
        ngx.log(ngx.ERR, sess_id, ", failed to store sess into local dict")
    else 
        ngx.log(ngx.ERR, sess_id, ", store sess into local dict")
    end  
end

ssl_session_store()

**Comment by spacewander** [comment]
Session ID is obsolete in TLS 1.3.

To recover the session from PSK, maybe we need to use `SSL_CTX_set_psk_find_session_callback` and its friends. We can pretend the session ID still works in TLS 1.3, or providing a new set of API.

@yongjianchn 
I will be too busy to work on this in the upcoming weeks. Would you like to dive into the details, and provide us a report (and a pull request or bugfix, if possible)?

BTW, I suggest you to use `openssl s_client` or other command line tools to reproduce the issue. There is a test case which uses the `openssl s_client`: https://github.com/openresty/lua-resty-core/blob/master/t/ssl.t#L2227. Firefox is too huge.

**Comment by yongjianchn** [comment]
> Session ID is obsolete in TLS 1.3.
> 
> To recover the session from PSK, maybe we need to use `SSL_CTX_set_psk_find_session_callback` and its friends. We can pretend the session ID still works in TLS 1.3, or providing a new set of API.

I think we should pretend the session ID still works(and it is real, but moved to PSK), thus users don't need to change their Lua code. The key point is we should use set_get_cb instead of client_hello_cb. client_hello_cb is good, no patches for OpenSSL is needed, but it's not designed for session resumption.
> 
> @yongjianchn
> I will be too busy to work on this in the upcoming weeks. Would you like to dive into the details, and provide us a report (and a pull request or bugfix, if possible)?

I like to, but I am busy these days. I may get some free time to work on this, but not for sure. And I think TLSv1.3 clients will support session ticket in PSK, so session ID is not that important. This is not an emergency.
> 
> BTW, I suggest you to use `openssl s_client` or other command line tools to reproduce the issue. There is a test case which uses the `openssl s_client`: https://github.com/openresty/lua-resty-core/blob/master/t/ssl.t#L2227. Firefox is too huge.

Thanks for your advice, I will try.

**Comment by yongjianchn** [comment]
@spacewander Another reason why we should not use client_hello_cb().
As the ssl_session_fetch_by_lua* document says: 
> SSL session resumptions based on TLS session tickets would happen automatically without going through this hook (nor the ssl_session_store_by_lua* hook). 

ssl_session_fetch_by_lua* should not be called when session ticket is used.  But with client_hello_cb(), ssl_session_fetch_by_lua* will be called by every connection no matter it can be resumed by ticket or not. This is breaking the original design.

**Comment by spacewander** [comment]
@yongjianchn 

> The key point is we should use set_get_cb instead of client_hello_cb.

Will the `session_get_cb` be called in TLS 1.3? Could you provide a test case?

**Comment by yongjianchn** [comment]
> @yongjianchn
> 
> > The key point is we should use set_get_cb instead of client_hello_cb.
> 
> Will the `session_get_cb` be called in TLS 1.3? Could you provide a test case?

Yes, `session_get_cb` will be called in TLS 1.3. See my test in the above conversation. Just use firefox, the second connection will trigger it. tls_parse_ctos_psk() -> tls_get_stateful_ticket() -> tls_get_stateful_ticket() -> lookup_sess_in_cache() -> get_session_cb()

**Comment by spacewander** [comment]
Getting rid of OpenSSL patch is tempting. Maybe we could provide a separate patch for TLS 1.3 (with PSK, without session ticket).

@yongjianchn @thibaultcha 
I just submitted a patch to fix the broken behavior of `ssl_session_fetch_by_lua*`: https://github.com/openresty/lua-nginx-module/pull/1540.
This patch simply skips the phase if thing doesn't look well.
To fully support TLS 1.3 with PSK, further work is in need.

**Comment by spacewander** [comment]
Or we could parse the PSK extension by ourselves.
Need to take care of PSK key mode and other stuff. But we still need to be care for each version of OpenSSL if we decide to maintain a patch. The change of spec is rarer than the change of library code.

**Comment by spacewander** [comment]
After the discussion in https://github.com/openresty/lua-nginx-module/pull/1540#discussion_r292860256, now we are sure that checking the PSK only is not enough. This way can not detect TLS 1.3 ClientHello in full handshake.

One of the idea, suggested by @crasyangel, is checking `TLSEXT_TYPE_supported_versions` instead, and also take care of the protocols supported by the server.

**Comment by yongjianchn** [comment]
@halfcrazy @spacewander

**Comment by thibaultcha** [comment]
Closing this now that d3dbc0c8102a9978d649c99e3261d93aac547378 is merged.
