### ISSUE TITLE
How to use both ngx.print() and error_page?

### ISSUE THREAD

**Issue by eeeeeunjung** [openresty/lua-nginx-module#1541]
i am using this configuration:
proxy_intercept_errors on;
error_page 404 /errors/404.html;

but in the location 
I configured content_by_lua_file '/nginx_content_phase.luac';
becauser nginx_content_phase.luac contains the ngx.print() directive，error_page doesn't work,

> GET /test/123 HTTP/1.1
> User-Agent: curl/7.37.0
> Host:10.10.15.15:443
> Accept: */*
>
> HTTP/1.1 404 Not Found
> Server product only is not blacklisted
> Server: product only
> Date: Tue, 11 Jun 2019 01:11:25 GMT
> Content-Type: application/octet-stream
> Transfer-Encoding: chunked
> Connection: keep-alive

it cann't redirect to 404.html,how can i use both ngx.print() and error_page?

**Comment by alwaysused** [comment]
I think ngx.print() is not relative to  the output of server but only does  some logging.Using error pages if or not determined by what you do in content_by_lua,such as using coroutines.

**Comment by thibaultcha** [comment]
If you wish to run Lua code in an error handler location, then don't make `error_page` point to a static HTML page. Point it to another location block (e.g. `error_page ... /my_error_handler`) and implement `*_by_lua*` directives in this new location block, e.g.:

```
location / {
    proxy_intercept_errors on;
    proxy_pass ...;
}

location = /my_error_handler {
    internal;

    content_by_lua_block {
        ngx.say("my error response")
    }
}
```

My advice is to use an internal, non-named location block. Named location blocks don't play well with `error_page` when NGINX didn't parse the URI yet (e.g. when NGINX produces HTTP 414). Unless you define multiple error location blocks for various error scenarios.

Best of luck,
