### ISSUE TITLE
nginx1.16 not run with lua-nginx-module-v0.10.11.tar.gz with luajit2-2.1-20190626?

### ISSUE THREAD

**Issue by ygm521** [openresty/lua-nginx-module#1550]
tmpfs on /data/nginx_proxy_temp type tmpfs (rw,nosuid,nodev)
tmpfs on /data/nginx_client_body_tmp type tmpfs (rw,nosuid,nodev)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '../lua-resty-core/lib/resty/core.lua'
	no file '../lua-resty-lrucache/lib/resty/core.lua'
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by agentzh** [comment]
@ygm521 Just follow the suggestions in the error messages. We won't repeat them here...

**Comment by lystormenvoy** [comment]
同样有这个问题。
error里只是说加载不了这个模块。但我只是编译了lua模块，没启用，为什么会报这个error呢？为什么要求我需要有这些文件呢？报了这个error，nginx似乎仍可以正常运行。
Just follow the suggestions in the error messages
提示里只是说让下载OpenResty，说好的是nginx模块呢？我要用nginx编译lua模块而已啊，为什么要下载OpenResty？

**Comment by agentzh** [comment]
@lystormenvoy Please don't use Chinese here. This place is English only.

The error message did not say you MUST use OpenResty at all. Read it more carefully.

**Comment by cosoc** [comment]
@agentzh  干嘛？英语了不起啊？我说中文咋的，你看不懂不知道用翻译？

**Comment by dlannan-fmad** [comment]
There are a few people having problems with this. Hopefully this helps: https://github.com/openresty/lua-nginx-module/issues/1829
