### ISSUE TITLE
ngx.escape_uri does not have effect on character `|`.

### ISSUE THREAD

**Issue by vampire007** [openresty/lua-nginx-module#1551]
hi, ngx.escape_uri("hey|andy") does not return expected string `hey%7Candy` but get `hey|andy`. Character `|` is not be escaped.. But when I try it in https://www.urlencoder.org/, it shows below.

![image](https://user-images.githubusercontent.com/11432644/60595329-5de0fa00-9dd9-11e9-87ae-3912f4d28920.png)

**Comment by membphis** [comment]
what is your openresty version?

it seems fine at my side:

```shell
$ resty -e 'print(ngx.escape_uri("hey|andy"))'
hey%7Candy

$ openresty -V
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by vampire007** [comment]
thanks.. it seems that my version openresty-1.11.2.4 is too low..

**Comment by vampire007** [comment]
my version is too low..
