### ISSUE TITLE
unknown directive "content_by_lua_block" in /root/work/conf/nginx.conf:11

### ISSUE THREAD

**Issue by samialmorshedi** [openresty/lua-nginx-module#1554]
I followed installation instruction on http://openresty.org/en/getting-started.html but when I want to run the command:
`nginx -p `pwd`/ -c conf/nginx.conf
`
I got this error:
`nginx: [emerg] unknown directive "content_by_lua_block" in /root/work/conf/nginx.conf:11`

I tried also to install  **lua-nginx-module** but on step **./configuration** I got this error:
`./configure: error: C compiler cc is not found`
But the directory exists! I`m exusted and tierd. I still could not install Openresty and see **"Hello world"** on my **http://myip**  

Please help me on this.

**Comment by membphis** [comment]
what is the version of your openresty? you can get it by command: `openresty -V`

if you still have problem, pls submit your fully nginx config file.

**Comment by agentzh** [comment]
@samialmorshedi Seems like you're not invoking openresty's nignx. You may have multiple nginx executables in your system. Try invoking openresty's nginx binary explicitly via its full path instead of relying on changing PATH environment variable values.

**Comment by thibaultcha** [comment]
Considering this answered and closing the topic.
