### ISSUE TITLE
How to mute `_G write guard` warnings during test?

### ISSUE THREAD

**Issue by ktalebian** [openresty/lua-nginx-module#1558]
In our test setup, we use `_G` to declare global variables, and this results in a lot of

```
2019/07/12 12:22:31 [warn] 93624#17052095: *2 [lua] _G write guard:12: __newindex(): writing a global lua variable ('resource') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
```
like errors. How can I mute these errors?

**Comment by agentzh** [comment]
@ktalebian Just use `local` in your test case and avoid the use of globals.

**Comment by ElvinEfendi** [comment]
For https://github.com/kubernetes/ingress-nginx we are using busted (which uses global variable when loading) to run tests and also make use of global `_TEST` variable to expose some functions for testing. To avoid this warning before starting test run I ended up monkeypatching metatable of _G table just like lua-nginx-module does. You can find the code in https://github.com/kubernetes/ingress-nginx/pull/4313/files#diff-3d8362de2ff5e9c575f8d65dc6de5effR1.

**Comment by doujiang24** [comment]
@ElvinEfendi 
that's not the recommended way, it's better to move those public functions to a Lua module.

**Comment by ElvinEfendi** [comment]
@doujiang24 while I agree that conditionally exposing some functions publicly during test is not great, it sometimes helps to reduce complexity when writing unit tests.

But yeah, unless there's a strong reason one should not use that (anti)pattern.

**Comment by ktalebian** [comment]
This is not just from my use of plugins. 
```
2019/07/15 09:50:50 [warn] 96697#18004569: *2 [lua] _G write guard:12: writing a global lua variable ('lfs') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
```
This is coming from the penlight library, from https://github.com/stevedonovan/Penlight/blob/master/lua/pl/path.lua#L22 line

**Comment by ktalebian** [comment]
Okay I fixed all my local variables, but I'm still getting

```
2019/07/15 10:08:43 [warn] 1657#18041694: *2 [lua] _G write guard:12: writing a global lua variable ('lfs') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
```
This comes form the line

```
local lfs = require 'lfs`
```

That line is throwing that error, and I don't know what to do about this now.

**Comment by agentzh** [comment]
@ktalebian It is the `lfs` module itself writing to global variables:

https://github.com/stevedonovan/Penlight/blob/master/lua/pl/path.lua#L22

Well-formed Lua modules should never write to global variables themselves since they pollute the global name space (not just for the context of OpenResty, but for Lua applications in general). For this reason, the `module()` function should not be used either since it also writes a global variable.

It is that `lfs` Lua module which needs fixing in this case.

**Comment by agentzh** [comment]
@ElvinEfendi Use of Lua globals can lead to bugs that are very hard to debug. Sometimes those globals are just typos in variable names.

**Comment by agentzh** [comment]
Muting global variable warnings in testing would defeat your purposes of testing since you may get the warnings (and maybe also real bugs) in production anyway.

**Comment by ElvinEfendi** [comment]
> @ElvinEfendi Use of Lua globals can lead to bugs that are very hard to debug. Sometimes those globals are just typos in variable names.

Yep definitely! I'm not disabling this warning altogether - as soon as busted is loaded I'm restoring the metatable back (with slight modification to whitelist `_TEST` global variable in timer phase where resty-cli runs code).

Agreed that root cause need to be fixed in the `lfs` module.

**Comment by ktalebian** [comment]
@agentzh I agree generally with the usage of globals, but all of these "globals" that I am getting warnings are, are aux functions made to be used _during_ test only, to simplify bootstrapping the test environment. They are not globals during runtime. 

But I have fixed all my global variables, the `lfs` is the last thing remaining.

**Comment by agentzh** [comment]
@ktalebian You should contact the maintainers of that `lfs` Lua module to fix that global. It's not maintained by us anyway.

**Comment by ktalebian** [comment]
@agentzh Is this line the issue? https://github.com/keplerproject/luafilesystem/blob/master/src/lfs.c#L944

**Comment by ktalebian** [comment]
Also, until they fix it, `lfs` is used in almost all the libraries I am using (required by `penlight`, required by `busted`). Is there any way to mute this warning so my logs can be more manageable?

**Comment by Crack** [comment]
You can do `rawset(_G, 'lfs', false)` before including `busted`.

**Comment by ktalebian** [comment]
@Crack thanks!

**Comment by ktalebian** [comment]
Going to close this issue now.
