### ISSUE TITLE
a problem with lua ffi in openresty

### ISSUE THREAD

**Issue by yukityan** [openresty/lua-nginx-module#1562]
## test case
```lua
-- filename: gateway/test.lua
local ffi = require "ffi"

ffi.cdef [=[
    typedef struct _TrigxNode {
        int val;
        struct _TrigxNode *char_nodes[64];
        struct _TrigxNode *rgx_next;
        int rgx_raw_len;
        void *re;
        char *rgx;
    } TrigxNode;
    TrigxNode *create_trigx_node();
    void trigx_insert(TrigxNode *root, const char *word, int len_word, int val);
    int trigx_search(TrigxNode *root, const char *word, int len_word);
    void trigx_free(TrigxNode *root);
   ]=];

local C = ffi.load("trigx_tree")

local node = C.create_trigx_node()
C.trigx_insert(node, '/menu/', 6, 10)
local result = C.trigx_search(node, '/menu/', 6)
if ngx ~= nil then
    --  test in openresty
    ngx.say("result: " .. result)
else
    -- test in luajit
    print("result: " .. result)
end
return
```
```nginx
# filename: conf.d/nginx.conf
http {

    init_worker_by_lua_block {
        local uuid = require 'resty.jit-uuid'
        uuid.seed()
        local verbose = false
        if verbose then
            local dump = require "jit.dump"
            dump.on(nil, "./jit.log")
        else
            local v = require "jit.v"
            v.on("./jit.log")
        end
        require "resty.core"
    }

    server {
        listen 9090;

        location / {
            content_by_lua_file "gateway/test.lua";
        }

        location /login {
            default_type 'application/json';
            content_by_lua_file 'gateway/login.lua';
        }

        location /wechat-callback {
            content_by_lua_file 'gateway/wechat_identify.lua';
        }

    }
}
```
>> when i call the ffi function by shell, **luajit -i gateway/test.lua**,I can see the right result are printed

![image](https://user-images.githubusercontent.com/30937220/61273379-eef1a100-a7db-11e9-91ae-2ded27727b88.png)
>> but when i try to call test.lua in nginx worker, **curl 'localhost:9090/abc'**,error occured

![image](https://user-images.githubusercontent.com/30937220/61273602-7f2fe600-a7dc-11e9-88bf-d763d5d7a383.png)

I have no idea about how this problem occured

**Comment by yukityan** [comment]
I use calloc rather malloc to allocate memory then problem solved

**Comment by doujiang24** [comment]
you should not ffi cdef the same thing more than one time, you can move
them into a Lua module, like:
https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.lua

then you can call in like:
content_by_lua_block {
    require "xx".go()
}

yukityan <notifications@github.com> 于2019年7月16日周二 下午3:17写道：

**Comment by yukityan** [comment]
I know that ffi cdef shoud only execute once,But in my test case, if my my
ffi extension work correctly, when the first request arrived, It should
give me the right answer, and when the second request arrived, It should
throw cdef dumplicated error.

doujiang <notifications@github.com> 于2019年7月20日周六 上午11:19写道：
