### ISSUE TITLE
README need update

### ISSUE THREAD

**Issue by zengjinji** [openresty/lua-nginx-module#1565]
patch http://mailman.nginx.org/pipermail/nginx-devel/2016-January/007748.html need update to support tlsv1.3 early data

in https://github.com/openresty/lua-nginx-module README.markdown
```
2532 This directive currently requires the following NGINX core patch to work correctly:
2533 
2534 <http://mailman.nginx.org/pipermail/nginx-devel/2016-January/007748.html>
2535 
2536 The bundled version of the NGINX core in OpenResty 1.9.7.2 (or above) already has this
2537 patch applied.

```

related:
https://github.com/openresty/lua-nginx-module/commit/467f0134dbf53737a0cf26de7ccb2c35bd490d85
https://github.com/openresty/openresty/commit/34918a30c3fd19fe0ae9fabbbea442fef32e1118

**Comment by thibaultcha** [comment]
Updated in e42f9b5f6520d7d5f51b6742134377f66bcdf841, thank you for letting us know.
