### ISSUE TITLE
The apisix failed to start

### ISSUE THREAD

**Issue by dayongi** [openresty/lua-nginx-module#1571]
I am currently using openresty1.15.8.1, The apisix based on that. But i'm sure, the apisix failed to start when i already installed it finished. The output is empty when i run the command（like 'apisix start'）,however i don't see the processes are running for the apisix. very disappointment for that.  i follow the steps of  github documents to install it.  just for the etcd i don't follow the steps  of github document when i install the etcd. I use  the  yum  commands to install it.
I feel the apisix failed to start because of the system. so i cut out some image of errors and system. I hope you can help me find errors for the apisix failed to start. thanks a lot.

**For the cpu:**
![image](https://user-images.githubusercontent.com/41787764/62261089-b80bc400-b446-11e9-8c89-8fcc4b7b8f80.png)

**The output of  command  `openresty -V`:**
![image](https://user-images.githubusercontent.com/41787764/62261204-1638a700-b447-11e9-885a-281fe2cd74e8.png)

**Comment by thibaultcha** [comment]
Please contact the authors of the apisix project, which we are not responsible for maintaining. Thank you.
