### ISSUE TITLE
Set headers in body_filter_by_lua* #825

### ISSUE THREAD

**Issue by ccjinghang** [openresty/lua-nginx-module#1586]
Set headers in body_filter_by_lua* #825.
Is there a solution to this problem?

**Comment by ccjinghang** [comment]
@thibaultcha

**Comment by thibaultcha** [comment]
@ccjinghang This is by design, as explained by agentzh in #825. I think the answer there is pretty clear already. You cannot set response headers once they have already been sent to the client.
