### ISSUE TITLE
ngx.location.capture with a different port number.

### ISSUE THREAD

**Issue by axot** [openresty/lua-nginx-module#1588]
Hi, I am looking for how to send a http request to localhost with a different port number, does ngx.location.capture support this?

**Comment by tokers** [comment]
@axot 

No. This is decided by the design of `ngx.location.capture`, it just spawning a subrequest without any real traffic. You can use HTTP library like lua-resty-http to achieve your purpose.

**Comment by axot** [comment]
Thanks for the advice!
