### ISSUE TITLE
 ngx.re.gsub failed

### ISSUE THREAD

**Issue by deetchtoys** [openresty/lua-nginx-module#1594]
when i use ngx.re.gsub to deal with a large string:

`
local newstr, n, err = ngx.re.gsub(str, "^(\\s*)(.*?)(\\s*)$", "$2", "jo")
`

 it will occur an error: 

`
ngx.re.gsub failed, err:pcre_exec() failed: -8
`

**Comment by liulei18** [comment]
* RTFM. https://github.com/openresty/lua-nginx-module#ngxregsub , there is a saying:`This method requires the PCRE library enabled in Nginx`

**Comment by dickietoys** [comment]
> * RTFM. https://github.com/openresty/lua-nginx-module#ngxregsub , there is a saying:`This method requires the PCRE library enabled in Nginx`

Hello;

This works when the str's length is short, but when the str's length up to 8M, it go failed.

Best regards.

**Comment by tyiss** [comment]
Note that -8 means that backtracklimit is reached.
taken from [https://pcre.org/pcre.txt](https://pcre.org/pcre.txt)
>         PCRE_ERROR_MATCHLIMIT     (-8)
       The backtracking limit, as specified by  the  match_limit  field  in  a
       pcre_extra  structure  (or  defaulted) was reached. See the description
       above.
