### ISSUE TITLE
Make a http request to an external service?

### ISSUE THREAD

**Issue by daurnimator** [openresty/lua-nginx-module#160]
I feel like I might be overlooking something; but is there an api to talk to an external http server?

location.capture is only for internal resources: I tried using it in conjunction with proxy; but that only allows for a single specified external domain at a time.

I could write one with the cosocket api; but I feel like there's probably something around that reuses connections, and does compression, caching, etc where possible...

**Comment by sugelalin** [comment]
Hello !   

I Use The Frist One use ngx.location.capture + ngx_proxy , But I got An Error.

The Code Is blow

`
location = "/first" {
        default_type 'application/json';
        content_by_lua_block {
                local res = ngx.location.capture(
                '/second',
                { method = ngx.HTTP_POST, always_forward_body = false })
        };
    }
    location = "/second" {
        internal;
        proxy_pass http://otherserver-upstream;
    }
`
And The Error Log is 
`
[error] 29212#29212: *1151961745 open() "/openresty/html/second" failed (2: No such file or directory),xxx
`
How do i fix it
