### ISSUE TITLE
ngx.location.capture().header case inconsistency with ngx.header.HEADER and ngx.req.get_headers()

### ISSUE THREAD

**Issue by pszemus** [openresty/lua-nginx-module#1612]
I've noticed a case inconsistency between headers returned by `ngx.location.capture().header[]` and the rest APIs/functions for returning headers.

`ngx.location.capture().header[]` returns header as it was sent by the server, eg:
```
local res = ngx.location.capture('/')
ngx.log(ngx.ERR, res.header['Content-Type']); -- returns 'text/html'
ngx.log(ngx.ERR, res.header['content-type']); -- returns nil
```
At the same time the rest APIs/functions return headers regardless its case:
* `ngx.header.HEADER`
> The header names are matched case-insensitively.
* `ngx.req.get_headers()`
> Also, by default, an __index metamethod is added to the resulting Lua table and will normalize the keys to a pure lowercase form
* `$http_name`
> arbitrary request header field; the last part of a variable name is the field name converted to lower case

Eg:
```
ngx.log(ngx.ERR, ngx.resp.get_headers()['Content-Type']); -- returns ' text/html'
ngx.log(ngx.ERR, ngx.resp.get_headers()['content-type']); -- returns ' text/html'
```

I think `ngx.location.capture().header` should be altered to conform with the rest functions.

---
The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version,
and your operating system version.
```
nginx version: openresty/1.13.6.2
built by gcc 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
built with OpenSSL 1.1.0h  27 Mar 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-dtrace-probes --with-stream --with-stream_ssl_module --with-http_ssl_module
```

**Comment by liulei18** [comment]
* `ngx.location.capture` issues a synchronous but still non-blocking Nginx Subrequest using uri. Also note that subrequests just mimic the HTTP interface but there is no extra HTTP/TCP traffic nor IPC involved. Everything works internally, efficiently, on the C level.
* `ngx.req.get_headers`  since the 0.6.9 release, all the header names in the Lua table returned are converted to the pure lower-case form by default, unless the raw argument is set to true (default to false).

**Comment by pszemus** [comment]
Thank you @liulei18 
I know how `ngx.location.capture` works and I make use of it quite often.
This issue is about how `headers` table looks like in comparison to those returned by:
* `ngx.req.get_headers`
* `ngx.resp.get_headers`
* `ngx.header`
* `$http_` variable
Where one can not worry about header caseness while accessing them.

**Comment by rushi47** [comment]
Facing same issue and wondering if its ideal solution exists.
