### ISSUE TITLE
 unknown directive "content_by_lua_block"  ,USING openresty/1.7.10.1

### ISSUE THREAD

**Issue by tylitianrui** [openresty/lua-nginx-module#1614]
location /lua {
        content_by_lua_block {
        ngx.say("content_by_lua_content");
        }
        }

nginx: [emerg] unknown directive "content_by_lua_block" in /opt/openresty/nginx/conf/nginx.conf:59

I  USE  openresty/1.7.10.1 ,not version 0.9

**Comment by membphis** [comment]
Please use the latest openresty version and make a try again.

**Comment by tylitianrui** [comment]
thx
