### ISSUE TITLE
why ngx.var.schema is null in rewrite_by_lua

### ISSUE THREAD

**Issue by louishot** [openresty/lua-nginx-module#1629]
ngx.say(ngx.var.schema)
ngx.say(ngx.var.remote_addr)

output
Server: openresty
Date: Tue, 10 Dec 2019 13:52:25 GMT
Content-Type: text/css
Transfer-Encoding: chunked
Connection: keep-alive

nil
1.0.40.239

**Comment by tokers** [comment]
Indeed it's `scheme`, not `schema`.

**Comment by louishot** [comment]
> schema



> Indeed it's `scheme`, not `schema`.

perfect. I'm a little sloppy
