### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by Anti067** [openresty/lua-nginx-module#1646]
hello, im use nginx 1.17.8 with ubuntu xenial and after put the script i take a error...

nginx: [emerg] unknown directive "access_by_lua_file" in /etc/nginx/conf.d/default.conf:11

Can you give me tutorial for compilation to ubuntu xenial and nginx 1.17.8?

**Comment by doujiang24** [comment]
you can simply try the rc0 tar bar.
https://openresty.org/download/openresty-1.17.8.1rc0.tar.gz

the original nginx does not have the `access_by_lua_file` directive.

**Comment by thibaultcha** [comment]
Please make sure that the `nginx` executable you are invoking is OpenResty's, and not stock NGINX. You can easily find out with `nginx -v`:

```
$ nginx -v
nginx version: openresty/1.17.8.1rc1
```
