### ISSUE TITLE
Problem set NGINX variable

### ISSUE THREAD

**Issue by khaiphan9x** [openresty/lua-nginx-module#1650]
Can I do the same?
```
ngx.var = {foo='bar', bar='foo'}
```
Instead of
```
ngx.var.foo = 'bar'
ngx.var.bar = 'foo'
```

**Comment by thibaultcha** [comment]
Hi,

No, you cannot do this since `ngx.var` uses a special metatable (see https://www.lua.org/pil/13.html) and thus your first example would override it and render `ngx.var` useless.
