### ISSUE TITLE
nginx: unknown directive "lua_package_path" in /usr/local/nginx/conf/nginx.conf

### ISSUE THREAD

**Issue by HanPengzhou** [openresty/lua-nginx-module#1662]
System: OS,
nginx:1.16.1,
lua:5.1,
luajit:2.1,
lua-ngx:v0.10.16rc4
`nginx version: nginx/1.16.1
built by clang 11.0.0 (clang-1100.0.33.17)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --sbin-path=/usr/local/nginx/bin/nginx --conf-path=conf/nginx.conf --pid-path=logs/nginx.pid --http-log-path=logs/access.log --error-log-path=logs/error.log --http-client-body-temp-path=temp/client_body_temp --http-proxy-temp-path=temp/proxy_temp --http-fastcgi-temp-path=temp/fastcgi_temp --http-scgi-temp-path=temp/scgi_temp --http-uwsgi-temp-path=temp/uwsgi_temp --with-cc-opt=-DFD_SETSIZE=32768 --with-pcre=objs/lib/pcre-8.38 --with-zlib=objs/lib/zlib-1.2.8 --with-openssl=objs/lib/openssl-OpenSSL_1_1_1d --with-select_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_stub_status_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_slice_module --with-mail --with-stream --with-http_ssl_module --with-mail_ssl_module --with-stream_ssl_module --with-http_v2_module --with-ipv6 --add-module=./lib/ngx_devel_kit --add-module=./lib/echo-nginx-module --add-module=./lib/set-misc-nginx-module --add-module=./lib/ngx_postgres --add-module=./lib/form-input-nginx-module --add-module=./lib/encrypted-session-nginx-module --add-module=./lib/lua-nginx-module --add-module=./lib/lua-upstream-nginx-module --add-module=./lib/headers-more-nginx-module --add-module=./lib/array-var-nginx-module --add-module=./lib/redis2-nginx-module --with-ld-opt=-Wl,-rpath,/usr/local/lib`

**Comment by rainingmaster** [comment]
You build the openresty by your self?  Maybe use the official pre-built is better?

**Comment by HanPengzhou** [comment]
> You build the openresty by your self? Maybe use the official pre-built is better?

You are right.Thanks.
