### ISSUE TITLE
nginx compile error when libluajit-5.1 is linked dynamically

### ISSUE THREAD

**Issue by fancy-rabbit** [openresty/lua-nginx-module#1669]
nginx:1.17.8 luajit: openresty/luajit2 20200102
compiling with the master branch of lua-nginx-module results in:

> unsupported LuaJIT build; ngx_http_lua_module requires LuaJIT with FFI enabled.

it will always look for libluajit-5.1.a for this check. I made a PR #1668 to fix this but wonder if it is appropriate.
at other parts of the file, the dynamically linked .so is treated correctly.

**Comment by fancy-rabbit** [comment]
same in the stream-lua-nginx-module :(

**Comment by thibaultcha** [comment]
There was a specific reason for it to be statistically linked but I forgot what it was - this was pushed quite some time ago... I will try to remember. I hear @agentzh refactored the test already anyway, which is not pushed yet.

**Comment by thibaultcha** [comment]
This should now be fixed in master. Thanks!
