### ISSUE TITLE
Which version of PCRE do I need? I can't use ngx.re.match after compiling

### ISSUE THREAD

**Issue by sunnykandy** [openresty/lua-nginx-module#1671]
Which version of PCRE do I need? I can't use ngx.re.match after compiling

**Comment by rainingmaster** [comment]
I think this issue is related to #1672 .

**Comment by thibaultcha** [comment]
Hi, 

There is a known issue with 1.15.8.x builds statically linked against libpcre. Try this workaround for now until 1.17.8.x gets a mainstream release: https://github.com/openresty/lua-resty-core/issues/258#issuecomment-524006713

Thanks
