### ISSUE TITLE
OpenResty was compiled without PCRE support

### ISSUE THREAD

**Issue by sunnykandy** [openresty/lua-nginx-module#1672]
2020/03/19 14:33:05 [error] 10356#19508: *1 lua entry thread aborted: runtime error: D:\nginxProject\src\build\build\bin\lua\resty\http.lua:17: no support for 'ngx.re.match': OpenResty was compiled without PCRE support
stack traceback:
coroutine 0:
	[C]: in function 'require'
	./src/utils/static_concat_req.lua:2: in main chunk, client: 192.168.10.18, server: www.mhool.com, request: "GET /apps HTTP/2.0", host: "www.mhool.com"

**Comment by rainingmaster** [comment]
I think it is obvious, this error from [the regex module](https://github.com/openresty/lua-resty-core/blob/master/lib/resty/core/regex.lua#L61), and it check [this function](https://github.com/openresty/lua-resty-core/blob/master/lib/resty/core/regex.lua#L52) exists or not.

Maybe you can check have you install the  PCRE in your machine which built the openresty, and you can use `nginx -V` to see if the PCRE lib path is included.

By the way, I think this should not be an issue? Maybe we can use [the official forum to discuss it](https://forum.openresty.us/), thanks!

**Comment by thibaultcha** [comment]
Hi, 

There is a known issue with 1.15.8.x builds statically linked against libpcre. Try this workaround for now until 1.17.8.x gets a mainstream release: https://github.com/openresty/lua-resty-core/issues/258#issuecomment-524006713

Thanks
