### ISSUE TITLE
closing connection during ssl cert by lua

### ISSUE THREAD

**Issue by splitice** [openresty/lua-nginx-module#1685]
I'm currently investigating a possible bug.

Hypothesis: Connections closed during ssl_cert_by_lua may leak memory

Why: In certain situations we are needing to close the connection before the request phase. As we are using ssl_cert_by_lua this seemed like a good place

Could anyone provide some insight into this. Is `ngx.exit(444)` safe to use in this phase? Should I re-consider this? Should I use a different phase?

**Comment by doujiang24** [comment]
`ngx.exit(444)` should be safe to use in this phase, otherwise, it should be a bug.
maybe you can help to provide a minimal example to reproduce the memory leak?

**Comment by splitice** [comment]
@doujiang24 that's the confirmation I need thanks. I'm still investigating this.

**Comment by splitice** [comment]
We ended up moving logic to the hello phase and haven't seen the issue since. Given this and that this was an issue on a now ancient version I'm happy for this to be closed.
