### ISSUE TITLE
Posslible issue in ngx_http_lua_socket_udp.c:1487 and -Werror=address with nginx-fstack

### ISSUE THREAD

**Issue by amdei** [openresty/lua-nginx-module#1691]
```
Debian 10.3 x64
# uname -a
Linux fire2-deb 4.19.16 #2 SMP Thu Oct 31 16:26:17 MSK 2019 x86_64 GNU/Linux
nginx-nx 1.16.1 (nginx with f-stack FreeBSD network stack module: https://github.com/F-Stack/f-stack )
ngx_devel_kit v0.3.1
lua-nginx-module v0.10.15 tag
OpenResty not used.
```

NGINX configuration script:
```
export LUAJIT_INC=/usr/local/lib/luajit/include/luajit-2.1/
export LUAJIT_LIB=/usr/local/lib/luajit/lib/

./configure \
  --with-cc-opt="-fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2" \
  --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' \
  --prefix=/opt/nginx \
  --conf-path=/etc/opt/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --http-log-path=/var/log/nginx/access.log \
  --lock-path=/var/run/lock/nginx.lock \
  --pid-path=/var/run/nginx.pid \
  --with-pcre=../ngx-libs/pcre-8.44 --with-pcre-jit \
  --with-zlib=../ngx-libs/zlib-1.2.11 \
  --with-debug \
  --with-stream \
  --with-stream_ssl_module \
  --with-http_ssl_module \
  --with-http_v2_module \
  --with-ff_module \
  --with-openssl=../ngx-libs/openssl-1.1.1f/ \
  --with-openssl-opt="no-gost no-comp no-dtls" \
  --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib/" \
  --add-module=../3rd-party-ngx-modules/ngx_devel_kit \
  --add-module=../3rd-party-ngx-modules/lua-nginx-module
```

When compiling after configuration above I got:
```
        ../3rd-party-ngx-modules/lua-nginx-module/src/ngx_http_lua_socket_udp.c
../3rd-party-ngx-modules/lua-nginx-module/src/ngx_http_lua_socket_udp.c: In function ‘ngx_http_lua_udp_connect’:
../3rd-party-ngx-modules/lua-nginx-module/src/ngx_http_lua_socket_udp.c:1487:9: error: the address of ‘ngx_add_event’ will always evaluate as ‘true’ [-Werror=address]
     if (ngx_add_event) {
         ^~~~~~~~~~~~~
```

Expected result: code being compiled.

Reason:
With NGX_HAVE_FSTACK defined, ngx_add_event being declared as function instead of macro:
#define ngx_add_event ngx_event_actions.add

Possible solution (compilable, but not tested):
```
-    if (ngx_add_event) {
+    if (ngx_event_actions.add) {
```

**Comment by amdei** [comment]
Issue in F-Stack: https://github.com/F-Stack/f-stack/issues/503

**Comment by doujiang24** [comment]
@rainingmaster can you help to take a look at this issue?

**Comment by rainingmaster** [comment]
@amdei 
Sorry for my delay, I think it should not be an issue for Openresty. As you see in the [install](https://github.com/openresty/lua-nginx-module#installation), Openresty recommended to use OpenResty releases which bundle Nginx, and maybe the official Nginx we can support, but there are various third part Nginx, they have difference change, maybe it is hard to support all of them.

In the Nginx of f-stack, I see the [`ngx_add_event` defined as a function](https://github.com/F-Stack/f-stack/blob/dev/app/nginx-1.16.1/src/event/ngx_event.h#L420), and it always is a macro in [offical Nginx](https://github.com/nginx/nginx/blob/master/src/event/ngx_event.h#L407), So the `if` in [lua-nginx-module](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_socket_udp.c#L1437) will get a warn `the address of ‘ngx_add_event’ will always evaluate as ‘true’`.

For your case, if you do not want to change the source code and ensure there is not other warning other code, maybe you can remove the [-Werror](http://tigcc.ticalc.org/doc/comopts.html) while compile the code. Of course, another way is to modify the source code.

**Comment by amdei** [comment]
Not an issue for lua-nginx-module.
See related issue in f-stack: https://github.com/F-Stack/f-stack/issues/503
