### ISSUE TITLE
lua_shared_dict return "no memory" error

### ISSUE THREAD

**Issue by pyrl247** [openresty/lua-nginx-module#1692]
Hello,I have some question about lua_shared_dict.
Here is my nginx config:
`location /pyrltestsetsmall {

        access_by_lua_block {
                pyrl = require "pyrltest"
                local key = pyrl:guid()
                local valuelen = math.random(10,20)
                local value = pyrl:randomStr(valuelen)
                success, err = ngx.shared.pyrldict:add(key,value)
                if success then
                        ngx.say("success add ,value = "..value)
                else
                        ngx.say("failed add ,err = "..err)
                end
        }
    }
`
When I call this route multiprocess,It return err "no memory".Is lua_shared_dict auto expire the oldest enties if there is no memry?
But when I call it singleprocess,It won't show this error.
Any help would be greatly appreciated!!

**Comment by doujiang24** [comment]
```
If up to tens of existing items have been removed and the storage left is still insufficient (either due to the total capacity limit specified by lua_shared_dict or memory segmentation), then the err return value will be no memory and success will be false
```
according to this doc: https://github.com/openresty/lua-nginx-module#ngxshareddictset

are there any other small keys in the `ngx.shared.pyrldict`?

**Comment by pyrl247** [comment]
I add all keys by calling this url "/pyrltestsetsmall",so I don't think it works as the doc mentioned "removed tens of existing items and still have no memory".
And also it happened only during multiprocessing .
when I call it single thread, the shared memory works well ,and will remove items when it's full.

**Comment by doujiang24** [comment]
@pyrl247 can you provide a reproducible and smaller case that we can reproduce it at our side?

**Comment by pyrl247** [comment]
`
location /pyrltestsmall

        access_by_lua_block {
                function guid()
                  local seed={'e','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'}
                  local tb={}
                  for i=1,32 do
                      table.insert(tb,seed[math.random(1,16)])
                  end
                  local sid=table.concat(tb)
                  return string.format('%s-%s-%s-%s-%s',
                      string.sub(sid,1,8),
                      string.sub(sid,9,12),
                      string.sub(sid,13,16),
                      string.sub(sid,17,20),
                      string.sub(sid,21,32)
                  )
                end
                function randomStr(len)
                     local rankStr = ""
                     local randNum = 0
                     for i=0,len do
                       if math.random(1,3)==1 then
                         randNum=string.char(math.random(0,26)+65)
                       elseif math.random(1,3)==2 then
                         randNum=string.char(math.random(0.26)+97)
                       else
                         randNum=math.random(0,10)
                       end
                       rankStr=rankStr..randNum
                     end
                     return rankStr
                end
                local key = guid()
                local valuelen = math.random(10,20)
                local value = randomStr(valuelen)
                success, err = ngx.shared.pyrldict:add(key,value)
                if success then
                        ngx.say("success add ,value = "..value)
                else
                        ngx.say("failed add ,err = "..err)
                end
        }
}`
Is that work for you?I writre all function I have used in nginx_lua_block.

**Comment by pyrl247** [comment]
The error shows up in single thread call too ,maybe it didn't show up before because I didn't call it a long time.If shared_dict remove tens of existing item ,why new entity add return error"no memeory" ,the previous entity value size just between 10-20.

**Comment by pyrl247** [comment]
@doujiang24 Hello？老哥? could u please check this？Thank you！！！

**Comment by doujiang24** [comment]
@pyrl247 actually, it's a known issue documented in the doc, it's a memory fragmentation related issue, and we are clarifying it more clear, see this PR:
https://github.com/openresty/lua-nginx-module/pull/1693

**Comment by pyrl247** [comment]
I see!Thank you!!!
