### ISSUE TITLE
it seems the ngx.re.match doesn't match quite rightly. e.g. the "27" is match "^0$", And "£" match "^$"

### ISSUE THREAD

**Issue by freelixilong** [openresty/lua-nginx-module#1695]
I used the "27" match "^0$", the return result is OK,  the  "£"  also match "^$".  It may be my problem, but i don't know how to solve it. It also may be a bug.

openresty/1.15.8.1

**Comment by freelixilong** [comment]
I use ngx.re.match("27", "^0$"), ngx.re.match("£", "^$")

**Comment by rainingmaster** [comment]
@freelixilong 
hello, have you download the `Openresty` download from official repo? It can not reproduce in my environment:
```
> nginx -V
nginx version: openresty/1.17.8.1rc1
built by clang 11.0.0 (clang-1100.0.33.12)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
```

nginx conf:
```
server {
    listen       8888;
    location / {
        content_by_lua_block {
            ngx.print(ngx.re.match("27", "^0$"), ", ", ngx.re.match("£", "^$"))
            ngx.exit(200)
        }
    }
}
```

```
> curl -x "127.0.0.1:8888" "http://localhost"
nil, nil
```

**Comment by freelixilong** [comment]
It is wired, it is also return right when used the invoke method given by you.  
I inovke it by sudo /var/log/nginxd/bin/resty ./xx.lua.  
May be it is wrong way invoked by this method.
Thanks very much @rainingmaster

**Comment by freelixilong** [comment]
Sorry, it seems my problem. I closed it
