### ISSUE TITLE
Cookie reset upon ngx.req.set_header("Cookie, ...")

### ISSUE THREAD

**Issue by altexy** [openresty/lua-nginx-module#1705]
Hi, 

In Gluu project we use Kong 2.0 which in turn I believe uses OpenResty OpenResty 1.15.8.2.

```Lua
local cookie1 = ngx.var.cookie_name1
local cookie2 = ngx.var.cookie_name2
-- suppose both cookies are here

-- now we want to hide cookie with `name1` from upstream server
-- we iterate thru all cookies,  remove cookie with name1, rebuild a header as semicolon separated list and call
ngx.req.set_header("Cookie", new_value)

local cookie1 = ngx.var.cookie_name1
local cookie2 = ngx.var.cookie_name2
-- now both values above contain nil
```

The real cookie header is correct, reflect our changes, but all `ngx.var.cookie_<cookie_name>` variables are damaged.

But our modules follow chain responsibility pattern.
First module works fine, seconds modules doesn't have access to its cookie, because calling `ngx.req.set_header("Cookie", new_value)` invalidate all `ngx.var.cookie_<cookie_name>` variables.

We may access a cookie using `ngx.var.http_cookie` or `ngx.req.get_header("Cookie")` and it works.
lua-resty-session library we use use `ngx.var.cookie_<cookie_name>`  to access the cookie and it fails.

I believe it may be not OpneResty specific, but because I'm using Lua - I posted this here.

Is it considered a bug or desired corner-case behavior?

**Comment by zhuizhuhaomeng** [comment]
I can't reproduce this problem with openresty 1.15.8-3.
can you reproduce in pure openresty with minimum config?

**Comment by altexy** [comment]
Hm, I cannot reproduce it using pure OpenResty.
I will try to minimize our code to minimal steps-to-reproduce.
