### ISSUE TITLE
nginx+lua-nginx-module+LuaJIT+ngx_devel_kit启动有alert

### ISSUE THREAD

**Issue by LLj-github-operations-develop** [openresty/lua-nginx-module#1720]
/usr/local/nginx-1.16.1/sbin/nginx 
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.0.5/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so') in /usr/local/nginx-1.16.1/conf/nginx.conf:118

yum -y install zlib zlib-devel openssl openssl--devel pcre pcre-devel
下载LuaJIT wget https://luajit.org/download/LuaJIT-2.0.5.tar.gz
下载ngx_devel_kit wget https://github.com/vision5/ngx_devel_kit/archive/v0.3.1.tar.gz
下载ngx_lua https://github.com/openresty/lua-nginx-module/archive/v0.10.16rc5.tar.gz
下载nginx wget https://nginx.org/download/nginx-1.16.1.tar.gz

**Comment by github65535** [comment]
同问

**Comment by WangWenchao** [comment]
1.19.2 同样的问题这个  搞得好蛋疼

**Comment by doujiang24** [comment]
the error message shows the reason:
1. you are not using a LuaJIT version which is not OpenResty's
2. missing the 'resty.core' module which is required.

**Comment by LLj-github-operations-develop** [comment]
> the error message shows the reason:
> 
> 1. you are not using a LuaJIT version which is not OpenResty's
> 2. missing the 'resty.core' module which is required.

**Comment by LLj-github-operations-develop** [comment]
1.you are not using a LuaJIT version which is not OpenResty's
The url to download LuaJIT in doc(https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/luajit.html)

**Comment by doujiang24** [comment]
openresty using this branch with some optimizations:
the url is listed in the error message: https://github.com/openresty/luajit2

**Comment by unixchina** [comment]
> 1.you are not using a LuaJIT version which is not OpenResty's
> The url to download LuaJIT in doc(https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/luajit.html)

I use openresty luajit2,but the same error

**Comment by unixchina** [comment]
> 1.19.2 同样的问题这个 搞得好蛋疼

lua-nginx-module-0.10.15自从这个版本后就开始报错了，这么多反馈官方安装文档也不更新一下

**Comment by wziww** [comment]
`luarocks install --server=https://luarocks.org/dev lua-resty-core`
Cause you are not using OpenResty's luajit, you need to isntall lua-resty-core module your self.
Also, you will need to check the version between nginx & lua-nginx-module to match correctlly (will output in the error log, if not match).

**Comment by tom123-zx** [comment]
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so') in /usr/local/nginx/nginx.conf:117

这个问题如何解决？

**Comment by LycEcho** [comment]
> nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found: no field package.preload['resty.core'] no file './resty/core.lua' no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua' no file '/usr/local/share/lua/5.1/resty/core.lua' no file '/usr/local/share/lua/5.1/resty/core/init.lua' no file './resty/core.so' no file '/usr/local/lib/lua/5.1/resty/core.so' no file '/usr/local/lib/lua/5.1/loadall.so' no file './resty.so' no file '/usr/local/lib/lua/5.1/resty.so' no file '/usr/local/lib/lua/5.1/loadall.so') in /usr/local/nginx/nginx.conf:117
> 
> 这个问题如何解决？

我也一模一样的问题
nginx version: openresty/1.21.4.3
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
