### ISSUE TITLE
Strange ngx.shared.DICT memory behaviour

### ISSUE THREAD

**Issue by decadence** [openresty/lua-nginx-module#1721]
Hello.
I don't quite understand how ngx.shared.DICT works in case of nginx memory usage.
Can you give some explanation or share some link documentation?

Let's say we have one shared.DICT in config:
```
lua_shared_dict clients 1024m;
```

For example it's filled with 100 MB after some requests and we have **6 nginx workers** enabled in config.
When the nginx under the load `atop` shows that RSIZE is approximately 600 MB (exactly **6 times** bigger than dictionary size).
When nginx is not under load `atop` doesn't show this memory usage. Only initial 100 MB.

Questions:
1. Is this normal behaviour that memory usage is greater 6 times than actual size of the dictionary? Does nginx copy data each time for each worker?
2. This memory is allocated even when I hit location which does not have `access_by_lua_file` (even static resources like images). Is this by design and can we disable this somehow so nginx doesn't allocate memory because we don't need it in this location?
3. Does string length in key affect memory usage or one dictionary item takes fixed memory size? And what is maximum key length?

Software:
nginx/1.16.1 + LuaJIT
Lua 5.1
CentOS Linux release 7.8.2003

Some compilation script options:
ARG LUAJIT_VERSION=2.1
ARG LUAJIT_RELEASE=20190507
ARG LUAMODULE_VERSION=0.10.15
ARG NGX_DEVEL_KIT_VERSION=0.3.1
ARG LUA_LRUCACHE_VERSION=0.09
ARG LUA_CORE_VERSION=0.1.17
ENV LUAJIT_LIB /usr/lib/
ENV LUAJIT_INC /usr/include/luajit-2.1/

**Comment by zhuizhuhaomeng** [comment]
here is a share about dhdict https://forum.openresty.us/d/6391-shdict-no-memory/3

**Comment by decadence** [comment]
@zhuizhuhaomeng thanks but I don't speak chinese unfortunately.
Can you provide some summary of that discussion?

**Comment by zhuizhuhaomeng** [comment]
Is this normal behaviour that memory usage is greater 6 times than actual size of the dictionary? Does nginx copy data each time for each worker?
dictionary is shared among all the worker. there are no copy.


This memory is allocated even when I hit location which does not have access_by_lua_file (even static resources like images). Is this by design and can we disable this somehow so nginx doesn't allocate memory because we don't need it in this location?

when the shared memory is allocate by the system, it will keep in memory. so you have other access ??


Does string length in key affect memory usage or one dictionary item takes fixed memory size? And what is maximum key length?

they do not take fix size. there is not explict limit on the key length and value

**Comment by decadence** [comment]
> there are no copy
Anyway there is 6x time RAM usage than dictionary size when 6 workers are active. 

Ok I think first and second question answer is "this is by design".

3. Got it.

**Comment by zhuizhuhaomeng** [comment]
show  the minimal config and test code that can reproduce this problem.

**Comment by decadence** [comment]
nginx
```
lua_shared_dict clients 1024m;
worker_processes 6;

location /test {
   access_by_lua_file /test.lua
}
```

test.lua
```lua
local clients = ngx.shared.clients

-- here we need to set new dictionary key each time we got request
-- just for testing purpose to see dictionary grows
-- so we get random key
math.randomseed(os.time())
local random = math.random(0, 10^10)
clients:set(random, 1)

local memory = (clients:capacity() - clients:free_space()) / 1024 / 1024

ngx.say(memory)
```

Then put this location under the load (by some script with HTTP requests) and see how many memory dictionary requires.
If you open `atop` you will see that all nginx processes use `RAM = worker_processes * memory` in summary.
When you stop the load nginx RAM usage is back to low.

We think this is by design. When worker is active nginx allocates individual memory copy of shared dictionary to each worker.
