### ISSUE TITLE
balancer_by_lua context missed in ngx.var.VARIABLE's doc

### ISSUE THREAD

**Issue by RocFang** [openresty/lua-nginx-module#1731]
ngx.var.VARIABLE is supported in balancer_by_lua context, but it seems the balancer_by_lua context is missed in ngx.var.VARIABLE's doc:

https://github.com/openresty/lua-nginx-module#ngxvarvariable

I don't know if there is something special to pay attention? thanks.

**Comment by doujiang24** [comment]
Thanks for your report, fixed in https://github.com/openresty/lua-nginx-module/pull/1761.
