### ISSUE TITLE
Yielding in generator loops leaks Lua contexts

### ISSUE THREAD

**Issue by piotrp** [openresty/lua-nginx-module#1732]
Executing the following scripts gives loops with increasing execution time:
```
#!/usr/bin/resty

local coro_yield = coroutine.yield
local coro_wrap = coroutine.wrap

local function get_time()
  ngx.update_time()
  return ngx.now()
end

local function get_generator()
  return coro_wrap(function()
    for _ = 1, 1000 do
      coro_yield(1)
    end
  end)
end

local function work()
  for _ in get_generator() do
  end
end

local i = 1
local t0_single = get_time()
local t0_batch = t0_single
while true do
  work()
  local t_now = get_time()
  if i % 1000 == 0 then
    print(("[%7d] time: %.3fs (batch: %.3fs)"):format(i, t_now - t0_single, t_now - t0_batch))
    t_now = get_time()
    t0_batch = t_now
  end
  t0_single = t_now
  i = i + 1
end
```

Time is spent in `ngx_http_lua_get_co_ctx`. Found this in a long running process that was executing yielding code in "work - sleep for 15s" loop after it stopped making its loops in time.

OpenResty 1.15.8.3

[job-1754260-C-land-CPU-Flame-Graph.zip](https://github.com/openresty/lua-nginx-module/files/4797698/job-1754260-C-land-CPU-Flame-Graph.zip)

**Comment by doujiang24** [comment]
yeah, same as https://github.com/openresty/lua-nginx-module/issues/1749.

**Comment by Crack** [comment]
Wouldn't #1749 only make this issue less pronounced? It's about making lookups faster, and I encountered a lookup list that was larger than it should be. Unless contexts are properly removed from list and it stays full of empty slots.

**Comment by doujiang24** [comment]
the coroutine is created from the Lua Land, and it does not have a destroy API, it will be destoryed by Lua GC manager.
I don't think we can remove it from list without a destroy API.

**Comment by agentzh** [comment]
@Crack Will you have a look at our slack channel please?

**Comment by Crack** [comment]
Thanks for explaining. So it's an issue only when user code uses a lot of generators and generates little Lua land garbage. Then GC doesn't kick in and runtime crawls to a stop, because from GC's heuristic's viewpoint there's nothing to collect.

**Comment by piotrp** [comment]
I just re-run my test script with 1.19.3.1, looks like it's no longer an issue

**Comment by spacewander** [comment]
Good to know. 
Consider solved.
