### ISSUE TITLE
PRs that ready to be merged

### ISSUE THREAD

**Issue by doujiang24** [openresty/lua-nginx-module#1747]
just a list for tracking.

1. https://github.com/openresty/lua-nginx-module/pull/1682
2. https://github.com/openresty/lua-nginx-module/pull/1666

**Comment by rainingmaster** [comment]
@doujiang24 hi, should we track them in here: https://github.com/openresty/lua-nginx-module/projects?

**Comment by rainingmaster** [comment]
https://github.com/openresty/lua-nginx-module/pull/1735 also should be ok now

**Comment by doujiang24** [comment]
https://github.com/openresty/lua-nginx-module/pull/1734
https://github.com/openresty/lua-resty-core/pull/302

**Comment by doujiang24** [comment]
https://github.com/openresty/lua-resty-core/pull/306

**Comment by agentzh** [comment]
Blocked #1735.

**Comment by agentzh** [comment]
Blocked openresty/lua-resty-core#302.

**Comment by agentzh** [comment]
Blocked #1666.

**Comment by agentzh** [comment]
Blocked #1682.

**Comment by rainingmaster** [comment]
> Blocked #1682.

https://github.com/openresty/lua-nginx-module/pull/1682 fixed and merged

**Comment by spacewander** [comment]
https://github.com/openresty/lua-nginx-module/pull/1756
https://github.com/openresty/lua-nginx-module/pull/1759
https://github.com/openresty/meta-lua-nginx-module/pull/78

**Comment by doujiang24** [comment]
moved to this project: https://github.com/orgs/openresty/projects/1
