### ISSUE TITLE
FIXME: we should use rbtree here to prevent O(n) lookup overhead in ngx_http_lua_get_co_ctx

### ISSUE THREAD

**Issue by doujiang24** [openresty/lua-nginx-module#1749]
related code:
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_util.c#L3125

we have observed `ngx_http_lua_get_co_ctx` take almost all of the CPU time in CPU flamegraph.
![image](https://user-images.githubusercontent.com/570391/87622455-bc171b80-c755-11ea-9591-7430a2d3726b.png)

it's easy to reproduce it by using [resty.http](https://github.com/ledgetech/lua-resty-http) in a resty command, like:

```
while true do -- a long time job
    -- resty.http request
end
```

**Comment by doujiang24** [comment]
related PR:
https://github.com/openresty/lua-nginx-module/pull/1215

**Comment by agentzh** [comment]
Now this operation becomes O(1), even better than the O(log n) time complexity in this PR. So closing this one as well as #1215.
