### ISSUE TITLE
support gRPC ?

### ISSUE THREAD

**Issue by snpcp** [openresty/lua-nginx-module#1782]
How to using gRPC for lua-nginx-module?

**Comment by spacewander** [comment]
Nginx supports gRPC proxy.
OpenResty doesn't provide gRPC relative feature, but you can treat gRPC request as a special HTTP2 request.
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

**Comment by snpcp** [comment]
ok, Please whether cosocket supports HTTP2?

**Comment by spacewander** [comment]
I guess no, but you can give it a try.
Unless you are using stream mode gRPC, you can use `ngx.req.read_body()` to get the data and do whatever you want.

**Comment by snpcp** [comment]
thanks for your tell me. that's big project for implement http2, so I will try to using others lib. thanks you help again.
