### ISSUE TITLE
openresty1.13.6.1 cannot use ngx.shared.dict:free_space()

### ISSUE THREAD

**Issue by huzhewei** [openresty/lua-nginx-module#1785]
This place is for bug reports and development discussions only. For general questions and
discussions, please join the openresty-en mailing list instead: https://openresty.org/en/community.html

Ensure you have provided the following details while reporting a problem:

* The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version,
and your operating system version.
* A minimal and standalone test case that others can easily run on their side and
reproduce the issue you are seeing.
* Do not simply say "something is broken" or "something does not work". Always provide
as much details as possible. Always describe the symptoms and your expected results.
* You can (temporarily) enable the nginx debugging logs to see the internal workings
of NGINX in your nginx''s `error.log` file. See http://nginx.org/en/docs/debugging_log.html
The same instructions apply equally well to OpenResty.
* If you are seeing crashes, please provide the full backtrace for the crash. See
https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump
for more details.

Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by huzhewei** [comment]
My openresty version is 1.13.6.2, but I cannt use ngx.shared.dict:free_space() in it,
while I have seen that it was supported in 1.13.6.1。 
![image](https://user-images.githubusercontent.com/50432229/93604352-d7253680-f9f7-11ea-8686-ccfea8a14773.png)

![image](https://user-images.githubusercontent.com/50432229/93604297-c5439380-f9f7-11ea-845c-a9a431ce0130.png)

**Comment by decadence** [comment]
Show the full code. Likely you just call method on the value that is not a dictionary.

**Comment by spacewander** [comment]
@huzhewei 
Have you called `require "resty.core.shdict"`as the doc suggests: https://github.com/openresty/lua-nginx-module#ngxshareddictfree_space?
We need a reproducible example, otherwise we can't offer you any help.

**Comment by huzhewei** [comment]
thank you @spacewander , it's all my fault !
I think that I didnt read the doc carefully and missed the [ require "resty.core.shdict" ].

Best wishes to you @decadence  @spacewander !
