### ISSUE TITLE
How to using access_by_lua on ngx.location.capture???

### ISSUE THREAD

**Issue by snpcp** [openresty/lua-nginx-module#1786]
I want to add auth to access_by_lua, but It doesn't call access_by_lua when execute the ngx.location.capture.

I see some doc about it: 
``As with other access phase handlers, access_by_lua will not run in subrequests.``

What should I do?

**Comment by snpcp** [comment]
https://github.com/openresty/lua-nginx-module#access_by_lua

**Comment by spacewander** [comment]
As you already pointed out, there is no way to run access_by_lua because Nginx doesn't run access phase in the subrequests.
