### ISSUE TITLE
Generic front-end interface for ngx_lua

### ISSUE THREAD

**Issue by simpl** [openresty/lua-nginx-module#179]
Have you considered the idea of creating a front-end socket configuration for ngx_lua (i.e. an interface on which ngx_lua can accept incoming connections)?  Thus any type of server could use the power of ngx_lua, not just an HTTP(S) one, sort of in a similar way to Node.js.

It could be implemented in a top-level lua { ... } block (instead of the http {} block, and there could be similar server {} blocks, with core settings like listen, buffer sizes etc could be set in the config file but the large part of the processing could be done by Lua, including all the header parsing.

I'm fairly sure it would then probably be possible to implement an HTTP server that was quite a bit quicker than Nginx, but I can also see other possibilities.  You could create your own Memcached/Redis implementation, perhaps performing some kind of cluster management while keeping the logic away from the connecting service.

**Comment by deltay** [comment]
Since nginx stream module is open source now, it there any plan to add stream lua support in ngx_lua module ?

**Comment by agentzh** [comment]
@deltay Yes, it's on the TODO list and the development work is expected to begin (and done) in Q4.

**Comment by agentzh** [comment]
The ngx_stream_lua_module is now available for testing:

https://github.com/openresty/stream-lua-nginx-module

Feedback welcome!

Since this module already allows what this ticket was asking for, I'm closing this.
