### ISSUE TITLE
init_worker_by_lua_block not working !!!

### ISSUE THREAD

**Issue by kiss291323003** [openresty/lua-nginx-module#1802]
my nginx.conf
```
worker_processes 2;
events
{
    worker_connections 65535;
}
http
{
    init_worker_by_lua_block{
         local timer = require("resty.xxxxx")
    }
    server{
        error_log error.log;
        access_log off;
    }
}
```
and here  resty.xxxxx is not an exists lib 。
if init_worker_by_lua_block working ,it should be throw error ,but it has not any error。

my openresty version is  1.15.8.3 。system: macos

**Comment by spacewander** [comment]
The `error_log error.log;` only applies in the server scope. You should take a look at `logs/error.log`.
