### ISSUE TITLE
ngx.req.set_header is not compliant with the HTTP spec RFC 7230

### ISSUE THREAD

**Issue by murillopaula** [openresty/lua-nginx-module#1827]
I think [ngx.req.set_header](https://github.com/openresty/lua-nginx-module#ngxreqset_header) is doing the opposite of what the HTTP spec RFC 7230 says:

>  A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).
>
> https://www.rfcreader.com/#rfc7230_line1043

As shown by this test case: https://github.com/openresty/lua-nginx-module/blob/master/t/028-req-header.t#L281-L296

Per the RFC, the request headers should be

```
Foo: a,abc
```

Instead of 

```
Foo: a
Foo: abc
```

**Comment by bungle** [comment]
@murillopaula,

```lua
 ngx.req.set_header("Foo", table.concat({"a", "abc"}, ”, ”))
```

should do it.
