### ISSUE TITLE
Is there any possibilities to share lua_shared_dict in different dockers container?

### ISSUE THREAD

**Issue by sddwt** [openresty/lua-nginx-module#1859]
* Docker version 1.13.1, build 0be3e21/1.13.1
* module version: latest build
Hi,
I'm trying to use --ipc=host to share memory cache during different containers to make no cache waste.
But I tried and it's not work as I expected.

```
header_filter_by_lua_block{

                ngx.header["content-type"] = "text/html;charset=utf-8"

            }
            location / {
                content_by_lua_block{
                    local data = ngx.shared.status:get("data")
                    if data == nil then ngx.shared.status:set("data", "c1", 30)
                    else ngx.say(data) end
                    ngx.say("hi, c1")
                }
            }
```
You can see that different container can set different status value,
But I just got same value as ```ngx.say```.
How could I achieve that or is it possible to achieve that?
Thanks.

**Comment by sddwt** [comment]
docker command is:
```
docker run --privileged  --ipc=host -itd  --network=mynet centos:7 /bin/bash
```

**Comment by attenuation** [comment]
No, nginx shared dict share memory with nginx worker process created by nginx master process, different dockers container have different nginx master and worker pair process in your machine, so if you want to share data with different docker container, i suggest  you use redis or other key/value database to do it.
https://github.com/openresty/lua-resty-redis

**Comment by sddwt** [comment]
> No, nginx shared dict share memory with nginx worker process created by nginx master process, different dockers container have different nginx master and worker pair process in your machine, so if you want to share data with different docker container, i suggest you use redis or other key/value database to do it.
> https://github.com/openresty/lua-resty-redis

Thanks, I forgot about that.
