### ISSUE TITLE
How to get the server certificate information with sslhandshake?

### ISSUE THREAD

**Issue by Evengard** [openresty/lua-nginx-module#1865]
Hello!

When calling tcpsock:sslhandshake, it seems there is no way to extract the server certificate data. I want to check manually for some fields in the certificate instead of matching it with an exact list of certificates. Is it somehow possible?

Thanks.

**Comment by geniuss99** [comment]
Yes, it is.

The easiest way is to to use LuaJIT's FFI library and call SSL_SESSION_get0_peer(SSL_SESSION *s) for session object returned from tcpsock:sslhandshake() call.

You can look at how it's done in the ssl module of OpenResty itself:
https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.lua

**Comment by Evengard** [comment]
Thanks, I stumbled upon https://github.com/fffonion/lua-resty-openssl after your comment which actually gave me an idea what to earch for. Seems to be what I need.
As an unrelated question, how hard would it be to call a custom getsocketopt with FFI on a ngx.req.socket()?

**Comment by geniuss99** [comment]
> As an unrelated question, how hard would it be to call a custom getsocketopt with FFI on a ngx.req.socket()?
You'll need to write your custom wrapper function in C language, compile it and link your .obj file to executable.
After that you'll be able to call your function via FFI binding from lua code.

No that hard if you know how to do it.

**Comment by Evengard** [comment]
Well, I actually found that modifying openresty source was easier for my custom getsockopt =) (https://github.com/Evengard/stream-lua-nginx-module/commit/2afc3a1de45ccce2b18542576922aabbac6f4d3c) I'll experiment with the server certificate information retrieval now, thanks!

**Comment by geniuss99** [comment]
> Well, I actually found that modifying openresty source was easier for my custom getsockopt =)

True, for small changes. Good luck :)

**Comment by Evengard** [comment]
Ended up writing a nginx module for that xD https://github.com/Evengard/lua-resty-getorigdest-module
Anyways, thanks for the help, lua-resty-openssl was the way to go, I successfully managed to retrieve info from the certificate.
