### ISSUE TITLE
wget has error "Unable to establish SSL connection"

### ISSUE THREAD

**Issue by MriceZxu** [openresty/lua-nginx-module#1895]
--2021-06-26 02:48:13--  https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.10.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openresty/lua-nginx-module/tar.gz/refs/tags/v0.10.10 [following]
--2021-06-26 02:48:14--  https://codeload.github.com/openresty/lua-nginx-module/tar.gz/refs/tags/v0.10.10
Resolving codeload.github.com (codeload.github.com)... 13.229.189.0
Connecting to codeload.github.com (codeload.github.com)|13.229.189.0|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.

**Comment by zhuizhuhaomeng** [comment]
network problem, please learn about how to across gfw
