### ISSUE TITLE
Strange thing while change ngx.arg[1] in body_filter_by_lua*

### ISSUE THREAD

**Issue by waterdeng** [openresty/lua-nginx-module#1906]
oprenresty version:1.15.8

I want to change file stream while downloading,  but I encountered a strange thing 
that once I touch ngx.arg[1] in body_filter_by_lua\*, **client will receive some little response first, 
then wait untill nginx process process the whole file**. 

Client will receive the whole file, but client receives nothing for a quite long time.
Nginx worker process will occupy memory about the same size as the file.

So what's the point?

I test with the following lua code **for simplify**, same thing happened too.  
File has size bigger than 1GB. 

```
location / {
    header_filter_by_lua_block { 
        ngx.header.content_length = nil 
    }
    body_filter_by_lua_block {
        ngx.arg[1]=ngx.arg[1]
    }
}
````

I know when set ngx.header.content_length to nil, 
http response will use  [chunked Transfer-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding),
and client will receive the file content via chunks.
I capture the http protocol with wireshark and 
check the chunk response, client receive part of first chunk
and then wait untill the whole file porcessed done.

**Comment by zhuizhuhaomeng** [comment]
please check if it still exists in openresty 1.19.3

**Comment by waterdeng** [comment]
> please check if it still exists in openresty 1.19.3



> please check if it still exists in openresty 1.19.3

**Comment by waterdeng** [comment]
> please check if it still exists in openresty 1.19.3

nothing changed.

**Comment by waterdeng** [comment]
If I jsut set ngx.header.content_length to nil in  header_filter_by_lua_block and has no body_filter_by_lua_block,
chunk size of [chunked Transfer-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding)
http response will be 512KB, the same as output buffer size in nginx conf.

Once touch ngx.arg[1] in body_filter_by_lua_block, chunk size will be **512K+1Bytes**, quite weird.

**Comment by waterdeng** [comment]
Everthing works well when nginx output_buffers is small enough. 
I set output_buffers to 16k and download of 2GB file is fine. 
Bigger files's download is not tested for now.

**Comment by zhuizhuhaomeng** [comment]
body_filter_by_lua_block {
        ngx.arg[1]=ngx.arg[1]
    }

this config will copy buffer from nginx buffer chain to a lua string, and then the assignment will copy the string buffer back to nginx.  so there will so many different lua strings which will consume much of the memory.

there is not need to set ngx.arg[1]=ngx.arg[1] in body_filter_by_lua_block.

**Comment by waterdeng** [comment]
> ```
> body_filter_by_lua_block {
>     ngx.arg[1]=ngx.arg[1]
> }
> ```
> 
> this config will copy buffer from nginx buffer chain to a lua string, and then the assignment will copy the string buffer back to nginx. so there will so many different lua strings which will consume much of the memory.
> 
> there is not need to set ngx.arg[1]=ngx.arg[1] in body_filter_by_lua_block.

Sorry for my expression. 'ngx.arg[1]=ngx.arg[1]' in body_filter_by_lua_block is just for test, it is much more complicated in fact.
But the  problem exists both.

**Comment by zhuizhuhaomeng** [comment]
there is still something I can not explain exactly.
will post a message here if I figure it out.

**Comment by waterdeng** [comment]
I enable nginx debug log and find epoll_wait blocked about 150s. 
I can't figure it out how it works before I know more code details.

![image](https://user-images.githubusercontent.com/6376310/129687134-a4cb0e80-35fa-4c39-a081-ac53447fdcf4.png)

![image](https://user-images.githubusercontent.com/6376310/129687479-6b0f23fb-dbd8-4f4d-a6d4-0ca2e3faa1a1.png)

**Comment by zhuizhuhaomeng** [comment]
https://github.com/openresty/lua-nginx-module/pull/1909

**Comment by waterdeng** [comment]
I tested with PR #1909 code, problem disappeared.

@zhuizhuhaomeng Thanks.
