### ISSUE TITLE
AddressSanitizer memcpy-param-overlap

### ISSUE THREAD

**Issue by Vadim-kb-lab** [openresty/lua-nginx-module#1938]
AddressSanitizer: memcpy-param-overlap

Version openresty-1.15.8.1

Run:
`ASAN_OPTIONS=log_path=/mnt/logs/Reports/1/asan/crash.test:log_exe_name=1:verbosity=7:exitcode=0:abort_on_error=1:handle_segv=0:detect_leaks=0:symbolize=0 /usr/local/openresty-debug/bin/openresty  -c /usr/local/openresty/nginx/conf/crash.conf -t`

Config files [crash.conf.txt](https://github.com/openresty/lua-nginx-module/files/7337447/crash.conf.txt)

Error:

```
==openresty==70603==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x621000001500,0x621000002181) and [0x62100000187f, 0x621000002500) overlap
    #0 0x7f3db1899ffe  (/lib64/libasan.so.5+0x99ffe)
    #1 0x9da926  (/usr/local/openresty-debug/nginx/sbin/nginx+0x9da926)
    #2 0x9dd1a1  (/usr/local/openresty-debug/nginx/sbin/nginx+0x9dd1a1)
    #3 0x4c89c6  (/usr/local/openresty-debug/nginx/sbin/nginx+0x4c89c6)
    #4 0x5d1e4e  (/usr/local/openresty-debug/nginx/sbin/nginx+0x5d1e4e)
    #5 0x4c89c6  (/usr/local/openresty-debug/nginx/sbin/nginx+0x4c89c6)
    #6 0x5b8583  (/usr/local/openresty-debug/nginx/sbin/nginx+0x5b8583)
    #7 0x4c89c6  (/usr/local/openresty-debug/nginx/sbin/nginx+0x4c89c6)
    #8 0x4b4419  (/usr/local/openresty-debug/nginx/sbin/nginx+0x4b4419)
    #9 0x427f16  (/usr/local/openresty-debug/nginx/sbin/nginx+0x427f16)
    #10 0x7f3daff27554  (/lib64/libc.so.6+0x22554)
    #11 0x42d537  (/usr/local/openresty-debug/nginx/sbin/nginx+0x42d537)

0x621000001500 is located 0 bytes inside of 4096-byte region [0x621000001500,0x621000002500)
allocated by thread T0 here:
    #0 0x7f3db190c638  (/lib64/libasan.so.5+0x10c638)
    #1 0x546381  (/usr/local/openresty-debug/nginx/sbin/nginx+0x546381)

0x62100000187f is located 895 bytes inside of 4096-byte region [0x621000001500,0x621000002500)
allocated by thread T0 here:
    #0 0x7f3db190c638  (/lib64/libasan.so.5+0x10c638)
    #1 0x546381  (/usr/local/openresty-debug/nginx/sbin/nginx+0x546381)

SUMMARY: AddressSanitizer: memcpy-param-overlap (/lib64/libasan.so.5+0x99ffe) 
==openresty==70603==ABORTING
```
Full backtrace [backtracefull.txt](https://github.com/openresty/lua-nginx-module/files/7337472/backtracefull.txt)

Error in line 1609, file ngx_lua-0.10.15/src/ngx_http_lua_directive.c:
```
1604-
1605-                return NGX_ERROR;
1606-            }
1607-
1608-            if (len) {
1609:                ngx_memcpy(b->start, b->pos, len);
1610-            }
1611-
1612-            size = (ssize_t) (file_size - cf->conf_file->file.offset);
1613-
1614-            if (size > b->end - (b->start + len)) {

```

**Comment by shankusu2017** [comment]
Can you upload the complete conf file

**Comment by Vadim-kb-lab** [comment]
Other crash ([crashes.zip](https://github.com/openresty/lua-nginx-module/files/7353565/crashes.zip)) find by AFL (exclude id%3A000000... we are already discussing this). All asan logs ([asan.zip](https://github.com/openresty/lua-nginx-module/files/7353577/asan.zip))

**Comment by shankusu2017** [comment]
@Vadim-kb-lab ，Nginx cannot handle a single configuration that is too long, such as a very long string, or a configuration item that is too long due to format errors in the configuration file you submitted. For details, please see the screenshot below, thank you

**Comment by shankusu2017** [comment]
a single configuration that is too long, like this 

`types {
    text/html                                        html htm shtml;
    text/css                                        7css;
    text1xml                                         xml;
    image/gif                                        gif;
    image/jpeg                                       jpeg jpg;
    application/javascript                           js;
    application/atom+xml                             atom;
    application/rss+xml                              rss;

    text/mathml                                      mml;
    text/plain                                      txt;
    text/vnd.sun.j2me.app-descriptor                 jad;
    text/vnd.wap.wml                                 wml;
    text/x-component                                 htc;

    image/png                                        png;
    image/svg+xml                                    svg svgz;
    image/tiff                                       tif tiff;
    image/vnd.wap.wbmp                               wbmp;
    image/webp                                       webp;
    image/x-icon                                     ico;
    image/x-jng                                      jng;
    image/x-ms-bmp                                   bmp;

    font/woff                                        woff;
    font/woff2                                       woff2;

    application/java-archive                         jar war ear;
    application/json                                 json;
    applicationes;
    defaul/mac-binhex40                         hqx;
    application/msword                               doc;
   application/pdf                                     xls;
    a              pdf;
    application/postscript                           ps eps ai;
    application/rtf                                  rtf;
    application/vnd.apple.mpegurl                    m3u8;
    application/vnd.google-earth.kml+xml             kml;
    application/vnd.google-earth.kmz                 kmz;
    application/vnd.ms-excel                         xls;
    application/vnd.ms-fontobject                    eot;
    application/   ps eps mime.types;
  ai;
    applica            ppt;    application/vnd.oasis.opendocument.graphics      odg;
    application/vnd.oasis.opendocument.presentation  odp;
    application/vnd.oasis.opendocument.spreadsheet   ods;
    application/vnd.oasis.opendocument.text          odt;
    application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                     pptx;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                       pplication/x-                 xlsx;
    application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                     docx;
    application/vnd.wap.wmlc                         wmlc;
    application/x-7z-compressed                      7z;
    application/x-cocoa                            ! cco;
    application/x-java-archive-diff                  jardiff;
    application/x-java-jnlp-file                     jnlp;
    application/x-makeself                           run;
»   application/x-perl                               pl pm;
    application/x-pilot                   location = /50x.html    application/x-rar-cressed                     rar;
    application/x-redhat-package-manager             rpm;
    application/x-sea                                sea;
    application/x-shockwave-flash                    swf;
    application/x-stuffit                            sit;
    application/x-tcl                                tcl tk;
    application/x-x509-ca-cert                       der pem crt;
    application/x-xpinstall                          xpi;
   o.colication/xhtml+xml                            xhtml;
    application/xspf+xml                             xspf;
    application/zip                                  zip;

    application/octet-stream                         bin exe dll;


The format mismatch problem in the configuration should be modified, such as adding the corresponding'}' at the end

**Comment by zhuizhuhaomeng** [comment]
https://github.com/openresty/lua-nginx-module/pull/1940
@Vadim-kb-lab  thank you for your reporting. 
We have fixed the problem.
