### ISSUE TITLE
Rescue of Nginx Exit Invocation 

### ISSUE THREAD

**Issue by abarrak** [openresty/lua-nginx-module#1957]
Hi, 
I wonder if there's there a way to capture the call of `ngx.exit` in the calling modules?

**Comment by GumpSun** [comment]
Please describe in detail

> Hi, I wonder if there's there a way to capture the call of `ngx.exit` in the calling modules?

**Comment by abarrak** [comment]
Hi @GumpSun,
Let's say I'm working on a codebase with a dependency that invokes `nginx.exit(stat_code)` when some sort of errors occur. And I would like to catch that call, then handle the error gracefully without the need to end or exit the current req/res cycle.

**Comment by GumpSun** [comment]
> 嗨@GumpSun， 假设我正在开发一个代码库，该代码库具有在`nginx.exit(stat_code)`发生某种错误时调用的依赖项。我想捕捉那个调用，然后优雅地处理错误，而不需要结束或退出当前的请求/请求周期。

Have you ever tried to capture error with pcall/xpcall?

**Comment by GumpSun** [comment]
> Hi @GumpSun, Let's say I'm working on a codebase with a dependency that invokes `nginx.exit(stat_code)` when some sort of errors occur. And I would like to catch that call, then handle the error gracefully without the need to end or exit the current req/res cycle.

Have you ever tried to capture error with pcall/xpcall?

**Comment by abarrak** [comment]
Thanks for the tip! 👍🏼 

As I mentioned `nginx.exit()` is what I'm looking to catch not `error`. 
what I meant by errors are business type of errors.
