### ISSUE TITLE
something about ngx.var.arg_

### ISSUE THREAD

**Issue by Purple-Dandelions** [openresty/lua-nginx-module#1977]
Hello, i try to use ngx.var.arg_ to get the param in the uri like
```
local name= ngx.var.arg_name
```
but when there is a space(which will be a %20 in the uri) in "name", such as
```
?name=hello%20world
```
i get a value "hello%20world" instead of "hello world"

does this mean the param "name" can not contain a space if i use ngx.var.arg_name?

and if the param contains a space, i have to use ngx.req.get_uri_args instead？

**Comment by zhuizhuhaomeng** [comment]
you can use ngx.decode_args  https://github.com/openresty/lua-nginx-module#ngxdecode_args

**Comment by Purple-Dandelions** [comment]
> you can use ngx.decode_args https://github.com/openresty/lua-nginx-module#ngxdecode_args

OK, thanks
