### ISSUE TITLE
rewrite_by_lua_block inside server block  is not being executed.

### ISSUE THREAD

**Issue by dileepyavan** [openresty/lua-nginx-module#1988]
Hello everyone,

I'm having problem with the following nginx configuration file(included only minimal config). rewrite_by_lua_block in server block is not executing. This config is generated by kubernetes ingress controller.When I replace rewrite_by_lua_block with access_by_lua_block, lua script seems to be executing. Is this because rewrite blocks are present both in location and server?

server {

    # this is not being executed.
    rewrite_by_lua_block {
        local res = ngx.location.capture("/auth")
        if res.status == ngx.HTTP_OK then
        if res.header["requesttype"] == "bar" then
        return ngx.req.set_uri("/bar/api/check", true)
        end
        return;
        end
        if res.status == ngx.HTTP_FORBIDDEN then
        ngx.exit(res.status)
        end
        ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    }

     location bar/api/check/ {

        rewrite_by_lua_block {
                lua_ingress.rewrite({
                        force_ssl_redirect = false,
                        ssl_redirect = true,
                        force_no_ssl_redirect = false,
                        preserve_trailing_slash = false,
                        use_port_in_redirects = false,
                        global_throttle = { namespace = "", limit = 0, window_size = 0, key = { }, ignored_cidrs = { } },
                })
                balancer.rewrite()
                plugins.run()
        }

     }

I'm using nginx v1.19.9

Any help is appreciated.

**Comment by zhuizhuhaomeng** [comment]
Yes, only the inner rewrite_by_lua_block will be executed.

**Comment by dileepyavan** [comment]
Thanks for clarifying.
