### ISSUE TITLE
Dynamic Cert Loading.

### ISSUE THREAD

**Issue by abrahack** [openresty/lua-nginx-module#2006]
Hello there, please I have a question.

I want to setup a nginx config, with the ability to setup dynamic cert loading .

```nginx
server {
    listen 443 ssl;
    server_name   test.com;

    # useless placeholders: just to shut up NGINX configuration
    # loader errors:
    ssl_certificate /path/to/fallback.crt;
    ssl_certificate_key /path/to/fallback.key;

    ssl_certificate_by_lua_block {
        local ssl = require "ngx.ssl"
        # I want a function here to perform a logic .
        # based on a true condition, a new ssl_certificate and ssl_certificate_key should be loaded from the file system.
        # based on a false condition, the fallback cert should be used.
    }

    location / {
        root html;
    }
}
```

So basically I need a way for the lua script to change the ssl_certificate & ssl_certificate_key .

Please how can this be done ?

**Comment by GumpSun** [comment]
Reference ：
`local ssl = require "ngx.ssl"
ssl.clear_certs()
local server_name = ssl.server_name()
if server_name ~= nil then
    server_name = string.gsub(server_name,"^www%.","")
    local file = io.open("/opt/openresty/nginx/conf/ssl/" .. server_name ..".pem")
    if file == nil then
        file = io.open("/opt/openresty/nginx/conf/letsencrypt/ssl/" .. server_name .."/mytest.pem")
        if file == nil then
            file = io.open("/opt/openresty/nginx/conf/ssl/nginx.pem")
        end
    end
    local f = assert(file)
    local pem_cert_chain = f:read("*a")
    local der_cert_chain, err = ssl.cert_pem_to_der(pem_cert_chain)
    ssl.set_der_cert(der_cert_chain)
    f:close()
    
    local kfile = io.open("/opt/openresty/nginx/conf/ssl/" .. server_name ..".key.pem")
    if kfile == nil then
        kfile = io.open("/opt/openresty/nginx/conf/letsencrypt/ssl/" .. server_name .."/privkey1.pem")
        if kfile == nil then
            kfile = io.open("/opt/openresty/nginx/conf/ssl/nginx.key.pem")
        end
    end
    local k = assert(kfile)
    local pem_priv_key = k:read("*a")
    local der_priv_key, err = ssl.priv_key_pem_to_der(pem_priv_key)
    ssl.set_der_priv_key(der_priv_key)
    k:close()
end`

**Comment by GumpSun** [comment]
Reference ：

local ssl = require "ngx.ssl"
ssl.clear_certs()
local server_name = ssl.server_name()
if server_name ~= nil then
    server_name = string.gsub(server_name,"^www%.","")
    local file = io.open("/opt/openresty/nginx/conf/ssl/" .. server_name ..".pem")
    if file == nil then
        file = io.open("/opt/openresty/nginx/conf/letsencrypt/ssl/" .. server_name .."/mytest.pem")
        if file == nil then
            file = io.open("/opt/openresty/nginx/conf/ssl/nginx.pem")
        end
    end
    local f = assert(file)
    local pem_cert_chain = f:read("*a")
    local der_cert_chain, err = ssl.cert_pem_to_der(pem_cert_chain)
    ssl.set_der_cert(der_cert_chain)
    f:close()
    
    local kfile = io.open("/opt/openresty/nginx/conf/ssl/" .. server_name ..".key.pem")
    if kfile == nil then
        kfile = io.open("/opt/openresty/nginx/conf/letsencrypt/ssl/" .. server_name .."/privkey1.pem")
        if kfile == nil then
            kfile = io.open("/opt/openresty/nginx/conf/ssl/nginx.key.pem")
        end
    end
    local k = assert(kfile)
    local pem_priv_key = k:read("*a")
    local der_priv_key, err = ssl.priv_key_pem_to_der(pem_priv_key)
    ssl.set_der_priv_key(der_priv_key)
    k:close()
end

**Comment by abrahack** [comment]
Hi @GumpSun ,

Thanks for the help .

Now I have one more question .

How will you access the host header, when the `server_name` is set to `_` .

**Comment by zhuizhuhaomeng** [comment]
ngx.var.http_host is still avaiable.

**Comment by GumpSun** [comment]
> Hi @GumpSun ,
> 
> Thanks for the help .
> 
> Now I have one more question .
> 
> How will you access the host header, when the `server_name` is set to `_` ?

You can access that from nginx built-in variables. 
The ngx_http_core_module module supports embedded variables with names matching the Apache Server variables. First of all, these are variables representing client request header fields.
Such as access agent/cookie/range/thirdplatform header, we can use the $http_user_agent, $http_cookie, $http_range.
proxy_set_header Range $http_range;
proxy_set_header Host $http_host;
proxy_set_header Thirdplatform $http_thirdplatform;

In Lua code：
access host header:  ngx.var.server_name.

**Comment by abrahack** [comment]
Hi @GumpSun @zhuizhuhaomeng ,

Well none of your suggestions worked .

Apparently you can't access `ngx.var.*`, in the `ssl_certificate_by_lua_block` .

@GumpSun thanks again for the code, it works perfectly now .

**Comment by zhuizhuhaomeng** [comment]
if you want to access the server name in ssl_certificate_by_lua_block .
you should use ssl.server_name() which @GumpSun  has provide above
```
local ssl = require "ngx.ssl"
ssl.clear_certs()
local server_name = ssl.server_name()
```
