### ISSUE TITLE
The resource app.js was preloaded but not used within a few seconds from the window's load event with body_filter_by_lua_block

### ISSUE THREAD

**Issue by dangjinghao** [openresty/lua-nginx-module#2013]
I am trying to replace some strings to insert javascript when using `body_filter_by_lua_block` in my vue3 site.
this is my code from https://github.com/openresty/lua-nginx-module/issues/1813#issuecomment-745054129
```       
location / {
            proxy_pass http://127.0.0.1:8080/;
            default_type text/html;
            body_filter_by_lua_block  {
                ngx.ctx.buffered = (ngx.ctx.buffered or "") .. ngx.arg[1]
                if ngx.arg[2] then
                    ngx.arg[1] = ngx.ctx.buffered:gsub("<body>","<body><script>alert('alert')</script>")
                else
                    ngx.arg[1] = ''
                end
            } 

           }
```
The insert script alerted but my vue3 web can``t work as usual.The browser console warned that `The resource http://127.0.0.1/js/app.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate 'as' value and it is preloaded intentionally.`
I`ve tested and passed in express with http-proxy-middleware .So maybe it is not vue3 problem.  
There are no obvious error in error.log.
By the way,it works when I just replace strings.

openresty version: openresty-1.19.9.1-win64 from https://openresty.org/en/download.html

**Comment by GumpSun** [comment]
Obviously, you have modified the content of the response body.This body's length changed.
Therefore, you have to modify the ngx.header["content-length"] = nil in the header_filter phase.

**Comment by dangjinghao** [comment]
> Obviously, you have modified the content of the response body.This body's length changed. Therefore, you have to modify the ngx.header["content-length"] = nil in the header_filter phase.

it works after i modified the content-length ,thank you!
