### ISSUE TITLE
ARM64 compatibility on Apple Silicon

### ISSUE THREAD

**Issue by dndx** [openresty/lua-nginx-module#2030]
Hello @agentzh, @zhuizhuhaomeng,

We recently discovered an issue with running OpenResty under Apple Silicon. Certain FFI functions such as the [shdicit FFI functions](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L1308-L1312) has very long argument list. On LuaJIT, there is a [known issue](https://github.com/LuaJIT/LuaJIT/issues/205#issuecomment-236426398) that passing non 64-bit value after the 8th argument on Apple ARM64 devices doesn't work due to ABI incompatibility and there appears to be no plan on fixing it soon.

Instead, what we have been doing is to use C struct to pass the argument of shdict FFI calls. These `cdata` can be preallocated by lua-resty-core at module level and does not need to be recreated for each operation. Therefore, the performance penalty should be negligible.

See:
* https://github.com/Kong/lua-kong-nginx-module/pull/38
* https://github.com/Kong/kong-build-tools/pull/447

We would like to do some cleanup and contribute these changes back to OpenResty so that OpenResty will work well on Apple Silicon Macs. Does this sounds good to you?

**Comment by agentzh** [comment]
We can use a different ABI for apple silicon specifically to work around this particular arch's restrictions. But we don't want to change the ABI for other architectures.

**Comment by dndx** [comment]
@agentzh Thanks for your reply!

Do we consider the FFI API shdict part of the public interface of OpenResty? I don't see much obvious benefit to keep a different ABI for other arch but I could be missing something here.

The reason I am double checking is that if we keep a different ABI for different arch then the `shdict.lua` file inside lua-resty-core will be much longer than currently is, not sure if that is desireable.

**Comment by dndx** [comment]
Ping @agentzh ^

We should like to contribute the change, but would like to understand a bit more on the benefit of keeping the old style API for our own education.

**Comment by dndx** [comment]
Thanks @agentzh for the explanations, we will arrange for the work on contributing this change to OpenResty.

**Comment by bungle** [comment]
> And how many users actually use Apple Silicon for production users using OpenResty?

A lot of developers do.

**Comment by samhaque** [comment]
@dndx it still doesn't work even in the new release of openresty on brew

**Comment by taf2** [comment]
We are also seeing this continue to fail on m2 macs with latest brew

**Comment by Fabriceli** [comment]
Me too, it still fail on M2 mac

**Comment by zhuizhuhaomeng** [comment]
http://openresty.org/en/ann-1021004002rc1.html
please try the 1.21.4.2rc1

**Comment by cycomachead** [comment]
thanks everyone! 1.21.4.2rc1 is working for me. I installed via `brew`, and chose to manually edit the brewfile. `brew edit openresty` and updated the version and sha256. 

👍 on the patches.
