### ISSUE TITLE
Why return `1` instead of `true` for success?

### ISSUE THREAD

**Issue by LoganDark** [openresty/lua-nginx-module#2038]
In the README, tons of functions are documented as returning, specifically, the number constant `1` on success, rather than `true`. This is incredibly weird for Lua APIs - usually `true` is used as the success value, even if errors always use `nil` instead (although really should be `false` like `pcall`).

It's probably too late to change now, since there is existing code likely depending on it, but why was this decision made back when the module was first being designed? Just carring C conventions into Lua bindings or?

**Comment by LoganDark** [comment]
> Could you give some examples?

`pcall`, `coroutine.resume`.

Generally when it's either success or failure, true/false is used. When it's either a returned object or nothing, it's that object or nil. But it's never something else (1) or false, unless the 1 is meaningful in some way.

**Comment by dndx** [comment]
Not sure what you means, but I did some quick test and don't see `1` returned:

```
$ resty -e 'print(pcall(function()return "hello"end))'
truehello
```

`pcall` is not even an OpenResty API, it is provided by the Lua runtime.

**Comment by LoganDark** [comment]
> Not sure what you means, but I did some quick test and don't see `1` returned:
> 
> ```
> $ resty -e 'print(pcall(function()return "hello"end))'
> truehello
> ```
> 
> `pcall` is not even an OpenResty API, it is provided by the Lua runtime.

Oh - give examples of functions that return `1` instead of `true`? Sure, I recently completed some typings so I can give a short list:

`ngx.print`, `ngx.say`, `ngx.flush`, `ngx.eof`, `udpsock:setpeername`, `udpsock:send`, `udpsock:close`, `tcpsock:connect`, `tcpsock:setclientcert`, `tcpsock:close`, `tcpsock:setkeepalive`, `ngx.on_abort`

**Comment by dndx** [comment]
Okay, that is fair. For some of the older functions, returning `1` is probably historical, and we can not really change it at this point. We do use `true` for newer functions after some point in time.

Realistically it should not make much difference. Usually people write:

```
local res, err = ngx.print("foo")
if not res then
    ...blah
end
```

anyway. As a matter of fact I have not even noticed the distinction between `true` and `1` return values until now.

**Comment by LoganDark** [comment]
> As a matter of fact I have not even noticed the distinction between `true` and `1` return values until now.

It comes up when making typings. Instead of `boolean, string?` I have `1 | (nil, string)`.

**Comment by LoganDark** [comment]
Closing because this cannot be changed for historical reasons (and future APIs will use the correct convention, if I understand correctly)
