### ISSUE TITLE
Atomic "lcontains" or "lfind" method for shared dict lists

### ISSUE THREAD

**Issue by LoganDark** [openresty/lua-nginx-module#2040]
Right now, it's not feasible to use a shared dict list for i.e. temporarily-banned IP addresses, because there's no way to easily/efficiently/atomically check if a list contains a certain value.

It would be really useful if a function were introduced that allowed me to check the presence of a value in a list.

**Comment by zhuizhuhaomeng** [comment]
why use a list to check the existence of the IP?

**Comment by LoganDark** [comment]
> why use a list to check the existence of the IP?

Because list insertions/removals are atomic whereas updating a string is not.

**Comment by LoganDark** [comment]
Maybe I'm not using lists for their intended purpose. Perhaps there should be "set functions" that deal with stuff like this. As in, a set of items that are all unique, and can be inserted/removed/checked by value, rather than by index.

**Comment by zhuizhuhaomeng** [comment]
does use the IP use key of the shared dict  meet your need?

**Comment by LoganDark** [comment]
> does use the IP use key of the shared dict meet your need?

oh. Yes. I'm an idiot lmao. A set is just a map where all the values are `true`
