### ISSUE TITLE
High CPU usage of  lj_BC_TGETS

### ISSUE THREAD

**Issue by LoremipsumSharp** [openresty/lua-nginx-module#2054]
## Version 
Software | Version
---|---
openresty | 1.19.9.1

## Problem

We currently using `Kong` as API Gateway, to route the traffic to our backend service.
About 3000 routes is maintained and most of them is `regex route`.

Recently, we experienced a significant increment of CPU usage after we  several API connected to `Kong`

In order to diagnostic the issue, we use `flame graph` to sample the CPU usage when alarm was triggered, here is the flame graph:
![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/img/temp4.svg)

From the graph above, I suspected that the `lj_BC_TGETS`  was the underlying cause of problem ,however ,there is little information except `lj_BC_TGETS`  ,moreover, we don't know much about `lj_BC_TGETS` behind the screen,  any ideas?

**Comment by zhuizhuhaomeng** [comment]
Your C backtrace is incomplete. Needs [OpenResty XRay](https://openresty.com/en/xray/) to get the full backtraces and flame graphs. OpenResty XRay can also get Lua-land flame graphs, which will be more helpful for profiling and analyzing this issue. Probably just bad Lua code on your side.

**Comment by fairyqb** [comment]
https://github.com/openresty/luajit2/issues/175

Similar problems
