### ISSUE TITLE
nginx 1.23.0 and ngx_http_lua_headers_in.c   cookies -> cookie

### ISSUE THREAD

**Issue by eilandert** [openresty/lua-nginx-module#2062]
/build/nginx-1.23.0/debian/modules/http-lua/src/ngx_http_lua_headers_in.c:156:50: error: 'ngx_http_headers_in_t' has no member named 'cookies'; did you mean 'cookie'?
  156 |                  offsetof(ngx_http_headers_in_t, cookies),

cookies field name just renamed to cookie, according to https://github.com/nginx/nginx/commit/3aef1d693f3cc431563a7e6a6aba6a34e5290f03 .

Possible fix:
https://github.com/openresty/headers-more-nginx-module/pull/134/commits/57ef661154ba32d0b072d640038754b348808e2e

**Comment by kn007** [comment]
same issue here

**Comment by Schamschula** [comment]
The above fix works for me: https://github.com/macports/macports-ports/commit/f8fb46b9a22f1364041832f81d606abb8b218337#diff-de70025eb9c2bca8b34947d16593e77fdab8e58b1a19f997d311012b983de660

**Comment by Mauraza** [comment]
Hi!, When will you create a new tag with this change?

**Comment by jjeejj** [comment]
same problem now
lua-nginx-module-0.10.22/src/ngx_http_lua_headers_in.c:156:18: error: no member named 'cookies' in ''
offsetof(ngx_http_headers_in_t, cookies)

**Comment by zhuizhuhaomeng** [comment]
@jjeejj @Mauraza you need to use the lates master.
create a new tag  also require update the lua-resty-core.

**Comment by maxbear1988** [comment]
@zhuizhuhaomeng Can i solve this issue by replying MR code to my owner  lua-nginx-module 0.10.15 code

**Comment by zhuizhuhaomeng** [comment]
you can clone to your own repo and create a new tag.

**Comment by zhuizhuhaomeng** [comment]
both the lua-resty-core and lua-nginx-module.
