### ISSUE TITLE
Apple Silicon环境下lua_shared_dict的set问题

### ISSUE THREAD

**Issue by yahuaChen** [openresty/lua-nginx-module#2066]
Mac Apple Silicon M1
openresty 1.21.4.1_1

使用lua_shared_dict报错，无法set数据

[error] 21691#261787: *1 lua entry thread aborted: runtime error: ...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:248: NYI: cannot call this C function (yet)
stack traceback:
coroutine 0:
	[C]: in function 'ngx_lua_ffi_shdict_store'
	...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:248: in function 'set'
	...y/1.21.4.1_1/nginx/conf/lua/test/util/ngx_shard_test.lua:5: in main chunk, client: 127.0.0.1, server: , request: "GET /test HTTP/1.1", host: "127.0.0.1:8090"

**Comment by spacewander** [comment]
See https://github.com/openresty/lua-nginx-module/pull/2037
