### ISSUE TITLE
ngx.req.get_headers issue

### ISSUE THREAD

**Issue by Vittly** [openresty/lua-nginx-module#207]
Hello!
the code: ngx.req.get_headers()['Accept-Encoding']
sometimes it returns
 table {'gzip, deflate', 'gzip, deflate'}
and sometimes
 string 'gzip, deflate' - why?

It is not good for code like "if enc:match('gzip') then ...". I also whould write "if type(enc) == 'table' then enc = table.concat(enc,',')"

**Comment by jney** [comment]
hi @agentzh, is it fixed ? i've got a behaviour making me wondered it is not.

**Comment by agentzh** [comment]
@jney For security filters built upon ngx_lua, it's reasonable to obtain all the instances of a single builtin header that disallow multiple instances for scanning purposes. You can always filter them out in your own Lua code anyway.
