### ISSUE TITLE
Get runtime error with latest version luajit + lua-nginx-module

### ISSUE THREAD

**Issue by vsbc2010** [openresty/lua-nginx-module#2106]
nginx -c /etc/nginx/nginx.conf

2022/10/16 08:55:08 [alert] 2968#0: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenRestyrelease from https://openresty.org/en/download.html (reason: /usr/lib/lua/resty/core/var.lua:44: /usr/lib/libluajit-5.1.so.2: undefined symbol: ngx_http_lua_ffi_var_get) in /etc/nginx/lighttpd.conf:71

Build with
devel-kit -- git b4642d6ca01011bd8cd30b253f5c3872b384fd21
lua-nginx -- git 4bbb57aa4a6995bd3efaf35c01e826de6f3cdf3a
luajit2 -- git 8384278b14988390cf030b787537aa916a9709bb
Nginx -- https://nginx.org/download/nginx-1.23.1.tar.gz

LUAJIT_INC=/usr/include/luajit-2.1
LUAJIT_LIB=/usr/lib

**Comment by vsbc2010** [comment]
Solved

TARGET_CFLAGS += -fvisibility=hidden -ffunction-sections -fdata-sections
TARGET_LDFLAGS += -Wl,--gc-sections

**Comment by yxing-xyz** [comment]
I used the -static parameter and the same problem occurred.

**Comment by yxing-xyz** [comment]
> ```
> I used the -static parameter and the same problem occurred.
> ```

After testing, all static links cannot be done, because all static links will cause the dynamic symbol table to be removed, causing Lua to not be able to find the symbol.

**Comment by lengocthuong15** [comment]
Hi team, sorry for asking but could I know how to fix it? I am facing the same issue but in Windows
