### ISSUE TITLE
Inconsistent Behavior Under High Load for ngx.var.host

### ISSUE THREAD

**Issue by urifoox** [openresty/lua-nginx-module#2114]
Hello,

Apologize if this is not the correct place but I am running into an odd issue I cannot resolve.

In production we currently run

nginx version: openresty/1.13.6.2
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled

We are upgrading to

nginx version: openresty/1.21.4.1
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled

We have a simple LUA script that connects to a Redis Server to look up data and return it. This has been working fine for years in Production.  Under the new version, it will work 99+% of the time but every once in a while it will return another hostname. It is as if under high load the ngx.var.host gets overwritten between threads.

The code, simplified, is:

local zoeyhost = ngx.var.host
local ok, err = red:connect("xxx", 6379)
zoeyparent = red:hmget(zoeyhost, "parent")
internalip = red:hmget(zoeyparent[1], "hostip", "internalip", "maintenance")
ngx.log(ngx.ERR, zoeyhost, "|", zoeyparent[1], "|", internalip[1], "|", internalip[2], "|", ngx.var.host)

for i in {1..1000}; do curl  https://domain1.com/foo.php; echo ""; done
for i in {1..1000}; do curl  https://domain2.com/foo.php; echo ""; done

In the domain1 or domain2 output you will see every once in a while the other hostname

domain1.com  - 192.168.1.89
domain1.com  - 192.168.1.89
domain1.com  - 192.168.1.89
domain2.com  - 192.168.1.89
domain1.com  - 192.168.1.89
domain1.com  - 192.168.1.89
domain1.com  - 192.168.1.89

In the log file I will see

domain1.com|domain1.com|172.xx.xx.104|192.168.1.89|domain1.com
domain1.com|domain1.com|172.xx.xx.104|192.168.1.89|domain1.com
domain1.com|domain2.com|172.xx.xx.104|192.168.1.89|domain1.com
domain1.com|domain1.com|172.xx.xx.104|192.168.1.89|domain1.com
domain1.com|domain1.com|172.xx.xx.104|192.168.1.89|domain1.com

I am unable to figure out why this is happening. For some reason the only variable that is always incorrect is zoeyparent[1] - even if I replace it with var.ngx.host it is still incorrect! 

Do I need to implement a lock() or some other mechanism to prevent the ngx.var.host from being overwritten between threads?

What is odd is that the other data hostip/internalip are correct so it must be looking it up correctly but the output of zoeyparent[1] is incorrect. 

Any insight/help is much appreciated.

**Comment by zhuizhuhaomeng** [comment]
There is a bug in the luajit, I think you can recompile the nginx with the latest luajit.
Not sure if it is related.

**Comment by urifoox** [comment]
I rebuilt Openresty (after much trial/error) with lua-nginx-module-0.10.22 but I have the same exact problem. 

Any other suggestions?

**Comment by urifoox** [comment]
Okay, looks like I got it to work - not sure if it was recompiling with the latest version but I added more `local` declarations to variables and it seems to have resolved the issue.

**Comment by zhuizhuhaomeng** [comment]
If you do not use the local variable, it is a global variable.
So I think it is the root cause of the problem
