### ISSUE TITLE
Server block config per worker

### ISSUE THREAD

**Issue by psvz** [openresty/lua-nginx-module#2120]
I implement one lockless architecture and have now spent a lot of time searching for a way to create a _server_ (in terms of nginx.conf) per worker. I want a handler of a unix socket to be a part of the nginx main event loop. Because each handler serves its dedicated section of a file, to make it mutex-free, only one worker should own that socket. It's _ala_ server-block in nginx.conf per worker.

I end up writing a separate piece of software to listen on those unix sockets. That effectively doubles number of threads (N nginx workers + N my sockets/handlers). Could anyone please point me to a direction of better implementation of what I try to achieve?

Low bows and many thanks.

**Comment by dndx** [comment]
You can take a look at https://github.com/Kong/lua-resty-events/tree/main/src for inspiration. This module allows disabling accept events of specific server block in workers that should not be accepting on that server. Maybe it will allow you achieve what you want.

**Comment by psvz** [comment]
Thank you.

**Comment by psvz** [comment]
Yes… no. I ended up with consistent hashing inside Lua to select unix socket, and then doing my lock-less stuff on my own. Further complication of nginx land is reckless.

**Comment by attenuation** [comment]
Which do you mean in consistent hashing inside Lua? when Nginx worker accept connection, this stream packet will dispatch to this worker, if you drop it in one worker, another worker can not accept again. In my understanding, chash can not resolve it.

**Comment by psvz** [comment]
You are right. But what if you'd like a worker doing something other than accepting connections (in Lua). Here is what/how I solved, and what didn't work: https://github.com/psvz/hashtable-in-file (the last section of Readme).
