### ISSUE TITLE
Cosocket workflow and apparent race

### ISSUE THREAD

**Issue by psvz** [openresty/lua-nginx-module#2124]
I would like to use **ngx.socket.udp** api, and I am confused with _"synchronous and non-blocking"_ promise.

Suppose I am doing in my content_by_lua block:

```
udpsock:setpeername
udpsock:send
udpsock:receive
```
So, I query my external server and I am happy that this is synchronous. As nginx worker is a single thread, **non-blocking** promise implies the worker can work on other requests pending on its event loop. But what if another request also needs my external server and calls _udpsock:setpeername_ right after _udpsock:send_ above??? Connection from my original request dies as per the docs:

"Calling this method on an already connected socket object will cause the original connection to be closed first."

Could someone please clarify how does it actually work in that case - otherwise it feels like very race-prone?

Thank you @agentzh

**Comment by psvz** [comment]
Or does nginx autobind with (1 << 20) possible source addresses?

**Comment by zhuizhuhaomeng** [comment]
did you share the socket across different request ?

**Comment by psvz** [comment]
Hi @zhuizhuhaomeng 

Not intentionally. Every incoming http request is handled by content_by_lua block, where subrequest via udp:sock(unix:..) takes place.

**Comment by zhuizhuhaomeng** [comment]
I think you can create two udp socket
