### ISSUE TITLE
About QUIC support

### ISSUE THREAD

**Issue by oowl** [openresty/lua-nginx-module#2191]
Hi, Openresty guys. After multiple delays, Nginx finally merged the QUIC branch into the mainline code today. So I would like to ask if Openresty has any plans to improve the support for Nginx's new feature - QUIC.  
https://github.com/nginx/nginx/commit/4b0266174814e6cf60a275321121dbaab084ee64#diff-4df230a19122385cb07cf48917f7316922bfa90db793f0d13e05a2be030060b8

**Comment by oowl** [comment]
@zhuizhuhaomeng

**Comment by oowl** [comment]
New Nginx has been released.

Changes with nginx 1.25.0                                        23 May 2023
                    
* Feature: experimental HTTP/3 support.

https://nginx.org/en/CHANGES

**Comment by kn007** [comment]
also please support PCRE2 https://github.com/openresty/lua-nginx-module/issues/1984

**Comment by splitice** [comment]
Duplicate of https://github.com/openresty/openresty/issues/741

**Comment by monkeyDluffy6017** [comment]
I've tried picking the quic-related changes to openresty and there are very few conflicts, so you can try it yourselves if you need to

**Comment by oowl** [comment]
Thanks @swananan https://github.com/openresty/openresty/pull/920
