### ISSUE TITLE
cannot resume non-suspended coroutine

### ISSUE THREAD

**Issue by splitice** [openresty/lua-nginx-module#2193]
Its rare but sometimes I see the following error when executing some monitoring code.

Error:
```
2023/05/30 10:35:49 [error] 931#931: *592067 lua entry thread aborted: runtime error: cannot resume non-suspended coroutine
stack traceback:
coroutine 0:, client: 127.0.0.1, server: , request: "GET /shminfo HTTP/1.1", host: "127.0.0.1:78"
```

Code:
```
for key,value in pairs(ngx.shared) do
    ngx.say(key.."|"..tostring(value:free_space()).."|"..tostring(value:capacity()))
end
```

This is with the latest luajit2 and lua-nginx-module from c8597eda0c3181f15ff58dedf3fb41f4259146fb I didnt see this on an earlier luajit2 version so I'm currently thinking it may be a regression with luajit2?

**Comment by splitice** [comment]
@oowl I have. Hit that with enough requests in a content_by_lua scope and the issue occurs.

I'm currently working on testing older luajit2 as its the main thing I've changed.

**Comment by zhuizhuhaomeng** [comment]
@oowl  If it is reproducible, you can disable the jit, and then try again.

**Comment by splitice** [comment]
Issue has been found as https://github.com/tokers/lua-io-nginx-module/issues/9

Uses memory after free in rare cases.

Sorry will close.
