### ISSUE TITLE
Description on `backlog` of cosocket connection pool is inaccurate?

### ISSUE THREAD

**Issue by outsinre** [openresty/lua-nginx-module#2205]
From the [official document](https://github.com/openresty/lua-nginx-module#tcpsockconnect), I read the following sentences:

>`backlog` if specified, this module will limit the total number of opened connections for this pool.

>No more connections than `pool_size` can be opened for this pool at any time.

Seems both `backlog` and `pool_size` limit the number of opened connections? If it is the case, why should we define the `backlog` parameter?

What does *opened connections* mean? Refer to established connections or connection handshake not completed yet?

Then I read another sentence:

>If the connection pool is full, subsequent connect operations will be queued into a queue equal to this option's value ...

If I am right, if the connection pool is full, shouldn't new connection operations just pick one alive connection from the pool?

Bit confused.

**Comment by oowl** [comment]
`backlog` is more like a wait queue size for `connection pool`,  Openresty will limit the number of opened connections.   if the connection pool is empty, the new wait gets connection function will be queued in backlog wait for the new connection from the connection pool.
