### ISSUE TITLE
Potential Context Pollution Issue with ngx.ctx in OpenResty

### ISSUE THREAD

**Issue by VanillaHeaven** [openresty/lua-nginx-module#2214]
Hello!
I have identified a potential issue with ngx.ctx in OpenResty, which seems to be causing context pollution when using the ngx.ctx interface in the ssl_*_by_lua_block phase, and it leads to different requests within the a keep-alive connection sharing the same ngx.ctx.

The version of openresty is openresty-1.21.4.2-1.el7.x86_64.
To reproduce the issue, you can follow these steps:

1. This is my nginx.conf. In the ssl_certificate_by_lua_block phase, I initialize ngx.ctx.api_ctx as a table and reference it in the rewrite_by_lua_block and log_by_lua_block phase. Then, I check if ngx.ctx.api_ctx.is_pollution is empty. Under normal circumstances, this value should be empty, and if it is, I assign it the value of ngx.var.request_id. Otherwise, if context pollution occurs, I print its value.

```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    resolver 223.5.5.5 114.114.114.114 8.8.8.8 1.1.1.1;

    ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES256:EECDH+AES128:RSA+AES256:RSA+AES128:EECDH+3DES:RSA+3DES:!MD5:!AES256-GCM-SHA384:!AES128-GCM-SHA256:!DES-CBC3-SHA:!ECDHE-RSA-DES-CBC3-SHA";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 10m;
    ssl_certificate /usr/local/openresty/nginx/cert/dummy.cer;
    ssl_certificate_key /usr/local/openresty/nginx/cert/dummy.key;
    ssl_session_tickets on;
    ssl_session_ticket_key /usr/local/openresty/nginx/cert/ticket.key;

    server {
        listen 80;
        listen 443 ssl deferred http2 reuseport;
        ssl_client_hello_by_lua_block {
        }

        ssl_certificate_by_lua_block {
            local api_ctx = ngx.ctx.api_ctx
            if not api_ctx then
                api_ctx = {}
                ngx.ctx.api_ctx = api_ctx
            end
        }

        location / {
            rewrite_by_lua_block {
                local api_ctx = ngx.ctx.api_ctx
                if not api_ctx then
                    api_ctx = {}
                    ngx.ctx.api_ctx = api_ctx
                end

            }
            access_by_lua_block {
            }
            header_filter_by_lua_block {
            }
            log_by_lua_block {
                local api_ctx = ngx.ctx.api_ctx
                if not api_ctx then
                    api_ctx = {}
                    ngx.ctx.api_ctx = api_ctx
                end
                if api_ctx.is_pollution then
                    ngx.log(ngx.ERR, "[TEST] ctx pollution ", api_ctx.is_pollution)
                else
                    api_ctx.is_pollution = ngx.var.request_id
                    ngx.log(ngx.ERR, "[TEST] set ctx ", api_ctx.is_pollution)
                end
            }
            root html;
        }
    }
}
```

2. Access the server using HTTPS and enable connection reuse. I use wrk to simulate this scenario:
`./wrk -t1 -c1 -d 2s "https://safe.taobao.com/index.html"`

3. This is the output in the error.log. In the mentioned test scenario, subsequent requests show ngx.ctx.api_ctx.is_pollution with a non-empty value, which is the ngx.var.request_id from the first request.
![image](https://github.com/openresty/lua-nginx-module/assets/32634416/d5362220-03ad-474d-8543-fd9c10e8c781)

Currently, I have resolved the issue by reverting the commit: 218af5ee90adeffc8d2cd6eb82d3dc908f9f3f6d. This prevents sharing the context between the SSL phase and subsequent phases. However, I'm uncertain if this is a bug or expected behavior. I would appreciate your feedback on this matter, thanks.

**Comment by spacewander** [comment]
```
        ssl_certificate_by_lua_block {
            local api_ctx = ngx.ctx.api_ctx
            if not api_ctx then
                api_ctx = {}
                ngx.ctx.api_ctx = api_ctx
            end
        }
```

```
else
                    api_ctx.is_pollution = ngx.var.request_id
                    ngx.log(ngx.ERR, "[TEST] set ctx ", api_ctx.is_pollution)
                end
```

The api_ctx here is actually set in the SSL phase's ngx.ctx, not the HTTP one.

**Comment by VanillaHeaven** [comment]
Thank you for your response.
So, does this mean that in a keep-alive connection, the SSL ngx.ctx context won't be reset after a request is completed, right?

**Comment by spacewander** [comment]
Yes

**Comment by VanillaHeaven** [comment]
Thank you very much.
