### ISSUE TITLE
Question about file write buffer and data order.

### ISSUE THREAD

**Issue by moweonlee** [openresty/lua-nginx-module#2223]
I'd like to ask whether if it is possible that written data could be mixed in race condition.

We have 50 nginx processes running in a container and Lua module record Web log into file.

But I guess some data in large requests  are mixed in single line.

The reason that I think so is that my Lua code always write data with trailing new line.

But I have obseved that two access A,b  are written in a single line like below.

```
Former Part of log data in A without new line+Complete line of Log B with new line.

```

```

                                local listLog = {}
                                table.insert( listLog, concatNonStringValue( "Timestamp", ts ) )

                                ...
                                local nlog_access = "{" .. table.concat( listLog, "," )  .. "}"
                                -- set log to ngx variable
                                ngx.var.nlog_access = nlog_access
                                local logfile = io.open("/home1/irteam/log-server/logs/nlog_access.log", "a+")
                                if ( logfile ~= nill ) then
                                        logfile:write( nlog_access .. "\n")
                                        logfile:close()
                                end
```

Do I need to set some buffering policy like this ?

https://www.gammon.com.au/scripts/doc.php?lua=f:setvbuf

Thank you in advance.

**Comment by swananan** [comment]
Hello, in Lua, the default mode for I/O operations is full buffering. This means that Lua's I/O will call the syscall `write` only when the Lua I/O object accumulates enough data. While the syscall `write` is indeed thread-safe, different Lua I/O objects within various Nginx worker threads may call `write` with multiple log messages, and the last message might end up being only partially written.

In my opinion, resolving this issue could involve changing the I/O mode to either no buffering or line buffering. Alternatively, we could consider triggering an io.flush before the Lua I/O object accumulates enough data to call `write`. This approach would help reduce the number of syscall `write` calls. I hope this can help you.

**Comment by moweonlee** [comment]
@swananan .

Thank you so much.
