### ISSUE TITLE
set-cookie only take effect once ?

### ISSUE THREAD

**Issue by busishe** [openresty/lua-nginx-module#2229]
i use both ngx.header['Set-Cookie'] and ngx.header.set_cookie to set a cookie to requests.Like:

ngx.header.set_cookie = 'cookie1=value1;'
--some other processing
 ngx.header.set_cookie = 'cookie2=value2;'

Found that only the last time operation took effect.

使用中发现，无论是使用ngx.header['Set-Cookie']方法还是ngx.header.set_cookie方式来setcookie，仅最后一次set生效。对于比较复杂的请求处理，需要在不同阶段决定是否set cookie时，有没有可行方案呢？

**Comment by lynch1981** [comment]
Multi-value headers can be set this way:
ngx.header['Set-Cookie'] = {'a=32; path=/', 'b=4; path=/'}
