### ISSUE TITLE
ngx.location.capture_multi request hang when body is nil

### ISSUE THREAD

**Issue by MuChenMuXuan** [openresty/lua-nginx-module#2234]
nginx version: openresty/1.21.4.2

```
server {
    listen 8005;
    server_name localhost;

    location /backend {
        internal;
        proxy_connect_timeout 1;
        proxy_read_timeout 5;
        proxy_send_timeout 5;
        proxy_pass https://www.baidu.com;
    }

    location / {
        content_by_lua_block {
            local json = require "cjson"
            local requests ={};
            local body = "";
            -- local body = nil;
            requests[1] = {"/backend", {method=ngx.HTTP_POST, body=body, copy_all_vars=true }}
            res1, res2, res3 = ngx.location.capture_multi(requests);
            ngx.say(json.encode(res1));        
        }
    }
}
```

When the value of the parameter body is nil, ngx.location.capture_multi will block until timeout (in this case, 5s), which is very confusing when debugging this feature.
As a comparison, when the value of the parameter body is an empty string, ngx.location.capture_multi will return soon.

**Expected effect:** 
When the value of the parameter body is nil, openrest can provide error or exception prompts instead of constantly blocking.

**Comment by lynch1981** [comment]
body is allowed to be nil.
I tried to reproduce this issue, but there is no difference between empty string and nil.
can you attach the output of curl?

curl -s http://127.0.0.1:8005/

**Comment by MuChenMuXuan** [comment]
@lynch1981 
Thank you for your reply.
There was an omission in my previous description of the problem. Only when a post request is used and the post body is not empty, will the exception be triggered.

```
curl -s  'http://127.0.0.1:8005' -d 'xxx'
```

<img width="989" alt="image" src="https://github.com/openresty/lua-nginx-module/assets/3232275/84cadeae-127b-480d-b2d1-e5b43ae2d1a4">

**Comment by lynch1981** [comment]
When you call ngx.location.capture_multi you set body to nil, which means no request body is required when initializing the subrequest. Therefore, the request body carried by curl -d "xxx" will not be passed to the backend. But when you set the -d parameter, the request header will contain "Content-Length: 3", which requires the backend server to receive the request body, and the server waits until it times out.

**Comment by MuChenMuXuan** [comment]
Okay, I understand a bit.

I understand the mechanism you described. And:
1. What is the way to dump the request information of subrequest?
2. Besides this mechanism of "the server waits until it times out", can it immediately fail and report an error to the user?

**Comment by lynch1981** [comment]
1. you can use wireshark to capture the packets, but the backend uses http protocol, not https
2. No, you told the backend server that there will be a three-byte request body, so the backend server can only wait
