### ISSUE TITLE
Is there any easy way to find correspondence of version between lua-nginx-module and its dependencies?

### ISSUE THREAD

**Issue by yangzhaofeng** [openresty/lua-nginx-module#2235]
For example, lua-nginx-module v0.10.24 requires lua-resty-core v0.1.26, which also requires lua-resty-lrucache.

I have not found an easy way but looking at lua-resty-core/lib/resty/core/base.lua every time to get the correspondence of the version between lua-nginx-module and lua-resty-core. This means I need to find it out and modify a bunch of numbers of them manually everytime when I am going to update lua-nginx-module. 

Is it possible to, for example, use submodules in these repositories so it can be easier for developers to build this module, especially with scripts?

**Comment by zhuizhuhaomeng** [comment]
Download the source code from https://openresty.org/en/download.html, and then decompress the tarball.
You can find the versions of the dependencies.
