### ISSUE TITLE
failed build with clang 

### ISSUE THREAD

**Issue by KnightBlood** [openresty/lua-nginx-module#2238]
/root/work/module/lua-nginx-module/src/ngx_http_lua_worker_thread.c
/root/work/module/lua-nginx-module/src/ngx_http_lua_worker_thread.c:454:57: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
    worker_thread_ctx->is_abort                         = 1;
                                                        ^ ~
1 error generated.
make[1]: *** [objs/Makefile:3103：objs/addon/src/ngx_http_lua_worker_thread.o] error 1

![image](https://github.com/openresty/lua-nginx-module/assets/14256591/3ffdd72b-b3b3-4997-af8f-586ad32e4f40)

**Comment by zhuizhuhaomeng** [comment]
Please update the master branch code.
