### ISSUE TITLE
[bug]attempt to index global 'sw_tracer ' (a nil value)

### ISSUE THREAD

**Issue by jxplus** [openresty/lua-nginx-module#2258]
1) init_by_lua_block, a init alias a require [sw_tracer = require("sw.tracer")] 
2) rewrite_by_lua, use the sw_tracer, then log error of title.

[error] 110733#0: *23 lua entry thread aborted: runtime error: rewrite_by_lua(xxx.com:8):2: attempt to index global 'sw_tracer' (a nil value)

version: 
nginx v1.22.0
lua-nginx-module, 
             when v0.10.15 is ok, 
             when v0.10.20 is error.
want to no why, and how to fix it.

**Comment by lynch1981** [comment]
it looks incredible. Can you give a minimal complete configuration to reproduce the issue?

**Comment by zhuizhuhaomeng** [comment]
did you configure the `lua_code_cache off`?

**Comment by jxplus** [comment]
> it looks incredible. Can you give a minimal complete configuration to reproduce the issue?

configuration like this:

`http {

    lua_package_path "/usr/local/lua_core/lib/lua/?.lua;;";

    init_worker_by_lua_block {
        sw_tracer = require("skywalking.tracer")
    }
    
    
    server {
        listen  80;
        server_name msm-test.mysteeltech.com;


        rewrite_by_lua_block {
            sw_tracer:start("upstreams")
        }

        body_filter_by_lua_block {
            if ngx.arg[2] then
                sw_tracer:finish()
            end
        }
        log_by_lua_block {
            sw_tracer:prepareForReport()
        } 


        location / {
            root /export/dist;
            index index.html;
            try_files $uri $uri/ /index.html;
        } 

    }

}`

**Comment by jxplus** [comment]
I know the reason， thanks
