### ISSUE TITLE
ngx_http_lua_module with support of pcre2 

### ISSUE THREAD

**Issue by Pranali4796** [openresty/lua-nginx-module#2269]
we are trying to update our nginx from 1.20 to 1.24 or 1.25 with latest lua nginx. but facing issue in doing so .

Using the latest stable version
https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.25.tar.gz

I am using nginx : 
Nginx:
https://nginx.org/packages/mainline/rhel/8/SRPMS/nginx-1.25.3-1.el8.ngx.src.rpm

Luajit:
wget https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20231117.tar.gz

 Lua-nginx:
https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.25.tar.gz

njs version:
https://github.com/nginx/njs/archive/refs/tags/0.8.2.tar.gz

Currently getting error while starting nginx:
2023/12/18 05:30:57 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: pcre_malloc) in /etc/nginx/nginx.conf:21
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: pcre_malloc) in /etc/nginx/nginx.conf:21
[root@r7515-155v029 /]#

Is there any way to resolve this error?  ngx_http_lua_module.so looking for pcre while nginx 1.25.3 supports pcre2

**Comment by lynch1981** [comment]
The use of pcre or pcre2 is determined during the compile phase. If nginx defines the NGX_PCRE2 macro, then pcre2 will be used when compiling ngx_lua.

Can you please show the parameters of nginx configure command and its output

**Comment by Pranali4796** [comment]
Hello @lynch1981 
for nginx version: https://nginx.org/packages/mainline/rhel/8/SRPMS/nginx-1.25.3-1.el8.ngx.src.rpm
It uses pcre2 

%define WITH_CC_OPT $(echo %{optflags} $(pcre2-config --cflags)) -fPIC

%define BASE_CONFIGURE_ARGS $(echo "--prefix=%{_sysconfdir}/nginx --sbin-path=%{_sbindir}/nginx --modules-path=%{_libdir}/nginx/modules --conf-path=%{_sysconfdir}/nginx/nginx.conf --error-log-path=%{_localstatedir}/log/nginx/error.log --http-log-path=%{_localstatedir}/log/nginx/access.log --pid-path=%{_localstatedir}/run/nginx.pid --lock-path=%{_localstatedir}/run/nginx.lock --http-client-body-temp-path=%{_localstatedir}/cache/nginx/client_temp --http-proxy-temp-path=%{_localstatedir}/cache/nginx/proxy_temp --http-fastcgi-temp-path=%{_localstatedir}/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=%{_localstatedir}/cache/nginx/uwsgi_temp --http-scgi-temp-path=%{_localstatedir}/cache/nginx/scgi_temp --user=%{nginx_user} --group=%{nginx_group} --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module  --add-dynamic-module=%{_builddir}/lua-nginx-module --add-dynamic-module=%{_builddir}/njs/nginx")

**Comment by lynch1981** [comment]
can you show the output of nginx configure, like these
```
lynch@ngx-dev:~/git/t1/nginx-1.25.3$ ./configure
checking for OS
 + Linux 5.15.0-52-generic x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
checking for gcc -pipe switch ... found
```

**Comment by Pranali4796** [comment]
Is there any other way to get output?

**Comment by lynch1981** [comment]
I don't know any other way yet :)
I will try to reproduce this issue by building nginx via nginx.spec in the rpm package

**Comment by Pranali4796** [comment]
Yes i did it via nginx.spec. Created custom rpm with above mentioned module.

**Comment by lynch1981** [comment]
i found that v0.10.25.tar.gz did not support pcre2, so  you can try v0.10.26rc1.tar.gz.
[https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.26rc1.tar.gz]

**Comment by Pranali4796** [comment]
@lynch1981 tried that
ended up with error:
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /etc/nginx/nginx.conf:58
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:43
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:43
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:44
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:44
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:836
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:836
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:837
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:837
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1009
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1009
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1010
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1010
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1562
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1562
2023/12/18 09:08:27 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1563
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/infra.conf:1563
2023/12/18 09:08:27 [alert] 1#1: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file '/etc/nginx/webui/lua/callhome/resty/core.lua'
        no file '/etc/nginx/webui/lua/hostadmin-mfa/resty/core.lua'
        no file '/etc/nginx/webui/lua/common/resty/core.lua'
        no file '/etc/nginx/webui/lua/eca/resty/core.lua'
        no file '/etc/nginx/webui/lua/fips-compliance-check/resty/core.lua'
        no file '/etc/nginx/webui/lua/smtp/resty/core.lua'
        no file '/etc/nginx/webui/lua/smart-card/resty/core.lua'
        no file './resty/core.lua'
        no file '//share/luajit-2.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '//share/lua/5.1/resty/core.lua'
        no file '//share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '//lib/lua/5.1/res in /etc/nginx/nginx.conf:151
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file '/etc/nginx/webui/lua/callhome/resty/core.lua'
        no file '/etc/nginx/webui/lua/hostadmin-mfa/resty/core.lua'
        no file '/etc/nginx/webui/lua/common/resty/core.lua'
        no file '/etc/nginx/webui/lua/eca/resty/core.lua'
        no file '/etc/nginx/webui/lua/fips-compliance-check/resty/core.lua'
        no file '/etc/nginx/webui/lua/smtp/resty/core.lua'
        no file '/etc/nginx/webui/lua/smart-card/resty/core.lua'
        no file './resty/core.lua'
        no file '//share/luajit-2.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '//share/lua/5.1/resty/core.lua'
        no file '//share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '//lib/lua/5.1/res in /etc/nginx/nginx.conf:151



After digging more found out: 
but, 'resty.core' is now mandatorily required in 
https://github.com/openresty/lua-nginx-module/commit/60736e686ac5ca5af9a5bf118cb9bd4a9126cefc

as per error message : " ensure you are using an OpenResty release from https://openresty.org/en/download.html 
we must have complete openResty, "
Again 
if you refer installation guide: https://openresty.org/en/installation.html
Prerequisites
You should have perl 5.6.1+, libpcre, libssl installed into your system. For Linux, you should also ensure that ldconfig is in your PATH environment.
That is "pcre"

**Comment by Pranali4796** [comment]
@lynch1981  can I  use pcre macro during compile phase https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.25.tar.gz of nginx to avoid use of pcre2 library.
Based on you comment below.
"The use of pcre or pcre2 is determined during the compile phase. If nginx defines the NGX_PCRE2 macro, then pcre2 will be used when compiling ngx_lua."

**Comment by lynch1981** [comment]
> @lynch1981 can I use pcre macro during compile phase https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.25.tar.gz of nginx to avoid use of pcre2 library? Based on you comment below. "The use of pcre or pcre2 is determined during the compile phase. If nginx defines the NGX_PCRE2 macro, then pcre2 will be used when compiling ngx_lua."

ngx_lua uses the version of pcre used by nginx, so you can disable pcre2 when building nginx.

**Comment by lynch1981** [comment]
You can install lua-resty-core to /usr/local/share/lua/5.1
Just modify LUA_LIB_DIR and run make install

```
 45 lynch@ngx-dev:~/git/lua-resty-core-dev$ head Makefile
 46 OPENRESTY_PREFIX=/usr/local/openresty
 47
 48 LUA_VERSION := 5.1
 49 PREFIX ?=          /usr/local
 50 LUA_INCLUDE_DIR ?= $(PREFIX)/include
 51 LUA_LIB_DIR ?=     $(PREFIX)/share/lua/$(LUA_VERSION)
 52 INSTALL ?= install
 53
 54 .PHONY: all test install
```

> no file '/usr/local/share/lua/5.1/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core/init.lua'

**Comment by Pranali4796** [comment]
Still facing error:
2023/12/22 05:02:25 [emerg] 849#849: open() "/etc/nginx/conf.d/infra.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:66
nginx: [emerg] open() "/etc/nginx/conf.d/infra.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:66

**Comment by lynch1981** [comment]
You can confirm whether /etc/nginx/conf.d/infra.conf exists, 
but it is  sure that this is not required by ngx_lua.
