### ISSUE TITLE
Why can't I use ngx.redirect or ngx.say in the header_filter_by_lua phase

### ISSUE THREAD

**Issue by zhyfei** [openresty/lua-nginx-module#2271]
Why can't I use ngx.redirect or ngx.say in the header_filter_by_lua phase? I have a requirement to intercept download requests, and I have to use the following method.  
 ngx.header["Content-Type"] = "text/html;charset=utf-8"
 ngx.header["Location"] = sso_portal_401               
 ngx.status = 307
 ngx.exit(ngx.status)
Is this approach risky?

**Comment by zhuizhuhaomeng** [comment]
This approach looks good to me.
