### ISSUE TITLE
How to share ctx in dfferent locations

### ISSUE THREAD

**Issue by zhwaaaaaa** [openresty/lua-nginx-module#2283]
I want to share ngx.ctx in different locations. like
```
location ^~ / {
  access_by_lua "ngx.ctx.foo = 'enter root'";
  proxy_pass http://s;
}

error_page 500 502 503 = @err;

location @err {
  content_by_lua "ngx.say('foo:'..ngx.ctx.foo)";
}
```
but I cannot get value of ngx.ctx.foo  in @err because ngx will clear r->ctx at location changing.
Are there any other solutions available ？？

**Comment by jamo** [comment]
Try using ngx.var instead

**Comment by zhuizhuhaomeng** [comment]
you can use this feature https://github.com/Kong/kong/blob/master/kong/resty/ctx.lua
