### ISSUE TITLE
http2 request failed 

### ISSUE THREAD

**Issue by zffocussss** [openresty/lua-nginx-module#2285]
Hi guys:
  we are using the kong application gateway which is built with openrest and other plugins.but requests failed due to http2 request.

https://github.com/openresty/lua-nginx-module/blob/7598ff389ef5a1a3e8949c48a6e13292fa9adc9e/src/ngx_http_lua_req_body.c#L90

**Comment by ZJfans** [comment]
check if your request has content-length-header

**Comment by ZJfans** [comment]
check if your request has content-length header

**Comment by zffocussss** [comment]
> check if your request has content-length header

content-length request header is not sent.It is not mandatory with the http2.

**Comment by oowl** [comment]
Please check the  context in https://github.com/openresty/lua-nginx-module/pull/2237 and https://github.com/openresty/lua-nginx-module/issues/2172
