### ISSUE TITLE
Is the dynamic module available precompiled?

### ISSUE THREAD

**Issue by oseiberts11** [openresty/lua-nginx-module#2288]
Hi! In the README, it is mentioned that "Starting from NGINX 1.9.11, you can also compile this module as a dynamic module, by using the --add-dynamic-module=PATH option instead of --add-module=PATH on the ./configure command line above.". and also that "It is discouraged to build this module with Nginx yourself since it is tricky to set up exactly right.".

Given that, is a pre-built version of the dynamic module available (preferably packaged for Ubuntu)? We are using Nginx PLUS, so just replacing our existing nginx with a bundled one from a different source doesn't sound like it will work.

**Comment by zhuizhuhaomeng** [comment]
No.
The OpenResty does not provide the precompiled so.
