### ISSUE TITLE
Search in POST request

### ISSUE THREAD

**Issue by midgard** [openresty/lua-nginx-module#2299]
Hi there.

My configuration:
```
access_by_lua_block {
    local cjson = require "cjson"
    ngx.req.read_body()
    local data = ngx.req.get_body_data()

    if data then
        local status, json_data = pcall(cjson.decode, data)
        if status then
            if string.find(tostring(data), "gpt-4-0613") then
                return ngx.exit(403)
            else
                ngx.log(ngx.ERR, "gpt-4-0613 expression not found: ", data)
            end
        end
    end
}
```

Access log: (looks 200)
```
[23/Mar/2024:17:51:29 +0300] - 200 - "AI%20Astrologer/1 CFNetwork/1492.0.1 Darwin/23.3.0" (0.323) - "{\x22model\x22:\x22gpt-4-0613\x22,\x22messages\x22:[{\x22role\x22:\x22user\x22,\x22content\x22:\x22\x22}],\x22max_tokens\x22:1}"
```

Error log: (attention to expressions please)
```
2024/03/23 17:51:29 [error] 66665#66665: *1 [lua] cappsule.tech:54):12: gpt-4-0613 expression not found: {"model":"gpt-4-0613","messages":[{"role":"user","content":""}],"max_tokens":1}, client: 162.158.111.99, server: gpt.cappsule.tech, request: "POST / HTTP/1.1", host: "gpt.cappsule.tech"
```

I don't understand. JSON data is contains gpt-4-0613, but I cannot blocking this request.

What is the problem?

**Comment by ZJfans** [comment]
string.find supports regular matching, "-" has special meaning, so you can modify the code like this
1. string.find(tostring(data), "gpt%-4%-0613")
2. string.find(tostring(data), "gpt[-]4[-]0613")
I like the second style,
`access_by_lua_block {
     local cjson = require "cjson"
     ngx.req.read_body()
     local data = ngx.req.get_body_data()
     if data then
         if string.find(data, "gpt[-]4[-]0613") then
             return ngx.exit(403)
         else
             ngx.log(ngx.ERR, "gpt-4-0613 expression not found: ", data)
         end
     end
}`

**Comment by ZJfans** [comment]
string.find supports regular matching, "-" has special meaning, so you can modify the code like this
1. string.find(tostring(data), "gpt%-4%-0613")
2. string.find(tostring(data), "gpt[-]4[-]0613")
I like the second style,

access_by_lua_block {
     local cjson = require "cjson"
     ngx.req.read_body()
     local data = ngx.req.get_body_data()
     if data then
         if string.find(data, "gpt[-]4[-]0613") then
             return ngx.exit(403)
         else
             ngx.log(ngx.ERR, "gpt-4-0613 expression not found: ", data)
         end
     end
}

**Comment by ZJfans** [comment]
string.find supports regular matching, "-" has special meaning, so you can modify the code like this
```
1. string.find(tostring(data), "gpt%-4%-0613")
2. string.find(tostring(data), "gpt[-]4[-]0613")
```
I like the second style,
```
access_by_lua_block {
      local cjson = require "cjson"
      ngx.req.read_body()
      local data = ngx.req.get_body_data()

      if data then
          if string.find(data, "gpt[-]4[-]0613") then
              return ngx.exit(403)
          else
              ngx.log(ngx.ERR, "gpt-4-0613 expression not found: ", data)
          end
      end
}
```

**Comment by midgard** [comment]
Thank you so much @ZJfans

You saved my life :)
