### ISSUE TITLE
issue use lua code beside modsecurity module

### ISSUE THREAD

**Issue by kikamorasuzuki** [openresty/lua-nginx-module#2300]
How can I determine that the code executed in the access_by_lua run after modsecurity module is executed. Currently, I have tested and found out that they are running at the same time and lua code send response to client faster . What is the solution that specifies the order of the modules? I want be first modsec after that run my lua code...
and big thanks to openresty to create this

**Comment by zhuizhuhaomeng** [comment]
https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#access_by_lua_no_postpone
By default, the acess_by_lua runs at the end of the access phase.

**Comment by kikamorasuzuki** [comment]
thank you

> https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#access_by_lua_no_postpone By default, the acess_by_lua runs at the end of the access phase.

thank you
