### ISSUE TITLE
Question on memory handling in shared_dict

### ISSUE THREAD

**Issue by IlyaIndigo** [openresty/lua-nginx-module#2306]
https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxshareddictset
Reading the documentation I didn't fully understand some points.
1 What happens when a key expires?
When and how and after how long is the memory replaced by this value freed and is it freed at all?
2 When memory is full, does the set method try to delete expired keys or can it delete keys that haven't expired yet?

**Comment by zhuizhuhaomeng** [comment]
> 1 What happens when a key expires?
> When and how and after how long is the memory replaced by this value freed and is it freed at all?
Nothing happens when a key expires.  The expired key is still there if it is not replaced by another new add/set operation.

2 When memory is full, does the set method try to delete expired keys or can it delete keys that haven't expired yet?
There are different APIs.  
When memory is full, the dict:set() will delete keys that is not expired yet.
And the dict:safe_set() will not delete keys that is not exipred.

**Comment by IlyaIndigo** [comment]
Thank you for the answer.
I understand correctly, if I want memory not to overflow I should take care of periodic calls of flush_expired() myself ?
```
http {
    ,,,,
    lua_shared_dict my 1m;
    lua_block {
        local function mem_free()
            ngx.shared.my:flush_expired()
        end
        require("resty.concurrent.scheduler").every("1h", mem_free)
    }   ....
}
```

**Comment by zhuizhuhaomeng** [comment]
Nope.
What you need to do is:
1. config a reasonable shdict size
2. choose the right API like set or safe_set
3. set a reasonable expired time

If the shdict still overflows, then tweak the above steps.

**Comment by IlyaIndigo** [comment]
But if I set the test key to 3600 sec.
And no one will access (:get("test")) it after expiration, it will hang in memory forever until nginx is rebooted.
And so it is with every value.

Or did I misunderstand?

**Comment by zhuizhuhaomeng** [comment]
Table entries in shared dict are passively eliminated and remain in memory as long as they are not overwritten.
