### ISSUE TITLE
Nginx + LibreSSL (undefined symbol: SSL_client_hello_get0_ext)

### ISSUE THREAD

**Issue by asyslinux** [openresty/lua-nginx-module#2325]
LibreSSL isn`t supported by lua-nginx-module ?

I look in sources of LibreSSL and don`t find any implementations of SSL_client_hello_get0 functions.
But in sources of lua-nginx-module i saw #ifdef LIBRESSL_VERSION_NUMBER directives.

Debian 12 (amd64) / Nginx 1.27.0 / LibreSSL 3.9.2 / Lua nginx module 0.10.26

After success build nginx + lua modules + LibreSSL 3.9.2 i got an error when try load lua module:

check nginx -t:
`
root@bookworm:~/compile/nginx# nginx -t
nginx: 2024/07/02 13:43:06 [emerg] 1732916#1732916: dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: SSL_client_hello_get0_ext) in /etc/nginx/nginx.conf:9
`

nginx version:
```
nginx version: nginx/1.27.0
built with LibreSSL 3.9.2
TLS SNI support enabled
```

nginx.conf:
```
load_module modules/ndk_http_module.so;
load_module modules/ngx_http_lua_module.so;
```

Thanks.

**Comment by zhuizhuhaomeng** [comment]
https://github.com/openresty/lua-nginx-module/pull/2327
@asyslinux  would you please try this PR?

**Comment by asyslinux** [comment]
@zhuizhuhaomeng unfortunately it doesn't work:
`
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: SSL_client_hello_get0_ext) in /etc/nginx/nginx.conf:9
nginx: configuration file /etc/nginx/nginx.conf test failed
`

**Comment by asyslinux** [comment]
Please add this: https://github.com/openresty/lua-nginx-module/pull/2327#pullrequestreview-2160120275

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
