### ISSUE TITLE
possible multiple redundant comparison of functions return codes

### ISSUE THREAD

**Issue by leeriorio** [openresty/lua-nginx-module#2360]
In result of static analyse of nginx sources (including lua-nginx-module) with Svace static analyzer I found multiple minor error of cathegory "REDUNDANT_COMPARISON.ALWAYS_FALSE" in lua-nginx-module sources. 

In file **ngx_http_lua_module.c** calling functions [`ngx_http_lua_capture_filter_init()`](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L785), [`ngx_http_lua_header_filter_init()`](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L848) and [`ngx_http_lua_body_filter_init()`](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L855) returns `NGX_OK` status only. 

In file **ngx_http_lua_socket_tcp.c** calling function `ngx_http_lua_socket_push_input_data()` in lines [3203](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_socket_tcp.c#L3203) and [3222](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_socket_tcp.c#L3222) returns `NGX_OK` status only. 

In file calling function [`ngx_http_lua_socket_resolve_retval_handler`](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_socket_udp.c#L349) can returns codes 2 or 1 only (not equals to `NGX_AGAIN`)

checks for **rc** variable after this calls find redundant because it seems that calling functions never return codes used in comparison

**Comment by zhuizhuhaomeng** [comment]
[ngx_http_lua_socket_resolve_retval_handler](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_socket_udp.c#L349) does return NGX_AGAIN

**Comment by zhuizhuhaomeng** [comment]
The checks in functions [ngx_http_lua_capture_filter_init()](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L785), [ngx_http_lua_header_filter_init()](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L848) and [ngx_http_lua_body_filter_init()](https://github.com/openresty/lua-nginx-module/blob/816483d6e66efa1b5a93571932d4e33f336b2d36/src/ngx_http_lua_module.c#L855) are needed in case their implements changes in the future.
