### ISSUE TITLE
why ngx.var.bytes_sent is 0?

### ISSUE THREAD

**Issue by firefoxbug** [openresty/lua-nginx-module#246]
I want to print packages' byes in lua and in my nginx.conf is:
location /test_lua{
....
content_by_lua'
            ngx.say("uri : ", ngx.var.uri)
            ngx.say("status : ", ngx.var.status)
            ngx.say("bytes sent: ", ngx.var.bytes_sent)
            ngx.say("body bytes sent: ", ngx.var.body_bytes_sent)

';
}
The results of uri and status is OK，but ngx.var.bytes_sent and ngx.var.body_bytes_sent is always zero，I have seen nginx's access log，they are not zero.

can you help me ? Thanks!

**Comment by rest17** [comment]
adding , ngx.var.status)
 in access_by_lua didn't work. I am trying to get the byte sent back in response to write to file
