### ISSUE TITLE
lua_package_path not getting the relative path when running nginx with -p 

### ISSUE THREAD

**Issue by kidd** [openresty/lua-nginx-module#263]
Hi!

I'm finding this strange behaviour:

When running nginx from the commandline with -p option, the lua_package_path doesn't seem to be passed to the lua files that are required.

I trimmed it to this minimal example:
All these files live inside /tmp/pof :
https://gist.github.com/kidd/6065019

When running nginx with:

`cd /tmp
sudo /opt/openresty/nginx/sbin/nginx -c ./nginx.conf -p /tmp/pof/`

and hitting the root path I get this error in error.log
`
2013/07/23 20:37:01 [error] 31454#0: *1 lua entry thread aborted: runtime error: /tmp/pof/foo.lua:1: module 'r' not found:
        no field package.preload['r']
        no file '/opt/openresty/lualib/r.lua'
        no file '/opt/openresty/lualib/r/init.lua'
        no file './r.lua'
        no file '/opt/openresty/luajit/share/luajit-2.0.2/r.lua'
        no file '/usr/local/share/lua/5.1/r.lua'
        no file '/usr/local/share/lua/5.1/r/init.lua'
        no file '/opt/openresty/luajit/share/lua/5.1/r.lua'
`

nginx version is:  
nginx version: ngx_openresty/1.2.8.6

PS: Thanks for lua-nginx. Amazing power and speed at our hands :)

**Comment by Mecanik** [comment]
This is interesting, so what happens when you cannot use -p for your nginx command line ?

**Comment by agentzh** [comment]
@Mecanik Then it just uses the default server prefix which is usually the installation directory of the nginx or openresty (unless specified otherwise via `./configure` options during compile-time).

**Comment by rrfeng** [comment]
@agentzh 
Is there a variable like $prefix that represent the location of nginx.conf ( nginx -c  ... )?
I am tring to put some lua code in the config dir, and want use the relative path in lua_package_path.

Relative path in config file is relative to the nginx.conf, but lua_package_path cannot.

**Comment by rrfeng** [comment]
The `$prefix` cannot help me. I want to put lua code beside the `nginx.conf`, and the `nginx.conf`(or --conf-path ) is not  under the `$prefix`. If there is a variable ${conf-path} may help.

It's not a big problem, I was searching about it and found this issue.

**Comment by rulatir** [comment]
Can I have a very specific example?

Assuming that:
- my modules reside in `/lua/foo/` in the image, and
- I want `require "bar.baz"` to hit `/lua/foo/bar/baz.lua",

then what **exactly** should I put in `lua_package_path`?

**Comment by agentzh** [comment]
@rulatir You should put this literally:

```nginx
lua_package_path "/lua/foo/?.lua;;";
```

Note that `?` is not meant to be replaced by yourself (the Lua VM needs to see that).

Also, you need to make sure your nginx's system account has enough permission to access that file and that directory path (each directory in the path must have executable permission and the file itself must have reading permission for the system account).
