### ISSUE TITLE
Strange behavior with lua_code_cache on

### ISSUE THREAD

**Issue by sharepad** [openresty/lua-nginx-module#272]
Hi

Using `nginx version: ngx_openresty/1.4.1.1`, we have an app that's working properly with `lua_code_cache off`.

When setting it to `on`, queries have the correct behavior only once, all subsequent calls will fail, making it look like a cache issue.

Here is most of `nginx.conf`:

``` nginx
worker_processes 1;
worker_rlimit_nofile 8192;
events {
  worker_connections  16384;
}
http {
  include mime.types;

  resolver 127.0.0.1;
  resolver_timeout 1s;

  access_log off;
  lua_package_path './src/?.lua;;';

  server {
    set $PRODUCTION 1;
    # lua_code_cache off;

    listen 8087;
    server_name localhost;
    set $root ./;
    root $root;

    location / { try_files $uri @lua; }
    location @lua {
      content_by_lua_file $root/src/index.lua;
    }
  }
}
```

We have several lua files, all modules being called by `index.lua` and have two main db globals, one for Redis the other for MySQL.

The following function for instance, returns the correct value only once with code cache:

``` lua
init_mysql()
local token = Auth.get_token()
end_mysql()
ngx.say(token)   
ngx.exit(ngx.HTTP_OK)
```

Subsequent calls return: 

```
error: failed to send query: cannot send query in the current context: nil nil
```

which comes from `if not res then ngx.say('error: ' .. err) end` in `Auth.get_token`.

**Comment by WALL-E** [comment]
@agentzh 
http://wiki.nginx.org/HttpLuaModule#Lua_Variable_Scope is 404, can you update it?

**Comment by agentzh** [comment]
@WALL-E The new location is here:

https://github.com/openresty/lua-nginx-module/#lua-variable-scope

**Comment by WALL-E** [comment]
@agentzh  Thanks
