### ISSUE TITLE
lua_shared_dict.Is it a memory leak?

### ISSUE THREAD

**Issue by ZhangBowen** [openresty/lua-nginx-module#279]
linux :     red hat 6
nginx:     1.4.1
nginx-lua:0.8.8
1. alloc 1mb memory.

```
lua_shared_dict test 1m;
```
1. set 1mb data into it.

```
suc,err = test:set(key,string.rep('a',1000*1024));
```

suc is true.
3. set 100kb data into it.

```
suc,err = test:set(key,string.rep('a',100*1024));
```

suc is true.
4. set 1mb data into it again.

```
suc,err = test:set(key,string.rep('a',1000*1024));
```

suc is FALSE, and err is 'no memory'.
In error log of nginx,there is a message 

```
ngx_slab_alloc() failed: no memory in lua_shared_dict zone "test"
```

In this time,the test zone is empty —— no any data.
this memory zone seems to be smaller.It can not hold 1mb data.
It is recurrent after

```
service nginx restart
```

Is it a memory leak or there is some matter with my usage?
need help~
thanks in advance.

**Comment by khaled4vokalz** [comment]
@agentzh ,
Has this patch been merged in the module?

**Comment by zhuizhuhaomeng** [comment]
I don't think this path has been merged.
But the problem may have been fixed in another way.
Do you encounter any problems?
Try [OpenResty XRay](https://openresty.com) to find the root cause.

**Comment by khaled4vokalz** [comment]
we're getting the same problem with memory fragmentation I guess.... while there's enough space left in the dictionary it's throwing **no memory** errors...

**Comment by lystormenvoy** [comment]
> we're getting the same problem with memory fragmentation I guess.... while there's enough space left in the dictionary it's throwing **no memory** errors...

the same on aarch64 server in docker
