### ISSUE TITLE
Support for HMAC-SHA256

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#311]
It would be cool to have support for HMAC-SHA256, as it's being increasingly used by some services like in the AWS Signature Version 4 (http://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html).

**Comment by agentzh** [comment]
@ddragosd Sorry, I changed my mind again. `lua-resty-string` has been a mess now :) Better put it in a separate Lua library. I'm very sorry for the frustrations with it. I'm closing this ticket.
