### ISSUE TITLE
nginx: [error] failed to initialize Lua VM

### ISSUE THREAD

**Issue by tibx17** [openresty/lua-nginx-module#325]
I have installed the Lua JIT 2.0, the Lua Nginx Module 0.94, and Nginx 1.5.8, but when I attempt to start nginx, I get the following error:

nginx: [error] failed to initialize Lua VM in /usr/local/conf/nginx.conf:94

(the same error also appears in the logs/error.log file)

**Comment by jackho** [comment]
hi，I have the same problem. How to solve that problem? fix it by using OpenResty? How?

**Comment by agentzh** [comment]
@jackho You are not running it with valgrind, right? What exact version of OpenResty are you using? What operating system you are on? Do you use any special building flags while building OpenResty? Do you have a minimal and standalone example that can reproduce the problem reliably and easily?

**Comment by jackho** [comment]
@agentzh 
openresty version:1.9.3.1
mac os x 10.11.1

openresty=================
export KERNEL_BITS=64
./configure --with-luajit \
--with-cc-opt="-I/usr/local/Cellar/pcre/8.36/include" \
--with-ld-opt="-L/usr/local/Cellar/pcre/8.36/lib" \
--prefix=/usr/local/Cellar/openresty \
--with-openssl=/Users/hojack/Downloads/openssl-1.0.2d -j9
make -j9
sudo make install


nginx======================
sudo ./configure --prefix=/usr/local/Cellar/nginx/1.6.3 \
--with-http_ssl_module \
--with-pcre \
--with-ipv6 \
--sbin-path=/usr/local/Cellar/nginx/1.6.3/bin/nginx \
--with-cc-opt='-I/usr/local/Cellar/pcre/8.36/include -I/usr/local/Cellar/openssl/1.0.2a-1/include' \
--with-ld-opt='-L/usr/local/Cellar/pcre/8.36/lib -L/usr/local/Cellar/openssl/1.0.2a-1/lib' \
--conf-path=/usr/local/etc/nginx/nginx.conf \
--pid-path=/usr/local/var/run/nginx.pid \
--lock-path=/usr/local/var/run/nginx.lock \
--http-client-body-temp-path=/usr/local/var/run/nginx/client_body_temp \
--http-proxy-temp-path=/usr/local/var/run/nginx/proxy_temp \
--http-fastcgi-temp-path=/usr/local/var/run/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/usr/local/var/run/nginx/uwsgi_temp \
--http-scgi-temp-path=/usr/local/var/run/nginx/scgi_temp \
--http-log-path=/usr/local/var/log/nginx/access.log \
--error-log-path=/usr/local/var/log/nginx/error.log \
--with-http_gzip_static_module \
--add-module=/Users/hojack/Downloads/echo-nginx-module-master \
--add-module=/Users/hojack/Downloads/ngx_devel_kit-master \
--add-module=/Users/hojack/Downloads/set-misc-nginx-module-master \
--add-module=/Users/hojack/Downloads/lua-nginx-module-master
make
sudo cp ./objs/nginx /usr/local/Cellar/nginx/1.6.3/bin/nginx

problem======================
nginx: [error] failed to initialize Lua VM in /usr/local/etc/nginx/nginx.conf:302

**Comment by jackho** [comment]
@agentzh  according another issus from yours,I reinstall lua(version:5.1), original version is 5.2.now I solved the problem. Thank you all the same! : )

**Comment by agentzh** [comment]
@jackho The homebrew openersty thing is not maintained by the official OpenResty team. It seems that you're using the standard Lua 5.1 interpreter there which is slooow and also biggger. It's highly recommended to build OpenResty directly from the official source distribution here for the best results:

https://openresty.org/#Download

https://openresty.org/#Installation

Regards,
-agentzh
