### ISSUE TITLE
add ngx.timer support in init_by_lua

### ISSUE THREAD

**Issue by likebean** [openresty/lua-nginx-module#330]
hi master,I want to load and refresh global config (from other site) ,and I think use a global singleton timer in init_by_lua is best solution.and because this timer is singleton and I think init_worker_by_lua is not a good place.
Any advice?

Thanks

**Comment by icearith** [comment]
@agentzh Could you please give a specific example of such implementation? did you mean to set an indicator that there is a worker is using the shared_dict ?
