### ISSUE TITLE
openresty 1.5.8.1 on FreeBSD10 issue

### ISSUE THREAD

**Issue by lhmwzy** [openresty/lua-nginx-module#333]
./configure 有如下错误

./configure
platform: freebsd (freebsd)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20140109
gmake TARGET_STRIP=@: CCDEBUG=-g PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-alpha ====
gmake -C src
gmake[1]: gcc: Command not found
gmake[1]: Entering directory `/usr/home/lhm/ngx_openresty-1.5.8.1/build/LuaJIT-2.1-20140109/src'
gmake[1]: gcc: Command not found
gmake[1]: gcc: Command not found
gmake[1]: gcc: Command not found
gmake[1]: gcc: Command not found
gmake[1]: gcc: Command not found
Makefile:228: *** Unsupported target architecture.  Stop.
gmake[1]: Leaving directory`/usr/home/lhm/ngx_openresty-1.5.8.1/build/LuaJIT-2.1-20140109/src'
gmake: **\* [default] Error 2
ERROR: failed to run command: gmake TARGET_STRIP=@: CCDEBUG=-g PREFIX=/usr/local/openresty/luajit

use ./configure --with-cc=/usr/bin/cc
has following error and warnings,but can make it.

cc: error: unsupported option '-dumpspecs'
cc: error: no input files
cc: warning: argument unused during compilation: '-fPIC'
cc: warning: argument unused during compilation: '-fomit-frame-pointer'
cc: warning: argument unused during compilation: '-Wall'
cc: warning: argument unused during compilation: '-D _FILE_OFFSET_BITS=64'
cc: warning: argument unused during compilation: '-D _LARGEFILE_SOURCE'
cc: warning: argument unused during compilation: '-U _FORTIFY_SOURCE'
cc: warning: argument unused during compilation: '-D LUA_ROOT="/usr/local/openresty/luajit"'
cc: warning: argument unused during compilation: '-D LUA_MULTILIB="lib"'
cc: warning: argument unused during compilation: '-fomit-frame-pointer'
cc: warning: argument unused during compilation: '-Wall'
cc: warning: argument unused during compilation: '-D _FILE_OFFSET_BITS=64'
cc: warning: argument unused during compilation: '-D _LARGEFILE_SOURCE'
cc: warning: argument unused during compilation: '-U _FORTIFY_SOURCE'
cc: warning: argument unused during compilation: '-D LUA_ROOT="/usr/local/openresty/luajit"'
cc: warning: argument unused during compilation: '-D LUA_MULTILIB="lib"'
ldconfig: illegal option -- n
usage: ldconfig [-32] [-aout | -elf] [-Rimrsv] [-f hints_file] [directory | file ...]
# /usr/bin/cc -v

FreeBSD clang version 3.3 (tags/RELEASE_33/final 183502) 20130610
Target: x86_64-unknown-freebsd10.0
Thread model: posix
this /usr/bin/cc is Clang

This warnings and errors has any impact on openresty?
Could @agentzh  fix them?

**Comment by gauravt** [comment]
I'm having this error on compiling:


/usr/include/bits/types.h:42: error: declaration for parameter ‘__uint32_t’ but no such parameter
/usr/include/bits/types.h:41: error: declaration for parameter ‘__int32_t’ but no such parameter
/usr/include/bits/types.h:40: error: declaration for parameter ‘__uint16_t’ but no such parameter
/usr/include/bits/types.h:39: error: declaration for parameter ‘__int16_t’ but no such parameter
/usr/include/bits/types.h:38: error: declaration for parameter ‘__uint8_t’ but no such parameter
/usr/include/bits/types.h:37: error: declaration for parameter ‘__int8_t’ but no such parameter
/usr/include/bits/types.h:34: error: declaration for parameter ‘__u_long’ but no such parameter
/usr/include/bits/types.h:33: error: declaration for parameter ‘__u_int’ but no such parameter
/usr/include/bits/types.h:32: error: declaration for parameter ‘__u_short’ but no such parameter
/usr/include/math.h:329: error: declaration for parameter ‘matherr’ but no such parameter
/usr/include/math.h:298: error: declaration for parameter ‘_LIB_VERSION_TYPE’ but no such parameter
/usr/include/math.h:157: error: declaration for parameter ‘signgam’ but no such parameter
host/minilua.c:7770: error: expected ‘{’ at end of input
gmake[1]: *** [host/minilua.o] Error 1
gmake[1]: Leaving directory `/toinstall/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
gmake: *** [default] Error 2
ERROR: failed to run command: gmake TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit

**Comment by agentzh** [comment]
@gauravt Your error messages are truncated. Will you provide the complete output somewhere like gist.github.com and then share the link here? Also, you'd better create a separate ticket because it's apparently a different issue than the original reporter in this ticket.
