### ISSUE TITLE
LUA Shared DICT doesn't working with long keys

### ISSUE THREAD

**Issue by carminexx** [openresty/lua-nginx-module#337]
Hi,
I've a really odd problem while using the LUA shared DICT with nginx openresty (stable versione 1.4.3.6): I use keys with reasonable lenghts (about 65-67 chars), and these keys worked well when I used that in a project.
Now I made a new (almost identical) deploy on another (identical) server, and the get/set doesn't work with such keys.
I exclude coding errors, because I tried everything, and the _only_ thing to do, in order to make the shared dict work, is reduce the lenght of keys to 30-32 chars.
How come?
Perhaps is a bug?

**Comment by decadence** [comment]
@agentzh is there any limit for value length?

**Comment by zhuizhuhaomeng** [comment]
no explicit limit fo the value length
