### ISSUE TITLE
global variables from includes

### ISSUE THREAD

**Issue by nvrmnd** [openresty/lua-nginx-module#346]
Hi. I'm using the following nginx config:

worker_processes  1;
location = /lua {
    content_by_lua_file 'main.lua';
}

The content of 'main.lua' file is:

```
require("include")
ngx.say(variable)
```

File 'include.lua' is required here, it's content (one line, global variable):

```
variable = "Test"
```

When I query the location, i see that after second request global variable from included file is gone:
    $ curl "127.0.0.1/lua" 
    Test
    $ curl "127.0.0.1/lua"
    nil

But everything is fine when I turn code cache off.

nginx 1.5.11
lua-nginx-module-0.9.5rc2
luajit 2.0.2

**Comment by Romaboy** [comment]
Global variables are awesome and limitation on them is very sad, so:
```lua
require("include")
ngx.say(variable)
```
You can rewrite it to:
```lua
setfenv(loadfile('include.lua'), _G)()
ngx.say(variable)
```
Or even write helper:
```lua
include = function(path)
  return setfenv(loadfile(path .. '.lua'), _G)()
end
```
And then just use include instead of require
