### ISSUE TITLE
Injecting HTTP headers during body_filter_by_lua based on response body contents

### ISSUE THREAD

**Issue by carlosabalde** [openresty/lua-nginx-module#360]
Hi,

It would be possible to add some HTTP headers to the nginx response during body_filter_by_lua? The idea is to look for some placeholders in the HTTP response body. If found, the plan is using the matched values to inject some extra headers to the response (remove values from the body it would be nice, but it's not required; the response can remain unmodified). I've been trying with not success. Any hints (or the confirmation by some advanced user that this is not possible with the LUA module) are welcome.

Thanks!

**Comment by ramesshh** [comment]
@agentzh @carlosabalde - Did you guys implemented this solution of sending headers and status as part of `body_filter_by_lua`. I would highly appreciate any pseudo code on

> @carlosabalde Well, you need a new API to suppress sending header in header_filter_by_lua* (like returning ngx.DECLINED from the user code chunk) and support for ngx.send_headers() in body_filter_by_lua*.

**Comment by agentzh** [comment]
@ramesshh Not yet. Patches welcome.
