### ISSUE TITLE
lua_shared_dict names are global across all http blocks but can only be accessed from one.

### ISSUE THREAD

**Issue by DorianGray** [openresty/lua-nginx-module#363]
http {
  lua_shared_dict stuff 1m;
}

http {
  lua_shared_dict stuff 1m;
}

With the above configuration, nginx will fail to start because the dict already exists

http {
  lua_shared_dict stuff 1m;
}

http {
  init_by_lua '
    assert(ngx.shared.stuff)
  ';
}

with the above configuration, nginx will fail to start because ngx.shared.stuff is nil.

I believe this behavior to be incorrect. I would either expect shm to be shared between all http blocks(preferable) or local to an http block entirely.

**Comment by agentzh** [comment]
Multiple `http {}` blocks are not prohibited in recent versions of the official NGINX cores. I'm closing this.

**Comment by Guard13007** [comment]
> are not prohibited

@agentzh Did you mean are *now* prohibited?
