### ISSUE TITLE
Using access_by_lua and try_files instructions would cause nginx coredump

### ISSUE THREAD

**Issue by yaronli** [openresty/lua-nginx-module#364]
I write the following code in nginx.conf:

``` nginx
location /test_try_files {
  access_by_lua '
     ngx.say("This is from access_by_lua")
  ';
  try_files /noexist @try_files_internal;
}

location @try_files_internal {
  proxy_pass http://my_upstream_cluster;
}
```

using this configure, and visit /test_tyr_files, nginx worker process will coredump, i used gdb to print backtrace, but there is no symbol table, so sorry, i can't provide it.

nginx version: 1.2.6
lua-nginx-module : 0.6.10

I think the reason is that ngx.say() was called in access_by_lua. when i remove it from access_by_lua, it can work correctly, no corecump.

It is a bug ? or there is some limitation when using access_by_lua.

**Comment by xyalan** [comment]
in nginx error log:
```
[alert] 2430#0: *598 header already sent while reading response header from upstream
```

It's `lua-nginx-module` message?

**Comment by agentzh** [comment]
@yaronli NGINX core generates that message it seems. You must be trying to generating duplicate response header for that same request. You can temporarily enable the nginx debugging logs to be sure. See http://nginx.org/en/docs/debugging_log.html The same instructions apply to the OpenResty bundle too.

**Comment by nirvanareborn** [comment]
你好，麻烦了，我这边开发中碰到了困难无法解决，希望获得您的帮助：
场景：我这边使用nginx+lua渲染页面响应客户端，但是页面模板中存在include调用碎片页！当我关闭nginx的ssi时，响应正常，但是include的碎片页都会无效；当我开启ssi的时候，nginx就会报错，存在子请求，导致响应失败!
`28816#0: *224 header already sent while sending response to client, client: 192.168.211.91, server: 10.10.*, request: "GET /99889195.dhtml HTTP/1.1", subrequest: "/inc/script/css/base.shtml",`
我的邮箱: 66013804@qq.com

**Comment by agentzh** [comment]
@nirvanareborn Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see

http://openresty.org/en/community.html

Also, your comment is off topic in this ticket. Please do not do that again. It's very rude.

**Comment by nirvanareborn** [comment]
@agentzh  I am sorry!
