### ISSUE TITLE
feature request: implement ngx.popen

### ISSUE THREAD

**Issue by fabled** [openresty/lua-nginx-module#372]
Implement ngx.popen that works similar to os.popen, but would return instead ngx.tcpsock like pipe object. The idea is to execute process that can run for long time, so it's output could be captured asynchronously while other lua threads execute.

**Comment by bjne** [comment]
Any news on this issue?

**Comment by ycaihua** [comment]
@agentzh i use lua-resty-shell to execute a about 30 min job，but it execute fail and not logs;then i use "io.popen" && "nohup CMD &" it execute successful，can you give me some idea about why? thanks

**Comment by agentzh** [comment]
@ycaihua lua-resty-shell is not my project. You should report any problems to its author/maintainer instead.

**Comment by ycaihua** [comment]
@agentzh thanks you，i have get this reason cause that problem。that project have buffer limit to process the big cmd.

**Comment by thibaultcha** [comment]
Now implemented as `ngx.pipe` in OpenResty 1.15.8.1. Closing this thread!

**Comment by Jiri-Mihal** [comment]
@thibaultcha Do you have some example of working `ngx.pipe` usage? I can't find anything in documentation. Also when I try to call `ngx.pipe()` I get error `attempt to call field 'pipe' (a nil value)`.

I use OpenResty on Mac:
```sh
$ openresty -v
nginx version: openresty/1.15.8.1
```

**Comment by thibaultcha** [comment]
@Jiri-Mihal The documentation for the `ngx.pipe` API can be found here: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/pipe.md.

You can also get more examples and inspiration from the [tests suite](https://github.com/openresty/lua-resty-core/blob/master/t/pipe.t) and [lua-resty-shell](https://github.com/openresty/lua-resty-shell) (which you may also use in-lieu of the low-level `ngx.pipe` API if you are only planning on opening a shell).

**Comment by Jiri-Mihal** [comment]
@thibaultcha thank you, it really helped. Now I’m able to spawn non-blocking process and stream stdout to client. Cool😀
