### ISSUE TITLE
Better API browser

### ISSUE THREAD

**Issue by Sirupsen** [openresty/lua-nginx-module#399]
Browsing the API documentation via the README isn't as pleasant as it could be. The documentation itself is wonderful, so it's unfortunate it's so hard to browse. Click link to Lua functions in the TOC, click API call, click back to TOC, click link to Lua functions in the TOC, click API call.

https://github.com/mbostock/d3 is an excellent example of leveraging the Github wiki.

**Comment by agentzh** [comment]
Consider it resolved.
