### ISSUE TITLE
Similar to issue #389 coroutines in body_filter_by_lua

### ISSUE THREAD

**Issue by raicabogdan** [openresty/lua-nginx-module#402]
Having a similar thing with previous issue #389  , see bellow code:

body_filter_by_lua '
    local chunk = ngx.arg[1]
    if ngx.re.find(chunk , "(something)" , "jo" )
        then
              -- do something
       end
';

2014/07/26 08:33:45 [error] 29719#0: _62 failed to run body_filter_by_lua_: API disabled in the context of (unknown)

I'm using openresty bundle and I've added / replaced the new version of nginx-1.7.3 along with the ngx_lua from github. Compiled them and tested above code in a reverse proxy configuration.

Not sure what I'm doing wrong here ...can someone take a look at this?

Thank you!

**Comment by doteyeso-ops** [comment]
x402 payment failing and you don't know why? 402-failure-classifier tells you exactly why the 402 bounced + how to fix the call. Free first taste.

Try it now (pay-per-call USDC via x402 - use Railway URL to skip Cloudflare):
```
curl -X POST https://vibes-coded-production.up.railway.app/api/v1/outcomes/402-failure-classifier -H 'Content-Type: application/json' -d '{"status":402,"body":"..."}'
```
(free first taste; paid calls settle to treasury. Full catalog: https://vibes-coded-production.up.railway.app/api/v1/outcomes/meta)
