### ISSUE TITLE
using cosockets in header_filter_by_lua/body_filter_by_lua

### ISSUE THREAD

**Issue by ngo** [openresty/lua-nginx-module#431]
cosocket API is currently disabled in header_filter_by_lua/body_filter_by_lua, which results in inability to use sockets and socket-based libraries in these handlers.

What is the reason for this limitation and how can it be removed?

**Comment by fankeke** [comment]
> @ngo To answer your question,
> 
> https://github.com/openresty/lua-nginx-module#cocockets-not-available-everywhere
> 
> "Due the internal limitations in the nginx core, the cosocket API are disabled in the following contexts: set_by_lua_, log_by_lua_, header_filter_by_lua*, and body_filter_by_lua."

could you enlighten  on me what exactly the limitations is and how ? thanks.
