### ISSUE TITLE
Is it possible to defined headers sent by proxy_pass from lua code ?

### ISSUE THREAD

**Issue by fatpat** [openresty/lua-nginx-module#437]
Hi,

I have a access_by_lua code which use ngx.location.capture to request a backend through the proxy_pass directive.

I'd like to dynamically set the headers sent to the backend through proxy_pass.

The name and the value of the headers are dynamic.

Is this possible to achieve ?

thanks for the answer

**Comment by yushantao** [comment]
thanks my problem also solved

**Comment by xbsura** [comment]
@agentzh 
is it possible to use ngx.req.set_header or other methods dynamic set upstream header in balancer module?

thanks

**Comment by agentzh** [comment]
@xbsura No, in the context of balancer_by_lua*, the upstream request is already generated by the ngx_proxy module and etc, so it's too late. Instead, you should do that in an earlier phase handler like `access_by_lua*` or `rewrite_by_lua*`.

**Comment by xbsura** [comment]
@agentzh 
ok, thanks

**Comment by panhow** [comment]
@agentzh 
I get a problem here.In order to set the headers of the upstream request, I use `ngx.req.set_header` in `rewrite_by_lua_block`, but my upstream endpoint cannot receive such header. 
here is my conf.
```conf
upstream foo {
        server 127.0.0.1:6666 weight=1;
    }

    server {
        listen 8001;
        location / {
            rewrite_by_lua_block {
                ngx.req.set_header("Connection", "Upgrade")
            }
            proxy_pass http://foo;
        }
    }
    server {
        listen 8002;
        location / {
            proxy_set_header Connection '';
            rewrite_by_lua_block {
                ngx.req.set_header("Connection", "Upgrade")
            }
            proxy_pass http://foo;
        }
    }
```

request send by `8001` port still cannot get the header "Connection: Upgrade"

**Comment by devgig** [comment]
@agentzh
I want to set headers in lua for an upstream request.  I would like guidance on the correct way to do this in Lua.

**Comment by djfsb** [comment]
> @djfsb Do you mean `8001` does work and `8002` works?

both does work， i want to set header before proxy

**Comment by Hanoboo** [comment]
> @agentzh I get a problem here.In order to set the headers of the upstream request, I use `ngx.req.set_header` in `rewrite_by_lua_block`, but my upstream endpoint cannot receive such header. here is my conf.
> 
> ```
> upstream foo {
>         server 127.0.0.1:6666 weight=1;
>     }
> 
>     server {
>         listen 8001;
>         location / {
>             rewrite_by_lua_block {
>                 ngx.req.set_header("Connection", "Upgrade")
>             }
>             proxy_pass http://foo;
>         }
>     }
>     server {
>         listen 8002;
>         location / {
>             proxy_set_header Connection '';
>             rewrite_by_lua_block {
>                 ngx.req.set_header("Connection", "Upgrade")
>             }
>             proxy_pass http://foo;
>         }
>     }
> ```
> 
> request send by `8001` port still cannot get the header "Connection: Upgrade"

Have you solved this problem?I have a similar problem

**Comment by Hanoboo** [comment]
> > @agentzh I get a problem here.In order to set the headers of the upstream request, I use `ngx.req.set_header` in `rewrite_by_lua_block`, but my upstream endpoint cannot receive such header. here is my conf.
> > ```
> > upstream foo {
> >         server 127.0.0.1:6666 weight=1;
> >     }
> > 
> >     server {
> >         listen 8001;
> >         location / {
> >             rewrite_by_lua_block {
> >                 ngx.req.set_header("Connection", "Upgrade")
> >             }
> >             proxy_pass http://foo;
> >         }
> >     }
> >     server {
> >         listen 8002;
> >         location / {
> >             proxy_set_header Connection '';
> >             rewrite_by_lua_block {
> >                 ngx.req.set_header("Connection", "Upgrade")
> >             }
> >             proxy_pass http://foo;
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > request send by `8001` port still cannot get the header "Connection: Upgrade"
> 
> Have you solved this problem?I have a similar problem，

Have you solved this problem?I have a similar problem too

**Comment by panhow** [comment]
@Hanoboo no, i skipped this problem, this has been a long time
