### ISSUE TITLE
Intermittant "attempt to call upvalue 'ngx'"

### ISSUE THREAD

**Issue by rkearsley** [openresty/lua-nginx-module#444]
Hi
Very occasionally, one of my nginx/lua instances will start giving this error.

    2014/12/14 10:26:48 [error] 30019#0: *7112558 lua entry thread aborted: runtime error: /usr/local/nginx/conf/lua/shared/redis.lua:0: attempt to call upvalue 'ngx' (a table value)
    stack traceback:
    coroutine 0:
            /usr/local/nginx/conf/lua/shared/redis.lua: in function 'disconnect'

Restarting nginx fixes it, what could be happening?

	local redis = require "resty.redis"
	local tostring = tostring
	local ngx = require "ngx"

	module(...)

	function disconnect(red)
		if red then
			local ok, err = red:set_keepalive(3900000, 10000) -- 65 min idle timeout, 10,000 connections
			if not ok then
				ngx.log(ngx.ERR, "redis.lua:disconnect: failed to set keepalive: " .. tostring(err))
				local ok, err = red:close()
				if not ok then
					ngx.log(ngx.ERR, "redis.lua:disconnect: failed to close: " .. tostring(err))
				end
			end
		else
			ngx.log(ngx.ERR, "redis.lua:disconnect: redis was nil")
		end
	end

**Comment by agentzh** [comment]
@rkearsley Any updates on this issue?

**Comment by rkearsley** [comment]
sorry for the delay, will test soon

**Comment by agentzh** [comment]
Consider it resolved.
