### ISSUE TITLE
Garbage injected into gsub result when accessing request headers

### ISSUE THREAD

**Issue by pintsized** [openresty/lua-nginx-module#445]
If you call `ngx.req.get_headers()` during the replacement function for `ngx.re.gsub` when there are multiple matches, garbage is injected into the replacement, and the replacement point in the input string seems to be incorrect too.

I've got it down to the following minimal example. If you comment the line accessing the request headers, everything works as expected. Also if `data` only has one line matching "INNER" then it's fine.

Other API calls don't seem to affect it (I haven't searched exhaustively) except for `ngx.var["http_host"]` which triggers a similar behaviour (weirdly injecting the string "http_host" into the result).

This is in 1.7.7.1, and also present in the previous RC, I haven't had a chance to test in older releases.

What's doubly strange is that I cannot replicate this using the test framework. Firing a request at OpenResty using Curl or any browser shows the same bug, but the test framework seems immune. Naturally this makes me think it's something peculiar to my setup, but the test framework is targeting the same OpenResty build, so it's really quite strange...

``` lua
local data = [[
    INNER
    INNER
]]

ngx.say(data)

local res =  ngx.re.gsub(data, "INNER", function(inner_matches)
    local header = ngx.req.get_headers()["Host"]
    return "INNER_REPLACED"
end, "s")

ngx.say(res)
```

_Expected output:_

```
    INNER
    INNER

    INNER_REPLACED
    INNER_REPLACED
```

_Output when calling `ngx.req.get_headers():_

```
    INNER
    INNER


INNE���d
    INNER_REPLACED
```

_Output when calling `ngx.var["http_HEADER"]`_

```
    INNER
    INNER

http_host_REPLACED
    INNER_REPLACED
```

**Comment by pintsized** [comment]
Hi there,

Your fix dealt with this issue, but my application tests founder a further (presumably related) issue when comparing results with and without `resty.core`. It seems like a similar buffer reuse issue, having reduced it to the following simple test.

```lua
function test()
    local data = [[
        OUTER {FIRST}
    ]]

    local p1 = "(OUTER)(.+)"
    local p2 = "{([A-Z]+)}"

    ngx.say(data)

    local res =  ngx.re.gsub(data, p1, function(m)
        local res = ngx.re.gsub(m[2], p2, function(_)
            return "REPLACED"
        end, "")
        return m[1] .. res
    end, "")

    ngx.say(res)
end

test()

require "resty.core"
test()
```

Output:

```
                        OUTER {FIRST}

                        OUTER REPLACED

                        OUTER {FIRST}

                        FIRST REPLACED
```

So it seems the first capture within the nested `gsub` is overwriting `m[1]` in the outer `gsub`, but only when `resty.core` is enabled.

**Comment by agentzh** [comment]
@pintsized Thank you for the report! Just fixed in git master of lua-resty-core. Please try it out on your side.

**Comment by agentzh** [comment]
@pintsized Alas. This fix also makes the general use cases of `ngx.re.gsub` calls with a function replacement argument even slower since we can no longer reuse the captures result table.

**Comment by pintsized** [comment]
@agentzh Yep, all of my tests are passing now, with and without `resty.core`. Thanks! Shame about the performance implication, but unless we want to add complexity to the API (perhaps a flag to disable features in the replacement function?), it seems like an optimisation that was never really on the table?

**Comment by agentzh** [comment]
@pintsized Unfortunately a flag returned by the user callback is ugly and error prone :) I'd rather leave it as is :)
