### ISSUE TITLE
Size of shared dict

### ISSUE THREAD

**Issue by Sirupsen** [openresty/lua-nginx-module#449]
Is it possible to get the size of the shared dictionary or LRU activity? This is useful in determining a good size for the dictionary.

**Comment by agentzh** [comment]
@Sirupsen We've provided the "ngx-shm" systemtap tool to get this information from any running nginx worker process:

https://github.com/openresty/nginx-systemtap-toolkit#ngx-shm

BTW, please join the openresty-en mailing list for such general discussions. Thank you for your cooperation! Please see http://openresty.org/#Community

**Comment by Sirupsen** [comment]
Thanks! I'll subscribe to the mailing list
