### ISSUE TITLE
ngx.shared.DICT.set    report  no memory 

### ISSUE THREAD

**Issue by wzhyuan** [openresty/lua-nginx-module#453]
when  I use  dict:set  ,if   I set  a   string that have the   same  length  and same key, it will be  ok.
but   if  the    the length is not same length every time when set into  dict, it will report 
ngx_slab_alloc() failed: no memory in lua_shared_dict zone "***" 

lua_shared_dict  *** 10M;
the  file read to string  about 1.3M.

**Comment by agentzh** [comment]
@wzhyuan I've already replied to your private email. Please do not cross-post. Thank you.

**Comment by wzhyuan** [comment]
I have resolve this issue,Thanks for your support.  Best regards.
