### ISSUE TITLE
How to catch the status of  connection closed by client(just close the socket in keep-alive period)?

### ISSUE THREAD

**Issue by teqian** [openresty/lua-nginx-module#455]
I met a trouble that how to catch the event of  connection closed by client in the configuration file(nginx.conf) level;As we knew,during the nginx handling with the request,if that happens,nginx will log 499 status code in the access log file,but when client do not request,just keep alive with nginx,then the client crash.I do know nothing abort that condition. By the way,nginx will log  in error log file with the information of ‘ client closed connection while waiting for request’ on that condition.

**Comment by agentzh** [comment]
@teqian It's much easier to catch and handle such events from the outside, via (online) dynamic tracing tools like systemtap.

On the other hand, There's no way to handle this event in your own way without patching the nginx core AFAIK.
