### ISSUE TITLE
How can I rewrite a full URL by rewrite_by_lua

### ISSUE THREAD

**Issue by winnywind** [openresty/lua-nginx-module#458]
How can I rewrite a full URL but not uri by rewrite_by_lua?
I know that proxy_pass can help me, but with some reason, I can't use it. So can rewrite_by_lua help me?

I'd like to do something like:
rewrite    ^(.*)$  http://b.com    last

**Comment by agentzh** [comment]
@winnywind I think you can just use the ngx.redirect() Lua API function for this:

https://github.com/openresty/lua-nginx-module#ngxredirect

BTW, please use the openresty-en mailing list for such general questions. Thank you for your cooperation! Please see http://openresty.org/#Community

**Comment by winnywind** [comment]
@agentzh Thank you for your answer!
