### ISSUE TITLE
nginx-lua test shows "nginx: lua atpanic: Lua VM crashed, reason: not enough memory", why?

### ISSUE THREAD

**Issue by weiqwang** [openresty/lua-nginx-module#459]
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2015/02/16 02:21:51 F[ngx_http_lua_util.c] L[1363] f[ngx_http_lua_run_thread] [error] 19835#0: *6731514 lua entry thread aborted: memory allocation error: not enough memory
2015/02/16 02:21:52 F[ngx_http_lua_logby.c] L[207] f[ngx_http_lua_log_by_chunk] [error] 19835#0: *6731514 failed to run log_by_lua*: not enough memory while logging request, 

nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2015/02/16 07:04:11 F[ngx_http_lua_util.c] L[1363] f[ngx_http_lua_run_thread] [error] 34018#0: *7525401 lua entry thread aborted: memory allocation error: not enough memory
2015/02/16 08:41:48 F[ngx_http_lua_util.c] L[1363] f[ngx_http_lua_run_thread] [error] 32613#0: *7878472 lua entry thread aborted: memory allocation error: not enough memory

**Comment by agentzh** [comment]
@weiqwang Please, no Chinese here.

Regarding your question, such errors are usually a sign of memory leaks (or very aggressive and wasteful memory use) in your own Lua code. Maybe you should check whether you have a Lua table or a Lua string growing forever in your Lua code.

It could also be the old memory leak bug in LuaJIT itself if you're using some old versions of LuaJIT. That's why you're always recommended to use the latest OpenResty bundle (1.7.7.2 ATM): http://openresty.org/#Download

**Comment by weiqwang** [comment]
we find that when printing"nginx: lua atpanic: Lua VM crashed, reason: not enough memory", nginx worker uses high memory. e.g., 790MB->2.2GB                                                                                    
31785 root      20   0 5755m 791m 721m S      2  0.6   1:26.39 nginx                                                                                        
31785 root      20   0 5756m 792m 721m S      2  0.6   1:27.06 nginx                                                                                        
31785 root      20   0 5756m 792m 721m S      2  0.6   1:27.11 nginx                                                                                        
31785 root      20   0 7066m 2.0g 721m S      8  1.6   1:29.20 nginx                                                                                        
31785 root      20   0 7150m 2.1g 721m S      7  1.7   1:29.34 nginx                                                                                        
31785 root      20   0 7243m 2.2g 721m S      7  1.8   1:29.49 nginx
  
Do you have suggustions how to monitor each lua VM managed memory for each nginx worker?

**Comment by agentzh** [comment]
@weiqwang You can use various different tools to do the monitoring and/or analysis. For example,

* https://github.com/openresty/stapxx#lj-gc
* https://github.com/openresty/stapxx#lj-gc-objs
* https://github.com/openresty/nginx-gdb-utils#lgc
* https://github.com/openresty/nginx-gdb-utils#lgcstat
* https://github.com/openresty/nginx-gdb-utils#lgcpath

**Comment by weiqwang** [comment]
when i use stap++, it reports errors like this. what's wrong?

[root@ stapxx-master]# ./stap++  ./samples/lj-gc-objs.sxx -x 17335 -v 
Pass 1: parsed user script and 109 library script(s) using 177368virt/33988res/2488shr/32256data kb, in 210usr/20sys/238real ms.
WARNING: cannot find module /usr/local/lib/libluajit-5.1.so.2.0.2 debuginfo: No DWARF information found [man warning::debuginfo]
semantic error: type definition 'lua_State' not found in '/usr/local/lib/libluajit-5.1.so.2.0.2': operator '@cast' at stapxx-oFkEVBjk/luajit.stp:162:12
        source:     return @cast(L, "lua_State", "/usr/local/lib/libluajit-5.1.so.2.0.2")->glref->ptr32
                           ^

Pass 2: analyzed script: 3 probe(s), 20 function(s), 5 embed(s), 3 global(s) using 191092virt/48876res/3592shr/45980data kb, in 520usr/80sys/601real ms.
Pass 2: analysis failed.  [man error::pass2]
[root@ stapxx-master]#

**Comment by agentzh** [comment]
Your own LuaJIT installation lacks debug symbols. Read the doc for more details on this. It's recommended to use the latest OpenResty bundle release to save such troubles.

BTW, from the error messages you provided, you are using an old version of LuaJIT, which may have known leaks in its VM. Again, try using the latest OpenResty directly.

**Comment by agentzh** [comment]
Consider it resolved.
