### ISSUE TITLE
bug of the ctx in the document

### ISSUE THREAD

**Issue by fengidri** [openresty/lua-nginx-module#460]
The document has the example:
 ```
location /test {
     rewrite_by_lua '
         ngx.say("foo = ", ngx.ctx.foo)
         ngx.ctx.foo = 76
     ';
     access_by_lua '
         ngx.ctx.foo = ngx.ctx.foo + 3
     ';
     content_by_lua '
         ngx.say(ngx.ctx.foo)
     ';
}
```
but I can only get:
```
 foo = nil
```

**Comment by agentzh** [comment]
@fengidri Only one running phase in nginx can be responsible for generating the response. This is by nginx's own design. Please keep in mind that ngx.say() generates response body data (and will automatically trigger sending a response header too if the header is not sent yet).

**Comment by fengidri** [comment]
This is in Readme of lua-nginx-module, should change.
![2015-05-20-115529_719x756_scrot](https://cloud.githubusercontent.com/assets/3820861/7718671/949fa122-fee6-11e4-9ab7-b76ecfa84b9c.png)

Thanks!!.

**Comment by agentzh** [comment]
@fengidri Ah, yes. The documentation needs updates. Thank you for the catch!

**Comment by agentzh** [comment]
@fengidri I've fixed the corresponding documentation on wiki.nginx.org:

http://wiki.nginx.org/HttpLuaModule#ngx.ctx

Will update the github README accordingly once I have my laptop back ;)
