### ISSUE TITLE
error log: "attempt to yield across C-call boundary" when I send email by socket.smtp

### ISSUE THREAD

**Issue by fansaien** [openresty/lua-nginx-module#461]
@agentzh ,
I have used the ngx_openresty-1.7.0.1. It can send email by "socket.smtp", and the version luasocket-2.0.2.
When I upgrade the Openresty to ngx_openresty-1.7.7.2 or ngx_openresty-1.7.7.1, there will be an error message:"4129#0: *1056 lua entry thread aborted: runtime error: attempt to yield across C-call boundary" .

Thanks

**Comment by agentzh** [comment]
@fansaien You should not use luasocket in the context of ngx_lua because it's always blocking the nginx event loop, ruining the performance. Check out 3rd-party SMTP client libraries designed with OpenResty in mind. For example, https://github.com/duhoobo/lua-resty-smtp

**Comment by fansaien** [comment]
@agentzh Thank you very much for the prompt reply. I will try it.
