### ISSUE TITLE
Parse PHP array syntax

### ISSUE THREAD

**Issue by JoyceBabu** [openresty/lua-nginx-module#462]
Is it possible to read post data encoded in PHP array syntax? For example, to submit a JSON array `{a: [1, 2], b: 3}`, Lua module expects the data to be encoded as 

    a=1&a=2&b=3

PHP/Rails expects it to be encoded as 

    a[]=1&a[]=2&b=3

Some of the advantages of the above format are
- Support for arrays with single value
- Support for multi dimensional arrays
- This is the default serialization format for jQuery `$.post`/`$.get`

**Comment by agentzh** [comment]
@JoyceBabu It's already supported (though may not be exactly what you'd expect, but easy to fix by yourself). Consider the following minimal and standalone example (tested on my side):

```nginx
location = /t {
    content_by_lua '
        local cjson = require "cjson"
        ngx.req.read_body()
        local args = ngx.req.get_post_args()
        ngx.say(cjson.encode(args))
    ';
}
```

Then use your test request:

```
$ curl -d 'a[]=1&a[]=2&b=3' localhost:8080/t
{"b":"3","a[]":["1","2"]}
```

You still need to take into account the "a[]" key yourself though.

Regards,
-agentzh

**Comment by JoyceBabu** [comment]
Thank you for the reply @agentzh. But that will not work with multi-dimensional arrays.

**Comment by agentzh** [comment]
@JoyceBabu You can always construct such things yourself. ngx_lua is a low level platform and I don't want to implement all such nonstandard sugar and tricks in it.

**Comment by JoyceBabu** [comment]
Okay, thank you. I will try JSON encoding the data on client side and decoding it using cjson on lua side.

**Comment by agentzh** [comment]
Consider it resolved.
