### ISSUE TITLE
在使用 lua-nginx-module + graphicsmagick gm 时遇到404

### ISSUE THREAD

**Issue by jjc** [openresty/lua-nginx-module#463]
你好，亦春，我在使用 lua-nginx-module + graphicsmagick gm 时遇到404

nginx 1.6.2
lua-nginx-module 0.9.2

我在图片服务器(nginx)的 location 段中对图片进行了自动生成并获取，大概如下，里面没有rewrite

    location ~ .* {
        root /image;
        set $real_img = ...;
        if (!-f $real_img) {
            rewrite_by_lua '
                command = "gm convert +profile ... " .. ngx.var.real_img;
                os.execute(command);
            ';
        }
        expires      1y;
    }

**结果是即时请求的图片无法获取，nginx返回 404，但观察服务器是有生成的，路径正确；再次刷新正常**

我看了文档 http://wiki.nginx.org/HttpLuaModule，rewrite_by_lua是顺序执行的(lua gm也是顺序？)，location段中没有其它的rewrite

请问这个如何解决？

**Comment by agentzh** [comment]
@jjc Please, no Chinese here. This place is supposed to be English only. You can join the openresty (Chinese) mailing list if you preferred Chinese. Please see the mailing list information here: http://openresty.org/#Community

Regarding your question, the short answer is "If is evil":

http://wiki.nginx.org/IfIsEvil

Try avoiding it whenever possible.

Also, BTW, `os.execte()` always blocks the nginx event loop. Try avoiding it if possible too. If not, then ensure that the shell command will not run for long (better on or under the level of milliseconds).

**Comment by agentzh** [comment]
Consider it resolved.
