### ISSUE TITLE
Print(...) and ngx.log(ngx.NOTICE, ...) in "init_by_lua" context

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#467]
I'm trying to print a log message in the `init_by_lua` context, and I ended up with the following edge case:

* Using `print("Hello")` will successfully print the log message in the nginx log file.
* Using ngx.log(ngx.NOTICE, "Hello") won't print the same message in the log.

I've been checking the documentation and it says that [`print` is equivalent to `ngx.log(ngx.NOTICE, ...)`] [1]

The nginx configuration has the following error level set: `error_log logs/error.log debug;`

Why is this happening?

[1]: http://wiki.nginx.org/HttpLuaModule#print

**Comment by agentzh** [comment]
@thefosk I've just tested the following snippet on my side:

```nginx
    init_by_lua '
        ngx.log(ngx.NOTICE, "Hello") 
    ';
```

And it *does* emit the message to the nginx error log file:

```
2015/03/03 14:51:48 [notice] 12111#0: [lua] init_by_lua:2: Hello
```

I'm using ngx_lua 0.9.15 + nginx 1.7.10 (or OpenResty 1.7.10.1).

The `ngx.log()` is available in the context of `init_by_lua`. I'll fix the docs. Thanks for bringing this to my attention.

**Comment by agentzh** [comment]
@thefosk I've checked the docs and found `init_by_lua` is already listed in the "context:" list for `ngx.log`:

https://github.com/openresty/lua-nginx-module#ngxlog

Note the first one is `init_by_lua`. Am I missing anything here?

**Comment by thefosk** [comment]
@agentzh you are right. For some reason I couldn't see the message in the logs file and I guess it was because of a wrong log level setting in the `nginx.conf` file. I'll close this issue because it cannot be replicated.

**Comment by thefosk** [comment]
@agentzh I tried one more time and I could replicate the problem, I wasn't very clear in my first message so I will rephrase the issue.

Using `ngx.NOTICE` will print the log message, while using `ngx.INFO` won't do it, although the log level in the `nginx.conf` file is set to `debug` (which should print both `ngx.INFO` and `ngx.NOTICE` messages, according to the log level hierarchy documented at http://wiki.nginx.org/HttpLuaModule#Nginx_log_level_constants). 

Below a sample `nginx.conf` file:

```nginx
worker_processes auto;
error_log logs/error.log debug;
daemon off;

events {
  worker_connections  1024;
}

http {
  init_by_lua "print('Using \"print\"');
               ngx.log(ngx.NOTICE, 'Using \"ngx.NOTICE\"');
               ngx.log(ngx.INFO, 'Using \"ngx.INFO\"')";
}
```

Executing `nginx -c nginx.conf -p .` will output the following logs:

```
015/03/17 16:17:39 [notice] 42617#0: [lua] init_by_lua:1: Using "print"
2015/03/17 16:17:39 [notice] 42617#0: [lua] init_by_lua:2: Using "ngx.NOTICE"
```

The log won't include the message printed with `ngx.INFO`.

**Comment by agentzh** [comment]
@thefosk This is a known limitation in the nginx core. Not only ngx_lua, all other nginx modules including the nginx core, all share this limitation.

Under the hood, the `init_by_lua` runs in the nginx configuration loading phase, so your `error_log` configuration does not take effect until the whole configuration is loaded successfully (due to the bootstrapping requirements: the configuration loading MAY fail). And nginx initially uses a logger with the NOTICE filtering level which is effect in the whole first configuration loading process (but not subsequent configuration reloading).

**Comment by thefosk** [comment]
@agentzh thank you, that wasn't clear at first glance.

**Comment by vespian** [comment]
@agentzh We have run into a very similar problem, it turns out that adding:
```
lua_shared_dict tmp 12k;
```
Into `http` section somehow forces Nginx to honour `error_log` settings for `init_by_lua` code. We are using OpenResty 1.9.15.1

**Comment by agentzh** [comment]
@vespian Yes, the presence of `lua_shared_dict` postpones the execution of the `init_by_lua*` handler *after* nginx initializes all its shm zones.

**Comment by agentzh** [comment]
@vespian That's just a happy side effect of `lua_shared_dict` :)
