### ISSUE TITLE
Consider replacing the submodule with a subrepo

### ISSUE THREAD

**Issue by ingydotnet** [openresty/lua-nginx-module#470]
See https://github.com/ingydotnet/git-subrepo#readme

I'll do it for you on the `subrepo` branch.

**Comment by agentzh** [comment]
@ingydotnet Ah, I was not aware that ngx_lua comes with a git submodule! Given that ngx_devel_kit is just an optional dependency, I'd rather remove this submodule :)

But your git-subrepo looks very interesting for our other git repos with meaningful submodules. I'll definitely try it out! Thank you very much for the pointer! It seems to me that wherever there is a sore point, there is Ingy :)

**Comment by agentzh** [comment]
@ingydotnet I've removed the submodule. Thanks for bringing it up to my attention :)

**Comment by ingydotnet** [comment]
Darn. Read your comment too late.

You can check out https://github.com/ingydotnet/lua-nginx-module/tree/subrepo

We could still try an opsboy-pgx subrepo. This would at least put one more
Pegex repo into the wild.

**Comment by agentzh** [comment]
@ingydotnet Thank you for the patch! I'm still thinking about submodule'ing all the dependencies for ngx_lua's test suite under `t/deps/` some time in the future :) Your work will not be wasted at any rate :)
