### ISSUE TITLE
lua-nginx-module-master solaris input config library location

### ISSUE THREAD

**Issue by CirrusThink** [openresty/lua-nginx-module#472]
Soalris 11.2  LUA Library location is in /opt/csw , how do I tell the config to look there ?

**Comment by agentzh** [comment]
@CirrusThink My suggestion is to avoid using the system Lua library. Because it's almost always sub-optimal. Try using the OpenResty bundle if possible:

    http://openresty.org/#Download

Regards,
-agentzh

**Comment by blablacio** [comment]
You should set LDFLAGS or LD_LIBRARY_PATH before running configure. Take a look at gcc or Sun Studio man pages for the correct environment variable to use.
Something like this should work: export LDFLAGS=/opt/csw

Anyway, it's always better to use the OpenResty bundle directly.

**Comment by CirrusThink** [comment]
LDFLAGS is an option but I would like to set that option only for the LUA libraries I downloaded from OPENCSW. Could I just add the path somewhere in the config file ?

**Comment by CirrusThink** [comment]
When I tun --add-module=/export/home/ladmin/lua-nginx-module-master LUAJIT_LIB=/opt/csw/lib/lua I get a ./configure: error: invalid option "LUAJIT_LIB=/opt/csw/lib/lua"

**Comment by blablacio** [comment]
Well, you should really take a look at the docs: https://github.com/openresty/lua-nginx-module#installation

As you see, you need to export LUAJIT_LIB, not every configure script allows passing environment variables like this. I've ran ngx_lua on Solaris a long time ago with a similar set up but can't recall if configuring it like this worked or I needed to export the environment variable.

Also, you may want to set LUA_LIB instead as I guess you're running against Lua and not LuaJIT.

**Comment by CirrusThink** [comment]
That was great input. The export did not work for me, next I went ahead and added those two in the config file
ls -l /usr/local/include/
-rw-r--r-- 1 root root  7344 Apr 12  2013 lauxlib.h
-rw-r--r-- 1 root root 13602 Feb 21 15:04 lua.h
-rw-r--r-- 1 root root   191 Dec 23  2004 lua.hpp
-rw-r--r-- 1 root root 15439 Nov 21  2013 luaconf.h
-rw-r--r-- 1 root root  1099 Apr 12  2013 lualib.h

ls -l /usr/local/lib/lua/5.2/luasql/
-rwxr-xr-x 1 root root 21776 Mar 16 17:13 postgres.so

so...
nano config
LUA_INC="/usr/local/include"
LUA_LIB="/usr/local/lib"
adding module in /export/home/ladmin/lua-nginx-module-master
checking for Lua library in /usr/local/lib and /usr/local/include (specified by the LUA_LIB and LUA_INC env) ... not found
            ./configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUA_LIB is defined as /usr/local/lib and LUA_INC (path for lua.h) is /usr/local/include, but we cannot find standard Lua there.
--------------------------------------------


so I am a little lost ....

**Comment by blablacio** [comment]
Do you have liblua-5.2.a/liblua-5.2.so under /usr/local/lib or whatever your actual path is?
Once again -- you really should try using the OpenResty bundle if that's an option.

**Comment by agentzh** [comment]
Hello!

On Mon, Mar 16, 2015 at 2:21 PM, Cirrus Thinking wrote:
> ls -l /usr/local/lib/lua/5.2/luasql/
> -rwxr-xr-x 1 root root 21776 Mar 16 17:13 postgres.so
>

Seems like your system Lua is 5.2? ngx_lua only works with the Lua 5.1
language (and LuaJIT speaks Lua 5.1 as well).

Also, mind you, luasql's postgres driver will block nginx's event
loop. You should always use those nonblocking lua-resty-* drivers like
lua-resty-postgres:

    https://github.com/azurewang/lua-resty-postgres

> LUA_INC="/usr/local/include"
> LUA_LIB="/usr/local/lib"
> adding module in /export/home/ladmin/lua-nginx-module-master
> checking for Lua library in /usr/local/lib and /usr/local/include (specified by the LUA_LIB and LUA_INC env) ... not found
>

If your Lua is 5.2 in that location, ngx_lua also reports "not found".
You can always check out the defailed errors in the file
`objs/autoconf.err`, BTW.

As I've said, using OpenResty is highly recommended. That can save
both your time and our time :)

Regards,
-agentzh

**Comment by CirrusThink** [comment]
I would not mind moving over to openresty but I am not familiar enough with yet to understand how to move away from our current deployment of passenger nginx moduel with added lua-nginx-module

**Comment by CirrusThink** [comment]
Ok so I headed over to the OpenResty site, I think I have a better understanding of it. Any feedback about using it with Phusion Passenger ?

**Comment by agentzh** [comment]
@CirrusThink OpenResty's build system is just a superset of nginx's. So just use your old way :)

**Comment by CirrusThink** [comment]
typically we deploy nginx via rvmsudo passenger-install-nginx 
I would have to see how that script is affected because typically it downloads and builds the sources. 
If you have some docs around about OpenResty with Phusion Passenger would be great

**Comment by CirrusThink** [comment]
BTW you where correct ! after installing 5.1 all worked as it should. Thank you for everything. 
I see in Passenger that there was a fix to compile correctly when nginx is with OpenResty. 
A little documentation would help go a long way to support changing to this format which looks like the right way to go

**Comment by CirrusThink** [comment]
well I may have spoken to early.
The module compiles but when I start everything up I see this .. not sure who is doing what 
[ Mar 16 23:47:20 Executing start method ("/lib/svc/method/svc-nginx start"). ]
Starting Nginx Web Server: nginx: [error] init_by_lua_file error: error loading module 'luasql.postgres' from file '/usr/local/lib/lua/5.1/luasql/postgres.so':
        dynamic libraries not enabled; check your Lua installation
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /opt/nginx/conf/postgres_connect.lua:1: in main chunk

**Comment by agentzh** [comment]
@CirrusThink You built your standard Lua 5.1 interpreter in the wrong way. You should enable dynamic library support in your Lua build. Alas. Please use OpenResty to avoid such issues.

As I've said, luasql.postgres will block your nginx event loop horribly and ruin the performance. Better use a nonblocking library like lua-resty-postgres intead (or doing subrequest to ngx_postgres module).

**Comment by CirrusThink** [comment]
@agentzh do you have a sample of OpenResty with passenger ?

**Comment by agentzh** [comment]
@CirrusThink Just use the classic `--add-module=PATH` option to add any 3rd-party modules as with nginx.

**Comment by agentzh** [comment]
@CirrusThink I don't think 3rd-party nginx modules should use any other ways.

**Comment by CirrusThink** [comment]
Uhmmso OpenResty installs just as a 3rd party ? --add-module=pathtoopenresty ?

**Comment by agentzh** [comment]
@CirrusThink No. OpenResty is superset of NGINX. 3rd-party nginx modules are *modules* or *addons*, by definition.

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by pahnin** [comment]
The problem I see with openresty is that you say in your documentation and everywhere to use openresty version of nginx and then we have to use add-module to add passenger. But why not make openresty modules work with system nginx? I'm not 100% familiar with how nginx works but from what I see all your answers point in one direction, simply use nginx provided by us and add whatever you want, while everyone is familiar with using nginx with passenger etc.

**Comment by pahnin** [comment]
Because of this I have to modify the service script to work with your nginx instead of picking system nginx. And another thing is lua rocks installs .lua files to /usr/local/share/lua/5.1/ and you install to /usr/local/openresty/lualib/ if both had installed into same location using system nginx would have worked fine.

**Comment by agentzh** [comment]
@pahnin No, OpenResty cannot simply use whatever existing nginx binaries already installed into your system. That just won't work really. Installing OpenResty Lua libraries into the default Lua library path does not make sense either, since those libraries will never work outside OpenResty anyway.

**Comment by agentzh** [comment]
BTW, you should add your own 3rd party nginx modules to OpenResty instead, using the same way as the official nginx (--add-module=PATH). But your own nginx modules are not tested and maintained by the OpenResty team, so you are at your own risk.
