### ISSUE TITLE
error when using socket (tcpsock:connect error)

### ISSUE THREAD

**Issue by ourstart** [openresty/lua-nginx-module#474]
hi,agentzh
   error when using sock:connect: [[[ failed to connect to 192.168.83.128 :no resolver defined to resolve "192.168.83.128 " ]]] ,nginx.conf like this: [[[ local ok, err = sock:connect(iplist[1],portlist[1]) ]]] ,iplist is a local ip list fetch in the previous context,portlist is a local port list.
   when i debug the code, it's ok to hard write ip and port like this: [[[ sock:connect("192.168.83.128",6666) ]]] , any solutions to my question?
   i think connect is not good support for variable, it only support domain or ip?

**Comment by agentzh** [comment]
@ourstart Please, no Chinese here. This place is supposed to be English only. If you really want to use Chinese, please use the openresty (Chinese) mailing list instead. Check out http://openresty.org/#Community for more details.

Regarding your question, the error message is self-explanatory IMHO. You just need to define a resolver via the official resolver directive of nginx:

http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver
