### ISSUE TITLE
Possible SEGFAULT when using raw downstream socket in two threads

### ISSUE THREAD

**Issue by aviramc** [openresty/lua-nginx-module#478]
I'm currently reviewing the changes that @agentzh and I made simultaneously in order to start using the mainline ngx_lua. One of the changes in the full duplex cosocket objects, a feature that I use for the raw downstream socket in my code.

I have had the following race condition in my code (which I resolved), and it seems that it happens in the mainline code as well:
* There is a thread reading from the raw downstream socket.
* There is a thread writing to the raw downstream socket.
* The two threads are blocking, but the reading thread started to block **after** the writing thread did. This would set `ctx->downstream_co_ctx` to the reading thread.
* The write handler of the request runs (`ngx_http_lua_wev_handler`). Since there is data to write, it fetches the reading thread from `ctx->downstream_co_ctx` and tries to run it.

In this case, the wrong code to run (i.e. the reading thread instead of the writing), and this may cause SEGFAULTs. The proper fix is using two co_ctx pointers for the downstream socket - `downstream_read_co_ctx` for reading and `downstream_write_co_ctx` for writing.

@agentzh , I will post a pull request soon, but if you have time, I'd love to hear what you think about it. The case itself is hard to reproduce (has happened to me in a load test about a year ago).

**Comment by agentzh** [comment]
@aviramc Yeah, I totally agree we need separate co_ctx pointers for the downstream socket as well. Patches welcome :)

**Comment by aviramc** [comment]
@agentzh , after researching this a bit, I've seen that the above scenario is not possible, but a similar race condition is:
* There is a thread reading from the raw downstream socket.
* There is a thread writing to the raw downstream socket.
* The two threads are blocking, but the reading thread started to block **after** the writing thread did. This would set `ctx->downstream_co_ctx` to the reading thread.
* The reading thread ends its receive before the writing thread does, and starts blocking on something else. This makes `coctx->data` to be changed to something that is not the downstream socket, but a different object.
* The write handler of the request runs (`ngx_http_lua_wev_handler`). Since there is data to write, it assumes that `ctx->downstream_co_ctx->data` is the downstream socket, but it isn't since `ctx->downstream_co_ctx` is pointing to the receiving thread. It tries to run `u->write_event_handler(r, u)`, which would probably cause a segfault.

The fix to this race condition is the same fix I've applied in the pull request. The test that reproduces this will be committed soon.

**Comment by agentzh** [comment]
@aviramc Excellent! Thanks for the hard work!

**Comment by agentzh** [comment]
Consider it resolved.
