### ISSUE TITLE
Some Nginx built-in headers not set/unset properly

### ISSUE THREAD

**Issue by aviramc** [openresty/lua-nginx-module#482]
I've noticed that the header `If-Match` doesn't get properly unset by the lua module. It seems that it is because it is not a considered a built in header in the `ngx_http_lua_headers_in.c` module (the array `ngx_http_lua_set_handlers`).

In addition to that, comparing the built-in headers in the Nginx code (`src/http/ngx_http_request.c:80` in Nginx 1.7.10) to this repository's code, it seems that there are a lot of headers that aren't considered as built-ins as well (e.g. `If-Unmodified-Since`, `Accept-Language` and some more). Is there a particular reason for that or should that be updated? To me it seems like some kind of a bug.

**Comment by agentzh** [comment]
@aviramc I think these were added to the nginx care after I implemented those parts in ngx_lua. That's why they are missing. Will you consider contributing a patch? ;) Thanks!

**Comment by aviramc** [comment]
@agentzh , working on it. Are there any built-in headers that you explicitly want *not* not handle?

**Comment by agentzh** [comment]
@aviramc Not any off the top of my head :)

**Comment by agentzh** [comment]
Consider it resolved.
