### ISSUE TITLE
Request headers not passed to ngx.location.capture

### ISSUE THREAD

**Issue by brycehemme** [openresty/lua-nginx-module#483]
When setting a request header using ngx.req.set_header and then calling ngx.location.capture for a location that contains a proxy_pass directive the set header does not get sent to the host defined by proxy_pass in certain cases. The specific example I've encountered is this -

In my content_by_lua_file file -
```
ngx.req.read_body()
ngx.req.set_header("Content-Type", "application/json")
ngx.location.capture("/my/endpoint", { method = ngx.HTTP_POST, body = my_json_str })
```

In the location called by ngx.location.capture -
```
location /my/endpoint {
        internal;
        proxy_pass https://some.host.com/api/service;
   }
```

As an example of the scenario that causes issues, the above passes the content type correctly when the user agent of the original request is set to -
```
curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
```
but it fails when the user agent of the original request is set to -
```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:28.0) Gecko/20100101 Firefox/28.0
```

This might be an issue with proxy_pass and not ngx.location.capture but I haven't been able to replicate the issue without using ngx.location.capture. I was able to avoid the issue by setting proxy_set_header but it does appear to be a potential bug.

**Comment by agentzh** [comment]
@brycehemme I've tried a minimal and standalone example below based on your code snippet and I cannot reproduce any issues.

```nginx
location = /t {
    content_by_lua '
        ngx.req.read_body()
        ngx.req.set_header("Content-Type", "application/json")
        local res = ngx.location.capture("/my/endpoint",
            { method = ngx.HTTP_POST, body = my_json_str })
        ngx.print(res.body)
    ';
}

location /my/endpoint {
    internal;
    proxy_pass http://127.0.0.1:$server_port/api/service;
}

# just to mock a backend endpoint
location = /api/service {
    content_by_lua '
        ngx.say(ngx.req.raw_header(true))
    ';
}
```

Now test your user-agent strings:

```
$ curl --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:28.0) Gecko/20100101 Firefox/28.0' localhost:8080/t
Host: 127.0.0.1:8080
Connection: close
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:28.0) Gecko/20100101 Firefox/28.0
Accept: */*
Content-Type: application/json

```

```
$ curl --user-agent 'curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2
/1.4.2' localhost:8080/t
Host: 127.0.0.1:8080
Connection: close
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Accept: */*
Content-Type: application/json

```

The output is the raw request header received by our mocked version of the backend server. We can see that both contain the expected "Content-Type: application/json" request header (set before `ngx.location.capture`).

You can run this code example on your side as well.

For your issue, I guess it's something in your backend instead of in nginx (including ngx_proxy and ngx_lua). If you still believes there's a bug on the nginx side, feel free to create a minimal and standalone example that can easily reproduce the issue on my side (as demonstrated above). Thank you!

**Comment by brycehemme** [comment]
Thanks for the quick response. I think I have found what is causing me to see this and your example to not display this issue. I am using ngx_http_auth_request_module and have an auth_request directive in the location that I hit initially. For example, add this to your example -

```
location = /auth {
        auth_request /t; 
        proxy_pass http://nginx.org;
    }   
```
You will see the issue with this change and hitting this location instead with your curl statements. You might need to log the headers since they won't print as the body due to using auth_request.

Thanks!

**Comment by agentzh** [comment]
@brycehemme I see. Never use `auth_request` with ngx_lua in a single main request. See

https://github.com/openresty/lua-nginx-module#locations-configured-by-subrequest-directives-of-other-modules

The simplest way is just to replace `auth_request` with `access_by_lua` and put everything in your original `content_by_lua` there. This way you can also save one subrequest and make it faster.

**Comment by brycehemme** [comment]
This resolved the issue. Thanks for the additional info!
