### ISSUE TITLE
set_by_lua variables not accessible both on request and response phase

### ISSUE THREAD

**Issue by dsanthosh** [openresty/lua-nginx-module#487]
I am trying to set a variable using set_by_lua and tried accessing it both during the request and response phase but the variable isnt visible. Can the variable set using set_by_lua be accessed during one of these phases.

**Comment by agentzh** [comment]
@dsanthosh Please provide a minimal and standalone example that can demonstrate the problem. Without seeing your actual code and configuration, I cannot help you with just my imagination :)

**Comment by dsanthosh** [comment]
@agentzh Thank you for your response, I figured it out, the problem was because of an error in my code. Please feel free to close this issue.

Is there a better documentation that you can point me to on how the variables are exposed to different phases.

**Comment by agentzh** [comment]
@dsanthosh See http://openresty.org/#eBooks
