### ISSUE TITLE
Setting response headers

### ISSUE THREAD

**Issue by ikhoyo** [openresty/lua-nginx-module#49]
I'm having problems setting response headers. I've tried

ngx.set_header("Content-Type","text/html")
ngx.header.content_type = "text/html"
ngx.header["Content-Type"] = "text/html"

The Content-Type header is not set. Here is my location:

```
    location /identity {
        default_type text/html;
        lua_need_request_body on;
        client_max_body_size 10k;
        client_body_in_single_buffer on;
        content_by_lua_file /Users/william/biblegateway/identity/server/router.lua;
```

I've tried setting the headers both before and after any other response was generated, but there is nothing in the response.

**Comment by edo888** [comment]
Hi,

Sorry if I'm posting in a wrong place, I'm trying to change the response headers like this:

header_filter_by_lua 'ngx.header.content_type = "text/html"';

But the charset part of the content_type is not being changed and is left intact.

How can I modify the Content-Type charset?

Thanks!

**Comment by agentzh** [comment]
@edo888 Alas. You are indeed hijacking ancient unrelated tickets. Better ask on the openresty-en mailing list instead for such new-comer questions. Please see https://openresty.org/en/community.html
