### ISSUE TITLE
Nginx Plus: attempt to yield across metamethod/C-call boundary

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#490]
The following Lua code:

```
local sock = ngx.socket.tcp()
sock:connect(host, port)
```
is causing the following error:
```
attempt to yield across metamethod/C-call boundary

stack traceback:
	[C]: in function 'connect'
```

Using Nginx Plus with the Lua extension enabled: `nginx version: nginx/1.7.7 (nginx-plus-extras-r5-p3)`, and Lua `5.1.5`.

**Comment by agentzh** [comment]
@thefosk I guess you're using `pcall` or `xpcall` on the toplevel of your Lua code?

The short answer to your question is to link your Nginx Plus against LuaJIT 2 instead so as to obviate this limitation in the standard Lua 5.1 interpreter.

The long answer can be found below:

https://github.com/openresty/lua-nginx-module#lua-coroutine-yieldingresuming

**Comment by thefosk** [comment]
I tried to contact the Nginx team, but unfortunately it's not possible at the moment to make Nginx Plus work with LuaJIT.

**Comment by Sirupsen** [comment]
@thefosk you can just use `LD_LIBRARY_PATH`/`LD_PRELOAD` to override the shared library. It's kind of sketchy because the Nginx Plus Support Team won't support it properly, but we haven't run into issues. We'll be downgrading to vanilla Nginx because of this in the future

**Comment by thefosk** [comment]
@Sirupsen may I ask what value did you set up in your `LD_LIBRARY_PATH` environment variable?

**Comment by Sirupsen** [comment]
In `/etc/init.d/nginx` we have:

```bash
LD_LIBRARY_PATH="/etc/nginx/ld-overrides"
export LD_LIBRARY_PATH
```

Then in `/etc/nginx/ld-overrides` we override it (along with a couple of others):

```bash
$ ls /etc/nginx/ld-overrides/
libcrypto.so  liblua5.1.so.0  libz.so
```

**Comment by thefosk** [comment]
Thank you, that helped. I can go ahead and close this issue since the workaround works, I will try to ping the nginx team for a better way to support LuaJIT.

**Comment by Sirupsen** [comment]
@thefosk we've tried that already, no luck.
