### ISSUE TITLE
ngx.redirect not supporting 303

### ISSUE THREAD

**Issue by davidsnt** [openresty/lua-nginx-module#496]
I am trying to setup redirect with 303 and looks to be not working.

In my rewrite_by_lua_file, I have the following

res = ngx.location.capture(/blah)

if res.status == 303 then 
  ngx.redirect(res.header[location])
end

and if I try the ngx.redirect to force 303 then it returns the following error

lua entry thread aborted: runtime error: only ngx.HTTP_MOVED_TEMPORARILY and ngx.HTTP_MOVED_PERMANENTLY are allowed

Am I missing something?

Running nginx 1.6.1

The question is how do is send 303 back to the client with ngx.redirect?

**Comment by davidsnt** [comment]
Not an issue, incorrect handling of 303. Fixed with the following,

if res.status = 303 then
  ngx.header["Location"] = res.location
  return ngx.exit(303)
end

**Comment by RammusXu** [comment]
`res.location` is nil...

**Comment by agentzh** [comment]
@RammusXu I don't think there is such a `res.location` field. Please read the documentation for this API. BTW, please do not hijack old closed issues for your new issues. Thank you for your cooperation.
