### ISSUE TITLE
Compilation Error on Nginx 1.9.0

### ISSUE THREAD

**Issue by charlesportwoodii** [openresty/lua-nginx-module#499]
When I try to compile lua-nginx-module against 1.9.0 I am presented with a compilation error. It looks like an API change on Nginx's end. Just wanted to file a bug report. I fully expected something to break when 1.9.0 was announced.

Please let me know if you require more information from me. Thanks!

#### Environment

Ubuntu 14.04 LTS x86_64

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux <hostname> 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### Expected Result

Make builds Nginx with the lua-nginx-module.

#### Actual Result

Make encounters a compilation error on 1.9.0

#### Reproduction Steps

Here's the exact CLI commands I am running to get Lua compiled (should be able to copy/paste directly to terminal). Note, LuaJit is already installed on this system.

```
# Download nginx 1.9.0
wget http://nginx.org/download/nginx-1.9.0.tar.gz
tar -xf nginx-1.9.0.tar.gz

# Create a modules directory
cd nginx-1.9.0/
mkdir -p modules
cd modules

# Clone the latest tag of lua-nginx-module
git clone https://github.com/openresty/lua-nginx-module
cd lua-nginx-module/
git checkout master
cd ..

# Clone the latest tag of ngx_devel_kit
git clone https://github.com/simpl/ngx_devel_kit
cd ngx_devel_kit
git checkout v0.2.19
cd ../..
```

# Building

Configuring works
```
./configure \
        --add-module=modules/ngx_devel_kit \
        --add-module=modules/lua-nginx-module
```

Then make fails with the following error:

```
modules/lua-nginx-module/src/ngx_http_lua_initworkerby.c: In function ‘ngx_http_lua_init_worker’:
modules/lua-nginx-module/src/ngx_http_lua_initworkerby.c:230:5: error: implicit declaration of function ‘ngx_http_set_connection_log’ [-Werror=implicit-function-declaration]
     ngx_http_set_connection_log(r->connection, clcf->error_log);
     ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_lua_initworkerby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/nginx-1.9.0'
make: *** [build] Error 2
```

# Edit:
Full output of ```./configure```: https://gist.github.com/charlesportwoodii/1aba3a3b0c1f366af624
Full output of ```make```: https://gist.github.com/charlesportwoodii/80b23d125b1f72456a6a

**Comment by msva** [comment]
reference: http://hg.nginx.org/nginx/rev/187aa751ad62

Please, don't merge commits above. Right way is to just rename function here.

**Comment by msva** [comment]
reference: http://hg.nginx.org/nginx/rev/187aa751ad62

**Comment by msva** [comment]
btw, I think, it can be closed, as #500 superseeds this issue.

**Comment by charlesportwoodii** [comment]
Agreed

**Comment by yurevich1** [comment]
I think this bugfix is not in release mode. I've tried to build new version of nginx-1.9.5 with up-to-date version of lua-module.
The same error:

/nginx/debian/modules/lua-nginx-module/src/ngx_http_lua_initworkerby.c:230:5: error: implicit declaration of function 'ngx_http_set_connection_log' [-Werror=implicit-function-declaration]
     ngx_http_set_connection_log(r->connection, clcf->error_log);
     ^
