### ISSUE TITLE
error with nginx 1.9.0

### ISSUE THREAD

**Issue by shanmuha** [openresty/lua-nginx-module#506]
objs/addon/src/ngx_http_lua_initworkerby.o: In function `ngx_http_lua_init_worker':
ngx_http_lua_initworkerby.c:(.text+0x4d1): undefined reference to `ngx_http_set_connection_log'
objs/addon/src/ngx_http_lua_timer.o: In function `ngx_http_lua_timer_handler':
ngx_http_lua_timer.c:(.text+0x503): undefined reference to `ngx_http_set_connection_log'
collect2: error: ld returned 1 exit status
objs/Makefile:395: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1

Thanks!

**Comment by jcadduono** [comment]
Looks like nginx renamed ngx_http_set_connection_log to... **ngx_set_connection_log**!

You'll want to open navigate to *lua-nginx-module/src* and open the files *ngx_http_lua_timer.c* and *ngx_http_lua_initworkerby.c* in a text editor.

Search for this: (ctrl+f *http_set_conn*)

```c
#if defined(nginx_version) && nginx_version >= 1003014

    ngx_http_set_connection_log(r->connection, clcf->error_log);

else
```

Change it to:

```c
#if defined(nginx_version) && nginx_version >= 1009000

    ngx_set_connection_log(r->connection, clcf->error_log);

#elif defined(nginx_version) && nginx_version >= 1003014

    ngx_http_set_connection_log(r->connection, clcf->error_log);

#else
```

It should then compile without error. (but remember, it's in 2 files!)

**Comment by blablacio** [comment]
Already reported numerous times, see #500.

**Comment by misiek08** [comment]
Is the module still production ready with nginx 1.9.0? Did anyone do tests and have all passed?

**Comment by agentzh** [comment]
@shanmuha This compilation issue is already fixed in git master.

@misiek08 This module has not yet been officially tested with nginx 1.9.x though I'd like to do that after OpenResty 1.7.10.2 is out.
