### ISSUE TITLE
ngx_openresty-1.7.10.1 Debian 8 "Unsupported target architecture" error

### ISSUE THREAD

**Issue by adolgoff** [openresty/lua-nginx-module#507]
/home/username/ngx_openresty-1.7.10.1 # ./configure
platform: linux (linux)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20150223
make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-alpha ====
make -C src
make[1]: Entering directory '/home/username/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
Makefile:232: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory '/home/username/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
Makefile:105: recipe for target 'default' failed
make: *** [default] Error 2
ERROR: failed to run command: make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit

**Comment by blablacio** [comment]
You don't seem to have a C compiler installed or it's installed in an unusual location.
Try installing gcc and run configure again. If you already have a C compiler then just do *export CC=/path/to/gcc* and retry.

**Comment by adolgoff** [comment]
Thanks, reinstalling build-essential has helped!
