### ISSUE TITLE
can get post data just like php $_post[name]?

### ISSUE THREAD

**Issue by javacty** [openresty/lua-nginx-module#509]
current, just ngx.var.request_body get raw post data and parse it by myself?

another,ngx.req.get_post_args() ,I think it has a problem  in key and value:

args = ngx.req.get_post_args()
for key, val in pairs(args) do
		ngx.say(key, "::::: ", val)
end

------WebKitFormBoundaryKhKBblFwwrV4QLPi
Content-Disposition: form-data; name::::: "file1_name"

新建位图图像.bmp
------WebKitFormBoundaryKhKBblFwwrV4QLPi

**Comment by chrislovecnm** [comment]
from the docs:

Returns a Lua table holding all the current request POST query arguments (of the MIME type application/x-www-form-urlencoded). Call ngx.req.read_body to read the request body first or turn on the lua_need_request_body directive to avoid errors.

https://github.com/openresty/lua-nginx-module#ngxreqget_post_args

You need to reference the item in the lua table.  Not sure what your lua experience is so here: http://lua-users.org/wiki/TablesTutorial

**Comment by javacty** [comment]
first, thank you answer.
but I had test the code in https://github.com/openresty/lua-nginx-module#ngxreqget_post_args:

ngx.req.read_body()
local args = ngx.req.get_post_args()

for key, val in pairs(args) do
             if type(val) == "table" then
                 ngx.say(key, "::::: ", table.concat(val, ", "))
             else
                 ngx.say(key, "::::: ", val)
             end
end

the restult is the same with up:
------WebKitFormBoundaryNZyBiXMtyl8dBpQF
Content-Disposition: form-data; name::: "file1_name"

新建位图图像.bmp
------WebKitFormBoundaryNZyBiXMtyl8dBpQF

what important is that my form method is "post":
<form name="upload" method="POST" enctype="multipart/form-data" action="/upload?a=000">
if the method is get ,just like doc give :curl --data 'foo=bar&bar=baz&bar=blah' localhost/test"  the result is ok !

so if the method post ,who can give me a function decode (or spilit) post data to array or table, my handle progress is:
function get_filename(res)
	--坑爹的lua 正则 单行模式和多行模式和别的语言刚好是相反的，几乎让我崩溃……
        --另外,好像别的语言\n可以同时代表\n和\r\n?
	local filename = ngx.re.match(res,'name="(.*?)"\r\n\r\n(.*?)\n------',"s")
    if filename then   
        return "filename[1].."："..filename[2]
    end  
end
just touch lua a little, so shamed……

**Comment by agentzh** [comment]
@javacty You're handling multipart request bodies. See the lua-resty-upload library which supports streaming processing huge uploads with (small) constant memory footprint:

https://github.com/openresty/lua-resty-upload

**Comment by javacty** [comment]
非常感谢章哥，不知 lua-resty-upload 和nginx-upload-module相比，在文件上传和mime解析上性能哪个更好？

I found a method to parse it according with http://wiki.nginx.org/HttpLuaModule#ngx.re.gmatch:
raw data:
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file1_name"

01.png
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file1_content_type"

image/png
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file1_path"

/tmp/nginx_upload/0000000001
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file1_md5"

ccea25bc393c99a5d477835e3c935f6d
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file1_size"

1258
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file2_name"

02.png
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file2_content_type"

image/png
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file2_path"

/tmp/nginx_upload/0000000002
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file2_md5"

4afed22a1eb90036ceb20c0ba1dbcc42
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file2_size"

1272
------WebKitFormBoundaryibLt7hH4RYRof3dc
Content-Disposition: form-data; name="file3_name"

Lua code:
    ngx.req.read_body()
    local args = ngx.var.request_body
    local it, err = ngx.re.gmatch(args,'name="(.*?)"\r\n\r\n(.*?)\r\n')
    while true do
        local m, err = it()
        if err then
            ngx.say(ngx.ERR, "error: ", err)
            return
        end
        if not m then            
            break
        end
 
        -- found a match
        ngx.say(m[1]..": "..m[2])
    end

result:
file1_name: 01.png
file1_content_type: image/png
file1_path: /tmp/nginx_upload/0000000001
file1_md5: ccea25bc393c99a5d477835e3c935f6d
file1_size: 1258
file2_name: 02.png
file2_content_type: image/png
file2_path: /tmp/nginx_upload/0000000002
file2_md5: 4afed22a1eb90036ceb20c0ba1dbcc42
file2_size: 1272

**Comment by agentzh** [comment]
@javacty Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see http://openresty.org/#Community Thanks for your cooperation!

Regarding your question, lua-resty-upload is a clear winner for large uploads because it supports non-buffered (or streaming) processing.

**Comment by 5977862** [comment]
Why not make form-date as normal form~ get a lua table~

**Comment by agentzh** [comment]
@5977862 Because the uploaded multipart form can be HUGE in which case streaming processing is key to performance and scalability :)

For urlencoded forms, you can always use the `ngx.req.get_post_args` method.

**Comment by bungle** [comment]
I think this does exactly what you want:
https://github.com/bungle/lua-resty-reqargs

```lua
local get, post, files = require "resty.reqargs"()
```

**Comment by 5977862** [comment]
@bungle we just process sample auth in nginx ~ thx for your code ~

@agentzh I just want get post data, the file in post we never process in nginx ~ so I think the function  which get all post data without file is useful~  ^_^

**Comment by bungle** [comment]
@5977862 I can add skip files etc. in that reqargs if you want.

**Comment by 5977862** [comment]
@bungle If do something with lua-resty-reqargs, then proxy_pass to another url,in the other url, can I get all date as same as from client?

I think add skip files is useful ~
