### ISSUE TITLE
SIGCHLD notification?

### ISSUE THREAD

**Issue by nelson2005** [openresty/lua-nginx-module#512]
I'm forking off child processes, and I'd like to get the exit codes but nginx seems to be picking them up and printing them to the log like

    unknown process 28319 exited with code 1

is there some way for my lua code to retrieve that information?  I wanted to use the luaposix wait function, but it never reaps any children because the nginx signal handler is doing it

**Comment by agentzh** [comment]
@nelson2005 You mean SIGCHLD received by individual nginx worker processes? If yes, then there is no existing ways to override the default nginx signal handler on the Lua land and...patches welcome :)

**Comment by nelson2005** [comment]
thanks.  I hacked the nginx signal handler so it only reaps process ids that it owns, then I used luaposix to reap the process ids that I'm managing.  I'll have to think about this some more, perhaps it would be better to have nginx send some notification to the backend.  Thanks for a cool project.
