### ISSUE TITLE
#在请求头中

### ISSUE THREAD

**Issue by samuelyao314** [openresty/lua-nginx-module#514]
HTTP GET请求中的参数 reason = '2##声音太小',   ngx.var.arg_reason 打印日志为  '2\x23\x23声音太小' ， 但是Lua 5.1不支持16进制格式在字符串中，不会进行转义。所有无法得到原先的字符串。

我的处理方法是：

local arg_reason = ngx.var.arg_reason
local reason = arg_reason:gsub("\\x(%x%x)",function (x) return string.char(tonumber(x,16)) end)

**Comment by agentzh** [comment]
@samuelyao314 FYI, this place is English only. So please do not use Chinese here. If you really want to use Chinese, please post to the openresty (Chinese) mailing list instead: http://openresty.org/#Community Thank you.

Regarding your problem, the \x23\x23 things are escaped sequences of the nginx *builtin logger*, which has nothing to do with ngx_lua or lua. You can try emitting the Lua string to your response body instead for debugging purposes.

**Comment by agentzh** [comment]
Consider it resolved.
