### ISSUE TITLE
Cannot get cookie

### ISSUE THREAD

**Issue by ojasojas** [openresty/lua-nginx-module#515]
Hi,

I got problem in getting cookie in Internet exploror 8.

That part of code is

#########################
local decObj = cjson.decode(ret.body)
local expires = 60 * 60

local binary = ndk.set_var.set_encrypt_session(decObj.name) 
local base32 = ndk.set_var.set_encode_base32(binary) 

ngx.header["Set-Cookie"] = "session=" .. base32 .. "; Expires=" .. ngx.cookie_time(ngx.time() + expires)

if ngx.var.cookie_session then
   ngx.log(ngx.ERR, "session exists")   
end

#########################

When I use Chrome, "session exists" log is printed.
But When I use Internet Explorer, the log is not printed.

Would you give me a help about this?

**Comment by agentzh** [comment]
@ojasojas Maybe you just forgot to enable cookies in your IE browser? Well, just guessing. For debugging such things, you can enable the nginx debugging logs:

http://nginx.org/en/docs/debugging_log.html

Use of tools like tcpdump or wireshark to inspect the packets sent by your IE browser may give you insights as well :)

Just my 2 cents.

**Comment by agentzh** [comment]
Consider it resolved.
