### ISSUE TITLE
nginx1.9.0 编译新版本报错～ ngx_http_set_connection_log不存在？thanks！

### ISSUE THREAD

**Issue by yiliaofan** [openresty/lua-nginx-module#516]
cc -c -I/home/zhangfan/nginx/lua/LuaJIT-2.0.4/src  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /home/zhangfan/nginx/lua/LuaJIT-2.0.4/src -I ../modules/lua-nginx-module-0.9.16rc1/src/api -I objs -I src/http -I src/http/modules -I src/mail -I src/stream \
		-o objs/addon/src/ngx_http_lua_initworkerby.o \
		../modules/lua-nginx-module-0.9.16rc1/src/ngx_http_lua_initworkerby.c
cc1: warnings being treated as errors
../modules/lua-nginx-module-0.9.16rc1/src/ngx_http_lua_initworkerby.c: 在函数‘ngx_http_lua_init_worker’中:
../modules/lua-nginx-module-0.9.16rc1/src/ngx_http_lua_initworkerby.c:230: 错误：隐式声明函数‘ngx_http_set_connection_log’
make[1]: *** [objs/addon/src/ngx_http_lua_initworkerby.o] 错误 1
make[1]: Leaving directory `/home/zhangfan/nginx/nginx-1.9.0'
make: *** [build] 错误 2

多谢！

**Comment by yiliaofan** [comment]
知道原因了。。
<pre>
-    ngx_http_set_connection_log(r->connection, clcf->error_log);
+    ngx_set_connection_log(r->connection, clcf->error_log);

</pre>

**Comment by nikolay** [comment]
@agentzh Will v0.9.16 be out soon? Many are waiting for it to upgrade Nginx to 1.9.0.

**Comment by agentzh** [comment]
@yiliaofan I believe the fix is already in the git master of this project. Try the latest git master on your side instead. BTW, please no Chinese here. If you really want to use Chinese, please join the OpenResty (Chinese) mailing list instead. Please see http://openresty.org/#Community

@nikolay Yes, I'm working on a new ngx_lua release.

**Comment by yiliaofan** [comment]
thank you~  Greate job
