### ISSUE TITLE
ngx.req.get_headers order

### ISSUE THREAD

**Issue by vladimir000** [openresty/lua-nginx-module#517]
Hi

I tried this code: https://github.com/openresty/lua-nginx-module#ngxreqget_headers

However it orders the headers in a specific way (order of processing?).

Is it possible to have them in the order sent by the client?

Thanks!

Vlad

**Comment by vladimir000** [comment]
I see it's a lua problem which has unordered tables

Is there a workaround you could implement? Would it be possible in some way to create 3 tables, with a numeric one that would link to 2 other tables?
Well any solution would work for me.
I think it would be a great addition, this is the best module to manipulate headers ..

**Comment by agentzh** [comment]
@vladimir000 The order usually does not matter at all. May I ask why you need the order in the first place? Maybe you really need the `ngx.req.raw_header` API function instead?

FWIW, I'm going to add a `ngx.req.get_header_list` function that returns an array of headers instead of a hash table.

**Comment by client9** [comment]
hello @agentzh  thanks for all your work with this.  It is a fantastic project.

Normally the order is not important.  But order matters for some people doing fraud detection.   Robots / Spammer will claim to be (for example) Chrome in the user agent, but the order of the request headers is different than what Chrome would do.

**Comment by agentzh** [comment]
@client9 Then I believe the raw header returned by `ngx.req.raw_header` is more appropriate for your purposes:

https://github.com/openresty/lua-nginx-module#ngxreqraw_header

**Comment by client9** [comment]
yeah thats great :-)  just explaining why someone might want headers in order.  
regards,
n

**Comment by agentzh** [comment]
Consider it resolved.
