### ISSUE TITLE
how to solve requesty body in temp file not supported

### ISSUE THREAD

**Issue by qiye** [openresty/lua-nginx-module#521]
luajit2.1
nginx version: nginx/1.8.0

[root@Test conf]# tail -f /usr/local/nginx/logs/error.log 
2015/06/02 17:55:55 [error] 26589#0: *1 open() "/usr/local/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.56.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.56.101"
2015/06/02 18:01:40 [error] 26686#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:55):1: requesty body in temp file not supported
stack traceback:
coroutine 0:
        [C]: in function 'get_post_args'
        content_by_lua(nginx.conf:55):1: in function <content_by_lua(nginx.conf:55):1>, client: 192.168.56.1, server: localhost, request: "POST /request_body HTTP/1.1", host: "192.168.56.101

nginx.conf

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

     location /request_body {
          # force reading request body (default off)
          default_type 'text/html';
          lua_need_request_body on;
          client_max_body_size 100m;
          client_body_buffer_size 128k;

          content_by_lua 'ngx.req.read_body();local args = ngx.req.get_post_args();ngx.say(args["data"])';
     }
}}

**Comment by doujiang24** [comment]
you have to config `client_body_buffer_size` equal `client_max_body_size`

**Comment by agentzh** [comment]
@qiye Yes, as @doujiang24 said, you can get rid of this error by enforcing in-memory buffering of the whole request body.

Alternatively, you can read the in-file data and parse the format yourself via `ngx.req.get_body_file` and etc.
