### ISSUE TITLE
ngx.req.get_headers() does not return headers set by proxy_set_header

### ISSUE THREAD

**Issue by christopherdcunha** [openresty/lua-nginx-module#522]
(I think this relates to https://github.com/openresty/lua-nginx-module/issues/437)

Why doesn't `ngx.req.get_headers()` return headers set by `proxy_set_header`? I can see that `ngx.req.raw_header()` has all the correct headers but `ngx.req.get_headers()` is missing ones set by `proxy_set_header`.

This is the configuration I have:

```nginx
http {
    server {
        listen 8081;

        location /my-resource {
            default_type text/plain;

            access_by_lua '
                ngx.say(ngx.req.raw_header())

                local h = ngx.req.get_headers()
                for k, v in pairs(h) do
                    ngx.say(k, ": ", v)
                end

                return
            ';

            content_by_lua '
                ngx.say("My Resource")
            ';
        }
    }

    server {
        listen 8080;

        location / {
            set_by_lua $user '
               return "my_user"
            ';

            proxy_set_header REMOTE_USER $user;
            proxy_pass http://localhost:8081;

        }
    }
}
```

And this is the result I get:

```bash
$ curl -v http://localhost:8080/my-resource
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /my-resource HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server openresty/1.7.10.1 is not blacklisted
< Server: openresty/1.7.10.1
< Date: Wed, 03 Jun 2015 11:17:35 GMT
< Content-Type: text/plain
< Content-Length: 218
< Connection: keep-alive
< 
GET /my-resource HTTP/1.0
REMOTE_USER: my_user
Host: localhost:8081
Connection: close
User-Agent: curl/7.35.0
Accept: */*


host: localhost:8081
accept: */*
user-agent: curl/7.35.0
connection: close
My Resource
* Connection #0 to host localhost left intact
```

As you can see, the first block of printed headers has "REMOTE_USER" and the second one does not. FYI, I also tried calling `get_headers(nil, true)` but it doesn't give me the extra header, just changes the casing (as mentioned in the docs).

I'm new to the nginx lua module so I don't know if I'm doing something wrong or if this is really a bug.

Thanks in advance for you help!

**Comment by doujiang24** [comment]
underscores in client request header fields is default disabled, you can config `underscores_in_headers on` [1]
or use REMOTE-USER instead.

[1] http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers

**Comment by christopherdcunha** [comment]
Thank you @doujiang24 !
