### ISSUE TITLE
Lua question

### ISSUE THREAD

**Issue by techpulse** [openresty/lua-nginx-module#523]
Hello there,

This is not a issue, but are there any where I can get support regarding it?

I would like to hire someone writing some small rules for me, such as "if cookie isset, else"..

**Comment by blablacio** [comment]
You should rather write to the mailing list: https://groups.google.com/forum/#!forum/openresty-en

And perhaps you could try Upwork or similar sites for hiring.

**Comment by techpulse** [comment]
Cheers, posted there now. I've been trying freelancer before but all I ended up with was some indians charging $100+ which is not very reliable.
