### ISSUE TITLE
Dynamic proxy_pass 

### ISSUE THREAD

**Issue by nezhazheng** [openresty/lua-nginx-module#526]
Here is my situation:
I have a api that do some request validation and judge which upstream should proxy_pass to.

My idea is set nginx var in lua, and use nginx 'if' syntax to proxy_pass to a specified upstream. 
But i can't do this in rewrite_by_lua, because if run before rewrite_by_lua.
And for some reason i can't use ngx.location.capture.

Could you give me any suggestion? 
Thanks a lot.

**Comment by agentzh** [comment]
@nezhazheng You may find the following demo helpful for your use case:

https://openresty.org/#DynamicRoutingBasedOnRedis

As you might have noticed, we avoid using nginx's "if" directive but using Lua's native if statement in `access_by_lua` instead because nginx's if is evil:

http://wiki.nginx.org/IfIsEvil

**Comment by agentzh** [comment]
@nezhazheng BTW, such general questions should go to the openresty-en mailing list instead. Please see

https://openresty.org/#Community

**Comment by nezhazheng** [comment]
@agentzh Thanks for you feedback, demo is inspired.
In my lua, i call backend api to determine that should return api result to client directly or to continue nginx process(proxy_pass).
That't means proxy_pass is not nessecery.
Now i use ngx.eof() when i do not need proxy_pass. Because i do some test and looks like  proxy_pass will not run when i call ngx.eof().

Is it the best way to implement this requirement.

**Comment by agentzh** [comment]
@nezhazheng The correct way to short-circuit the request processing in `rewrite_by_lua` or `access_by_lua` is to call `ngx.exit` with a status code (>= 200). Or example,

```nginx
rewrite_by_lua 'ngx.exit(200)';
proxy_pass ...
```

will always bypass the `proxy_pass` thing.
