### ISSUE TITLE
proxing requests using ngx.location.capture

### ISSUE THREAD

**Issue by alexsv** [openresty/lua-nginx-module#528]
When I do request to nginx, which then bypasses request to some upstream:
GET /path/?param=1 2 HTTP/1.1
it works,

but if I want to do
ngx.location.capture('/path/?param=1 2') it fails with 400 Bad Request error.

The idea is bypass requests as - is.
Any suggestions?

**Comment by agentzh** [comment]
@alexsv You provided too little information for me to help you. Please see the following FAQ for details on how to report a problem properly:

http://openresty.org/faq.html#how-should-i-report-a-problem

**Comment by agentzh** [comment]
Consider it resolved.
