### ISSUE TITLE
lua nginx module 0.9.15 failed to compile with nginx 1.8.0 when --with-threads turned on

### ISSUE THREAD

**Issue by somsak** [openresty/lua-nginx-module#530]
Hello,

The compilation of 0.9.15 with Nginx 1.8.0 with --with-threads failed with the following errors.

cc -c -O2 -Wall -DFORTIFY_SOURCE=2 -fstack-protector  -DNDK_SET_VAR -I/root/repo/nginx18/./nginx-rtmp-module-1.1.7      -I/usr/include/apr-1.0       -I/usr/include/apr-1.0 -I/usr/include     -I/usr/include/apache2     -I/usr/include/libxml2          -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY          -DWITH_APU_CRYPTO -DWITH_REMOTE_RULES                 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /root/repo/nginx18/./ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I /usr/include/luajit-2.0 -I /root/repo/nginx18/./lua-nginx-module-0.9.15/src/api -I /root/repo/nginx18/./nginx-push-stream-module-0.5.1/src -I /root/repo/nginx18/./nginx-push-stream-module-0.5.1/include -I /root/repo/nginx18/./modsecurity-2.9.0/nginx/modsecurity -I /root/repo/nginx18/./modsecurity-2.9.0/nginx/modsecurity/../../standalone -I /root/repo/nginx18/./modsecurity-2.9.0/nginx/modsecurity/../../apache2 -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I /root/repo/nginx18/./ngx_devel_kit-0.2.19/src -I src/mail \
                -o objs/addon/src/ngx_http_lua_req_method.o \
                /root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_req_method.c
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c: In function ‘ngx_http_lua_udp_connect’:
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1407:8: error: ‘ngx_event_t’ has no member named ‘lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1407:19: error: ‘ngx_connection_t’ has no member named ‘lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1408:8: error: ‘ngx_event_t’ has no member named ‘lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1408:19: error: ‘ngx_connection_t’ has no member named ‘lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1409:8: error: ‘ngx_event_t’ has no member named ‘own_lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1409:23: error: ‘ngx_connection_t’ has no member named ‘lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1410:8: error: ‘ngx_event_t’ has no member named ‘own_lock’
/root/repo/nginx18/./lua-nginx-module-0.9.15/src/ngx_http_lua_socket_udp.c:1410:23: error: ‘ngx_connection_t’ has no member named ‘lock’
make[2]: *** [objs/addon/src/ngx_http_lua_socket_udp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/var/tmp/nginx-1.8.0-buildroot/nginx-1.8.0'

Are there anyway to workaround this problem? We need with-threads to cope up with I/O loads on the server.

**Comment by agentzh** [comment]
@somsak I believe this has already been fixed in the latest git master branch:

https://github.com/openresty/lua-nginx-module

**Comment by agentzh** [comment]
@somsak Caution: ngx_lua has only been officially tested with nginx 1.7.10 and earlier so far. Use of 1.8.x is at your own risk at the moment even if it can be compiled successfully.

**Comment by somsak** [comment]
Thanks a lot!

Yes, we are ready to take some risk :).
