### ISSUE TITLE
issues about TOC

### ISSUE THREAD

**Issue by ssdr** [openresty/lua-nginx-module#532]
hey,
I wanna TOC in Chinese, but in-page link seems doesn't work in Chinese, any sugguestions? please help...

**Comment by agentzh** [comment]
@ssdr Sorry but I cannot parse your question. More details? BTW, such general questions should go to the openresty-en or openresty (Chinese) mailing list instead. Please see

https://openresty.org/#Community

**Comment by agentzh** [comment]
Consider it resolved.
