### ISSUE TITLE
1.8.x Stable Version

### ISSUE THREAD

**Issue by apeschel** [openresty/lua-nginx-module#539]
Hello,

We are interested in rolling out 1.8.X with this module. How much work is required to get a stable version of this module for the 1.8.X line?

**Comment by agentzh** [comment]
The latest git master HEAD of this module should already be stable enough for nginx 1.8.x. A tagged release will come very soon.

**Comment by apeschel** [comment]
That is great news! Please let me know if you would like some assistance finalizing any work that needs to be done for a tagged release. This would be helpful for my team.

**Comment by agentzh** [comment]
@apeschel I've checked it and the existing tagged release v0.9.16 should serve your purposes well.
