### ISSUE TITLE
[ssl-cert-by-lua] Implicit declaration error

### ISSUE THREAD

**Issue by greggilbert** [openresty/lua-nginx-module#540]
So I'm trying to compile nginx using the `ssl-cert-by-lua` version.

Here's the command I'm running:

`cd /tmp/nginx-1.9.3 && ./configure --with-http_ssl_module --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --without-http_fastcgi_module --without-http_geo_module --without-http_memcached_module --without-http_scgi_module --without-http_uwsgi_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_ssl_module --with-http_stub_status_module --with-http_gzip_static_module --add-module=/tmp/ngx_devel_kit-0.2.19 --add-module=/tmp/ngx_postgres-1.0rc7 --add-module=/tmp/ngx_lua --with-ld-opt=-Wl,-rpath,/usr/local/lib && make && make install`

It fails out with this:
```
/tmp/ngx_lua/src/ngx_http_lua_module.c: In function ‘ngx_http_lua_merge_srv_conf’:
/tmp/ngx_lua/src/ngx_http_lua_module.c:749:9: error: implicit declaration of function ‘SSL_CTX_set_cert_cb’ [-Werror=implicit-function-declaration]
         SSL_CTX_set_cert_cb(sscf->ssl.ctx, ngx_http_lua_ssl_cert_handler, NULL);
```

Any idea what's wrong? `/tmp_ngx_lua` was made by checking out the proper branch (latest commit `b4eeb04a04f984b19470b6ee2fcabb88c9072975`). For reference, this is Lua 5.1.5 and LuaJIT 2.0.4.

**Comment by agentzh** [comment]
@greggilbert This is because your OpenSSL is not recent enough. At least OpenSSL 1.0.2 is required. The newer, the better (IIRC, some early RC releases of OpenSSL 1.0.2 has bugs that break `ssl_certificate_by_lua` in special cases).

**Comment by greggilbert** [comment]
@agentzh Thanks for the quick update! I just compiled 1.0.2d and tried rebuilding, and got:

```
/tmp/ngx_lua/src/ngx_http_lua_util.c: In function ‘ngx_http_lua_finalize_fake_request’:
/tmp/ngx_lua/src/ngx_http_lua_util.c:3569:42: error: ‘ngx_ssl_connection_t’ has no member named ‘lua_ctx’
                 if (c && c->ssl && c->ssl->lua_ctx) {
                                          ^
/tmp/ngx_lua/src/ngx_http_lua_util.c:3570:34: error: ‘ngx_ssl_connection_t’ has no member named ‘lua_ctx’
                     cctx = c->ssl->lua_ctx;
```

Do I need to update something else?

**Comment by agentzh** [comment]
@greggilbert You also need to apply the patch to your nginx core, as detailed here:

https://github.com/openresty/lua-nginx-module/issues/331#issuecomment-77279170

Please read my comment here carefully to save your time. Thanks!

**Comment by greggilbert** [comment]
Sorry about that - I somehow missed that comment. Everything works now! Thanks!
