### ISSUE TITLE
Return a different response based on the upstream response

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#545]
I am trying to handle the upstream response of a `proxy_pass` directive, and to return a different response status when certain headers are being returned by the upstream server.

To give an example, when the upstream server returns a `x-stop: true` header, the OpenResty application should return a `400 Bad Request` response.

Currently I am having an hard time implementing this functionality, since the output APIs are disabled in the `header_by_lua` directive. What would the best practice in this case?

**Comment by agentzh** [comment]
@thefosk It's easy. You just need to use `ngx.exit` in `header_filter_by_lua` to trigger so-called "filter finalization" in nginx:

```nginx
    header_filter_by_lua '
        local val = ngx.header["x-stop"]
        if val == "true" then
            return ngx.exit(400)
        end
    '
```

**Comment by thefosk** [comment]
@agentzh Thank you

**Comment by thefosk** [comment]
@agentzh Just one more comment on this issue. I am trying to set a header right before exiting, but that seems to not be working, like:

```lua
ngx.header["Hello"] = "World"
ngx.exit(429)
```

**Comment by agentzh** [comment]
@thefosk I cannot reproduce it on my side with OpenResty 1.9.3.1 using the following minimal example:

```nginx
    location = /t {
        echo ok;
        header_filter_by_lua '
            ngx.header["Hello"] = "World"
            ngx.exit(429)
        ';
    }
```

And then

```
$ curl -i localhost:8080/t
HTTP/1.1 429
Server: openresty/1.9.3.1
Date: Tue, 18 Aug 2015 04:25:15 GMT
Content-Length: 0
Connection: keep-alive
Hello: World
```

**Comment by thefosk** [comment]
@agentzh There was other *hidden* code conflicting with that specific code of mine, and that was the issue. Thanks for your patience in testing that out.

**Comment by agentzh** [comment]
@thefosk So you've got it working?

**Comment by thefosk** [comment]
Yes @agentzh

**Comment by kshitijmjoshi** [comment]
Is it possible to add headers to the return ngx.exit(302)?
I'm trying to redirect if for example x-stop: true
