### ISSUE TITLE
Modify response header when parsing response body

### ISSUE THREAD

**Issue by onexpiece** [openresty/lua-nginx-module#547]
I need to add a special header when the response body matches some rules. Can nginx-lua-module do this?

**Comment by agentzh** [comment]
@onexpiece Yes. But the details depend on how your response is generated in the first place. Assuming you are using ngx_proxy, then you can use `ngx.location.capture` to initiate a (fully-buffered) subrequest instead.

**Comment by agentzh** [comment]
Consider it resolved.
