### ISSUE TITLE
about lightuserdata's metatable of ngx.shared.DICT 

### ISSUE THREAD

**Issue by helloyi** [openresty/lua-nginx-module#548]
Hello!

Recently, I'm coding ngx.shrbtree.RBTREE(like ngx.shared.DICT, and support for table).
But, ngx.shrbtree.RBTREE conflict with ngx.shared.DICT.

# Description

These methods(set, add, etc.) of ngx.shared.DICT is nil, when I testing ngx.shrbtree.RBTREE.
Finally, I detect the bug. The reason is that __tables and full userdata have individual metatables,
and values of all other types(include lightuserdata) share one single metatable per type.__

I think there are two point in function ngx_http_lua_inject_shared_api:

1. If need set metatable for lightuserdata, and just set once.
2. A potential problem is that the metatable of lightuserdata would changed, if set metatable for lightuserdata. 

# Detail

That is the bug code. After this, I coding a demo to show this problem:

implement in ngx_http_lua_util.c:

    static void
    ngx_http_lua_inject_ngx_api(lua_State *L, ngx_http_lua_main_conf_t *lmcf,
        ngx_log_t *log)
    {
        // ......

        ngx_http_lua_inject_shdict_api(lmcf, L);

        // note, this after inject shdict api.
        ngx_http_lua_inject_shrbtree_api(lmcf, L);
    
        // ......
    }

implement in function ngx_http_lua_inject_shdict_api:
    
    // ......
    // set matatable of lightuserdata
    for (i = 0; i < lmcf->shm_zones->nelts; i++) {
        if (zone[i]->tag != (void *)&ngx_http_lua_module_shdict
            /* #define ngx_http_lua_module_shdict (ngx_http_lua_module.spare0) */
                                                           ) {
            continue;
        }
        ctx = zone[i]->data;

        lua_pushlstring(L, (char *) ctx->name.data, ctx->name.len);
            /* shared mt key */

        lua_pushlightuserdata(L, zone[i]); /* shared mt key ud */
        lua_pushvalue(L, -3); /* shared mt key ud mt */
        lua_setmetatable(L, -2); /* shared mt key ud */
        lua_rawset(L, -4); /* shared mt */
    }

implement in function ngx_http_lua_inject_shrbtree_api:

    // ......
    // set matatable of lightuserdata
    for (i = 0; i < lmcf->shm_zones->nelts; i++) {
        if (zone[i]->tag != (void *)&ngx_http_lua_module_shrbtree) {
            /* #define ngx_http_lua_module_shrbtree (ngx_http_lua_module.spare1) */
            continue;
        }
        ctx = zone[i]->data;

        lua_pushlstring(L, (char *) ctx->name.data, ctx->name.len);
        lua_pushlightuserdata(L, zone[i]);
        lua_pushvalue(L, -3);
        lua_setmetatable(L, -2);
        lua_rawset(L, -4);
    }

First, shdict api injected. After inject shrbtree api, the shdict api was replaced,
Because lightuserdata share one metatable.

Demo of show lightuserdata type share one single metatable:

    #include <stdio.h>
    #include <lua.h>
    #include <lauxlib.h>
    #include <lualib.h>

    int main() {
        lua_State *L;
        if(NULL == (L = luaL_newstate())) {
            perror("luaL_newstate failed");
            return -1;
        }
        luaL_openlibs(L);

        // construct metatable
        lua_newtable(L);
        lua_pushnumber(L, 1);
        lua_setfield(L, -2, "is1");
        lua_pushvalue(L, -1);
        lua_setfield(L, -2, "__index"); // [{is1=1, __index=(self)}]
        
        // set lightuserdata metatable
        lua_pushlightuserdata(L, (void *)0x11111111);
        lua_pushvalue(L, -2);
        lua_setmetatable(L, -2);
        lua_setglobal(L, "lightuserdata1");
        // _G["lightuserdata1"] = 0x11111111
        //                        |
        //                        V
        //                        mt = {is1=1, __index=(self)}
        if (luaL_dostring(L, 
                      "local print_ud = function(ud)    "
                      "    print(ud)                    "
                      "    local mt = getmetatable(ud)  "
                      "    for i, v in pairs(mt) do     "
                      "        print(i,' ', v)          "
                      "    end                          "
                      "end "
                      "print('after 0x11111111 setmetatable:') "
                      "print_ud(lightuserdata1)         "
                      "print('\\n') "
                      )) {

            printf("run lua error\n");
        }

        // just push lightuserdata
        lua_pushlightuserdata(L, (void *)0x22222222);
        lua_setglobal(L, "lightuserdata2");

        if (luaL_dostring(L,
                      "local print_ud = function(ud)"
                      "    print(ud)"
                      "    local mt = getmetatable(ud)"
                      "    for i, v in pairs(mt) do"
                      "        print(i,' ', v)"
                      "    end "
                      "end "
                      "print('after push 0x22222222, not metatable:') "
                      "print_ud(lightuserdata1) "
                      "print_ud(lightuserdata2) "
                      "print('\\n')"
                      )) {

            printf("run lua error\n");
        }

        // construct lightuserdata3
        // construct metatable
        lua_newtable(L);
        lua_pushnumber(L, 2);
        lua_setfield(L, -2, "is2");
        lua_pushvalue(L, -1);
        lua_setfield(L, -2, "__index"); // [{is1=1, __index=(self)}]
        
        // set lightuserdata metatable
        lua_pushlightuserdata(L, (void *)0x33333333);
        lua_pushvalue(L, -2);
        lua_setmetatable(L, -2);
        lua_setglobal(L, "lightuserdata3");
        // _G["lightuserdata3"] = 0x33333333
        //                        |
        //                        V
        //                        mt = {is2=2, __index=(self)}
    
        if (luaL_dostring(L,
                      "local print_ud = function(ud)"
                      "    print(ud)"
                      "    local mt = getmetatable(ud)"
                      "    for i, v in pairs(mt) do"
                      "        print(i,' ', v)"
                      "    end "
                      "end "
                      "print('after push 0x33333333, and set metatable:') "
                      "print_ud(lightuserdata1) "
                      "print_ud(lightuserdata2) "
                      "print_ud(lightuserdata3) "
                      "print('\\n')"
                      )) {

            printf("run lua error\n");
        }
        lua_close(L);
        return 0;
    }

output:

    after 0x11111111 setmetatable:
    userdata: 0x11111111
    is1	 	1.0
    __index	 	table: 0x209ad90
    
    
    after push 0x22222222, not metatable:
    userdata: 0x11111111
    is1	 	1.0
    __index	 	table: 0x209ad90
    userdata: 0x22222222
    is1	 	1.0
    __index	 	table: 0x209ad90
    
    
    after push 0x33333333, and set metatable:
    userdata: 0x11111111
    __index	 	table: 0x209c630
    is2	 	2.0
    userdata: 0x22222222
    __index	 	table: 0x209c630
    is2	 	2.0
    userdata: 0x33333333
    __index	 	table: 0x209c630
    is2	 	2.0

It show the problem.

# solution

Make tables for every ngx.shrbtree.RBTREE, to store the zone and share methods.
It look like "{zone = addr_of_zone}", then set metatable of this table.

        // in function ngx_http_lua_inject_shrbtree_api
        for (i = 0; i < lmcf->shm_zones->nelts; i++) {
            if (zone[i]->tag != (void *)&ngx_http_lua_module_shrbtree) {
                continue;
            }
            ctx = zone[i]->data;

            lua_pushlstring(L, (char *) ctx->name.data, ctx->name.len);
            lua_createtable(L, 0, 2);  // the zone table
            lua_pushlightuserdata(L, zone[i]);
            lua_setfield(L, -2, "zone");
            lua_pushvalue(L, -3);
            lua_setmetatable(L, -2); // set mt of zone table
            lua_rawset(L, -4);
        }

**Comment by agentzh** [comment]
@helloyi Oh yeah. That's indeed a problem. Lightuserdata share the metatable globally. Alas. Really dislike creating a stub Lua table just for this. But it seems that there's no better way.

Regarding your patch, I think just save the lightuserdata to the 1 index of the array part of the stub Lua table to avoid hash-table lookup overhead.

Will you please create a pull request for this?

Many thanks for the report!

**Comment by helloyi** [comment]
@agentzh You are great!  According to your suggestion, I have changed hash-table of same Lua tables to array in ngx.shared.RBTREE. I will create a pull request for ngx.shared.RBTREE  in the near time.

Thank you so much!

**Comment by agentzh** [comment]
@helloyi Cool. Thanks!

**Comment by Sirupsen** [comment]
this sounds like super interesting work @helloyi, in a situation right now where a shared red black tree would do wonders :)

**Comment by agentzh** [comment]
@helloyi FWIW, I'd like to expose a C API in ngx_lua (via the existing header file `ngx_http_lua_api.h`) that can make new lua_shared_dict variants easy and pluggable. Will you work on that also? It should be more motivating with a real plugin :) We could talk in another issue if you're interested.

**Comment by helloyi** [comment]
@Sirupsen You could see how to use it in [shdict-shrbtree-api-merge-shared-table test suit](https://github.com/helloyi/lua-nginx-module/blob/shdict-shrbtree-api-merge-shared-table/t/132-shrbtree.t).
And last code in [shdict-shrbtree-api-merge-shared-table](https://github.com/helloyi/lua-nginx-module/tree/shdict-shrbtree-api-merge-shared-table) branch.
We could talk more details if you're interested :).
Welcome correct, include my English :).

**Comment by helloyi** [comment]
@agentzh Yeah. I'm very interesting. It's a good way to pure coding. Thank you! :)
