### ISSUE TITLE
Retrieving the number of timers running

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#549]
Would it be possible to know how many timers are running at any given moment? This would be a useful information for applications that intensively use timers, to allow further tuning and optimizations.

Currently one solution to achieve this would be to increase a counter every time a timer starts, and decrease it when the function ends, but having a native way of doing this would probably be a cleaner solution.

**Comment by Sirupsen** [comment]
FYI we have a `monitor.lua` that goes from `ngx.cycle` to the `ngx_http_lua_main_conf_s` type to retrieve this information freely available on this struct, however, it'd be great if it was exposed directly.

**Comment by agentzh** [comment]
Well, we could have a `ngx.timer.pending_count()` and `ngx.timer.running_count()` Lua API functions exposed. Patches welcome :)

**Comment by Sirupsen** [comment]
Patch sent :)

**Comment by agentzh** [comment]
Consider it resolved.
