### ISSUE TITLE
Working with idn domains

### ISSUE THREAD

**Issue by Vittly** [openresty/lua-nginx-module#551]
Hello! How can I work with idn domains in openresty? I need encode-decode logic to match human-written hostname with host-header within http.

**Comment by agentzh** [comment]
@Vittly You can do the logic yourself in Lua. We're doing something similar at CloudFlare. Basically nginx and openresty does not try to make sense of the hostname encoding and simply treat them as byte strings.

**Comment by agentzh** [comment]
Consider it resolved.
