### ISSUE TITLE
ngx.req.set_header

### ISSUE THREAD

**Issue by gibatronic** [openresty/lua-nginx-module#553]
Hi! I'm trying to set the `Content-Type` header to `text/html` in a `content_by_lua_file` with no success.

nginx.conf:
```
location /lua {
	content_by_lua_file /fake/path/content.lua;
	lua_code_cache off;
}
```

content.lua:
```
ngx.req.set_header('Content-Type', 'text/html')
ngx.print('yo')
```

When I access `/lua` it defaults to `application/octet-stream`.
I'm running OS X 10.10.5 with nginx 1.8.0 and LuaJIT 2.0.4.

**Comment by gibatronic** [comment]
Oh... I see, my bad! I'm setting a request header however I should be setting a response header. But there's no `ngx.resp.set_headers`?

**Comment by bjoe2k4** [comment]
It's unprefixed, just `ngx.header`.

**Comment by gibatronic** [comment]
Awesome! Thanks @bjoe2k4!
