### ISSUE TITLE
failed in init_worker_by_lua

### ISSUE THREAD

**Issue by chiyouhen** [openresty/lua-nginx-module#554]
ngx_lua 0.9.16

an other module attempted to get server conf in merge server conf, but lua module didnot save it, so that module failed in merge server conf. then, lua failed to init worker process.

use 'get server conf' in merge conf is not well, but i think it should be a bug of lua module.

and i think the correct sequence should be like following.

```diff
--- tmp/lua-nginx-module-0.9.16/src/ngx_http_lua_initworkerby.c 2015-06-23 22:25:43.000000000 +0800
+++ ngx_http_lua_initworkerby.c 2015-08-27 16:39:49.507207468 +0800
@@ -166,6 +166,8 @@
             if (cur == NULL) {
                 return NGX_ERROR;
             }
+            /* save server conf before merge */
+            http_ctx.srv_conf[ngx_modules[i]->ctx_index] = cur;
 
             if (module->merge_srv_conf) {
                 prev = module->create_srv_conf(&conf);
@@ -179,7 +181,7 @@
                 }
             }
 
-            http_ctx.srv_conf[ngx_modules[i]->ctx_index] = cur;
+            /* http_ctx.srv_conf[ngx_modules[i]->ctx_index] = cur; */
         }
 
         if (module->create_loc_conf) {
```

functional testing has not been taken place, this diff is just used to talk about this case.

**Comment by agentzh** [comment]
> an other module attempted to get server conf in merge server conf

Could you please name a module of this kind? It'll be much easier for me if I can reproduce the issue on my side.

Thanks!

**Comment by chiyouhen** [comment]
to reproduce this issue, just write a small module, we call it fake here.

```c
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <nginx.h>

typedef struct {
    ngx_int_t i;
} ngx_http_fake_srv_conf_t;


static void *ngx_http_fake_create_srv_conf(ngx_conf_t *cf);
static char *ngx_http_fake_merge_srv_conf(ngx_conf_t *cf, void *prev, void *conf);

/* flow identify module configure struct */
static ngx_http_module_t  ngx_http_fake_module_ctx = {
    NULL,                           /* 4- preconfiguration */
    NULL,                           /* 8- postconfiguration */

    NULL,                           /* 1- create main configuration */
    NULL,                           /* 5- init main configuration (just after parse conf) */

    ngx_http_fake_create_srv_conf,  /* 2- create server configuration */
    ngx_http_fake_merge_srv_conf,   /* 6- merge server configuration */

    NULL,                           /* 3- create location configuration */
    NULL                            /* 7- merge location configuration */
};

/* flow identify module struct */
ngx_module_t  ngx_http_fake_module = {
    NGX_MODULE_V1,
    &ngx_http_fake_module_ctx,      /* module context */
    NULL,                           /* module directives */
    NGX_HTTP_MODULE,                /* module type */
    NULL,                           /* init master */
    NULL,                           /* init module */
    NULL,                           /* init process */
    NULL,                           /* init thread */
    NULL,                           /* exit thread */
    NULL,                           /* exit process */
    NULL,                           /* exit master */
    NGX_MODULE_V1_PADDING
};

/* create server configure */
static void *ngx_http_fake_create_srv_conf(ngx_conf_t *cf)
{
    ngx_http_fake_srv_conf_t   *fscf;

    fscf = ngx_pcalloc(cf->pool, sizeof(ngx_http_fake_srv_conf_t));
    if(fscf == NULL)
    {
        return NGX_CONF_ERROR;
    }

    return fscf;
}

/* merge server configure */
static char *ngx_http_fake_merge_srv_conf(ngx_conf_t *cf, void *prev, void *conf)
{
    ngx_http_fake_srv_conf_t   *fscf;
    
    fscf = ngx_http_conf_get_module_srv_conf(cf, ngx_http_fake_module);
    /* lua should return NULL */
    if(fscf == NULL)
    {
        ngx_conf_log_error(NGX_LOG_ALERT, cf, 0,
                "get module srv conf failed in merge srv conf");
        return NGX_CONF_ERROR;
    }
    ngx_conf_log_error(NGX_LOG_NOTICE, cf, 0,
            "merge srv conf ok");
    return NGX_CONF_OK;
}
```
then, compile this fake and lua-ngx into nginx, and set *init_worker_by_lua* in http block.
nginx would spawn no worker process.

**Comment by agentzh** [comment]
@chiyouhen Your fake module's code does not look reasonable to me. In the `ngx_http_fake_merge_srv_conf` function, why not just write the following?

```C
    ngx_http_fake_srv_conf_t   *fscf = cf;
```

It's not supposed to call ngx_http_conf_get_module_srv_conf there I'm afraid. None of the builtin nginx C modules that I'm aware do something like that.

**Comment by chiyouhen** [comment]
@agentzh 
yes, you are right. i do agree with you so much.

but, it is really a difference here in lua from the same conf processing in nginx http module. i think the same process should be the same behavior.

and, of course, i will push the author of 'an other module' to fix his code. but, as a most popular nginx module, lua-nginx need to be more patient to other developers. :)

**Comment by agentzh** [comment]
@chiyouhen I agree. I've committed a fix to git master. Please try it out on your side. Thanks!

**Comment by agentzh** [comment]
@chiyouhen Oh, BTW, I've included your test case (with the fake module) in ngx_lua's official test suite to cover this case. And I've fixed the case of loc_conf as well.

It's worth mentioning that I also fixed some obvious minor (unrelated) issues in your fake module code :)

**Comment by chiyouhen** [comment]
oh, i see it, thank you so much. i will improve my code style and take more care in details.
