### ISSUE TITLE
[ssl-cert-by-lua] -- problems with EV-SSL certs intermediates

### ISSUE THREAD

**Issue by andrea-spoldi** [openresty/lua-nginx-module#563]
Hi,
 I got a problem, happened with some customers now, with ssl-cert-by-lua and EV-SSL certs.

I don't know if it's related to ssl-cert-by-lua but if I use standard SSL nginx setup it just works.

Problems is with bundle certificates, there is no way I make it work for EV-SSL certificates (all the others are just okay). Every check I find on the internet reports errors, also testing with openssl as client

Any ideas ? which sort of info I can provide to help troubleshooting ? 

thanks.

regards

**Comment by agentzh** [comment]
@andrea-spoldi Please see the following document on how to report a problem effectively:

http://openresty.org/faq.html#how-should-i-report-a-problem

Thank you :)

The best thing for me is a standalone and minimal example that I can run and reproduce the problem locally on my side.

**Comment by andrea-spoldi** [comment]
@agentzh thanks for hints, here some more info 'bout my env

nginx -V
nginx version: openresty/1.7.10.1
built by gcc 4.7.2 (Debian 4.7.2-5) 
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx/nginx --with-cc-opt='-I/usr/src/ngx_openresty-1.7.10.1/build/luajit-root/etc/nginx/luajit/include/luajit-2.1 -O2' --add-module=../ngx_devel_kit-0.2.19 --add-module=../echo-nginx-module-0.57 --add-module=../xss-nginx-module-0.04 --add-module=../ngx_coolkit-0.2rc2 --add-module=../set-misc-nginx-module-0.28 --add-module=../form-input-nginx-module-0.10 --add-module=../encrypted-session-nginx-module-0.03 --add-module=../srcache-nginx-module-0.29 --add-module=../ngx_lua-0.9.15 --add-module=../ngx_lua_upstream-0.02 --add-module=../headers-more-nginx-module-0.25 --add-module=../array-var-nginx-module-0.03 --add-module=../memc-nginx-module-0.15 --add-module=../redis2-nginx-module-0.11 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.13 --add-module=../rds-csv-nginx-module-0.05 --with-ld-opt='-Wl,-rpath,/etc/nginx/luajit/lib -L/usr/src/ngx_openresty-1.7.10.1/build/luajit-root/etc/nginx/luajit/lib' --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-openssl=/usr/src/ngx_openresty-1.7.10.1/bundle/openssl-1.0.2a


Here's output from the working situation, with certificate assignment not managed by lua module : 

openssl s_client -connect XXXXX:443 -servername XXXXX
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=COMODO SSL Wildcard/CN=*.xxxxx.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 4 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Extended Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority
 5 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
-----BEGIN CERTIFICATE--------
...
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=COMODO SSL Wildcard/CN=*.xxxxx.com
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
---
SSL handshake has read 8550 bytes and written 535 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 7F9580090808C425195E0B431E6E2649AAB2E79C8E69E20E7E9E78CB704250A8
    Session-ID-ctx: 
    Master-Key: F9E61FDDFBFD81AF6D2BFBD903EE307895A4263AC4421997F0F126038D1BE33E369CEC1391DFFF161351A39137A4E437
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1441868555
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)

if I turn back to lua managed certificate, here's what I got

openssl s_client -connect <omitted>:443 -servername <omitted>
CONNECTED(00000003)
depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=COMODO SSL Wildcard/CN=*.xxxxx.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE--------
...
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=COMODO SSL Wildcard/CN=*.xxxxx.com
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
---
SSL handshake has read 2971 bytes and written 479 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 99437B312EFAC4ED10AD339436093813F0D1116B4A1FDDA7B6858C98CD735CB9
    Session-ID-ctx: 
    Master-Key: 87E25C8104486CA190D5B598BCA6E655E233C465AA6D74462085C3112E32CFD04885EB844F02B7B1692218BF060B5F63
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1441868798
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---

about the certificates, for the lua managed one I've appended the file with the bundle chain certificates from COMODO to the customer certificate file, and then converted it (plus the key file) from PEM to DER format with r509 ruby gem. I use the same method with other not EV-SSL certificates for my customers, and they all work good in any case

there are no errors in nginx logs, I'll try to produce debug logs as soon as I can recompile nginx 

thank you

A

**Comment by agentzh** [comment]
@andrea-spoldi Please use proper markdown notations for your comments. Your previous comment looks horrible both in the mail and in the web UI. Also, it might be a good idea to gather long text in 3rd-party pasting services like gist.github.com and simply to share the links here.

**Comment by agentzh** [comment]
@andrea-spoldi My hunch is that there might be some issues in your Lua code or in your bundle data or even in your OpenSSL (though the chance of hitting a bug in OpenSSL is relatively small). There is really no code paths in ngx_lua that is specific to EV-SSL certificates.

**Comment by andrea-spoldi** [comment]
@agentzh bundle data are just the same between "lua" and "not-lua" configurations, simply the "not-lua" one is a plain PEM file and the lua one is a DER file 
I also thought about OpenSSL but it should give the same error with or without lua in any case, I mean nginx should always use the openssl libraries I compiled it with

my lua code just works like the one showed with lua tests example 

```
	    -- load cert from SNI
	    local f, err = assert(io.open("/etc/nginx/ssl/" .. cert_name .. ".der"))
            local cert_data = f:read("*a")
            f:close()
	    -- set cert
	    local ok, err = ssl.set_der_cert(cert_data)
            if not ok then
                ngx.log(ngx.ERR, "failed to set DER cert: ", err)
                return
            end
```

the "cert_name" variable is might be the SNI value or the domain (extracted from SNI value) with "wc_" (stands for wildcard) prefix in front of it if

Maybe I should try to use openssl to transform PEM to DER instead of my ruby gem which might be bugged, or use the pem_to_der conversion bundled with ssl-cert-to-lua

I'll give it a shot and let you know

A

**Comment by agentzh** [comment]
Hello!

On Thu, Sep 10, 2015 at 3:12 PM, Andrea Spoldi wrote:
> if I turn back to lua managed certificate, here's what I got
>
> openssl s_client -connect :443 -servername
> CONNECTED(00000003)
> depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
> verify error:num=27:certificate not trusted
> verify return:1
> depth=0 OU = Domain Control Validated, OU = COMODO SSL Wildcard, CN = *.xxxxx.com
> verify error:num=21:unable to verify the first certificate
>

These output lines do not look right. It seems that your certificate
bundle is seriously messed up.

Also, you may also want to try (temporarily) enabling the nginx
debugging logs to get more details on the nginx side, which MAY give
us some more insight:

    http://nginx.org/en/docs/debugging_log.html

@lziest You may want to have a quick peek here?

Regards,
-agentzh

**Comment by andrea-spoldi** [comment]
@agentzh thank's for the hint, I will enable debug logs and give you back the result of it.
FYI, the certificate bundle I use (appended to the domain one, then it all turned to DER format) is just the same I use (again appended to the domain one) with the non-lua Nginx config. They could be messed up in a way 'cause bloody COMODO docs for proper chain is a mess, but with no-lua it just works.

I'll give you debug logs as soon as I can

Ty again

**Comment by loveshell** [comment]
I met the same problem, @andrea-spoldi are u sloved it?

**Comment by andrea-spoldi** [comment]
@loveshell not yet, had a couple more customers with same kind of cert and same problem, didn't have time to work with debug log really and kinda "can't" enable them on production 'cause it would produce loads of logs...

**Comment by lziest** [comment]
We have observed some EV cert that has some ASN.1 incompatibility with existing parsers. OpenSSL is being robust (or loose) on enforcing certain ASN.1 rules. We had a EV cert that can't parse with Go's X509 parser. @andrea-spoldi can you share your certificate chain in PEM? Maybe we can verify that. Also, please don't share private key. :)

**Comment by andrea-spoldi** [comment]
@lziest here's the last chain I found as not working and had to set up "manually" in the old fashioned way
http://pastebin.com/PLRXpPcs

Thank you.
A

**Comment by fvanniere** [comment]
There is only 1 certificate in the DER format, nginx reads PEM with 'SSL_CTX_use_certificate()' for the first certificate found and 'SSL_CTX_add_extra_chain_cert()' for the others. 

you need either 'ssl.set_pem_cert(cert_data)' or 'ssl.add_der_chain(cert_data)'

**Comment by fvanniere** [comment]
I've foud that `ssl.cert_pem_to_der` keeps the chain, you need to keep PEM cert and convert it to DER within lua  : 
`local ok, err = ssl.set_der_cert(ssl.cert_pem_to_der(cert_pem))`

**Comment by andrea-spoldi** [comment]
@fvanniere sorry but I don't understand...
till now I've always used this lua code as I showed before 

```
  -- load cert from SNI
        local f, err = assert(io.open("/etc/nginx/ssl/" .. cert_name .. ".der"))
            local cert_data = f:read("*a")
            f:close()
        -- set cert
        local ok, err = ssl.set_der_cert(cert_data)
            if not ok then
                ngx.log(ngx.ERR, "failed to set DER cert: ", err)
                return
            end
```

and it still does it OK for not-EV certs, I do convert from PEM to DER by OpenSSL, not using ssl.cert_pem_to_der, I always thought it could bring to some overhead so I avoided that, and thought it would be the same "ssl" wise...

in "my" way, checking the chain afterwards with either online tools or openssl just works okay with chain too ...so would it be possible that the "normal way" leaves the chain behind for EV stuff only ?

**Comment by fvanniere** [comment]
Convert back your .der to .pem with openssl, are the 2 certs inside ? (cert + chain)

**Comment by agentzh** [comment]
@andrea-spoldi You need to use ngx_lua's own `pem_to_der` API function to do the PEM -> DER conversion. I'm afraid the default openssl PEM -> DER toolchain does not support certificate chains at all in the DER output.

**Comment by agentzh** [comment]
@andrea-spoldi Also, you can always cache the DER output on the Lua land (via lua_shared_dict and/or lua-resty-lrucache) to reduce the `cert_pem_to_der` calls.

**Comment by agentzh** [comment]
Consider it resolved.
