### ISSUE TITLE
Feature suggestion: error_page_by_lua

### ISSUE THREAD

**Issue by bjoe2k4** [openresty/lua-nginx-module#578]
I am not sure if it is technically possible, therefore i am just asking it here (just a suggestion): i would really like to have an `error_page_by_lua` directive that would allow much more flexible and less painful error page configurations than the nginx core `error_page` + error location approach.

Basically `error_page_by_lua` could just override the built-in error pages without the need to configure a separate location for serving the custom/dynamic error pages which may be also very error prone, especially for new nginx users.

One of the reasons i am proposing this, is the complex configuration needed when having custom error pages + per location access logs. Part of this i already described on the nginx mailing list.
http://forum.nginx.org/read.php?2,261979,261979#msg-261979

Thanks for reading!

**Comment by agentzh** [comment]
@bjoe2k4 Use of the `error_page` directive is the right way to go. Your proposal won't fly without patching the NGINX core, which is quite undesired from the perspective of a 3rd-party module like ngx_lua (unless absolutely necessary).

**Comment by bjoe2k4** [comment]
I was already worried about nginx core maybe not allowing this easily, however i don't know much about nginx internals. Therefore thanks for evaluating!
