### ISSUE TITLE
ngx.re.quote

### ISSUE THREAD

**Issue by bungle** [openresty/lua-nginx-module#581]
Sometimes you build your regexes dynamically, and in these cases you may need to quote the dynamic part of it. It would be nice if lua-nginx-module provides a predefined `ngx.re.quote` function to do that, so that people don't need to reinvent the wheel, e.g. add backslash before these (are there others?):

`\ + * ? [ ^ ] $ ( ) { } = ! < > | : -`

**Comment by agentzh** [comment]
@bungle I think you can just use the `\Q...\E` regex construct to do this inline. Consider the following example,

```console
$ resty -e 'local m = ngx.re.match("aa?*bb", [[\Qa?*b\E]], "jo") print(m and m[0])'
a?*b
```

Will this trick suffice your needs?

**Comment by bungle** [comment]
Yes, thanks, wasn't aware of this.
