### ISSUE TITLE
how to interrupt tcpsock:receive() while nginx is shutting down?

### ISSUE THREAD

**Issue by chobits** [openresty/lua-nginx-module#582]
In `ngx.timer.**` context, I create one tcpsock and use `tcpsock:receive('*l')`API to receive data.

After reloading nginx, I found that `tcpsock:receive('*l')` would return until one line of text was received or timer set by `tcpsock:timeout()` expired.

Is there a way let `tcpsock:receive('*l')` return immediately  when nginx is exiting?

**Comment by agentzh** [comment]
@chobits This is what "graceful exit" means. Pending syscalls in nginx workers do not get interrupted during nginx reload or hot-binary-upgrade restart.

If you want to prevent such calls from lasting too long in a specific context, then you should really use shorter timeout thresholds for these cosockets and frequently check if the current worker is in existing mode via the `ngx.worker.exiting` API:

https://github.com/openresty/lua-nginx-module#ngxworkerexiting

BTW, you can always rerun the `receive` method on the same cosocket without re-connecting if the previous `receive` call returns the `timeout` error.

**Comment by agentzh** [comment]
@chobits Oh, BTW, such general questions should really go to the openresty-en mailing list instead. Please see

https://openresty.org/#Community

Thank you for your cooperation :)

**Comment by chobits** [comment]
> If you want to prevent such calls from lasting too long in a specific context, then you should really use shorter timeout thresholds for these cosockets and frequently check if the current worker is in exiting mode via the ngx.worker.exiting API:
> https://github.com/openresty/lua-nginx-module#ngxworkerexiting

Aha, that's what I did. And also I turned off 'lua_socket_log_errors', otherwise there were so many 'timed out' error log.

> Oh, BTW, such general questions should really go to the openresty-en mailing list ...

OK, I will try next time.

**Comment by agentzh** [comment]
Yeah, one should always do proper Lua-land cosocket error handling and turn off `lua_socket_log_errors` for production. That directive is just on by default for beginners :)

I'm closing this.
