### ISSUE TITLE
Problem with ngx.var.VARIABLE , $VARIABLE is empty

### ISSUE THREAD

**Issue by ehsan310** [openresty/lua-nginx-module#585]
Hello,

I have Lua script to capture information from a API location then parse json and set variable to use inside our html page, Everything is working great but the variable is empty outside of the Lua block.

I have tried to print out ngx.var inside content_by_lua via ngx.say and it seems than variable is not empty but outside of any Lua block i can't get the value of the vriable.

I have the latest openresty installation 1.9.3.1 

location /files/view/ {

        lua_need_request_body on; #location directive
        set $file_name '';
        rewrite_by_lua '
            function string:split(delimiter)
                local result = { }
                local from = 1
                local delim_from, delim_to = string.find( self, delimiter, from )
                while delim_from do
                    table.insert( result, string.sub( self, from , delim_from-1 ) )
                    from = delim_to + 1
                    delim_from, delim_to = string.find( self, delimiter, from )
                end
                table.insert( result, string.sub( self, from ) )
                return result
            end
            json = require("cjson")
            local path = ngx.var.request:split(" ")[2]
            local m = ngx.re.match(path,"/files/view/(?<token>.*)/(?<filename>.*)")
            local res = ngx.location.capture("/files/info/".. m["token"])
            local raw_json_text = res.body
            local lua_value = json.decode(raw_json_text)
            for key,val in pairs (lua_value) do
                if key == "name" then
                    ngx.vars.file_name = val
                end
            end
        ';
        

        set_if_empty $file_name 7654; ####$file_name is empty here 
        rewrite ^/files/view/(.*)/(.*)$ /download-$lang.html last;
    }

**Comment by ehsan310** [comment]
I found that , i didn't pay attention to this note in Nginx documentation 

"Note that this handler always runs after the standard ngx_http_rewrite_module."

So i have changed the last part of my config 
from
rewrite ^/files/view/(.*)/(.*)$ /download-$lang.html last;
to
try_files $uri /download-$lang.html;
and problem solved

**Comment by agentzh** [comment]
@ehsan310 Yeah, one has to pay attention to nginx's request processing phases while combining different nginx modules in the same context (location). Glad you figured it out yourself. I'm closing this.
