### ISSUE TITLE
The return value in the api "ngx_http_lua_find_zone" is wrong

### ISSUE THREAD

**Issue by qlee001** [openresty/lua-nginx-module#589]
//ngx_http_lua_shdict.c, line1700.  in function ngx_http_lua_find_zone()
//zone = part->elts, zone points to the start of the array. In the line 1731, return zone, but shared_memory matching the name is zone[i], Maybe here should be " return &zone[i]"
 
ngx_shm_zone_t *
ngx_http_lua_find_zone(u_char *name_data, size_t name_len)
{
    ngx_str_t                       *name;
    ngx_uint_t                       i;
    ngx_shm_zone_t                  *zone;
    volatile ngx_list_part_t        *part;

    part = &ngx_cycle->shared_memory.part;
    zone = part->elts;

    for (i = 0; /* void */ ; i++) {

        if (i >= part->nelts) {
            if (part->next == NULL) {
                break;
            }

            part = part->next;
            zone = part->elts;
            i = 0;
        }

        name = &zone[i].shm.name;

        dd("name: [%.*s] %d", (int) name->len, name->data, (int) name->len);
        dd("name2: [%.*s] %d", (int) name_len, name_data, (int) name_len);

        if (name->len == name_len
            && ngx_strncmp(name->data, name_data, name_len) == 0)
        {
            return zone;      //line 1731, Maybe here should be "return &zone[i]".
        }
    }

    return NULL;
}

**Comment by doujiang24** [comment]
@qlee001 Nice catch, I think you are right :+1:

**Comment by agentzh** [comment]
@qlee001 Oh, this is very very embarrassing. This serious bug has been lurking for years. We did notice some strange things before, either in multi-shdict benchmarking as well as in systemtap tool inspections (on the shm zones). This bug explains them all :)

I really owe you a beer, buddy :) Thank you so much!

**Comment by qlee001** [comment]
@agentzh  Your contribution to a opensource world make us develop the nginx module faster and easier.
Thank you too.

**Comment by agentzh** [comment]
Phew. The impact of this bug is very limited since the ngx_lua core does not make use of this `ngx_http_lua_find_zone` function. And no known out-of-tree users to my knowledge (I guess that you're making use of it on your side?).

**Comment by agentzh** [comment]
Just fixed in git master. Thanks!
