### ISSUE TITLE
set_by_lua not work

### ISSUE THREAD

**Issue by mysterytoo** [openresty/lua-nginx-module#591]
I have installed lua into nginx and modify the nginx.conf file as below, and run 'nginx -s reload', always get error 'unknown directive "set_by_lua"...', you know I also use 'content_by_lua' that works.
It's werid, I think lua-nginx-module installed successfully cause 'content_by_lua' works, but why 'set_by_lua' can't work?

    location / {
        #env AQM_STARTING;
        set_by_lua $f 'return os.getenv("AQM_STARTING")';       

        if ($f) {
          return 503;
        }
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8080;
    }

    location /hello {
        default_type 'text/plain';
        content_by_lua 'return ngx.say("hello james!")';
    }

**Comment by agentzh** [comment]
@mysterytoo To answer your question, I'd quote the documentation for set_by_lua:

> This directive requires the ngx_devel_kit module.

See https://github.com/openresty/lua-nginx-module#set_by_lua

So you won't have set_by_lua* if you don't have the ngx_devel_kit module compiled in.

This is also why it's recommended to use the OpenResty bundle instead of building nginx of your own:

https://openresty.org

**Comment by mysterytoo** [comment]
I have remove all the installed files related nginx and installed again. After that , 'set_by_lua' worked. I can get value by 'os.getenv("AQM_STARTING")', but when change this env. value in ubuntu command line, the value from 'os.getenv("AQM_STARTING")' still wasn't  changed. I need to stop nginx , and start again if I need to take the env. value effect in lua script. But why I can't dynamically get the env. value in nginx lua script?

**Comment by agentzh** [comment]
@mysterytoo For security reasons, nginx does not pass along all the system environments unconditionally. You need to be explicit here via the env directive:

http://nginx.org/en/docs/ngx_core_module.html#env

Oh, mind you, please do not hijack unrelated ticket like this. The current topic is "set_by_lua not work".

Also, for such new-comer questions, the openresty-en mailing list is a better place:

https://openresty.org/#Community

Thanks for your cooperation :)

**Comment by mysterytoo** [comment]
I got it. But I have added env directive on the top of nginx.conf, I mean I can  get the env. value through nginx lua script, but I can't sync the env. value that is modified by command line directly. If I want, I need to stop the nginx and start again, that will work. So can nginx lua script dynamically get the env. value ?

**Comment by agentzh** [comment]
@mysterytoo No, that's not how system environments should behave. Environments only take effect upon process startup. If you want dynamic configurations, then you should use formal approaches like shm updates, socket communication, and etc.

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by andrea-spoldi** [comment]
Hi, sorry to open this thread again, but I have problem setting a var with "set_by_lua" on my environment 

on top of nginx.conf I got : 

`env foo;`

then I made a simple test block

```
location /lua {

                default_type text/html;

                content_by_lua '

                ngx.say(os.getenv("foo"));

                ';
        }
```

output is "nil"

here's my configuration

nginx version: openresty/1.9.3.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.2.19 --add-module=../echo-nginx-module-0.58 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.29 --add-module=../form-input-nginx-module-0.11 --add-module=../encrypted-session-nginx-module-0.04 --add-module=../srcache-nginx-module-0.30 --add-module=../ngx_lua-0.9.16 --add-module=../ngx_lua_upstream-0.03 --add-module=../headers-more-nginx-module-0.26 --add-module=../array-var-nginx-module-0.04 --add-module=../memc-nginx-module-0.16 --add-module=../redis2-nginx-module-0.12 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.06 --with-ld-opt=-Wl,-rpath,/etc/nginx/luajit/lib --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module


the env "foo" is set by a script executed at server's boot with rc.local.


thanks


A

**Comment by detailyang** [comment]
That's because you reset the foo to nil.
````bash
env foo; #you rewrite the foo to nil
````
you can check the [doc](http://nginx.org/en/docs/ngx_core_module.html#env) again .

**Comment by nicholassmith** [comment]
@detailyang I also have the same issue as @andrea-spoldi. I've looked at the docs but there's no implication that using `env foo;` does the same thing as `foo=""`. The line 
> Default:	
env TZ;

Suggests to me that using it as `env foo;` should inherit the system variable, and many articles ([http://blog.doismellburning.co.uk/environment-variables-in-nginx-config/](url) suggest that it should work like that. Has the behaviour changed? This feels like a new issue should be opened.

**Comment by agentzh** [comment]
@nicholassmith Right, `env VAR` does not clear the original value.

I guess the problem is just that the environments used when launching nginx are just different from your default bash session. You should check your script that directly starts your nginx.

**Comment by agentzh** [comment]
@andrea-spoldi @nicholassmith You can try directly starting your nginx (or openresty) executable on command line, as in

```bash
export Foo=bar
/path/to/nginx/sbin/nginx -c /path/to/your/nginx.conf ...
```

Better login as `root` instead of using sudo since on some systems `sudo` session does not automatically inherit environments from your current shell session.

And then in your `nginx.conf`, you can have

```nginx
env Foo;
...
location = /t {
    content_by_lua_block { ngx.say(os.getenv("Foo")) }
}
```

I've just tested it out myself locally and it works as expected:

```session
[root@fedora64 ~]# export Foo=bar
[root@fedora64 ~]# /usr/local/openresty/nginx/sbin/nginx
[root@fedora64 ~]# curl localhost/t
bar
```
