### ISSUE TITLE
Nginx not terminating?

### ISSUE THREAD

**Issue by JimOct** [openresty/lua-nginx-module#593]
I load a specific lua script before loading my php.conf which contains PHP etc.

It has this in it:     ngx.exit(403)

However, my PHP script has limit requests.. even when it says ngx.exit(403) it keeps limiting requests? I am using this for a ip_blacklist script, to prevent attacks. 

Here is my full script: http://pastebin.com/xHTffG5p

I load this BEFORE limit_request, but it still limits the requests. I don't want to make it limit requests when it's returning 403 (when the ip is banned). 

Am I doing something wrong? I would think ngx.exit would terminate the connection to the user, and not run "php.conf" which is loaded after ngx.exit.. right?

Screenshot of my nginx conf: http://i.imgur.com/FGiRxdV.png

And the PHP.conf is the one that contains limit requests, so i basically limit requests only for php files.. the issue is that it limits request even when returning 403.

**Comment by agentzh** [comment]
@JimOct Please minimize your example first. It takes too much time for me to understand your complete workflow and real configurations.

**Comment by agentzh** [comment]
@JimOct Please see http://openresty.org/faq.html#how-should-i-report-a-problem for the basic guidelines.

**Comment by agentzh** [comment]
Consider it resolved.
