### ISSUE TITLE
Broken HTML when using status codes instead of constants in body_filter_by_lua 

### ISSUE THREAD

**Issue by davidsnt** [openresty/lua-nginx-module#594]
Code snippet

if ngx.status == 301 then
  local chunk, eof = ngx.arg[1], ngx.arg[2]
  if not eof then
   ngx.arg[1] = nil
  else
   local new = "{Test Content}\\n"
   ngx.arg[1] = new
  end
end

when used inside body filter by lua gives a broken page where as the same code when using constants returns a correct HTML

if ngx.status == ngx.HTTP_MOVED_PERMANENTLY or ngx.HTTP_MOVED_TEMPORARILY then
  ...
  ....

**Comment by agentzh** [comment]
> if ngx.status == ngx.HTTP_MOVED_PERMANENTLY or ngx.HTTP_MOVED_TEMPORARILY

This line does not look right to me. I think you should use "if ngx.status == xxx or ngx.status == yyy" instead of "if ngx.status == xxx or yyy".

Also, ngx.status is a metamethod call, it's faster to cache the result in a local Lua variable yourself, as in

```lua
local status = ngx.status
if status == xxx or status == yyy then
    ...
end
```

Ensure you have no typos in your constant names as well.

**Comment by davidsnt** [comment]
sorry about the typo, using lua variable to cache the status doesnt help much, I still see a broken page. 

local status = ngx.status

if status == 301 or status == 302  then
  {same code from my first email}
end

Any idea why it would return the page broken?

**Comment by agentzh** [comment]
@davidsnt Maybe you change the size of the response body in your body filter but forgot to clear the Content-Length response header in your header filter?

**Comment by davidsnt** [comment]
Thank you for the hint, it worked. I had a header_filter_by_lua but with a conflict, in header_filter phase the validation was based on constants whereas in body_filter I used codes believe this caused pages to appear broken. 

Closing this issue.
