### ISSUE TITLE
ngx.var documentation

### ISSUE THREAD

**Issue by pirogoeth** [openresty/lua-nginx-module#595]
This is just a minor thing, but I think the [ngx.var documentation](https://github.com/openresty/lua-nginx-module#ngxvarvariable) should mention that an empty string is returned rather than a `nil` when you attempt to call when the variable you're checking for doesn't exist. 

As a brief side note (or side question, rather), why doesn't the `ngx.var` API follow typical Lua semantics and return a `nil` for variables that don't exist?

**Comment by agentzh** [comment]
@pirogoeth For nonexistent nginx variable references via `ngx.var`, the value should be nil. There is a test case for this case actually:

https://github.com/openresty/lua-nginx-module/blob/master/t/045-ngx-var.t#L55

What nginx variable in particular are you talking about?

**Comment by pirogoeth** [comment]
@agentzh it's one that may or may not be set depending on the location that `access_by_lua_file` is called from. 

In my case, the variable is `ngx.var.lsso_location_scope`.

**Comment by pirogoeth** [comment]
@agentzh Here's some logging messages from some debugging code I just put in:

```
2015/11/02 22:51:26 [warn] 45831#101245: *28 using uninitialized "lsso_location_scope" variable, client: --snip--, server: sso.maio.me, request: "POST /auth/verify HTTP/1.1", host: "sso.maio.me", referrer: "https://sso.maio.me/auth/?error=WW8sIHRoZXNlIGFpbid0IHlvIGNoZWV6LWl0cyE%3D"
2015/11/02 22:51:26 [notice] 45831#101245: *28 [lua] access.lua:29: lsso_location_scope is type: string, client: --snip--, server: sso.maio.me, request: "POST /auth/verify HTTP/1.1", host: "sso.maio.me", referrer: "https://sso.maio.me/auth/?error=WW8sIHRoZXNlIGFpbid0IHlvIGNoZWV6LWl0cyE%3D"
2015/11/02 22:51:26 [notice] 45831#101245: *28 [lua] access.lua:30: lsso_location_scope contains: , client: --snip--, server: sso.maio.me, request: "POST /auth/verify HTTP/1.1", host: "sso.maio.me", referrer: "https://sso.maio.me/auth/?error=WW8sIHRoZXNlIGFpbid0IHlvIGNoZWV6LWl0cyE%3D"
```

**Comment by agentzh** [comment]
@pirogoeth Is that variable a builtin one exposed by some 3rd-party nginx modules? Builtin nginx variables can have magic.

If not, please provide a minimal and self-contained example that I can run and reproduce your problem, so as to save time :)

**Comment by pirogoeth** [comment]
@agentzh It's not exposed by any other module. I've got nginx doing a `set $lsso_location_scope` on two separate locations. Any other location (where `$lsso_location_scope` was not set) that is hit and handled by the Lua handler shows that `lsso_location_scope` is an empty string. 

I'd suppose you could reproduce by setting `$some_var` in a location and dumping it to log from a Lua script from one location where it is set and one location where it isn't.

**Comment by agentzh** [comment]
@pirogoeth Mind to craft an example for me? I don't have much time to poke around myself from your natural language description. Sorry. Thank you for your understanding.

**Comment by pirogoeth** [comment]
Sure!

nginx site config:
```
server {
  listen 80 default_server;
  server_name example.com;
  location /test/novar {
    default_type "text/plain";
    content_by_lua_file '/root/vartest.lua';
  }

  location /test/var {
    default_type "text/plain";
    set $var_thing "test";
    content_by_lua_file '/root/vartest.lua';
  }
}
```

`/root/vartest.lua`:
```
local ngx_var = ngx.var.var_thing;
local ngx_undef = ngx.var.undefined_var;

ngx.say("var_thing is type: " .. type(ngx_var))
ngx.say("var_thing contains: " .. tostring(ngx_var))

ngx.say("undefined_var is type: " .. type(ngx_undef))
ngx.say("undefined_var contains: " .. tostring(ngx_undef)
```

`example.com/test/novar`:
```
var_thing is type: string
var_thing contains: 
undefined_var is type: nil
undefined_var contains: nil
```

`example.com/test/var`:
```
var_thing is type: string
var_thing contains: test
undefined_var is type: nil
undefined_var contains: nil
```

**Comment by agentzh** [comment]
@pirogoeth Okay, I see what is going on here. So uninitialized nginx variables are different from undefined nginx variables. Your `$var_thing` variable is defined (though in another location) but not initialized in `location /test/novar`; and uninitialized nginx variables all have the default initial value, an empty string. So this is the expected behaviour.

**Comment by pirogoeth** [comment]
@agentzh Alright, thanks! I was curious because that seemed slightly strange plus it wasn't documented.

**Comment by agentzh** [comment]
@pirogoeth I've added a line to ngx.var.VARIABLE's documentation. Thank you for the suggestion.
