### ISSUE TITLE
What is the difference between ngx.time() and os.time()? 

### ISSUE THREAD

**Issue by yandd** [openresty/lua-nginx-module#598]
Our project use os.time() to get current time, we found the time was delayed for nearly two hours.

**Comment by cubicdaiya** [comment]
> What is the difference between ngx.time() and os.time()?

`os.time()` is the wrapper of the syscall (e.g. `time()`). On the other hand, `ngx.time()` gets the current timestamp from nginx's cached timestamp.

**Comment by agentzh** [comment]
Consider it resolved.
