### ISSUE TITLE
lua_code_cache seems causing `signal 17 (SIGCHLD) received` error

### ISSUE THREAD

**Issue by kureikain** [openresty/lua-nginx-module#599]
When I turn off `lua_code_cache` in my developmet env,  I'm seeing those error in log file:

```
2015/11/09 21:43:21 [notice] 16063#0: signal 17 (SIGCHLD) received
2015/11/09 21:43:21 [notice] 16063#0: unknown process 16064 exited with code 0
```

So nginx process exit at every request and a new nginx process is spawn. Is this intended behaviour or I'm doing sth wrong?

Here is my nginx.conf:

```
daemon off;

#error_log /tmp/error.log error;
#error_log /tmp/error.log debug;
error_log /dev/stdout debug;

events {
    worker_connections 1023;
    use epoll;
}

http {
  lua_package_path "/etc/nginx/lua-resty-http-0.05/lib/?.lua;;";
  server {
    listen 8888;

    access_log /tmp/access.log;
    lua_code_cache off;

    location ~ ^/(?<path>.*\.(?<ext>[A-Z0-9a-z_]*))$ {
      resolver 8.8.8.8;
      root cache2;
      set_unescape_uri $arg_s;
      content_by_lua_file "app.lua";

      expires     max;
      add_header  Cache-Control public;
    }
  }
}
```

When I change `lua_code_cache to on`, I'm no longer see the error.

**Comment by agentzh** [comment]
@kureikain Will you make your nginx generate a core dump file and use gdb to get the full backtrace of the crash? In addition, temporarily enabling the nginx debugging logs can give us more context about the crash. Please see

https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/

(The `./configure --with-debug` trick also applies to OpenResty's build system, BTW.)

Also, ensure your ngx_lua module is up to date. You might be just hitting an old bug in an ancient version of ngx_lua.

**Comment by kureikain** [comment]
@agentzh Thanks. Let me try upgrade to openresty 1.9 first then if the problem remains, I will get the core dump.

**Comment by agentzh** [comment]
@kureikain Thanks. Also, if you can provide a minimal and self-contained test case that I can reproduce the issue, it'll be much much easier for me to investigate it.

**Comment by kureikain** [comment]
@agentzh After updating to 1.9, I still see the issue but I think the issue is more related to my Lua code(I used Luajit FFI to write a C binding for librsvg2). 

I'm going to extract unrelated code to create a minimum test case for your further investigate. I'll update later with this test case.

**Comment by kureikain** [comment]
Hi @agentzh 
I track out the issue. It's totally my code, not related to OpenResty at all. I'm closing this. Thanks for giving me information about coredump and --with-debug . It's very helpful

**Comment by agentzh** [comment]
@kureikain Glad you figured it out. BTW, valgrind is also very helpful in debugging FFI related Lua code. Also, tuning the Lua GC parameters to make the GC more aggressive can also be helpful.

**Comment by thefosk** [comment]
@kureikain what was the problem in your case?

**Comment by kureikain** [comment]
@thefosk It turns out in one of my branch of code, a segment of code make a shell exec command to an external binary in case LUA code cannot handle this. So the unknow process that exited is that shell proces, not Nginx process.

To more clear, I was trying to do image processing with C binding of ImageMagick but I don't know how to process GIF with C-binding so I called `convert` command to process GIF which cause this issue.
