### ISSUE TITLE
ngx.exit() and custom body?

### ISSUE THREAD

**Issue by rik1083** [openresty/lua-nginx-module#60]
Hi 
Here's what I'm currently using to return an error to a client:

elseif (res.status == ngx.HTTP_GONE) then
     ngx.exit(res.status)

This returns the nginx "style" conteny body with error code and description

Can I somehow return a custom/dynamic body instead?
The reason being I would like to print more detailed information as to what the error was at the auth server

Many thanks

**Comment by davidsnt** [comment]
Is it possible to use a html document in ngx.say?
Something like ngx.say("path/to/html") so that it prints the whole html.

**Comment by bjoe2k4** [comment]
No, you have to read it first, before you can print it. However, it is way more efficient to let nginx serve the html directly.

**Comment by danihodovic** [comment]
I'm running into the very same issue but having nginx return 200 when a header is set. If the header is set earlier than the `ngx.status` or `ngx.say` call the request will return a 200 status code.

Code snippet:
```lua
ngx.headers['Content-Type'] = 'application/json'
ngx.status = 429
ngx.say(jsonStr)
ngx.exit(200)
```

This is configured in nginx like so:
```
  location /main {
  access_by_lua_file /opt/app/src/main.lua;
  proxy_pass http://localhost:5555;
}
```

**Comment by agentzh** [comment]
@danihodovic I'm not sure what version of your ngx_lua module used in that ubuntu package which is not maintained by us at all.

I've tried your example locally (after fixing a typo in `ngx.headers` and making up the value of the `jsonStr` variable and it works perfectly for me:

```nginx
    location /main {
        access_by_lua_block {
            local jsonStr = '{"name":"foo"}'
            ngx.header['Content-Type'] = 'application/json'
            ngx.status = 429
            ngx.say(jsonStr)
            ngx.exit(200)
        }
    }
```

Accessing `/main` gives:

```console
$ curl -i localhost:8080/main
HTTP/1.1 429
Server: nginx/1.9.15
Date: Thu, 28 Apr 2016 18:42:28 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive

{"name":"foo"}
```

BTW, you're recommended to use the latest official OpenResty bundle to avoid any unneeded problems:

https://openresty.org/en/download.html
