### ISSUE TITLE
How to delete a cookie in lua

### ISSUE THREAD

**Issue by VJVijay** [openresty/lua-nginx-module#600]
I need to delete a cookie (e.g abc) from req path and preserve other cookies as-is. It turns out, there is no easy way to do this. Any thoughts?

**Comment by agentzh** [comment]
@VJVijay I think you can just manipulate the corresponding request (or response) headers in Lua directly.

**Comment by agentzh** [comment]
@VJVijay BTW, such questions should really go to the openresty-en mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

**Comment by VJVijay** [comment]
Can you move this thread over?  I still cannot find how this can be done...

**Comment by agentzh** [comment]
@VJVijay No, I cannot move the thread for you. Regarding the details, please refer to the user manual:

https://github.com/openresty/lua-nginx-module#ngxreqget_headers
https://github.com/openresty/lua-nginx-module#ngxreqset_header
https://github.com/openresty/lua-nginx-module#ngxheaderheader

**Comment by agentzh** [comment]
Consider it resolved.
