### ISSUE TITLE
Using env keyword in nginx.conf but os.getenv in init_by_lua returns nothing

### ISSUE THREAD

**Issue by diddek** [openresty/lua-nginx-module#601]
Hi,

When I try to set an env var in the nginx master conf and then try to get it in a file on the init_by_lua handler, the value is empty

nginx.conf:

env MyKey="value123";

http {
  lua_package_path '/usr/local/lib/lua/?.lua';
  init_by_lua_file '/usr/local/nginx/conf/test.lua';

...

test.lua:

local mykey = os.getenv('MyKey')

-mykey is still empty

Is this expected? Or am I missing something?

Thanks in advance for your answer!

Kind regards,

D

**Comment by agentzh** [comment]
@diddek Yes, it's the expected behaviour. The official documentation for the `env` directive states that it mainly affects worker processes:

http://nginx.org/en/docs/ngx_core_module.html#env

while `init_by_lua*` runs in the master process (before forking off the workers).

**Comment by diddek** [comment]
Hi Agentz,

Thanks! 

Is there a way to set a variable in ngxin.conf to be read in init_by_lua?

Best,

D

**Comment by agentzh** [comment]
@diddek Maybe just make your init Lua scripts a parametrized Lua module and invokes it like this in nginx.conf?

```nginx
    init_by_lua_block {
        require("myinit").init{ dogs => 32, cats => 56 }
    }
```

Just my 2 cents.

**Comment by diddek** [comment]
Hi Agentz,

The file referred to in the actual case is a rather large ffi related generated lua file, which I'd rather not put in the conf 'as is': too much clutter and secondly I'd like to use a compiled lua file, which the blck does not allow.

Could I use init_by_lua twice (I know I can't :), init_by_lua_file followed by init_by_lua to inject some variables is perhaps an idea.

I can read something from file, but that means hardcoding a location.

Best,

D

**Comment by agentzh** [comment]
@diddek You can just make the Lua file a Lua module which exposes an `init` method such that you can just write a minimal boilerplate `init_by_lua_block` as demonstrated above. I was not suggesting putting every line of your Lua file inside nginx.conf at all :)

Allowing multiple instances of the `_by_lua*` directives have merits for its own right. Maybe we can add that in the future. Patches welcome :)

**Comment by diddek** [comment]
Hi Agentz,

Thanks! I will look into it.

Regards,

D

**Comment by agentzh** [comment]
@diddek Oh, please don't call me Agentz. Call me agentzh (my web nick, all lower case) or Yichun (my first name) instead :) Thanks!

**Comment by diddek** [comment]
module.init works, thanks!
