### ISSUE TITLE
lrexlib-pcre compatibility problem?

### ISSUE THREAD

**Issue by iaadoa** [openresty/lua-nginx-module#602]
I have met a problem while using lrexlib-pcre in nginx context.

I've called rex_pre.new in init_by_lua_file script and called rex_pcre.match in access_by_lua_file script, but I got following error message every time:

    550 2015/11/10 11:21:34 [error] 28259#0: *154 lua entry thread aborted: runtime error:###########/siglib.lua:31: error PCRE_ERROR_BADMAGIC

But when I try my scripts in shell with luajit, everything is ok.

Is it a compatibility problem?

p.s. My target is to precompile regex in initial phase and accelerate match operation when request is in-progressing.  Thus, the default openresty regex engine is not suitable.

**Comment by splitice** [comment]
there was a patch a little while ago for this wasnt there? Removing nginx's memory management or something from the PCRE allocator (or so I seem to recall).

Are you on the latest lua module version?

**Comment by agentzh** [comment]
@iaadoa See my reply on the openresty-en mailing list: https://groups.google.com/d/topic/openresty-en/phIIkiVJ2LE/discussion

BTW, please do not cross-post. It's annoying. Thank you for your cooperation.

**Comment by agentzh** [comment]
Consider it resolved.
