### ISSUE TITLE
use nginx proxy_pass method in lua

### ISSUE THREAD

**Issue by gaoguoxin** [openresty/lua-nginx-module#606]
for some reason ,I want to use proxy_pass in lua instead of ngx.redirect ,but I cant't found the api.bellow is the correct code ,and I am looking for the method proxy_pass of the nginx using in lua
```nginx
  location ~* /(\w+\/\w+) {
    set $qstring $1;
    access_by_lua '
      local redis = require "resty.redis"
      local red = redis:new()
      red:connect("127.0.0.1", 6379)
      red:set_timeout(1000)
      local ok, err = red:hget("center:" .. ngx.var.qstring, "m")
      local domain,err = red:hget("db_center",ok)
      if ok and ok ~= ngx.null then
        local domain,err = red:hget("db_center",ok)
        if domain and domain ~= ngx.null then
          return ngx.redirect("http://" .. domain .. ngx.var.request_uri)
        end
      end
      red:set_keepalive(10000,100)
    ';
    try_files $request_uri $uri @server;
  }
```

The reason is I don't want the url change if the request_uri matched the regexpress. And if the request_uri dosen't match the regxpress,I want the request continue which don't cause the Death cycle

**Comment by agentzh** [comment]
@gaoguoxin I think you just need the `ngx.exec()` function here to initiate an internal redirect.
