### ISSUE TITLE
segmentation fault when lowcase_key in the header is null

### ISSUE THREAD

**Issue by web-data-sci** [openresty/lua-nginx-module#610]
Hello,

I am using lua-nginx-module-0.9.16. Worker process crashing (exit, signal 11) is logged and crash occurs in Nginx when lowcase_key in the header is null. Crash occurs around line 405 in 'ngx_http_lua_ngx_req_get_headers' method in 'ngx_http_lua_headers.c' file when an attempt is made to extract lowcase_key from headers array.

I have fixed the code on my side so that lowcase_key will not be null in the header. However it will be nice if Lua module fails gracefully with a message instead of crash/segmentation fault.

Thanks.

**Comment by agentzh** [comment]
@web-data-sci Hmm I don't think `lowcase_key` is allowed to be NULL according to the NGINX internals' usage. For example, ngx_http_realip_module uses `lowcase_key` without testing nullity. If you create that header, then it's your responsibility to always allocate and initialize `lowcase_key` properly at the same time.

**Comment by agentzh** [comment]
Consider it resolved.
