### ISSUE TITLE
ssl_certificate_by_lua without certs

### ISSUE THREAD

**Issue by aledbf** [openresty/lua-nginx-module#612]
Is possible to use `ssl_certificate_by_lua` to forward the handshake to an upstream?
(the server in the upstream contains the certificate)
Thanks

**Comment by agentzh** [comment]
@aledbf Not really since you're effectively doing a man-in-the-middle attack :) SSL/TLS tries very hard to make that impossible.

BTW, SSL certificates are public info. What really matters here is the private key. Even in the key-less SSL mode (as provided by CloudFlare), only the private keys are off the edge.

**Comment by aledbf** [comment]
>  you're effectively doing a man-in-the-middle attack

I know :) . I'm just trying to put all the certificates in the same place.
Thanks.

**Comment by aledbf** [comment]
@agentzh this is what I'm trying to do http://blog.haproxy.com/2012/04/13/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/

```
...
backend bk_ssl_default
  mode tcp
 
  acl application_1 req_ssl_sni -i application1.domain.com
  acl application_2 req_ssl_sni -i application2.domain.com
 
  use-server server1 if application_1
  use-server server2 if application_2
  use-server server3 if !application_1 !application_2
 
  option ssl-hello-chk
  server server1 10.0.0.11:443 check
  server server2 10.0.0.12:443 check
  server server3 10.0.0.13:443 check
```

**Comment by agentzh** [comment]
@aledbf Well, you can always lazily load (and cache) the certificates and private keys from your own central place nonblockingly via ssl_certificate_by_lua + cosockets anyway.
