### ISSUE TITLE
conditional use in content_by_lua

### ISSUE THREAD

**Issue by bendpx** [openresty/lua-nginx-module#613]
this is more of a question as I couldn't understand it from the docs.

I'm trying to create a conditional content_by_lua script, where the content should be set by lua only under a turthy condition. 

example: 
nginx.conf
      
    location / {
            content_by_lua_file  /nginx/lua/nginx.lua;

            root   /nginx/www;
            index  index.html;

            location ~* \.(?:ico|css|js|gif|jpe?g|png|woff|ttf)$ {
                expires max;
                add_header Pragma public;
                add_header Cache-Control "public, must-revalidate, proxy-revalidate";
            }
        }

nginx.lua
```  
   if condition then
        ngx.header["Content-type"] = "text/html"
        ngx.say('<H1>Hello World.</H1>');
        ngx.exit(0)
    else
        -- serve the original content (index.html)
    end

**Comment by membphis** [comment]
```lua
if condition then
        ngx.header["Content-type"] = "text/html"
        ngx.say('<H1>Hello World.</H1>');
        -- ngx.exit(0) 
else
        -- serve the original content (index.html)
end 
```

please remove `ngx.exit(0)`, the `ngx.say` have set the exit code(http status code) to `200` directly.

**Comment by bendpx** [comment]
The condition works (but thanks for the comment) what's not working is when the condition is false. Then it return a blank page

**Comment by Oik741** [comment]
Hi bendpx,
take a look at [this article](http://www.staticshin.com/programming/definitely-an-open-resty-guide/#content_by_lua), 
location block should have only one content handler

**Comment by agentzh** [comment]
Consider it resolved.
