### ISSUE TITLE
lua_shared_dict   invalid lua shared dict size

### ISSUE THREAD

**Issue by mlr3000** [openresty/lua-nginx-module#615]
...
lua_shared_dict dogs 1k;
...

nginx: [emerg] invalid lua shared dict size "1k" in ./conf/nginx.conf:32

nginx version: openresty/1.9.3.2

**Comment by thibaultCha** [comment]
I ran into the same problem a few days ago.

According to [this line](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_directive.c#L110), it would seem like the minimum size allowed is `8192`, aka `8k` (`8 * 1024`).

However, I have noticed that setting a value smaller than `12k` (or 12288 bytes) still fails with the message:

```
nginx: [crit] ngx_slab_alloc() failed: no memory
```

OS X 10.11.1
openresty/1.9.3.1

**Comment by agentzh** [comment]
Yes, the minimum threshold is 8KB.

@thibaultCha There is some boilerplate overhead of the shared dicts. So you can easily run into such errors with very small sizes like 12KB.

**Comment by thibaultCha** [comment]
Alright. Well, if that can help @mlr3000, I went with allocating 100KB for the smallest dicts I use (with only 2 or 3 values), and I did not have any issue so far.
