### ISSUE TITLE
Questions about init_by_lua and init_worker_by_lua

### ISSUE THREAD

**Issue by zhanchch** [openresty/lua-nginx-module#620]
Hi all,

I am hoping you can shed some light on a couple questions regarding init_by_lua and init_worker_by_lua :)

I am trying to use init_by_lua to load some config lua file

1. My config lua file is using ngx.re.match to do some work, and I read that ngx.re.match is not available in init_by_lua but is available in init_worker_by_lua, is there any specific reason that ngx.re.match is not allow in init_by_lua?

2. When is init_worker_by_lua executed? Is it on nginx start or at the first request come in?

example code:
```
init_by_lua '
local config = require("config")
local rawFiles = config.get("rawFiles") -- {"/tmp/abc.txt", "/tmp/def.doc"}
local files = {}
for i, location in ipairs(rawFiles) do
        local match = ngx.re.match(location, ".*/(*.txt)")
        if match ~= nil and match[1] then
                local name = match[1]
                files[name] = location
        end
end
config.set("txtFiles", files)
';
```

Thank you very much!

Chuchu

**Comment by agentzh** [comment]
@zhanchch Regarding your question 1), the `ngx.re` API is unavailable in the context of `init_by_lua*` just because the limitation in the current implementation. This is fixable though. Patches welcome.

Regarding your question 2), please refer to the official documentation for the `init_worker_by_lua*` directive.

**Comment by agentzh** [comment]
@zhanchch BTW, it's better for such questions to go to the openresty-en mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

**Comment by zhanchch** [comment]
@agentzh Thank you very much! I had the second question because ngx.log didn't write to file when used during init_worker_by_lua, turns out I need to declare error_log outside of the http block

**Comment by agentzh** [comment]
@zhanchch Glad you figured it out.
