### ISSUE TITLE
cosocket concurency -- posible issuse?

### ISSUE THREAD

**Issue by slw** [openresty/lua-nginx-module#621]
I am use resty.redis at high request rate (about 1500 rps per nginx worker).
Every request do one or two redis request.
Some times I am see 3000 concurent redis connections, about 2700 have unread data on nginx side. As result resty.redis give many timeout errors.

**Comment by agentzh** [comment]
@slw I need more information to debug the issue for you.

Normally, 1500 rps per nginx worker is not really high for moderate production server machines nowadays. But absolute numbers certainly rely on your data set, access patterns, hardware, user code, configurations, and etc.

From your vague description, it seems that something is blocking nginx's event loop for some reasons. To be sure, please consider using the on-CPU and off-CPU flame graph tools to generate flame graphs for a typical nginx worker process experiencing the issue (observing the CPU usage of that worker can be helpful as well):

https://openresty.org/#Profiling

Usually it's just suboptimal user Lua code or misconfigurations (on either the nginx side or the redis-server side or both). But feel free to prove me wrong :)

BTW, it's a good practice to provide as many details as possible when reporting a problem. Please see
http://openresty.org/faq.html#how-should-i-report-a-problem for more info. Thank you.

**Comment by slw** [comment]
nginx 1.9.7
luajit 2.0
ngx_lua 0.9.19
redis 3.0.5 (local instance, unix socket connection)
FreeBSD 10.2-STABLE
Dual  E5-2650v2, 128GB RAM, cpu load about 50%, output traffic 25Gbit/s.
W/o redis code all work nice.
I don't see workers blocking.
Nothing interesting in error log (only socket read timeout).
This is production, I am can't enable debug log.
I found similar issuse #316

**Comment by agentzh** [comment]
@slw Use the on-CPU and off-CPU flame graph tools to analyze both nginx workers and your redis-server. Maybe your redis is the bottleneck (maybe shard the traffic to multiple redis-server instances). 25Gbit/s is quite a thing.

**Comment by agentzh** [comment]
@slw BTW, ensure you've enabled connection pool in your resty.redis accesses by calling `set_keepalive` and checking its return values properly. In addition, ensure you've tuned your redis-server's configuration settings for busy accesses, especially the `tcp-backlog` setting which has a low default value.

**Comment by agentzh** [comment]
@slw BTW, intermittent timeout errors are normal when relatively short timeout thresholds are used. Just handle such timeout errors and retry once (or twice) automatically in your Lua code, and also configure `lua_socket_log_errors off` in your `nginx.conf` (when you already handle socket errors properly yourself).

**Comment by slw** [comment]
yes, I am already increase redis backlog to 4096.
yes, I am use set_keepalive (w/o checking return value -- don't know how handle error in this case).
no, redis is not bottleneck -- reidis is just for access control, no data from redis pass to client (one or two request to redis (150 bytes for success) for 500KB data servered to client).

**Comment by agentzh** [comment]
@slw `set_keepalive` returns `nil` and a string describing the error in case of failures. Consult the documentation for this method for more details: https://github.com/openresty/lua-resty-redis#set_keepalive

**Comment by agentzh** [comment]
@slw Keep an eye on the CPU usage of your redis-server.

**Comment by slw** [comment]
> BTW, intermittent timeout errors are normal when relatively short timeout thresholds are used (unless it happens too frequently).

I am use 1s timeout, redis server on benchmark show 100K rps.
I see read timeout, not connect timeout.

**Comment by slw** [comment]
> set_keepalive returns nil and a string describing the error in case of failures.

What recomended action in this case? I am don't see this (recomended action) in documentation.

> Keep an eye on the CPU usage of your redis-server.

30-50%% of nginx, i.e. about 5-10% of one CPU core.

**Comment by agentzh** [comment]
@slw Then I think there is something blocking your nginx event loop. Use tools like this to be sure:

https://github.com/openresty/stapxx#epoll-loop-blocking-distr

**Comment by agentzh** [comment]
@slw You gave CPU usage for nginx while I was asking for the CPU usage of redis-server.

**Comment by agentzh** [comment]
@slw As I've stated for multiple times already, use of off-CPU time flame graphs can be very helpful as well.

**Comment by agentzh** [comment]
@slw Err, one common error handling action is to log the error message with some context info. Well, it's completely up to you. This is considered common sense and I don't want to document that for every API function. And, you do have an example in the official manual's Synopsis section:

https://github.com/openresty/lua-resty-redis#synopsis

**Comment by slw** [comment]
> Err, one common error handling action is to log the error message with some context info. Well, it's completely up to you. This is considered common sense and I don't want to document that for every API function. And, you do have an example in the official manual's Synopsis section:

I.e. you ack about error at return from set_keepalive ("calling set_keepalive and checking its return values properly")? I don't need special action to handle this (force to close socket or smth)?

**Comment by agentzh** [comment]
@slw Just log the errors so that we know `set_keepalive` fails. That was my original point :)

**Comment by agentzh** [comment]
@slw And you should do proper error handling for all the API functions that may fail (not limited to lua-resty-redis).

**Comment by slw** [comment]
> You gave CPU usage for nginx while I was asking for the CPU usage of redis-server.

I give both CPU usage.

redis about 5%
nginx about 10%
system about 45%
idle about 33%

**Comment by agentzh** [comment]
@slw Then it looks good.

**Comment by slw** [comment]
Ok, I am do logging and monitor this.
All other error checked and handled (logged and nginx error code returned)

**Comment by agentzh** [comment]
@slw Let me re-emphasize: check the event loop blocking effect quantitively and do off-CPU flame graph analysis.

**Comment by slw** [comment]
> Then I think there is something blocking your nginx event loop

Blocking nginx event loop must be lead traffic drop from nginx (sending to cliend also do in nginx event loop). I am don't see traffic drops.

I am try catch next "timeout" cycle and record blocking-distr and off-cpu.

**Comment by agentzh** [comment]
@slw No, it's not necessarily leading to nginx traffic drop because it may be just those writev() syscalls sending data downstream that add to the blocking time of the event loop in the first place.

**Comment by slw** [comment]
This is not may case: I have 30K concurent connections (4K connections per worker) and blocking on writev() for one client cause traffic drops on the rest clients.
Any way, I am use aio.

**Comment by agentzh** [comment]
@slw I'd rather see quantitive measurement results rather than speculations :) `writev()` is expensive even for nonblocking I/O (BTW, I don't think native AIO is involved in network I/O here in nginx even on FreeBSD).

**Comment by agentzh** [comment]
@slw BTW, you can also try emulating the traffic with load testing tools like ab and weighttp so that you can more easily experiment with things like larger timeout thresholds.

**Comment by slw** [comment]
I am try evaluating kevent distributing and found some strange result:
(for example one worker pid 69467):
  ns                                                    69467
           value  ------------- Distribution ------------- count    
             512 |                                         0        
            1024 |                                         1        
            2048 |                                         0        
            4096 |                                         20074    
            8192 |@@@@@@@@@@@@@@@@                         726376   
           16384 |@@@@@@@@@@                               438446   
           32768 |@@@@@@                                   275685   
           65536 |@@@                                      119763   
          131072 |@@                                       87868    
          262144 |@                                        51561    
          524288 |@                                        38319    
         1048576 |                                         7506     
         2097152 |                                         1064     
         4194304 |                                         320      
         8388608 |                                         72       
        16777216 |                                         57       
        33554432 |                                         21       
        67108864 |                                         11       
       134217728 |                                         11       
       268435456 |                                         0        
       536870912 |                                         0        
      1073741824 |                                         0        
      2147483648 |                                         2        
      4294967296 |                                         0        

  max                                                   69467       2639590660 (in ns, i.e. 2.6s)

But at the same time, none syscall elapsed more then 1s.
May be this is some internal lua loop?

**Comment by agentzh** [comment]
@slw That's good progress. Well, even if none of the individual syscall elapses more than 1s, multiple syscalls in a single kqueue event loop iteration can add up to exceed 2s. To dig further, you need to produce both the on-CPU flame graphs and off-CPU flame graphs for your busy worker.

**Comment by slw** [comment]
I am evaluate inter-syscall distribute and kevent return distribute.
Like under high load nginx don't enter in kevent loop if can do write to socket.

**Comment by slw** [comment]
As I understund in my setup exist simultaneously two event processing module: kevent and aio, and most time under high load nginx spend in aio event processing.

**Comment by agentzh** [comment]
@slw Please let me repeat: we need on-CPU flame graphs and off-CPU flame graphs for your busy worker processes to get more insight about what's really happening here.

**Comment by agentzh** [comment]
@slw See https://github.com/openresty/nginx-systemtap-toolkit#sample-bt and https://github.com/openresty/nginx-systemtap-toolkit#sample-bt-off-cpu for reference.

**Comment by slw** [comment]
```
#!/usr/sbin/dtrace -s

#pragma D option ustackframes=100

sched:::off-cpu /execname == "nginx"/ { self->ts = timestamp; }

sched:::on-cpu
/self->ts/
{
        @[execname, pid, curlwpsinfo->pr_lwpid, ustack()] = sum(timestamp - self->ts);
        self->ts = 0;
}

dtrace:::END { printa("\n%s-%d/%d%k%@d\n", @); }
```

http://zxy.spb.ru/edge04.off-cpu.svg

```
#!/usr/sbin/dtrace -s

#pragma D option ustackframes=100

profile-1000
/execname == "nginx" && !self->ts/ {
  self->ts = vtimestamp;
}

profile-1000
/execname == "nginx"/ {

  @[execname, pid, tid, ustack()] = sum(vtimestamp - self->ts);
  self->ts = vtimestamp;
}

dtrace:::END { printa("\n%s-%d/%d%k%@d\n", @); }
```

http://zxy.spb.ru/edge04.on-cpu.svg

currently I am don't see timeout.

**Comment by agentzh** [comment]
@slw Assuming that your flame graphs are correct, it seems that no off-CPU blocking operations in your nginx according to the off-CPU flame graph. And the bottleneck is those writev() syscalls according to your on-CPU flamegraph.

BTW, your LuaJIT build lacks debuginfo and the corresponding part of the graph is blurring (still, it seems that we can improve the performance of that part though it's not dominating).

**Comment by slw** [comment]
"bottleneck" is not correct here.
this is main load for this setup.
I think aprox. count of writev() syscall is 40k per second for one worker and time consumption per one writev() call is very low.

**Comment by agentzh** [comment]
@slw The word "bottleneck" is correct here since optimizing things other than writev() (no matter individual call's overhead or the number of calls) will have not dramatic effect on the overall performance.

Also, even if a single writev() call is fast, 40K writev calls are surely something and they are indeed the dominating factor here. Try reducing the writev calls and increasing the number of nginx workers (if you still have idle CPU cores) can help reduce the blocking overhead of the accumulated effects of writev() syscalls in each single kqueue event loop iteration.

**Comment by agentzh** [comment]
@slw Well, all my observations and analyses above are based on your flame graph samples given above. Whether these flame graphs are typical or correct enough is still something we should think about very carefully :)

**Comment by slw** [comment]
I am already have multiple workers, binding to specific CPU.
and so I am reduce to one worker (per system 320K syscalls/seconds, for 30Gbit/s), also flame graph from multiple cores is not representative.
I am not able to reduce writev calls for preserving smooth outbound transfer to 30K simultaneously clients (per system, 4K per worker).

**Comment by agentzh** [comment]
@slw Please ensure you have *not* configured `multi_accept on` in your `nginx.conf`. In addition, you should have configured `accept_mutex off`. These help nginx respond to events more evenly.

**Comment by agentzh** [comment]
@slw The flame graphs for an individual worker process are fine. No problem with that as long as that process at that sampling period are representative enough for the problem you are analyzing.

**Comment by agentzh** [comment]
@slw Increase the redis timeout threshold a bit more if possible since you're essentially trading latency with throughput here, it seems.

**Comment by agentzh** [comment]
@slw Or with shorter timeout threshold but with automatic retrials as I suggested earlier.

**Comment by antonheryanto** [comment]
upgrading to luajit 2.1 will help? as i see @slw use luajit 2.0 ?

**Comment by slw** [comment]
I am don't see standart nginx package with luajit 2.1.
Also, stable branch is luajit 2.0.

**Comment by agentzh** [comment]
@slw LuaJIT is never shipped with any "standard" NGINX distributions but OpenResty does:

https://openresty.org/#Download

**Comment by slw** [comment]
LuaJIT shipped with standart (from ports) FreeBSD nginx distributions

**Comment by agentzh** [comment]
@slw That's a FreeBSD thing, not an NGINX official thing at all.

**Comment by agentzh** [comment]
@slw Nor is it OpenResty official. Generally, using the official OpenResty source distribution is recommended: https://openresty.org/#Download

**Comment by agentzh** [comment]
Consider it resolved.
