### ISSUE TITLE
 error: ‘ngx_worker’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by sforce100** [openresty/lua-nginx-module#622]
system: ubuntu
nginx: 1.8.0

make[1]: Entering directory `/home/deploy/soft/nginx-1.8.0'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/include/luajit-2.0 -I /home/deploy/soft/lua-nginx-module/src/api -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/src/ngx_http_lua_worker.o \
		/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c: In function ‘ngx_http_lua_ngx_worker_id’:
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c:62:38: error: ‘ngx_worker’ undeclared (first use in this function)
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c:62:38: note: each undeclared identifier is reported only once for each function it appears in
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c: In function ‘ngx_http_lua_ffi_worker_id’:
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c:91:18: error: ‘ngx_worker’ undeclared (first use in this function)
/home/deploy/soft/lua-nginx-module/src/ngx_http_lua_worker.c:92:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_lua_worker.o] Error 1
make[1]: Leaving directory `/home/deploy/soft/nginx-1.8.0'
make: *** [build] Error 2

**Comment by agentzh** [comment]
@sforce100 Yes, the git master HEAD was broken with nginx cores older than 1.9.1 (exclusive). Just submitted a fix in master. Please try it out again.

**Comment by agentzh** [comment]
@sforce100 Thanks for the report!

**Comment by agentzh** [comment]
Consider it resolved.
