### ISSUE TITLE
nginx - 1.7.12 process crash centOS7

### ISSUE THREAD

**Issue by balyanrobin** [openresty/lua-nginx-module#626]
Hi,

Please suggest the direction on how to fix the issue

I am facing the issue with nginx process crashing every time any lua code is hit. Same combination works well on centOS6.5. i am not sure if it is OS issue or not. Issue is reproducable with any directive like set_by_lua, log_by_lua or content_by_lua.

nginx - 1.7.12, lua-nginx-module-0.9.16rc1, centOS7, luaJit 2.0.3

2015/12/19 18:03:07 [notice] 51714#0: signal 17 (SIGCHLD) received
2015/12/19 18:03:07 [alert] 51714#0: worker process 55058 exited on signal 11
2015/12/19 18:03:07 [notice] 51714#0: start worker process 55094
2015/12/19 18:03:07 [notice] 51714#0: signal 29 (SIGIO) received

Failure : with below location, log message is successfully written in log file.
location = /test.txt {
		echo "Pass";
                log_by_lua 'ngx.log(ngx.INFO,"Test")';
	}

Success : No crash of nginx process
location = /test.txt {
		echo "Pass";
	}

**Comment by membphis** [comment]
you can take a test https://openresty.org/download/ngx_openresty-1.9.3.2.tar.gz

**Comment by agentzh** [comment]
@balyanrobin To debug crashes, we need at least the full backtrace at the crash site. Please see https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump for more details.

But it's recommended to try out the latest OpenResty 1.9.3.2 release to avoid hitting known issues that have already been fixed in recent releases.

**Comment by agentzh** [comment]
@balyanrobin BTW, ensure your PCRE library is recent enough because some PCRE versions (around 8.34?) are known to have bugs that can crash.

**Comment by balyanrobin** [comment]
Thanks a lot. it worked. 
Is there a way i can find out why it is crashing, the reason i am asking is the most of my servers are running nginx 1.7.12, i have not done enough testing of my rest of the things to roll out 1.9.

pcre on this box is 8.32, do you think this version could be a problem too?

**Comment by agentzh** [comment]
@balyanrobin I've already provided info on how to analyze the crash by enabling core dumps and getting backtraces via gdb. Please do that.

To my knowledge, PCRE 8.32 should be clean.

**Comment by agentzh** [comment]
Consider it resolved.
