### ISSUE TITLE
always get nil for http_x_forwarded_proto in access_by_lua

### ISSUE THREAD

**Issue by tedder** [openresty/lua-nginx-module#628]
I'm trying to do some work that depends on nginx's `http_x_forwarded_proto`, but it's always nil in `access_by_lua` (or `access_by_lua_block`). I've tried `ngx.var.http_x_forwarded_proto` and simply `http_x_forwarded_proto`. Am I missing something? Is there a way to get at this field?

**Comment by agentzh** [comment]
@tedder Please check this document for how to report a problem in the recommended way:

http://openresty.org/faq.html#how-should-i-report-a-problem
