### ISSUE TITLE
the consume that use share_dict?

### ISSUE THREAD

**Issue by adpoint** [openresty/lua-nginx-module#629]
I use "ab" for a test,case 1, I did not use share_dict,the qps is 10800,case 2,I use one share_dict for "get" option twice,the qps is 9800,the consume for using share_dict is bigger? and compare with redis?

**Comment by agentzh** [comment]
@adpoint Using lua-resty-core and LuaJIT v2.1 can usually speed up the shdict accesses a lot (both of which are shipped with recent OpenResty releases). If you're using the latest version of OpenResty, then just put the following line in `http {}` of your `nginx.conf`:

```nginx
init_by_lua_block { require "resty.core" }
```

Try doing the benchmark again :)

**Comment by agentzh** [comment]
@adpoint Also, using the flame graph tools can guide us optimize your configurations and Lua code: https://openresty.org/#Profiling

**Comment by agentzh** [comment]
Consider it resolved.
