### ISSUE TITLE
the share_dict variable will be free after expired?

### ISSUE THREAD

**Issue by adpoint** [openresty/lua-nginx-module#633]

**Comment by membphis** [comment]
the share_dict remove existing items in the storage according to the Least-Recently Used (LRU) algorithm. 

you can get the data after expired maybe.

**Comment by adpoint** [comment]
if the share_dict variable is out of memory,share_dict will remove the expired data?

**Comment by agentzh** [comment]
@adpoint Freeing expired items work like an incremental garbage collector. Every `get()` and `set()` method calls will free up a few least recently used expired items (if any). And it will try harder when the memory storage is exhausted.

**Comment by agentzh** [comment]
@adpoint BTW, such general questions should go to the openresty-en mailing list instead. This GitHub Issues board should be used for real issues :) Please see https://openresty.org/#Community Thanks for your cooperation.

**Comment by adpoint** [comment]
ok
