### ISSUE TITLE
About lua_ssl question?

### ISSUE THREAD

**Issue by laozi2** [openresty/lua-nginx-module#638]
Because lua_ssl_*(such as lua_ssl_ciphers) are configured in the http/server/location context,
but if there is more than one cosockets will request to diffent SSL/TLS servers in one lua script( or nignx http request), such as sock1 is used for http upstream server, sock2 is used for mysql upstream server, but they use diffent SSL/TLS configure. 
And the question is, is it a problem or how to sovle it ?

**Comment by agentzh** [comment]
@laozi2 Correct. Right now all the cosockets in a single location share the same lua_ssl_* configurations. To solve this, I think we can implement cosocket object level SSL ctx API, as in

```lua
local ngx_ssl_ctx = require "ngx.ssl.ctx"
local ssl_ctx = ngx_ssl_ctx.new{ ciphers = "...", protocols = "..." }
```

And then just reference the SSL ctx on a particular cosocket object before calling `sslhandshake`, as in

```lua
local ok, err = cosocket:setsslctx(ssl_ctx)
if not ok then
    return error("failed to set ssl ctx: ", err)
end
ok, err = cosocket:sslhandshake(...)
```

What do you think of it? Are you interested in contributing an implementation for this? You can check how the existing ngx.ssl module is implemented in the following PRs, for example.

https://github.com/openresty/lua-nginx-module/pull/637

https://github.com/openresty/lua-resty-core/pull/12

Thanks!

**Comment by laozi2** [comment]
Cool, it seems like a good soultion, I would like to think about it,  thanks!
