### ISSUE TITLE
ubuntu upstart configuration

### ISSUE THREAD

**Issue by aptro** [openresty/lua-nginx-module#641]
Here's my ubuntu upstart configuration
start on (filesystem and net-device-up IFACE=lo)
stop on runlevel [!2345]

env DAEMON=/usr/local/openresty/nginx/sbin/nginx
env PID=/usr/local/openresty/nginx/logs/nginx.pid

expect fork
respawn
respawn limit 10 5

pre-start script
        $DAEMON -t
        if [ $? -ne 0 ]
                then exit $?
        fi
end script

exec $DAEMON

But in pid file it shows the pid of master process but not of worker process. 
So while  stopping the service i am unable to stop the workers.

**Comment by agentzh** [comment]
@aptro To stop the nginx service, you just need to send the `QUIT` signal to the nginx *master* process which will take care of all the worker processes itself.

**Comment by aptro** [comment]
Thanks @agentzh
