### ISSUE TITLE
Serving different SSL certs depending on the browser

### ISSUE THREAD

**Issue by needcaffeine** [openresty/lua-nginx-module#643]
So this is actually a CloudFlare feature that I'm unable to use because we don't use CF, for reasons.

I'd like to serve SHA-1 certificates to browsers that cannot accept SHA-2 and SHA-2 to everyone else. Is that possible?

**Comment by agentzh** [comment]
@needcaffeine Yes, it's possible with `ssl_certificate_by_lua*`.

**Comment by needcaffeine** [comment]
Woah! I'll check that out, thank you very much!
