### ISSUE TITLE
0.10.0 & LibreSSL 2.2.5 ?

### ISSUE THREAD

**Issue by centminmod** [openresty/lua-nginx-module#654]
Prior lua-nginx-module versions compiled against my Nginx 1.9.9+LibreSSL 2.2.5 install. But seems updating to 0.10.0 has given an error

```
checking for C compiler ... found
 + using Clang C compiler
 + clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
checking for --with-ld-opt="-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib" ... found

make -f objs/Makefile install
make[1]: Entering directory `/svr-setup/nginx-1.9.9'
ccache /usr/bin/clang -ferror-limit=0 -c -I/usr/local/include/luajit-2.1  -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-sign-compare -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/chromium/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/google-sparsehash/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/protobuf/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/re2/src -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/out/Release/obj/gen -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/apr/src/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/aprutil/src/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.9.32.11-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I ../ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.1 -I ../lua-nginx-module-0.10.0/src/api -I ../nginx_upstream_check_module-0.3.0 -I ../pcre-8.38 -I ../libressl-2.2.5/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.2.19/src -I src/mail -I src/stream \
                -o objs/addon/src/ngx_http_lua_module.o \
                ../lua-nginx-module-0.10.0/src/ngx_http_lua_module.c
../lua-nginx-module-0.10.0/src/ngx_http_lua_module.c:897:9: error: implicit declaration of function 'SSL_CTX_set_cert_cb' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        SSL_CTX_set_cert_cb(sscf->ssl.ctx, ngx_http_lua_ssl_cert_handler, NULL);
        ^
1 error generated.
make[1]: *** [objs/addon/src/ngx_http_lua_module.o] Error 1
make[1]: Leaving directory `/svr-setup/nginx-1.9.9'
make: *** [install] Error 2
```

I believe it's related to check for OpenSSL version at https://github.com/openresty/lua-nginx-module/blob/08c32bc08b15fa5029d807690d88d3f0caee70c6/src/ngx_http_lua_module.c#L895-L903 or something else ? I am using LibreSSL 2.2.5 instead of OpenSSL 1.0.2e

edit:

Looks like LibreSSL doesn't support SSL_CTX_set_cert_cb like OpenSSL 1.0.2+. OpenSSL i can find references to it https://github.com/openssl/openssl/search?utf8=✓&q=SSL_CTX_set_cert_cb but no reference in LibreSSL code https://github.com/libressl-portable/portable/search?utf8=✓&q=SSL_CTX_set_cert_cb. Is there any flag I can pass to just disable that part of 0.10.0 ?

cheers

George

**Comment by agentzh** [comment]
@centminmod I didn't know nginx already supports libressl. What are your exact building steps? I'd like to give it a short on my side. Thanks.

**Comment by agentzh** [comment]
@centminmod Alas. It seems that LibreSSL pretends to be OpenSSL 2.0 but it does not even provide OpenSSL API functions defined in OpenSSL 1.0.2. Very bad. We'll have to explicitly test if the current ssl library is LibreSSL.

**Comment by centminmod** [comment]
@agentzh sorry for late reply.. yes i have been using libressl instead of openssl for the past 8 months with my Centmin Mod LEMP stack https://community.centminmod.com/threads/nginx-and-libressl-alternative-to-openssl.3146/

but yes i found LibreSSL doesn't support the OpenSSL 1.0.2 feature that you added into 0.10 so i added support so if lua nginx 0.10 is detected my nginx compilation falls back to openssl 1.0.2f and if lua nginx <0.10 detected uses libressl 2.2.6 - the routines are in https://github.com/centminmod/centminmod/blob/123.09beta01/inc/nginx_configure.inc#L2-L12 just hack job to keep everyone happy :)

**Comment by agentzh** [comment]
@centminmod You're welcome to submit a patch to ngx_lua to disable those ssl_certificate_by_lua* stuff for libressl.

**Comment by centminmod** [comment]
unfortunately don't have the coding chops for it heh

**Comment by agentzh** [comment]
@centminmod I prefer macro tests instead of auto feature detection (the latter adds time to the building process).

**Comment by agentzh** [comment]
@centminmod Fixed the compilation errors in git master. Thanks for the report.
