### ISSUE TITLE
Regex pattern first and last character in openresty

### ISSUE THREAD

**Issue by Asoul** [openresty/lua-nginx-module#655]
Hi,
I want to match first and last character in openresty, but **^** and **$** have already used to reserved character. What is the **CORRECT** syntax in openresty?
Thanks

**Comment by agentzh** [comment]
@Asoul If you are talking about the PCRE-based `ngx.re` API here, then you can just use back slashes to escape these meta characters, as in

```console
$ resty -e 'fr,to=ngx.re.find("^$", [[\^\$]], "jo") ngx.say(fr,", ",to)'
1, 2
```

**Comment by agentzh** [comment]
@Asoul BTW, such general questions should really go to the openresty-en mailing lists and we'd like to leave this Issues board for "real issues" :) Please see https://openresty.org/#Community Thanks for your cooperation!

**Comment by Asoul** [comment]
OK, thanks
