### ISSUE TITLE
Can I specify encoding of "ngx.escape (str)".

### ISSUE THREAD

**Issue by linsongze** [openresty/lua-nginx-module#658]
Can I specify encoding of "ngx.escape (str)".
Such as result of  escape("中文","gbk") is "%d6%d0%ce%c4" , and escape("中文","utf8") is "%e4%b8%ad%e6%96%87".

**Comment by doujiang24** [comment]
Actually Lua doesn't have encoding related with string.
You have to convert the encoding yourself.
Maybe you want this: https://github.com/ittner/lua-iconv

**Comment by linsongze** [comment]
Thx!
