### ISSUE TITLE
使用 ngx.req 就 500 错误

### ISSUE THREAD

**Issue by yccphp** [openresty/lua-nginx-module#662]
ubuntu: 14.04 
luajit: 2.0.4
lua-nginx-module: v0.1.6rc2-0-gccaf132

ngx.say 是没有问题的

ngx.var. 也都没问题

但是只要使用 ngx.req. 都会500错误

`nginx.conf`

```
location /lua {
		default_type text/html;
		#lua_code_cache off;
		#content_by_lua_file /etc/nginx/lua/t.lua;
		content_by_lua 'ngx.say("user-agent : ", ngx.req.get_headers()["user-agent"], "<br/>")';
	}
```

`error.log`

```
attempt to index field 'req' (a nil value), 
```

请问是什么原因

**Comment by doujiang24** [comment]
@yccphp Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/#Community Thanks for
your cooperation.

Regarding your question, the lua-nginx-module seems too old, it is 0.10.0 now.

**Comment by yccphp** [comment]
Ok, thank you
