### ISSUE TITLE
nginx 1.9.11 incompatibility

### ISSUE THREAD

**Issue by nzt4567** [openresty/lua-nginx-module#668]
Hi,

new nginx version removes ngx_udp_connection_t which is used in lua module -> it will not compile :'(

Thanks,
Tomas

**Comment by teward** [comment]
I was about to poke here, too, about this issue.  Heh.

**Comment by agentzh** [comment]
The compilation error should be gone now.

**Comment by sumantdas** [comment]
seems the issue is coming again in the current master branch

**Comment by agentzh** [comment]
@sumantdas Fixed. Thanks for the report.

BTW, why are you using such an old nginx core? We no longer do thorough testing against such old nginx cores.

BTW2: it's highly recommended to use OpenResty to make sure the best compatibility and stability:

http://openresty.org/en/download.html

**Comment by sumantdas** [comment]
@agentzh - I dont think i have mentioned anything related to using old nginx core.

**Comment by agentzh** [comment]
@sumantdas It's definitely older than 1.11.2. Mind you, the latest nginx core version is 1.13.7:

http://nginx.org/
