### ISSUE TITLE
Excessive CLOSE_WAIT v1.9.7.3

### ISSUE THREAD

**Issue by krg7880** [openresty/lua-nginx-module#670]
I am experiencing an issue where there are excessive CLOSE_WAIT TCP states that, ultimately, renders the app unresponsive. It seems similar to Issue #298 as I was able to replicate using httperf. 

The origin of the issue was from a third-party who connects to the API using a GoLang HTTP client. Is this a known issue with OpenResty 1.9.7.3? I have been investigating for a few days now and it's not very clear why this is happening. 

I enabled debugging mode when compiling OpenResty and see quite a few *EAGAIN (Resource temporarily unavailable)*  which I am assuming is referencing Redis, however, that's not entirely clear at this point.

**Comment by agentzh** [comment]
@krg7880 No, there's no other reports on that. It'll be great if you can provide a minimal and standalone example that we can reproduce the issue with precise steps. We cannot help you without seeing more details. Please see

http://openresty.org/faq.html#how-should-i-report-a-problem

**Comment by agentzh** [comment]
@krg7880 EAGAIN is completely normal and also common for nonblocking I/O operations.

**Comment by krg7880** [comment]
@agentzh no problem! I'll try to provide more details. Thanks for the link reference.

**Comment by krg7880** [comment]
@agentzh This isn't much of an update per-se as I am still trying to understand how this is happening with a particular client. The one thing I notice consistently with *perf top*

Samples: 5M of event 'cycles', Event count (approx.): 341625886017
  96.44%  libluajit-5.1.so.2.1.0                       [.] lj_cf_table_insert
   0.21%  libluajit-5.1.so.2.1.0                       [.] lj_tab_len
   0.07%  libluajit-5.1.so.2.1.0                       [.] lj_BC_TGETS
   0.06%  libluajit-5.1.so.2.1.0                       [.] lj_BC_RET

Still trying to dig up more info, but thought i'd post this in the event it rings a bell

**Comment by agentzh** [comment]
@krg7880 Sounds like a suspiciously hot (or infinite?) Lua loop keeping inserting huge amount of data into a Lua table (or many Lua tables?) Better plot a Lua-land flame graph tool I keep suggesting you here:

https://github.com/openresty/stapxx#lj-lua-stacks

Please do that.

Failing that, manually fetching a dozen samples of Lua backtraces via the GDB command lbt can be insightful regarding the culprit in your Lua code base:

https://github.com/openresty/nginx-gdb-utils/#lbt

**Comment by agentzh** [comment]
Any updates on this issue?

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by krg7880** [comment]
@agentzh sorry about the delay. Yes it's resolved! The Lau-land flame graph tool identified the hotspot and I was able to resolve the issue. Thanks!
