### ISSUE TITLE
Too many symbols inside content_by_lua area

### ISSUE THREAD

**Issue by sdmrnv** [openresty/lua-nginx-module#674]
Hi

When I try to use string variable inside content_by_lua block with long text assigned to it I have received  nginx compile error: nginx: [emerg] Lua code block missing the closing long bracket "]]"

For example:

server{
...
location = /test {
  .....bla-bla-bla...
  content_by_lua_block {
  ....
  local some_long_text = [[Lorem Ipsum.....many symbols....qwerty]];
  ngx.say(some_long_text);
  }
}

If I cut off symbols inside LOCATION (not only inside text variable) limiting them up to about 4 000 then all OK. There is the same problem if I even used content_by_lua_file. 

And unfortunately if I get this some_long_text variable from redis database (for example) I have receive 500 Internal Server Error when getting this location in my browser.  

Please help me with this problem because I am interested in this awesome module in my projects.

Thanks in advance
Sergey

**Comment by agentzh** [comment]
@sdmrnv Maybe you should try the `content_by_lua_file` directive instead? The `_by_lua_block` directives are not really meant for inlining large chunks of Lua code.

**Comment by sdmrnv** [comment]
Unfortunately content_by_lua_file  gives the same effect.  And I don't inline large Lua code...I only get variable with some text (for example, blog post) and I receive '500 Internal Server Error' for such text. But for small text all OK.

**Comment by agentzh** [comment]
@sdmrnv Seems like you indeed have a Lua syntax error in your code? Will you provide a minimal and standalone example that I can try on my side?

**Comment by sdmrnv** [comment]
Example is:

location = /test {
   default_type   text/html;
  content_by_lua_block {
      local post_txt = [[
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis dui vulputate, accumsan justo ac, iaculis elit. Sed erat elit, pretium sit amet semper vitae, porta ut ligula. Duis tellus ligula, tristique in nunc vitae, vulputate blandit mi. Mauris pharetra libero nisl, commodo accumsan elit suscipit nec. Fusce sit amet finibus nibh. Duis rhoncus enim a enim scelerisque pellentesque. Nam consequat consectetur gravida. In in lobortis nisl, ut tempor nisi. Donec tincidunt sem ut diam egestas fringilla eget eu nibh. In non auctor libero. Nam venenatis porttitor urna sed pharetra. Proin ut ante tincidunt, sodales eros ac, fringilla justo. Cras semper, massa vitae semper lobortis, lorem ex hendrerit leo, sit amet pretium tellus quam nec urna. Quisque mollis neque a lacus sagittis hendrerit. Donec ut est sit amet dui mattis luctus. In pulvinar, turpis sed rhoncus porta, mauris ligula facilisis elit, eu aliquet nisi lorem quis mauris.
Morbi placerat purus turpis, id consectetur lacus elementum sit amet. Fusce commodo urna ut elit hendrerit dapibus ut ut felis. Vivamus imperdiet massa augue, eget maximus ligula imperdiet finibus. Morbi finibus quam auctor, feugiat velit sed, elementum est. Proin molestie ipsum in sem feugiat posuere. Etiam sit amet ante tortor. Etiam nibh lorem, venenatis non tellus condimentum, molestie facilisis tellus. Morbi fermentum scelerisque erat sit amet rhoncus. Aenean iaculis eu nibh sit amet pulvinar. Nulla vitae nibh non sapien euismod suscipit. Suspendisse efficitur porttitor velit, non tempus urna elementum aliquam. Integer fringilla ligula nulla.
Nunc tincidunt felis at justo tempus, ac vestibulum nisl placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed a ultrices elit, vel lacinia ipsum. Donec libero urna, aliquam nec semper nec, dignissim ut lectus. Praesent nec malesuada sapien. Vestibulum egestas diam magna, sed tempor arcu pharetra quis. In hac habitasse platea dictumst. Donec congue, quam non lacinia viverra, ipsum orci semper magna, ac convallis est ipsum in neque. Donec vulputate a mauris nec ultricies. Nullam vestibulum mi in nisi placerat, et ullamcorper dolor elementum. Maecenas ut consectetur ex. Curabitur placerat nisi lorem, malesuada finibus mi tempor quis. Morbi ultrices, neque vitae vestibulum malesuada, metus ante gravida justo, quis consectetur sem orci a dui. Phasellus venenatis id mi sit amet pretium.
Vivamus ultricies dui in nunc pellentesque cursus. Curabitur condimentum interdum mi vitae ultricies. Curabitur neque nisi, aliquet sed pellentesque a, tempus facilisis turpis. Sed in ipsum sed eros euismod ultricies at sit amet libero. Phasellus vitae eros augue. Phasellus sed sollicitudin felis. Nulla facilisi. Ut dapibus ullamcorper urna, vitae ultrices turpis tincidunt vel. Nulla accumsan efficitur quam in blandit. Fusce sit amet dolor vulputate, semper dolor ac, efficitur purus. Ut purus urna, ullamcorper id facilisis eget, laoreet sed eros. Quisque vitae pretium ante, at mattis massa.
Vestibulum dolor arcu, fermentum sed metus ac, ultricies vestibulum felis. Phasellus tristique purus erat, nec luctus massa euismod vitae. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce sed suscipit est. Praesent commodo, leo a gravida aliquet, enim turpis faucibus est, sed mattis tortor eros eget ipsum. Duis imperdiet dui at dictum facilisis. Integer accumsan massa at nunc fringilla aliquet. In hac habitasse platea dictumst. Fusce id mi quis neque efficitur rutrum sit amet sit amet sapien. Donec quis sodales tortor, non aliquet nunc. Suspendisse velit tellus, consectetur a mi consectetur, ullamcorper scelerisque lacus.
Donec gravida blandit metus. Integer ut augue tempus, imperdiet risus eu, consequat nisi. Morbi sollicitudin nibh sed massa aliquet suscipit. Etiam non sodales odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras vel ex et urna egestas lobortis. Sed tincidunt mauris sit amet leo laoreet, quis congue dui hendrerit. In feugiat id enim vitae vestibulum.
In at orci dictum, bibendum augue in, pretium tellus. Aliquam ut quam consectetur, convallis mauris convallis, blandit metus. Cras non luctus arcu, quis feugiat mi. Duis fringilla eros ultrices, mattis arcu non, laoreet sapien. Nulla porta sit amet sem mattis fermentum. Nam molestie ornare nisl, ullamcorper malesuada mi ullamcorper vel. Sed eleifend, mauris et lobortis tempus, magna mauris accumsan justo, vel placerat quam purus a nibh. Maecenas sit amet malesuada sem. Aenean malesuada tortor sed commodo elementum. Fusce nec justo sapien. Quisque at arcu cursus, laoreet eros ac, bibendum massa. Nulla facilisi. Nunc eu lorem iaculis, consequat lorem semper, congue odio. In vulputate, velit ut placerat mollis, eros quam tristique mauris, quis laoreet ante nisi in elit.
Nam et felis nulla. Vivamus finibus lorem sit amet sodales imperdiet. Sed id elementum risus. Etiam posuere leo ex, ut ultricies est scelerisque id. Sed quis pulvinar ante. Mauris a pretium arcu, non fermentum lacus. Cras in sem quis massa volutpat fermentum. Ut porttitor venenatis velit. Quisque condimentum lobortis eleifend. Maecenas consectetur risus non ultrices sagittis.
Morbi at augue tempor nisi molestie finibus id nec ligula. Praesent maximus consequat neque ac eleifend. Fusce nisi sapien, consequat vitae bibendum non, malesuada id purus. Ut tincidunt dignissim tortor, a sollicitudin mauris venenatis in. Ut ut vehicula purus. Suspendisse a magna pharetra, facilisis sapien quis, mollis enim. Praesent at tortor vitae sapien porttitor semper. In facilisis nunc felis, interdum eleifend metus viverra a. Donec pharetra velit lacus, ac scelerisque est sollicitudin sed. Proin vestibulum leo in lorem dignissim, a vestibulum justo scelerisque. Curabitur a orci sed nisi aliquet maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et rutrum purus, viverra dapibus orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Vestibulum quis facilisis dui, eget faucibus dolor. Cras tristique auctor felis. Pellentesque ac tincidunt odio, ut luctus dui. Fusce et rutrum dui. Fusce ac felis sodales, accumsan dolor ac, hendrerit lectus. Fusce iaculis lacinia neque, nec rhoncus arcu molestie sed. Cras aliquam est nunc. Aenean lobortis aliquet luctus. Ut eget nulla eget nunc tincidunt euismod sodales quis ex. Aliquam sed rhoncus velit. Suspendisse bibendum felis non justo fermentum, ut consequat diam pharetra.
Nullam auctor faucibus urna sed pretium. Nunc lectus dui, cursus in sem quis, condimentum interdum odio. Etiam auctor ac est a eleifend. Nulla facilisi. Nullam placerat lacus ac nisl tincidunt congue ac eu metus. Vivamus placerat massa vel metus condimentum, suscipit egestas metus sollicitudin. Nullam porttitor ex ac lectus semper luctus. Quisque posuere est quam, vitae egestas nisl venenatis in. Praesent eu sodales nisl, et eleifend felis. Praesent non gravida risus, ut accumsan mi. Fusce vel leo convallis orci efficitur viverra sit amet eget lectus. In in lectus varius, feugiat tellus eu, blandit ex. Praesent non ex neque. Quisque ut ultrices libero. Nam commodo est elit, at laoreet ex consequat eget.
Integer suscipit ante nulla, vulputate egestas velit ultricies vitae. Donec at iaculis nibh. Aenean enim metus, elementum quis justo vitae, finibus accumsan mi. Cras bibendum tincidunt egestas. Proin velit sem, hendrerit eget mattis id, sollicitudin at nisl. Cras ac leo viverra turpis convallis vehicula. Phasellus eu sapien in ligula tristique convallis. Nunc eros magna, ultrices sed sem nec, sagittis vulputate mi. Duis leo mi, pharetra ac mollis ac, vehicula ut nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec in nunc ex. Cras vitae fringilla metus.
Morbi eu arcu maximus, tristique sapien nec, efficitur nisi. Vivamus sagittis ultrices luctus. Praesent mauris mauris, cursus vitae tincidunt ultricies, porttitor nec ipsum. Donec efficitur, eros vitae commodo ultrices, orci nibh efficitur mauris, ut vehicula metus eros sed neque. Quisque imperdiet orci eget arcu luctus tempor. Quisque odio libero, sodales at bibendum vel, porttitor id neque. Nullam vitae lacus mollis, facilisis risus a, fermentum neque. Praesent convallis fermentum efficitur. Sed et sem rhoncus, consequat odio ac, dictum lectus. Proin sit amet libero bibendum, hendrerit ante sed, euismod nisi. Nulla venenatis justo eu blandit tempus. Ut id nibh non risus scelerisque ornare eget ut augue. Cras ex sem, suscipit sit amet mauris non, porttitor eleifend velit. Ut eleifend dolor non augue commodo posuere.
Praesent a dignissim quam. Phasellus ornare libero sapien, ac malesuada risus tincidunt egestas. Nunc eget mollis elit. Duis id dignissim nibh. In lacinia dignissim nisl, ut vehicula nisi ultrices id. Proin quam tellus, congue eget dolor ac, ultrices blandit velit. Nam vel semper velit. Mauris faucibus nisi nec imperdiet eleifend. Aliquam erat volutpat. Praesent volutpat mauris sit amet dui feugiat, sit amet luctus purus tristique.
Morbi malesuada sodales nunc vitae ultricies. Etiam at tortor eget dui feugiat viverra vel at erat. Quisque ac sapien sit amet neque semper viverra. Duis vel mattis tortor. Pellentesque fringilla magna tincidunt elit congue dignissim. Aliquam a volutpat diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur at urna urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris tortor erat, congue vel interdum ac, eleifend sed odio. Pellentesque eu augue felis. Ut id mauris molestie, hendrerit nibh ut, pulvinar augue. Praesent laoreet vel odio sit amet porttitor.
In tempus, turpis vel tincidunt efficitur, massa augue vulputate odio, et mattis massa turpis at libero. Aenean nec dolor tortor. Etiam euismod id purus eget viverra. Duis id vehicula nisl. Phasellus semper aliquet sem, vitae scelerisque leo condimentum nec. Vestibulum bibendum neque vel viverra posuere. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus ut erat in ligula finibus bibendum. Duis pulvinar metus nec felis laoreet blandit. Maecenas massa magna, porttitor eget semper sodales, ullamcorper sit amet mauris.
Vivamus at feugiat nulla, non rhoncus lacus. Nunc nec semper leo, nec luctus purus. In fringilla, justo non rhoncus cursus, orci urna lacinia ex, eu consectetur velit magna vel ipsum. Phasellus at facilisis metus, eu gravida enim. Proin sed tellus mollis, convallis orci eu, mattis lectus. In et bibendum nisi, at convallis lacus. Duis ut arcu sed felis tempus auctor et in dui. Curabitur imperdiet eleifend turpis, sed pharetra quam hendrerit ut.
Mauris consequat faucibus ex, ac condimentum lorem porta ut. Morbi fringilla a dolor non pellentesque. Mauris imperdiet dui lacinia auctor varius. Quisque eu sapien tellus. Nunc pretium imperdiet lacus eu commodo. Vivamus ultrices condimentum leo vel volutpat. Nullam non molestie augue. Ut cursus magna et aliquam vehicula.
Cras egestas rutrum neque et interdum. Nullam imperdiet ultricies eleifend. Ut non ipsum at turpis condimentum imperdiet at id nunc. Aliquam id sollicitudin justo, at pretium augue. Nullam varius sem non odio condimentum dignissim. Aliquam accumsan laoreet euismod. Donec eu faucibus eros. Fusce malesuada risus vel massa tristique venenatis. Nunc nec feugiat erat, vitae aliquet dui. Integer ornare, mi id auctor efficitur, lacus ipsum malesuada est, vitae porta arcu risus sit amet ex. Curabitur mollis vel nibh vel volutpat. Pellentesque non orci non leo blandit tincidunt. Cras consectetur dapibus nunc porttitor finibus.
Quisque eu dignissim ligula, sit amet tristique nunc. Pellentesque cursus quis ante id ornare. Ut ac laoreet nulla. Vestibulum eleifend porttitor eros, vitae varius augue eleifend vel. Vivamus nec ante leo. Integer nec metus sed nunc sodales venenatis vel ut nisl. Sed imperdiet mauris nec dolor porttitor efficitur. Nullam dui lacus, blandit non fermentum a, posuere in eros. Vivamus quis euismod nulla. Sed in suscipit eros. Etiam luctus, metus eu laoreet fermentum, ex lacus hendrerit nisl, maximus ultricies turpis dui eget ligula. Integer dignissim nec lorem in lobortis. Vestibulum erat orci, luctus vitae dapibus quis, pellentesque nec urna.
      ]];
      ngx.say(post_txt);
}

**Comment by agentzh** [comment]
@sdmrnv Use of `content_by_lua_file` works for me using your test case. Here "large" means above 4KB. Here your long-bracket chunk is about 12KB already, not quite suitable for inlining via `content_by_lua_block {}`.

**Comment by agentzh** [comment]
@sdmrnv Are you sure you get the same `Lua code block missing the closing long bracket "]]"` error when you are using `content_by_lua_file`? It's impossible because only `_by_lua_block` directives can generate such errors. It looks like you did not start your nginx server properly with your new nginx.conf configurations.

**Comment by sdmrnv** [comment]
@agentzh You are right! If I used **content_by_lua_file** instead of **content_by_lua_block** the error disappears and all OK. It seems to me that my mistake was in copy-paste process when I have transferred code from nginx config to separate file that used in content_by_lua_file directive. Some strings were transferred not correctly and this gives me on the one hand compiling with no mistakes and '500 server error' in runtime and on the other hand - illusion that **content_by_lua_file** also doesn't work correctly in this case. 

Thanks for your help!
