### ISSUE TITLE
Lua issue 'directive is not allowed here'

### ISSUE THREAD

**Issue by itpp16** [openresty/lua-nginx-module#678]
All modules up to date, nginx 1.9.12
nginx: [emerg] "lua_shared_dict" directive is not allowed here

http {
    include       mime.types;
    default_type  application/octet-stream;
........
    lua_shared_dict testarea 1m;

**Comment by agentzh** [comment]
@itpp16 Because you didn't provide enough info, I can only guess here. This error message means two possibilities usually:

1. You didn't compile the ngx_http_lua module as a static module into your nginx binary, or
2. You did compile the ngx_http_lua module as a dynamic module but you forgot to load the module via the `load_module` directive in your `nginx.conf` (before using any directives provided by this module).

**Comment by itpp16** [comment]
Everything is build as static, nothing new other then the new 1.9.12 layout and "--add-module=" as before.

**Comment by itpp16** [comment]
It's caused by the new 'config', used the previous one which solved this issue. still have to figure out why. Surely the lua_upstream issue is related.

**Comment by agentzh** [comment]
@itpp16 NGINX 1.9.12 is not even released yet and I do not want to spend too much time on it right now. You're welcome to investigate if you are interested.

**Comment by itpp16** [comment]
I know, we always run with the latest code if possible to catch issues early on.

**Comment by itpp16** [comment]
and confirmed, all openresty modules work when using the previous (lua-nginx-module) config file

**Comment by agentzh** [comment]
@itpp16 I've just built the latest ngx_lua on Windows 10 with MinGW gcc + MSYS bash (with ngx_lua_upstream and nginx 1.9.7) and everything works including the following configuration:

```
lua_shared_dict dogs 1m;

server {
    location = /t {
        content_by_lua_block {
            local dogs = ngx.shared.dogs
            dogs:set("Tom", 32)
            ngx.say("Tom: ", dogs:get("Tom"))
        }
    }
}
```

**Comment by agentzh** [comment]
Because I failed to reproduce it on Windows myself. I'm closing this.

**Comment by domq** [comment]
For people who come here by Googling in 2018, the root cause is that `lua_shared_dict` [is indeed no longer allowed at the top level](https://github.com/openresty/lua-nginx-module#lua_shared_dict). Try putting it inside the `http { }` block.

**Comment by agentzh** [comment]
@domq It was never allowed in the top level since it's a directive of an http module.
