### ISSUE TITLE
Proxy-server how catch response http status code of web-server

### ISSUE THREAD

**Issue by zenboss** [openresty/lua-nginx-module#679]
I have a web-server and a proxy-server, My proxy-server want at  "body_filter_by_lua_block" catch http response status code of web-server 

So, How to do.
Thank you.

**Comment by zenboss** [comment]
OK, I found it. Just "ngx.status". It's right?

**Comment by agentzh** [comment]
@zenboss Yes it is. BTW, please join the openresty-en mailing list for such general questions. Thank you! Please see https://openresty.org/ for more details.
