### ISSUE TITLE
diffrent location lua code

### ISSUE THREAD

**Issue by 6api** [openresty/lua-nginx-module#680]
my nginx.conf like this

```
server {
    location /test {
        proxy_pass ...
    }
    location / {
        try_files $uri @cache;
    }
    location @cache {
        access_by_lua_file ....
        proxy_pass ...
    }
}
```

if i visite /test/foo/bar the access_by_lua_file code has been executed.
how can i ignore the lua code with the uri /test/foo/bar ?

**Comment by bjoe2k4** [comment]
Check for the uri in your lua code or add a second location:

```
server {
    location /test {
        proxy_pass ...
    }
    location / {
        try_files $uri @cache;
    }

    location = /test/foo/bar {
        try_files $uri @cache2;
    }

    location @cache {
        access_by_lua_file ....
        proxy_pass ...
    }

    location @cache2 {
        proxy_pass ...
    }
}
```

**Comment by agentzh** [comment]
@6api Logically `location /test` should take priority over `location /` for the request `/test/foo/bar`. Maybe you have other things messed up your nginx.conf. You can want to temporarily enable the nginx debugging logs to debug things. See

http://nginx.org/en/docs/debugging_log.html

The same steps apply to OpenResty as well.

Also see this documentation for an explanation on exactly how nginx matches locations against a particular request URI:

http://nginx.org/en/docs/http/ngx_http_core_module.html#location

**Comment by agentzh** [comment]
@6api BTW, such new comer questions should go to the openresty-en mailing list instead: https://openresty.org/#Community This place is reserved for real issues in the module. Please see http://openresty.org/faq.html#how-should-i-report-a-problem

**Comment by agentzh** [comment]
Consider it resolved.
