### ISSUE TITLE
ngx.req.get_post_args() generate a run time error when body data cached to disk

### ISSUE THREAD

**Issue by alexazhou** [openresty/lua-nginx-module#682]
syntax is: 
> args, err = ngx.req.get_post_args(max_args?)

seems like that should return a err message instead of raise a exception

**Comment by agentzh** [comment]
@alexazhou Agreed. Patches welcome :)

**Comment by agentzh** [comment]
Patch already applied. I'm closing this.

**Comment by alexazhou** [comment]
You are very nice~
Thank you!
