### ISSUE TITLE
MySQL failed to connect: timeout

### ISSUE THREAD

**Issue by ChStark** [openresty/lua-nginx-module#690]
Hi team, I read the documentation and Im trying to use the library but I cant do that so far.

```nginx
 location /mysqltest {
            resolver 8.8.8.8 valid=60s;
            resolver_timeout 30s;
            default_type application/json;
            content_by_lua_file app/mysql.lua;
 }
 ```

mysql.lua

```lua
local mysql = require "resty.mysql"
local db,error = mysql:new()

if not db then
  ngx.say("{response:'MySQL instance error'}")
  return
end

db:set_timeout(5000)

local ok,error,errno,sqlstate = db:connect{
  host = "real amazon rds uri ",
  port = 3306,
  database = "real database name",
  user = "root",
  password = "super secret password",
  max_packet_size = 1024*1024
}

if not ok then
  ngx.say("{response:'MySQL connecion error'}")
  return
end

res, err, errno, sqlstate =
    db:query("select * from devices")
if not res then
    ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
    return
end

local cjson = require "cjson"
ngx.say("result: ", cjson.encode(res))
```

I have the correct details of the db of course (tested with MySQL workbench) , I also tried the resovler 127.0.0.1 with dnsmasq.

and I always got _failed to connect: timeout_

**Comment by agentzh** [comment]
@ChStark My hunch is that there is network connectivity issues with wrong IP addresses. Try turning off IPv6 in your `resolver` directive, that is,

```
resolver 8.8.8.8 ipv6=off;
```

To debug the issue further, you can (temporarily) enable the debugging logs in your NGINX or OpenResty build. See

http://nginx.org/en/docs/debugging_log.html

It can give your more details on what's happening under the hood.

**Comment by agentzh** [comment]
@ChStark Oh, wait, you didn't specify a host in your `connect()` method call in your `mysql.lua` file?

**Comment by ChStark** [comment]
@agentzh  I obviously set the host, I just omitted in this snippet for security.

In the error log I have
`2016/02/28 19:21:19 [error] 10477#0: *1 lua tcp socket connect timed out, client: XXX.XXX.XXX.XXX, server: , request: "GET /mysqltest HTTP/1.1", host: "XXX.XXX.XXX.XXX"`

**Comment by ChStark** [comment]
Im going to be executing simple queries, do you recommend to use drizzle library instead of this one ?, or both are capable of handle the job ?

**Comment by ChStark** [comment]
Im using RDS, is there any special config I am missing ?

**Comment by agentzh** [comment]
@ChStark lua-resty-mysql is much more powerful and flexible than ngx_drizzle + ngx_rds_xxx.

**Comment by agentzh** [comment]
@ChStark I've already suggested turning off ipv6 in your resolver settings and enabling nginx debugging logs to see the actual IP address used for connecting to MySQL. Please follow these suggestions.

**Comment by ChStark** [comment]
I turned off ipv6 and the logs just said :

`2016/02/29 02:42:50 [error] 11401#0: *1 lua tcp socket connect timed out, client: 201.173.79.95, server: , request: "GET /mysql HTTP/1.1", host: "site.com"
2016/02/29 02:43:12 [info] 11401#0: *3 client closed connection while waiting for request, client: 201.173.79.95, server: 0.0.0.0:8080
`

**Comment by agentzh** [comment]
@ChStark What are the earlier debugging logs mentioning the IP address actually used? Grab that IP address and test network connectivity outside nginx to be sure. Again, I believe this is a network connectivity issue. Please keep in mind that lua-resty-mysql has been used in many production environments for years already.

**Comment by agentzh** [comment]
@ChStark Also, please ensure you are using the latest version of OpenResty to avoid running into old bugs.

**Comment by agentzh** [comment]
@ChStark The most interesting debugging log entries are those right before those 2 lines you mentioned, those lines with the "[debug]" tag.

**Comment by ChStark** [comment]
I dont know what exactly you are looking for, but I guess is the resolver part

```
2016/02/29 03:08:35 [debug] 20675#0: *1 lua creating new thread
2016/02/29 03:08:35 [debug] 20675#0: *1 http cleanup add: 0000000001B38E38
2016/02/29 03:08:35 [debug] 20675#0: *1 lua run thread, top:0 c:1
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket pool get keepalive peer
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket keepalive connection pool not found
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket connect timeout: 5000
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B56D90:176
2016/02/29 03:08:35 [debug] 20675#0: resolve: "adsoverflow.cdxbydnfgnts.us-west-1.rds.amazonaws.com"
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B56E50:176
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B56F10:52
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B31B10:70
2016/02/29 03:08:35 [debug] 20675#0: resolve: "adsoverflow.cdxbydnfgnts.us-west-1.rds.amazonaws.com" A 9344
2016/02/29 03:08:35 [debug] 20675#0: UDP socket 20
2016/02/29 03:08:35 [debug] 20675#0: connect to 8.8.8.8:53, fd:20 #3
2016/02/29 03:08:35 [debug] 20675#0: epoll add event: fd:20 op:1 ev:80002001
2016/02/29 03:08:35 [debug] 20675#0: send: fd:20 70 of 70
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B56F50:96
2016/02/29 03:08:35 [debug] 20675#0: event timer add: -1: 30000:1456715345719
2016/02/29 03:08:35 [debug] 20675#0: event timer add: -1: 5000:1456715320719
2016/02/29 03:08:35 [debug] 20675#0: *1 lua resume returned 1
2016/02/29 03:08:35 [debug] 20675#0: *1 lua thread yielded
2016/02/29 03:08:35 [debug] 20675#0: *1 http finalize request: -4, "/mysql?" a:1, c:2
2016/02/29 03:08:35 [debug] 20675#0: *1 http request count:2 blk:0
2016/02/29 03:08:35 [debug] 20675#0: worker cycle
2016/02/29 03:08:35 [debug] 20675#0: accept mutex locked
2016/02/29 03:08:35 [debug] 20675#0: epoll timer: 5000
2016/02/29 03:08:35 [debug] 20675#0: epoll: fd:20 ev:0001 d:00007FCC47CF4370
2016/02/29 03:08:35 [debug] 20675#0: post event 0000000001B60140
2016/02/29 03:08:35 [debug] 20675#0: timer delta: 74
2016/02/29 03:08:35 [debug] 20675#0: posted event 0000000001B60140
2016/02/29 03:08:35 [debug] 20675#0: recv: fd:20 134 of 4096
2016/02/29 03:08:35 [debug] 20675#0: resolver DNS response 9344 fl:8180 1/2/0/0
2016/02/29 03:08:35 [debug] 20675#0: resolver DNS response qt:1 cl:1
2016/02/29 03:08:35 [debug] 20675#0: malloc: 0000000001B56FC0:52
2016/02/29 03:08:35 [debug] 20675#0: resolver qs:adsoverflow.cdxbydnfgnts.us-west-1.rds.amazonaws.com
2016/02/29 03:08:35 [debug] 20675#0: resolver naddrs:1 cname:00007FFECE722EE2 ttl:4
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket resolve handler
2016/02/29 03:08:35 [debug] 20675#0: *1 name was resolved to 52.9.130.45
2016/02/29 03:08:35 [debug] 20675#0: resolve name done: 0
2016/02/29 03:08:35 [debug] 20675#0: event timer del: -1: 1456715345719
2016/02/29 03:08:35 [debug] 20675#0: resolver expire
2016/02/29 03:08:35 [debug] 20675#0: event timer del: -1: 1456715320719
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp operation done, resuming lua thread
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket calling prepare retvals handler 00000000004D0E80, u:0000000040077DA8
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket resolve retval handler
2016/02/29 03:08:35 [debug] 20675#0: *1 socket 21
2016/02/29 03:08:35 [debug] 20675#0: *1 epoll add connection: fd:21 ev:80002005
2016/02/29 03:08:35 [debug] 20675#0: *1 connect to 52.9.130.45:3306, fd:21 #4
2016/02/29 03:08:35 [debug] 20675#0: *1 http cleanup add: 0000000001B38F58
2016/02/29 03:08:35 [debug] 20675#0: *1 lua tcp socket connect: -2
2016/02/29 03:08:35 [debug] 20675#0: *1 posix_memalign: 0000000001B57000:128 @16
2016/02/29 03:08:35 [debug] 20675#0: *1 event timer add: 21: 5000:1456715320793
2016/02/29 03:08:35 [debug] 20675#0: recv: fd:20 -1 of 4096
2016/02/29 03:08:35 [debug] 20675#0: recv() not ready (11: Resource temporarily unavailable)
2016/02/29 03:08:35 [debug] 20675#0: worker cycle
2016/02/29 03:08:35 [debug] 20675#0: accept mutex locked
2016/02/29 03:08:35 [debug] 20675#0: epoll timer: 5000
2016/02/29 03:08:36 [debug] 20674#0: timer delta: 500
2016/02/29 03:08:36 [debug] 20674#0: worker cycle
2016/02/29 03:08:36 [debug] 20674#0: accept mutex lock failed: 0
2016/02/29 03:08:36 [debug] 20674#0: epoll timer: 500
2016/02/29 03:08:36 [debug] 20673#0: timer delta: 500
2016/02/29 03:08:36 [debug] 20673#0: worker cycle
2016/02/29 03:08:36 [debug] 20673#0: accept mutex lock failed: 0
2016/02/29 03:08:36 [debug] 20673#0: epoll timer: 500
2016/02/29 03:08:36 [debug] 20677#0: timer delta: 500
```
But I guess this is what you are looking for

**Comment by ChStark** [comment]
I am using the most recent openresty version by the way

**Comment by agentzh** [comment]
@ChStark The [error] message you given earlier did not match the [debug] messages you just pasted. Will you provide the complete session's debugging logs?

**Comment by agentzh** [comment]
@ChStark Also, try the following command on the exactly same machine running your nginx:

```
telnet 52.9.130.45 3306
```

Let's see if you can directly connect to that port in the first place.

**Comment by ChStark** [comment]
wow, I am ashamed, there was some misconfiguration with the VPC, thank you very much, sorry for bothering you

**Comment by agentzh** [comment]
@ChStark Glad you figured it out. Happy hacking with OpenResty :)

**Comment by 5290charlie** [comment]
@ChStark I'm having very similar issues to what you reported here. Can you post the solution that found with the VPC configuration?

I have tried everything I can think of (includes what was mentioned here). Here are some things I've tried from the EC2 instance that is having the issue:
- Add `ipv6=off` to affected nginx config
  - *nginx service won't even pass configtest with this set...*
- `telnet RDS_DNS 3306` 
  - *Connects successfully*
- `mysql -h RDS_DNS -u RDS_USER -p` (password given at prompt) 
  - *Connects and allows expected access to MySQL*

I'm feeling a bit ashamed at the moment also haha ... Can't seem to figure this one out, please let me know what you did to get it working!

I can attach logs/code if needed, but I'm hopeful that it's just a misconfiguration with the VPC same as you :)

Thanks!

**Comment by 5290charlie** [comment]
May have figured it out!
I tried changing the resolver line to the nameserver listed in my instance `/etc/resolv.conf`

Was:
`resolver 8.8.8.8 valid=300s;`

Changed to:
`resolver 172.31.0.2 valid=300s;`

Not entirely sure how some of the AWS networking magic happens, but this appears to have fixed the `resty.mysql` connection error I was seeing!

**Comment by ChStark** [comment]
@5290charlie Sorry I just opened this thread I was busy, glad to hear you resolved
