### ISSUE TITLE
log_format

### ISSUE THREAD

**Issue by wangyinsheng** [openresty/lua-nginx-module#691]
Hi,
   here is my log_format 
`log_format tick "$u_log"`
   while, in my lua code ,u_log is connected by several fields and ‘\t’, like this
`u_log = u_type .. "\t" .. u_user_id ..  "\t"  .. u_time;`
   the problem is the '\t' is translate to '\x09' in the log file, which make it a wrong format. 
 so what should i do to make it correct,Thank you for any suggestion!

**Comment by agentzh** [comment]
@wangyinsheng This is the automatic escaping behavior in the standard ngx_http_log_module:

http://nginx.org/en/docs/http/ngx_http_log_module.html

We can do nothing on our side but live with it.
