### ISSUE TITLE
Using balancer_by_lua_block with SSL results in crash

### ISSUE THREAD

**Issue by AWooldrige** [openresty/lua-nginx-module#696]
It seems that OpenResty does not support setting an SSL-enabled peer. Nginx will crash in `ngx_http_upstream_set_round_robin_peer_session()` while attempting to initiate the SSL connection.

Example fragment to reproduce the problem:

    upstream test-backend {
        server 0.0.0.1:1000 max_fails=3 fail_timeout=5s;
        balancer_by_lua_block {
          local balancer = require "ngx.balancer"
          local ok, err = balancer.set_current_peer("127.0.0.1", 443)
          if not ok then
            ngx.log(ngx.ERR, "failed to set the current peer: ", err)
            return ngx.exit(500)
          end
        }
        keepalive 512;
    }

    proxy_pass https://test-backend;

Note: we use `proxy_cache` together with `proxy_path` just in case this matters.

**Comment by agentzh** [comment]
@AWooldrige Thanks for the report! We'll look into this. BTW, just a quick question: can you reproduce the crash without configuring `proxy_cache`?

**Comment by AWooldrige** [comment]
Hi @agentzh, thanks for the quick reply! We've just tested without configuring `proxy_cache` and it still crashes.

**Comment by agentzh** [comment]
@AWooldrige Just committed a fix to git master. Please try it out on your side. Thanks!
