### ISSUE TITLE
Is it possible to run a code coverage test with luacov in openresty?

### ISSUE THREAD

**Issue by ms2008** [openresty/lua-nginx-module#701]
I just add `require("luacov.tick")` to the top of my api file. But it giving error as 
> runtime error: attempt to yield across C-call boundary.

 And I know it cannot be yielded in the middle of the require call in openresty, I'm pretty sure that there is no nonblocking I/O operations (including ngx.sleep) in the middle of `require` step in this case. so, what else other operations could raised this issue?

Is there any workaround to did a code coverage test in openresty?

**Comment by agentzh** [comment]
@ms2008 You need to put the line `require 'luacov.tick'` in the context of init_by_lua* and also turn off the JIT compiler (if you are using LuaJIT), as in

```nginx
init_by_lua_block {
    require 'luacov.tick'
    jit.off()
}
```

Then a file `luacov.stats.out` will be generated in the current working directory. You can further run `luacov` to generate the report file `luacov.report.out`. Just tested on my side. It's working.

**Comment by ms2008** [comment]
Yes, it works, but the result seems not very accurate...

Thanks all the same.

**Comment by agentzh** [comment]
@ms2008 Maybe you just need to decrease the size of the "tick" in luacov. Try the following patch, for example,

```
diff --git a/src/luacov/runner.lua b/src/luacov/runner.lua
index 90a7663..a169c2b 100644
--- a/src/luacov/runner.lua
+++ b/src/luacov/runner.lua
@@ -21,7 +21,7 @@ M.skip = skip
 local function on_line(_, line_nr)
    if tick then
       ctr = ctr + 1
-      if ctr == 100 then
+      if ctr == 3 then
          ctr = 0
          stats.save(data, statsfile)
       end
```

**Comment by ms2008** [comment]
I will give it a try, Thank you. Issue closed

**Comment by jmdacruz** [comment]
If seems that the latest version of luacov is somewhat configurable. I'm using something like this for doing code coverage in [Kong](https://github.com/Mashape/kong): 

```nginx
    init_by_lua_block {
      runner = require 'luacov.runner'
      runner.tick = true
      runner.init({savestepsize = 3})
      jit.off()

      kong = require "kong"
      kong.init()
    }
```

This should (in theory) do the same thing as the patch provided above, although I'm not getting the expected results either (probably a different issue, though)

**Comment by agentzh** [comment]
@jmdacruz Nice! Thanks for the tip!

**Comment by lufb** [comment]
i had get the expected results in test::nginx as follows:
init_by_lua_block {
        require 'luacov.tick'
        jit.off()
    }
    log_by_lua_block {
      runner = require 'luacov.runner'
      runner.shutdown()
    }
