### ISSUE TITLE
how to group multiple requests into one action?

### ISSUE THREAD

**Issue by starius** [openresty/lua-nginx-module#702]
There is a nginx server and a backend. The backend can process multiple requests from clients at once in effective manner. I want to understand how to aggregate multiple requests in nginx.

Example. Requests from clients:
  * `?foo=bar`
  * `?foo=baz`

Desired request to backend:
  * `?foo=bar&foo=baz`

It should accumulate `foo`s with limits of time and number of items. When the limits are exhausted, it should make a single request to backend.

How to use in Lua:

```lua
-- foo.lua
local accumulate = require 'accumulate'
local get_answer = accumulate(100, 0.5, function(tasks)
    return array of answers, e.g. using ngx.location.capture_multi
end)
return function()
    nginx.say(get_answer(ngx.req.get_uri_args().foo)
end

-- nginx.conf
require('foo')()
```

Function `accumulate` takes limits for queue size and timeout (in seconds) and a function, which solves the problem for an array of inputs. It returns a function (`get_answer`), which operates as if it solves a problem for one input. It can be used in a request handler.

I got stuck at pausing a light thread. I want to pause it and then resume manually from a request handler which gets results from backend for all accumulated items. If I call `coroutine.yield()`, it is resumed at the same moment by Nginx. If I call `ngx.sleep(timeout)`, I have no means of cancelling this sleep (if it is ready before it expires).

**Comment by agentzh** [comment]
@starius Maybe you can use the ngx.semaphore API for synchronizing different request handlers served by each worker process:

https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/semaphore.md

**Comment by starius** [comment]
Thank you, @agentzh!
I tried to do it: https://github.com/starius/accumulate/blob/master/src/accumulate/accumulate.lua

Unfortunately, I discovered a bug/feature of lua-nginx. The location is blocked for all requests while you are in `ngx.sleep`, `nginx.thread.wait` or `sema:wait`. Consider the following code:

```
location /test {
  default_type text/html;
  content_by_lua '
    print("before sleep")
    ngx.sleep(5)
    print("after sleep")
  ';
}
```

I open two requests simultaneously. I expect to see the following in log:
```
[00:00] before sleep
[00:00] before sleep
[00:05] after sleep
[00:05] after sleep
```

But actually I observe the following:

```
[00:00] before sleep
[00:05] after sleep
[00:05] before sleep
[00:10] after sleep
```

The second request is processed after the first request as if the server is synchronous.

Other locations (including locations with Lua) work normally at the same time.

**Comment by agentzh** [comment]
@starius I think it's your web browser serializing concurrent requests for the same domain. ngx.sleep is nonblocking.

**Comment by agentzh** [comment]
@starius Better use other command-line utilities like curl and ab to run your tests.

**Comment by starius** [comment]
Thank you! It works.
