### ISSUE TITLE
ngx.append_body will block when I post null data

### ISSUE THREAD

**Issue by yuhai1023** [openresty/lua-nginx-module#703]
Nginx conf as follows:

```
server {
    listen 80;

    location / {
        access_by_lua_block {
            ngx.req.read_body()
            local body=ngx.req.get_body_data()
            ngx.req.init_body()
            ngx.req.append_body('some string transformed by body')
            ngx.req.finish_body()
        }
        proxy_pass http://localhost:8080;
    }
}

```
Then i post a null data:

`curl localhost -d ""`

And server blocks here ...

**Comment by doujiang24** [comment]
@yuhai1023 Thanks for you report, I can reproduce it on my side, I'll deep into it soon.

**Comment by doujiang24** [comment]
https://github.com/openresty/lua-nginx-module/pull/705
@yuhai1023 Can you have a try on your side? Thanks.

**Comment by yuhai1023** [comment]
It works for me : -)

**Comment by agentzh** [comment]
@doujiang24's fix has been committed to git master. Thanks for your report!
