### ISSUE TITLE
ngx.re.find: Which is the first capture to be matched?

### ISSUE THREAD

**Issue by alubbe** [openresty/lua-nginx-module#704]
I am using `ngx.re.find` to run regexs that look like this:
```
(abc)|(xy{2,4}z)|pe(.+?)ter
```
My problem is trying to figure out which of my three somewhat distinct subpatterns was the one that matched. Is there a way to do this?

If there isn't, I would like to propose that the optional `ctx` table could have a field `firstCapture` that, in my case, could equal 1, 2 or 3 depending on which is the first non-nil capture, or nil if the regex contains no captures. 

From reading https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_regex.c#L519 and onwards, I believe pcre gives us this information either through the capture table or pcre_exec's return value - but I don't fully understand it.

**Comment by agentzh** [comment]
@alubbe Maybe you just need to use `ngx.re.match` instead?

**Comment by alubbe** [comment]
Unfortunately, no. Using `match` or `gmatch` will tell me more about the captures, but a) it does not give the position of the match (e.g., `from` & `to`), which I absolutely need for my use case, and b) it is a lot more expensive than `find` because of the table allocation involved

**Comment by agentzh** [comment]
ngx.re.match does not have to allocate a new table since you can provide one via an argument and reuse the table over and over again. Also match() supports outputting a pos in the ctx table argument you give, which can be used to compute the offsets as returned by find().

**Comment by alubbe** [comment]
I had thought of that and dismissed it as feeling somewhat hacky at first,
but I'll try that approach, benchmark it and report back in the next few
days.
Am 11.03.2016 19:13 schrieb "Yichun Zhang" <notifications@github.com>:

**Comment by alubbe** [comment]
So good news, using match with a pre-allocated table and string.sub is 
fast enough, my issue is solved.
But I've noticed that while ngx.re.gsub(str, regex, STRING) is really 
fast, ngx.re.gsub(str. regex, FUNCTION) is a lot slower than what I've 
built: essentially a while loop using ngx.re.match and a ctx table, 
calling the FUNCTION on said match, taking the return value and 
concatenating those. Is there anything ngx.re.gsub does on top of that? 
Otherwise it might be interesting to explore replacing the current 
implementation of ngx.re.gsub with something similar to this.

**Comment by agentzh** [comment]
@alubbe Have you enabled lua-resty-core in your setup? It should make such cases much faster.

Regarding the slowness of function-typed arguments, this is because we have to take into account special cases like recursively calling `ngx.re.gsub()` or `ngx.re.sub()` in that function callback, hence the lack of aggressive optimizations.

**Comment by alubbe** [comment]
Yes, resty-core is enabled.

You are right, recursive calls prevent us from re-using the ctx and matches tables, but somehow my implementation still runs a bit faster (see below). I've also noticed that for large strings/subjects (>20KB), it's more performant to use a table and concat to prevent intermediary string allocations.
Anyways, here is what I've been benchmarking with:

```lua
local gsub = ngx.re.gsub
local match = ngx.re.match
local concat = table.concat
local insert = table.insert
local sub = string.sub
local assert = assert
local type = type
local function fastgsub(subject, regex, replace, options)
  local replaceType = type(replace)
  if replaceType == "string" then return gsub(subject, regex, replace, options) end
  assert(replaceType == "function")

  local ctx = {pos = 1}
  local matches = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}

  local foundAtLeastOneMatch = false
  local newstr = ""
  -- local newstrTable = {}
  while true do
    local oldPos = ctx.pos
    matches[0] = false
    match(subject, regex, "oj", ctx, matches)
    if matches[0] then
      -- insert(newstrTable, sub(subject, oldPos, ctx.pos - #matches[0] - 1))
      -- insert(newstrTable, replacer(matches))
      newstr = newstr .. sub(subject, oldPos, ctx.pos - #matches[0] - 1) .. replacer(matches)
      foundAtLeastOneMatch = true
    else
      if not foundAtLeastOneMatch then
        return subject
      else
        return newstr .. sub(subject, ctx.pos)
        -- return concat(newstrTable) .. sub(subject, ctx.pos)
      end
    end
  end
end
```
Does this overlook any edge cases that I may have missed?
Additionally I was thinking of having a ctx & matches table that always get reused, and if matches[0] is truthy, we must be in a recursive call so let's create a new one. But all non-recursive calls and the first call of a recursive call would get the speedup.

Something like
```lua
local matches = {false, false, false, false, .....}
matches[0] = false
local ctx = {pos = 1}
local function gsub()
  local matches = matches[0] and {} or matches
  local ctx = matches[0] and {pos = 1} or ctx
  ....
end
```

Here is how I've been measuring performance (not sure if luajit's optimizations skew the results somehow):
```lua
  local start = getTime()
  local _
  for i = 1, 1000 do
    _ = gsub(body, regex, replacer, "oj")
  end

  local halfway = getTime()
  local __
  for i = 1, 1000 do
    __ = fastgsub(body, regex, replacer, "oj")
  end

  local done = getTime()
```

**Comment by agentzh** [comment]
@alubbe For benchmark, you'd better use random subject strings to avoid string intern'ing that helps you too much.

**Comment by alubbe** [comment]
Thanks for the feedback. How would you suggest to do this while making sure our measurements include only the gsubbing, not the generation of random subject strings?
Here is attempt at it:
```lua
local char = string.char
local random = math.random
local concat = table.concat
local insert = table.insert
local function generateRandomString(length)
  local array = {}
  for i = 1, length do
    insert(array, char(random(32, 126)))
  end
  return concat(array)
end

local function generateBody()
  -- regex is [[someString|a-much-longer-string]]
  return generateRandomString(400) .. "someString" .. generateRandomString(300) .. "a-much-longer-string" .. generateRandomString(300)
end

local function runBenchmark()
  collectgarbage()
  local gsubTime = 0
  do
    local _
    for i = 1, 10000 do
      local body = generateBody()
      local temp = getTime()
      _ = gsub(body, regex, replacer, "oj")
      gsubTime = gsubTime + getTime() - temp
    end
  end

  collectgarbage()
  local fastgsubTime = 0
  do
    local _
    for i = 1, 10000 do
      local body = generateBody()
      local temp = getTime()
      _ = fastgsub(body, regex, replacer, "oj")
      fastgsubTime = fastgsubTime + getTime() - temp
    end
  end
end
```

**Comment by agentzh** [comment]
@alubbe You can regenerate the input strings and store them in a Lua table and in your timed code, just iterate through that table.

**Comment by alubbe** [comment]
Agreed. Would you let both cases use the same table/same strings or generate two different tables? I'm not familiar with how luajit interns strings and its other optimizations that might skew this benchmark.

**Comment by alubbe** [comment]
Here is what I am working with now. Any further suggestions?

```lua
local function runBenchmark()
  local stringTable = {}

  for i = 1, 10000 do stringTable[i] = generateBody() end
  collectgarbage()
  local gsubTime = getTime()
  for i = 1, 10000 do
    gsub(stringTable[i], regex, replacer, "oj")
  end
  gsubTime = getTime() - gsubTime

  for i = 1, 10000 do stringTable[i] = generateBody() end
  collectgarbage()
  local fastgsubTime = getTime()
  for i = 1, 10000 do
    fastgsub(stringTable[i], regex, replacer, "oj")
  end
  fastgsubTime = getTime() - fastgsubTime

  ngx.say("ngx.re.gsub runtime: " .. gsubTime)
  ngx.say("ngx.re.fastgsub runtime: " .. fastgsubTime)
end
```

**Comment by alubbe** [comment]
Assuming the above is now a fair assessment, not skewed by any JIT optimizations, I'd like to try out their performance in `body_filter_by_lua` and measure the amount of req/s for each implementation. 
```nginx
location /bench {
    root public;
    try_files $uri =404;
    body_filter_by_lua { require "gsubBenchmark"() } # this runs gsub on ngx.arg[1]
}
```
Would it be alright to always load the same url/same file/same body? My hope would be that, while nginx might cache the content, lua will always allocate a new string for it and thus, no unfair JIT optimizations kick in. What do you think?

**Comment by agentzh** [comment]
@alubbe You don't really need nginx.conf for this.

For example,

```lua
local data = {}
for i = 1, 10000 do
    data[i] = gen_random_string()
end

-- start timing here...
for i = 1, 10000 do
    run_ngx_re_api(data[i], ...)
end
-- stop timing here...
```

We do not need to worry about the intern'ing of the subject strings themselves, just string intern'ing in your benchmarked code. Basically, using `..` to build up a large string in a Lua loop is a very bad idea since it triggers one lj_str_new() call upon every loop iteration.

**Comment by agentzh** [comment]
Consider it resolved.
