### ISSUE TITLE
get_headers()["Cookie"] returns "table". Why?

### ISSUE THREAD

**Issue by vitaliy-orlov** [openresty/lua-nginx-module#710]
Hi, 

Here source code:
``` lua
local function check_cookie(key, defense)
	local counter = 0;
	local cookies = ngx.req.get_headers()['Cookie'];

	if cookies ~= nil then
	  ngx.log(ngx.ERR, ' >>> ' .. type(cookies) .. ' <<< ');
		for i,v in pairs(cookies:split(';')) do
			if v:find(cookie_name .. '=') ~= nil then
				counter = counter + 1;
			end
		end
	end
    
    ....
end
```

In some situations I get variable type "table" instead of the "string" for "cookies". Could you explain this behavior?

Example of log file:
```
2016/03/17 14:31:09 [error] 14389#14389: *78232203 [lua] handler.lua:165: check_cookie():  >>> table <<< ...
2016/03/17 14:31:09 [error] 14389#14389: *78232203 lua entry thread aborted: runtime error: /etc/nginx/handler.lua:166: attempt to call method 'split' (a nil value)
	/etc/nginx/handler.lua: in function 'check_cookie'
	/etc/nginx/handler.lua:264: in function 'on_request'
	/etc/nginx/handler.lua:293: in function </etc/nginx/handler.lua:1>
```

**Comment by shel3over** [comment]
same issue :  #713

**Comment by agentzh** [comment]
This is officially documented:

> For multiple instances of request headers such as:
> 
>  Foo: foo
>  Foo: bar
>  Foo: baz
> the value of ngx.req.get_headers()["Foo"] will be a Lua (array) table such as:
> 
>  {"foo", "bar", "baz"}

See https://github.com/openresty/lua-nginx-module#ngxreqget_headers for more details.

**Comment by vitaliy-orlov** [comment]
Thanks!

But as i know browsers always send a single "Cookie" header. It's strange to get many Cookie headers in request...

**Comment by agentzh** [comment]
@vitaliy-orlov You cannot really control what the clients in the wild may send to you :) Just be prepared.

**Comment by vitaliy-orlov** [comment]
@agentzh You are right :)
