### ISSUE TITLE
Can't dynamically reset userid cookie

### ISSUE THREAD

**Issue by Fry-kun** [openresty/lua-nginx-module#711]
I'm using http://nginx.org/en/docs/http/ngx_http_userid_module.html to set a cookie
At some point, I want set it to a new ID, so ngx.var.uid_reset = '1'. That works just fine -- but only as long as I haven't accessed ngx.var.uid_got or ngx.var.uid_set

If I read ngx.var.uid_set before doing a reset, then
   ngx.var.uid_set will not get the new value -- OOPS
elseif I read ngx.var.uid_got before doing a reset, then
   ngx.var.uid_set will get the new value -- YAY
   ...but the Set-Cookie header is not sent back to the user -- OOPS
elseif I read neither ngx.var.uid_set nor ngx.var.uid_got, then
  ngx.var.uid_set will get the new value -- YAY
  Set-Cookie header is sent back to the user -- YAY
  ...but I need to specify reset based on the old value of the cookie! -- OOPS

I've also tried doing a reset first, followed by clearing the header -- that doesn't work, either

Anything else I can do to reset the cookie (other than setting the header manually.. which needs base64 encoding, etc.)?

**Comment by Fry-kun** [comment]
Update: looks like this was a bad test setup on my part.
I set it  up as

``` lua
if extract_timestamp(ngx.var.uid_got) < ngx.var.msec then
    ngx.print(ngx.var.uid_got..' ~~ too old, generating a new one')
    ngx.var.uid_reset = '1'
end
```

so the problem wasn't reading uid_got -- it was just ngx.print() before dealing with headers

Note: if a cookie was given at query time, reading uid_set before uid_reset=1 keeps it at nil even after the reset. But reading it after will show the new value.
Sounds like there might be some caching going on?

**Comment by agentzh** [comment]
@Fry-kun There's no caching in the ngx_lua side. We just call the standard nginx variable C API to fetch and set nginx variables. If there were caching, then the builtin variables themselves allow that.

**Comment by Fry-kun** [comment]
Thanks for confirming
Guess this is just a peculiarity of how nginx works
