### ISSUE TITLE
At Sometimes ngx.req.get_headers()['User-Agent'] return a table but not a string

### ISSUE THREAD

**Issue by knightdf** [openresty/lua-nginx-module#713]
Here is what i got in my server's log:
03-19 11:34:38 ERROR [23257] [_handle] PCALL Error: UA In Request: ["Mozilla\/5.0 (X11; Linux x86_64; rv:34.0) Gecko\/20100101 Firefox\/34.0","Mozilla\/5.0 (X11; Linux x86_64; rv:34.0) Gecko\/20100101Firefox\/34.0"]
I use cjson to log the user-agent from "bad request", you can see that what i got is a table, but before this i always got string.
Versions:
    nginx 1.4.7
    lua-nginx-module 0.9.13

**Comment by agentzh** [comment]
Well, this is officially documented:

> For multiple instances of request headers such as:
> 
>  Foo: foo
>  Foo: bar
>  Foo: baz
> the value of ngx.req.get_headers()["Foo"] will be a Lua (array) table such as:
> 
>  {"foo", "bar", "baz"}

See https://github.com/openresty/lua-nginx-module#ngxreqget_headers for more details.

**Comment by knightdf** [comment]
well, ok, i thought that User-Agent will return as string. Thanks! I should read the document more careful!
