### ISSUE TITLE
How are errors handled in the co-routine of the user code in a request?

### ISSUE THREAD

**Issue by da99** [openresty/lua-nginx-module#716]
According to the [Introduction (wiki)](https://github.com/openresty/lua-nginx-module/wiki/Introduction), does an unexpected error in the co-routine of a request leads to NGINX handling the error w/ error message as an 50x HTTP status code?  For example:

1) request to NGINX  server ->  NGINX worker process ->
2) LuaJIT instance of worker process -> create/resume co-routine for user code ->
3) Uh-oh... error in co-routine -> false, error message
4) NGINX handles 50x HTTP Status Code, NGINX worker continues

**Comment by agentzh** [comment]
@da99 Yes, an uncaught Lua error leads to 500 error page on the nginx level. Well, it's easier to try it out yourself:

```nginx
location = /t {
    content_by_lua_block { error("bad!") }
}
```

**Comment by da99** [comment]
@agentzh Thank you very much.
