### ISSUE TITLE
why  ngx.location.capture("/old")  response  blank

### ISSUE THREAD

**Issue by winfan** [openresty/lua-nginx-module#717]
index index.html index.htm index.php;
     root /data/service;

     location ~ /Framework/yii/ {
            default_type 'text/html';
            content_by_lua '
             if ngx.var.arg__r == "base/abc/action/saveinfo" or ngx.var.arg__r == "base/bcd/whats/saveinfo" then
                 ngx.say(1)
                 ngx.location.capture("/new")
             else
                local res = ngx.location.capture("/old")
                ngx.say(res.body)
             end
            ';
     }

     location = /old{
         try_files $uri $uri/ /Framework/yii/index.php?$args;
     }

     location = /new{
        proxy_pass http://saveinfo;
     }

**Comment by winfan** [comment]
@agentzh please help me

**Comment by agentzh** [comment]
@winfan Do you know that `$uri` and `$args` become the subrequests' URI and querystring in that subrequest?
