### ISSUE TITLE
set cookie in body_filter_by_lua

### ISSUE THREAD

**Issue by systemdesign2** [openresty/lua-nginx-module#718]
For some reasons, I need to get the information (for example, "ABCD") from http body and set the information in cookie. My code is:
ngx.header['Set-Cookie'] = {'token=ABCD'}.

It works in header_filter_by_lua. However, it doesn't work if I apply it in body_filter_by_lua.

Any helps are really appreciated!!!

Thanks!

**Comment by agentzh** [comment]
@systemdesign2 HTTP cookies are encoded in the HTTP (response) header. In the context of `body_filter_by_lua*`, the response header has already been sent out. So we would need a time machine to set a cookie in that context :)

**Comment by agentzh** [comment]
@systemdesign2 You should at least do such things in `header_filter_by_lua*` instead.
