### ISSUE TITLE
does the 5th argument of  ngx.re.match make the 4th argument ctx.pos invalid?

### ISSUE THREAD

**Issue by iorichina** [openresty/lua-nginx-module#719]
the code:
`
local ctx, m = { pos = 1 }, {}
local _, err = ngx.re.match("2016-11-3 03:07:09", [=[^(\d\d\d\d)]=], "", ctx)
print(m[0], ' ', _[0], ' ', ctx.pos)
-- will output:nil 2016 5

local ctx, m = { pos = 1 }, {}
local _, err = ngx.re.match("2016-11-3 03:07:09", [=[^(\d\d\d\d)]=], "", ctx, m)
print(m[0], ' ', _[0], ' ', ctx.pos)
-- will output:2016 2016 1

`
openresty info:
`# /usr/local/openresty-1.9.7.2/bin/resty -V
resty 0.03
nginx version: openresty/1.9.7.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
built with OpenSSL 1.0.0s 11 Jun 2015
TLS SNI support enabled
`

**Comment by agentzh** [comment]
@iorichina This looks like a bug to me. Will you contribute a patch for it? Thanks!

**Comment by iorichina** [comment]
春哥吩咐，义不容辞，我会try，但不做承诺，lol

**Comment by agentzh** [comment]
@iorichina Thanks. But please use English here. Thank you :)

**Comment by iorichina** [comment]
@agentzh Sir, yes sir! lol

**Comment by agentzh** [comment]
The fix has been committed to git master.
