### ISSUE TITLE
why no ngx.req.set_post_args?

### ISSUE THREAD

**Issue by aaashun** [openresty/lua-nginx-module#722]
The latest API contains:
 * ngx.req.get_uri_args()
 * ngx.req.set_uri_args()
 * ngx.req.get_post_args()

but no ngx.req.set_post_args(), why?

**Comment by agentzh** [comment]
@aaashun Because this is trivial on the Lua land with the existing Lua API:

```lua
ngx.req.set_body_data(ngx.encode_args(args_table))
```
