### ISSUE TITLE
Logging to error_log syslog from ssl_certificate_by_* segfaults

### ISSUE THREAD

**Issue by JonathanSerafini** [openresty/lua-nginx-module#723]
Hi Friends, 

Using OpenResty 1.9.7.4, OpenSSL 1.0.2g on Ubuntu 14.04, I repeatedly receive segfaults when combining syslog error_log with the ssl_certificate_by_* statements. Below you can find the relevant portions from the configuration, with everything other than the affected lines omitted : 

This will print a log line to the file
`
http {
  error_log /tmp/logfile info;
  server { 
    ssl_certificate_by_lua_block {
      ngx.log(ngx.INFO, "OMGWTFBBQ")
    }
  }
}
`

This will segfault : 
`
http {
  error_log syslog:server=unix:/dev/log info;
  server { 
    ssl_certificate_by_lua_block {
      ngx.log(ngx.INFO, "OMGWTFBBQ")
    }
  }
}
`

Segfault line in syslog : Mar 24 15:30:36 vagrant kernel: [ 1771.074683] nginx[23051]: segfault at 0 ip 000000000044e5a7 sp 00007ffc833dada0 error 4 in nginx[400000+390000]

If you require more information, please don't hesitate to let me know.

**Comment by agentzh** [comment]
@JonathanSerafini Will you please provide a complete backtrace for the crash site? Thank you! Please see https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump for more details.

**Comment by gregkare** [comment]
I'm getting the same issue in both 1.9.7.4 and 1.9.15.1. Using `ngx.log` in a ` ssl_certificate_by_lua_block` when `error_log` is set to syslog will segfault. You don't actually need a working syslog setup for the example to work, you can use localhost or anything else

**Comment by agentzh** [comment]
@JonathanSerafini @gregkare Just committed a fix to the git master. Please try it out on your side. Thanks for your report!
