### ISSUE TITLE
bad $upstream_addr with the balancer feature,when proxy_next_upstream is occurred

### ISSUE THREAD

**Issue by guanglinlv** [openresty/lua-nginx-module#729]
hi,

Thanks the balancer feature firstly. it's so cool.

as the topic said, i have 2 server,`9.91.39.111:9075` and `9.91.39.111:9076`,the former is unavailable. if `proxy_next_upstream` occurs, the `$upstream_addr` return `9.91.39.111:9076, 9.91.39.111:9076` not `9.91.39.111:9075, 9.91.39.111:9076`. I think the unexpected value break the semantics of `upstream_addr`. so, is it a problem?

@agentzh 

Thanks.

**Comment by agentzh** [comment]
@guanglinlv I believe this issue has been addressed in one of those pending pull requests. Please check it out.

**Comment by guanglinlv** [comment]
@agentzh ,yeah, i really forget check that,thank you. 

FYI: relate PR,https://github.com/openresty/lua-nginx-module/pull/721

closing.
