### ISSUE TITLE
And content_by_lua of different content_by_lua_file

### ISSUE THREAD

**Issue by xfan1015** [openresty/lua-nginx-module#730]
With the same script and content_by_lua introduced content_by_lua_file
Content_by_lua_file introduced with post script content is relatively large when normal
Content_by_lua script with the introduction of post content will be reported when large lua entry thread aborted: runtime error: attempt to yield across C-call boundary

example
```
    server{
      client_max_body_size 30m;
      client_body_buffer_size 30m;
      listen 8080;
      location /p1
      {
              lua_code_cache  off;
              content_by_lua_file /home/num/nums.lua;
      }
      location /p2
      {
              lua_code_cache  off;
              content_by_lua 'require("/home/num/nums")';
      }
    access_log logs/nums-access.log;
    error_log logs/nums-error.log debug;
    }
```

nums.lua

```
ngx.req.read_body()
local reqbody=ngx.req.get_body_data() or nil
if reqbody==nil then ngx.exit(444) end
ngx.say(reqbody)
```

error.log
2016/04/07 20:44:40 [error] 8475#0: *1 lua entry thread aborted: runtime error: attempt to yield across C-call boundary
stack traceback:
coroutine 0:
        [C]: in function 'require'
        content_by_lua(nginx.conf:48):1: in function <content_by_lua(nginx.conf:48):1>, client: *.*.*.*, server: , request: "POST /p2 HTTP/1.1", host: "*.*.*.*:8080"

**Comment by agentzh** [comment]
@xfan1015 Maybe googling the error message is a good habit when seeing one. This is actually officially documented:

https://github.com/openresty/lua-nginx-module#lua-coroutine-yieldingresuming

Basically you are not writing a Lua module in the right way. See those lua-resty-* libraries for examples of how to create Lua modules correctly.
