### ISSUE TITLE
lua_shared_DICT used only 1/3.

### ISSUE THREAD

**Issue by KyoHS** [openresty/lua-nginx-module#731]
I set a lua_shared_DICT 300m; with exptime value 0, then I incr a lot of something to it, but I find when the shm comes to 100m, it is FULL. It only used 1/3.

**Comment by agentzh** [comment]
@KyoHS Please see this page on how to report a problem:

http://openresty.org/en/faq.html#how-should-i-report-a-problem

Basically we need more details to do anything useful. A standalone and minimal example that can reproduce the issue on our side would be ideal.

BTW, lua_shared_dict has been widely used in many companies' production environment for years already :)
