### ISSUE TITLE
Sharing data within a worker, with a timer

### ISSUE THREAD

**Issue by lightpriest** [openresty/lua-nginx-module#734]
I'm having a small issue which rarely happens, but I'm not sure I understand why it happens. I'm using OpenResty 1.7.10.1 with Lua 0.9.16.

I'm using a timed function (timer.at) to share data to incoming requests. The timer periodically reads a JSON file and updates a module. At the worker's requests, I'm using set_by_lua to set a variable that determines which proxy upstream to choose. My problem is that at some point in time, which I haven't figured out when, the workers are seeing an old copy of the data - i.e. they adhere to rules that are no longer in the file. Reloading NGINX solves the issue.

At first I thought that this was a problem with the rule logic, but we have a few NGINX servers that only a some of them are having this problem. Any ideas on why this even happens? Should I just use a shared.DICT and update it from a single worker (or from an endpoint request?).

The timer is initiated by this init_by_lua:
```
init_worker_by_lua '
  local timed_function
  timed_function = function(pre)
    -- Run in "protected call (pcall)" to catch errors
    if not pre then
      local status, err = pcall(
        function()
          local cjson = require "cjson"
          local rules_module = require "rules_module"

          rules_module.set(cjson.decode(io.open("/path/to/rule.json", "r"):read("*all")))
        end
      )

      if not status then
        ngx.log(ngx.ERR, "error in timed_function: ", err)
      end
    end

    ngx.timer.at(30, timed_function)
  end

  ngx.timer.at(0, timed_function)
';
```

This is the module:
```
local _M = {}

local rules = {}

function _M.set(data)
  local cjson = require("cjson")
  local new_rules = {}

  for id, rule in pairs(data) do
    new_rules[id] = cjson.decode(rule)
  end

  rules = new_rules
end

function _M.get()
  return rules
end

return _M
```

And this is what the worker runs:
```
location / {
  ..
  ..
  
  set_by_lua $backend_proxy '
    local rules_module = require "rules_module"
    local rules = rules_module.get()

    for _, rule in pairs(rules) do
      -- Some rule logic that sets the returned variable
    end

    return ngx.var.default_backend
  ';
}

```

**Comment by qlee001** [comment]
Why use json.decode in the function _M.set?
Maybe you can simple do it.

```
function _M.set(data)
    rules = data
end
```

**Comment by lightpriest** [comment]
@qlee001 The data is JSON serialized, but that's beside the point. How will not serializing help here? I mean, since I'm translating a file to a Lua table, I must serialize it somehow.

**Comment by agentzh** [comment]
@lightpriest I suggest you add logging code to your timer so that you can know what is going on in each worker's recurring timers. Remember to add the worker pid in your log messages. BTW, the latest OpenResty is 1.9.7.4. Better upgrade to the latest version to avoid hitting old bugs.

**Comment by lightpriest** [comment]
@agentzh You're right, I do have some logging in place, but the logging shows consistent output on all the workers and on all the servers. I'll try upgrading to see if it fixes the issue. I also created an HTTP endpoint that returns the current rule-set and the worker PID to try and find discrepancies in the worker's context.

I wonder if this is caused because I switch the table references, perhaps an in-place update would be better. In any case, I'll try upgrading to a newer release, maybe that'll do the trick. Thanks!
