### ISSUE TITLE
Send request to remote host

### ISSUE THREAD

**Issue by rumkin** [openresty/lua-nginx-module#737]
Is it possible to send sub-request to remote host with `ngx.location.capture` or other openresty method without magic with `proxy_pass`?

**Comment by agentzh** [comment]
@rumkin Depending on what protocol you are using to talk to the remote host. For HTTP and HTTPS, you can check out those lua-resty-http* libraries based on OpenResty's nonblocking cosocket API.

**Comment by rumkin** [comment]
Solved. Thanks :+1:
