### ISSUE TITLE
access_by_lua_file directive called twice for single page

### ISSUE THREAD

**Issue by bendpx** [openresty/lua-nginx-module#738]
I have the following confiugration:

nginx.conf
```
    server {
        listen 80;
        location / {
            access_by_lua_file access.lua;
            add_header Cache-Control "private, max-age=0, no-cache";
            root   /nginx/www;
            index  index.html;
        }
    }
```

access.lua
```
ngx.log(ngx.ERROR, "test")
return true;
```

for each browser refresh I get the log twice
```
2016/04/14 14:24:57 [error] 6#0: *1 [lua] access.lua:1: test, client: 192.168.99.1, server: , request: "GET / HTTP/1.1", host: "192.168.99.100:8888"
2016/04/14 14:24:57 [error] 6#0: *1 [lua] access.lua:1: test, client: 192.168.99.1, server: , request: "GET / HTTP/1.1", host: "192.168.99.100:8888"
```

this also happens when I curl the address.

what might cause this? thanks

**Comment by agentzh** [comment]
@bendpx This looks like nginx's internal redirect in action. You know that the `index` directive can initiate an internal redirect, hence rerunning the access phase handlers (and the rewrite phase too)?

**Comment by bendpx** [comment]
hey, thanks for replying.

it happens without it. 
is there a way for me to identify internal redirect in the lua access code?

**Comment by agentzh** [comment]
@bendpx `access_by_lua` never initiate internal redirects itself unless you explicitly uses Lua APIs like `ngx.exec` and `ngx.req.set_uri` in your own Lua code.

To debug such things, you can temporarily enable the nginx debugging logs to get details about the internal redirects and other things.

**Comment by bendpx** [comment]
my bad, I actually wasnt asking about the redirect code been initiated in the access_by_lua*, I was asking if there's any exposed global variable I can check in the lua code asking "is this block running after an internal redirect occured?"

**Comment by agentzh** [comment]
@bendpx You can use the `ngx.ctx` API for request-level bookkeeping. Consult the official documentation for more details.

**Comment by bendpx** [comment]
thanks!

**Comment by dafgar** [comment]
Hello.
According to documentation "Internal redirection will destroy the original request ngx.ctx data (if any) and the new request will have an empty ngx.ctx table." How could one use ngx.ctx to check if the lua code block is running after internal redirect?

**Comment by MarineJoker** [comment]
I also find this .The reason is the index directive.When I try to enter the full URL,it's normal
