### ISSUE TITLE
Switched from openssl1.0.1s to openssl1.0.2g and now  Lua VM fails to initialize.

### ISSUE THREAD

**Issue by ajrpayne** [openresty/lua-nginx-module#739]
When using nginx 1.9.14, luajit 2.0.4, lua-nginx-module 0.10.2,  and openssl1.0.1s nginx appears to start without issue.

However, when using nginx 1.9.14, luajit 2.0.4, lua-nginx-module 0.10.2, and openssl1.0.2g nginx will not start.

/etc/init.d/nginx start
* Caching service dependencies ... 
File descriptor 3 (pipe:[55368402]) leaked on lvm invocation. Parent PID 8516: /bin/sh 
/run/lvm/lvmetad.socket: connect failed: No such file or directory 
WARNING: Failed to connect to lvmetad. Falling back to internal scanning.                  [ ok ] 
 * Checking nginx' configuration ...
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:118
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:118
nginx: configuration file /etc/nginx/nginx.conf test failed
 * failed, please correct errors above                                                     [ !! ]
 * ERROR: nginx failed to start

**Comment by ajrpayne** [comment]
From strace

mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_32BIT, -1, 0) = -1 ENOMEM (Cannot allocate memory)

**Comment by agentzh** [comment]
@ajrpayne Will you try OpenSSL 1.0.2e instead?

**Comment by ajrpayne** [comment]
@agentzh 

I switched to 1.0.2e and the problem still exists.

write(3, "2016/04/16 22:42:19 [notice] 245"..., 92) = 92
gettid()                                = 24505
write(3, "2016/04/16 22:42:19 [notice] 245"..., 112) = 112
gettid()                                = 24505
write(3, "2016/04/16 22:42:19 [notice] 245"..., 93) = 93
gettid()                                = 24505
write(3, "2016/04/16 22:42:19 [notice] 245"..., 93) = 93
mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_32BIT, -1, 0) = -1 ENOMEM (Cannot allocate memory)
gettid()                                = 24505
write(3, "2016/04/16 22:42:19 [error] 2450"..., 98) = 98
write(2, "nginx: [error] failed to initial"..., 72nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:118
) = 72
close(4)                                = 0
munmap(0x7ff19014c000, 2152568)         = 0
munmap(0x7ff18f876000, 7098368)         = 0
brk(0x52427000)                         = 0x52427000
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by agentzh** [comment]
@ajrpayne Seems like your build of LuaJIT is bad. Maybe you have chosen to use the system allocator in LuaJIT for x86_64? That configuration will cause errors like this.

BTW, will you try using the OpenResty bundle without special flags?

https://openresty.org/en/download.html

It can avoid many mistakes in manually setting things up.

**Comment by ajrpayne** [comment]
@agentzh 

I installed using OpenResty 1.9.7.4. Same problem.

I will note, our nginx config is very large. I noticed that if I removed a number of server contexts nginx would start when using openssl 1.0.2g.

When using openssl 1.0.1s I noticed that if I added a number of extra server contexts the lua vm would fail to initialize. 

Are there any memory settings that need to be tweaked so that the luajit vm can allocate the memory it needs for large nginx configs?

**Comment by agentzh** [comment]
@ajrpayne LuaJIT needs the lowest 1GB address space for its GC allocated memory.

Some suggestions:

1. avoid defining too many https virtual servers in nginx.conf since it's very memory inefficient. try using a generic virtual server and dispatch different virtual hosts in Lua (via `ssl_ceritficate_by_lua*`, for example).
2. if you are on Linux, you can try the ljmm library to ensure that nginx and other things won't use the lowest 1GB address space and LuaJIT can use the lowest 2GB address space: https://github.com/cloudflare/ljmm

**Comment by ajrpayne** [comment]
@agentzh 

Thanks for the link. 

"On Linux/x86-64 platform, Luajit can use no more than 1G memory due to the combination of bunch of nasty issues."

Do you know if freebsd systems are effected? We have some running and the switch would be easy.

I'll give it a shot on one of them and I'll let you know the results.

I tried using standard lua5.1 and found the issue did not occur, but would like to avoid using that.

**Comment by agentzh** [comment]
@ajrpayne Yes, FreeBSD x86_64 is affected. You can try compiling your nginx as a PIE, which may help avoid nginx's memory allocations to occupy the lowest 1G or 2G address space.

**Comment by agentzh** [comment]
@ajrpayne Also consider my previous suggestion of using a generic virtual server to all your different hosts. Otherwise it's a waste of memory anyway.

**Comment by ajrpayne** [comment]
@agentzh 

Thanks a bunch, https://github.com/cloudflare/ljmm did the trick.

As for the generic virtual server for https, I don't think that'll work for us as each virtual server represents a unique client with unique needs.

**Comment by agentzh** [comment]
@ajrpayne CloudFlare, for example, runs many many different web sites in the same nginx server {} block. And their https and other settings are unique and wildly different :)

**Comment by alubbe** [comment]
ljmm is a really cool fix! Any chance of including this in the openresty bundle with a flag for configure to build it? There are probably a lot of Linux/x86-64 platform deployments and I only found out about ljmm today.

**Comment by agentzh** [comment]
@alubbe Yeah, we are going to include ljmm in OpenResty by default. And then extend support for FreeBSD x64 and Mac OS X x64 as well, and eventually support the full 4GB address space for each LuaJIT VM instance on x64 (right now ljmm enables the full 2GB address space).

**Comment by alubbe** [comment]
Awesome, thanks!

**Comment by agentzh** [comment]
@alubbe Oh, I've just noted that the latest LuaJIT v2.1's own allocator already supports the full 2GB address space. So we will no longer need ljmm once we upgrade to the latest LuaJIT :)
