### ISSUE TITLE
couple of cppcheck issues

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-nginx-module#742]
[src/ngx_http_lua_headers_in.c:246]: (error) Address of local auto-variable assigned to a function parameter.
[src/ngx_http_lua_headers_out.c:189]: (error) Address of local auto-variable assigned to a function parameter.

as far as I understand, those are not false positives.

**Comment by agentzh** [comment]
@chipitsine They are false positives since `&h[i]` is really `h + i`, so we are not really taking address of local auto-variables.
