### ISSUE TITLE
nginx crash when adding multiple access_by_lua_file

### ISSUE THREAD

**Issue by zousheng** [openresty/lua-nginx-module#743]
Hi,

Today I tried to add ngx_lua_waf into our nignx, but it crashed aftering adding it, our websize is not available, there is no specific log about this error. I guess this might be caused by the conflict with another acces_by_lua_file (route.lua) we used to do A/B release which is added in server block, and lua_waf is added in http block, I rollbacked the lua_waf after the crash, the site was recovered after one hour. Would you please give some advice on this?  thanks very much.

**Comment by agentzh** [comment]
@zousheng Because ngx_lua_waf is not maintained by us, I cannot help you with that. If you believe it is a bug in this ngx_lua module, please provide a minimal and self-contained example that we can run on our side and reproduce the "crash" you are seeing. Thanks for your cooperation.

**Comment by zousheng** [comment]
@agentzh Thanks for your comments, as the ngx_lua_waf is not active, I couldn't get support from that project, would you help advice if it's ok to run 2 lua scripts in same scope like http or server? If that's not possible I will try to put the waf script in rewite phase?  Really appreciate your time.

Thanks

**Comment by agentzh** [comment]
@zousheng It's faster to combine multiple Lua scripts on the Lua land instead of in nginx.conf. For example,

```nginx
access_by_lua_block {
    require("my_module1").go()
    require("my_module2").go()
    require("my_module3").go()
}
```

This way is much more efficient and much more flexible.

**Comment by zousheng** [comment]
Hi agentzh, thanks very much for your great adivce, I will learn about this about try to use it in our environment.

BRs,
