### ISSUE TITLE
assignment from incompatible pointer type

### ISSUE THREAD

**Issue by yiliaofan** [openresty/lua-nginx-module#753]
nginx1.9.15 compile error
<pre>
lua-nginx-module-0.9.20

c1: warnings being treated as errors
../modules/stream-lua-nginx-module/src/ngx_stream_lua_socket_tcp.c: In function ‘ngx_stream_lua_socket_resolve_handler’:
../modules/stream-lua-nginx-module/src/ngx_stream_lua_socket_tcp.c:819: error: assignment from incompatible pointer type
make[1]: *** [objs/addon/src/ngx_stream_lua_socket_tcp.o] Error 1
make[1]: Leaving directory `/alidata1/zhangfan/env-trunk/nginx/nginx-1.9.15'
make: *** [build] Error 2
</pre>

<pre>
lua-nginx-module-0.10.2

I src/http/modules -I src/http/v2 -I /usr/local/include/luajit-2.0 -I src/stream \
		-o objs/addon/src/ngx_stream_lua_socket_tcp.o \
		../modules/stream-lua-nginx-module/src/ngx_stream_lua_socket_tcp.c
cc1: warnings being treated as errors
../modules/stream-lua-nginx-module/src/ngx_stream_lua_socket_tcp.c: In function ‘ngx_stream_lua_socket_resolve_handler’:
../modules/stream-lua-nginx-module/src/ngx_stream_lua_socket_tcp.c:819: error: assignment from incompatible pointer type
make[1]: *** [objs/addon/src/ngx_stream_lua_socket_tcp.o] Error 1
make[1]: Leaving directory `/alidata1/zhangfan/env-trunk/nginx/nginx-1.9.15'
make: *** [build] Error 2
</pre>

**Comment by agentzh** [comment]
@yiliaofan You are reporting to the wrong GitHub repository? This is `lua-nginx-module` but your error message indicates `stream-lua-nginx-module`.

Regarding your problem, you should really use the latest git masters of both nginx modules for NGINX 1.9.15.

**Comment by agentzh** [comment]
Consider it resolved.
