### ISSUE TITLE
mysql / test / initialisation ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-nginx-module#754]
Hello,

I'm working on travis-ci support, there're tests on mysql, however, I didn't find any script for database initialisation

what do you think of

-------------<begin>----------
create database ngx_test;
grant all on ngx_test.* to 'ngx_test'@'%' identified by 'ngx_test';
flush privileges;
-------------<end>---------------

somewhere in t/database.mysql ?

**Comment by chipitsine** [comment]
well, I think the best way would be  several

mysql -e '....'

statements within .travis.yml

**Comment by agentzh** [comment]
Yeah, putting them in `.travis.yml` is fine.
