### ISSUE TITLE
Some help with a basic lua script

### ISSUE THREAD

**Issue by techpulse** [openresty/lua-nginx-module#758]
ngx.header.content_type = 'text/plain'
ngx.say("Banned")
ngx.exit(403)

For some reason, nginx is returning:

*2183013 attempt to set status 403 via ngx.exit after sending out the response status 200, client:

How can i fix this

**Comment by ndenev** [comment]
Maybe you need this? : https://github.com/openresty/lua-nginx-module#ngxstatus

**Comment by es** [comment]
@techpulse it sounds like you may be running your code in the wrong context. Can you include the context in which your code is being executed?

**Comment by blablacio** [comment]
The reason for this is that you call ngx.say() before ngx.exit(403).

The `ngx.say()` call outputs response body data so it also triggers sending out the default response header which is 200.

See `ngx.print()` documentation (same goes to `ngx.say()`): https://github.com/openresty/lua-nginx-module#ngxprint

Use `ngx.log()` for debugging purposes instead (or swap the two statements if you insist).

**Comment by ndenev** [comment]
Just adding a ```ngx.status = 403``` call before ```ngx.say()``` would be sufficient.
At least that's what I'm doing in one of my scripts and is working:
```
ngx.header.content_type = "text/plain"
ngx.status = 403
ngx.say("Forbidden")
return ngx.exit(403)
```

Yes, maybe setting the code in ngx.exit() too is redundant.

**Comment by agentzh** [comment]
@ndenev Yes, your way is the right way.
