### ISSUE TITLE
"Lua code block missing the closing long bracket "]]" if bracket is at offset >=4096

### ISSUE THREAD

**Issue by redbaron** [openresty/lua-nginx-module#762]
Version used: 1.9.7.4

If closing bracket in a *_by_lua_block is located at absolute offset >=4096 relative to beginning of the file, it is incorrectly not recognized.

here is a minimal file demonstrating the problem https://gist.github.com/redbaron/e50e8436d70421c285736d821ac23427

**Comment by tmthrgd** [comment]
I've hit the same bug(?). #674 is related.

**Comment by agentzh** [comment]
Please try the following patch for lua-nginx-module (for OpenResty 1.9.7.4, just apply the patch to `bundle/ngx_lua-*/`).

```diff
diff --git a/src/ngx_http_lua_directive.c b/src/ngx_http_lua_directive.c
index 2d04816..e6bc339 100644
--- a/src/ngx_http_lua_directive.c
+++ b/src/ngx_http_lua_directive.c
@@ -1480,7 +1480,10 @@ ngx_http_lua_conf_read_lua_token(ngx_conf_t *cf,

     for ( ;; ) {

-        if (b->pos >= b->last) {
+        if (b->pos >= b->last
+            || (b->last - b->pos < (b->end - b->start) / 3
+                && cf->conf_file->file.offset < file_size))
+        {

             if (cf->conf_file->file.offset >= file_size) {

@@ -1493,7 +1496,7 @@ ngx_http_lua_conf_read_lua_token(ngx_conf_t *cf,
                 return NGX_ERROR;
             }

-            len = b->pos - start;
+            len = b->last - start;

             if (len == buf_size) {

@@ -1531,8 +1534,8 @@ ngx_http_lua_conf_read_lua_token(ngx_conf_t *cf,
                 return NGX_ERROR;
             }

-            b->pos = b->start + len;
-            b->last = b->pos + n;
+            b->pos = b->start + (b->pos - start);
+            b->last = b->start + len + n;
             start = b->start;

 #if nginx_version >= 1009002
```

This should fix your minimal example at least. Still this is a workaround and a major refactoring of the parser is still required in the near future :)

**Comment by agentzh** [comment]
@doujiang24 Your eyes on my patch above will also be appreciated :)

**Comment by tmthrgd** [comment]
@agentzh the patch has fixed the issue I was facing. Thanks, keep up the good work!

**Comment by agentzh** [comment]
@tmthrgd Great! Thanks for your feedback!

**Comment by redbaron** [comment]
Thanks for a prompt response and provided fix!
