### ISSUE TITLE
auth_request in util/build.sh

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-nginx-module#765]
nginx supports auth_request since 1.5.4+

http://nginx.org/ru/docs/http/ngx_http_auth_request_module.html

do we actually need earlier versions?
if so, we can make a switch like

[ilia@localhost nginx-1.9.15]$ ./configure --help | grep auth_request
  --with-http_auth_request_module    enable ngx_http_auth_request_module
[ilia@localhost nginx-1.9.15]$

**Comment by agentzh** [comment]
@chipitsine Nice catch. Fixed in git master.
