### ISSUE TITLE
Argument Delimiter

### ISSUE THREAD

**Issue by dakanji** [openresty/lua-nginx-module#77]
Hi.

I have a PHP application that uses ";" to delimit GET arguments as in "/index.php?a=1;b=2". It seems that get I run ngx.req.get_uri_args, this gets passed as a single argument "a=1;b=2" instead of two, "a=1" and "b=2".

Using ngx_lua to filter inputs, I am getting many false positives because of this. Is it possible to tell the app to consider other delimiters apart from "&" as it is in PHP?

Thanks

**Comment by JayceJiaa** [comment]
@agentzh Hey, Yichun.

Any progress on this feature? I encountered the same problem in some old systems.

I assume all the `reserved characters` in [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2) should be able to be configured as parameter delimiters.

Thanks!

**Comment by dakanji** [comment]
Guess it's about time to close this one down!
