### ISSUE TITLE
build with luajit2.1

### ISSUE THREAD

**Issue by nzt4567** [openresty/lua-nginx-module#772]
Greetings,

_config_ only searches in _/usr/local/include/luajit-2.0_ while luajit2.1 places its headers into _/usr/local/include/luajit-2.1_

As usually - thanks for development ;)

Take care!

**Comment by agentzh** [comment]
@nzt4567 You're recommended to explicitly set the `LUAJIT_INC` and `LUAJIT_LIB` environments. I don't want to touch the auto-detection stuff any more since it's already a mess :)

**Comment by nzt4567** [comment]
Thanks for the tip ;) I've hacked it simply by changing the path to the headers but this seems like far more better solution. Closing now aaaaand thanks again :)
