### ISSUE TITLE
Upgrade nginx/1.8.1 to nginx/1.10.0 - Error: Unknown directive "content_by_lua_file

### ISSUE THREAD

**Issue by nalexs** [openresty/lua-nginx-module#773]
Hello,

After Upgrade nginx/1.8.1 to nginx/1.10.0 appeared error: nginx: [emerg]  Unknown directive "content_by_lua_file

location ~* /test.txt {
           content_by_lua_file '/usr/local/etc/nginx/conf.d/test.lua';

tell me please how to fix this error?

**Comment by agentzh** [comment]
@nalexs This error message is usually a clear indication that you are invoking a wrong nginx binary executable that does not have ngx_lua compiled in.

**Comment by microbash** [comment]
Check your nginx.conf, it must have line like this
load_module /usr/local/libexec/nginx/ngx_http_lua_module.so;

https://nginx.org/en/docs/ngx_core_module.html#load_module

**Comment by agentzh** [comment]
@microbash It depends on whether the ngx_lua module is compiled as a dynamic module.

It's highly recommended to use OpenResty releases:

http://openresty.org/en/download.html
