### ISSUE TITLE
ngx.socket doesn't use connection pool after call tcpsock:connect twice

### ISSUE THREAD

**Issue by fanchangyong** [openresty/lua-nginx-module#775]
Hi, I don't know if it is a bug, here is the testcase:
`nginx.conf`:
```nginx
{
  http{
    server {
      listen 80;
      access_by_lua_file "test_sock.lua"
    }
  }
}
```

`test_sock.lua`:
```lua
local sock = ngx.socket.tcp()
-- connect to redis server
local ok, err = sock:connect("127.0.0.1", 6379)
-- call connect again
sock:conect("127.0.0.1", 6379)

local times, err = sock:getreusedtimes()
ngx.say("reused times: ", times, ", err: ", err)
local ok, err = sock:setkeepalive(0, 100)
```

then http request:
`curl localhost:80`

from the redis server log, I found it would close the connection first before calling the second `tcpsock:connect` function. And if I call `tcpsock:connect` only once, it would use the connection pool correctly.

**Comment by saks** [comment]
As far as I understand you should return socket back to pool before calling `connect` second time. Have you tried that?

**Comment by fanchangyong** [comment]
@saks So, you mean I have to call `tcpsock:setkeepalive` before the subsequent `connect` call?
 I've tried this, it worked. Thank you!
