### ISSUE TITLE
ngx.worker.id() in init_worker_by_lua directive

### ISSUE THREAD

**Issue by eminden** [openresty/lua-nginx-module#776]
when proxy_cache enabled, nginx spawns two more process(cache loader process, cache manager process), using  ngx.worker.id() in init_worker_by_lua directive returns 0 for cache manager process and the first worker process. I suppose ngx.worker.id() should return unique integer values?

Is there an way to prevent cache related process not involved in init_worker_by_lua directive or any way to return from init_worker script in case the worker is a cache process?

local worker_key = string.format("%s_%d_%d_%d", "ngx_worker", ngx.worker.id(), ngx.worker.pid(), ngx.worker.count())
ngx.log(ngx.ERR, worker_key)

$ ps aux| grep nginx:
root            26012   0.0  0.1  2607476  12136   ??  Ss   Wed04PM   0:00.75 nginx: master process 
nobody          **38422**   0.0  0.0  2607476   3020   ??  S     5:49PM   0:00.01 nginx: cache manager process  
nobody          38421   0.0  0.1  2610832   6088   ??  S     5:49PM   0:00.01 nginx: worker process  
nobody          38420   0.0  0.1  2610832   6092   ??  S     5:49PM   0:00.01 nginx: worker process  
nobody          38419   0.0  0.1  2610832   6068   ??  S     5:49PM   0:00.01 nginx: worker process  
nobody          **38418**   0.0  0.1  2610832   6128   ??  S     5:49PM   0:00.01 nginx: worker process 

2016/05/26 17:49:23 [error] 38420#0: [lua] init_worker.lua:2: ngx_worker_2_38420_4, context: init_worker_by_lua*
2016/05/26 17:49:23 [error] **38418**#0: [lua] init_worker.lua:2: ngx_worker_**0**_38418_4, context: init_worker_by_lua*
2016/05/26 17:49:23 [error] 38419#0: [lua] init_worker.lua:2: ngx_worker_1_38419_4, context: init_worker_by_lua*
2016/05/26 17:49:23 [error] 38421#0: [lua] init_worker.lua:2: ngx_worker_3_38421_4, context: init_worker_by_lua*
2016/05/26 17:49:23 [error] **38422**#0: [lua] init_worker.lua:2: ngx_worker_**0**_38422_4, context: init_worker_by_lua*

**Comment by agentzh** [comment]
@eminden In the latest OpenResty (1.9.15.1RC1), `ngx.worker.id()` now returns `nil` in those helper processes since they are not *workers* by definition anyway.

**Comment by eminden** [comment]
tested, ngx.worker.id() returning as in your explanation, thank you.
