### ISSUE TITLE
How to create thread, which is not block the request?

### ISSUE THREAD

**Issue by Romaboy** [openresty/lua-nginx-module#777]
There is ngx.thread.spawn command, that produce thread, which blocks a request. I mean, while some thread is running, user will not receive his answer. Maybe I use it in wrong way, or there is another way to not block request? Or only solution is standalone server for parallel tasks? It is for sending emails and just good thing.

**Comment by nithinmohan** [comment]
I believe this is what you need
https://github.com/openresty/lua-nginx-module#ngxtimerat

Disclaimer: Just started using openresty

**Comment by Romaboy** [comment]
Yes! Thank you

**Comment by Romaboy** [comment]
Also, it's not about openresty so I won't reopen issue, why if I try to create lua listening socket, it will freeze all server? Even with this great ngx.timer.at

ngx.timer.at 0, ->
	libsocket = require "socket"
	libunix = require "socket.unix"
	socket = assert(libunix())
	SOCKET="/tmp/socket"
	assert(socket\bind(SOCKET)) # after this line server not responding
	assert(socket\listen()) # or after this
	conn = assert(socket\accept())
	data=assert(conn\receive())
	print("Got line: " .. data)
	conn\send("echo: " .. data .. "\n")`

**Comment by agentzh** [comment]
The LuaSocke library is always blocking in the context of OpenResty. Do not use it! Use OpenResty's own cosockets instead.

**Comment by Romaboy** [comment]
But OpenResty's own cosockets can create listening server? I need exactly listening of unix domain. According to docs, they are only for connection.

**Comment by agentzh** [comment]
@Romaboy No listen/accept yet. Our developers are still working on these methods.

**Comment by agentzh** [comment]
@Romaboy You're welcome to contribute patches too :)

**Comment by mcarbonneaux** [comment]
is exactly what i'm searching !!! :) thank !
