### ISSUE TITLE
write different level of log in different file

### ISSUE THREAD

**Issue by FrancisHe** [openresty/lua-nginx-module#778]
We have mass of log to write, including error log, notice log, or some other level of log. Writing all level of log in single file is difficult to trouble shooting. Is there any way to write a specific level of log in a specific file?

**Comment by benbiti** [comment]
We want to write business logs, sth like yours.

we decide to use our customize logs with ngx.error and use another log processor for further processing.

**Comment by GhostZCH** [comment]
@FrancisHe. This config may write logs for different level to diiferent file.

        error_log  logs/error.log  error;
        error_log  logs/debug.log  debug;

**Comment by weakestan** [comment]
@FrancisHe U need a log server.
`error_log  syslog:server=ip debug;
`
depart logs by log server

**Comment by FrancisHe** [comment]
@GhostZCH 

```
error_log  logs/error.log  error;
error_log  logs/debug.log  debug;
```

`logs/error.log` will contain debug, info, notice, error level of logs, not only contain error logs.

**Comment by agentzh** [comment]
@FrancisHe This is not possible according to the current nginx core design. Also this has nothing to do with this ngx_lua module. I think you should ask instead on the official nginx mailing list instead :)

**Comment by FrancisHe** [comment]
@agentzh ok, thanks a lot.
