### ISSUE TITLE
error  compile  openresty-1.9.15.1rc2

### ISSUE THREAD

**Issue by guanhui07** [openresty/lua-nginx-module#781]
objs/addon/src/ngx_http_rds_json_output.o \
        objs/addon/src/ngx_http_rds_json_handler.o \
        objs/addon/src/ngx_http_rds_csv_filter_module.o \
        objs/addon/src/ngx_http_rds_csv_processor.o \
        objs/addon/src/ngx_http_rds_csv_util.o \
        objs/addon/src/ngx_http_rds_csv_output.o \
        objs/ngx_modules.o \
        -L/root/openresty-1.9.15.1rc2/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-E -ldl -lpthread -lcrypt -L/root/openresty-1.9.15.1rc2/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lpcre -lssl -lcrypto -ldl -lz \
        -Wl,-E
objs/addon/src/ngx_http_lua_regex.o: In function `ngx_http_lua_regex_free_study_data':
/root/openresty-1.9.15.1rc2/build/nginx-1.9.15/../ngx_lua-0.10.5/src/ngx_http_lua_regex.c:1959: undefined reference to `pcre_free_study'
objs/addon/src/ngx_http_lua_regex.o: In function `ngx_http_lua_ffi_destroy_regex':
/root/openresty-1.9.15.1rc2/build/nginx-1.9.15/../ngx_lua-0.10.5/src/ngx_http_lua_regex.c:2353: undefined reference to `pcre_free_study'
collect2: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/root/openresty-1.9.15.1rc2/build/nginx-1.9.15'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/root/openresty-1.9.15.1rc2/build/nginx-1.9.15'
make: *** [all] Error 2

**Comment by guanhui07** [comment]
uname -r
2.6.32-358.el6.x86_64

**Comment by guanhui07** [comment]
openresty/1.9.7.4 install success

**Comment by agentzh** [comment]
@guanhui07 Those link time errors are a clear indication that the versions of your PCRE headers and PCRE libraries in your system's default search paths do *not* match.

**Comment by lichao-hulu** [comment]
need to compile nginx together with pcre by adding options like "--with-pcre=/usr/local/src/pcre-8.34"

**Comment by dipenpatel235** [comment]
-L/root/openresty/openresty-1.11.2.2rc2/build/luajit-root/usr/local/nginx/luajit/lib -Wl,-rpath,/usr/local/nginx/luajit/lib -Wl,-E -ldl -lpthread -lcrypt -L/root/openresty/openresty-1.11.2.2rc2/build/luajit-root/usr/local/nginx/luajit/lib -lluajit-5.1 -lm -ldl -lpcre -lssl -lcrypto -ldl -lz \
        -Wl,-E
objs/addon/src/ngx_http_lua_regex.o: In function `ngx_http_lua_regex_free_study_data':
ngx_http_lua_regex.c:(.text+0x135): undefined reference to `pcre_free_study'
objs/addon/src/ngx_http_lua_regex.o: In function `ngx_http_lua_ffi_destroy_regex':
ngx_http_lua_regex.c:(.text+0x2dba): undefined reference to `pcre_free_study'
collect2: error: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory `/root/openresty/openresty-1.11.2.2rc2/build/nginx-1.11.2'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/root/openresty/openresty-1.11.2.2rc2/build/nginx-1.11.2'
gmake: *** [all] Error 2

**Comment by agentzh** [comment]
@dipenpatel235 Your error messages clearly indicate that your PCRE header files and PCRE library files in the default search paths do not match (that is, the PCRE header files belong to a more recent version of PCRE while the library files belong to an old version).

To save troubles like this, I suggest you just use OpenResty's official yum repositories for CentOS. Please see

http://openresty.org/en/linux-packages.html

**Comment by dipenpatel235** [comment]
[root@localhost ~]# ls /usr/include/pcre
pcrecpparg.h        pcrecpp.h           pcre.h              pcreposix.h         pcre_scanner.h      pcre_stringpiece.h

[root@localhost ~]# ls /usr/lib64/libpcre.so
/usr/lib64/libpcre.so

**Comment by detailyang** [comment]
Hello.

@dipenpatel235 do you sure you are using the recent version of pcre? Or you can make sure whether exists the function on system by `grep pcre_free_study /usr/include/pcre*`

Also if you are using the centos, maybe `rpm -qa |grep pcre` is better to you:)

**Comment by dipenpatel235** [comment]
you sure you are using the recent version of pcre? - Yes
because same version is also working in my another system and it is working fine there.

 rpm -qa |grep pcre
pcre-devel-7.8-7.el6.x86_64
pcre-7.8-7.el6.x86_64

**Comment by dipenpatel235** [comment]
finally i have fixed is using below step
cp /usr/lib64/libpcre.so /root/openresty-1.11.2.2/build/luajit-root/usr/local/openresty/luajit/lib/
gmake


Thanks

**Comment by agentzh** [comment]
@dipenpatel235 That was a dirty hack instead of a proper fix.

**Comment by agentzh** [comment]
@dipenpatel235 Why don't you just use OpenResty's official binary linux packages directly? Custom builds may have issues if you do not know what you are doing. Please see

https://openresty.org/en/linux-packages.html

**Comment by dipenpatel235** [comment]
Why don't you just use OpenResty's official binary linux packages directly?  - 
Because i want also need to add some another modules like real ip , gzip static,eval so  i am preferring compile from system

**Comment by agentzh** [comment]
@dipenpatel235 ngx_realip and ngx_gzip_static are already enabled in the official package:

https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec#L128

For ngx_eval, it's recommended to do that kind of stuff via ngx_lua module.
