### ISSUE TITLE
Read worker_connections in Lua

### ISSUE THREAD

**Issue by danihodovic** [openresty/lua-nginx-module#783]
I have been reading the OpenResty Redis docs and one of the guidelines state:

`
Ensure you configure the connection pool size properly in the set_keepalive . Basically if your NGINX handle n concurrent requests and your NGINX has m workers, then the connection pool size should be configured as n/m. For example, if your NGINX usually handles 1000 concurrent requests and you have 10 NGINX workers, then the connection pool size should be 100.
`
Taken from https://github.com/openresty/lua-resty-redis#check-list-for-issues.

I was wondering if this can be calculated dynamically in Lua. I know that the function `ngx.worker.count()` gives you the number of worker processes, but I haven't found any Lua function that can retrieve the `worker_connections` config. Is there such a variable?

**Comment by agentzh** [comment]
@danihodovic Your usage is wrong. The nginx documentation says clearly that you should use the number of concurrent requests your NGINX *usually* handles. But the `worker_connections` configuration is for the maximum number of concurrent connections allowed, which can be *WAY* larger than the usual concurrency level and lead to too large connection pool sizes following your wrong formulae.

**Comment by danihodovic** [comment]
I see. Thank you for clarifying that up!
