### ISSUE TITLE
ngx.re.match匹配乱码时抛异常

### ISSUE THREAD

**Issue by LuciferoO** [openresty/lua-nginx-module#785]
使用Lua编写Web防御规则的时候发现使用ngx.rematch匹配会出现异常
发起的请求：1.php?id=1%df%27%20and%20%271%27=%271

产生的异常信息：
 pcre_exec() failed: -10 on "1�' and '1'='1" using 

辛苦帮忙解答下面对此类问题需要在Lua中需要处理，才能使正则匹配不抛异常:)。

**Comment by agentzh** [comment]
Please do not use Chinese here. Thank you.
