### ISSUE TITLE
can't get environment variable defined in nginx.conf with init_by_lua

### ISSUE THREAD

**Issue by fanchangyong** [openresty/lua-nginx-module#788]
I define an environment variable in nginx.conf:
```nginx
env FOO=123;
```
and use it in lua:
```nginx
init_by_lua "print(os.getenv('FOO'))";
```
it prints `nil`

The environment variable is accessible with `access_by_lua`, but not accessible with `init_by_lua`.
And if I define the environment variable in the command line, it is accessible with `init_by_lua`,
```shell
#FOO=123 nginx -p .
```

**Comment by GhostZCH** [comment]
in my opinion, `ngx_http_lua_init_by_file` execute before `ngx_set_environment` witch called by `ngx_worker_process_init`. Try `init_worker_by_lua*`

**Comment by agentzh** [comment]
Right, `init_by_lua*` runs too early for those environment variables set by nginx via the `env` directive.
