### ISSUE TITLE
Why lua can't find the module?

### ISSUE THREAD

**Issue by TurnOffNOD** [openresty/lua-nginx-module#792]
Hi, I am using openresty. My project structure is:
nginx.conf:

```
user  nginx www-data;
worker_processes  2;

error_log  /var/log/nginx/error.log notice;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr     "Host:$host"    [$time_iso8601]'
                      '  "$request" $status $body_bytes_sent    "$http_user_agent"  $http_x_forwarded_for"'
                     ' "$http_referer"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        off;
    lua_code_cache off;
    keepalive_timeout  65;

    server {
            listen 80;
            server_name mysite.site.domain;

            root /srv/www/nginx/mysite/;
            index index.html index.htm;

            location /site1 {
                    try_files $uri $uri/ =404;

                    default_type text/html;
                    access_by_lua_file /srv/www/nginx/mysite/mysite.lua;
            }
    }
}
```

And the structure /srv/www/nginx/mysite is:

```
$ls -l /srv/www/nginx/mysite/
total 24
-rw-rw-r-- 1 nginx   www-data    537 Jun  3 22:45 50x.html
-rw-rw-r-- 1 nginx   www-data    361 Jun  3 22:46 m1.lua
-rw-rw-r-- 1 nginx   www-data    579 Jun  6 12:09 mysite.lua
```

m1.lua is the module,in mysite.lua, I required as follows:

```
local mymod = require "m1"
(other codes)
```

When I visit mysite.site.domain/site1, I get a 500 error.
In the error.log, it says:

> /srv/www/nginx/userapp/mysite.lua:1: in function </srv/www/nginx/mysite/mysite.lua:1>, client: xxx
> 
>  [error] 1173#0: *2 lua entry thread aborted: runtime error: //srv/www/nginx/mysite/mysite.lua:1:
>         no field package.preload['m1']
>         no file '/usr/share/nginx/lualib/m1.lua'
>         no file '/usr/share/nginx/lualib/m1/init.lua'
>         no file './m1.lua'
>         no file '/usr/share/nginx/luajit/share/luajit-2.1.0-beta1/m1.lua'
>         no file '/usr/local/share/lua/5.1/m1.lua'
>         no file '/usr/local/share/lua/5.1/m1/init.lua'
>         no file '/usr/share/nginx/luajit/share/lua/5.1/m1.lua'
>         no file '/usr/share/nginx/luajit/share/lua/5.1/m1/init.lua'
>         no file '/usr/share/nginx/lualib/m1.so'
>         no file './m1.so'
>         no file '/usr/local/lib/lua/5.1/m1.so'
>         no file '/usr/share/nginx/luajit/lib/lua/5.1/m1.so'
>         no file '/usr/local/lib/lua/5.1/loadall.so'

I am confused why there is "no file './m1.lua' " error. As ls -l shows, file m1.lua is right here beside file mysite.lua in the same directory.

**Comment by qlee001** [comment]
Set lua library path.
https://github.com/openresty/lua-nginx-module#lua_package_path

**Comment by agentzh** [comment]
@TurnOffNOD `.` means the *current working directory* used by your nginx server, instead of the same directory as the current running Lua script file as you assume.

**Comment by TurnOffNOD** [comment]
@agentzh Thanks. That solve my problem.
Perhaps it can have a better name. (Convert the relative path "." to another name.)

**Comment by agentzh** [comment]
@TurnOffNOD That error message is from the Lua VM directly. I don't see the reason to change `.` since its semantics is consistent across most operating systems.

**Comment by tourist-py** [comment]
@agentzh Which way  do you recommend/use to find lua files? absolute path or relative path.

**Comment by agentzh** [comment]
@tourist-py Just see the openresty-survey and openresty.org demo apps on GitHub for how I use paths in OpenResty apps :)

**Comment by tourist-py** [comment]
@agentzh ；Got it, use $prefix. thanks

**Comment by kwanhur** [comment]
@chenshun00 what's the lua_package_path config content and where the lua-resty-cookie module do you place it ?

**Comment by agentzh** [comment]
@chenshun00 Your nginx's user account should also have the `x` permission on all the directory entries in the file path. Otherwise it cannot resolve the file path itself. It's *NIX permission basics.

**Comment by chenshun00** [comment]
@kwanhur @agentzh  thinks , I have solved it because its parent directory does not have `X` permissions .

**Comment by auqf** [comment]
the mean of the "resty.redis " is refer the path "resty/redis.lua"
