### ISSUE TITLE
several issues found by clang static analyzer

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-nginx-module#793]
I compiled git master of lua-nginx-module with nginx-1.11.1, and used scan-build (which is clang static analyzer)

http://chipitsine.github.io/lua-nginx-1.11.1/

at least 3 issues looks serious:

http://chipitsine.github.io/lua-nginx-1.11.1/report-e25d29.html#EndPath
http://chipitsine.github.io/lua-nginx-1.11.1/report-3a226f.html#EndPath
http://chipitsine.github.io/lua-nginx-1.11.1/report-f21a47.html#EndPath

**Comment by agentzh** [comment]
@doujiang24 @cuiweixie I thought this was once investigated and was believed to be a false positive. Will you please confirm it again? Thanks!

**Comment by doujiang24** [comment]
Yes, I think they are false positive.

**Comment by cuiweixie** [comment]
I am agree with @doujiang24 . Actually, I get some thing familiar too.  @chipitsine , don't worry, I have check it many times.
