### ISSUE TITLE
Request Headers Ordering

### ISSUE THREAD

**Issue by NerdsvilleCEO** [openresty/lua-nginx-module#794]
When I use the following code in the filter_by_lua stage, the headers are not consistent in:
1.) Header order
2.) Header casing

CODE
========
local headers = ngx.req.get_headers()
for k,v in pairs(headers) do
  ngx.header["X-" .. k] = "TEST"
end

As you can see from the data below, it is converting some headers (excluding Host and User-Agent) to lowercase, and is sorting all of the headers (lowercase and uppercase) in alphabetical order

INPUT HEADERS:
===============
Host: HOST
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

OUTPUT
=========
X-Host: TEST
X-User-Agent: TEST
X-accept: TEST
X-accept-encoding: TEST
X-accept-language: TEST
X-cache-control: TEST
X-connection: TEST
X-cookie: TEST
X-pragma: TEST

**Comment by agentzh** [comment]
@NerdsvilleCEO `ngx.req.get_headers()` returns a hash table and why will you expect iterating through a hash table gives you a particular order?

**Comment by NerdsvilleCEO** [comment]
Understood, is there a way to maintain order and create case sensitivity for the header values

**Comment by NerdsvilleCEO** [comment]
For the header field names rather

**Comment by agentzh** [comment]
@NerdsvilleCEO See https://github.com/openresty/lua-nginx-module#ngxreqraw_header

We're also planning on the `ngx.req.get_header_list()` API which returns a list of header entries instead of a hash table indexed by header names. If you're interested in this API instead, please contribute a patch :)

**Comment by NerdsvilleCEO** [comment]
Awesome! Will take a look :D
