### ISSUE TITLE
find  a bug in ngx_http_lua_ssl_certby.c

### ISSUE THREAD

**Issue by cjhust** [openresty/lua-nginx-module#798]
function: ngx_http_lua_ssl_cert_by_lua
line:136
summary:

       ngx_http_lua_ssl_ctx_index = SSL_get_ex_new_index(0, NULL, NULL,
                                                          NULL, NULL);

        if (ngx_ssl_connection_index == -1) {      //error, should be ngx_http_lua_ssl_ctx_index 
            ngx_ssl_error(NGX_LOG_ALERT, cf->log, 0,
                          "lua: SSL_get_ex_new_index() failed");
            return NGX_CONF_ERROR;
        }

**Comment by agentzh** [comment]
@cjhust You mean you are always getting the error message "lua: SSL_get_ex_new_index() failed"? Usually it's just a sign of getting out of memory I guess.

What versions of the related software are you using? Including NGINX, ngx_lua (or just OpenResty), OpenSSL, and your operating system? We've never seen this ourselves.

**Comment by agentzh** [comment]
@cjhust Okay, never mind. I see your point now. It's indeed a typo due to copy&paste. I'll fix it soon. Thanks!

**Comment by agentzh** [comment]
@cjhust Fixed in git master. Thanks!

**Comment by cjhust** [comment]
I find this problem when I read lua_ssl_certby.c(I have a feature similar to it), my system nerver getting the error message "lua: SSL_get_ex_new_index()".

thank you for your reply.
