### ISSUE TITLE
Overwrite Nginx Default Proxy Behavior

### ISSUE THREAD

**Issue by NerdsvilleCEO** [openresty/lua-nginx-module#799]
Hello,
  I am trying to send headers to an upstream with the exact content and header ordering that the end user sends to the server. I have been able to do this with the exception of the Host header and the Connection header. It appears that it is Nginx default behavior when proxying to send Connection: close; and Host: [proxy IP]:[proxy port], is there any way to overwrite this with lua?

**Comment by agentzh** [comment]
@NerdsvilleCEO Please use the openresty-en mailing list for such general discussions. This place is preserved for bug reports and patch review. Thank you for your cooperation. Please see https://openresty.org/en/community.html for more details.

**Comment by NerdsvilleCEO** [comment]
Ok thanks
