### ISSUE TITLE
running nginx fails on luajit so after build

### ISSUE THREAD

**Issue by Industrial** [openresty/lua-nginx-module#8]
Hi.

$ export LUAJIT_LIB=/home/tom/Applications/LuaJIT-2.0.0.beta5/lib

$ export LUAJIT_INC=/home/tom/Applications/LuaJIT-2.0.0.beta5/include/luajit-2.0

$ ./configure --prefix=/home/tom/Applications/nginx-0.8.53 --add-module=/home/tom/Downloads/ngx_devel_kit --add-module=/home/tom/Downloads/lua-nginx-module

$ make -j

$ make install

$ /home/tom/Applications/nginx-0.8.53/sbin/nginx

nginx: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

$

**Comment by sinabs** [comment]
ln -s /usr/local/lib/libluajit-5.1.so.2 /lib64/libluajit-5.1.so.2
