### ISSUE TITLE
when I clear x-forwarded-for header, `ngx.var.http_x_forwareded_for` is cleared too, log is missing

### ISSUE THREAD

**Issue by chunpu** [openresty/lua-nginx-module#801]
I use subrequest capture to request, so I need to clear x-forwarded-for first when I request some server because I don't need this header, and `ngx.var.http_x_forwareded_for` is cleared too

after I used the capture, I will set x-forwarded-for back, but `ngx.var.http_x_forwareded_for` is still empty

so I can never see `$http_x_forwareded_for` in my access log

but we may expect that we can still print the `$http_x_forwareded_for` in access log

Thanks!

**Comment by agentzh** [comment]
@chunpu Seems like you have a typo in your variable name. It should be `ngx.var.http_x_forwarded_for` instead of `ngx.var.http_x_forwareded_for`.

**Comment by agentzh** [comment]
@chunpu I've tried the following minimal and standalone example on my side with the latest ngx_lua and it works for me:

```nginx
location = /main {
    content_by_lua_block {
        ngx.req.clear_header("x-forwarded-for")
        ngx.location.capture("/fake")
        ngx.req.set_header("X-Forwarded-For", "foo")
        ngx.say("X-Forwarded-For: ", ngx.var.http_x_forwarded_for)
    }
}

location = /fake {
    return 200 ok;
}
```

Accessing /main gives the expected result:

```console
$ curl localhost:8080/main
X-Forwarded-For: foo
```

**Comment by chunpu** [comment]
hi @agentzh 

I use your minimal example to test in my server

use `1.9.3.1` and return `X-Forwarded-For: nil` fail
use `1.9.15.1` and return `X-Forwarded-For: foo` passed

is this problem fixed after 1.9.3.1?

Thanks!

**Comment by agentzh** [comment]
@chunpu 1.9.3.1 is ancient and you should always use the latest version. Yes, there is a bug fix in the X-Forwarded-For header handling since 1.9.3.1. You can look up the change logs for more details:

http://openresty.org/en/changes.html

**Comment by chunpu** [comment]
Thanks，I will update OpenResty to latest~
