### ISSUE TITLE
Compilation fails if NGX_LUA_NO_FFI_API is enabled

### ISSUE THREAD

**Issue by jsopenrb** [openresty/lua-nginx-module#802]
objs/addon/src/ngx_http_lua_module.o: In function ngx_http_lua_create_main_conf:
ngx_http_lua_module.c: undefined reference to ngx_http_lua_sema_mm_init

Looks like `#ifndef NGX_LUA_NO_FFI_API` check is missing here:
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_module.c#L805

**Comment by agentzh** [comment]
@jsopenrb Just fixed in git master. Thanks for the report!

**Comment by membphis** [comment]
hello @jsopenrb , I'm yuansheng, a member of the OpenResty community. 

We want send you a little gift for your great job, can you tell me your email? then we can talk more detail.

waiting for your response.
