### ISSUE TITLE
why type lua_shared_dict is userdata?

### ISSUE THREAD

**Issue by AnonymMan** [openresty/lua-nginx-module#805]
local shared_data = ngx.shared.subtitle_lua_subhead_rule_cache_dict;
 ngx.log(ngx.ERR,"shared_data type is:"..type(shared_data))
The log print the type is userdata,why it is userdata in my different environment.Can someone knows this         problem?

**Comment by agentzh** [comment]
@AnonymMan Seems like you are using an old version of ngx_lua module (or OpenResty)?

**Comment by agentzh** [comment]
It is a Lua table now.

**Comment by AnonymMan** [comment]
@agentzh Thanks.
