### ISSUE TITLE
Why as long as the use of ""ngx.re" will be reported to the wrong?attempt to index field 're' (a nil value)

### ISSUE THREAD

**Issue by donghuichun** [openresty/lua-nginx-module#815]
2016/07/03 17:29:30 [error] 2736#0: *138 lua entry thread aborted: runtime error: /Users/hogesoft/lua/lottery0.1/index.lua:45: attempt to index field 're' (a nil value)

code:
local client_type, client_to, client_err = ngx.re.find(ngx.ctx._header['user-agent'], "iPhone", "ix")

http.lua
local ngx_re_match = ngx.re.match

Why as long as the use of ""ngx.re" will be reported to the wrong?

**Comment by donghuichun** [comment]
But another server is normal, is an environmental problem?

**Comment by agentzh** [comment]
@donghuichun Ensure you are using the latest version of OpenResty.

BTW, ensure you have provided the following details while reporting a problem:

* The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the ngx_lua module version,
and your operating system version.
* A minimal and standalone test case that others can easily run on their side and
reproduce the issue you are seeing.
