### ISSUE TITLE
balancer_by_lua ngx.log

### ISSUE THREAD

**Issue by splitice** [openresty/lua-nginx-module#816]
I noticed ngx.log does not appear to be outputting anything when called from the upstream context (balancer_by_lua). I'll be conducting some testing of my own later to try and see whats what.

 - Is ngx.log in the upstream context NYI (i understand balancer_by_lua is still experimental)?
 - Is there any patches required for this functionality in your openresty patch collection?
 - Are you aware of any changes in the recent nginx versions that I should look at for possible regressions?

I'll be conducting some more testing myself this week, but I figured I'd ask these questions now.

Versions:
Nginx Lua Module: v0.9.6 (I'll test latest master soon)
Lua Resty Core: latest master
Nginx: nginx/1.11.1

Code to replicate:
```
ngx.log(ngx.ERR, "test")
````

Expected: test in the logs

Actual: no log output, but balancer context continues without error

I also checked, ngx.log is functional when called from init_worker_by_lua.

**Comment by agentzh** [comment]
@splitice There is passing test cases using `print()` (which is equivalent to `ngx.log(ngx.INFO, ...)`) with `balancer_by_lua*` in the existing test suite. I've also added a test case using `ngx.log(ngx.ERR, ...)` in `balancer_by_lua*`. All the tests in `t/138-balancer.t` are passing with nginx 1.11.1 + lua-nginx-module git master HEAD (lua-resty-core is irrelevant here since it does not redefine `ngx.log` at all). See

https://github.com/openresty/lua-nginx-module/blob/master/t/138-balancer.t

**Comment by agentzh** [comment]
@splitice You definitely need to prepare a minimal example that I can reproduce the issue on my side.

**Comment by splitice** [comment]
Thanks for your review of the information.

I'll upgrade to latest master and build a more minimal test later this week. I'll update this then when I know more.

**Comment by splitice** [comment]
Thank you for your information. I updated my branch with the latest master and can confirm this issue does not present itself with the latest master. So its fixed some time between v0.9.6 and v0.10.5(HEAD).

All that was required was re-compilation with the new lua module.

**Comment by agentzh** [comment]
@splitice Phew. What a waste of time. Please ensure you are using the latest version of the component when you report an issue. This is stated in the issue template. Please read it more carefully the next time you create a new issue. Thank you very much for your cooperation.
