### ISSUE TITLE
Failing to load compiled lua byte code using lua_package_path

### ISSUE THREAD

**Issue by krugar100** [openresty/lua-nginx-module#818]
I am trying to compile [lua-resty-waf](https://github.com/p0pr0ck5/lua-resty-waf) to byte code using [LuaJIT-2.1.0-beta2](http://luajit.org/download/LuaJIT-2.1.0-beta2.tar.gz) using 

for f in $(find ./ -name '*.lua'); 
do 
    luajit-2.1.0-beta2 -b $f `dirname $f`/`basename $f .lua`.o
done

and liking this in the nginx template as 

lua_package_path '/usr/local/openresty/lualib/lua_resty_waf/?.o;;';
lua_package_cpath '/usr/local/openresty/lualib/lua_resty_waf/?.o;;';

(I am trying to load bytecode files using lua_package_path && lua_package_cpath, is it supported in the first place? )

This was the same procedure mentioned in [here](https://github.com/openresty/lua-nginx-module#lualuajit-bytecode-support)

But when i do `nginx -s reload` , I get
nginx: [error] init_by_lua_file error: error loading module 'waf' from file '/usr/local/openresty/lualib/lua_resty_resty/waf.o':
/usr/local/openresty/lualib/lua_resty_resty/waf.o:1: unexpected symbol near 'char(127)'

This occurs when I try to load waf using `require "waf" `.

**Comment by agentzh** [comment]
@krugar100 You should add the path to `lua_package_cpath` only, not `lua_package_path`.

**Comment by agentzh** [comment]
@krugar100 You're using `require "waf"` in your `init_by_lua*` handler, right? Please provide as much details as possible and do not make me guess ;)

**Comment by agentzh** [comment]
`lua_package_path` is for `require()` and bytecode files are supported, as documented in the documentation section you referenced:

> Loading bytecode files via the Lua primitives like require and dofile should always work as expected.

**Comment by krugar100** [comment]
@agentzh Giving just the lua_package_path '/usr/local/openresty/lualib/lua_resty_waf/?.o;;'; didn't work either, i get the same error.
Yes i am using require "waf", this is my code,
require "resty.core"
local lua_resty_waf = require "waf"

And it is similar to what is there [here](https://github.com/p0pr0ck5/lua-resty-waf#synopsis)

**Comment by agentzh** [comment]
@krugar100 What operating system and architecture are you in? What version of OpenResty are you using? (BTW, please read the issue template carefully upon creating a new issue).

**Comment by agentzh** [comment]
@krugar100 Also, please try a minimal Lua module file to test if it works. I'm not sure if there's any peculiarities with the `waf` Lua module you are using.

**Comment by agentzh** [comment]
@krugar100 Also ensure you compile the LuaJIT bytecode in the same system that you load the bytecode. Also, how did you build your OpenResty? Show me your `nginx -V` output.

**Comment by agentzh** [comment]
@krugar100 Details, details, details :)

**Comment by krugar100** [comment]
Here they are :) (I'll read issue template before posting next time :) )

nginx version: openresty/1.9.15.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.59 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.30 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.05 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.5 --add-module=../ngx_lua_upstream-0.05 --add-module=../headers-more-nginx-module-0.30 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --http-client-body-temp-path=/var/log/fenced/nginx/client_body_temp --http-proxy-temp-path=/var/log/fenced/nginx/proxy_temp --http-log-path=/var/log/fenced/nginx/access.log --error-log-path=/var/log/fenced/nginx/error.log --pid-path=/var/log/fenced/nginx/nginx.pid --lock-path=/var/log/fenced/nginx/nginx.lock --with-pcre-jit --with-ipv6 --with-http_ssl_module --without-http_ssi_module --without-http_userid_module --without-http_uwsgi_module --without-http_scgi_module

**Comment by agentzh** [comment]
64-bit of system?

**Comment by krugar100** [comment]
I have tried a simple lua module and it worked! But this isn't working. I tried making archive and then linking it as suggested [here](https://github.com/openresty/lua-nginx-module#statically-linking-pure-lua-modules), but had no luck!

**Comment by krugar100** [comment]
yup x86_64

**Comment by agentzh** [comment]
@krugar100 Use the `-bg` option to luajit instead of `-b` so that you can have debug symbols in your luajit bytecode. And then the error message in your nginx.conf can make sense.

**Comment by agentzh** [comment]
@krugar100 Okay, I see what's going on here. Your `lib/*.lua` files should be compiled into bytecode files in the same directory, i.e., under `lib/`. Otherwise `waf.lua` would fail to load those sub-modules.

**Comment by agentzh** [comment]
@krugar100 I've just tried on my Fedora Linux x86_64 with OpenResty 1.9.15.1 and it works for me.

I used the following bash script to compile the `.lua` module files in lua-resty-waf into bytecode files `.luac`:

```bash
#!/bin/bash

for f in `find . -name '*.lua'`; do
    /usr/local/openresty/luajit/bin/luajit -bg $f "`dirname $f`/`basename "$f" .lua`.luac"
done
```

And then in my `nginx.conf`, I have

```nginx
    init_by_lua_block {
        require "waf"
    }
```

Then starting nginx gives no errors in `logs/error.log`.

**Comment by agentzh** [comment]
@krugar100 BTW, do not use your own LuaJIT to compile the Lua files. Use the one shipped with the same OpenResty installation.

**Comment by krugar100** [comment]
@agentzh I have done the following ( basically using the same luajit compiler)

for f in $(find ./lua_resty_waf -name '*.lua'); 
do 
    /usr/local/openresty/luajit/bin/luajit -bg $f `dirname $f`/`basename $f .lua`.luac
done

And i get the following error, on doing nginx -t or nginx -s reload

nginx: [error] init_by_lua_file error: error loading module 'waf' from file '/usr/local/openresty/lualib/lua_resty_waf/waf.luac':
	/usr/local/openresty/lualib/lua_resty_waf/waf.luac: invalid ELF header
stack traceback:
	[C]: at 0x7f98ece69d60
	[C]: in function 'require'
	code/default_init.lua:6: in main chunk
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed


I have split up the  nginx conf and lua code is inserted from different file.
So I am loading the  default_init.lua as follows in nginx.conf

init_by_lua_file bytecode/default_init.bytecode;

This default_init has the following code 

-- use resty.core for performance improvement, see the status note above
require "resty.core"

-- require the base module
local lua_resty_waf = require "waf"
**and rest of the file has just the lua code

I have compiled this too with /usr/local/openresty/luajit/bin/luajit itself in this way,

for f in $(find code -name '*.lua'); 
do 
    /usr/local/openresty/luajit/bin/luajit -bg $f "bytecode/"`basename $f .lua`.bytecode
done
(I am compiling lua code in code directory and placing them in bytecode directory, which I am loading with init_by_lua_file in nginx conf file)

**Comment by krugar100** [comment]
@agentzh I have tested the compiling the template and integrating with nginx.conf separately without compiling lua_resty_waf code, (including .lua files itself) and it was working. So there shouldn't be an issue there.

**Comment by agentzh** [comment]
@krugar100 Please use proper markdown in your comments. Otherwise your code snippets are not readable. Alas.

**Comment by agentzh** [comment]
@krugar100 How did you build your OpenResty? What's the `./configure` command line? I hope you are not mixing with the stuff here:

https://github.com/openresty/lua-nginx-module/#statically-linking-pure-lua-modules

Because they are VERY different things.

**Comment by agentzh** [comment]
@krugar100 Also, ensure you are testing the minimal examples (as I've given above) instead of big ones.

**Comment by agentzh** [comment]
@krugar100 Just tried the following example on my side as well. Still no errors:

```nginx
    lua_package_path "/home/agentzh/git/lua-resty-waf/?.luac;;";
    init_by_lua_file /tmp/a.luac;
```

```lua
-- a.lua
require "resty.core"
local lua_resty_waf = require "waf"
```

And then compile this `a.lua`:

```bash
/usr/local/openresty/luajit/bin/luajit -bg a.lua /tmp/a.luac
```

BTW, your `invalid ELF header` error looks very wrong since well-formed LuaJIT bytecode files do not contain an ELF header. Ensure you are building your OpenResty without trying to linking any your own `.o` files which might be incorrectly generated.

**Comment by krugar100** [comment]
yeah I have updated my previous comment with proper markdown.

This is the command I am using to build the Openresty
```bash
./configure \
    --http-client-body-temp-path=/var/log/fenced/nginx/client_body_temp \
    --http-proxy-temp-path=/var/log/fenced/nginx/proxy_temp \
    --http-log-path=/var/log/fenced/nginx/access.log \
    --error-log-path=/var/log/fenced/nginx/error.log \
    --pid-path=/var/log/fenced/nginx/nginx.pid \
    --lock-path=/var/log/fenced/nginx/nginx.lock \
    --with-luajit \
    --with-pcre-jit \
    --with-ipv6 \
    --with-http_ssl_module \
    --without-http_ssi_module \
    --without-http_userid_module \
    --without-http_uwsgi_module \
    --without-http_scgi_module \
make 
make install
```

**Comment by agentzh** [comment]
@krugar100 Again, do not add the path of your `.luac` to the `lua_package_cpath` paths!

Try my tested configurations as-is (better use copy&paste) given above. Details matter.

**Comment by agentzh** [comment]
@krugar100 Only set your `lua_package_path` (oh yes, I've made a typo in one of my previous comment. Already fixed on the GitHub web UI).

**Comment by agentzh** [comment]
@krugar100 Otherwise LuaJIT is trying to load a C module instead of a Lua module (including LuaJIT bytecode module).

**Comment by agentzh** [comment]
@krugar100 And in that case, the ELF header is expected since that's part of the `.so` files.

**Comment by agentzh** [comment]
@krugar100 Just remove your `lua_package_cpath` directive from your `nginx.conf`.

**Comment by krugar100** [comment]
@agentzh  Yeah it is working! I was using docker containers and had to bring it down and up in between. I forgot to remove the ```lua_package_cpath```. Now it works like charm! Thanks! :)

**Comment by agentzh** [comment]
@krugar100 Glad it finally works :)

**Comment by agentzh** [comment]
@krugar100 Ah, better avoid using dockers for development.

**Comment by krugar100** [comment]
@agentzh Yeah lesson learned!! :)
