### ISSUE TITLE
NGX_HAVE_SHA1 doesn't exists since 1.11.2

### ISSUE THREAD

**Issue by manwe-pl** [openresty/lua-nginx-module#819]
Commit https://github.com/nginx/nginx/commit/c60b61a290960c1411d4da34d7f9265a43fd831b removed non-internal SHA1 implementations, removing also "NGX_HAVE_SHA1", thus disabling ngx.sha1_bin function in lua module.

**Comment by agentzh** [comment]
Just fixed in git master. Thank you!
