### ISSUE TITLE
Set headers in body_filter_by_lua*

### ISSUE THREAD

**Issue by adrianke** [openresty/lua-nginx-module#825]
When trying to set headers via `ngx.headers.HEADER` in `body_filter_by_lua*`, I get the following error:

`*311 attempt to set ngx.header.HEADER after sending out response headers while sending to client`

I need to set headers based on what's in the response. Is there a way to delay the first byte of the response until I've set my headers? Kind of like `lua_need_request_body`.

**Comment by agentzh** [comment]
@adrianke Nginx's output body filters always run *after* its output header filters, which means the response header has already been sent out. You'll need a time machine to change the sent-out response header which *may* already be on the wire. Please note that, nginx tries to output data as soon as possible to reduce memory footprint (as opposed to full-buffering).

**Comment by agentzh** [comment]
@adrianke If you need full buffering, then you shouldn't use the output filters in the first place since output filters are for the nonbuffered outputting mode which is the most optimal approach.

**Comment by ruslantalpa** [comment]
looking at this right now,
@agentzh if what you are saying here is true (and it is :))

then the docs are wrong/misleading

```
ngx.header.HEADER
syntax: ngx.header.HEADER = VALUE
syntax: value = ngx.header.HEADER
context: rewrite_by_lua*, access_by_lua*, content_by_lua*, header_filter_by_lua*, body_filter_by_lua*, log_by_lua*
```

notice it says it can be used in `body_filter_by_lua*`

so, absolutely no way to set a response header based on the body from the upstream (i am buffering the response body as you showed in some issue using `ngx.arg[1] = nil`)? 

Thank you
