### ISSUE TITLE
No HTTP reason-phrase is returned for 429 responses

### ISSUE THREAD

**Issue by danihodovic** [openresty/lua-nginx-module#828]
I'm using the following code to return a 429 and rate limit a request:

```
  ngx.status = 429
  ngx.say(jsonStr)
  ngx.exit(200)
```

This results in the following response when using curl:
```
$ curl -v localhost
...
< HTTP/1.1 429
...
```

The response status line is missing a Reason-Phrase. According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html:

> The first line of a Response message is the Status-Line, consisting of the protocol version followed by a numeric status code and its associated textual phrase, with each element separated by SP characters. No CR or LF is allowed except in the final CRLF sequence.

```
       Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```

Is it possible to set a Reason-Phrase for the status line using OpenResty? In this case I'd like to set the Reason-Phrase to `Too Many Requests`. The response should then be:

```
$ curl -v localhost
...
< HTTP/1.1 429 Too Many Requests
...
```

**Comment by agentzh** [comment]
@danihodovic Unfortunately this cannot be controlled from our ngx_lua module. You'll have to patch the nginx core for this since it's hard coded. See the `src/http/ngx_http_header_filter_module.c` file for more details. (I think you'd better ask on the nginx mailing list instead :))

**Comment by danihodovic** [comment]
Thanks for the quick response @agentzh!

I take it that this issue can't be fixed at all from an OpenResty standpoint as it originates from nginx core?

**Comment by agentzh** [comment]
@danihodovic Well, we could prepare a nginx core patch in OpenResty, but it's better to be upstreamed in nginx.

**Comment by danihodovic** [comment]
I'm an idiot. As I was patching together an example I realized using capitalized header names works.

```
ngx.header['X-My-Captialized-Header'] = 'bar'
```

```
$ curl -v localhost
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
...
< HTTP/1.1 429
...
< X-My-Captialized-Header: bar
...
```
