### ISSUE TITLE
*_by_lua_file full path on Windows doesn't work

### ISSUE THREAD

**Issue by Someguynamedpie** [openresty/lua-nginx-module#833]
I'm on Windows for rapid prototyping -- I'd like to use $document_root so I can easily move it around and just change that one var.
Unfortunately, it tries to load it as though it were a relative path, not the absolute path that it is, causing an error: "./C:/-snip-/init.lua"
Root is set to: "root C:/-snip-/"
The location block in question:
`location /srv {
	content_by_lua_file $document_root/init.lua;
}`
Updated: Turns out even giving the full path(which I guess isn't unexpected) doesn't work either and it tries to prepend the path with ./ presumably because it doesn't realize that driveletter:/ is an absolute path.

**Comment by agentzh** [comment]
@Someguynamedpie Right, `*_by_lua_file` only checks the leading `/` for absolute path recognition. It should get fixed for Windows's path format. Will you submit a patch for it? Many thanks!

**Comment by Someguynamedpie** [comment]
Sure, it'll be a bit since I'm pretty busy but I'll add it to my todo list.

**Comment by Someguynamedpie** [comment]
Is it alright if I use a WinAPI function( See https://msdn.microsoft.com/en-us/library/windows/desktop/bb773660(v=vs.85).aspx ) if on windows, or would you prefer a non-winapi implementation?

**Comment by agentzh** [comment]
@Someguynamedpie I'm fine with the WinAPI solution as long as

1. that part is guarded by Win32-specific C macro definition (so that other operating systems won't see it) and
2.  it compiles with MinGW :)

Many thanks!

**Comment by agentzh** [comment]
@Someguynamedpie `#if (NGX_WIN32)` should be enough I guess.

**Comment by agentzh** [comment]
@Someguynamedpie Sorry, seems like nginx core already does the hard work for us. We can just use `ngx_test_full_name` or even just `ngx_get_full_name` for the whole thing directly.

**Comment by Someguynamedpie** [comment]
Apologies for taking so long, been really busy with some stuff. If that'll work then that's great! Otherwise, I'll throw in the check.

**Comment by agentzh** [comment]
@Someguynamedpie Cool, thanks for taking care of this!

**Comment by Someguynamedpie** [comment]
Looking into that NGINX function, it doesn't consider UMC paths and anything else that Windows would consider a full path like the Win32 function would; however I don't have a full MinGW setup at the moment so it sounds like using the nginx method will suffice for now :sleeping:

**Comment by Someguynamedpie** [comment]
I'll work on using the Win32 function if on Windows; if my MinGW setup doesn't comply, I'll just swap it to use the NGINX core function.

**Comment by agentzh** [comment]
@Someguynamedpie I suggest you use the nginx core functions instead of calling Win32 APIs directly.

**Comment by Someguynamedpie** [comment]
Alright; it still doesn't consider everything Windows would consider a full path though, but if using the core functions is preferred I'll use them instead.

**Comment by agentzh** [comment]
@Someguynamedpie Well, if the core nginx functions are not enough, then I'd suggest you report that to the nginx-devel mailing list :) It's WAY better to fix the core in one place instead of hacking around that in every 3rd-party nginx modules :)

**Comment by Someguynamedpie** [comment]
Perfectly fair point, didn't even think about that. Alright then its settled, use nginx api, report suggestion to their mailinglist haha. Expect a pull request tonight.

**Comment by agentzh** [comment]
@Someguynamedpie Awesome. Thanks!
