### ISSUE TITLE
can't set cookie with data from subrequest body

### ISSUE THREAD

**Issue by vkonnyu** [openresty/lua-nginx-module#834]
after reading subrequest's response data, can't set a cookie with value from the reponse 

    local cookie, err = ck:new()
    local res = ngx.location.capture(
         "/select",
         { method = ngx.HTTP_POST , body = bdy } 
    )
    local body_table = cjson.decode(res.body)
    local ok, err = cookie:set({
    key = "tid",
    value = body_table[1]["id"]
    })

*Setting a cookie works before issuing a subrequest

**Comment by agentzh** [comment]
What is the `ck` thing in your example? Your example is definitely incomplete and I'm not sure what 3rd-party Lua library you are using here to set the cookie thing.

**Comment by agentzh** [comment]
@vkonnyu Please read the issue template carefully. To quote,

> A minimal and standalone test case that others can easily run on their side and
reproduce the issue you are seeing.

**Comment by vkonnyu** [comment]
I'm sorry, you are right and also it seems you solved my problem with your comment. While trying to create a minimal test by removing the ngx.say() calls it started to work. Still, I don't understand why it fails when I uncomment any of the ngx.say() lines (ck is the resty-cookie library https://github.com/cloudflare/lua-resty-cookie#synopsis there is a HTTP POST with email and password args )

    location /login {
    content_by_lua '
    --mandatory
    ngx.req.read_body()
    local cookie, err = ck:new()
    --get post params
    local email = ngx.req.get_post_args()["email"]
    local password = ngx.req.get_post_args()["password"]
    --hash pw
    local sha512 = resty_sha512:new()
    sha512:update(password)
    local digest = sha512:final()
    local pw = str.to_hex(digest)
    --prepare body for subroutine
    local bdy = "email=" .. email .. "&password=" .. pw
    --ngx.say(bdy)
    res = ngx.location.capture(
         "/select",
         { method = ngx.HTTP_POST , body = bdy }
    )
    --  ngx.say(res.body)
    local body_table = cjson.decode(res.body)
    ok, err = cookie:set({
    key = "tid",
    value = body_table[1]["id"]
    })
    ';
    }

    location /select {
      postgres_pass database;
      rds_json on;
      set_form_input      $password;
      set_form_input      $email;
      set_unescape_uri    $psw $password;
      set_unescape_uri    $eml $email;
      postgres_escape     $psw;
      postgres_escape     $eml;
      postgres_query    POST "SELECT * FROM users WHERE email = $eml AND pw = $psw";
    }

**Comment by agentzh** [comment]
@vkonnyu Setting a cookie is adding a response header. When you call `ngx.say()` to generate some part of the response body, the response header has to be constructed and sent out. So there is no way that you can add a response header entry after sending out part of the response body data (you would need a time machine for that).
