### ISSUE TITLE
ngx.var never gets set

### ISSUE THREAD

**Issue by gatisdukurs** [openresty/lua-nginx-module#838]
Hi, 

Im trying to do this:

```
location /test.txt {
    set $foo 'foo';
    
    access_by_lua '
        ngx.var.foo = "bar";
    ';

     return 200 $foo;
}
```

and nginx returns foo, instead of bar. Am i missing something?

I want to query redis db using lua and then set file name and use it with try_files, something like this.

```
location ~* /image/(\d+)\.jpg {
	    root /some/path;
	    set $some_file '';

	    access_by_lua '
	    	local redis = require "redis";
		local red   = redis:new()

		local ok, err = red:connect("127.0.0.1", 6379)
                if not ok then
                    ngx.say("failed to connect: ", err)
                    return
                end

		local res, err = red:get($1)
                if not res then
                    ngx.say("Error: ", err)
                    return
                end

		ngx.var.some_file = res
 	    ';
           
            try_files $some_file $uri/ @404;
	}
```
But it does not work, if i return 200 $some_file its empty.

**Comment by agentzh** [comment]
You misunderstand the running order of different Nginx directives. They do not usually run in the same order as they appear in nginx.conf. For example, access_by_lua* always run after return while content_by_lua* always run after try_files. This is because they belong to different request processing phases of nginx.

**Comment by agentzh** [comment]
When in doubt, you can always enable the debugging logs of nginx

**Comment by agentzh** [comment]
Also your Lua code contains a syntax error. $1 should be ngx.var.1, I guess?

**Comment by gatisdukurs** [comment]
So, in theory is it possible to query db with lua and pass return it to try files? Or should i look for other non nginx solutions? Basically what i want to do is serve staric files, but these files can change from time to time, but i want the same filename, also this way multiple urls could point to the same physical file. I could do it on every request with php or python etc. But nginx level solution would be bettet.

**Comment by gatisdukurs** [comment]
Ok, looks like i could do it inside lua file all the processing and logic. Something similar to this:

http://leafo.net/posts/creating_an_image_server.html

Thanks, i will try out and see how it goes.
