### ISSUE TITLE
log_by_lua - not called in all requests

### ISSUE THREAD

**Issue by Fr3DBr** [openresty/lua-nginx-module#841]
Hi, guys.

When is the log_by_lua method called ?

Only after a request is parsed by the upstream server ?

Because right now, static file requests served by nginx cache aren't triggering it, and I wanted to know if this is the expected behavior or not, thanks. :)

**Comment by detailyang** [comment]
hello
The picture as the following will help you understand:)
![nginx-phase](https://cloud.githubusercontent.com/assets/3370345/17831759/96922caa-6724-11e6-9eaf-356380ab2f08.png)


static file (upstream also) works on the nginx content phase. Anyway, the log_by_lua should be call after the content phase.

Or can you show us the how to reproduce what you have said

**Comment by Fr3DBr** [comment]
I've just added log_by_lua in server section, instead of inside a location and set the number of workers to 2, then any request served by proxy_pass with nginx cache enabled is not triggering it.

**Comment by Fr3DBr** [comment]
I've added a lua file write I/O to write a log line, every time the method is called, but unless there is a request being parsed by the upstream it is not called. (At least on my end).

**Comment by detailyang** [comment]
can you paste your nginx configuration sample to here. Thanks!

**Comment by Fr3DBr** [comment]
This is in production, so I don't have a simple sample. But I've told you everything that is done in this scenario. I'm using an old version of openresty tho: 1.9.3.1 so not sure if this was a bug or not.

**Comment by Fr3DBr** [comment]
Ok, I've found the problem, in fact log_by_lua is being called all the time, the problem is that I'm trying to access a few variables and sometimes it seems the Lua code will not be run, or will be interrupted by LuaJIT at a certain point, these are the variables:

        local rs_time_up = tonumber(ngx.var.upstream_response_time)
        local rs_time    = tonumber(ngx.var.request_time)
        local rs_bs      = tonumber(ngx.var.bytes_sent)
        local r_ac       = tonumber(ngx.var.connections_active)
        r_time_sec_up    = r_time_sec_up + rs_time_up
        r_time_sec       = r_time_sec + rs_time
        r_bs_sec         = r_bs_sec + rs_bs
        r_ac_sec         = r_ac_sec + r_ac

Is there a way to avoid this from happening ? Like a way to test if I can access or not these variables and let the code run always ?!

**Comment by Fr3DBr** [comment]
In fact the issue is with this variable: ngx.var.upstream_response_time it is not available for static requests, causing the lua code to stop being parsed/run, is there a way to check if this variable can be used or not and keep the code running ?

**Comment by detailyang** [comment]
just check the variable not be nil like

````lua
ngx.var.upstream_response_time ~= nil
````

**Comment by Fr3DBr** [comment]
Ok, problem fixed, sorry for the headache really. :) :+1:
