### ISSUE TITLE
can't print the response header Set-Cookie in log

### ISSUE THREAD

**Issue by tjliupeng** [openresty/lua-nginx-module#845]
Hi,

I try to print the response header Set-Cookie to log by:

header_filter_by_lua_block {
            ngx.log(ngx.WARN, "Set-Cookie %s", ngx.resp.get_headers()['Set-Cookie'] or "None")
        }

But I get nothing in access.log or error.log.

Thanks

**Comment by detailyang** [comment]
check the [docs](http://nginx.org/en/docs/ngx_core_module.html#error_log)
````
Syntax:	error_log file [level];
Default:	
error_log logs/error.log error;
Context:	main, http, mail, stream, server, location
````
 level is error at default, your are using ngx.WARN to logging so it will be ignored. you can use ngx.ERR or set error_log level to warn

**Comment by tjliupeng** [comment]
Thanks. I change to ngx.ERR and something is printed in error.log. But it fail to get the Set-Cookie header as follow. If I change 

2016/08/23 14:05:58 [error] 22020#22020: *1 failed to run header_filter_by_lua*: header_filter_by_lua:2: bad argument #2 to 'log' (expected table to have __tostring metamethod)
stack traceback:
        [C]: in function 'log'
        header_filter_by_lua:2: in function <header_filter_by_lua:1> while reading response header from upstream, client: 15.107.4.15, server: 16.165.217.31, request: "POST /SM/ui HTTP/1.1", upstream: "http://15.107.4.15:13080/SM/ui", host: "16.165.217.31"
2016/08/23 14:05:58 [error] 22020#22020: *3 failed to run header_filter_by_lua*: header_filter_by_lua:2: bad argument #2 to 'log' (expected table to have __tostring metamethod)
stack traceback:
        [C]: in function 'log'
        header_filter_by_lua:2: in function <header_filter_by_lua:1> while reading response header from upstream, client: 15.107.4.15, server: 16.165.217.31, request: "POST /SM/ui HTTP/1.1", upstream: "http://15.107.4.15:13081/SM/ui", host: "16.165.217.31"

**Comment by detailyang** [comment]
the error as the following:
````bash
header_filter_by_lua:2: bad argument #2 to 'log' (expected table to have __tostring metamethod)
````
it means your `ngx.resp.get_headers()['Set-Cookie']`  argument is table . you cannot log table directly unless you have __tostring metamethod.

I guess you upstream return more than set-cookie header. you can check this [docs](https://github.com/openresty/lua-nginx-module#ngxreqget_headers)  carefully

**Comment by tjliupeng** [comment]
@detailyang , you are right. Thanks.
