### ISSUE TITLE
"no request object found" is thrown in init_by_lua_block

### ISSUE THREAD

**Issue by tjliupeng** [openresty/lua-nginx-module#847]
I run the master branch for nginx 1.11.3. And I try to print the upstream serves to log in init_by_lua_block, "no request object found" is thrown when starts nginx. The lua block is as follow :

```
init_by_lua_block {
        require "resty.core"
        local upstream = require "ngx.upstream"
        local get_servers = upstream.get_servers
        collectgarbage("collect")  -- just to collect any garbage
        local servers, err = get_servers("sm")
        if not servers then
            ngx.log(ngx.ERR, "No upstream servers!")
        else
            for _, srv in ipairs(servers) do
                local first = true
                for k, v in pairs(srv) do
                    if first then
                        first = false
                        ngx.print("    ")
                    else
                        ngx.print(", ")
                    end
                    if type(v) == "table" then
                        ngx.print(k, " = {", concat(v, ", "), "}")
                    else
                        ngx.print(k, " = ", v)
                    end
                end
                ngx.print("\n")
            end
        end
    }
```

Thanks

**Comment by agentzh** [comment]
@tjliupeng `ngx.print` is disabled in the context of `init_by_lua*` since in that context no client request exists yet. Read the corresponding documentation more carefully please.

**Comment by agentzh** [comment]
@tjliupeng Since you are very green, I suggest you join the openresty-en mailing list to ask for such things instead of filing many tickets here. And please read the manual carefully before trying things out to avoid wasting both your time and our time. Thank you. The documentation has been there for a reason ;)
