### ISSUE TITLE
both ngx.time ngx.now will not update in non-yielding case ?

### ISSUE THREAD

**Issue by mike07026** [openresty/lua-nginx-module#857]
In non-yielding case, i mean a light-thread took a time doing something without yield, 
ngx.time and ngx.time will behave wrong.For example below,  it takes about 5s on my computer, but output wrong time measurement.

**I notice that openresty provides ngx.update_time, so is this a default behavior by design ?**

Environment:
Ubuntu 16.04 64bit
openresty/1.9.15.1
openresty/1.11.2.1

```
local cjson = require "cjson.safe"

local function test()

    local t = {a = 10, b = 20, c = 30, d = 40, e = 50, f = 60}
    local r = cjson.decode(cjson.encode(t))
    return r

end

local t1_ostime = os.time()
local t1_ngxtime = ngx.time()
local t1_ngxnow = ngx.now()

for i = 1, 1000 * 1000 do
    -- do non-yielding stuff
    test()
end

-- we can workaround with ngx.sleep
--ngx.sleep(0.001)

local t2_ostime = os.time()
local t2_ngxtime = ngx.time()
local t2_ngxnow = ngx.now()

ngx.say("os.time elapsed : ", t2_ostime - t1_ostime)
ngx.say("ngx.time elapsed : ", t2_ngxtime - t1_ngxtime)
ngx.say("os.now elapsed : ", t2_ngxnow - t1_ngxnow)
```

Incorrect Output:
```
os.time elapsed : 5
ngx.time elapsed : 0
os.now elapsed : 0
```

Uncomment ngx.sleep(0.001), Output
```
os.time elapsed : 5
ngx.time elapsed : 5
os.now elapsed : 4.7699999809265
```

**Comment by agentzh** [comment]
@mike07026 `ngx.time` uses nginx core's cached time which usually gets updated upon the entry point of the nginx event loop. This is an optimization by saving syscalls. For timing purposes, you should always call `ngx.update_time` itself. Well, it's documented.

**Comment by NicoAdrian** [comment]
@agentzh Is the value ngx.time() rounded to the nearest second or updated once the next second is reached ?
