### ISSUE TITLE
How can change the “REQUEST_URI” variable in openresty with lua

### ISSUE THREAD

**Issue by xxoxx** [openresty/lua-nginx-module#858]
My environment : openresty + php5.3

Test code with LUA:

    ngx.req.set_uri_args("a=3&b=123")

And the php code test.php:

    <?php
    echo $_SERVER['QUERY_STRING']."<br>";
    echo $_SERVER['REQUEST_URI'];

I send the request with "http://127.0.0.1/test.php?id=one"

The result:

    a=3&b=123
    /test.php?id=one

Why the REQUEST_URI did not changed.

**Comment by agentzh** [comment]
@xxoxx I guess you map the nginx built-in variable `$request_uri` to `REQUEST_URI` in your `nginx.conf`. That is, you should have something like below in your `nginx.conf` (or files included by `nginx.conf`, like `fastcgi_params`):

```
fastcgi_param  REQUEST_URI        $request_uri;
```

The `$request_uri` variable is the original URI sent from the HTTP client by definition. See the official nginx documentation for this variable:

http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_uri

To get what you want, I think you should replace that line with the following:

```
fastcgi_param  REQUEST_URI        "$uri?$args";
```

**Comment by xxoxx** [comment]
@agentzh  Thanks,  But there has a problem  that  the "REQUEST_URI" variable can't be change.
My nginx conf:

    fastcgi_param  REQUEST_URI        "$uri?$args"; 
    fastcgi_param  REQUEST_URIA        "$uri?$args";

My test.php:

    <?php
    echo $_SERVER['QUERY_STRING']."<br>";
    echo $_SERVER['REQUEST_URI']."<br>";
    echo $_SERVER['REQUEST_URIA'];

I send the request "http://172.17.0.2/test.php?id=one"  
result:

    a=3&b=123
    /test.php?id=one
    /test.php?a=3&b=123

the "REQUEST_URIA" variable result is i want
But the "REQUEST_URI"  did not changed.

**Comment by xxoxx** [comment]
@agentzh  There is no problem,  I find the reason is that 

    include        fastcgi.conf;

and in the fastcgi.conf

    fastcgi_param  REQUEST_URI        $request_uri;

Thanks a lot

**Comment by bungle** [comment]
@xxoxx, @agentzh,

One question though (I didn't test this), but is `ngx.req.set_uri_args` compatible with `$is_args`, so that you can request page without uri args, but this works then too:

```nginx
fastcgi_param  REQUEST_URI        "$uri$is_args$args";
```

**Comment by agentzh** [comment]
@bungle Ah, I was not aware of the `$is_args` variable. This is even better. Thanks!
