### ISSUE TITLE
当post提交数据过长时，ngx.log写日志时，信息只能写部分

### ISSUE THREAD

**Issue by zou2062** [openresty/lua-nginx-module#86]
httpluamodule version:  0.4.1
nginx version: nginx/1.1.3
nginx: configure arguments: --prefix=/path/nginx --add-module=/path/addon/memc-nginx-module/ --add-module=/path/addon/ngx_http_upstream_keepalive/ --add-module=/path/addon/evanmiller-nginx_upstream_hash/ --add-module=/path/addon/ngx_devel_kit/ --add-module=/path/addon/lua-nginx-module/

**Comment by lrliang** [comment]
ngx.log()的大小限制现在已经修改为4k了，但是我需要答应更大的日志，有没有什么办法将这个值改到8k呢？

**Comment by agentzh** [comment]
@lrliang You'll have to edit the nginx core's source code for it.
