### ISSUE TITLE
tcp connect fails with nil as final option

### ISSUE THREAD

**Issue by Tieske** [openresty/lua-nginx-module#860]
This code;

```lua
local function myConnect(sock, host, port, opts)
  return sock:connect(host, port, opts)   --> args = 3, `opts = nil`
end

local ok, err = myConnect(myTcpSocket, "www.google.com", 80)  --> `opts` omitted
```

Will always fail. The internal implementation checks the number of arguments, but not whether it is `nil`. In case of `nil` it falls through and sets the `port` to the default 0 instead of the provided one.

So the code above will effectively try to connect to `www.google.com:0` instead of `www.google.com:80`.

current master still has the issue.

[This line](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_socket_tcp.c#L428) should be updated to something like this (untested and very rusty on my c code);
```c
n = lua_gettop(L);
while ( n>0 && lua_type(L, n) == LUA_TNIL) { --n; }
```

**Comment by agentzh** [comment]
@Tieske Thanks for the report and test case! We'll look into this. I don't quite agree with your patch though :)

@doujiang24 Will you have a look at this? ;)

**Comment by doujiang24** [comment]
@Tieske I opened a PR, will you take a look at it please?
https://github.com/openresty/lua-nginx-module/pull/862

**Comment by Tieske** [comment]
on first glance the solution seems to work, but missing a testcase for the actual issue, eg. arguments; string, number, nil

as a more general comment; common Lua idiom is to ignore excess parameters, where openresty functions tend to throw an error. Maybe a consideration to drop those checks in the future?

> I don't quite agree with your patch though :)

Like I mentioned; rusty on my c, so I'm not even disappointed 😄

**Comment by doujiang24** [comment]
@Tieske Sorry for the mistake, I have correct the test case, thanks :)

**Comment by Tieske** [comment]
@doujiang24 looks good to me!
