### ISSUE TITLE
the new shdict methods such as rpush can not be used

### ISSUE THREAD

**Issue by shixinke** [openresty/lua-nginx-module#864]
the new shdict methods such as ngx.shared.DICT.rpush can not be used in version 1.11.2.1。
example:
`local dict = ngx.shared.common_dict`
`dict:rpush('lists', 2)`

the error:
attempt to call method 'rpush' (a nil value)

**Comment by moonbingbing** [comment]
`rpush`  is works for me. what's your OS？and please check your running
OpenResty's version again.

2016-09-05 14:36 GMT+08:00 诗心客 <notifications@github.com>:

**Comment by shixinke** [comment]
还是说中文吧，英文不过关。
我在官方下载的1.11.2.1的版本。下载解压后可以看到c源码包中已经有rpush相关函数，但是在openresty-1.11.2.1/bundle/lua-resty-core-0.1.8/lib/resty/core/shdict.lua中还没有加入相关的接口实现函数，不知道是不是这个原因。

**Comment by agentzh** [comment]
@shixinke If you really want to use Chinese, please post to the openresty (Chinese) mailing list instead. Please see

http://openresty.org/en/community.html

This place is considered English only.

Regarding your question, no, when lua-resty-core does not implement some `ngx.*` implementation, you will just use ngx_lua's default implementation.

**Comment by thibaultcha** [comment]
Considering this answered (ensure lua-resty-core is in use, or switch to a modern OpenResty version that loads it by default). Closing the thread.
