### ISSUE TITLE
libluajit-5.1.so.2()(64bit) is needed by nginx-1.11.3-1.el6.ngx.x86_64

### ISSUE THREAD

**Issue by atomyuk** [openresty/lua-nginx-module#865]
Hi all.

I am trying to install nginx builded(via rpmbuild) with lua and luajit support, and getting error 
libluajit-5.1.so.2()(64bit) is needed by nginx-1.11.3-1.el6.ngx.x86_64.
libluajit-5.1.so.2 is present in /usr/lib and /usr/lib64 but during install it some how doesn't visible.
Maybe during build of nginx package i can point installed where to find this lib?

**Comment by agentzh** [comment]
@atomyuk Please use the official OpenResty rpm packages and repositories:

http://openresty.org/en/linux-packages.html

http://openresty.org/en/rpm-packages.html
