### ISSUE TITLE
ssl_session_store_by_lua* cause core dump

### ISSUE THREAD

**Issue by nomyself** [openresty/lua-nginx-module#869]
Hi.

ssl_session_store_by_lua\* cause core dump when enabled ssl_session_store_by_lua\* on part of vhosts.
## Environment

> openresty-1.11.2.1
> openresty-openssl-1.0.2h
> openresty-pcre-8.39
> nginx_lua v0.10.6
## Minimal standalone test case

<pre><code>
http {
    access_log  off;
    server_names_hash_bucket_size 128;
    lua_package_path '/usr/local/openresty/lualib/?.lua;;';

```
server {
    listen 80;
    listen 443 ssl;
    server_name abc.example.com;
    ssl_certificate /etc/nginx/HTTPS/example.com.crt;
    ssl_certificate_key /etc/nginx/HTTPS/example.com.key;

    ssl_session_store_by_lua_block {
            local ssl_sess = require "resty.ngx.ssl.session"

            local sess_id, err = ssl_sess.get_session_id()
            ngx.log(ngx.ERR, "session ID: ", sess_id)
            if not sess_id then
                    ngx.log(ngx.ERR, "failed to get session ID: ", err)
                    -- just give up
                    return
            end
    }

    location / {
        return 200 "abc\n";
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name 123.example.com;
    ssl_certificate /etc/nginx/HTTPS/example.com.crt;
    ssl_certificate_key /etc/nginx/HTTPS/example.com.key;

    location / {
        return 200 "123\n";
    }
}
```

}
</pre></code>
## Test case
1. abc.example.com is ok
   `curl https://abc.example.com
   abc`
2. nginx worker crash
   `curl https://123.example.com
   curl: (56) SSLRead() return error -9806`
## Nginx errlog

> 2016/09/14 13:39:32 [notice] 30097#30097: signal 17 (SIGCHLD) received
> 2016/09/14 13:39:32 [alert] 30097#30097: worker process 30100 exited on signal 11 (core >dumped)
> 2016/09/14 13:39:32 [notice] 30097#30097: start worker process 30101
## gdb backtrace

<pre><code>(gdb) bt
# 0  0x0000000000000000 in ?? ()
# 1  0x00000000004fd04f in ngx_http_lua_ssl_sess_store_handler (ssl_conn=<value optimized out>, sess=<value optimized out>)

```
at ../ngx_lua-0.10.6/src/ngx_http_lua_ssl_session_storeby.c:272
```
# 2  0x00007f9211ff1232 in ssl_update_cache (s=0x7f920cb6e010, mode=2) at ssl_lib.c:2643
# 3  0x00007f9211fcddd9 in ssl3_accept (s=0x7f920cb6e010) at s3_srvr.c:850
# 4  0x0000000000447f7f in ngx_ssl_handshake (c=0x7f920bfc62e0) at src/event/ngx_event_openssl.c:1191
# 5  0x0000000000448162 in ngx_ssl_handshake_handler (ev=<value optimized out>) at src/event/ngx_event_openssl.c:1367
# 6  0x0000000000443945 in ngx_epoll_process_events (cycle=<value optimized out>, timer=<value optimized out>, flags=<value optimized out>)

```
at src/event/modules/ngx_epoll_module.c:900
```
# 7  0x000000000043ac45 in ngx_process_events_and_timers (cycle=0x7f921330fbd0) at src/event/ngx_event.c:242
# 8  0x00000000004417b8 in ngx_worker_process_cycle (cycle=0x7f921330fbd0, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:753
# 9  0x000000000043fdf7 in ngx_spawn_process (cycle=0x7f921330fbd0, proc=0x441780 <ngx_worker_process_cycle>, data=0x0, name=0x5119f5 "worker process", respawn=-3)

```
at src/os/unix/ngx_process.c:198
```
# 10 0x0000000000440cbc in ngx_start_worker_processes (cycle=0x7f921330fbd0, n=1, type=-3) at src/os/unix/ngx_process_cycle.c:358
# 11 0x0000000000441e44 in ngx_master_process_cycle (cycle=0x7f921330fbd0) at src/os/unix/ngx_process_cycle.c:130
# 12 0x000000000041d5bf in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:367

</pre></code>

**Comment by agentzh** [comment]
Thanks for the report! We'll look into this ASAP.

**Comment by agentzh** [comment]
@nomyself BTW, you should edit your posts according to the markdown notation, otherwise it's not readable at all (see above youself ;))

**Comment by cjhust** [comment]
this problem we met too, the reason is the no-default server use the default server's ctx.

the resolve way is add the same instruction to the all servers.


https://trac.nginx.org/nginx/ticket/1006#no3
https://github.com/openssl/openssl/issues/1271

**Comment by everpcpc** [comment]
Maybe better adding the `ssl_session_*_by_lua` to http context rather than server context?

**Comment by cjhust** [comment]
yes, I think so

**Comment by agentzh** [comment]
Yes, we're considering limiting the `ssl_session_*_by_lua*` directives to the `http {}` scope only.

**Comment by agentzh** [comment]
Please let us know if putting your `ssl_session_*_by_lua*` directives to the `http {}` scope can solve all your issues. Thanks!

**Comment by cjhust** [comment]
although this way may resolve the problem, but I think the best way is to add a patch to openssl.
the current sequence is:
(1)s->session_ctx->get_session_cb (s3_srvr.c:1045) ->nginx default server a.com
(2)ngx_http_ssl_servername (s3_srvr.c:1263)
(3)s->cert->cert_cb (s3_srvr.c:1427) ->b.com server
(4)s->session_ctx->new_session_cb (ssl_lib.c:2644) ->a.com server(default server)

the expect sequence is:
(1)ngx_http_ssl_servername (s3_srvr.c:1263)
(2)s->session_ctx->get_session_cb (s3_srvr.c:1045) 
(3)s->cert->cert_cb (s3_srvr.c:1427) r
(4)s->session_ctx->new_session_cb (ssl_lib.c:2644)


openssl wish me give a patch, I've tried, but openssl's code is so hard to understand.

**Comment by agentzh** [comment]
@cjhust SSL session resumption is irrelevant with virtual server dispatch, so it's natural for it to happen before server name dispatch. Also patching OpenSSL just for this is a horrible idea :)

**Comment by everpcpc** [comment]
@agentzh Besides, if I have a server only listening port 80, adding the `ssl_session_*_by_lua*` directives to `http {}` scope would cause nginx return error `nginx: [emerg] no ssl configured for the server` in config test.

**Comment by agentzh** [comment]
@everpcpc Your issue (and also other issues in this thread) should have already been fixed in the latest master branch. Please try it out.
