### ISSUE TITLE
Disabling log_by_lua_file inside a location

### ISSUE THREAD

**Issue by tarunlalwani** [openresty/lua-nginx-module#871]
I have a nginx config where we use `log_by_lua_file` at the http level, so each server defined gets logged.

Now inside one of the server for a location statement i want to override/disable the inherited `log_by_lua_file`. As of now I didn't find a way to disable the inherited one. So I had to use a workaround of below config

```
location /xyz {
    log_by_lua_block { a=2 }
}
```
Which means some lua code will still be executed, which is not my need at all. Any way to disable a hook for certain section? If not then should there be one or not?

**Comment by agentzh** [comment]
@tarunlalwani Just use this:

```
log_by_lua_block { return }
```

It's a bit more efficient than your verison :)
