### ISSUE TITLE
ngx.resp.get_headers() doesn't return all headers.

### ISSUE THREAD

**Issue by rHermes** [openresty/lua-nginx-module#873]
When looking at the ouput of ```ngx.resp.get_headers()``` I found a couple of weird things:

+ Even if the "Connection" header sent to the client is "Keep-Alive", it will always be set to "close" when you use it from any of the ```log_by_lua*``` directives.
+ Several headers are missing, like "Server" and "Date". These cannot be accessed by using ```ngx.var.sent_http_server``` or ```ngx.var.sent_http_date```.

I was just wondering if this is intended behavior or if something is going wrong?

**Comment by agentzh** [comment]
@rHermes This is a FAQ. What you are seeing is the expected behavior since those headers are special headers added by the nginx core (in its `ngx_http_header_filter_module`).

**Comment by rHermes** [comment]
Thank you so much for the quick reply and sorry if I've posted this in the wrong place. If I have made such a mistake, could you tell me where these sort of questions should be posted :D 

Thank you once again for the fast answer!

**Comment by agentzh** [comment]
Please use the openresty-en mailing list for general questions.
