### ISSUE TITLE
in ssl_session_store_by_lua_file directive  use nginx.timer.at.. with ngx.ssl.session.set_serialized_session,this report error

### ISSUE THREAD

**Issue by lvkegarden** [openresty/lua-nginx-module#874]
first, i want use redis cahe in ssl_session_store_by_lua_file'lua.   in the condition ,connect redis server use socket ,so i use nginx.timer.at.   in callback function,i can operator redis.

the problem is ,when i use ngx.ssl.session.set_serialized_session function ,it report error,the error log is session_fetch.lua:12: failed to set cached SSL session: bad request, context: ngx.timer.

in this condition, how to use value get form redis with ngx.ssl.session.set_serialized_session function.

i need your help,thanks.

nginx.conf :

.....
```
server {
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        listen       443 ssl http2 ;
        server_name  localhost;

        ssl_certificate      ./ssl/server.crt;
        ssl_certificate_key  ./ssl/server.key;

       # ssl_session_cache    shared:SSL:1m;
       # ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        
        #ssl_stapling on;ssl_stapling_file ocsp.staple;

		ssl_session_store_by_lua_file conf/lua/session_store.lua;
        ssl_session_fetch_by_lua_file conf/lua/session_fetch.lua;

		
		#test redis
		#rewrite_by_lua_file  conf/lua/thumbnail.lua;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
```

session_fetch.lua :
```
local redis = require("redis_instanse")
local ngx_ssl_session = require "ngx.ssl.session" 
local key, err = ngx_ssl_session.get_session_id() 
g_session = ""
local function async_get_handler(premature, key,ngx_ssl_session) 
	cache = redis:get_redis()
	g_session = cache:get(key)
	ngx.log(ngx.DEBUG, "cache value: ", g_session)

	local ok, err = ngx_ssl_session.set_serialized_session(g_session) 
	if not ok then 
	ngx.log(ngx.ERR, "failed to set cached SSL session: ", err) 
		return 
	end 
end 
local ok, err = ngx.timer.at(0, async_get_handler, key,ngx_ssl_session) 
if not ok then 
    ngx.log(ngx.ERR, "failed to create a 0-delay timer: ", err) 
    return 
end 
```

error.log:
session_fetch.lua:12: failed to set cached SSL session: bad request, context: ngx.timer

**Comment by agentzh** [comment]
@lvkegarden This error usually means that in your timer handler you are using a cosocket which is not initialized in the same timer handler. You cannot pass cosockets across different handler contexts (here, the ssl_session_store_by_lua* context and your timer handler context).

**Comment by agentzh** [comment]
@lvkegarden Another obvious mistake is that you cannot assume that the SSL session still exists when your timer handler calls `set_serialized_session` since timer handlers are already *detached* from the original request handlers that create them, given the asynchronous nature of timers. So this will never work since you already lose the original request connection context in your timer handler, which is completely independent and detached.

**Comment by agentzh** [comment]
@lvkegarden The ssl_session_fetch_by_lua* does support cosockets directly. You should not use timers there. You'd better use the official OpenResty linux packages to avoid patching OpenSSL (or the nginx core if you are not using OpenResty at all):

https://openresty.org/en/linux-packages.html

**Comment by lvkegarden** [comment]
@agentzh hi, thanks for you answer
about:" You cannot pass cosockets across different handler contexts (here, the ssl_session_store_by_lua* context and your timer handler context)."is it mean that in this directive'lua all the created  cosocket is using same tcp() function.
current,we use nginx to build a network,the network  should have a common cache server,in this condition the sessionid and session need store in common cache server,so i select do some operation in  ssl_session_fetch_by_lua'lua to do above things(tips:all about redis operation i used  come from the official openresty,i only do some to get config'msg in my module).
in current condition ,what is the correct way to use redis in ssl_session_fetch_by_lua'lua or realize the network's common need.
http://cjhust.blog.163.com/blog/static/175827157201652221340588/

**Comment by agentzh** [comment]
@lvkegarden I cannot read your English at all. Sorry. I'm closing this.

**Comment by lvkegarden** [comment]
hah,thanks
