### ISSUE TITLE
Doc correction: ngx.* log level constants context missing init_by_lua, init_worker_by_lua

### ISSUE THREAD

**Issue by kraml** [openresty/lua-nginx-module#876]
I noticed that the doc does not mention log level constatns ngx.INFO/ERR/ALERT etc. are available in phases such as init_by_lua, init_worker_by_lua. But they are actually available in these phases. Could you correct the doc?

**Comment by detailyang** [comment]
Thanks for you reply, I try to create a PR to fix:)

**Comment by agentzh** [comment]
#908 is already merged. Consider it resolved.
