### ISSUE TITLE
can not use define error_page setting 

### ISSUE THREAD

**Issue by leo52668** [openresty/lua-nginx-module#877]
```
error_page 406 = /406.html;

location = /406.html {
    internal;
    root /var/www/html;
}

if ($uid_got = '') {
    return 406;
}
```

I've set up a 406.html, but when I start testing, it shows the default 406 page, not my setting page.

Could you tell me what can I do to fix it?

**Comment by agentzh** [comment]
@leo52668 Try temporarily enabling the nginx debugging logs and then we can talk :)

**Comment by leo52668** [comment]
I set the error_log /var/log/nginx/error.log debug;

but  it has no log about the issue.

So, could you tell me how to enable nginx debugging log?

Thnaks.

**Comment by leo52668** [comment]
I tried two setting, for the issue.

No.1 -> it return system default 406 page.
        if ($request_method = GET) {
            return 406;
        }
        error_page 406  /406.html;
        location = /406.html {
            root html;
            internal;
        }

No.2 -> it will return the custom 406 page
        location /test {
           return 406;
        }
        error_page 406  /406.html;
        location = /406.html {
            root html;
            internal;
        }

So, could you tell me what are the different between these?

**Comment by detailyang** [comment]
Hello.
The key point is the `if` is [evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/). If you do not understand if how to work in real, you should not use `if`.

For your case, the if in nginx will create noname location inside, this location will not inherit error_page directive which you write. So it will use default rule:)

You can using the `lua block` to replace `nginx if` to implement you operations:)

By the way, you can close this issue if you do understand.
