### ISSUE TITLE
CUDA is not working properly with OpenResty

### ISSUE THREAD

**Issue by mdasadul** [openresty/lua-nginx-module#882]
* OpenResty and NGINX core version version: 1.11.2.1, Lua version 5.1
* Here is my ngx.conf look like 

````
      events {}
http {
  lua_code_cache on;
  #lua_package_path ";;$prefix/?.lua;";
  lua_package_path './?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?$
   lua_package_cpath './?.so;/usr/lib/lua/5.1/?.so;';
   init_by_lua_file 'foo.lua';
    server {
    lua_code_cache on;
    listen 6788;
      location / {
content_by_lua '

local p=f(8)
ngx.say(p)
';
}
  }
}
````
* My foo.lua looks like which is without CUDA and working fine

````
local torch =require("torch")
a=torch.Tensor(2,2):fill(3)

function _add(p)
b=torch.Tensor(2,2):fill(p)
return b:add(a):sum()
end


function f(type)
return _add(type)
end
````
* When I am adding CUDA with it it's giving me several errors
*Here is the modified foo.lua with CUDA
````
local torch =require("torch")

local cutorch = require 'cutorch'
a=torch.Tensor(2,2):fill(3):cuda()

function _add(p)
b=torch.Tensor(2,2):fill(p):cuda()
return b:add(a):sum()
end


function f(type)
return _add(type)
end
````

* I am getting following error
```` THCudaCheck FAIL file=/tmp/buildd/torch7-0.9.99/extra/cutorch/lib/THC/generic/THCStorage.cu line=41 error=3 : initialization error
2016/10/03 13:36:03 [error] 27488#0: *1 lua entry thread aborted: runtime error: unknown reason
stack traceback:
coroutine 0:
        [C]: in function 'resize'
        /usr/share/lua/5.1/cutorch/Tensor.lua:14: in function 'cuda'
        /data/asadul/score/Model_sept_02/rootpath/foo.lua:10: in function 'f'
        content_by_lua(testngx.conf:23):4: in function <content_by_lua(testngx.conf:23):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:6788" ````


* I am using ubuntu 14.04 and running the nginx by following commands
 ```` /usr/local/openresty/nginx/sbin/nginx -p "$(pwd)" -c "ngx.conf" ````

* getting the output by 
```` curl http://localhost:6788/ ````

**Comment by mdasadul** [comment]
It's working perfectly fine with Luajit command line. I am using that library to use GPU. I think openrestry fails when Lua is using GPU

**Comment by agentzh** [comment]
You should check what exactly the error code returned by your Lua library in your error log means.

You can try replacing your init_by_lua directive with init_worker_by_lua. Maybe your Lua library hates process forking.

You can also try using your own system account to run the nginx worker processes. Maybe the default nobody account does not have enough permissions to access your GPU.

Be careful when blaming OpenResty. It could well be your own usage mistake.

**Comment by mdasadul** [comment]
init_worker_by_lua is working fine so it's process forking issue. Thanks @agentzh for your help and this wonderful piece of software
