### ISSUE TITLE
ngx.req.set_header for authorization

### ISSUE THREAD

**Issue by amreladawy** [openresty/lua-nginx-module#884]
I am trying to set the AUTHORIZATION header with no success

nginx.conf:

```
location /lua {
    rewrite_by_lua_file /fake/path/content.lua;
    lua_code_cache off;
    proxy_pass  https://localhost/app.php;
}
```
content.lua:

```
ngx.req.set_header('ATHURIZATION', 'c29tZXVzZXI6MQ==')
ngx.req.set_header('any_other_name', 'c29tZXVzZXI6MQ==')
```

The request reaches the ```app.php``` but with the header "any_other_name" only set and the authorization is empty.

Running openresty Version 1.11.2.1  windows 10

**Comment by detailyang** [comment]
check the typo `ATHURIZATION` :)

**Comment by amreladawy** [comment]
I got it working, It was not the typo in my post above. It was in the php code in the proxied server. 
Thanks
