### ISSUE TITLE
Strange behavior of lua script addressing in nginx

### ISSUE THREAD

**Issue by microbash** [openresty/lua-nginx-module#886]
Hello, please help with my issue.

content files:
#cat /usr/local/www/example.ru/idx.lua
ngx.say("example.ru")
#cat /usr/local/www/example.ru/index.html
<!DOCTYPE html>
<html>
<head><title>example.ru</title></head>
<body>example.ru</body>
</html>

lua address methods (1) and (2) in nginx.conf:
(1) NO ERRORS, show idx.lua
http {
lua_package_path '/usr/local/www/example.ru/?.lua;;';
...
server {
...
location = / {
default_type text/html;
root /usr/local/www/example.ru;
content_by_lua_file **/usr/local/www/example.ru/**idx.lua;
index idx.lua;
}
...

(2) ERROR: cannot open /usr/local/etc/nginx/idx.lua, not show idx.lua
http {
lua_package_path '/usr/local/www/example.ru/?.lua;;';
...
server {
...
location = / {
default_type text/html;
root /usr/local/www/example.ru;
content_by_lua_file idx.lua;
index idx.lua;
}
...

(3) simple html, no errors, show index.html
http {
...
server {
...
location = / {
default_type text/html;
root /usr/local/www/example.ru;
index index.html;
}

How I could use content_by_lua_file without absolute file path?
How I could use nginx lua engine with lua files in the current location directory?
Thank you.

**Comment by agentzh** [comment]
@microbash I suggest you read the docs more carefully. It's all documented:

https://github.com/openresty/lua-nginx-module#content_by_lua_file

https://openresty.org/en/getting-started.html

You can also look through the demo apps:

https://openresty.org/en/samples.html

BTW, such general questions should go to the openresty-en mailing list instead. Please see http://openresty.org/en/community.html Thanks for your cooperation.
