### ISSUE TITLE
Read proxied server response before sending the headers to the client 

### ISSUE THREAD

**Issue by amreladawy** [openresty/lua-nginx-module#888]
I am using openresty as a reverse proxy between a client and a service provider through the following steps

1. I am changing the headers coming from the client 
2. I convert the GET method to POST and create a body to be passed to the proxied server.
3. The response coming back from is then altered and sent to the client

### The problem 
As the final response sent back to the client is altered, I need to change the Content-Length to match the new content. I am able to read the response from the proxied server only in the ```body_filter_by_lua_file``` but at that stage, the headers are already sent.

In the ```header_filter_by_lua_file``` phase, I don't have access on the response ```ng.args[1]```

Currently, I am removing the Content-Length header making the request chunked which is causing a problem the client. 

How can I send the correct content length back to the client?

**Comment by agentzh** [comment]
@amreladawy Why don't you just clear the content-length header in your Lua header filter and let the nginx core use the chunked encoding for your response body? BTW, it's documented here:

https://github.com/openresty/lua-nginx-module#body_filter_by_lua

Please read the documentation more carefully.

**Comment by amreladawy** [comment]
Hi @agentzh, thanks for the reply.  It would be a problem for my client to get a chunked response. I need to read the response from the proxied server and alter it then calculate the final content length 

BTW what you recommended is already mentioned in my post.  Please read the raised issues more carefully.
