### ISSUE TITLE
Is required files cached or not?

### ISSUE THREAD

**Issue by microbash** [openresty/lua-nginx-module#893]
hello.

My application has two lua files:
# cat /usr/local/www/app/a.lua
local b = require("b")
local a = {}
function a.out()
    ngx.say("aaa")
end
a.out()
b.out()

# cat /usr/local/www/app/b.lua
local b = {}
function b.out()
    ngx.say("bbb")
end
return b

and nginx.conf:
...
http {
    lua_package_path '
    ;/usr/local/www/app/?.lua;
    ';
...
        location / {
            default_type text/plain;
            lua_need_request_body on;
            **lua_code_cache on;**
            **content_by_lua_file app/a.lua;**
        }
...

**When I go on my application by browser I get page:
aaa
bbb**

In nginx info log I have this (**a.lua is in the cache, b.lua is not in the cache**):

lua *** ngx_http_lua_cache_loadfile: CACHE file key already pre-calculated at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 227.
lua *** ngx_http_lua_cache_loadfile: XXX cache key for file: [nhlf_15b9742d0d3e96410dd70a74248099de] at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 230.
lua *** ngx_http_lua_cache_load_code: Code cache table to load: 0x96f8 at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 45.
lua *** ngx_http_lua_cache_load_code: Value associated with given key in code cache table is not code chunk: stack top=2, top value type=no value
 at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 80.
lua *** ngx_http_lua_cache_loadfile: Code cache missed! cache key='nhlf_15b9742d0d3e96410dd70a74248099de', stack top=0, **file path='/usr/local/www/app/a.lua'** at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 247.
lua *** ngx_http_lua_cache_loadfile: loadfile returns 0 (6) at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 252.
lua *** ngx_http_lua_cache_store_code: Code cache table to store: 0x96f8 at /usr/ports/www/nginx/work/lua-nginx-module-0.10.6/src/ngx_http_lua_cache.c line 111.

Is required lua script files cached or not?
Thank you.

**Comment by detailyang** [comment]
yes, you can check the doc [lua-variable-scope](https://github.com/openresty/lua-nginx-module#lua-variable-scope).

By the way, you can learn [github markdown](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) to beautify comment:)

**Comment by microbash** [comment]
-> yes, you can check the doc lua-variable-scope.

I have read the doc. Why don't I see the second file in the cache log?

**Comment by microbash** [comment]
-> By the way, you can learn github markdown to beautify comment:)
Sorry, I'm a beginner. I will try in the future )

**Comment by detailyang** [comment]
That's because require is cached on the lua global variable  package.loaded table not    ngx_http_lua_cache_loadfile

**Comment by detailyang** [comment]
maybe you can close the issue if you do understand :)
