### ISSUE TITLE
package.path in lua cache

### ISSUE THREAD

**Issue by microbash** [openresty/lua-nginx-module#894]
hello.

I have two applications:

**app1 in the /usr/local/www/app1/**
-- app1/a.lua
if string.find(package.path,'app1') == nil then
    package.path = '/usr/local/www/app1/?.lua;'..package.path
end
local a = {}
function a.out()
    ngx.say(package.path)
    ngx.say(string.len(package.path))
    ngx.say("app A")
end
a.out()
local c = require "config"
c.out()

-- app1/config.lua
local config = {}
function config.out()
    ngx.say("app A config")
end

**app2 in the /usr/local/www/app2/**
-- app2/b.lua
if string.find(package.path,'app2') == nil then
    package.path = '/usr/local/www/app2/?.lua;'..package.path
end
local b = {}
function b.out()
    ngx.say(package.path)
    ngx.say(string.len(package.path))
    ngx.say("app B")
end
b.out()
local c = require "config"
c.out()

-- app2/config.lua
local config = {}
function config.out()
    ngx.say("app B config")
end
return config

and my nginx.conf is:
# server 1
        location / {
            default_type text/plain;
            lua_need_request_body on;
            **lua_code_cache off;**
            content_by_lua_file app1/a.lua;
        }
# server 2
        location / {
            default_type text/plain;
            lua_need_request_body on;
            **lua_code_cache off;**
            content_by_lua_file app2/b.lua;
            }

This is work good!
browser1 -> http://example1/ -> output -> 
/usr/local/www/app1/?.lua;./?.lua;/usr/local/share/luajit-2.0.4/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
136
app A
app A config

browser2 -> http://example2/ -> output ->
/usr/local/www/app2/?.lua;./?.lua;/usr/local/share/luajit-2.0.4/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
139
app B
app B config

**NOW, I use the lua cache:**
# server 1
        location / {
            default_type text/plain;
            lua_need_request_body on;
            **lua_code_cache on;**
            content_by_lua_file app1/a.lua;
        }
# server 2
        location / {
            default_type text/plain;
            lua_need_request_body on;
            **lua_code_cache on;**
            content_by_lua_file app2/b.lua;
            }

browser1 -> http://example1/ -> output -> 
/usr/local/www/app1/?.lua;./?.lua;/usr/local/share/luajit-2.0.4/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
136
app A
app A config

browser2 -> http://example2/ -> output ->
/usr/local/www/app2/?.lua;/usr/local/www/app1/?.lua;./?.lua;/usr/local/share/luajit-2.0.4/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
165
app B
app A config

Why?

**Comment by microbash** [comment]
More simple example.

**app1 in the /usr/local/www/app1/**
-- app1/a.lua
ngx.say(package.path)

**app2 in the /usr/local/www/app2/**
-- app2/b.lua
package.path = 'hello'
ngx.say(package.path)

nginx.conf
# server example1.com
...
  location / {
        default_type text/plain;
        lua_need_request_body on;
        **lua_code_cache on;**
        content_by_lua_file app1/a.lua;
    }
...
...
#server example2.com
...
  location / {
        default_type text/plain;
        lua_need_request_body on;
        **lua_code_cache on;**
        content_by_lua_file app2/b.lua;
    }
...

browser1 -> http://example1/ -> output ->
./?.lua;/usr/local/share/luajit-2.0.4/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua

browser2 -> http://example2/ -> output ->
hello

browser1 -> http://example1/ (or F5) -> output->
hello

Why?

**Comment by detailyang** [comment]
because you all requests enter the same lua vm instance on the same nginx worker when you enable `lua_code_cache`;
 
you should understand when you enable `lua_code_cache`, what's happening on nginx.

By agentzh said
>Basically, when lua_code_cache is off, each request has its own (isolated) Lua VM instance and init_by_lua is run for every such VM instance. And it's just for quick development only. Never use it in production because of its functional limitations and high overhead.

**Comment by microbash** [comment]
Ok, now I see  developers idea. "Production level" is one application for one nginx with one lua vm.
