### ISSUE TITLE
Test failures in 147-tcp-socket-timeouts.t under mockeagain test mode

### ISSUE THREAD

**Issue by agentzh** [openresty/lua-nginx-module#901]
@doujiang24 When running the latest git master branch on my EC2 test cluster, I noted some test failures in the mockeagain testing mode in your recently added`147-tcp-socket-timeouts.t` test file. For example, in mockeagain reading test mode, TEST 3, TEST 6, and TEST 7 fail:

```
TEST 3: send ok - response_body_like - response is expected (failed to send body: timeout)
'failed to send body: timeout
'
doesn't match '(?^s:received: got len: 8290304
)'
TEST 3: send ok - pattern "[error]" should not match any line in error.log but matches line "2016/10/30 02:53:12 [error] 16922\#0: *1 lua tcp socket write timed out, client: 127.0.0.1, server: localhost, request: \"GET /t HTTP/1.1\", host: \"localhost\"" (req 0)
TEST 6: different timeout with duplex socket (settimeout) - response_body - response is expected (repeated req 0, req 0)
@@ -1,2 +1,2 @@
received: ok
-failed to receive a line: closed []
+failed to receive a line: timeout []
'
TEST 6: different timeout with duplex socket (settimeout) - pattern "failed to receive data: timeout" should match a line in error.log (req 0)
TEST 7: different timeout with duplex socket (settimeouts) - response_body - response is expected (repeated req 0, req 0)
@@ -1,2 +1,2 @@
received: ok
-failed to receive a line: closed []
+failed to receive a line: timeout []
'
TEST 7: different timeout with duplex socket (settimeouts) - pattern "[error]" should not match any line in error.log but matches line "2016/10/30 02:53:14 [error] 16933\#0: *1 lua tcp socket read timed out, client: 127.0.0.1, server: localhost, request: \"GET /t HTTP/1.1\", host: \"localhost\"" (req 0)
```

Also, in mockeagain writing mode + valgrind mode, TEST 3 and TEST 4 even time out:

```
ERROR: client socket timed out - TEST 4: send timeout
ERROR: client socket timed out - TEST 3: send ok
```

I see you are sending many mega bytes of data in the test case, which is very unfriendly to these test modes. The recommended way is to use small payload and leverage the `MOCKEAGAIN_WRITE_TIMEOUT_PATTERN` feature of mockeagain to achieve extremely slow writing at the same time :)

Will you please help fixing these tests? Many thanks!

**Comment by doujiang24** [comment]
@agentzh Just created a PR: https://github.com/openresty/lua-nginx-module/pull/902, which passed on my side with both `mockeagain reading test mode` and `mockeagain writing mode + valgrind mode`
