### ISSUE TITLE
Build Fail with OpenSSL 1.1.0b

### ISSUE THREAD

**Issue by smoghaddas** [openresty/lua-nginx-module#903]
dear all
i compile openresty 1.11.2.1 with 1.1.0b and got this error ...

-I /proxy/source/openssl-1.1.0b/.openssl/include -I objs \
        -o objs/src/event/ngx_event_openssl.o \
        src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function 'ngx_ssl_connection_error':
src/event/ngx_event_openssl.c:2048:21: error: 'SSL_R_NO_CIPHERS_PASSED' undeclared (first use in this function)
             || n == SSL_R_NO_CIPHERS_PASSED                          /*  182 */
                     ^
src/event/ngx_event_openssl.c:2048:21: note: each undeclared identifier is reported only once for each function it appears in
objs/Makefile:1287: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[2]: *** [objs/src/event/ngx_event_openssl.o] Error 1
make[2]: Leaving directory '/proxy/source/openresty-1.11.2.1/build/nginx-1.11.2'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/proxy/source/openresty-1.11.2.1/build/nginx-1.11.2'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bjoe2k4** [comment]
See #757 and #761.

**Comment by agentzh** [comment]
Use the OpenSSL 1.0.2 series instead.

**Comment by KeithTt** [comment]
So terrible... I just upgrade openssl to 1.1.0f few days ago.

**Comment by thibaultcha** [comment]
FYI, support for OpenSSL 1.1.0 has recently been merged and is pending for release: https://github.com/openresty/lua-nginx-module/pull/1213

**Comment by agentzh** [comment]
Already in the master branches.
