### ISSUE TITLE
Auto added new line in response

### ISSUE THREAD

**Issue by Romaboy** [openresty/lua-nginx-module#910]
Hello, I want write about very small bug, that many could not see.
Server side just check that something is true or false and respond:
```lua
ngx.say('true')
```
but javascript on client receives "true\n" and can't check it by respond == "true".
Yes, it is easy to walk around that, but that new line is bad.

**Comment by agentzh** [comment]
I think you should use ngx.print() instead.

**Comment by Romaboy** [comment]
sorry, it was in readme
