### ISSUE TITLE
how to use ngx lua to catch nginx error log 

### ISSUE THREAD

**Issue by jaywayjayway** [openresty/lua-nginx-module#914]
HI, everyone. Now, I use ngx_lua to catch nginx access log (just use variable in nginx [ngx.var.status],[ngx.var.http_x_forwarded_for],[ngx.var.request_time] ). But how to get the PHP error log from fastcgi_pass.

**Comment by agentzh** [comment]
@jaywayjayway Such general questions should go to the openresty-en mailing list, thank you! Please see

http://openresty.org/en/community.html
