### ISSUE TITLE
/ngx_http_lua_api.c:179:11: error: no member named 'noreuse' in 'struct ngx_shm_zone_s'

### ISSUE THREAD

**Issue by idreamsoft** [openresty/lua-nginx-module#923]
lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179:11: error: no member named 'noreuse' in 'struct ngx_shm_zone_s'
    zone->noreuse = shm_zone->noreuse;

/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179:31: error: no member named 'noreuse' in 'struct ngx_shm_zone_s'
    zone->noreuse = shm_zone->noreuse;
                    ~~~~~~~~  ^
2 errors generated.
objs/Makefile:1703: recipe for target 'objs/addon/src/ngx_http_lua_api.o' failed
gmake[1]: *** [objs/addon/src/ngx_http_lua_api.o] Error 1
Makefile:8: recipe for target 'build' failed
gmake: *** [build] Error 2

OS: FreeBSD 10.1-RELEASE amd64

**Comment by agentzh** [comment]
@idreamsoft Seems like you are using an old version of the nginx core.

**Comment by agentzh** [comment]
@doujiang24 Will you mind proposing a patch to fix this issue for older nginx cores? Many thanks!

**Comment by idreamsoft** [comment]
@agentzh nginx 1.6.2 Tengine 2.1.0

**Comment by agentzh** [comment]
@idreamsoft BTW, Tengine is not a supported target of this module.

**Comment by doujiang24** [comment]
@agentzh We have already checked the `nginx_version`: https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_api.c#L178
And nginx 1.9.0 do have `noreuse` in `ngx_shm_zone_s`.

@idreamsoft will you check the `nginx_version` in your Tengine src?

**Comment by idreamsoft** [comment]
@agentzh @doujiang24
解决了 
非常谢谢
Tengine 可以支持这个模块
编译通过了

**Comment by agentzh** [comment]
No Chinese here please. And no Tengine discussions here either. Thanks for your cooperation. I am closing this.

**Comment by nonight89** [comment]
The latest release version(0.10.7) of lua-nginx-module does not check the version of the nginx(https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_api.c#L178), so if you want install the module on Tengine you should add this version checking code by yourself.
