### ISSUE TITLE
error: lua pcre free failed due to empty pcre pool

### ISSUE THREAD

**Issue by YannKr** [openresty/lua-nginx-module#928]
Using openresty-1.11.2.2 with "--with-ipv6 --with-pcre-jit --with-http_realip_module --with-http_auth_request_module" configure options. I tried enabling debug, it didn't give me any additional details.

When using lua code within log_by_lua and doing following regex:
```
      local iterator, iter_err = ngx.re.gmatch(authorization_header, "\\s*[Bb]earer\\s+(.+\\..+\\..+)")
```

Every ~5-10th request, nginx throws an error (without newline) saying "error: lua pcre free failed due to empty pcre pool".

I use this code to parse JWT tokens to then decode them. I've managed to reproduce it by only running that regex only using ngx.re.gmatch. The requests seem to succeed but this does mess up our logs quite a bit :)

Any suggestion on what's wrong here is welcome. Let me know if you need anything else from me.

**Comment by agentzh** [comment]
@YannKr I've never seen this before. Are you using any 3rd-party Lua libraries which use the PCRE C API? If yes, then please avoid those Lua libraries in the OpenResty environment.
