### ISSUE TITLE
failed:compile with tengine  dso_tool

### ISSUE THREAD

**Issue by leavesbnw** [openresty/lua-nginx-module#930]
* lua-nginx-module version: 0.10.7
* Tengine version: Tengine/2.1.2 (nginx/1.6.2)
* compile failed with report ：

   /root/lua-nginx-module-0.10.7/src/ngx_http_lua_socket_tcp.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -fPIC -DNDK_SET_VAR -I /root/lua-nginx-module-0.10.7/src/api -I /usr/local/include/luajit-2.0  \
                -Iobjs -I/usr/local/tengine/include \
                -o objs/src/src/ngx_http_lua_api.o \
                /root/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c
/root/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c: 在函数‘ngx_http_lua_shared_memory_init’中:
/root/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179: 错误：‘ngx_shm_zone_t’没有名为‘noreuse’的成员
/root/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179: 错误：‘ngx_shm_zone_t’没有名为‘noreuse’的成员
make: *** [objs/src/src/ngx_http_lua_api.o] 错误 1

but 
 lua-nginx-module version 0.10.6 is OK

**Comment by leavesbnw** [comment]
I have known why

**Comment by agentzh** [comment]
@leavesbnw BTW, Tengine is *not* a supported target of this module.
