### ISSUE TITLE
ngx.thread.wait 如何归并多个上游服务器的返回结果，而不是最先返回的结果？

### ISSUE THREAD

**Issue by ygm521** [openresty/lua-nginx-module#932]
您好：
        请教下，我现在想使用lua归并多个上游服务器返回的结果数据，而不是最先返回的结果。请问怎么解决呢？ 谢谢！我试了下ngx.thread.wait 个获取最先返回的结果。谢谢

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
