### ISSUE TITLE
Cannot compile on Windows (luajit not found)

### ISSUE THREAD

**Issue by pavlusha23** [openresty/lua-nginx-module#934]
All the necessary files (lua + luajit) (*.lib *.dll *.h) are located in the objs/lib/luajit. However, the compilation fails. Please repair the module compilation for Windows or provide detailed instructions to compile the module.

```
......
......
C:\LuaJIT-2.0.4\src>if exist lua51.dll.manifest mt /nologo -manifest lua51.dll.m
anifest -outputresource:lua51.dll;2

C:\LuaJIT-2.0.4\src>cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE luajit.c
luajit.c

C:\LuaJIT-2.0.4\src>link /nologo /out:luajit.exe luajit.obj lua51.lib

C:\LuaJIT-2.0.4\src>if exist luajit.exe.manifest mt /nologo -manifest luajit.exe
.manifest -outputresource:luajit.exe

=== Successfully built LuaJIT for Windows/x86 ===
```
and copy all files to objs/lib/luajit

```
export LUAJIT_INC=objs/lib/luajit
export LUAJIT_LIB=objs/lib/luajit

./auto/configure						\
		--with-cc=cl						\
		--builddir=objs						\
		--prefix= 						\
		--conf-path=conf/nginx.conf				\
		--pid-path=logs/nginx.pid				\
		--http-log-path=logs/access.log				\
		--error-log-path=logs/error.log				\
		--sbin-path=nginx.exe					\
		--http-client-body-temp-path=temp/client_body_temp	\
		--http-proxy-temp-path=temp/proxy_temp			\
		--http-fastcgi-temp-path=temp/fastcgi_temp		\
		--http-scgi-temp-path=temp/scgi_temp			\
		--http-uwsgi-temp-path=temp/uwsgi_temp			\
		--with-cc-opt='-DFD_SETSIZE=32768'			\
		--with-pcre=objs/lib/pcre-8.39				\
		--with-pcre-jit						\
		--with-zlib=objs/lib/zlib-1.2.8				\
		--with-select_module					\
		--add-module=objs/lib/ngx_devel_kit-0.3.0			\
                --add-module=objs/lib/lua-nginx-module-openssl-1.1   
```

```
checking for OS
 + MINGW32_NT-6.1-WOW 2.6.0(0.304/5/3) i686
 + using Microsoft Visual C++ compiler
 + cl version:
auto/cc/msvc: line 117: [: : integer expression expected
checking for MINGW32_NT-6.1-WOW specific features
configuring additional modules
adding module in objs/lib/ngx_devel_kit-0.3.0
 + ngx_devel_kit was configured
adding module in objs/lib/lua-nginx-module-openssl-1.1
checking for LuaJIT library in objs/lib/luajit and objs/lib/luajit (win32) ... not found
        ./auto/configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUAJIT_LIB is defined as objs/lib/luajit and LUAJIT_INC (path for lua.h) objs/lib/luajit, but we cannot find LuaJIT there.

```

**Comment by agentzh** [comment]
@pavlusha23 See https://github.com/openresty/openresty/blob/master/doc/README-win32.md

**Comment by pavlusha23** [comment]
Why did you send me to the compilation instructions OpenResty? OpenResty!=Nginx

I tell you about the bug - lua-nginx-module does not compile on Windows with the standard official distribution Nginx! I would like to compile my own version official distribution Nginx + lua-nginx-module, I do not need OpenResty.

If your module is not compatible with the official distribution Nginx (on Windows) the need to write about it on the project's home page.

**Comment by agentzh** [comment]
@pavlusha23 OpenResty == NGINX + ngx_lua + ... and the latter is configurable.

For ngx_lua, we no longer want to (officially) support compilation with stock nginx since building OpenResty is much much easier and much much safer.

**Comment by pavlusha23** [comment]
lua-nginx-module must be renamed to lua-resty-module because it does not support compilation with stock nginx (on Windows). Do not deceive your users.

**Comment by agentzh** [comment]
@pavlusha23 Sorry for the confusion, I mean we do not want to provide free technical support for helping you to compile ngx_lua with the stock nginx core. The ngx_lua module will always support the official nginx core. You have my word. We just do not have enough time and energy to support nginx users who do not know what they are doing even after reading the official installation documentation of ngx_lua. Am I clear enough?

**Comment by agentzh** [comment]
@pavlusha23 I suggest you ask on the openresty-en mailing list so that the OpenResty user community can help you out. Filing a ticket on this github project means asking for help from the ngx_lua maintainers. See

http://openresty.org/en/community.html

**Comment by agentzh** [comment]
@pavlusha23 BTW, you are using open source projects and paying NOTHING. So please be nice to open source developers. Thank you.

**Comment by pavlusha23** [comment]
Thank you for your answers. I have great respect for open source developers. And I do not need any support, either paid or free. I just killed a 3 day time trying to compile your module. It turned out that it does not support stock nginx (on Windows). As you said, you do not want to support the compilation with the stock nginx because you promote your OpenResty, which I do not want to use.

Out of respect for users it would be great to write only two lines of text on the project's home page that lua-nginx-module does not support stock nginx (on Windows). I killed 3 days, and some maybe more.

Sorry for my English, it is google translate.

**Comment by agentzh** [comment]
@pavlusha23 It does support compiling stock nginx cores on Windows. Otherwise OpenResty won't compile on Windows. OpenResty is a bundle per se. You can either look at how OpenResty does the job or ask on openresty-en mailing lists. But spreading out the false information that ngx_lua module does not support building with stock NGINX on Windows is a shame.

**Comment by agentzh** [comment]
@pavlusha23 And it's not that I want to promote OpenResty. But as I've stated, we do not have enough developer time to hand-hold every nginx user who wants to choose the hard way. Please do not make false statements like that either. That's also a shame.

**Comment by agentzh** [comment]
@pavlusha23 I understand your frustrations with your own experiments but you should not blame us for that. That's not fair at all. Especially when we've given you several constructive suggestions and trying to help you.

**Comment by agentzh** [comment]
@pavlusha23 Again: be nice!
