### ISSUE TITLE
caputure and range

### ISSUE THREAD

**Issue by aholic** [openresty/lua-nginx-module#947]
conf:
```
server {
    listen 80;
    location /lua {
        rewrite_by_lua '
            --ngx.req.read_body()
            ngx.req.set_header("Range", "bytes=0-10")
            local res = ngx.location.capture("/30m")
            ngx.log(ngx.ERR, res.status)
        ';
    }
    location / {
        root html;
    }
}
```

It will always give me a `200` in log. But I can get a `206` from `curl '127.0.0.1:80/30m' -r0-10 -v`

**Comment by aholic** [comment]
I am using gdb to trace it. I find that both `r` and `sr` have the header `Range: bytes=0-10` in `headers_in`, but why it doesn't work for the `sr`? ( `sr -> main == r`

**Comment by aholic** [comment]
I found that `range_header_filter` is being placed after `ngx_http_lua_capture_header_filter`. And in the end of `ngx_http_lua_capture_header_filter`, it doesn't call `ngx_http_lua_next_header_filter` if it's a subrequest. If it's a subrequest, it just return......

So `range_body_filter` did nothing.

It seems a feature, not a bug. why?

**Comment by agentzh** [comment]
@aholic The subrequest thing is simple and do not try to expect too much from it.

**Comment by aholic** [comment]
yes……when i found so many issues about it, i feel gg……

**Comment by agentzh** [comment]
@aholic For your use case, I think you can just do the work of the range-header-filter in your parent request's Lua handler. It should be easy I think.

**Comment by agentzh** [comment]
@aholic It can quickly become tricky to work around the running order of output filters (3rd-party modules actually have very little control over that). And this is also why we introduced Lua into the nginx world in the first place :)
