### ISSUE TITLE
coroutine.resume and error logging

### ISSUE THREAD

**Issue by bungle** [openresty/lua-nginx-module#951]
As far as I know, `coroutine.resume` should behave about the same as `pcall` regarding to errors, but this code gives different results:

```lua
local function a()
    error "ohno"
end
print(coroutine.resume(coroutine.create(a)))
print(pcall(a))
```

Here are different outputs.

```bash
bungle@mbp13tb:~$ lua a.lua 
false	a.lua:2: ohno
false	a.lua:2: ohno
bungle@mbp13tb:~$ luajit a.lua 
false	a.lua:2: ohno
false	a.lua:2: ohno
bungle@mbp13tb:~$ resty a.lua 
2017/01/12 22:43:20 [error] 19716#0: *2 lua coroutine: runtime error: a.lua:2: ohno
stack traceback:
coroutine 0:
	[C]: in function 'error'
	a.lua:2: in function <a.lua:1>
coroutine 1:
	[C]: in function 'resume'
	a.lua:5: in function 'file_gen'
	init_worker_by_lua:36: in function <init_worker_by_lua:34>
	[C]: in function 'pcall'
	init_worker_by_lua:43: in function <init_worker_by_lua:41>, context: ngx.timer
false	a.lua:2: ohno
false	a.lua:2: ohno
```

The last example with `resty` writes to error log when using `coroutine.resume` but doesn't write to error log when using `pcall`. Is there some specific reason for that? I think it is better if the `resty`(and OpenResty) just does the same as with `pcall` when calling `coroutine.resume` aka no logging.

**Comment by agentzh** [comment]
@bungle Yeah, it's better to behave the same. Mind to propose a pull request for this? ;)

**Comment by bungle** [comment]
@agentzh, yes, but do you know if this should behave differently with "main" coroutine?

**Comment by agentzh** [comment]
@bungle You mean the main light thread, right? For all light threads (not just the main ones), they should not capture any exceptions due to their asynchronous nature.

**Comment by bungle** [comment]
@agentzh,

The problem is here:
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_util.c#L1440-L1441

But if I comment that out, this code doesn't log anything:

```lua
local function a()
    error "this is just a return value for coroutine.resume & pcall"
end
print(coroutine.resume(coroutine.create(a)))
print(pcall(a))
error 'this should be logged as an error in nginx logs'
```

I think the last line here should log normally that error.

That's why I was questioning that should this behave differently on the main light thread?

I tried a few guards, but I have not found the correct one yet.

**Comment by bungle** [comment]
Well, actually there could be another problem. Aka this last `error` call actually doesn't write error. So those lines could be removed, and it fixes this issue, but should we have another issue for that last `error` call?

**Comment by agentzh** [comment]
@bungle We should not change the default behavior of logging errors. Otherwise we'll sit completely in darkness if the Lua handler does not explicitly handle the Lua error.

**Comment by bungle** [comment]
The comment above those lines says:

```
ended with error, coroutine.resume returns false plus err msg
```

Aka no logging needed. Same as `pcall` aka `nil, err`. But the darkness is from some other place where this patch has nothing to do.

**Comment by thibaultcha** [comment]
Done as part of #1239, closing this issue, thanks!
