### ISSUE TITLE
ngx.header["Set-Cookies"] -> Corrupts Content-Type header.

### ISSUE THREAD

**Issue by Fr3DBr** [openresty/lua-nginx-module#955]
Hi, I'm using the version: 1.11.2.2

After using ngx.header["Set-Cookie"] in rewrite_by_lua, the Content-Type: header is corrupted, not sure why, but it happens, here's the output:

```
Date: Sat, 14 Jan 2017 11:47:28 GMT
Content-Type: text/html^@^@^@^@^S�D^@^@^@^@^@��D
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
```

The code used to produce this was:

```
               cname1="COK1_"
               cname2="COK2_"
               cval1="asdjASDJasjdasdjasdiewqeqwoweaksdk1"
               cval2="09as9d0as9d0912k123k12k3aid9asd91#"
               local cookie1    = cname1 .. "=" .. cval1 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                local cookie2    = cname2 .. "=" .. cval2 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                ngx.header["Set-Cookie"] = { cookie1, cookie2 }
```

Not sure exactly what happens, but due to this, it cannot serve the content properly.

**Comment by Fr3DBr** [comment]
Temporarily, I've fixed it by doing a "backup" of Content-Type this way:

```
               cname1="COK1_"
               cname2="COK2_"
               cval1="asdjASDJasjdasdjasdiewqeqwoweaksdk1"
               cval2="09as9d0as9d0912k123k12k3aid9asd91#"
               local content_type_backup = ngx.header["Content-Type"]
               local cookie1    = cname1 .. "=" .. cval1 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                local cookie2    = cname2 .. "=" .. cval2 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                ngx.header["Set-Cookie"] = { cookie1, cookie2 }
                ngx.header["Content-Type"] = content_type_backup

```

**Comment by agentzh** [comment]
@moonbingbing @membphis Will you look into this?

@Fr3DBr Will you confirm that your code example above can indeed reproduce the problem easily in isolation?

**Comment by agentzh** [comment]
@Fr3DBr Your code snippet is incomplete since it does not define the `expire` Lua variable. Please provide a minimal and standalone example that can easily reproduce the problem on others' machines. Thank you.

**Comment by agentzh** [comment]
@Fr3DBr I tried the following example and it works fine on my side:

```
    location = /t {
        content_by_lua_block {
                local expire = 32
               cname1="COK1_"
               cname2="COK2_"
               cval1="asdjASDJasjdasdjasdiewqeqwoweaksdk1"
               cval2="09as9d0as9d0912k123k12k3aid9asd91#"
               local cookie1    = cname1 .. "=" .. cval1 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                local cookie2    = cname2 .. "=" .. cval2 .. "; Path=/; Expires=" .. ngx.cookie_time(ngx.time() + expire)
                ngx.header["Set-Cookie"] = { cookie1, cookie2 }
        }
    }
```

Requesting `/t` gives me the *expected* response header

```
HTTP/1.1 200 OK
Server: openresty/1.11.2.2
Date: Sat, 14 Jan 2017 19:18:31 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: close
Set-Cookie: COK1_=asdjASDJasjdasdjasdiewqeqwoweaksdk1; Path=/; Expires=Sat, 14-Jan-17 19:19:03 GMT
Set-Cookie: COK2_=09as9d0as9d0912k123k12k3aid9asd91#; Path=/; Expires=Sat, 14-Jan-17 19:19:03 GMT
```

BTW, you should always use local Lua variables instead of globals. Though the use of globals should have no impact here.

**Comment by agentzh** [comment]
@Fr3DBr Please see above for what a standalone and minimal example should look like.

**Comment by Fr3DBr** [comment]
@agentzh Indeed I had forgot to "paste" the expire variable. 👍 But, yes, in my case the problem was happening, anyways, I was already using "local" declarations for all variables, like this:

```
                local cname1     = "__COK_1"
                local cval1      = ""
                local cname2     = "__COK_2"
                local cval2      = ""
                local expire     = (3600 * 24) -- 1 day
```

So yes, you can be sure I'm using local vars. 👍

**Comment by agentzh** [comment]
@Fr3DBr Please try my standalone example above on your side. If you are doing something different, please make any changes to that example while still keeping its integrity. Your previous comment still fails to provide a minimal and standalone example that we can easily run on our side. If you see corrupted responses, then you should provide the steps and the actual stuff you are seeing. I feel sad that you still refuse to follow my suggestions. I don't know how we can help.

**Comment by agentzh** [comment]
@Fr3DBr Also, ensure that you can reproduce the problem using the latest OpenResty 1.11.2.3 release without any components that are not maintained by either the official nginx team or the official openresty team. We do not want to support your custom build of nginx, really, since it's so easy to screw things up that way for a normal user.

**Comment by Fr3DBr** [comment]
@agentzh I'm using stock openresty... not even http2 is enabled yet, although I'm planning to use it.
By the way, the code I'm using is exactly like yours, but I cannot do it using content_by_lua_block, because I want to rewrite/redirect the user in specific conditions, hence why rewrite_by_lua and yes, I'm covering "all locations" not only / or /t as in your example. So "any" request received by nginx in "any" location, is processed by my code block, but the current test is against "/" location of course.

**Comment by agentzh** [comment]
@Fr3DBr You were not listening. I said you could make any necessary changes to my example so long as the issue is reproducible. I cannot guess what your configuration is. That's not helpful. I won't repeat it here.

**Comment by Fr3DBr** [comment]
@agentzh I understand, but when I have to backup an existing variable, because writting to the other one causes it to get corrupted, I don't think it could be related to my configuration... Anyways, I will try the new version and report it for you.

**Comment by agentzh** [comment]
@Fr3DBr Well, the thing is if we cannot reproduce the issue on my side, we cannot really do any investigations or fixes. We are not gods :) The info you have provided so far is not sufficient for us. That's why I've been asking you for a standalone and minimal example. But sadly you keep ignoring it.

**Comment by Fr3DBr** [comment]
@agentzh I had updated my answer in Github, but it seems it didn't save it, but yes, I will try to minimize it in a basic environment to see what happens.

**Comment by Fr3DBr** [comment]
@agentzh Just updating openresty, didn't make any difference. I make the isolated test a bit later and let you know what happens.

**Comment by Fr3DBr** [comment]
I deleted all the obj files and performed a full clean rebuild of latest version and the problem has been fixed. 👍
