### ISSUE TITLE
Is it possible to return the only first response of multiple subrequests running in parallel?

### ISSUE THREAD

**Issue by djskl** [openresty/lua-nginx-module#964]
how to response immediately after one of multiple subrequests running in parallel finish?

**Comment by spacewander** [comment]
First of all, please join the openresty mailing list to ask general questions.
This issue tracker is only for bug report.

Maybe you can use `ngx.thread.wait` to solve the problem:
```lua
local capture = ngx.location.capture
local spawn = ngx.thread.spawn
local wait = ngx.thread.wait
local say = ngx.say

local function fetch(uri)
  return capture(uri)
end

local threads = {
  spawn(fetch, "/1"),
  spawn(fetch, "/2"),
  spawn(fetch, "/3")
}

local ok, res = wait(unpack(threads))
if not ok then
    say("failed to run: ", res)
else
    say("res.body: ", res.body)
end
```

**Comment by djskl** [comment]
Thanks very much for your answer! 

-- I wanted to delete it yesterday, but didn't find how to do. Sorry for it.
