### ISSUE TITLE
build fail on tengine 2.2.0 with 0.10.7

### ISSUE THREAD

**Issue by xuecai** [openresty/lua-nginx-module#970]
tengine 2.2.0 base nginx 1.8.1
build succ with 0.10.6 but fail on 0.10.7.
maybe use new features on nginx version newer than version 1.8?

**Comment by agentzh** [comment]
@xuecai Tengine is *not* an officially supported target of this module. You should ask the Tengine team instead.

**Comment by xuecai** [comment]
also build fail on nginx 1.8.1
/usr/local/src/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c
/usr/local/src/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c: In function ‘ngx_http_lua_shared_memory_init’:
/usr/local/src/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179:9: error: ‘ngx_shm_zone_t’ has no member named ‘noreuse’
     zone->noreuse = shm_zone->noreuse;
         ^
/usr/local/src/lua-nginx-module-0.10.7/src/ngx_http_lua_api.c:179:29: error: ‘ngx_shm_zone_t’ has no member named ‘noreuse’
     zone->noreuse = shm_zone->noreuse;
                             ^
make[1]: *** [objs/addon/src/ngx_http_lua_api.o] Error 1
make[1]: Leaving directory `/usr/local/src/nginx-1.8.1'
make: *** [build] Error 2

**Comment by agentzh** [comment]
@xuecai Why don't you use the latest nginx 1.10.x stable series or the 1.11.x mainline series? 1.8.x is in "end of life".

**Comment by agentzh** [comment]
@xuecai Or better, just use the official OpenResty release. Although the official nginx core is our officially supported target, it never fully passes this module's test suite due to long standing bugs and limitations in the official nginx core.

**Comment by xuecai** [comment]
@agentzh , sorry for the issus, i see it fix in https://github.com/openresty/lua-nginx-module/commit/5e59e8c897c4256dc14bdd7f1b2f0b8d090a9434
btw, i can't decide whether to use nginx or Tengine in the production environment, i would also like to use the new version.

**Comment by agentzh** [comment]
@xuecai I think I've already made my recommendation above.

**Comment by xuecai** [comment]
@agentzh  Thank you. I've got it.
