### ISSUE TITLE
ngix.exit Terminate connection in access_by_lua

### ISSUE THREAD

**Issue by dmurali123** [openresty/lua-nginx-module#977]
Hi all,
I am writing a lua script for downloading a file with authentication. In access_by_lua_file I'm calling an API by using lua http resty and getting response, If the response status is 200 I have to allow for downloading the requested file, Otherwise I should terminate the connection. In header_filter_by_lua_file I'm setting all the headers for downloading a file.
**nginx.conf**
 ```
location /download {
        access_by_lua_file "/etc/nginx/luaFiles/auth.lua";
        header_filter_by_lua_file "/etc/nginx/luaFiles/header.lua";
                alias "/uploads/";
        }
```

**access_by_lua_file: auth.lua**
In this file i'm calling an API, if status code return by api is not equal to 200 then I should terminate the connection without allowing the file to download. Here I'm using ngx.exit with the status code to terminate the connection. But connection is not terminated it's still going in to the header_filter_by_lua_file.
```
if res then
    if res.status==200 then
    ngx.status=res.status
    return
    end
    if res.status~=200 then
    ngx.status=res.status
    ngx.say("error code :",res.status)
    return ngx.exit(res.status)
    end
else
    ngx.status=500
    ngx.say("failed to request: ",err)
    ngx.exit(500)
end
```

please help me to terminate the connection without going into header_filter_by_lua_file.

**Comment by detailyang** [comment]
Hello.

@dmurali123 

`header_filter_by_lua` is working on the phase of nginx output chain. So you have to enter the phase. But you can just pass the status of authorization by ctx to this phase. For example:

```bash
                access_by_lua_block {
                        if ngx.status ~= 200 then
                           ngx.ctx.auth = false
                        else
                            ngx.ctx.auth = true
                        end
                }

                header_filter_by_lua_block {
                        if ngx.ctx.auth == false then 
                              -- do what you want to do on failure
                        else
                              -- do what you want to do on success
                        end
                }
```

**Comment by agentzh** [comment]
@dmurali123 The correct way of terminating connections immediately is to call `ngx.exit(444)`.

**Comment by dmurali123** [comment]
@agentzh but i need to terminate with status code given by an upstream API.

**Comment by dmurali123** [comment]
@detailyang thank you so much for your quick response.It worked for me.
