### ISSUE TITLE
ngx.req.raw_header() err http v2 not supported yet

### ISSUE THREAD

**Issue by cntaoyu** [openresty/lua-nginx-module#979]
when i use `ngx.print(ngx.req.raw_header())`

not support http2?

2017/02/08 09:39:04 [error] 9681#0: *41 lua entry thread aborted: runtime error: /home/taoyu/web/index.lua:63: http v2 not supported yet
stack traceback:
coroutine 0:
	[C]: in function 'raw_header'
	/home/rainwsy/web/index.lua:63: in function </home/taoyu/web/index.lua:1>, client: 119.98.107.52, server: taoyu.me, request: "GET / HTTP/2.0", host: "taoyu.me"

**Comment by spacewander** [comment]
https://github.com/openresty/lua-nginx-module#ngxreqraw_header
The HTTP/2 support of `ngx.raw_header` is still on TODO list.
