### ISSUE TITLE
Subrequests in background light threads (timer.at)

### ISSUE THREAD

**Issue by myfreeweb** [openresty/lua-nginx-module#983]
Currently, subrequests in background light threads (timer.at) are not supported. This is really sad. To e.g. push a message to an nchan channel from a background thread that listens to Postgres notification, I currently have to use a [full HTTP client](https://github.com/pintsized/lua-resty-http) to call into an nginx endpoint, which adds overhead and flaky configuration (have to know the port).

There is an old module called [nginx-independent-subrequest](https://github.com/srlindsay/nginx-independent-subrequest) that creates a fake request to make subrequests from. I wonder if ngx_lua could do the same thing in timers?

**Comment by agentzh** [comment]
@myfreeweb Subrequests make no sense there since background light threads have no nginx requests attached to them, obviously.

The "independent subrequest" thing is really a hack. Libraries based on the ngx_lua cosocket API is the future. The lua-resty-http library you are using, for example, have a lot of room of optimizations.

**Comment by myfreeweb** [comment]
But it's a great hack! It allows making requests fully in-process, without touching TCP or Unix sockets. Since HTTP request handlers is the only API offered by native nginx modules (e.g. nchan), there should be a way to make calls to these modules without OS level sockets.

**Comment by agentzh** [comment]
@myfreeweb Without OS level sockets? How can that be possible without using the OS kernel's TCP/IP stack? Do you actually know about those nginx C modules are working?

ngx_lua's cosocket uses exactly the same nginx socket API layer which is also atop the OS level socket API anyway.

**Comment by myfreeweb** [comment]
By [creating nginx's internal objects that represent a fake connection](https://github.com/srlindsay/nginx-independent-subrequest/blob/master/src/fake_request.c) of course. No cosocket, just `location.capture` without a real request coming in.

**Comment by agentzh** [comment]
@myfreeweb Nope, fake connections can be very quirky under the complicated subrequest model. Also, cosockets can be much more efficient than `ngx.location.capture*` since it's possible to do streaming processing in the former.

**Comment by agentzh** [comment]
@myfreeweb BTW, if you don't believe what I'm saying here. Then there's no need to continue this fruitless conversation.
