### ISSUE TITLE
"ngx.var.binary_remote_addr" is an empty value at "content_by_lua" phase?

### ISSUE THREAD

**Issue by wangchunpeng** [openresty/lua-nginx-module#986]
the " ngx.var.binary_remote_addr" returns an empty value in my lua code,  which is called at "content_by_lua" phase,  while "ngx.var.remote_addr" returns an expected value.

is there any limitation to use " ngx.var.binary_remote_addr" ?

**Comment by moonbingbing** [comment]
Do you have the smallest reproduce code?  It works on my side. 
Please note `ngx.var.binary_remote_addr` is a binary data, which can not print directly, you can print the json encoded result.

**Comment by wangchunpeng** [comment]
@moonbingbing  It is indeed my fault, I just printed the result directly using "ngx.log" , and took it as a Lua-Number type data as granted. when I converted the data using "string.byte", it woked !!!
