### ISSUE TITLE
Removing duplicate headers with different case does not work

### ISSUE THREAD

**Issue by danihodovic** [openresty/lua-nginx-module#992]
## Problem
I have two response headers set by my backend. They have the same name, but are cased differently. `My-Header` and `my-header`. I'm trying to use the `header_filter_by_lua_block` to remove the duplicates.

Backend configuration
```
  server {
    listen 5555;
    location / {
      add_header my-header 'test';
      add_header My-Header 'test';
      return 200 'Success\n ';
    }
  }
```

### Solution 1: remove the lowercase header by assigning it `nil`

```
  server {
    header_filter_by_lua_block {
      -- Let's remove the duplicate header
      ngx.header['my-header'] = nil
    }

    proxy_pass http://localhost:5555;
  }
```
Result: Both headers are removed. Presumably because the assignment is case-insensitive.

### Solution 2: assign both headers to one header
``` 
  server {
    header_filter_by_lua_block {
      ngx.header['My-Header'] = ngx.header['My-Header']
    }

    proxy_pass http://localhost:5555
  }
```
Result: Both headers are still returned.

```
$ curl -v localhost:80
...
< my-header: test
< My-Header: test
```

### Solution 3: do a step-by-step assignment
``` 
  server {
    header_filter_by_lua_block {
      -- Store the header value
      header_value = ngx.header['My-Header']
      -- Clear the header
      ngx.header['my-header'] = nil
      -- Set it again
      ngx.header['My-Header'] = header_value
    }

    proxy_pass http://localhost:5555
  }
```
Result: Duplicate headers again. This time in uppercase
```
$ curl -v localhost:80
...
< My-Header: test
< My-Header: test
```

### Hack: Use a hardcoded value
``` 
  server {
    header_filter_by_lua_block {
      -- Store the header value
      header_value = ngx.header['My-Header']
      -- Clear the header
      ngx.header['my-header'] = nil
      -- Set it again
      ngx.header['My-Header'] = 'non-dynamic-value'
    }

    proxy_pass http://localhost:5555
  }
```
Result: ??? No duplicate headers if a hardcoded value is used.
```
$ curl -v localhost:80
...
< My-Header: non-dynamic-value
```

Edit:

### Solution 4. If the response header value is a table, only set one value in the table...
``` 
  server {
    header_filter_by_lua_block {
      local value = ngx.header.my_header
      ngx.header.my_header = nil
      ngx.header['My-Header'] = value[1]
    }

    proxy_pass http://localhost:5555
  }
```
Result: Strangely, it seems to work.
```
$ curl -v localhost:80
...
< My-Header: test
```

## Details
OS: Ubuntu 14:04
OpenResty version: v1.11.2.2

### Edit: Update

It seems like I had another block in the `access_by_lua` phase which set the header too. So `access_by_lua` would set the headers, the backend would set the headers and I'd have a table of headers in `header_filter_by_lua`. It's still strange that you can't remove duplicate upper/lowercase headers.

**Comment by agentzh** [comment]
@danihodovic I don't see any bugs here. Everything works as expected. Note that `ngx.header[NAME]` will return a Lua table holding values for *all* the headers of the name `NAME`. And when you set this Lua table back to `ngx.header[NAME]` again, it will surely re-install all those duplicate headers but with the unified `NAME` header name.

**Comment by danihodovic** [comment]
Ok thanks
