### ISSUE TITLE
Question: How is it possible to set response headers before reaching the backend?

### ISSUE THREAD

**Issue by danihodovic** [openresty/lua-nginx-module#996]
Looking at the following picture you can notice that the `access_by_lua` phase happens before reaching the upstream. The directive `ngx.header.<header>` sets response headers and is usable from the `access_by_lua` phase. 

Questions:
- How is it possible to set response headers **before** the upstream has created a response? Shouldn't the `ngx.header.<header>` directive only be available **after** the upstream has generated the response?
- If I set a header in `access_by_lua`, will the same header be available for the upstream server? Or is it set after the upstream server has generated a response?

![Picture](https://cloud.githubusercontent.com/assets/2137369/15272097/77d1c09e-1a37-11e6-97ef-d9767035fc3e.png)

Example
```
  server {
    access_by_lua_block {
      ngx.header['foo'] = 'foo'
    }

    location / {
      proxy_pass http://nodejs;
    }
  }
```

**Comment by spacewander** [comment]
For the first question:
Response header is a part of `ngx_http_request_t`, referred to:
https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.h#L389
So once Nginx create a request struct, there is already room for it.

And set the response header in `access_by_lua` is useful sometimes. Let's look at this example:
```
access_by_lua_block {
        ngx.header['response'] = 'header'
        ngx.exit(ngx.HTTP_FORBIDDEN)
}
```
```
☁  openresty  curl -i localhost:6699/1
HTTP/1.1 403 Forbidden
Server: openresty/1.11.2.2
Date: Sat, 18 Feb 2017 08:30:33 GMT
Content-Type: text/html
Content-Length: 175
Connection: keep-alive
response: header

<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.11.2.2</center>
</body>
</html>
```

For the second one:
The upstream can override the response header.
Let's show you another example:
```
access_by_lua_block {
        ngx.header['response'] = 'header'
}
content_by_lua_block {
        ngx.header['response'] = 'another-header'
}
```

```
☁  openresty  curl -i localhost:6699/1
HTTP/1.1 200 OK
Server: openresty/1.11.2.2
Date: Sat, 18 Feb 2017 08:28:30 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
response: another-header
```

**Comment by danihodovic** [comment]
Got it, thanks.
