### ISSUE TITLE
Cosocket support in init_worker_by_lua_*

### ISSUE THREAD

**Issue by xytis** [openresty/lua-nginx-module#998]
Documentation lists that it is possible to support cosockets in init sequences.
I am writing a [lua balancer implementation](https://github.com/xytis/lua-consul-balancer#known-issues), and my code would benefit from removal of that constrain.

Could someone do that?

**Comment by agentzh** [comment]
@xytis You can use a 0-delay timer via `ngx.socket.at()` in the `init_worker_by_lua*` context since cosockets are available in the timer handler context.

For a related matter, we're gonna add cosocket support to the `init_by_lua*` context very soon.

**Comment by agentzh** [comment]
There is no plan to add cosockets directly to the worker since the use of cosockets in the `init_by_lua*` context is much more useful in practice.
